import Foundation
import MLCompute

func testExecutionOptionsBits() {
    precondition(MLCExecutionOptions.skipWritingInputDataToDevice.rawValue == 1)
    precondition(MLCExecutionOptions.synchronous.rawValue == 2)
    precondition(MLCExecutionOptions.profiling.rawValue == 4)
    precondition(MLCExecutionOptions.forwardForInference.rawValue == 8)
    precondition(MLCExecutionOptions.perLayerProfiling.rawValue == 16)
    var options = MLCExecutionOptions()
    precondition(options.isEmpty)
    precondition(options.rawValue == 0)
    options.formUnion(.synchronous)
    precondition(options.contains(.synchronous))
    options.formIntersection([.synchronous, .profiling])
    precondition(options == .synchronous)
    options.formSymmetricDifference(.profiling)
    precondition(options.contains(.profiling))
    let unioned = MLCExecutionOptions.synchronous.union(.profiling)
    precondition(unioned.contains(.synchronous) && unioned.contains(.profiling))
    let intersected = unioned.intersection(.synchronous)
    precondition(intersected == .synchronous)
    let subtracted = unioned.subtracting(.profiling)
    precondition(subtracted == .synchronous)
    var mutating = unioned
    mutating.subtract(.synchronous)
    precondition(mutating == .profiling)
    precondition(unioned.symmetricDifference(.profiling) == .synchronous)
    precondition(unioned.isSuperset(of: .synchronous))
    precondition(unioned.isSubset(of: [.synchronous, .profiling, .perLayerProfiling]))
    precondition(!unioned.isStrictSubset(of: .synchronous))
    precondition(unioned.isStrictSuperset(of: .synchronous))
    precondition(MLCExecutionOptions.synchronous.isDisjoint(with: .profiling))
    var insertTarget = MLCExecutionOptions.synchronous
    let inserted = insertTarget.insert(.profiling)
    precondition(inserted.inserted)
    let removed = insertTarget.remove(.profiling)
    precondition(removed == .profiling)
    let updated = insertTarget.update(with: .profiling)
    precondition(updated == nil || updated != nil)
    let fromSequence = MLCExecutionOptions([.synchronous, .profiling])
    precondition(fromSequence.contains(.synchronous))
    let literal: MLCExecutionOptions = [.synchronous, .forwardForInference]
    precondition(literal.contains(.forwardForInference))
    precondition(MLCExecutionOptions.synchronous != .profiling)
}

func testGraphCompilationOptionsBits() {
    precondition(MLCGraphCompilationOptions.debugLayers.rawValue == 1)
    precondition(MLCGraphCompilationOptions.disableLayerFusion.rawValue == 2)
    precondition(MLCGraphCompilationOptions.linkGraphs.rawValue == 4)
    precondition(MLCGraphCompilationOptions.computeAllGradients.rawValue == 8)
    var options = MLCGraphCompilationOptions()
    precondition(options.isEmpty)
    options.formUnion(.debugLayers)
    precondition(options.contains(.debugLayers))
    options.formIntersection([.debugLayers, .linkGraphs])
    precondition(options == .debugLayers)
    options.formSymmetricDifference(.disableLayerFusion)
    let unioned = MLCGraphCompilationOptions.debugLayers.union(.linkGraphs)
    precondition(unioned.contains(.linkGraphs))
    precondition(unioned.intersection(.debugLayers) == .debugLayers)
    precondition(unioned.subtracting(.linkGraphs) == .debugLayers)
    var mutating = unioned
    mutating.subtract(.debugLayers)
    precondition(mutating == .linkGraphs)
    precondition(unioned.symmetricDifference(.linkGraphs) == .debugLayers)
    precondition(unioned.isSuperset(of: .debugLayers))
    precondition(unioned.isSubset(of: [.debugLayers, .linkGraphs, .computeAllGradients]))
    precondition(unioned.isStrictSuperset(of: .debugLayers))
    precondition(!unioned.isStrictSubset(of: .debugLayers))
    precondition(MLCGraphCompilationOptions.debugLayers.isDisjoint(with: .linkGraphs))
    var insertTarget = MLCGraphCompilationOptions.debugLayers
    precondition(insertTarget.insert(.linkGraphs).inserted)
    precondition(insertTarget.remove(.linkGraphs) == .linkGraphs)
    _ = insertTarget.update(with: .computeAllGradients)
    let fromSequence = MLCGraphCompilationOptions([.debugLayers, .disableLayerFusion])
    precondition(fromSequence.contains(.disableLayerFusion))
    let literal: MLCGraphCompilationOptions = [.linkGraphs]
    precondition(literal.contains(.linkGraphs))
    precondition(MLCGraphCompilationOptions.debugLayers != .linkGraphs)
    precondition(MLCGraphCompilationOptions(rawValue: 1) == .debugLayers)
}
