/*
 * mach/processor_set.h -- machorun's clean-room stand-in for MIG output.
 *
 * NOT Apple's header, and not MIG's either.  Apple's copy carries no licence
 * block because nobody wrote it: it is generated by MIG from
 * xnu:osfmk/mach/processor_set.defs, which IS published -- but running MIG means porting
 * a Mach-specific code generator to Linux.  docs/SDK_SURVEY.md §2.3 measured
 * the alternative and recommended it: the ten MIG headers declare 237 routines
 * between them, the whole test corpus links against 10 Mach symbols, and
 * objc4's source names 6.  So these are hand-written, exactly as
 * vendor/objc4-priv/ already is for 25 Apple SPI headers.
 *
 * THE RULE FOR THIS FILE: it declares a routine only if
 * darwin/usr/lib/libSystem.B.dylib EXPORTS it.  A Mach routine we have not
 * implemented is absent, so calling it is an undeclared-identifier error at
 * compile time rather than a missing symbol at load time -- loud aborts over
 * silent stubs, and scripts/gen_tbd.sh keeps the two sides honest.
 *
 * WHAT THIS OMITS versus MIG's output: the MIG message structs
 * (__Request__*_t / __Reply__*_t), the *_MSG_COUNT constants, the AUTOTEST
 * function tables, and every routine we do not implement.  Nothing that omits
 * is ABI: the structs are the on-the-wire form of a Mach RPC, and machorun
 * does not do Mach RPC -- darwin/src/mach.c services these calls directly.
 */

#ifndef _mach_processor_set_user_
#define _mach_processor_set_user_

#include <mach/std_types.h>
#include <mach/mach_types.h>
#include <sys/cdefs.h>

/* Nothing here: darwin/src/mach.c implements no processor_set routine, so by this
 * file's rule it declares none.  The file exists because
 * <mach/mach_interface.h> -- which IS xnu's own and vendored -- includes it. */

#endif /* _mach_processor_set_user_ */
