/*
 * mach/vm_map.h -- machorun's clean-room stand-in for MIG output.
 *
 * NOT Apple's header, and not MIG's either.  Apple's copy carries no licence
 * block because nobody wrote it: it is generated by MIG from
 * xnu:osfmk/mach/vm_map.defs, which IS published -- but running MIG means porting
 * a Mach-specific code generator to Linux.  docs/SDK_SURVEY.md §2.3 measured
 * the alternative and recommended it: the ten MIG headers declare 237 routines
 * between them, the whole test corpus links against 10 Mach symbols, and
 * objc4's source names 6.  So these are hand-written, exactly as
 * vendor/objc4-priv/ already is for 25 Apple SPI headers.
 *
 * THE RULE FOR THIS FILE: it declares a routine only if
 * darwin/usr/lib/libSystem.B.dylib EXPORTS it.  A Mach routine we have not
 * implemented is absent, so calling it is an undeclared-identifier error at
 * compile time rather than a missing symbol at load time -- loud aborts over
 * silent stubs, and scripts/gen_tbd.sh keeps the two sides honest.
 *
 * WHAT THIS OMITS versus MIG's output: the MIG message structs
 * (__Request__*_t / __Reply__*_t), the *_MSG_COUNT constants, the AUTOTEST
 * function tables, and every routine we do not implement.  Nothing that omits
 * is ABI: the structs are the on-the-wire form of a Mach RPC, and machorun
 * does not do Mach RPC -- darwin/src/mach.c services these calls directly.
 */

#ifndef _mach_vm_map_user_
#define _mach_vm_map_user_

#include <mach/std_types.h>
#include <mach/mach_types.h>
#include <mach/vm_prot.h>
#include <mach/vm_inherit.h>
#include <mach/vm_region.h>
#include <mach/memory_object_types.h>
#include <sys/cdefs.h>

__BEGIN_DECLS

/* All implemented in darwin/src/mach.c, on mmap/mprotect/munmap. */
extern kern_return_t vm_allocate(vm_map_t target_task,
                                 vm_address_t *address,
                                 vm_size_t size,
                                 int flags);

extern kern_return_t vm_deallocate(vm_map_t target_task,
                                   vm_address_t address,
                                   vm_size_t size);

extern kern_return_t vm_protect(vm_map_t target_task,
                                vm_address_t address,
                                vm_size_t size,
                                boolean_t set_maximum,
                                vm_prot_t new_protection);

/* MEASURED against macOS, not read off a summary: no page-alignment
 * requirement on address or size, memmove semantics on overlap, and an
 * unmapped/PROT_NONE/read-only region gives KERN_INVALID_ADDRESS rather than
 * KERN_PROTECTION_FAILURE. tests/src/vm_copy.c is the measurement. */
extern kern_return_t vm_copy(vm_map_t target_task,
                             vm_address_t source_address,
                             vm_size_t size,
                             vm_address_t dest_address);

extern kern_return_t vm_remap(vm_map_t target_task,
                              vm_address_t *target_address,
                              vm_size_t size,
                              vm_address_t mask,
                              int flags,
                              vm_map_t src_task,
                              vm_address_t src_address,
                              boolean_t copy,
                              vm_prot_t *cur_protection,
                              vm_prot_t *max_protection,
                              vm_inherit_t inheritance);

__END_DECLS

#endif /* _mach_vm_map_user_ */
