#!/bin/bash
# Generate darwin/src/rune_table.h from macOS's own _DefaultRuneLocale.
#
# WHY THIS IS DATA AND NOT CODE: Darwin's <ctype.h> does not call isdigit(), it
# INLINES a table lookup into the guest --
#
#   #define __isctype(c, f) \
#       ((c < 0 || c >= 256) ? __maskrune(c, f) : (_DefaultRuneLocale.__runetype[c] & (f)))
#
# so `_DefaultRuneLocale` is a data symbol whose 3208-byte layout, and whose
# contents, are compiled into every guest that includes <ctype.h>. Getting the
# bytes from Apple rather than reconstructing them from the POSIX spec is the
# difference between "isupper agrees" and "isupper agrees for the characters we
# thought to check".
#
# The C-locale table has no pointers set (verified: __sgetrune, __sputrune,
# every __ranges pointer and __variable are all NULL), so it reproduces exactly
# as static data with no relocation.
#
#   scripts/gen_rune_table.sh          # macOS only
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/darwin/src/rune_table.h"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

[ "$(uname -s)" = "Darwin" ] || { echo "gen_rune_table.sh: Apple's table lives on macOS" >&2; exit 64; }

cat > "$WORK/probe.c" <<'EOF'
#include <stdio.h>
#include <stddef.h>
#include <runetype.h>
#include <ctype.h>
#include <stdlib.h>
int main(void) {
    const _RuneLocale *r = &_DefaultRuneLocale;
    /* Refuse to emit a table we cannot reproduce as static data. */
    if (r->__sgetrune || r->__sputrune || r->__variable ||
        r->__runetype_ext.__nranges || r->__maplower_ext.__nranges ||
        r->__mapupper_ext.__nranges) {
        fprintf(stderr, "the default rune locale is no longer pointer-free\n");
        return 1;
    }
    printf("# sizeof %zu magic %zu encoding %zu invalid %zu runetype %zu maplower %zu mapupper %zu\n",
           sizeof(_RuneLocale), offsetof(_RuneLocale, __magic),
           offsetof(_RuneLocale, __encoding), offsetof(_RuneLocale, __invalid_rune),
           offsetof(_RuneLocale, __runetype), offsetof(_RuneLocale, __maplower),
           offsetof(_RuneLocale, __mapupper));
    printf("# magic %.8s encoding %s invalid %d mbcurmax %d cached %d\n",
           r->__magic, r->__encoding, r->__invalid_rune, (int)MB_CUR_MAX, _CACHED_RUNES);
    /* The flag bits the inlined ctype macros AND-with. Taken from Apple's
     * headers rather than deduced from the table, which would be a guess. */
#define F(n) printf("FLAG %s 0x%08lx\n", #n, (unsigned long)n)
    F(_CTYPE_A); F(_CTYPE_C); F(_CTYPE_D); F(_CTYPE_G); F(_CTYPE_L); F(_CTYPE_P);
    F(_CTYPE_S); F(_CTYPE_U); F(_CTYPE_X); F(_CTYPE_B); F(_CTYPE_R); F(_CTYPE_I);
    F(_CTYPE_T); F(_CTYPE_Q); F(_CTYPE_SW0); F(_CTYPE_SW1); F(_CTYPE_SW2); F(_CTYPE_SW3);
    for (int i = 0; i < _CACHED_RUNES; i++) printf("RT %u\n", r->__runetype[i]);
    for (int i = 0; i < _CACHED_RUNES; i++) printf("ML %d\n", r->__maplower[i]);
    for (int i = 0; i < _CACHED_RUNES; i++) printf("MU %d\n", r->__mapupper[i]);
    return 0;
}
EOF

xcrun clang -O1 -o "$WORK/probe" "$WORK/probe.c"
"$WORK/probe" > "$WORK/dump"

python3 - "$WORK/dump" "$OUT" <<'PY'
import sys, datetime, platform
lines = open(sys.argv[1]).read().splitlines()
meta = dict()
head = lines[0].split()
meta['sizeof'] = int(head[2])
for k, i in (('magic',4),('encoding',6),('invalid',8),('runetype',10),('maplower',12),('mapupper',14)):
    meta[k] = int(head[i])
info = lines[1].split()
magic, encoding, invalid, mbcurmax, cached = info[2], info[4], int(info[6]), int(info[8]), int(info[10])

def col(tag):
    return [int(l.split()[1]) for l in lines if l.startswith(tag + " ")]
rt, ml, mu = col("RT"), col("ML"), col("MU")
assert len(rt) == len(ml) == len(mu) == cached

flags = [l.split()[1:] for l in lines if l.startswith("FLAG ")]

def rows(vals, per, fmt="%u"):
    """A backslash-continued initialiser list, so the struct can be
    statically initialised -- no constructor, nothing to order."""
    out = []
    for i in range(0, len(vals), per):
        out.append("    " + " ".join((fmt + ",") % v for v in vals[i:i+per]))
    return " \\\n".join(out)

open(sys.argv[2], "w").write('''/* rune_table.h -- GENERATED by scripts/gen_rune_table.sh. Do not edit.
 *
 * Apple's own _DefaultRuneLocale, recorded from macOS %s on %s.
 * Darwin's <ctype.h> inlines `_DefaultRuneLocale.__runetype[c] & flag` into the
 * guest, so this is not our table to design: it is a data ABI the guest was
 * compiled against.
 *
 * Layout, measured: sizeof %d, __magic @%d, __encoding @%d, __invalid_rune @%d,
 * __runetype @%d, __maplower @%d, __mapupper @%d, %d cached runes.
 * magic "%s", encoding "%s", invalid rune %d, MB_CUR_MAX %d.
 */
#ifndef MACHORUN_RUNE_TABLE_H
#define MACHORUN_RUNE_TABLE_H

#define MR_CACHED_RUNES %d
#define MR_INVALID_RUNE %d
#define MR_MB_CUR_MAX   %d

/* The bits the guest's inlined <ctype.h> macros AND with __runetype[c]. */
%s

#define MR_RUNETYPE_INIT \
%s

#define MR_MAPLOWER_INIT \
%s

#define MR_MAPUPPER_INIT \
%s

#endif
''' % (platform.mac_ver()[0], datetime.date.today().isoformat(),
       meta['sizeof'], meta['magic'], meta['encoding'], meta['invalid'],
       meta['runetype'], meta['maplower'], meta['mapupper'], cached,
       magic, encoding, invalid, mbcurmax,
       cached, invalid, mbcurmax,
       "\n".join("#define MR%-12s %s" % (n, v) for n, v in flags),
       rows(rt, 8, "0x%08x"), rows(ml, 12, "%d"), rows(mu, 12, "%d")))
print("wrote %s: %d cached runes" % (sys.argv[2], cached))
PY
