import GSS

func testGSSStatusCodes() {
    gssRequire(GSS_S_COMPLETE == 0, "COMPLETE")
    gssRequire(GSS_S_BAD_MECH == 1 << 16, "BAD_MECH")
    gssRequire(GSS_S_BAD_NAME == 2 << 16, "BAD_NAME")
    gssRequire(GSS_S_BAD_NAMETYPE == 3 << 16, "BAD_NAMETYPE")
    gssRequire(GSS_S_BAD_BINDINGS == 4 << 16, "BAD_BINDINGS")
    gssRequire(GSS_S_BAD_STATUS == 5 << 16, "BAD_STATUS")
    gssRequire(GSS_S_BAD_SIG == 6 << 16, "BAD_SIG")
    gssRequire(GSS_S_BAD_MIC == GSS_S_BAD_SIG, "BAD_MIC alias")
    gssRequire(GSS_S_NO_CRED == 7 << 16, "NO_CRED")
    gssRequire(GSS_S_NO_CONTEXT == 8 << 16, "NO_CONTEXT")
    gssRequire(GSS_S_DEFECTIVE_TOKEN == 9 << 16, "DEFECTIVE_TOKEN")
    gssRequire(GSS_S_DEFECTIVE_CREDENTIAL == 10 << 16, "DEFECTIVE_CREDENTIAL")
    gssRequire(GSS_S_CREDENTIALS_EXPIRED == 11 << 16, "CREDENTIALS_EXPIRED")
    gssRequire(GSS_S_CONTEXT_EXPIRED == 12 << 16, "CONTEXT_EXPIRED")
    gssRequire(GSS_S_FAILURE == 13 << 16, "FAILURE")
    gssRequire(GSS_S_BAD_QOP == 14 << 16, "BAD_QOP")
    gssRequire(GSS_S_UNAUTHORIZED == 15 << 16, "UNAUTHORIZED")
    gssRequire(GSS_S_UNAVAILABLE == 16 << 16, "UNAVAILABLE")
    gssRequire(GSS_S_DUPLICATE_ELEMENT == 17 << 16, "DUPLICATE_ELEMENT")
    gssRequire(GSS_S_NAME_NOT_MN == 18 << 16, "NAME_NOT_MN")
    gssRequire(GSS_S_BAD_MECH_ATTR == 19 << 16, "BAD_MECH_ATTR")
    gssRequire(GSS_S_CRED_UNAVAIL == GSS_S_FAILURE, "CRED_UNAVAIL alias")
    gssRequire(GSS_S_CALL_INACCESSIBLE_READ == 1 << 24, "CALL_INACCESSIBLE_READ")
    gssRequire(GSS_S_CALL_INACCESSIBLE_WRITE == 2 << 24, "CALL_INACCESSIBLE_WRITE")
    gssRequire(GSS_S_CALL_BAD_STRUCTURE == 3 << 24, "CALL_BAD_STRUCTURE")
}

func testGSSCallingMasksAndOffsets() {
    gssRequire(GSS_C_CALLING_ERROR_OFFSET == 24, "calling offset")
    gssRequire(GSS_C_ROUTINE_ERROR_OFFSET == 16, "routine offset")
    gssRequire(GSS_C_SUPPLEMENTARY_OFFSET == 0, "supplementary offset")
    gssRequire(GSS_C_CALLING_ERROR_MASK == 0o377, "calling mask")
    gssRequire(GSS_C_ROUTINE_ERROR_MASK == 0o377, "routine mask")
    gssRequire(GSS_C_SUPPLEMENTARY_MASK == 0o177777, "supplementary mask")
}

func testGSSContextFlags() {
    gssRequire(GSS_C_DELEG_FLAG == 1, "DELEG")
    gssRequire(GSS_C_MUTUAL_FLAG == 2, "MUTUAL")
    gssRequire(GSS_C_REPLAY_FLAG == 4, "REPLAY")
    gssRequire(GSS_C_SEQUENCE_FLAG == 8, "SEQUENCE")
    gssRequire(GSS_C_CONF_FLAG == 16, "CONF")
    gssRequire(GSS_C_INTEG_FLAG == 32, "INTEG")
    gssRequire(GSS_C_ANON_FLAG == 64, "ANON")
    gssRequire(GSS_C_PROT_READY_FLAG == 128, "PROT_READY")
    gssRequire(GSS_C_TRANS_FLAG == 256, "TRANS")
    gssRequire(GSS_C_DCE_STYLE == 4096, "DCE_STYLE")
    gssRequire(GSS_C_IDENTIFY_FLAG == 8192, "IDENTIFY")
    gssRequire(GSS_C_EXTENDED_ERROR_FLAG == 16384, "EXTENDED_ERROR")
    gssRequire(GSS_C_DELEG_POLICY_FLAG == 32768, "DELEG_POLICY")
}

func testGSSUsageAndQOP() {
    gssRequire(GSS_C_BOTH == 0, "BOTH")
    gssRequire(GSS_C_INITIATE == 1, "INITIATE")
    gssRequire(GSS_C_ACCEPT == 2, "ACCEPT")
    gssRequire(GSS_C_GSS_CODE == 1, "GSS_CODE")
    gssRequire(GSS_C_MECH_CODE == 2, "MECH_CODE")
    gssRequire(GSS_C_QOP_DEFAULT == 0, "QOP_DEFAULT")
    gssRequire(GSS_KRB5_CONF_C_QOP_DES == 0x0100, "QOP_DES")
    gssRequire(GSS_KRB5_CONF_C_QOP_DES3_KD == 0x0200, "QOP_DES3")
    gssRequire(GSS_C_INDEFINITE == 0xffff_ffff, "INDEFINITE")
    gssRequire(GSS_C_OPTION_MASK == 0xffff, "OPTION_MASK")
    gssRequire(GSS_C_CRED_NO_UI == 0x1_0000, "CRED_NO_UI")
    gssRequire(GSS_C_PRF_KEY_FULL == 0, "PRF_FULL")
    gssRequire(GSS_C_PRF_KEY_PARTIAL == 1, "PRF_PARTIAL")
}

func testGSSAddressFamilies() {
    gssRequire(GSS_C_AF_UNSPEC == 0, "UNSPEC")
    gssRequire(GSS_C_AF_LOCAL == 1, "LOCAL")
    gssRequire(GSS_C_AF_INET == 2, "INET")
    gssRequire(GSS_C_AF_IMPLINK == 3, "IMPLINK")
    gssRequire(GSS_C_AF_PUP == 4, "PUP")
    gssRequire(GSS_C_AF_CHAOS == 5, "CHAOS")
    gssRequire(GSS_C_AF_NS == 6, "NS")
    gssRequire(GSS_C_AF_NBS == 7, "NBS")
    gssRequire(GSS_C_AF_ECMA == 8, "ECMA")
    gssRequire(GSS_C_AF_DATAKIT == 9, "DATAKIT")
    gssRequire(GSS_C_AF_CCITT == 10, "CCITT")
    gssRequire(GSS_C_AF_SNA == 11, "SNA")
    gssRequire(GSS_C_AF_DECnet == 12, "DECnet")
    gssRequire(GSS_C_AF_DLI == 13, "DLI")
    gssRequire(GSS_C_AF_LAT == 14, "LAT")
    gssRequire(GSS_C_AF_HYLINK == 15, "HYLINK")
    gssRequire(GSS_C_AF_APPLETALK == 16, "APPLETALK")
    gssRequire(GSS_C_AF_BSC == 17, "BSC")
    gssRequire(GSS_C_AF_DSS == 18, "DSS")
    gssRequire(GSS_C_AF_OSI == 19, "OSI")
    gssRequire(GSS_C_AF_X25 == 21, "X25")
    gssRequire(GSS_C_AF_INET6 == 24, "INET6")
    gssRequire(GSS_C_AF_NULLADDR == 255, "NULLADDR")
}

func testGSSIOVConstants() {
    gssRequire(GSS_IOV_BUFFER_TYPE_EMPTY == 0, "EMPTY")
    gssRequire(GSS_IOV_BUFFER_TYPE_DATA == 1, "DATA")
    gssRequire(GSS_IOV_BUFFER_TYPE_HEADER == 2, "HEADER")
    gssRequire(GSS_IOV_BUFFER_TYPE_MECH_PARAMS == 3, "MECH_PARAMS")
    gssRequire(GSS_IOV_BUFFER_TYPE_TRAILER == 7, "TRAILER")
    gssRequire(GSS_IOV_BUFFER_TYPE_PADDING == 9, "PADDING")
    gssRequire(GSS_IOV_BUFFER_TYPE_STREAM == 10, "STREAM")
    gssRequire(GSS_IOV_BUFFER_TYPE_SIGN_ONLY == 11, "SIGN_ONLY")
    gssRequire(GSS_IOV_BUFFER_TYPE_FLAG_MASK == 0xffff_0000, "FLAG_MASK")
    gssRequire(GSS_IOV_BUFFER_FLAG_ALLOCATE == 0x0001_0000, "ALLOCATE")
    gssRequire(GSS_IOV_BUFFER_FLAG_ALLOCATED == 0x0002_0000, "ALLOCATED")
    gssRequire(GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATE == GSS_IOV_BUFFER_FLAG_ALLOCATE, "TYPE_ALLOCATE")
    gssRequire(GSS_IOV_BUFFER_TYPE_FLAG_ALLOCATED == GSS_IOV_BUFFER_FLAG_ALLOCATED, "TYPE_ALLOCATED")
}

func testGSSAppleDictionaryKeys() {
    gssRequire(kGSSICPassword == "kGSSICPassword", "password")
    gssRequire(kGSSICCertificate == "kGSSICCertificate", "certificate")
    gssRequire(kGSSICVerifyCredential == "kGSSICVerifyCredential", "verify")
    gssRequire(kGSSCredentialUsage == "kGSSCredentialUsage", "usage")
    gssRequire(kGSS_C_INITIATE == "kGSS_C_INITIATE", "k initiate")
    gssRequire(kGSS_C_ACCEPT == "kGSS_C_ACCEPT", "k accept")
    gssRequire(kGSS_C_BOTH == "kGSS_C_BOTH", "k both")
    gssRequire(kGSSICLKDCHostname == "kGSSICLKDCHostname", "lkdc")
    gssRequire(kGSSICKerberosCacheName == "kGSSICKerberosCacheName", "ccache")
    gssRequire(kGSSICSiteName == "kGSSICSiteName", "site")
    gssRequire(kGSSICAppIdentifierACL == "kGSSICAppIdentifierACL", "acl")
    gssRequire(kGSSICVerifyCredentialAcceptorName == "kGSSICVerifyCredentialAcceptorName", "acceptor")
    gssRequire(kGSSICCreateNewCredential == "kGSSICCreateNewCredential", "create")
    gssRequire(kGSSICAppleSourceApp == "kGSSICAppleSourceApp", "source app")
    gssRequire(kGSSICAppleSourceAppAuditToken == "kGSSICAppleSourceAppAuditToken", "audit")
    gssRequire(kGSSICAppleSourceAppPID == "kGSSICAppleSourceAppPID", "pid")
    gssRequire(kGSSICAppleSourceAppSigningIdentity == "kGSSICAppleSourceAppSigningIdentity", "signing")
    gssRequire(kGSSICAuthenticationContext == "kGSSICAuthenticationContext", "authctx")
    gssRequire(kGSSChangePasswordOldPassword == "kGSSChangePasswordOldPassword", "old")
    gssRequire(kGSSChangePasswordNewPassword == "kGSSChangePasswordNewPassword", "new")
}
