// BreakProbe on REAL iOS: which REQUIRED constraint UIKit breaks when a
// system is unsatisfiable, and the frames that result.
//
// Why: Firefox Focus's URL bar (URLBar.swift) activates contradictory
// required constraints; the port broke different ones than iOS 26.1 and the
// editing field collapsed to 40 pt (docs/agent_reports/guest-interactive-2.md).
// The scenarios (scenarios.json, generated by gen_scenarios.py) add small
// conflicting systems in every order, both LIVE (the container is already in
// a laid-out window, so the engine exists while constraints are activated)
// and BULK (every constraint is installed first, then the container joins the
// window). UIKit's break decision is recorded at the source: UIView's
// engine:willBreakConstraint:dueToMutuallyExclusiveConstraints: (the method
// that logs "Will attempt to recover by breaking constraint") is wrapped to
// note the broken constraint, the exclusive set and the step being applied.
//
// Output: <Documents>/breakprobe.json then DONE. Run: scripts/break_probe_sim.sh
import UIKit
import ObjectiveC

let docsDir = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0]

nonisolated(unsafe) var tagOf: [ObjectIdentifier: String] = [:]
nonisolated(unsafe) var currentStep = -1
nonisolated(unsafe) var breaks: [[String: Any]] = []

func installBreakRecorder() {
    let sel = NSSelectorFromString("engine:willBreakConstraint:dueToMutuallyExclusiveConstraints:")
    let m = class_getInstanceMethod(UIView.self, sel)!
    typealias Orig = @convention(c) (AnyObject, Selector, AnyObject, NSLayoutConstraint, NSArray) -> Void
    let orig = unsafeBitCast(method_getImplementation(m), to: Orig.self)
    let block: @convention(block) (AnyObject, AnyObject, NSLayoutConstraint, NSArray) -> Void = { me, engine, broken, set in
        let tag = tagOf[ObjectIdentifier(broken)] ?? "?"
        let exclusive = (set as? [NSLayoutConstraint] ?? []).map { tagOf[ObjectIdentifier($0)] ?? "?" }
        breaks.append(["step": currentStep, "broken": tag, "exclusive": exclusive])
        orig(me, sel, engine, broken, set)
    }
    method_setImplementation(m, imp_implementationWithBlock(block))
}

func attribute(_ s: String?) -> NSLayoutConstraint.Attribute {
    switch s {
    case "leading": return .leading
    case "trailing": return .trailing
    case "left": return .left
    case "right": return .right
    case "top": return .top
    case "bottom": return .bottom
    case "width": return .width
    case "height": return .height
    case "centerX": return .centerX
    case "centerY": return .centerY
    default: return .notAnAttribute
    }
}

/// A view with a fixed intrinsicContentSize (the content-size constraints
/// UIKit derives from it are what the I* scenarios test).
final class IntrinsicView: UIView {
    var size = CGSize.zero
    override var intrinsicContentSize: CGSize { size }
}

func r3(_ v: CGFloat) -> Double { (Double(v) * 1000).rounded() / 1000 }

func run(_ s: [String: Any], root: UIView) -> [String: Any] {
    let c = UIView(frame: CGRect(x: 0, y: 0, width: 300, height: 300))
    var views: [String: UIView] = ["c": c]
    let intrinsic = (s["intrinsic"] as? [String: [NSNumber]]) ?? [:]
    for name in (s["viewCreate"] as? [String]) ?? (s["views"] as! [String]) {
        let v: UIView
        if let spec = intrinsic[name] {
            let k = IntrinsicView()
            k.size = CGSize(width: spec[0].doubleValue, height: spec[1].doubleValue)
            k.setContentHuggingPriority(UILayoutPriority(spec[2].floatValue), for: .horizontal)
            k.setContentCompressionResistancePriority(UILayoutPriority(spec[3].floatValue), for: .horizontal)
            v = k
        } else {
            v = UIView()
        }
        v.translatesAutoresizingMaskIntoConstraints = false
        views[name] = v
    }
    for name in (s["viewAdd"] as? [String]) ?? (s["views"] as! [String]) where name != "u" {
        c.addSubview(views[name]!)
    }
    if let u = views["u"] { views["v"]!.addSubview(u) }
    var cons: [String: NSLayoutConstraint] = [:]
    let specs = s["constraints"] as! [String: [Any]]
    for tag in s["create"] as! [String] {
        let spec = specs[tag]!
        let rel: NSLayoutConstraint.Relation = (spec[2] as! String) == "<=" ? .lessThanOrEqual
            : (spec[2] as! String) == ">=" ? .greaterThanOrEqual : .equal
        let second = (spec[3] as? String).map { views[$0]! }
        let k = NSLayoutConstraint(item: views[spec[0] as! String]!, attribute: attribute(spec[1] as? String),
                                   relatedBy: rel, toItem: second, attribute: attribute(spec[4] as? String),
                                   multiplier: CGFloat((spec[5] as! NSNumber).doubleValue),
                                   constant: CGFloat((spec[6] as! NSNumber).doubleValue))
        k.priority = UILayoutPriority(Float((spec[7] as! NSNumber).doubleValue))
        k.identifier = tag
        cons[tag] = k
        tagOf[ObjectIdentifier(k)] = tag
    }
    breaks = []
    let live = (s["mode"] as! String) == "live"
    if live { root.addSubview(c); root.layoutIfNeeded() }
    for (i, step) in (s["steps"] as! [String]).enumerated() {
        currentStep = i
        let k = cons[String(step.dropFirst())]!
        k.isActive = step.hasPrefix("+")
    }
    currentStep = -1
    if !live { root.addSubview(c) }
    root.layoutIfNeeded()
    var frames: [String: [Double]] = [:]
    for (name, v) in views where name != "c" {
        let f = v.frame
        frames[name] = [r3(f.origin.x), r3(f.origin.y), r3(f.width), r3(f.height)]
    }
    c.removeFromSuperview()
    return ["name": s["name"]!, "breaks": breaks, "frames": frames]
}

final class AppDelegate: NSObject, UIApplicationDelegate {
    var window: UIWindow?
    func application(_ app: UIApplication,
                     didFinishLaunchingWithOptions o: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        installBreakRecorder()
        let w = UIWindow(frame: UIScreen.main.bounds)
        window = w
        let vc = UIViewController()
        vc.view.backgroundColor = .white
        w.rootViewController = vc
        w.makeKeyAndVisible()
        let path = Bundle.main.path(forResource: "scenarios", ofType: "json")!
        let spec = try! JSONSerialization.jsonObject(with: Data(contentsOf: URL(fileURLWithPath: path))) as! [String: Any]
        let results = (spec["scenarios"] as! [[String: Any]]).map { run($0, root: vc.view) }
        let data = try! JSONSerialization.data(withJSONObject: ["results": results], options: [.sortedKeys, .prettyPrinted])
        try! data.write(to: URL(fileURLWithPath: "\(docsDir)/breakprobe.json"))
        try! "ok".write(toFile: docsDir + "/DONE", atomically: true, encoding: .utf8)
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) { exit(0) }
        return true
    }
}

UIApplicationMain(CommandLine.argc, CommandLine.unsafeArgv, nil, NSStringFromClass(AppDelegate.self))
