#!/bin/bash
# build_collections.sh -- the swift-collections modules FoundationEssentials
# actually depends on, as arm64-apple-macos Mach-O.
#
# NOT AN OPTIONAL EXTRA.  Package.swift:118-123 lists `_RopeModule` and
# `OrderedCollections` among FoundationEssentials' dependencies, and
# AttributedString is BUILT on _RopeModule's BigString -- 106 of the first
# whole-module run's error lines were "cannot find type 'BigString' in scope".
#
# Three modules, in dependency order:
#   InternalCollectionsUtilities  (hidden, both others depend on it)
#   OrderedCollections
#   _RopeModule                   (source directory is Sources/RopeModule --
#                                  target name and directory differ, and the
#                                  find below uses the DIRECTORY)
#
# swift-collections needs no special flags: its only build settings are
# `-D` defines, all of them commented out except COLLECTIONS_RANDOMIZED_TESTING
# which is for tests.  The `.gyb` templates are excluded by extension since we
# glob *.swift, and their generated outputs are checked in under autogenerated/.
set -euo pipefail
W=${W:-/w}
SC=${SC:-$W/scratch/swift-collections}
SYS=${SYS:-$W/scratch/sysroot_fe4}
OUT=${OUT:-$W/scratch/fe4_collections}
TARGET=${TARGET:-arm64-apple-macos15.0}
mkdir -p "$OUT"

build_one() {   # build_one <module-name> <source-dir>
    local mod=$1 dir=$2
    local srcs=()
    while IFS= read -r f; do srcs+=("$f"); done < <(find "$SC/Sources/$dir" -name '*.swift' | sort)
    echo "== $mod: ${#srcs[@]} files"
    swiftc -target "$TARGET" -sdk "$SYS" \
        -module-cache-path "$W/scratch/modcache_fe4" \
        -module-name "$mod" -wmo -parse-as-library \
        -runtime-compatibility-version none \
        -I "$OUT" \
        -emit-module -emit-module-path "$OUT/$mod.swiftmodule" \
        -c -o "$OUT/$mod.o" \
        "${srcs[@]}"
}

build_one InternalCollectionsUtilities InternalCollectionsUtilities
build_one OrderedCollections          OrderedCollections
build_one _RopeModule                 RopeModule
echo "== built:"; ls -l "$OUT"
