#!/bin/bash
# build_collections.sh -- the swift-collections modules FoundationEssentials
# actually depends on, as arm64-apple-macos Mach-O.
#
# NOT AN OPTIONAL EXTRA.  Package.swift:118-123 lists `_RopeModule` and
# `OrderedCollections` among FoundationEssentials' dependencies, and
# AttributedString is BUILT on _RopeModule's BigString -- 106 of the first
# whole-module run's error lines were "cannot find type 'BigString' in scope".
#
# Three modules, in dependency order:
#   InternalCollectionsUtilities  (hidden, both others depend on it)
#   OrderedCollections
#   _RopeModule                   (source directory is Sources/RopeModule --
#                                  target name and directory differ; the pinned
#                                  manifest group names that DIRECTORY)
#
# swift-collections needs no special flags: its only build settings are
# `-D` defines, all of them commented out except COLLECTIONS_RANDOMIZED_TESTING
# which is for tests. The pinned manifest selects `.swift` blobs, so `.gyb`
# templates are excluded and their generated outputs under autogenerated/ are
# the exact tracked compiler inputs.
set -euo pipefail
W=${W:-/w}
W=$(cd "$W" && pwd -P)
SC=${SC:-$W/scratch/swift-collections}
SYS=${SYS:-$W/scratch/sysroot_fe4}
OUT=${OUT:-$W/scratch/fe4_collections}
MC=${MC:-$W/scratch/modcache_fe4}
TARGET=${TARGET:-arm64-apple-macos15.0}
PINNED_INPUTS_TOOL=${PINNED_INPUTS_TOOL:-$W/full/foundation/pinned_inputs.pl}
[ -f "$PINNED_INPUTS_TOOL" ] || { echo "no pinned-input tool $PINNED_INPUTS_TOOL" >&2; exit 1; }
mkdir -p "$OUT" "$MC"
[ -d "$SYS" ] && SYS=$(realpath -P "$SYS")
[ -d "$SC" ] && SC=$(realpath -P "$SC")
OUT=$(realpath -P "$OUT")
MC=$(realpath -P "$MC" 2>/dev/null || readlink -f "$MC")

build_one() {   # build_one <module-name> <manifest-group> <expected-count>
    local mod=$1 group=$2 expected=$3
    local srcs=()
    local source_list
    source_list=$(perl "$PINNED_INPUTS_TOOL" list \
        --repository swift-collections --repo "$SC" --group "$group")
    while IFS= read -r f; do
        [ -n "$f" ] && srcs+=("$f")
    done <<<"$source_list"
    [ "${#srcs[@]}" -eq "$expected" ] || {
        echo "build_collections: pinned $mod manifest is not exactly $expected files" >&2
        exit 2
    }
    echo "== $mod: ${#srcs[@]} files"
    swiftc -target "$TARGET" -sdk "$SYS" \
        -module-cache-path "$MC" \
        -module-name "$mod" -wmo -parse-as-library \
        -runtime-compatibility-version none \
        -I "$OUT" \
        -emit-module -emit-module-path "$OUT/$mod.swiftmodule" \
        -c -o "$OUT/$mod.o" \
        "${srcs[@]}"
}

build_one InternalCollectionsUtilities collections-internal-utilities 18
build_one OrderedCollections          collections-ordered              61
build_one _RopeModule                 collections-rope                 76
echo "== built:"; ls -l "$OUT"
