// png_probe.swift -- isolates the isa-decode paths that machorun's image
// placement used to break. Every case is graded against native macOS.
protocol Backend: AnyObject { func v() -> Int32 }
final class ImplA: Backend { func v() -> Int32 { 3 } }

@_cdecl("p_existential") public func p_existential() -> Int32 {
    let b: Backend = ImplA()          // class-bound protocol existential
    let r = b.v()                     // witness dispatch
    return r                          // b released here
}
@_cdecl("p_plainclass") public func p_plainclass() -> Int32 {
    final class C { var x: Int32 = 5 }
    let c = C(); return c.x           // native class release -> swift_release
}
@_cdecl("p_arrayslice") public func p_arrayslice() -> Int32 {
    var arr: [UInt8] = []
    for i in 0..<32 { arr.append(UInt8(i)) }
    let s = arr[4..<20]
    var sum: Int32 = 0
    for b in s { sum &+= Int32(b) }
    return sum &+ Int32(s.count)      // 184 + 16 = 200
}
@_cdecl("p_string") public func p_string() -> Int32 {
    let s = "boxes" + "_basic"
    return Int32(s.count)             // 11
}

// --- bare AnyObject: the cheapest swift_unknownObject{Retain,Release} path ---
@_cdecl("p_anyobject") public func p_anyobject() -> Int32 {
    final class D { var y: Int32 = 7 }
    let o: AnyObject = D()            // unknown-object reference
    let d = o as! D
    return d.y                        // 7
}
// --- NON-class-bound existential (what CanvasBackend actually is) ---
protocol AnyBackend { func w() -> Int32 }
final class ImplB: AnyBackend { func w() -> Int32 { 13 } }
@_cdecl("p_anyexistential") public func p_anyexistential() -> Int32 {
    let b: AnyBackend = ImplB()       // not AnyObject-constrained -> boxed existential
    return b.w()                      // 13
}
// --- runtime-instantiated generic metadata over a USER type ---
final class Elem { var n: Int32; init(_ n: Int32) { self.n = n } }
@_cdecl("p_userarrayslice") public func p_userarrayslice() -> Int32 {
    var arr: [Elem] = []              // __ContiguousArrayStorage<Elem>: NOT prespecialized
    for i in 0..<10 { arr.append(Elem(Int32(i))) }
    let s = arr[2..<8]                // ArraySlice over user-class storage
    var sum: Int32 = 0
    for e in s { sum &+= e.n }
    return sum &+ Int32(s.count)      // 2+..+7 = 27, +6 = 33
}
final class Box<T> { var t: T; init(_ t: T) { self.t = t } }
@_cdecl("p_genericclass") public func p_genericclass() -> Int32 {
    let b = Box<Elem>(Elem(21))       // runtime-instantiated generic CLASS metadata
    let c = Box<Int32>(4)
    return b.t.n &+ c.t               // 25
}
// --- unowned: side-table path ---
final class Owner { var v: Int32 = 6 }
final class Holder { unowned let o: Owner; init(_ o: Owner) { self.o = o } }
@_cdecl("p_unowned") public func p_unowned() -> Int32 {
    let o = Owner(); let h = Holder(o)
    return h.o.v &* 3                 // 18
}

// --- the HEAP half of the isa/data-mask problem -------------------------------
// The other nine cases exercise class metadata that libswiftCore serves from
// its static InitialAllocationPool -- 64 KiB in __DATA, inside a mapped image,
// therefore always below the loader's 2^47 ceiling. That is why they pass even
// on a loader that places the HEAP badly: `genericclass` is one Box<T> and
// never comes close to the pool's limit.
//
// Past 64 KiB the allocator falls through to swift_slowAlloc -> malloc, and the
// metadata lands wherever the C heap is. This case forces that: 900 DISTINCT
// generic instantiations, each a separate metadata record, which measurably
// crosses the line. Distinct TYPES are what matters -- a loop over one Box<Int>
// allocates nothing after the first -- so the phantom type parameter is the
// mechanism, not decoration.
//
// It costs ~900 lines of IR and a second of compile time. That is the price of
// covering a bug the other nine cannot see.
struct P0 {}; struct P1 {}; struct P2 {}; struct P3 {}; struct P4 {}
struct P5 {}; struct P6 {}; struct P7 {}; struct P8 {}; struct P9 {}
struct Q0_0 {}
struct Q0_1 {}
struct Q0_2 {}
struct Q0_3 {}
struct Q0_4 {}
struct Q0_5 {}
struct Q0_6 {}
struct Q0_7 {}
struct Q0_8 {}
struct Q1_0 {}
struct Q1_1 {}
struct Q1_2 {}
struct Q1_3 {}
struct Q1_4 {}
struct Q1_5 {}
struct Q1_6 {}
struct Q1_7 {}
struct Q1_8 {}
struct Q2_0 {}
struct Q2_1 {}
struct Q2_2 {}
struct Q2_3 {}
struct Q2_4 {}
struct Q2_5 {}
struct Q2_6 {}
struct Q2_7 {}
struct Q2_8 {}
struct Q3_0 {}
struct Q3_1 {}
struct Q3_2 {}
struct Q3_3 {}
struct Q3_4 {}
struct Q3_5 {}
struct Q3_6 {}
struct Q3_7 {}
struct Q3_8 {}
struct Q4_0 {}
struct Q4_1 {}
struct Q4_2 {}
struct Q4_3 {}
struct Q4_4 {}
struct Q4_5 {}
struct Q4_6 {}
struct Q4_7 {}
struct Q4_8 {}
struct Q5_0 {}
struct Q5_1 {}
struct Q5_2 {}
struct Q5_3 {}
struct Q5_4 {}
struct Q5_5 {}
struct Q5_6 {}
struct Q5_7 {}
struct Q5_8 {}
struct Q6_0 {}
struct Q6_1 {}
struct Q6_2 {}
struct Q6_3 {}
struct Q6_4 {}
struct Q6_5 {}
struct Q6_6 {}
struct Q6_7 {}
struct Q6_8 {}
struct Q7_0 {}
struct Q7_1 {}
struct Q7_2 {}
struct Q7_3 {}
struct Q7_4 {}
struct Q7_5 {}
struct Q7_6 {}
struct Q7_7 {}
struct Q7_8 {}
struct Q8_0 {}
struct Q8_1 {}
struct Q8_2 {}
struct Q8_3 {}
struct Q8_4 {}
struct Q8_5 {}
struct Q8_6 {}
struct Q8_7 {}
struct Q8_8 {}
struct Q9_0 {}
struct Q9_1 {}
struct Q9_2 {}
struct Q9_3 {}
struct Q9_4 {}
struct Q9_5 {}
struct Q9_6 {}
struct Q9_7 {}
struct Q9_8 {}
final class Cell<T> { var n: Int32; init(_ n: Int32) { self.n = n } }
final class Pair<A, B> { var n: Int32; init(_ n: Int32) { self.n = n } }

@inline(never) func mk<A, B>(_ a: A.Type, _ b: B.Type, _ n: Int32) -> Int32 {
    Pair<A, B>(n).n &+ Cell<A>(n).n
}

@_cdecl("p_heapmetadata") public func p_heapmetadata() -> Int32 {
    var sum: Int32 = 0
    sum &+= mk(P0.self, Q0_0.self, 1)
    sum &+= mk(P0.self, Q0_1.self, 1)
    sum &+= mk(P0.self, Q0_2.self, 1)
    sum &+= mk(P0.self, Q0_3.self, 1)
    sum &+= mk(P0.self, Q0_4.self, 1)
    sum &+= mk(P0.self, Q0_5.self, 1)
    sum &+= mk(P0.self, Q0_6.self, 1)
    sum &+= mk(P0.self, Q0_7.self, 1)
    sum &+= mk(P0.self, Q0_8.self, 1)
    sum &+= mk(P0.self, Q1_0.self, 1)
    sum &+= mk(P0.self, Q1_1.self, 1)
    sum &+= mk(P0.self, Q1_2.self, 1)
    sum &+= mk(P0.self, Q1_3.self, 1)
    sum &+= mk(P0.self, Q1_4.self, 1)
    sum &+= mk(P0.self, Q1_5.self, 1)
    sum &+= mk(P0.self, Q1_6.self, 1)
    sum &+= mk(P0.self, Q1_7.self, 1)
    sum &+= mk(P0.self, Q1_8.self, 1)
    sum &+= mk(P0.self, Q2_0.self, 1)
    sum &+= mk(P0.self, Q2_1.self, 1)
    sum &+= mk(P0.self, Q2_2.self, 1)
    sum &+= mk(P0.self, Q2_3.self, 1)
    sum &+= mk(P0.self, Q2_4.self, 1)
    sum &+= mk(P0.self, Q2_5.self, 1)
    sum &+= mk(P0.self, Q2_6.self, 1)
    sum &+= mk(P0.self, Q2_7.self, 1)
    sum &+= mk(P0.self, Q2_8.self, 1)
    sum &+= mk(P0.self, Q3_0.self, 1)
    sum &+= mk(P0.self, Q3_1.self, 1)
    sum &+= mk(P0.self, Q3_2.self, 1)
    sum &+= mk(P0.self, Q3_3.self, 1)
    sum &+= mk(P0.self, Q3_4.self, 1)
    sum &+= mk(P0.self, Q3_5.self, 1)
    sum &+= mk(P0.self, Q3_6.self, 1)
    sum &+= mk(P0.self, Q3_7.self, 1)
    sum &+= mk(P0.self, Q3_8.self, 1)
    sum &+= mk(P0.self, Q4_0.self, 1)
    sum &+= mk(P0.self, Q4_1.self, 1)
    sum &+= mk(P0.self, Q4_2.self, 1)
    sum &+= mk(P0.self, Q4_3.self, 1)
    sum &+= mk(P0.self, Q4_4.self, 1)
    sum &+= mk(P0.self, Q4_5.self, 1)
    sum &+= mk(P0.self, Q4_6.self, 1)
    sum &+= mk(P0.self, Q4_7.self, 1)
    sum &+= mk(P0.self, Q4_8.self, 1)
    sum &+= mk(P0.self, Q5_0.self, 1)
    sum &+= mk(P0.self, Q5_1.self, 1)
    sum &+= mk(P0.self, Q5_2.self, 1)
    sum &+= mk(P0.self, Q5_3.self, 1)
    sum &+= mk(P0.self, Q5_4.self, 1)
    sum &+= mk(P0.self, Q5_5.self, 1)
    sum &+= mk(P0.self, Q5_6.self, 1)
    sum &+= mk(P0.self, Q5_7.self, 1)
    sum &+= mk(P0.self, Q5_8.self, 1)
    sum &+= mk(P0.self, Q6_0.self, 1)
    sum &+= mk(P0.self, Q6_1.self, 1)
    sum &+= mk(P0.self, Q6_2.self, 1)
    sum &+= mk(P0.self, Q6_3.self, 1)
    sum &+= mk(P0.self, Q6_4.self, 1)
    sum &+= mk(P0.self, Q6_5.self, 1)
    sum &+= mk(P0.self, Q6_6.self, 1)
    sum &+= mk(P0.self, Q6_7.self, 1)
    sum &+= mk(P0.self, Q6_8.self, 1)
    sum &+= mk(P0.self, Q7_0.self, 1)
    sum &+= mk(P0.self, Q7_1.self, 1)
    sum &+= mk(P0.self, Q7_2.self, 1)
    sum &+= mk(P0.self, Q7_3.self, 1)
    sum &+= mk(P0.self, Q7_4.self, 1)
    sum &+= mk(P0.self, Q7_5.self, 1)
    sum &+= mk(P0.self, Q7_6.self, 1)
    sum &+= mk(P0.self, Q7_7.self, 1)
    sum &+= mk(P0.self, Q7_8.self, 1)
    sum &+= mk(P0.self, Q8_0.self, 1)
    sum &+= mk(P0.self, Q8_1.self, 1)
    sum &+= mk(P0.self, Q8_2.self, 1)
    sum &+= mk(P0.self, Q8_3.self, 1)
    sum &+= mk(P0.self, Q8_4.self, 1)
    sum &+= mk(P0.self, Q8_5.self, 1)
    sum &+= mk(P0.self, Q8_6.self, 1)
    sum &+= mk(P0.self, Q8_7.self, 1)
    sum &+= mk(P0.self, Q8_8.self, 1)
    sum &+= mk(P0.self, Q9_0.self, 1)
    sum &+= mk(P0.self, Q9_1.self, 1)
    sum &+= mk(P0.self, Q9_2.self, 1)
    sum &+= mk(P0.self, Q9_3.self, 1)
    sum &+= mk(P0.self, Q9_4.self, 1)
    sum &+= mk(P0.self, Q9_5.self, 1)
    sum &+= mk(P0.self, Q9_6.self, 1)
    sum &+= mk(P0.self, Q9_7.self, 1)
    sum &+= mk(P0.self, Q9_8.self, 1)
    sum &+= mk(P1.self, Q0_0.self, 1)
    sum &+= mk(P1.self, Q0_1.self, 1)
    sum &+= mk(P1.self, Q0_2.self, 1)
    sum &+= mk(P1.self, Q0_3.self, 1)
    sum &+= mk(P1.self, Q0_4.self, 1)
    sum &+= mk(P1.self, Q0_5.self, 1)
    sum &+= mk(P1.self, Q0_6.self, 1)
    sum &+= mk(P1.self, Q0_7.self, 1)
    sum &+= mk(P1.self, Q0_8.self, 1)
    sum &+= mk(P1.self, Q1_0.self, 1)
    sum &+= mk(P1.self, Q1_1.self, 1)
    sum &+= mk(P1.self, Q1_2.self, 1)
    sum &+= mk(P1.self, Q1_3.self, 1)
    sum &+= mk(P1.self, Q1_4.self, 1)
    sum &+= mk(P1.self, Q1_5.self, 1)
    sum &+= mk(P1.self, Q1_6.self, 1)
    sum &+= mk(P1.self, Q1_7.self, 1)
    sum &+= mk(P1.self, Q1_8.self, 1)
    sum &+= mk(P1.self, Q2_0.self, 1)
    sum &+= mk(P1.self, Q2_1.self, 1)
    sum &+= mk(P1.self, Q2_2.self, 1)
    sum &+= mk(P1.self, Q2_3.self, 1)
    sum &+= mk(P1.self, Q2_4.self, 1)
    sum &+= mk(P1.self, Q2_5.self, 1)
    sum &+= mk(P1.self, Q2_6.self, 1)
    sum &+= mk(P1.self, Q2_7.self, 1)
    sum &+= mk(P1.self, Q2_8.self, 1)
    sum &+= mk(P1.self, Q3_0.self, 1)
    sum &+= mk(P1.self, Q3_1.self, 1)
    sum &+= mk(P1.self, Q3_2.self, 1)
    sum &+= mk(P1.self, Q3_3.self, 1)
    sum &+= mk(P1.self, Q3_4.self, 1)
    sum &+= mk(P1.self, Q3_5.self, 1)
    sum &+= mk(P1.self, Q3_6.self, 1)
    sum &+= mk(P1.self, Q3_7.self, 1)
    sum &+= mk(P1.self, Q3_8.self, 1)
    sum &+= mk(P1.self, Q4_0.self, 1)
    sum &+= mk(P1.self, Q4_1.self, 1)
    sum &+= mk(P1.self, Q4_2.self, 1)
    sum &+= mk(P1.self, Q4_3.self, 1)
    sum &+= mk(P1.self, Q4_4.self, 1)
    sum &+= mk(P1.self, Q4_5.self, 1)
    sum &+= mk(P1.self, Q4_6.self, 1)
    sum &+= mk(P1.self, Q4_7.self, 1)
    sum &+= mk(P1.self, Q4_8.self, 1)
    sum &+= mk(P1.self, Q5_0.self, 1)
    sum &+= mk(P1.self, Q5_1.self, 1)
    sum &+= mk(P1.self, Q5_2.self, 1)
    sum &+= mk(P1.self, Q5_3.self, 1)
    sum &+= mk(P1.self, Q5_4.self, 1)
    sum &+= mk(P1.self, Q5_5.self, 1)
    sum &+= mk(P1.self, Q5_6.self, 1)
    sum &+= mk(P1.self, Q5_7.self, 1)
    sum &+= mk(P1.self, Q5_8.self, 1)
    sum &+= mk(P1.self, Q6_0.self, 1)
    sum &+= mk(P1.self, Q6_1.self, 1)
    sum &+= mk(P1.self, Q6_2.self, 1)
    sum &+= mk(P1.self, Q6_3.self, 1)
    sum &+= mk(P1.self, Q6_4.self, 1)
    sum &+= mk(P1.self, Q6_5.self, 1)
    sum &+= mk(P1.self, Q6_6.self, 1)
    sum &+= mk(P1.self, Q6_7.self, 1)
    sum &+= mk(P1.self, Q6_8.self, 1)
    sum &+= mk(P1.self, Q7_0.self, 1)
    sum &+= mk(P1.self, Q7_1.self, 1)
    sum &+= mk(P1.self, Q7_2.self, 1)
    sum &+= mk(P1.self, Q7_3.self, 1)
    sum &+= mk(P1.self, Q7_4.self, 1)
    sum &+= mk(P1.self, Q7_5.self, 1)
    sum &+= mk(P1.self, Q7_6.self, 1)
    sum &+= mk(P1.self, Q7_7.self, 1)
    sum &+= mk(P1.self, Q7_8.self, 1)
    sum &+= mk(P1.self, Q8_0.self, 1)
    sum &+= mk(P1.self, Q8_1.self, 1)
    sum &+= mk(P1.self, Q8_2.self, 1)
    sum &+= mk(P1.self, Q8_3.self, 1)
    sum &+= mk(P1.self, Q8_4.self, 1)
    sum &+= mk(P1.self, Q8_5.self, 1)
    sum &+= mk(P1.self, Q8_6.self, 1)
    sum &+= mk(P1.self, Q8_7.self, 1)
    sum &+= mk(P1.self, Q8_8.self, 1)
    sum &+= mk(P1.self, Q9_0.self, 1)
    sum &+= mk(P1.self, Q9_1.self, 1)
    sum &+= mk(P1.self, Q9_2.self, 1)
    sum &+= mk(P1.self, Q9_3.self, 1)
    sum &+= mk(P1.self, Q9_4.self, 1)
    sum &+= mk(P1.self, Q9_5.self, 1)
    sum &+= mk(P1.self, Q9_6.self, 1)
    sum &+= mk(P1.self, Q9_7.self, 1)
    sum &+= mk(P1.self, Q9_8.self, 1)
    sum &+= mk(P2.self, Q0_0.self, 1)
    sum &+= mk(P2.self, Q0_1.self, 1)
    sum &+= mk(P2.self, Q0_2.self, 1)
    sum &+= mk(P2.self, Q0_3.self, 1)
    sum &+= mk(P2.self, Q0_4.self, 1)
    sum &+= mk(P2.self, Q0_5.self, 1)
    sum &+= mk(P2.self, Q0_6.self, 1)
    sum &+= mk(P2.self, Q0_7.self, 1)
    sum &+= mk(P2.self, Q0_8.self, 1)
    sum &+= mk(P2.self, Q1_0.self, 1)
    sum &+= mk(P2.self, Q1_1.self, 1)
    sum &+= mk(P2.self, Q1_2.self, 1)
    sum &+= mk(P2.self, Q1_3.self, 1)
    sum &+= mk(P2.self, Q1_4.self, 1)
    sum &+= mk(P2.self, Q1_5.self, 1)
    sum &+= mk(P2.self, Q1_6.self, 1)
    sum &+= mk(P2.self, Q1_7.self, 1)
    sum &+= mk(P2.self, Q1_8.self, 1)
    sum &+= mk(P2.self, Q2_0.self, 1)
    sum &+= mk(P2.self, Q2_1.self, 1)
    sum &+= mk(P2.self, Q2_2.self, 1)
    sum &+= mk(P2.self, Q2_3.self, 1)
    sum &+= mk(P2.self, Q2_4.self, 1)
    sum &+= mk(P2.self, Q2_5.self, 1)
    sum &+= mk(P2.self, Q2_6.self, 1)
    sum &+= mk(P2.self, Q2_7.self, 1)
    sum &+= mk(P2.self, Q2_8.self, 1)
    sum &+= mk(P2.self, Q3_0.self, 1)
    sum &+= mk(P2.self, Q3_1.self, 1)
    sum &+= mk(P2.self, Q3_2.self, 1)
    sum &+= mk(P2.self, Q3_3.self, 1)
    sum &+= mk(P2.self, Q3_4.self, 1)
    sum &+= mk(P2.self, Q3_5.self, 1)
    sum &+= mk(P2.self, Q3_6.self, 1)
    sum &+= mk(P2.self, Q3_7.self, 1)
    sum &+= mk(P2.self, Q3_8.self, 1)
    sum &+= mk(P2.self, Q4_0.self, 1)
    sum &+= mk(P2.self, Q4_1.self, 1)
    sum &+= mk(P2.self, Q4_2.self, 1)
    sum &+= mk(P2.self, Q4_3.self, 1)
    sum &+= mk(P2.self, Q4_4.self, 1)
    sum &+= mk(P2.self, Q4_5.self, 1)
    sum &+= mk(P2.self, Q4_6.self, 1)
    sum &+= mk(P2.self, Q4_7.self, 1)
    sum &+= mk(P2.self, Q4_8.self, 1)
    sum &+= mk(P2.self, Q5_0.self, 1)
    sum &+= mk(P2.self, Q5_1.self, 1)
    sum &+= mk(P2.self, Q5_2.self, 1)
    sum &+= mk(P2.self, Q5_3.self, 1)
    sum &+= mk(P2.self, Q5_4.self, 1)
    sum &+= mk(P2.self, Q5_5.self, 1)
    sum &+= mk(P2.self, Q5_6.self, 1)
    sum &+= mk(P2.self, Q5_7.self, 1)
    sum &+= mk(P2.self, Q5_8.self, 1)
    sum &+= mk(P2.self, Q6_0.self, 1)
    sum &+= mk(P2.self, Q6_1.self, 1)
    sum &+= mk(P2.self, Q6_2.self, 1)
    sum &+= mk(P2.self, Q6_3.self, 1)
    sum &+= mk(P2.self, Q6_4.self, 1)
    sum &+= mk(P2.self, Q6_5.self, 1)
    sum &+= mk(P2.self, Q6_6.self, 1)
    sum &+= mk(P2.self, Q6_7.self, 1)
    sum &+= mk(P2.self, Q6_8.self, 1)
    sum &+= mk(P2.self, Q7_0.self, 1)
    sum &+= mk(P2.self, Q7_1.self, 1)
    sum &+= mk(P2.self, Q7_2.self, 1)
    sum &+= mk(P2.self, Q7_3.self, 1)
    sum &+= mk(P2.self, Q7_4.self, 1)
    sum &+= mk(P2.self, Q7_5.self, 1)
    sum &+= mk(P2.self, Q7_6.self, 1)
    sum &+= mk(P2.self, Q7_7.self, 1)
    sum &+= mk(P2.self, Q7_8.self, 1)
    sum &+= mk(P2.self, Q8_0.self, 1)
    sum &+= mk(P2.self, Q8_1.self, 1)
    sum &+= mk(P2.self, Q8_2.self, 1)
    sum &+= mk(P2.self, Q8_3.self, 1)
    sum &+= mk(P2.self, Q8_4.self, 1)
    sum &+= mk(P2.self, Q8_5.self, 1)
    sum &+= mk(P2.self, Q8_6.self, 1)
    sum &+= mk(P2.self, Q8_7.self, 1)
    sum &+= mk(P2.self, Q8_8.self, 1)
    sum &+= mk(P2.self, Q9_0.self, 1)
    sum &+= mk(P2.self, Q9_1.self, 1)
    sum &+= mk(P2.self, Q9_2.self, 1)
    sum &+= mk(P2.self, Q9_3.self, 1)
    sum &+= mk(P2.self, Q9_4.self, 1)
    sum &+= mk(P2.self, Q9_5.self, 1)
    sum &+= mk(P2.self, Q9_6.self, 1)
    sum &+= mk(P2.self, Q9_7.self, 1)
    sum &+= mk(P2.self, Q9_8.self, 1)
    sum &+= mk(P3.self, Q0_0.self, 1)
    sum &+= mk(P3.self, Q0_1.self, 1)
    sum &+= mk(P3.self, Q0_2.self, 1)
    sum &+= mk(P3.self, Q0_3.self, 1)
    sum &+= mk(P3.self, Q0_4.self, 1)
    sum &+= mk(P3.self, Q0_5.self, 1)
    sum &+= mk(P3.self, Q0_6.self, 1)
    sum &+= mk(P3.self, Q0_7.self, 1)
    sum &+= mk(P3.self, Q0_8.self, 1)
    sum &+= mk(P3.self, Q1_0.self, 1)
    sum &+= mk(P3.self, Q1_1.self, 1)
    sum &+= mk(P3.self, Q1_2.self, 1)
    sum &+= mk(P3.self, Q1_3.self, 1)
    sum &+= mk(P3.self, Q1_4.self, 1)
    sum &+= mk(P3.self, Q1_5.self, 1)
    sum &+= mk(P3.self, Q1_6.self, 1)
    sum &+= mk(P3.self, Q1_7.self, 1)
    sum &+= mk(P3.self, Q1_8.self, 1)
    sum &+= mk(P3.self, Q2_0.self, 1)
    sum &+= mk(P3.self, Q2_1.self, 1)
    sum &+= mk(P3.self, Q2_2.self, 1)
    sum &+= mk(P3.self, Q2_3.self, 1)
    sum &+= mk(P3.self, Q2_4.self, 1)
    sum &+= mk(P3.self, Q2_5.self, 1)
    sum &+= mk(P3.self, Q2_6.self, 1)
    sum &+= mk(P3.self, Q2_7.self, 1)
    sum &+= mk(P3.self, Q2_8.self, 1)
    sum &+= mk(P3.self, Q3_0.self, 1)
    sum &+= mk(P3.self, Q3_1.self, 1)
    sum &+= mk(P3.self, Q3_2.self, 1)
    sum &+= mk(P3.self, Q3_3.self, 1)
    sum &+= mk(P3.self, Q3_4.self, 1)
    sum &+= mk(P3.self, Q3_5.self, 1)
    sum &+= mk(P3.self, Q3_6.self, 1)
    sum &+= mk(P3.self, Q3_7.self, 1)
    sum &+= mk(P3.self, Q3_8.self, 1)
    sum &+= mk(P3.self, Q4_0.self, 1)
    sum &+= mk(P3.self, Q4_1.self, 1)
    sum &+= mk(P3.self, Q4_2.self, 1)
    sum &+= mk(P3.self, Q4_3.self, 1)
    sum &+= mk(P3.self, Q4_4.self, 1)
    sum &+= mk(P3.self, Q4_5.self, 1)
    sum &+= mk(P3.self, Q4_6.self, 1)
    sum &+= mk(P3.self, Q4_7.self, 1)
    sum &+= mk(P3.self, Q4_8.self, 1)
    sum &+= mk(P3.self, Q5_0.self, 1)
    sum &+= mk(P3.self, Q5_1.self, 1)
    sum &+= mk(P3.self, Q5_2.self, 1)
    sum &+= mk(P3.self, Q5_3.self, 1)
    sum &+= mk(P3.self, Q5_4.self, 1)
    sum &+= mk(P3.self, Q5_5.self, 1)
    sum &+= mk(P3.self, Q5_6.self, 1)
    sum &+= mk(P3.self, Q5_7.self, 1)
    sum &+= mk(P3.self, Q5_8.self, 1)
    sum &+= mk(P3.self, Q6_0.self, 1)
    sum &+= mk(P3.self, Q6_1.self, 1)
    sum &+= mk(P3.self, Q6_2.self, 1)
    sum &+= mk(P3.self, Q6_3.self, 1)
    sum &+= mk(P3.self, Q6_4.self, 1)
    sum &+= mk(P3.self, Q6_5.self, 1)
    sum &+= mk(P3.self, Q6_6.self, 1)
    sum &+= mk(P3.self, Q6_7.self, 1)
    sum &+= mk(P3.self, Q6_8.self, 1)
    sum &+= mk(P3.self, Q7_0.self, 1)
    sum &+= mk(P3.self, Q7_1.self, 1)
    sum &+= mk(P3.self, Q7_2.self, 1)
    sum &+= mk(P3.self, Q7_3.self, 1)
    sum &+= mk(P3.self, Q7_4.self, 1)
    sum &+= mk(P3.self, Q7_5.self, 1)
    sum &+= mk(P3.self, Q7_6.self, 1)
    sum &+= mk(P3.self, Q7_7.self, 1)
    sum &+= mk(P3.self, Q7_8.self, 1)
    sum &+= mk(P3.self, Q8_0.self, 1)
    sum &+= mk(P3.self, Q8_1.self, 1)
    sum &+= mk(P3.self, Q8_2.self, 1)
    sum &+= mk(P3.self, Q8_3.self, 1)
    sum &+= mk(P3.self, Q8_4.self, 1)
    sum &+= mk(P3.self, Q8_5.self, 1)
    sum &+= mk(P3.self, Q8_6.self, 1)
    sum &+= mk(P3.self, Q8_7.self, 1)
    sum &+= mk(P3.self, Q8_8.self, 1)
    sum &+= mk(P3.self, Q9_0.self, 1)
    sum &+= mk(P3.self, Q9_1.self, 1)
    sum &+= mk(P3.self, Q9_2.self, 1)
    sum &+= mk(P3.self, Q9_3.self, 1)
    sum &+= mk(P3.self, Q9_4.self, 1)
    sum &+= mk(P3.self, Q9_5.self, 1)
    sum &+= mk(P3.self, Q9_6.self, 1)
    sum &+= mk(P3.self, Q9_7.self, 1)
    sum &+= mk(P3.self, Q9_8.self, 1)
    sum &+= mk(P4.self, Q0_0.self, 1)
    sum &+= mk(P4.self, Q0_1.self, 1)
    sum &+= mk(P4.self, Q0_2.self, 1)
    sum &+= mk(P4.self, Q0_3.self, 1)
    sum &+= mk(P4.self, Q0_4.self, 1)
    sum &+= mk(P4.self, Q0_5.self, 1)
    sum &+= mk(P4.self, Q0_6.self, 1)
    sum &+= mk(P4.self, Q0_7.self, 1)
    sum &+= mk(P4.self, Q0_8.self, 1)
    sum &+= mk(P4.self, Q1_0.self, 1)
    sum &+= mk(P4.self, Q1_1.self, 1)
    sum &+= mk(P4.self, Q1_2.self, 1)
    sum &+= mk(P4.self, Q1_3.self, 1)
    sum &+= mk(P4.self, Q1_4.self, 1)
    sum &+= mk(P4.self, Q1_5.self, 1)
    sum &+= mk(P4.self, Q1_6.self, 1)
    sum &+= mk(P4.self, Q1_7.self, 1)
    sum &+= mk(P4.self, Q1_8.self, 1)
    sum &+= mk(P4.self, Q2_0.self, 1)
    sum &+= mk(P4.self, Q2_1.self, 1)
    sum &+= mk(P4.self, Q2_2.self, 1)
    sum &+= mk(P4.self, Q2_3.self, 1)
    sum &+= mk(P4.self, Q2_4.self, 1)
    sum &+= mk(P4.self, Q2_5.self, 1)
    sum &+= mk(P4.self, Q2_6.self, 1)
    sum &+= mk(P4.self, Q2_7.self, 1)
    sum &+= mk(P4.self, Q2_8.self, 1)
    sum &+= mk(P4.self, Q3_0.self, 1)
    sum &+= mk(P4.self, Q3_1.self, 1)
    sum &+= mk(P4.self, Q3_2.self, 1)
    sum &+= mk(P4.self, Q3_3.self, 1)
    sum &+= mk(P4.self, Q3_4.self, 1)
    sum &+= mk(P4.self, Q3_5.self, 1)
    sum &+= mk(P4.self, Q3_6.self, 1)
    sum &+= mk(P4.self, Q3_7.self, 1)
    sum &+= mk(P4.self, Q3_8.self, 1)
    sum &+= mk(P4.self, Q4_0.self, 1)
    sum &+= mk(P4.self, Q4_1.self, 1)
    sum &+= mk(P4.self, Q4_2.self, 1)
    sum &+= mk(P4.self, Q4_3.self, 1)
    sum &+= mk(P4.self, Q4_4.self, 1)
    sum &+= mk(P4.self, Q4_5.self, 1)
    sum &+= mk(P4.self, Q4_6.self, 1)
    sum &+= mk(P4.self, Q4_7.self, 1)
    sum &+= mk(P4.self, Q4_8.self, 1)
    sum &+= mk(P4.self, Q5_0.self, 1)
    sum &+= mk(P4.self, Q5_1.self, 1)
    sum &+= mk(P4.self, Q5_2.self, 1)
    sum &+= mk(P4.self, Q5_3.self, 1)
    sum &+= mk(P4.self, Q5_4.self, 1)
    sum &+= mk(P4.self, Q5_5.self, 1)
    sum &+= mk(P4.self, Q5_6.self, 1)
    sum &+= mk(P4.self, Q5_7.self, 1)
    sum &+= mk(P4.self, Q5_8.self, 1)
    sum &+= mk(P4.self, Q6_0.self, 1)
    sum &+= mk(P4.self, Q6_1.self, 1)
    sum &+= mk(P4.self, Q6_2.self, 1)
    sum &+= mk(P4.self, Q6_3.self, 1)
    sum &+= mk(P4.self, Q6_4.self, 1)
    sum &+= mk(P4.self, Q6_5.self, 1)
    sum &+= mk(P4.self, Q6_6.self, 1)
    sum &+= mk(P4.self, Q6_7.self, 1)
    sum &+= mk(P4.self, Q6_8.self, 1)
    sum &+= mk(P4.self, Q7_0.self, 1)
    sum &+= mk(P4.self, Q7_1.self, 1)
    sum &+= mk(P4.self, Q7_2.self, 1)
    sum &+= mk(P4.self, Q7_3.self, 1)
    sum &+= mk(P4.self, Q7_4.self, 1)
    sum &+= mk(P4.self, Q7_5.self, 1)
    sum &+= mk(P4.self, Q7_6.self, 1)
    sum &+= mk(P4.self, Q7_7.self, 1)
    sum &+= mk(P4.self, Q7_8.self, 1)
    sum &+= mk(P4.self, Q8_0.self, 1)
    sum &+= mk(P4.self, Q8_1.self, 1)
    sum &+= mk(P4.self, Q8_2.self, 1)
    sum &+= mk(P4.self, Q8_3.self, 1)
    sum &+= mk(P4.self, Q8_4.self, 1)
    sum &+= mk(P4.self, Q8_5.self, 1)
    sum &+= mk(P4.self, Q8_6.self, 1)
    sum &+= mk(P4.self, Q8_7.self, 1)
    sum &+= mk(P4.self, Q8_8.self, 1)
    sum &+= mk(P4.self, Q9_0.self, 1)
    sum &+= mk(P4.self, Q9_1.self, 1)
    sum &+= mk(P4.self, Q9_2.self, 1)
    sum &+= mk(P4.self, Q9_3.self, 1)
    sum &+= mk(P4.self, Q9_4.self, 1)
    sum &+= mk(P4.self, Q9_5.self, 1)
    sum &+= mk(P4.self, Q9_6.self, 1)
    sum &+= mk(P4.self, Q9_7.self, 1)
    sum &+= mk(P4.self, Q9_8.self, 1)
    sum &+= mk(P5.self, Q0_0.self, 1)
    sum &+= mk(P5.self, Q0_1.self, 1)
    sum &+= mk(P5.self, Q0_2.self, 1)
    sum &+= mk(P5.self, Q0_3.self, 1)
    sum &+= mk(P5.self, Q0_4.self, 1)
    sum &+= mk(P5.self, Q0_5.self, 1)
    sum &+= mk(P5.self, Q0_6.self, 1)
    sum &+= mk(P5.self, Q0_7.self, 1)
    sum &+= mk(P5.self, Q0_8.self, 1)
    sum &+= mk(P5.self, Q1_0.self, 1)
    sum &+= mk(P5.self, Q1_1.self, 1)
    sum &+= mk(P5.self, Q1_2.self, 1)
    sum &+= mk(P5.self, Q1_3.self, 1)
    sum &+= mk(P5.self, Q1_4.self, 1)
    sum &+= mk(P5.self, Q1_5.self, 1)
    sum &+= mk(P5.self, Q1_6.self, 1)
    sum &+= mk(P5.self, Q1_7.self, 1)
    sum &+= mk(P5.self, Q1_8.self, 1)
    sum &+= mk(P5.self, Q2_0.self, 1)
    sum &+= mk(P5.self, Q2_1.self, 1)
    sum &+= mk(P5.self, Q2_2.self, 1)
    sum &+= mk(P5.self, Q2_3.self, 1)
    sum &+= mk(P5.self, Q2_4.self, 1)
    sum &+= mk(P5.self, Q2_5.self, 1)
    sum &+= mk(P5.self, Q2_6.self, 1)
    sum &+= mk(P5.self, Q2_7.self, 1)
    sum &+= mk(P5.self, Q2_8.self, 1)
    sum &+= mk(P5.self, Q3_0.self, 1)
    sum &+= mk(P5.self, Q3_1.self, 1)
    sum &+= mk(P5.self, Q3_2.self, 1)
    sum &+= mk(P5.self, Q3_3.self, 1)
    sum &+= mk(P5.self, Q3_4.self, 1)
    sum &+= mk(P5.self, Q3_5.self, 1)
    sum &+= mk(P5.self, Q3_6.self, 1)
    sum &+= mk(P5.self, Q3_7.self, 1)
    sum &+= mk(P5.self, Q3_8.self, 1)
    sum &+= mk(P5.self, Q4_0.self, 1)
    sum &+= mk(P5.self, Q4_1.self, 1)
    sum &+= mk(P5.self, Q4_2.self, 1)
    sum &+= mk(P5.self, Q4_3.self, 1)
    sum &+= mk(P5.self, Q4_4.self, 1)
    sum &+= mk(P5.self, Q4_5.self, 1)
    sum &+= mk(P5.self, Q4_6.self, 1)
    sum &+= mk(P5.self, Q4_7.self, 1)
    sum &+= mk(P5.self, Q4_8.self, 1)
    sum &+= mk(P5.self, Q5_0.self, 1)
    sum &+= mk(P5.self, Q5_1.self, 1)
    sum &+= mk(P5.self, Q5_2.self, 1)
    sum &+= mk(P5.self, Q5_3.self, 1)
    sum &+= mk(P5.self, Q5_4.self, 1)
    sum &+= mk(P5.self, Q5_5.self, 1)
    sum &+= mk(P5.self, Q5_6.self, 1)
    sum &+= mk(P5.self, Q5_7.self, 1)
    sum &+= mk(P5.self, Q5_8.self, 1)
    sum &+= mk(P5.self, Q6_0.self, 1)
    sum &+= mk(P5.self, Q6_1.self, 1)
    sum &+= mk(P5.self, Q6_2.self, 1)
    sum &+= mk(P5.self, Q6_3.self, 1)
    sum &+= mk(P5.self, Q6_4.self, 1)
    sum &+= mk(P5.self, Q6_5.self, 1)
    sum &+= mk(P5.self, Q6_6.self, 1)
    sum &+= mk(P5.self, Q6_7.self, 1)
    sum &+= mk(P5.self, Q6_8.self, 1)
    sum &+= mk(P5.self, Q7_0.self, 1)
    sum &+= mk(P5.self, Q7_1.self, 1)
    sum &+= mk(P5.self, Q7_2.self, 1)
    sum &+= mk(P5.self, Q7_3.self, 1)
    sum &+= mk(P5.self, Q7_4.self, 1)
    sum &+= mk(P5.self, Q7_5.self, 1)
    sum &+= mk(P5.self, Q7_6.self, 1)
    sum &+= mk(P5.self, Q7_7.self, 1)
    sum &+= mk(P5.self, Q7_8.self, 1)
    sum &+= mk(P5.self, Q8_0.self, 1)
    sum &+= mk(P5.self, Q8_1.self, 1)
    sum &+= mk(P5.self, Q8_2.self, 1)
    sum &+= mk(P5.self, Q8_3.self, 1)
    sum &+= mk(P5.self, Q8_4.self, 1)
    sum &+= mk(P5.self, Q8_5.self, 1)
    sum &+= mk(P5.self, Q8_6.self, 1)
    sum &+= mk(P5.self, Q8_7.self, 1)
    sum &+= mk(P5.self, Q8_8.self, 1)
    sum &+= mk(P5.self, Q9_0.self, 1)
    sum &+= mk(P5.self, Q9_1.self, 1)
    sum &+= mk(P5.self, Q9_2.self, 1)
    sum &+= mk(P5.self, Q9_3.self, 1)
    sum &+= mk(P5.self, Q9_4.self, 1)
    sum &+= mk(P5.self, Q9_5.self, 1)
    sum &+= mk(P5.self, Q9_6.self, 1)
    sum &+= mk(P5.self, Q9_7.self, 1)
    sum &+= mk(P5.self, Q9_8.self, 1)
    sum &+= mk(P6.self, Q0_0.self, 1)
    sum &+= mk(P6.self, Q0_1.self, 1)
    sum &+= mk(P6.self, Q0_2.self, 1)
    sum &+= mk(P6.self, Q0_3.self, 1)
    sum &+= mk(P6.self, Q0_4.self, 1)
    sum &+= mk(P6.self, Q0_5.self, 1)
    sum &+= mk(P6.self, Q0_6.self, 1)
    sum &+= mk(P6.self, Q0_7.self, 1)
    sum &+= mk(P6.self, Q0_8.self, 1)
    sum &+= mk(P6.self, Q1_0.self, 1)
    sum &+= mk(P6.self, Q1_1.self, 1)
    sum &+= mk(P6.self, Q1_2.self, 1)
    sum &+= mk(P6.self, Q1_3.self, 1)
    sum &+= mk(P6.self, Q1_4.self, 1)
    sum &+= mk(P6.self, Q1_5.self, 1)
    sum &+= mk(P6.self, Q1_6.self, 1)
    sum &+= mk(P6.self, Q1_7.self, 1)
    sum &+= mk(P6.self, Q1_8.self, 1)
    sum &+= mk(P6.self, Q2_0.self, 1)
    sum &+= mk(P6.self, Q2_1.self, 1)
    sum &+= mk(P6.self, Q2_2.self, 1)
    sum &+= mk(P6.self, Q2_3.self, 1)
    sum &+= mk(P6.self, Q2_4.self, 1)
    sum &+= mk(P6.self, Q2_5.self, 1)
    sum &+= mk(P6.self, Q2_6.self, 1)
    sum &+= mk(P6.self, Q2_7.self, 1)
    sum &+= mk(P6.self, Q2_8.self, 1)
    sum &+= mk(P6.self, Q3_0.self, 1)
    sum &+= mk(P6.self, Q3_1.self, 1)
    sum &+= mk(P6.self, Q3_2.self, 1)
    sum &+= mk(P6.self, Q3_3.self, 1)
    sum &+= mk(P6.self, Q3_4.self, 1)
    sum &+= mk(P6.self, Q3_5.self, 1)
    sum &+= mk(P6.self, Q3_6.self, 1)
    sum &+= mk(P6.self, Q3_7.self, 1)
    sum &+= mk(P6.self, Q3_8.self, 1)
    sum &+= mk(P6.self, Q4_0.self, 1)
    sum &+= mk(P6.self, Q4_1.self, 1)
    sum &+= mk(P6.self, Q4_2.self, 1)
    sum &+= mk(P6.self, Q4_3.self, 1)
    sum &+= mk(P6.self, Q4_4.self, 1)
    sum &+= mk(P6.self, Q4_5.self, 1)
    sum &+= mk(P6.self, Q4_6.self, 1)
    sum &+= mk(P6.self, Q4_7.self, 1)
    sum &+= mk(P6.self, Q4_8.self, 1)
    sum &+= mk(P6.self, Q5_0.self, 1)
    sum &+= mk(P6.self, Q5_1.self, 1)
    sum &+= mk(P6.self, Q5_2.self, 1)
    sum &+= mk(P6.self, Q5_3.self, 1)
    sum &+= mk(P6.self, Q5_4.self, 1)
    sum &+= mk(P6.self, Q5_5.self, 1)
    sum &+= mk(P6.self, Q5_6.self, 1)
    sum &+= mk(P6.self, Q5_7.self, 1)
    sum &+= mk(P6.self, Q5_8.self, 1)
    sum &+= mk(P6.self, Q6_0.self, 1)
    sum &+= mk(P6.self, Q6_1.self, 1)
    sum &+= mk(P6.self, Q6_2.self, 1)
    sum &+= mk(P6.self, Q6_3.self, 1)
    sum &+= mk(P6.self, Q6_4.self, 1)
    sum &+= mk(P6.self, Q6_5.self, 1)
    sum &+= mk(P6.self, Q6_6.self, 1)
    sum &+= mk(P6.self, Q6_7.self, 1)
    sum &+= mk(P6.self, Q6_8.self, 1)
    sum &+= mk(P6.self, Q7_0.self, 1)
    sum &+= mk(P6.self, Q7_1.self, 1)
    sum &+= mk(P6.self, Q7_2.self, 1)
    sum &+= mk(P6.self, Q7_3.self, 1)
    sum &+= mk(P6.self, Q7_4.self, 1)
    sum &+= mk(P6.self, Q7_5.self, 1)
    sum &+= mk(P6.self, Q7_6.self, 1)
    sum &+= mk(P6.self, Q7_7.self, 1)
    sum &+= mk(P6.self, Q7_8.self, 1)
    sum &+= mk(P6.self, Q8_0.self, 1)
    sum &+= mk(P6.self, Q8_1.self, 1)
    sum &+= mk(P6.self, Q8_2.self, 1)
    sum &+= mk(P6.self, Q8_3.self, 1)
    sum &+= mk(P6.self, Q8_4.self, 1)
    sum &+= mk(P6.self, Q8_5.self, 1)
    sum &+= mk(P6.self, Q8_6.self, 1)
    sum &+= mk(P6.self, Q8_7.self, 1)
    sum &+= mk(P6.self, Q8_8.self, 1)
    sum &+= mk(P6.self, Q9_0.self, 1)
    sum &+= mk(P6.self, Q9_1.self, 1)
    sum &+= mk(P6.self, Q9_2.self, 1)
    sum &+= mk(P6.self, Q9_3.self, 1)
    sum &+= mk(P6.self, Q9_4.self, 1)
    sum &+= mk(P6.self, Q9_5.self, 1)
    sum &+= mk(P6.self, Q9_6.self, 1)
    sum &+= mk(P6.self, Q9_7.self, 1)
    sum &+= mk(P6.self, Q9_8.self, 1)
    sum &+= mk(P7.self, Q0_0.self, 1)
    sum &+= mk(P7.self, Q0_1.self, 1)
    sum &+= mk(P7.self, Q0_2.self, 1)
    sum &+= mk(P7.self, Q0_3.self, 1)
    sum &+= mk(P7.self, Q0_4.self, 1)
    sum &+= mk(P7.self, Q0_5.self, 1)
    sum &+= mk(P7.self, Q0_6.self, 1)
    sum &+= mk(P7.self, Q0_7.self, 1)
    sum &+= mk(P7.self, Q0_8.self, 1)
    sum &+= mk(P7.self, Q1_0.self, 1)
    sum &+= mk(P7.self, Q1_1.self, 1)
    sum &+= mk(P7.self, Q1_2.self, 1)
    sum &+= mk(P7.self, Q1_3.self, 1)
    sum &+= mk(P7.self, Q1_4.self, 1)
    sum &+= mk(P7.self, Q1_5.self, 1)
    sum &+= mk(P7.self, Q1_6.self, 1)
    sum &+= mk(P7.self, Q1_7.self, 1)
    sum &+= mk(P7.self, Q1_8.self, 1)
    sum &+= mk(P7.self, Q2_0.self, 1)
    sum &+= mk(P7.self, Q2_1.self, 1)
    sum &+= mk(P7.self, Q2_2.self, 1)
    sum &+= mk(P7.self, Q2_3.self, 1)
    sum &+= mk(P7.self, Q2_4.self, 1)
    sum &+= mk(P7.self, Q2_5.self, 1)
    sum &+= mk(P7.self, Q2_6.self, 1)
    sum &+= mk(P7.self, Q2_7.self, 1)
    sum &+= mk(P7.self, Q2_8.self, 1)
    sum &+= mk(P7.self, Q3_0.self, 1)
    sum &+= mk(P7.self, Q3_1.self, 1)
    sum &+= mk(P7.self, Q3_2.self, 1)
    sum &+= mk(P7.self, Q3_3.self, 1)
    sum &+= mk(P7.self, Q3_4.self, 1)
    sum &+= mk(P7.self, Q3_5.self, 1)
    sum &+= mk(P7.self, Q3_6.self, 1)
    sum &+= mk(P7.self, Q3_7.self, 1)
    sum &+= mk(P7.self, Q3_8.self, 1)
    sum &+= mk(P7.self, Q4_0.self, 1)
    sum &+= mk(P7.self, Q4_1.self, 1)
    sum &+= mk(P7.self, Q4_2.self, 1)
    sum &+= mk(P7.self, Q4_3.self, 1)
    sum &+= mk(P7.self, Q4_4.self, 1)
    sum &+= mk(P7.self, Q4_5.self, 1)
    sum &+= mk(P7.self, Q4_6.self, 1)
    sum &+= mk(P7.self, Q4_7.self, 1)
    sum &+= mk(P7.self, Q4_8.self, 1)
    sum &+= mk(P7.self, Q5_0.self, 1)
    sum &+= mk(P7.self, Q5_1.self, 1)
    sum &+= mk(P7.self, Q5_2.self, 1)
    sum &+= mk(P7.self, Q5_3.self, 1)
    sum &+= mk(P7.self, Q5_4.self, 1)
    sum &+= mk(P7.self, Q5_5.self, 1)
    sum &+= mk(P7.self, Q5_6.self, 1)
    sum &+= mk(P7.self, Q5_7.self, 1)
    sum &+= mk(P7.self, Q5_8.self, 1)
    sum &+= mk(P7.self, Q6_0.self, 1)
    sum &+= mk(P7.self, Q6_1.self, 1)
    sum &+= mk(P7.self, Q6_2.self, 1)
    sum &+= mk(P7.self, Q6_3.self, 1)
    sum &+= mk(P7.self, Q6_4.self, 1)
    sum &+= mk(P7.self, Q6_5.self, 1)
    sum &+= mk(P7.self, Q6_6.self, 1)
    sum &+= mk(P7.self, Q6_7.self, 1)
    sum &+= mk(P7.self, Q6_8.self, 1)
    sum &+= mk(P7.self, Q7_0.self, 1)
    sum &+= mk(P7.self, Q7_1.self, 1)
    sum &+= mk(P7.self, Q7_2.self, 1)
    sum &+= mk(P7.self, Q7_3.self, 1)
    sum &+= mk(P7.self, Q7_4.self, 1)
    sum &+= mk(P7.self, Q7_5.self, 1)
    sum &+= mk(P7.self, Q7_6.self, 1)
    sum &+= mk(P7.self, Q7_7.self, 1)
    sum &+= mk(P7.self, Q7_8.self, 1)
    sum &+= mk(P7.self, Q8_0.self, 1)
    sum &+= mk(P7.self, Q8_1.self, 1)
    sum &+= mk(P7.self, Q8_2.self, 1)
    sum &+= mk(P7.self, Q8_3.self, 1)
    sum &+= mk(P7.self, Q8_4.self, 1)
    sum &+= mk(P7.self, Q8_5.self, 1)
    sum &+= mk(P7.self, Q8_6.self, 1)
    sum &+= mk(P7.self, Q8_7.self, 1)
    sum &+= mk(P7.self, Q8_8.self, 1)
    sum &+= mk(P7.self, Q9_0.self, 1)
    sum &+= mk(P7.self, Q9_1.self, 1)
    sum &+= mk(P7.self, Q9_2.self, 1)
    sum &+= mk(P7.self, Q9_3.self, 1)
    sum &+= mk(P7.self, Q9_4.self, 1)
    sum &+= mk(P7.self, Q9_5.self, 1)
    sum &+= mk(P7.self, Q9_6.self, 1)
    sum &+= mk(P7.self, Q9_7.self, 1)
    sum &+= mk(P7.self, Q9_8.self, 1)
    sum &+= mk(P8.self, Q0_0.self, 1)
    sum &+= mk(P8.self, Q0_1.self, 1)
    sum &+= mk(P8.self, Q0_2.self, 1)
    sum &+= mk(P8.self, Q0_3.self, 1)
    sum &+= mk(P8.self, Q0_4.self, 1)
    sum &+= mk(P8.self, Q0_5.self, 1)
    sum &+= mk(P8.self, Q0_6.self, 1)
    sum &+= mk(P8.self, Q0_7.self, 1)
    sum &+= mk(P8.self, Q0_8.self, 1)
    sum &+= mk(P8.self, Q1_0.self, 1)
    sum &+= mk(P8.self, Q1_1.self, 1)
    sum &+= mk(P8.self, Q1_2.self, 1)
    sum &+= mk(P8.self, Q1_3.self, 1)
    sum &+= mk(P8.self, Q1_4.self, 1)
    sum &+= mk(P8.self, Q1_5.self, 1)
    sum &+= mk(P8.self, Q1_6.self, 1)
    sum &+= mk(P8.self, Q1_7.self, 1)
    sum &+= mk(P8.self, Q1_8.self, 1)
    sum &+= mk(P8.self, Q2_0.self, 1)
    sum &+= mk(P8.self, Q2_1.self, 1)
    sum &+= mk(P8.self, Q2_2.self, 1)
    sum &+= mk(P8.self, Q2_3.self, 1)
    sum &+= mk(P8.self, Q2_4.self, 1)
    sum &+= mk(P8.self, Q2_5.self, 1)
    sum &+= mk(P8.self, Q2_6.self, 1)
    sum &+= mk(P8.self, Q2_7.self, 1)
    sum &+= mk(P8.self, Q2_8.self, 1)
    sum &+= mk(P8.self, Q3_0.self, 1)
    sum &+= mk(P8.self, Q3_1.self, 1)
    sum &+= mk(P8.self, Q3_2.self, 1)
    sum &+= mk(P8.self, Q3_3.self, 1)
    sum &+= mk(P8.self, Q3_4.self, 1)
    sum &+= mk(P8.self, Q3_5.self, 1)
    sum &+= mk(P8.self, Q3_6.self, 1)
    sum &+= mk(P8.self, Q3_7.self, 1)
    sum &+= mk(P8.self, Q3_8.self, 1)
    sum &+= mk(P8.self, Q4_0.self, 1)
    sum &+= mk(P8.self, Q4_1.self, 1)
    sum &+= mk(P8.self, Q4_2.self, 1)
    sum &+= mk(P8.self, Q4_3.self, 1)
    sum &+= mk(P8.self, Q4_4.self, 1)
    sum &+= mk(P8.self, Q4_5.self, 1)
    sum &+= mk(P8.self, Q4_6.self, 1)
    sum &+= mk(P8.self, Q4_7.self, 1)
    sum &+= mk(P8.self, Q4_8.self, 1)
    sum &+= mk(P8.self, Q5_0.self, 1)
    sum &+= mk(P8.self, Q5_1.self, 1)
    sum &+= mk(P8.self, Q5_2.self, 1)
    sum &+= mk(P8.self, Q5_3.self, 1)
    sum &+= mk(P8.self, Q5_4.self, 1)
    sum &+= mk(P8.self, Q5_5.self, 1)
    sum &+= mk(P8.self, Q5_6.self, 1)
    sum &+= mk(P8.self, Q5_7.self, 1)
    sum &+= mk(P8.self, Q5_8.self, 1)
    sum &+= mk(P8.self, Q6_0.self, 1)
    sum &+= mk(P8.self, Q6_1.self, 1)
    sum &+= mk(P8.self, Q6_2.self, 1)
    sum &+= mk(P8.self, Q6_3.self, 1)
    sum &+= mk(P8.self, Q6_4.self, 1)
    sum &+= mk(P8.self, Q6_5.self, 1)
    sum &+= mk(P8.self, Q6_6.self, 1)
    sum &+= mk(P8.self, Q6_7.self, 1)
    sum &+= mk(P8.self, Q6_8.self, 1)
    sum &+= mk(P8.self, Q7_0.self, 1)
    sum &+= mk(P8.self, Q7_1.self, 1)
    sum &+= mk(P8.self, Q7_2.self, 1)
    sum &+= mk(P8.self, Q7_3.self, 1)
    sum &+= mk(P8.self, Q7_4.self, 1)
    sum &+= mk(P8.self, Q7_5.self, 1)
    sum &+= mk(P8.self, Q7_6.self, 1)
    sum &+= mk(P8.self, Q7_7.self, 1)
    sum &+= mk(P8.self, Q7_8.self, 1)
    sum &+= mk(P8.self, Q8_0.self, 1)
    sum &+= mk(P8.self, Q8_1.self, 1)
    sum &+= mk(P8.self, Q8_2.self, 1)
    sum &+= mk(P8.self, Q8_3.self, 1)
    sum &+= mk(P8.self, Q8_4.self, 1)
    sum &+= mk(P8.self, Q8_5.self, 1)
    sum &+= mk(P8.self, Q8_6.self, 1)
    sum &+= mk(P8.self, Q8_7.self, 1)
    sum &+= mk(P8.self, Q8_8.self, 1)
    sum &+= mk(P8.self, Q9_0.self, 1)
    sum &+= mk(P8.self, Q9_1.self, 1)
    sum &+= mk(P8.self, Q9_2.self, 1)
    sum &+= mk(P8.self, Q9_3.self, 1)
    sum &+= mk(P8.self, Q9_4.self, 1)
    sum &+= mk(P8.self, Q9_5.self, 1)
    sum &+= mk(P8.self, Q9_6.self, 1)
    sum &+= mk(P8.self, Q9_7.self, 1)
    sum &+= mk(P8.self, Q9_8.self, 1)
    sum &+= mk(P9.self, Q0_0.self, 1)
    sum &+= mk(P9.self, Q0_1.self, 1)
    sum &+= mk(P9.self, Q0_2.self, 1)
    sum &+= mk(P9.self, Q0_3.self, 1)
    sum &+= mk(P9.self, Q0_4.self, 1)
    sum &+= mk(P9.self, Q0_5.self, 1)
    sum &+= mk(P9.self, Q0_6.self, 1)
    sum &+= mk(P9.self, Q0_7.self, 1)
    sum &+= mk(P9.self, Q0_8.self, 1)
    sum &+= mk(P9.self, Q1_0.self, 1)
    sum &+= mk(P9.self, Q1_1.self, 1)
    sum &+= mk(P9.self, Q1_2.self, 1)
    sum &+= mk(P9.self, Q1_3.self, 1)
    sum &+= mk(P9.self, Q1_4.self, 1)
    sum &+= mk(P9.self, Q1_5.self, 1)
    sum &+= mk(P9.self, Q1_6.self, 1)
    sum &+= mk(P9.self, Q1_7.self, 1)
    sum &+= mk(P9.self, Q1_8.self, 1)
    sum &+= mk(P9.self, Q2_0.self, 1)
    sum &+= mk(P9.self, Q2_1.self, 1)
    sum &+= mk(P9.self, Q2_2.self, 1)
    sum &+= mk(P9.self, Q2_3.self, 1)
    sum &+= mk(P9.self, Q2_4.self, 1)
    sum &+= mk(P9.self, Q2_5.self, 1)
    sum &+= mk(P9.self, Q2_6.self, 1)
    sum &+= mk(P9.self, Q2_7.self, 1)
    sum &+= mk(P9.self, Q2_8.self, 1)
    sum &+= mk(P9.self, Q3_0.self, 1)
    sum &+= mk(P9.self, Q3_1.self, 1)
    sum &+= mk(P9.self, Q3_2.self, 1)
    sum &+= mk(P9.self, Q3_3.self, 1)
    sum &+= mk(P9.self, Q3_4.self, 1)
    sum &+= mk(P9.self, Q3_5.self, 1)
    sum &+= mk(P9.self, Q3_6.self, 1)
    sum &+= mk(P9.self, Q3_7.self, 1)
    sum &+= mk(P9.self, Q3_8.self, 1)
    sum &+= mk(P9.self, Q4_0.self, 1)
    sum &+= mk(P9.self, Q4_1.self, 1)
    sum &+= mk(P9.self, Q4_2.self, 1)
    sum &+= mk(P9.self, Q4_3.self, 1)
    sum &+= mk(P9.self, Q4_4.self, 1)
    sum &+= mk(P9.self, Q4_5.self, 1)
    sum &+= mk(P9.self, Q4_6.self, 1)
    sum &+= mk(P9.self, Q4_7.self, 1)
    sum &+= mk(P9.self, Q4_8.self, 1)
    sum &+= mk(P9.self, Q5_0.self, 1)
    sum &+= mk(P9.self, Q5_1.self, 1)
    sum &+= mk(P9.self, Q5_2.self, 1)
    sum &+= mk(P9.self, Q5_3.self, 1)
    sum &+= mk(P9.self, Q5_4.self, 1)
    sum &+= mk(P9.self, Q5_5.self, 1)
    sum &+= mk(P9.self, Q5_6.self, 1)
    sum &+= mk(P9.self, Q5_7.self, 1)
    sum &+= mk(P9.self, Q5_8.self, 1)
    sum &+= mk(P9.self, Q6_0.self, 1)
    sum &+= mk(P9.self, Q6_1.self, 1)
    sum &+= mk(P9.self, Q6_2.self, 1)
    sum &+= mk(P9.self, Q6_3.self, 1)
    sum &+= mk(P9.self, Q6_4.self, 1)
    sum &+= mk(P9.self, Q6_5.self, 1)
    sum &+= mk(P9.self, Q6_6.self, 1)
    sum &+= mk(P9.self, Q6_7.self, 1)
    sum &+= mk(P9.self, Q6_8.self, 1)
    sum &+= mk(P9.self, Q7_0.self, 1)
    sum &+= mk(P9.self, Q7_1.self, 1)
    sum &+= mk(P9.self, Q7_2.self, 1)
    sum &+= mk(P9.self, Q7_3.self, 1)
    sum &+= mk(P9.self, Q7_4.self, 1)
    sum &+= mk(P9.self, Q7_5.self, 1)
    sum &+= mk(P9.self, Q7_6.self, 1)
    sum &+= mk(P9.self, Q7_7.self, 1)
    sum &+= mk(P9.self, Q7_8.self, 1)
    sum &+= mk(P9.self, Q8_0.self, 1)
    sum &+= mk(P9.self, Q8_1.self, 1)
    sum &+= mk(P9.self, Q8_2.self, 1)
    sum &+= mk(P9.self, Q8_3.self, 1)
    sum &+= mk(P9.self, Q8_4.self, 1)
    sum &+= mk(P9.self, Q8_5.self, 1)
    sum &+= mk(P9.self, Q8_6.self, 1)
    sum &+= mk(P9.self, Q8_7.self, 1)
    sum &+= mk(P9.self, Q8_8.self, 1)
    sum &+= mk(P9.self, Q9_0.self, 1)
    sum &+= mk(P9.self, Q9_1.self, 1)
    sum &+= mk(P9.self, Q9_2.self, 1)
    sum &+= mk(P9.self, Q9_3.self, 1)
    sum &+= mk(P9.self, Q9_4.self, 1)
    sum &+= mk(P9.self, Q9_5.self, 1)
    sum &+= mk(P9.self, Q9_6.self, 1)
    sum &+= mk(P9.self, Q9_7.self, 1)
    sum &+= mk(P9.self, Q9_8.self, 1)
    return sum   // 900 distinct instantiations, 2 metadata records each
}
