#!/bin/bash
# Stage Darwin overlay headers + a Clang module Darwin into a Darwin sysroot.
#
# Usage: stage_overlay_darwin.sh [SDK_ROOT]
#
# WALL 2 of the overlay operator log: swiftDarwin compiled, then failed on
# the sysroot's header surface (sig_t, FILE, OSStatus, extern_proc, MAP_FAILED,
# every float/long-double libm variant). Those names live in headers this
# sysroot already stages (or in overlay-darwin/ Apple OSS copies); they are
# invisible because usr/include has no Darwin.modulemap.
#
# Prefer the phase-2 FE sysroot (scratch/sysroot_fe4-x86_64) when present —
# that tree already carries Apple's SDK headers + generated Darwin modulemaps.
# Otherwise vendor Libm-2026 Intel math.h + CarbonHeaders-18.1 MacTypes.h
# (same class of copy as overlay-posix) and generate Darwin.modulemap from
# the headers that are actually here. Never name an absent header. Never
# hand-write prototypes. Never write into machorun/sdk/.
set -euo pipefail
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
SWIFTCORE_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
OPENUIKIT_ROOT=$(cd "$SWIFTCORE_ROOT/.." && pwd)
# shellcheck disable=SC1091
. "$SCRIPT_DIR/guest_arch.inc"

SDK=${1:-${SDK:-$HOME/work/sdk/MacOSX.sdk}}
SRC=$SWIFTCORE_ROOT/sdk/overlay-darwin
W=${W:-$HOME/work}

LIBM_TAG=Libm-2026
LIBM_COMMIT=17a5f9daa3f5679f7536b26f133b40cc078753c3
CARBON_TAG=CarbonHeaders-18.1
CARBON_COMMIT=214a9ae7ab3c0c78ddb50328ca226e6313c4c782

# Headers Darwin.o / Synchronization.o / CFExecutor.swift actually named.
# A modulemap line is emitted only when the file exists after staging.
# Submodule MacTypes matches Apple's Darwin.MacTypes. os/lock.h is
# Synchronization/Mutex/DarwinImpl.swift (os_unfair_lock_*); dlfcn.h is
# Concurrency/CFExecutor.swift (dlopen / dlsym / RTLD_NOLOAD).
DARWIN_MODULE_HEADERS=(
  signal.h
  sys/signal.h
  stdio.h
  _stdio.h
  sys/proc.h
  sys/mman.h
  math.h
  os/base.h
  os/lock.h
  dlfcn.h
)

resolve_fe_sysroot() {
  local cand
  for cand in \
      ${SWIFTCORE_FE_SYSROOT:+$SWIFTCORE_FE_SYSROOT} \
      "$W/scratch/sysroot_fe4-${SWIFTCORE_DARWIN_ARCH}" \
      "$W/scratch/sysroot_fe4-x86_64" \
      "$OPENUIKIT_ROOT/scratch/sysroot_fe4-${SWIFTCORE_DARWIN_ARCH}" \
      "$OPENUIKIT_ROOT/scratch/sysroot_fe4-x86_64"
  do
    [ -n "$cand" ] || continue
    if [ -f "$cand/usr/include/Darwin.modulemap" ]; then
      printf '%s\n' "$cand"
      return 0
    fi
  done
  return 1
}

stage_file() {
  local rel=$1 src=$2 mode=$3 repo=$4 tag=$5 commit=$6 upath=$7
  local dest=$SDK/$rel
  mkdir -p "$(dirname "$dest")"
  if [ -e "$dest" ]; then
    if cmp -s "$src" "$dest"; then
      echo "stage_overlay_darwin: already $rel"
      return 0
    fi
    if [ "$mode" = replace ]; then
      echo "stage_overlay_darwin: replacing $rel in the staged SDK"
      echo "  with apple-oss-distributions/$repo $upath ($tag)."
      echo "  machorun/sdk/ is not touched."
    else
      echo "stage_overlay_darwin: REFUSING to overwrite $dest" >&2
      echo "  with apple-oss-distributions/$repo $upath ($tag)." >&2
      exit 2
    fi
  fi
  cp "$src" "$dest"
  echo "stage_overlay_darwin: staged $rel"
  echo "  from apple-oss-distributions/$repo tag=$tag commit=$commit path=$upath"
}

write_darwin_modulemap() {
  local dest=$SDK/usr/include/Darwin.modulemap
  local h
  mkdir -p "$SDK/usr/include"
  {
    echo "// GENERATED by stage_overlay_darwin.sh — do not edit."
    echo "// Covers only headers this sysroot stages. Enumerated from Darwin.o,"
    echo "// Synchronization/Mutex/DarwinImpl.swift, Concurrency/CFExecutor.swift."
    echo "module Darwin [system] [extern_c] {"
    if [ -f "$SDK/usr/include/MacTypes.h" ]; then
      echo "  module MacTypes {"
      echo "    header \"MacTypes.h\""
      echo "    export *"
      echo "  }"
    fi
    for h in "${DARWIN_MODULE_HEADERS[@]}"; do
      if [ -f "$SDK/usr/include/$h" ]; then
        echo "  header \"$h\""
      fi
    done
    echo "  export *"
    echo "}"
  } > "$dest"
  echo "stage_overlay_darwin: wrote Darwin.modulemap ($(grep -c 'header \"' "$dest") headers)"
}

ensure_module_modulemap() {
  local top=$SDK/usr/include/module.modulemap
  mkdir -p "$SDK/usr/include"
  if [ ! -f "$top" ]; then
    cat > "$top" <<'EOF'
module ObjectiveC [system] {
  header "objc/objc.h"
  header "objc/objc-api.h"
  header "objc/runtime.h"
  header "objc/message.h"
  export *
}
EOF
  fi
  grep -q 'extern module Darwin' "$top" 2>/dev/null \
    || printf '\nextern module Darwin "Darwin.modulemap"\n' >> "$top"
}

copy_fe_darwin() {
  local fe=$1
  local f rel dest copied_maps=0 copied_hdr=0
  echo "stage_overlay_darwin: FE sysroot $fe (Apple SDK headers + Darwin modulemaps)"
  mkdir -p "$SDK/usr/include"
  while IFS= read -r -d '' f; do
    rel=${f#"$fe/usr/include/"}
    dest=$SDK/usr/include/$rel
    mkdir -p "$(dirname "$dest")"
    cp -a "$f" "$dest"
    copied_maps=$((copied_maps + 1))
  done < <(find "$fe/usr/include" -maxdepth 1 -name 'Darwin*.modulemap' -print0 2>/dev/null)
  if [ -d "$fe/usr/include/_modules" ]; then
    mkdir -p "$SDK/usr/include/_modules"
    cp -a "$fe/usr/include/_modules/." "$SDK/usr/include/_modules/"
  fi
  # Error-enumerated headers: take Apple's from FE when present.
  for rel in math.h MacTypes.h ConditionalMacros.h sys/proc.h signal.h \
             sys/signal.h stdio.h _stdio.h sys/mman.h architecture/i386/math.h \
             tgmath.h os/base.h os/lock.h dlfcn.h; do
    if [ -f "$fe/usr/include/$rel" ]; then
      mkdir -p "$(dirname "$SDK/usr/include/$rel")"
      cp -f "$fe/usr/include/$rel" "$SDK/usr/include/$rel"
      copied_hdr=$((copied_hdr + 1))
      echo "stage_overlay_darwin: FE header usr/include/$rel"
    fi
  done
  ensure_module_modulemap
  if [ -f "$fe/usr/include/module.modulemap" ]; then
    local line
    while IFS= read -r line; do
      grep -qxF "$line" "$SDK/usr/include/module.modulemap" && continue
      case "$line" in
        'extern module '*|'// Appended by '*)
          printf '%s\n' "$line" >> "$SDK/usr/include/module.modulemap"
          ;;
      esac
    done < "$fe/usr/include/module.modulemap"
  fi
  echo "stage_overlay_darwin: FE copied $copied_maps Darwin*.modulemap, $copied_hdr error-enumerated headers"
  [ -f "$SDK/usr/include/Darwin.modulemap" ]
}

[ -d "$SRC" ] || { echo "stage_overlay_darwin: missing $SRC" >&2; exit 2; }
mkdir -p "$SDK/usr/include"

FE=
if FE=$(resolve_fe_sysroot); then
  copy_fe_darwin "$FE" || {
    echo "stage_overlay_darwin: FE sysroot present but Darwin.modulemap copy failed; falling back to overlay-darwin pins" >&2
    FE=
  }
fi

if [ -z "$FE" ]; then
  # x86_64: Libm's Intel math.h is the published x86 surface (explicit f/l
  # prototypes). Do not replace machorun's arm64-capable clean-room math.h
  # when this configure is the Graviton arm64 path — Libm's dispatcher
  # #errors on __arm64__.
  if [ "${SWIFTCORE_DARWIN_ARCH}" = x86_64 ]; then
    stage_file usr/include/math.h "$SRC/math.h" replace \
      Libm "$LIBM_TAG" "$LIBM_COMMIT" Source/Intel/math.h
    stage_file usr/include/architecture/i386/math.h \
      "$SRC/architecture/i386/math.h" replace \
      Libm "$LIBM_TAG" "$LIBM_COMMIT" Source/Intel/math.h
  else
    echo "stage_overlay_darwin: skipping Libm Intel math.h on SWIFTCORE_DARWIN_ARCH=$SWIFTCORE_DARWIN_ARCH (Libm dispatcher does not accept __arm64__)"
  fi
  stage_file usr/include/MacTypes.h "$SRC/MacTypes.h" replace \
    CarbonHeaders "$CARBON_TAG" "$CARBON_COMMIT" MacTypes.h
  stage_file usr/include/ConditionalMacros.h "$SRC/ConditionalMacros.h" replace \
    CarbonHeaders "$CARBON_TAG" "$CARBON_COMMIT" ConditionalMacros.h
  write_darwin_modulemap
  ensure_module_modulemap
fi

# FE copy or a leftover sysroot can leave a math.h / proc.h that does not
# have the Darwin.o surface. Repair from the overlay-darwin / machorun pins
# rather than compiling against a silently incomplete tree.
if [ "${SWIFTCORE_DARWIN_ARCH}" = x86_64 ]; then
  if [ ! -f "$SDK/usr/include/math.h" ] \
      || ! grep -Eq '(^|[[:space:]*])fmaxl[[:space:]]*\(' "$SDK/usr/include/math.h"; then
    echo "stage_overlay_darwin: math.h lacks fmaxl; staging overlay-darwin Intel math.h"
    stage_file usr/include/math.h "$SRC/math.h" replace \
      Libm "$LIBM_TAG" "$LIBM_COMMIT" Source/Intel/math.h
    stage_file usr/include/architecture/i386/math.h \
      "$SRC/architecture/i386/math.h" replace \
      Libm "$LIBM_TAG" "$LIBM_COMMIT" Source/Intel/math.h
  fi
fi
if [ ! -f "$SDK/usr/include/MacTypes.h" ]; then
  echo "stage_overlay_darwin: MacTypes.h absent; staging CarbonHeaders pin"
  stage_file usr/include/MacTypes.h "$SRC/MacTypes.h" replace \
    CarbonHeaders "$CARBON_TAG" "$CARBON_COMMIT" MacTypes.h
fi
if [ ! -f "$SDK/usr/include/ConditionalMacros.h" ]; then
  echo "stage_overlay_darwin: ConditionalMacros.h absent; staging CarbonHeaders pin"
  stage_file usr/include/ConditionalMacros.h "$SRC/ConditionalMacros.h" replace \
    CarbonHeaders "$CARBON_TAG" "$CARBON_COMMIT" ConditionalMacros.h
fi
PROC_PIN=$OPENUIKIT_ROOT/machorun/sdk/usr/include/sys/proc.h
if [ -f "$PROC_PIN" ]; then
  if [ ! -f "$SDK/usr/include/sys/proc.h" ] \
      || ! grep -Eq 'extern_proc' "$SDK/usr/include/sys/proc.h"; then
    echo "stage_overlay_darwin: sys/proc.h lacks extern_proc; restoring machorun pin"
    mkdir -p "$SDK/usr/include/sys"
    cp "$PROC_PIN" "$SDK/usr/include/sys/proc.h"
  fi
fi
if [ -f "$SDK/usr/include/Darwin.modulemap" ]; then
  for h in math.h sys/proc.h; do
    if [ -f "$SDK/usr/include/$h" ] \
        && ! grep -q "header \"$h\"" "$SDK/usr/include/Darwin.modulemap"; then
      # Insert before the last line (the outer module's closing brace).
      sed -i '$i\  header "'"$h"'"' "$SDK/usr/include/Darwin.modulemap"
      echo "stage_overlay_darwin: Darwin.modulemap now names $h"
    fi
  done
else
  write_darwin_modulemap
fi
ensure_module_modulemap

echo "stage_overlay_darwin: done sysroot=$SDK"
echo "  Darwin.modulemap: $([ -f "$SDK/usr/include/Darwin.modulemap" ] && echo present || echo ABSENT)"
if [ -f "$SDK/usr/include/math.h" ]; then
  echo "  math.h: $(wc -l < "$SDK/usr/include/math.h") lines"
else
  echo "  math.h: missing"
fi
if [ -f "$SDK/usr/include/MacTypes.h" ]; then
  echo "  MacTypes.h: $(wc -l < "$SDK/usr/include/MacTypes.h") lines"
else
  echo "  MacTypes.h: missing"
fi
