import Foundation
import Dispatch
import SpriteKit

func testActionMoveAndFade() {
    let scene = SKScene(size: CGSize(width: 100, height: 100))
    let node = SKNode()
    scene.addChild(node)
    node.run(SKAction.move(to: CGPoint(x: 10, y: 20), duration: 0))
    scene.update(0)
    scene.update(1)
    precondition(abs(node.position.x - 10) < 0.001)
    node.run(SKAction.moveBy(x: 5, y: -5, duration: 0))
    scene.update(2)
    precondition(abs(node.position.x - 15) < 0.001)
    node.run(SKAction.move(by: CGVector(dx: 1, dy: 1), duration: 0))
    scene.update(3)
    node.run(SKAction.moveTo(x: 0, duration: 0))
    scene.update(4)
    node.run(SKAction.moveTo(y: 0, duration: 0))
    scene.update(5)
    node.alpha = 1
    node.run(SKAction.fadeOut(withDuration: 0))
    scene.update(6)
    precondition(node.alpha == 0)
    node.run(SKAction.fadeIn(withDuration: 0))
    scene.update(7)
    precondition(node.alpha == 1)
    node.run(SKAction.fadeAlpha(to: 0.25, duration: 0))
    scene.update(8)
    precondition(abs(node.alpha - 0.25) < 0.001)
    node.run(SKAction.fadeAlpha(by: 0.25, duration: 0))
    scene.update(9)
}

func testActionScaleRotateResize() {
    let scene = SKScene(size: CGSize(width: 40, height: 40))
    let sprite = SKSpriteNode(color: .white, size: CGSize(width: 10, height: 10))
    scene.addChild(sprite)
    sprite.run(SKAction.scale(to: 2, duration: 0))
    scene.update(0); scene.update(1)
    precondition(abs(sprite.xScale - 2) < 0.001)
    sprite.run(SKAction.scale(by: 0.5, duration: 0))
    scene.update(2)
    sprite.run(SKAction.scaleX(to: 3, y: 4, duration: 0))
    scene.update(3)
    sprite.run(SKAction.scaleX(by: 1, y: 1, duration: 0))
    scene.update(4)
    sprite.run(SKAction.scaleX(to: 1, duration: 0))
    scene.update(5)
    sprite.run(SKAction.scaleY(to: 1, duration: 0))
    scene.update(6)
    sprite.run(SKAction.rotate(byAngle: 0.5, duration: 0))
    scene.update(7)
    sprite.run(SKAction.rotate(toAngle: 0, duration: 0, shortestUnitArc: true))
    scene.update(8)
    sprite.run(SKAction.rotate(toAngle: 1, duration: 0))
    scene.update(9)
    sprite.run(SKAction.resize(toWidth: 20, height: 8, duration: 0))
    scene.update(10)
    precondition(abs(sprite.size.width - 20) < 0.001)
    sprite.run(SKAction.resize(byWidth: 2, height: 2, duration: 0))
    scene.update(11)
    sprite.run(SKAction.resize(toWidth: 10, duration: 0))
    scene.update(12)
    sprite.run(SKAction.resize(toHeight: 10, duration: 0))
    scene.update(13)
    sprite.run(SKAction.scale(to: CGSize(width: 12, height: 12), duration: 0))
    scene.update(14)
}

func testActionSequenceGroupRepeat() {
    let scene = SKScene(size: CGSize(width: 10, height: 10))
    let node = SKNode()
    scene.addChild(node)
    let seq = SKAction.sequence([
        SKAction.moveBy(x: 4, y: 0, duration: 0),
        SKAction.moveBy(x: 0, y: 4, duration: 0),
    ])
    node.run(seq)
    scene.update(0); scene.update(0.5); scene.update(1)
    let grouped = SKAction.group([
        SKAction.fadeAlpha(to: 0.5, duration: 0),
        SKAction.rotate(byAngle: 0.1, duration: 0),
    ])
    node.run(grouped)
    scene.update(2)
    node.run(SKAction.repeat(SKAction.moveBy(x: 1, y: 0, duration: 0), count: 2))
    scene.update(3); scene.update(4)
    let forever = SKAction.repeatForever(SKAction.wait(forDuration: 0))
    node.run(forever, withKey: "loop")
    precondition(node.action(forKey: "loop") != nil)
    precondition(node.hasActions())
    node.removeAction(forKey: "loop")
    node.removeAllActions()
    precondition(!node.hasActions())
}

func testActionHideWaitRun() {
    let scene = SKScene(size: CGSize(width: 8, height: 8))
    let node = SKNode()
    node.name = "child"
    scene.addChild(node)
    node.run(SKAction.hide())
    scene.update(0)
    precondition(node.isHidden)
    node.run(SKAction.unhide())
    scene.update(1)
    precondition(!node.isHidden)
    var ran = false
    node.run(SKAction.run { ran = true })
    scene.update(2)
    precondition(ran)
    let childAction = SKAction.run(SKAction.fadeOut(withDuration: 0), onChildWithName: "child")
    scene.run(childAction)
    scene.update(3)
    node.run(SKAction.wait(forDuration: 0))
    scene.update(4)
    node.run(SKAction.wait(forDuration: 0, withRange: 0))
    scene.update(5)
    var custom = 0 as CGFloat
    node.run(SKAction.customAction(withDuration: 0) { _, t in custom = t })
    scene.update(6)
    precondition(custom >= 0)
    let reversed = SKAction.moveBy(x: 2, y: 0, duration: 0).reversed()
    node.run(reversed)
    scene.update(7)
    _ = SKAction().copy()
}

func testActionTextureAndPhysicsFactories() {
    let texture = SKTexture(imageNamed: "dot")
    _ = SKAction.setTexture(texture)
    _ = SKAction.setTexture(texture, resize: true)
    _ = SKAction.setNormalTexture(texture)
    _ = SKAction.setNormalTexture(texture, resize: false)
    _ = SKAction.animate(with: [texture], timePerFrame: 0.1)
    _ = SKAction.animate(with: [texture], timePerFrame: 0.1, resize: false, restore: false)
    _ = SKAction.animate(withNormalTextures: [texture], timePerFrame: 0.1)
    _ = SKAction.animate(withNormalTextures: [texture], timePerFrame: 0.1, resize: false, restore: true)
    _ = SKAction.playSoundFileNamed("x.wav", waitForCompletion: false)
    _ = SKAction.play()
    _ = SKAction.pause()
    _ = SKAction.stop()
    _ = SKAction.applyForce(CGVector(dx: 1, dy: 0), duration: 0)
    _ = SKAction.applyForce(CGVector(dx: 1, dy: 0), at: .zero, duration: 0)
    _ = SKAction.applyImpulse(CGVector(dx: 1, dy: 0), duration: 0)
    _ = SKAction.applyImpulse(CGVector(dx: 1, dy: 0), at: .zero, duration: 0)
    _ = SKAction.applyTorque(1, duration: 0)
    _ = SKAction.applyAngularImpulse(1, duration: 0)
    _ = SKAction.changeMass(to: 2, duration: 0)
    _ = SKAction.changeMass(by: 1, duration: 0)
    _ = SKAction.changeCharge(to: 1, duration: 0)
    _ = SKAction.changeCharge(by: 1, duration: 0)
    _ = SKAction.changeVolume(to: 1, duration: 0)
    _ = SKAction.changeVolume(by: 1, duration: 0)
    _ = SKAction.changePlaybackRate(to: 1, duration: 0)
    _ = SKAction.changePlaybackRate(by: 1, duration: 0)
    _ = SKAction.changeObstruction(to: 1, duration: 0)
    _ = SKAction.changeObstruction(by: 1, duration: 0)
    _ = SKAction.changeOcclusion(to: 1, duration: 0)
    _ = SKAction.changeOcclusion(by: 1, duration: 0)
    _ = SKAction.changeReverb(to: 1, duration: 0)
    _ = SKAction.changeReverb(by: 1, duration: 0)
    _ = SKAction.stereoPan(to: 1, duration: 0)
    _ = SKAction.stereoPan(by: 1, duration: 0)
    _ = SKAction.falloff(to: 1, duration: 0)
    _ = SKAction.falloff(by: 1, duration: 0)
    _ = SKAction.strength(to: 1, duration: 0)
    _ = SKAction.strength(by: 1, duration: 0)
    _ = SKAction.colorize(withColorBlendFactor: 1, duration: 0)
    _ = SKAction.colorize(with: .red, colorBlendFactor: 1, duration: 0)
    _ = SKAction.speed(to: 2, duration: 0)
    _ = SKAction.speed(by: 1, duration: 0)
    precondition(SKAction(named: "missing") == nil)
    _ = SKAction(named: "missing", duration: 1)
    _ = SKAction(named: "missing", fromURL: URL(fileURLWithPath: "/tmp/x"))
    _ = SKAction(named: "missing", fromURL: URL(fileURLWithPath: "/tmp/x"), duration: 1)
}

func testActionFollowReachWarp() {
    let path = CGPath(rect: CGRect(x: 0, y: 0, width: 10, height: 10))
    _ = SKAction.follow(path, duration: 0)
    _ = SKAction.follow(path, speed: 1)
    _ = SKAction.follow(path, asOffset: true, orientToPath: false, duration: 0)
    _ = SKAction.follow(path, asOffset: false, orientToPath: true, speed: 1)
    let node = SKNode()
    let root = SKNode()
    _ = SKAction.reach(to: CGPoint(x: 1, y: 1), rootNode: root, duration: 0)
    _ = SKAction.reach(to: CGPoint(x: 1, y: 1), rootNode: root, velocity: 1)
    _ = SKAction.reach(to: node, rootNode: root, duration: 0)
    _ = SKAction.reach(to: node, rootNode: root, velocity: 1)
    let warp = SKWarpGeometry()
    _ = SKAction.warp(to: warp, duration: 0)
    _ = SKAction.animate(withWarps: [warp], times: [0 as NSNumber])
    _ = SKAction.animate(withWarps: [warp], times: [0 as NSNumber], restore: true)
    let action = SKAction.wait(forDuration: 1)
    action.duration = 0.5
    action.speed = 2
    action.timingMode = .easeIn
    action.timingFunction = { $0 }
    _ = action.timingFunction(0.5)
    var queued = false
    let queue = DispatchQueue(label: "spritekit-action-queue")
    let scene = SKScene(size: CGSize(width: 8, height: 8))
    scene.addChild(node)
    node.run(SKAction.run({ queued = true }, queue: queue))
    scene.update(0)
    precondition(queued)
}
