#!/usr/bin/env python3
"""Deterministic, fail-closed Swift source generation for .intentdefinition files.

This is an independent implementation of the public intent-definition plist
model.  It emits portable Swift against this project's Intents runtime; it
does not invoke or redistribute Apple's ``intentbuilderc`` output.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import plistlib
import re
import shutil
import stat
import sys
import tempfile
from typing import Any, Iterable


CLASSIFICATION = "open-intentdefinition-derived-sources"
COMPILER_NAME = "OpenIntentDefinitionCompiler"
FORMAT_VERSION = 1
COMPILER_VERSION = 1
MAX_INPUT_BYTES = 16 * 1024 * 1024

SWIFT_KEYWORDS = {
    "associatedtype", "class", "deinit", "enum", "extension", "fileprivate",
    "func", "import", "init", "inout", "internal", "let", "open", "operator",
    "private", "precedencegroup", "protocol", "public", "rethrows", "static",
    "struct", "subscript", "typealias", "var", "break", "case", "continue",
    "default", "defer", "do", "else", "fallthrough", "for", "guard", "if",
    "in", "repeat", "return", "switch", "where", "while", "as", "Any",
    "catch", "false", "is", "nil", "super", "self", "Self", "throw", "throws",
    "true", "try", "_", "async", "await", "some", "any", "consuming",
    "borrowing", "sending", "package", "nonisolated", "isolated", "macro",
}
IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
MODULE_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_.]*$")
PLACEHOLDER_RE = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}")

BASE_RESPONSE_CODES = (
    ("unspecified", 0),
    ("ready", 1),
    ("continueInApp", 2),
    ("inProgress", 3),
    ("success", 4),
    ("failure", 5),
    ("failureRequiringAppLaunch", 6),
)


class Refusal(RuntimeError):
    """A deterministic input or output contract refusal."""


def refuse(message: str) -> None:
    raise Refusal(message)


def sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def require_regular_no_link(path: Path, label: str) -> None:
    try:
        mode = path.lstat().st_mode
    except FileNotFoundError:
        refuse(f"missing {label}: {path}")
    if stat.S_ISLNK(mode):
        refuse(f"{label} is a symlink: {path}")
    if not stat.S_ISREG(mode):
        refuse(f"{label} is not a regular file: {path}")


def require_directory_no_link(path: Path, label: str) -> None:
    try:
        mode = path.lstat().st_mode
    except FileNotFoundError:
        refuse(f"missing {label}: {path}")
    if stat.S_ISLNK(mode):
        refuse(f"{label} is a symlink: {path}")
    if not stat.S_ISDIR(mode):
        refuse(f"{label} is not a directory: {path}")


def require_dict(value: Any, label: str) -> dict[str, Any]:
    if not isinstance(value, dict) or not all(isinstance(key, str) for key in value):
        refuse(f"{label} must be a string-keyed dictionary")
    return value


def require_list(value: Any, label: str) -> list[Any]:
    if not isinstance(value, list):
        refuse(f"{label} must be an array")
    return value


def require_string(value: Any, label: str) -> str:
    if not isinstance(value, str) or not value:
        refuse(f"{label} must be a non-empty string")
    if any(character in value for character in "\x00\r\n\t"):
        refuse(f"{label} contains a control character")
    return value


def raw_identifier(value: Any, label: str) -> str:
    name = require_string(value, label)
    if not IDENTIFIER_RE.fullmatch(name):
        refuse(f"{label} is not a portable Swift identifier: {name!r}")
    return name


def swift_identifier(name: str) -> str:
    return f"`{name}`" if name in SWIFT_KEYWORDS else name


def upper_initial(name: str) -> str:
    return name[0].upper() + name[1:]


def lower_initial(name: str) -> str:
    return name[0].lower() + name[1:]


def generated_header(source_name: str) -> str:
    return (
        f"// {source_name}\n"
        f"// Generated by {COMPILER_NAME} {COMPILER_VERSION}; do not edit.\n"
        "// Portable implementation derived from the .intentdefinition schema.\n\n"
        "import Intents\n\n"
    )


def class_name(record: dict[str, Any], family: str) -> str:
    if family == "intent":
        override = record.get("INIntentClassName")
        base = raw_identifier(record.get("INIntentName"), "intent name") + "Intent"
    elif family == "type":
        override = record.get("INTypeClassName")
        base = raw_identifier(record.get("INTypeName"), "type name")
    elif family == "enum":
        override = record.get("INEnumClassName")
        base = raw_identifier(record.get("INEnumName"), "enum name")
    else:
        raise AssertionError(family)
    return raw_identifier(override, f"{family} class name") if override else base


def parameter_type(
    record: dict[str, Any],
    prefix: str,
    enums: dict[str, str],
    types: dict[str, str],
) -> tuple[str, str]:
    logical = require_string(record.get(prefix + "Type"), prefix + "Type")
    multiple = bool(record.get(prefix + "SupportsMultipleValues", False))
    enum_name = record.get(prefix + "EnumType")
    object_name = record.get(prefix + "ObjectType")

    if enum_name is not None:
        enum_key = raw_identifier(enum_name, prefix + "EnumType")
        if enum_key not in enums:
            refuse(f"{prefix} references unknown enum {enum_key!r}")
        swift = enums[enum_key]
        default = f".{swift_identifier(first_enum_case(enum_key))}"
    elif logical == "Object":
        if object_name is None:
            swift = "INObject"
        else:
            object_key = raw_identifier(object_name, prefix + "ObjectType")
            if object_key not in types:
                refuse(f"{prefix} references unknown object type {object_key!r}")
            swift = types[object_key]
        default = "nil"
    elif logical == "String":
        swift, default = "String", "nil"
    elif logical in ("Integer", "Decimal", "Boolean"):
        # This is Apple's public generated-source shape as well.  The open
        # Foundation facade owns NSNumber's real value semantics.
        swift, default = "NSNumber", "nil"
    elif logical == "URL":
        swift, default = "URL", "nil"
    elif logical == "SpeakableString":
        swift, default = "INSpeakableString", "nil"
    else:
        refuse(f"unsupported intent-definition value type: {logical!r}")

    if multiple:
        return f"[{swift}]?", "nil"
    if enum_name is not None:
        return swift, default
    return f"{swift}?", default


# Set while one model is being rendered. It keeps parameter_type small and
# makes default enum cases use the schema's declared first value.
_ENUM_FIRST_CASES: dict[str, str] = {}


def first_enum_case(enum_name: str) -> str:
    try:
        return _ENUM_FIRST_CASES[enum_name]
    except KeyError:
        refuse(f"enum {enum_name!r} has no declared values")
    raise AssertionError("unreachable")


def render_enum(record: dict[str, Any], swift_name: str) -> tuple[str, dict[str, Any]]:
    model_name = raw_identifier(record.get("INEnumName"), "enum name")
    enum_type = record.get("INEnumType", "Regular")
    if enum_type != "Regular":
        refuse(f"unsupported enum type for {model_name}: {enum_type!r}")
    values = require_list(record.get("INEnumValues"), f"enum {model_name} values")
    if not values:
        refuse(f"enum {model_name} has no values")
    rendered: list[tuple[str, int]] = []
    seen_names: set[str] = set()
    seen_values: set[int] = set()
    next_value = 0
    for index, raw in enumerate(values):
        value = require_dict(raw, f"enum {model_name} value {index}")
        name = raw_identifier(value.get("INEnumValueName"), f"enum {model_name} value name")
        integer = value.get("INEnumValueIndex", next_value)
        if not isinstance(integer, int) or isinstance(integer, bool):
            refuse(f"enum {model_name} value {name} index must be an integer")
        if name in seen_names or integer in seen_values:
            refuse(f"enum {model_name} contains a duplicate name or raw value")
        seen_names.add(name)
        seen_values.add(integer)
        rendered.append((name, integer))
        next_value = integer + 1
    _ENUM_FIRST_CASES[model_name] = rendered[0][0]

    filename = f"{swift_name}.swift"
    lines = [generated_header(filename)]
    lines.append(f"public enum {swift_identifier(swift_name)}: Int, CaseIterable, Sendable {{\n")
    for name, integer in rendered:
        lines.append(f"    case {swift_identifier(name)} = {integer}\n")
    lines.append("}\n\n")
    lines.append(f"public class {swift_identifier(swift_name)}ResolutionResult: INEnumResolutionResult, @unchecked Sendable {{\n")
    lines.append(
        f"    public class func success(with resolvedValue: {swift_identifier(swift_name)}) -> Self {{\n"
        "        self.init(outcome: .success, value: resolvedValue.rawValue)\n"
        "    }\n\n"
    )
    lines.append(
        f"    public class func confirmationRequired(with valueToConfirm: {swift_identifier(swift_name)}) -> Self {{\n"
        "        self.init(outcome: .confirmationRequired, value: valueToConfirm.rawValue)\n"
        "    }\n"
    )
    lines.append("}\n")
    inventory = {
        "kind": "enum",
        "model_name": model_name,
        "swift_name": swift_name,
        "cases": [{"name": name, "raw_value": value} for name, value in rendered],
        "resolution_result": swift_name + "ResolutionResult",
    }
    return "".join(lines), inventory


def render_type(
    record: dict[str, Any],
    swift_name: str,
    enums: dict[str, str],
    types: dict[str, str],
) -> tuple[str, dict[str, Any]]:
    model_name = raw_identifier(record.get("INTypeName"), "type name")
    properties = require_list(record.get("INTypeProperties", []), f"type {model_name} properties")
    output_properties: list[dict[str, str]] = []
    seen: set[str] = set()
    for index, raw in enumerate(properties):
        prop = require_dict(raw, f"type {model_name} property {index}")
        name = raw_identifier(prop.get("INTypePropertyName"), f"type {model_name} property name")
        if name in seen:
            refuse(f"type {model_name} has duplicate property {name!r}")
        seen.add(name)
        # identifier/displayString/pronunciationHint/alternativeSpeakableMatches
        # are inherited INObject state and must not be shadowed.
        if bool(prop.get("INTypePropertyDefault", False)):
            continue
        swift_type, default = parameter_type(prop, "INTypeProperty", enums, types)
        output_properties.append({"name": name, "type": swift_type, "default": default})

    filename = f"{swift_name}.swift"
    lines = [generated_header(filename)]
    lines.append(f"public class {swift_identifier(swift_name)}: INObject, @unchecked Sendable {{\n")
    for prop in output_properties:
        lines.append(
            f"    public var {swift_identifier(prop['name'])}: {prop['type']} = {prop['default']}\n"
        )
    lines.append("}\n\n")
    lines.append(f"public class {swift_identifier(swift_name)}ResolutionResult: INObjectResolutionResult, @unchecked Sendable {{\n")
    lines.append(
        f"    public class func success(with resolvedObject: {swift_identifier(swift_name)}) -> Self {{\n"
        "        self.init(outcome: .success, value: resolvedObject)\n"
        "    }\n\n"
    )
    lines.append(
        f"    public class func disambiguation(with objectsToDisambiguate: [{swift_identifier(swift_name)}]) -> Self {{\n"
        "        self.init(outcome: .disambiguation, value: objectsToDisambiguate)\n"
        "    }\n\n"
    )
    lines.append(
        f"    public class func confirmationRequired(with objectToConfirm: {swift_identifier(swift_name)}?) -> Self {{\n"
        "        self.init(outcome: .confirmationRequired, value: objectToConfirm)\n"
        "    }\n"
    )
    lines.append("}\n")
    inventory = {
        "kind": "object",
        "model_name": model_name,
        "swift_name": swift_name,
        "properties": output_properties,
        "resolution_result": swift_name + "ResolutionResult",
    }
    return "".join(lines), inventory


def resolution_result_type(
    record: dict[str, Any],
    prefix: str,
    enums: dict[str, str],
    types: dict[str, str],
) -> str:
    logical = require_string(record.get(prefix + "Type"), prefix + "Type")
    enum_name = record.get(prefix + "EnumType")
    object_name = record.get(prefix + "ObjectType")
    if enum_name is not None:
        key = raw_identifier(enum_name, prefix + "EnumType")
        if key not in enums:
            refuse(f"{prefix} references unknown enum {key!r}")
        result = enums[key] + "ResolutionResult"
    elif logical == "Object":
        if object_name is None:
            result = "INObjectResolutionResult"
        else:
            key = raw_identifier(object_name, prefix + "ObjectType")
            if key not in types:
                refuse(f"{prefix} references unknown object type {key!r}")
            result = types[key] + "ResolutionResult"
    else:
        result = {
            "String": "INStringResolutionResult",
            "Integer": "INIntegerResolutionResult",
            "Decimal": "INDoubleResolutionResult",
            "Boolean": "INBooleanResolutionResult",
        }.get(logical, "")
        if not result:
            refuse(f"unsupported resolution-result type: {logical!r}")
    if bool(record.get(prefix + "SupportsMultipleValues", False)):
        return f"[{result}]"
    return result


def dynamic_collection_element_type(
    record: dict[str, Any],
    prefix: str,
    enums: dict[str, str],
    types: dict[str, str],
) -> str:
    logical = require_string(record.get(prefix + "Type"), prefix + "Type")
    enum_name = record.get(prefix + "EnumType")
    object_name = record.get(prefix + "ObjectType")
    if enum_name is not None:
        key = raw_identifier(enum_name, prefix + "EnumType")
        if key not in enums:
            refuse(f"{prefix} references unknown enum {key!r}")
        return enums[key]
    if logical == "Object":
        if object_name is None:
            return "INObject"
        key = raw_identifier(object_name, prefix + "ObjectType")
        if key not in types:
            refuse(f"{prefix} references unknown object type {key!r}")
        return types[key]
    if logical == "String":
        return "NSString"
    if logical in ("Integer", "Decimal", "Boolean"):
        return "NSNumber"
    refuse(f"unsupported dynamic-options type: {logical!r}")
    raise AssertionError("unreachable")


def response_codes(response: dict[str, Any], intent_name: str) -> list[tuple[str, int]]:
    declared = require_list(
        response.get("INIntentResponseCodes", []), f"intent {intent_name} response codes"
    )
    output = list(BASE_RESPONSE_CODES)
    builtin = {name for name, _ in BASE_RESPONSE_CODES}
    next_custom = 100
    seen: set[str] = set()
    for index, raw in enumerate(declared):
        code = require_dict(raw, f"intent {intent_name} response code {index}")
        name = raw_identifier(code.get("INIntentResponseCodeName"), "response code name")
        if name in seen:
            refuse(f"intent {intent_name} has duplicate response code {name!r}")
        seen.add(name)
        if name not in builtin:
            output.append((name, next_custom))
            next_custom += 1
    return output


def render_intent(
    record: dict[str, Any],
    swift_name: str,
    enums: dict[str, str],
    types: dict[str, str],
) -> tuple[str, dict[str, Any]]:
    model_name = raw_identifier(record.get("INIntentName"), "intent name")
    intent_kind = require_string(record.get("INIntentType"), f"intent {model_name} type")
    if intent_kind != "Custom":
        refuse(f"render_intent called for non-custom intent {model_name}")
    parameters = require_list(record.get("INIntentParameters", []), f"intent {model_name} parameters")
    seen_parameters: set[str] = set()
    output_parameters: list[dict[str, Any]] = []
    for index, raw in enumerate(parameters):
        parameter = require_dict(raw, f"intent {model_name} parameter {index}")
        name = raw_identifier(parameter.get("INIntentParameterName"), "intent parameter name")
        if name in seen_parameters:
            refuse(f"intent {model_name} has duplicate parameter {name!r}")
        seen_parameters.add(name)
        swift_type, default = parameter_type(parameter, "INIntentParameter", enums, types)
        output_parameters.append(
            {
                "name": name,
                "type": swift_type,
                "default": default,
                "resolution": bool(parameter.get("INIntentParameterSupportsResolution", False)),
                "dynamic": bool(parameter.get("INIntentParameterSupportsDynamicEnumeration", False)),
                "search": bool(parameter.get("INIntentParameterSupportsSearch", False)),
                "multiple": bool(parameter.get("INIntentParameterSupportsMultipleValues", False)),
                "model": parameter,
            }
        )

    response = require_dict(record.get("INIntentResponse", {}), f"intent {model_name} response")
    response_parameters_raw = require_list(
        response.get("INIntentResponseParameters", []), f"intent {model_name} response parameters"
    )
    response_parameters: list[dict[str, Any]] = []
    seen_response: set[str] = set()
    for index, raw in enumerate(response_parameters_raw):
        parameter = require_dict(raw, f"intent {model_name} response parameter {index}")
        name = raw_identifier(
            parameter.get("INIntentResponseParameterName"), "response parameter name"
        )
        if name in seen_response:
            refuse(f"intent {model_name} has duplicate response parameter {name!r}")
        seen_response.add(name)
        swift_type, default = parameter_type(
            parameter, "INIntentResponseParameter", enums, types
        )
        response_parameters.append({"name": name, "type": swift_type, "default": default})

    response_name = swift_name + "Response"
    response_code_name = response_name + "Code"
    handling_name = swift_name + "Handling"
    codes = response_codes(response, model_name)
    filename = f"{swift_name}.swift"
    lines = [generated_header(filename)]
    lines.append(f"public class {swift_identifier(swift_name)}: INIntent, @unchecked Sendable {{\n")
    for parameter in output_parameters:
        lines.append(
            f"    public var {swift_identifier(parameter['name'])}: {parameter['type']} = {parameter['default']}\n"
        )
    lines.append("}\n\n")

    lines.append(f"public protocol {swift_identifier(handling_name)}: AnyObject {{\n")
    lines.append(
        f"    func handle(intent: {swift_identifier(swift_name)}, completion: @escaping ({swift_identifier(response_name)}) -> Void)\n"
    )
    lines.append(
        f"    func handle(intent: {swift_identifier(swift_name)}) async -> {swift_identifier(response_name)}\n"
    )
    lines.append(
        f"    func confirm(intent: {swift_identifier(swift_name)}, completion: @escaping ({swift_identifier(response_name)}) -> Void)\n"
    )
    lines.append(
        f"    func confirm(intent: {swift_identifier(swift_name)}) async -> {swift_identifier(response_name)}\n"
    )
    for parameter in output_parameters:
        cap = upper_initial(parameter["name"])
        if parameter["resolution"]:
            result = resolution_result_type(
                parameter["model"], "INIntentParameter", enums, types
            )
            lines.append(
                f"    func resolve{cap}(for intent: {swift_identifier(swift_name)}, with completion: @escaping ({result}) -> Void)\n"
            )
            lines.append(
                f"    func resolve{cap}(for intent: {swift_identifier(swift_name)}) async -> {result}\n"
            )
        if parameter["dynamic"]:
            element_type = dynamic_collection_element_type(
                parameter["model"], "INIntentParameter", enums, types
            )
            search_argument = ", searchTerm: String?" if parameter["search"] else ""
            lines.append(
                f"    func provide{cap}OptionsCollection(for intent: {swift_identifier(swift_name)}{search_argument}, with completion: @escaping (INObjectCollection<{element_type}>?, Error?) -> Void)\n"
            )
            lines.append(
                f"    func provide{cap}OptionsCollection(for intent: {swift_identifier(swift_name)}{search_argument}) async throws -> INObjectCollection<{element_type}>\n"
            )
            lines.append(
                f"    func default{cap}(for intent: {swift_identifier(swift_name)}) -> {parameter['type']}\n"
            )
    lines.append("}\n\n")

    lines.append(f"public extension {swift_identifier(handling_name)} {{\n")
    lines.append(
        f"    func handle(intent: {swift_identifier(swift_name)}, completion: @escaping ({swift_identifier(response_name)}) -> Void) {{\n"
        f"        completion({swift_identifier(response_name)}(code: .failure, userActivity: nil))\n"
        "    }\n"
    )
    lines.append(
        f"    func handle(intent: {swift_identifier(swift_name)}) async -> {swift_identifier(response_name)} {{\n"
        f"        {swift_identifier(response_name)}(code: .failure, userActivity: nil)\n"
        "    }\n"
    )
    lines.append(
        f"    func confirm(intent: {swift_identifier(swift_name)}, completion: @escaping ({swift_identifier(response_name)}) -> Void) {{\n"
        f"        completion({swift_identifier(response_name)}(code: .ready, userActivity: nil))\n"
        "    }\n"
    )
    lines.append(
        f"    func confirm(intent: {swift_identifier(swift_name)}) async -> {swift_identifier(response_name)} {{\n"
        f"        {swift_identifier(response_name)}(code: .ready, userActivity: nil)\n"
        "    }\n"
    )
    for parameter in output_parameters:
        cap = upper_initial(parameter["name"])
        if parameter["resolution"]:
            result = resolution_result_type(
                parameter["model"], "INIntentParameter", enums, types
            )
            lines.append(
                f"    func resolve{cap}(for intent: {swift_identifier(swift_name)}, with completion: @escaping ({result}) -> Void) {{\n"
                f"        completion({result}.needsValue())\n"
                "    }\n"
            )
            lines.append(
                f"    func resolve{cap}(for intent: {swift_identifier(swift_name)}) async -> {result} {{\n"
                f"        {result}.needsValue()\n"
                "    }\n"
            )
        if parameter["dynamic"]:
            element_type = dynamic_collection_element_type(
                parameter["model"], "INIntentParameter", enums, types
            )
            search_argument = ", searchTerm: String?" if parameter["search"] else ""
            lines.append(
                f"    func provide{cap}OptionsCollection(for intent: {swift_identifier(swift_name)}{search_argument}, with completion: @escaping (INObjectCollection<{element_type}>?, Error?) -> Void) {{\n"
                "        completion(INObjectCollection(items: []), nil)\n"
                "    }\n"
            )
            lines.append(
                f"    func provide{cap}OptionsCollection(for intent: {swift_identifier(swift_name)}{search_argument}) async throws -> INObjectCollection<{element_type}> {{\n"
                "        INObjectCollection(items: [])\n"
                "    }\n"
            )
            lines.append(
                f"    func default{cap}(for intent: {swift_identifier(swift_name)}) -> {parameter['type']} {{ {parameter['default']} }}\n"
            )
    lines.append("}\n\n")

    lines.append(f"public enum {swift_identifier(response_code_name)}: Int, Sendable {{\n")
    for name, raw_value in codes:
        lines.append(f"    case {swift_identifier(name)} = {raw_value}\n")
    lines.append("}\n\n")

    lines.append(f"public class {swift_identifier(response_name)}: INIntentResponse, @unchecked Sendable {{\n")
    for parameter in response_parameters:
        lines.append(
            f"    public var {swift_identifier(parameter['name'])}: {parameter['type']} = {parameter['default']}\n"
        )
    lines.append(f"    public private(set) var code: {swift_identifier(response_code_name)}\n\n")
    lines.append(
        f"    public init(code: {swift_identifier(response_code_name)}, userActivity: NSUserActivity?) {{\n"
        "        self.code = code\n"
        "        super.init()\n"
        "        self.userActivity = userActivity\n"
        "    }\n"
    )

    response_parameter_map = {item["name"]: item for item in response_parameters}
    for raw in response.get("INIntentResponseCodes", []):
        code = require_dict(raw, f"intent {model_name} response code")
        code_name = raw_identifier(code.get("INIntentResponseCodeName"), "response code name")
        formats = " ".join(
            value for key, value in code.items()
            if "FormatString" in key and isinstance(value, str)
        )
        placeholders: list[str] = []
        for placeholder in PLACEHOLDER_RE.findall(formats):
            if placeholder not in placeholders:
                placeholders.append(placeholder)
        if not placeholders:
            continue
        unknown = [name for name in placeholders if name not in response_parameter_map]
        if unknown:
            refuse(f"intent {model_name} response code {code_name} references unknown response parameter {unknown[0]!r}")
        arguments = ", ".join(
            f"{swift_identifier(name)}: {response_parameter_map[name]['type'].removesuffix('?')}"
            for name in placeholders
        )
        lines.append(
            f"\n    public static func {swift_identifier(code_name)}({arguments}) -> {swift_identifier(response_name)} {{\n"
            f"        let response = {swift_identifier(response_name)}(code: .{swift_identifier(code_name)}, userActivity: nil)\n"
        )
        for name in placeholders:
            lines.append(f"        response.{swift_identifier(name)} = {swift_identifier(name)}\n")
        lines.append("        return response\n    }\n")
    lines.append("}\n")

    inventory = {
        "kind": "intent",
        "model_name": model_name,
        "swift_name": swift_name,
        "handling_protocol": handling_name,
        "parameters": [
            {key: item[key] for key in ("name", "type", "resolution", "dynamic", "search", "multiple")}
            for item in output_parameters
        ],
        "response": {
            "swift_name": response_name,
            "code_name": response_code_name,
            "codes": [{"name": name, "raw_value": value} for name, value in codes],
            "parameters": response_parameters,
        },
    }
    return "".join(lines), inventory


def json_bytes(value: Any) -> bytes:
    return (json.dumps(value, sort_keys=True, indent=2, ensure_ascii=False) + "\n").encode("utf-8")


def load_model(path: Path) -> tuple[bytes, dict[str, Any]]:
    require_regular_no_link(path, "intent-definition input")
    size = path.stat().st_size
    if size <= 0 or size > MAX_INPUT_BYTES:
        refuse(f"intent-definition input size {size} is outside 1..{MAX_INPUT_BYTES}")
    payload = path.read_bytes()
    try:
        decoded = plistlib.loads(payload)
    except Exception as error:
        refuse(f"intent-definition plist parse failed: {error}")
    model = require_dict(decoded, "intent-definition root")
    if model.get("INIntentDefinitionModelVersion") != "1.2":
        refuse(
            "unsupported intent-definition model version: "
            f"{model.get('INIntentDefinitionModelVersion')!r}"
        )
    require_list(model.get("INEnums"), "INEnums")
    require_list(model.get("INTypes"), "INTypes")
    require_list(model.get("INIntents"), "INIntents")
    return payload, model


def generate(input_path: Path, output_root: Path, module_name: str) -> dict[str, Any]:
    payload, model = load_model(input_path)
    if not MODULE_RE.fullmatch(module_name) or ".." in module_name:
        refuse(f"module name is not a portable Swift module name: {module_name!r}")
    require_directory_no_link(output_root.parent, "output parent")
    if output_root.exists() or output_root.is_symlink():
        refuse(f"refusing to overwrite output root: {output_root}")

    enum_records = [require_dict(item, "enum record") for item in model["INEnums"]]
    type_records = [require_dict(item, "type record") for item in model["INTypes"]]
    intent_records = [require_dict(item, "intent record") for item in model["INIntents"]]
    enum_names: dict[str, str] = {}
    type_names: dict[str, str] = {}
    for record in enum_records:
        model_key = raw_identifier(record.get("INEnumName"), "enum name")
        if model_key in enum_names:
            refuse(f"duplicate enum name: {model_key}")
        enum_names[model_key] = class_name(record, "enum")
    for record in type_records:
        model_key = raw_identifier(record.get("INTypeName"), "type name")
        if model_key in type_names:
            refuse(f"duplicate type name: {model_key}")
        type_names[model_key] = class_name(record, "type")

    _ENUM_FIRST_CASES.clear()
    outputs: list[tuple[str, str, dict[str, Any]]] = []
    for record in enum_records:
        swift_name = enum_names[raw_identifier(record.get("INEnumName"), "enum name")]
        source, inventory = render_enum(record, swift_name)
        outputs.append((swift_name + ".swift", source, inventory))
    for record in type_records:
        swift_name = type_names[raw_identifier(record.get("INTypeName"), "type name")]
        source, inventory = render_type(record, swift_name, enum_names, type_names)
        outputs.append((swift_name + ".swift", source, inventory))

    skipped: list[dict[str, str]] = []
    for record in intent_records:
        model_key = raw_identifier(record.get("INIntentName"), "intent name")
        kind = require_string(record.get("INIntentType"), f"intent {model_key} type")
        if kind == "System":
            skipped.append(
                {
                    "model_name": model_key,
                    "class_name": class_name(record, "intent"),
                    "reason": "owned-by-Intents-runtime",
                }
            )
            continue
        if kind != "Custom":
            refuse(f"unsupported intent kind for {model_key}: {kind!r}")
        swift_name = class_name(record, "intent")
        source, inventory = render_intent(record, swift_name, enum_names, type_names)
        outputs.append((swift_name + ".swift", source, inventory))

    filenames = [name for name, _source, _inventory in outputs]
    declaration_names = [item["swift_name"] for _name, _source, item in outputs]
    if len(filenames) != len(set(filenames)):
        refuse("two schema declarations map to the same output filename")
    if len(declaration_names) != len(set(declaration_names)):
        refuse("two schema declarations map to the same Swift name")
    if not outputs and not skipped:
        refuse("intent-definition contains no declarations")

    inventory = {
        "classification": "open-intentdefinition-declaration-inventory",
        "format_version": FORMAT_VERSION,
        "module_name": module_name,
        "declarations": [item for _name, _source, item in outputs],
        "skipped_system_intents": skipped,
    }
    inventory_payload = json_bytes(inventory)
    records = []
    for filename, source, item in outputs:
        encoded = source.encode("utf-8")
        records.append(
            {
                "path": filename,
                "kind": item["kind"],
                "swift_name": item["swift_name"],
                "sha256": sha256_bytes(encoded),
                "size": len(encoded),
            }
        )
    records.append(
        {
            "path": "declaration-inventory.json",
            "kind": "attestation",
            "sha256": sha256_bytes(inventory_payload),
            "size": len(inventory_payload),
        }
    )
    manifest = {
        "classification": CLASSIFICATION,
        "format_version": FORMAT_VERSION,
        "compiler": COMPILER_NAME,
        "compiler_version": COMPILER_VERSION,
        "module_name": module_name,
        "input": {
            "name": input_path.name,
            "sha256": sha256_bytes(payload),
            "size": len(payload),
            "model_version": model["INIntentDefinitionModelVersion"],
            "tools_version": model.get("INIntentDefinitionToolsVersion"),
            "tools_build_version": model.get("INIntentDefinitionToolsBuildVersion"),
        },
        "counts": {
            "enums": len(enum_records),
            "objects": len(type_records),
            "custom_intents": sum(item[2]["kind"] == "intent" for item in outputs),
            "skipped_system_intents": len(skipped),
            "swift_sources": len(outputs),
        },
        "skipped_system_intents": skipped,
        "outputs": records,
    }
    manifest_payload = json_bytes(manifest)

    temporary = Path(
        tempfile.mkdtemp(prefix=f".{output_root.name}.INCOMPLETE.", dir=output_root.parent)
    )
    try:
        for filename, source, _item in outputs:
            path = temporary / filename
            path.write_text(source, encoding="utf-8", newline="\n")
        (temporary / "declaration-inventory.json").write_bytes(inventory_payload)
        (temporary / "intentdefinition-manifest.json").write_bytes(manifest_payload)
        os.replace(temporary, output_root)
    except BaseException:
        shutil.rmtree(temporary, ignore_errors=True)
        raise
    return manifest


def verify(root: Path) -> dict[str, Any]:
    require_directory_no_link(root, "generated output root")
    manifest_path = root / "intentdefinition-manifest.json"
    require_regular_no_link(manifest_path, "generated manifest")
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except Exception as error:
        refuse(f"generated manifest parse failed: {error}")
    manifest = require_dict(manifest, "generated manifest")
    if manifest.get("classification") != CLASSIFICATION:
        refuse("generated manifest classification drifted")
    if manifest.get("format_version") != FORMAT_VERSION:
        refuse("generated manifest format version drifted")
    outputs = require_list(manifest.get("outputs"), "generated manifest outputs")
    expected_names = {"intentdefinition-manifest.json"}
    for index, raw in enumerate(outputs):
        record = require_dict(raw, f"generated output {index}")
        name = require_string(record.get("path"), "generated output path")
        if Path(name).name != name or name in (".", ".."):
            refuse(f"unsafe generated output path: {name!r}")
        if name in expected_names:
            refuse(f"duplicate generated output path: {name}")
        expected_names.add(name)
        path = root / name
        require_regular_no_link(path, f"generated output {name}")
        payload = path.read_bytes()
        if len(payload) != record.get("size") or sha256_bytes(payload) != record.get("sha256"):
            refuse(f"generated output changed: {name}")
    physical_names = {entry.name for entry in os.scandir(root)}
    if physical_names != expected_names:
        refuse("generated output directory differs from manifest")
    return manifest


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description=__doc__)
    commands = result.add_subparsers(dest="command", required=True)
    generate_parser = commands.add_parser("generate")
    generate_parser.add_argument("--input", required=True)
    generate_parser.add_argument("--output-root", required=True)
    generate_parser.add_argument("--module-name", required=True)
    generate_parser.add_argument("--emit-summary", action="store_true")
    verify_parser = commands.add_parser("verify")
    verify_parser.add_argument("root")
    verify_parser.add_argument("--emit-summary", action="store_true")
    return result


def main(argv: Iterable[str] | None = None) -> int:
    args = parser().parse_args(argv)
    try:
        if args.command == "generate":
            manifest = generate(Path(args.input), Path(args.output_root), args.module_name)
        else:
            manifest = verify(Path(args.root))
        if args.emit_summary:
            print(json.dumps(manifest, sort_keys=True, separators=(",", ":")))
        return 0
    except Refusal as error:
        print(f"intentdefinition_compiler: REFUSING -- {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
