// ConformanceApps.registry is generated by scripts/gen_conformance_registry.sh
// from a directory scan. Regenerating it must change nothing — that is how
// we know the checked-in Registry.swift matches the apps on disk, and how
// adding an app is "create the directory + one register line + run the
// generator" instead of editing five host files.
//
// MEASURED: SKIP_CAPTURE=1 scripts/conformance_flow.sh against
// /tmp/conformance-<App> for NavFlow, Forms, TableEditor, Feed, Modal —
// every capture score unchanged to three decimals after openhost and
// confprobe switched onto this table.

import Foundation
import XCTest
import ConformanceApps

final class ConformanceRegistryTests: XCTestCase {

    static func repoRoot() throws -> URL {
        let url = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()   // Tests/OpenUIKitTests
            .deletingLastPathComponent()   // Tests
            .deletingLastPathComponent()   // repo root (uikit/)
        let gen = url.appendingPathComponent("scripts/gen_conformance_registry.sh")
        guard FileManager.default.fileExists(atPath: gen.path) else {
            throw XCTSkip("scripts/gen_conformance_registry.sh not found next to test sources")
        }
        return url
    }

    /// App directories: a folder under Sources/ConformanceApps that contains
    /// both <Name>App.swift and script.json. Same rule as the generator.
    static func scannedApps(in root: URL) throws -> [String] {
        let appsDir = root.appendingPathComponent("Sources/ConformanceApps")
        let fm = FileManager.default
        let items = try fm.contentsOfDirectory(atPath: appsDir.path)
        var names: [String] = []
        for name in items {
            if name.hasPrefix(".") { continue }
            let dir = appsDir.appendingPathComponent(name)
            var isDir: ObjCBool = false
            guard fm.fileExists(atPath: dir.path, isDirectory: &isDir), isDir.boolValue else {
                continue
            }
            let appFile = dir.appendingPathComponent(name + "App.swift")
            let script = dir.appendingPathComponent("script.json")
            if fm.fileExists(atPath: appFile.path), fm.fileExists(atPath: script.path) {
                names.append(name)
            }
        }
        return names.sorted()
    }

    func testRegeneratingRegistryChangesNothing() throws {
        let root = try Self.repoRoot()
        let script = root.appendingPathComponent("scripts/gen_conformance_registry.sh")
        let checkedIn = root.appendingPathComponent("Sources/ConformanceApps/Registry.swift")
        let tmp = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("Registry-\(UUID().uuidString).swift")
        defer { try? FileManager.default.removeItem(at: tmp) }

        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/bin/zsh")
        p.arguments = [script.path, tmp.path]
        p.currentDirectoryURL = root
        let err = Pipe()
        p.standardError = err
        p.standardOutput = Pipe()
        try p.run()
        p.waitUntilExit()
        XCTAssertEqual(p.terminationStatus, 0,
                       String(data: err.fileHandleForReading.readDataToEndOfFile(),
                              encoding: .utf8) ?? "")

        let expected = try String(contentsOf: checkedIn, encoding: .utf8)
        let got = try String(contentsOf: tmp, encoding: .utf8)
        XCTAssertEqual(got, expected,
                       "Registry.swift is stale; run scripts/gen_conformance_registry.sh")
    }

    func testNamesMatchDirectoryScan() throws {
        let root = try Self.repoRoot()
        let scanned = try Self.scannedApps(in: root)
        XCTAssertEqual(ConformanceApps.names, scanned)
        XCTAssertFalse(scanned.isEmpty)
    }

    /// MEASURED TableEditor t1350 / t2350 and Modal t600: script times
    /// convert to a named 60 Hz frame so confprobe and openhost cannot
    /// drift (scoreboard/open.txt three-clock split).
    func testClockMapsMidFlightDelaysToNamedFrames() {
        XCTAssertEqual(ConformanceClock.hz, 60)
        XCTAssertEqual(ConformanceClock.frameIndex(for: 0.15), 9)
        XCTAssertEqual(ConformanceClock.frameIndex(for: 0.20), 12)
        XCTAssertEqual(ConformanceClock.frameIndex(for: 1.20), 72)
        XCTAssertEqual(ConformanceClock.frameIndex(for: 1.35), 81)
        XCTAssertEqual(ConformanceClock.frameIndex(for: 2.20), 132)
        XCTAssertEqual(ConformanceClock.frameIndex(for: 2.35), 141)
        XCTAssertEqual(ConformanceClock.frameIndex(for: 0.40), 24)
        XCTAssertEqual(ConformanceClock.frameIndex(for: 0.60), 36)
        XCTAssertEqual(ConformanceClock.time(of: 9), 0.15, accuracy: 1e-12)
        XCTAssertEqual(ConformanceClock.time(of: 12), 0.20, accuracy: 1e-12)
        XCTAssertEqual(ConformanceClock.time(of: 81), 1.35, accuracy: 1e-12)
        XCTAssertEqual(ConformanceClock.time(of: 141), 2.35, accuracy: 1e-12)
        // Accumulating t += 1/60 missed 2.35 (fire_n=142). Integer multiply
        // does not.
        var t = 0.0
        let tick = 1.0 / 60.0
        var n = 0
        while t <= 2.35 + tick {
            if 2.35 <= t { break }
            t += tick
            n += 1
        }
        XCTAssertEqual(n, 142)
        XCTAssertEqual(ConformanceClock.frameIndex(for: 2.35), 141)
    }

    @MainActor
    func testRegistryHasEveryScannedApp() throws {
        let root = try Self.repoRoot()
        let scanned = try Self.scannedApps(in: root)
        let table = ConformanceApps.registry
        XCTAssertEqual(Set(table.keys), Set(scanned))
        for name in scanned {
            let entry = try XCTUnwrap(table[name])
            XCTAssertEqual(entry.scriptPath,
                           "Sources/ConformanceApps/" + name + "/script.json")
            XCTAssertGreaterThan(entry.windowSize.width, 0)
            XCTAssertGreaterThan(entry.windowSize.height, 0)
        }
    }
}
