// ConformanceApps.registry is generated by scripts/gen_conformance_registry.sh
// from a directory scan. Regenerating it must change nothing — that is how
// we know the checked-in Registry.swift matches the apps on disk, and how
// adding an app is "create the directory + one register line + run the
// generator" instead of editing five host files.
//
// MEASURED: SKIP_CAPTURE=1 scripts/conformance_flow.sh against
// /tmp/conformance-<App> for NavFlow, Forms, TableEditor, Feed, Modal,
// Pager — regenerating Registry.swift changes nothing. Pager mid-flight
// scores are identical to three decimals across five runs.

import Foundation
import XCTest
import ConformanceApps

final class ConformanceRegistryTests: XCTestCase {

    static func repoRoot() throws -> URL {
        let url = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()   // Tests/OpenUIKitTests
            .deletingLastPathComponent()   // Tests
            .deletingLastPathComponent()   // repo root (uikit/)
        let gen = url.appendingPathComponent("scripts/gen_conformance_registry.sh")
        guard FileManager.default.fileExists(atPath: gen.path) else {
            throw XCTSkip("scripts/gen_conformance_registry.sh not found next to test sources")
        }
        return url
    }

    /// App directories: a folder under Sources/ConformanceApps that contains
    /// both <Name>App.swift and script.json. Same rule as the generator.
    static func scannedApps(in root: URL) throws -> [String] {
        let appsDir = root.appendingPathComponent("Sources/ConformanceApps")
        let fm = FileManager.default
        let items = try fm.contentsOfDirectory(atPath: appsDir.path)
        var names: [String] = []
        for name in items {
            if name.hasPrefix(".") { continue }
            let dir = appsDir.appendingPathComponent(name)
            var isDir: ObjCBool = false
            guard fm.fileExists(atPath: dir.path, isDirectory: &isDir), isDir.boolValue else {
                continue
            }
            let appFile = dir.appendingPathComponent(name + "App.swift")
            let script = dir.appendingPathComponent("script.json")
            if fm.fileExists(atPath: appFile.path), fm.fileExists(atPath: script.path) {
                names.append(name)
            }
        }
        return names.sorted()
    }

    func testRegeneratingRegistryChangesNothing() throws {
        let root = try Self.repoRoot()
        let script = root.appendingPathComponent("scripts/gen_conformance_registry.sh")
        let checkedIn = root.appendingPathComponent("Sources/ConformanceApps/Registry.swift")
        let tmp = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("Registry-\(UUID().uuidString).swift")
        defer { try? FileManager.default.removeItem(at: tmp) }

        let p = Process()
        p.executableURL = URL(fileURLWithPath: "/bin/zsh")
        p.arguments = [script.path, tmp.path]
        p.currentDirectoryURL = root
        let err = Pipe()
        p.standardError = err
        p.standardOutput = Pipe()
        try p.run()
        p.waitUntilExit()
        XCTAssertEqual(p.terminationStatus, 0,
                       String(data: err.fileHandleForReading.readDataToEndOfFile(),
                              encoding: .utf8) ?? "")

        let expected = try String(contentsOf: checkedIn, encoding: .utf8)
        let got = try String(contentsOf: tmp, encoding: .utf8)
        XCTAssertEqual(got, expected,
                       "Registry.swift is stale; run scripts/gen_conformance_registry.sh")
    }

    func testNamesMatchDirectoryScan() throws {
        let root = try Self.repoRoot()
        let scanned = try Self.scannedApps(in: root)
        XCTAssertEqual(ConformanceApps.names, scanned)
        XCTAssertFalse(scanned.isEmpty)
    }

    /// MEASURED TableEditor t1350 / t2350 and Modal t600: script times
    /// convert to a named 60 Hz frame so confprobe and openhost cannot
    /// drift (scoreboard/open.txt three-clock split).
    func testClockMapsMidFlightDelaysToNamedFrames() {
        XCTAssertEqual(ConformanceClock.hz, 60)
        XCTAssertEqual(ConformanceClock.frameIndex(for: 0.15), 9)
        XCTAssertEqual(ConformanceClock.frameIndex(for: 0.20), 12)
        XCTAssertEqual(ConformanceClock.frameIndex(for: 1.20), 72)
        XCTAssertEqual(ConformanceClock.frameIndex(for: 1.35), 81)
        XCTAssertEqual(ConformanceClock.frameIndex(for: 2.20), 132)
        XCTAssertEqual(ConformanceClock.frameIndex(for: 2.35), 141)
        XCTAssertEqual(ConformanceClock.frameIndex(for: 0.40), 24)
        XCTAssertEqual(ConformanceClock.frameIndex(for: 0.60), 36)
        // Pager page-next frames 0/6/12/18 and fling frames 0/8/16/30.
        XCTAssertEqual(ConformanceClock.frameIndex(for: 0.50), 30)
        XCTAssertEqual(ConformanceClock.frameIndex(for: 0.70), 42)
        XCTAssertEqual(ConformanceClock.frameIndex(for: 3.00), 180)
        XCTAssertEqual(ConformanceClock.frameIndex(for: 3.133), 188)
        XCTAssertEqual(ConformanceClock.frameIndex(for: 3.267), 196)
        XCTAssertEqual(ConformanceClock.frameIndex(for: 3.50), 210)
        XCTAssertEqual(ConformanceClock.frameIndex(for: 4.50), 270)
        XCTAssertEqual(ConformanceClock.frameIndex(for: 4.65), 279)
        XCTAssertEqual(ConformanceClock.time(of: 9), 0.15, accuracy: 1e-12)
        XCTAssertEqual(ConformanceClock.time(of: 12), 0.20, accuracy: 1e-12)
        XCTAssertEqual(ConformanceClock.time(of: 81), 1.35, accuracy: 1e-12)
        XCTAssertEqual(ConformanceClock.time(of: 141), 2.35, accuracy: 1e-12)
        // Accumulating t += 1/60 missed 2.35 (fire_n=142). Integer multiply
        // does not.
        var t = 0.0
        let tick = 1.0 / 60.0
        var n = 0
        while t <= 2.35 + tick {
            if 2.35 <= t { break }
            t += tick
            n += 1
        }
        XCTAssertEqual(n, 142)
        XCTAssertEqual(ConformanceClock.frameIndex(for: 2.35), 141)
    }

    /// Dark captures append `.dark` so light goldens keep `t200` and the
    /// scoreboard can hold both timelines (`NavFlow:t200` vs
    /// `NavFlow:t200.dark`). Env wins over the script field so
    /// `conformance_flow.sh --dark` can drive a light script.json.
    func testDarkCaptureSuffixAndStyleResolution() {
        XCTAssertEqual(ConformanceClock.captureSuffix(for: 0.20), "t200")
        XCTAssertEqual(ConformanceClock.captureSuffix(for: 0.20, style: "light"), "t200")
        XCTAssertEqual(ConformanceClock.captureSuffix(for: 0.20, style: "dark"), "t200.dark")
        XCTAssertEqual(ConformanceClock.captureSuffix(for: 0.08, style: "dark"), "t080.dark")
        XCTAssertEqual(ConformanceClock.captureSuffix(for: 1.0, style: "dark"), "t1000.dark")
        XCTAssertEqual(ConformanceClock.resolvedStyle(script: "light", environment: nil), "light")
        XCTAssertEqual(ConformanceClock.resolvedStyle(script: "dark", environment: nil), "dark")
        XCTAssertEqual(ConformanceClock.resolvedStyle(script: "light", environment: "dark"), "dark")
        XCTAssertEqual(ConformanceClock.resolvedStyle(script: "dark", environment: "light"), "dark")
    }

    /// Content-size captures append `.ax1` / `.xxxl` so default-size goldens
    /// keep `t200`. Env `CONFPROBE_CONTENT_SIZE` / `OPENUIKIT_APP_CONTENT_SIZE`
    /// drive `conformance_flow.sh --ax1` / `--xxxl`.
    func testContentSizeCaptureSuffixAndResolution() {
        XCTAssertEqual(ConformanceClock.captureSuffix(for: 0.20, contentSize: "large"), "t200")
        XCTAssertEqual(ConformanceClock.captureSuffix(for: 0.20, contentSize: "ax1"), "t200.ax1")
        XCTAssertEqual(ConformanceClock.captureSuffix(for: 0.08, contentSize: "xxxl"), "t080.xxxl")
        XCTAssertEqual(ConformanceClock.captureSuffix(for: 0.20, style: "dark",
                                                     contentSize: "ax1"), "t200.dark.ax1")
        XCTAssertEqual(ConformanceClock.resolvedContentSize(environment: nil), "large")
        XCTAssertEqual(ConformanceClock.resolvedContentSize(environment: "ax1"), "ax1")
        XCTAssertEqual(ConformanceClock.resolvedContentSize(environment: "xxxl"), "xxxl")
        XCTAssertEqual(ConformanceClock.resolvedContentSize(environment: "other"), "large")
        XCTAssertEqual(ConformanceClock.contentSizeCategory(for: "ax1"),
                       .accessibilityLarge)
        XCTAssertEqual(ConformanceClock.contentSizeCategory(for: "xxxl"),
                       .extraExtraExtraLarge)
        XCTAssertEqual(ConformanceClock.contentSizeCategory(for: "large"), .large)
    }

    @MainActor
    func testRegistryHasEveryScannedApp() throws {
        let root = try Self.repoRoot()
        let scanned = try Self.scannedApps(in: root)
        let table = ConformanceApps.registry
        XCTAssertEqual(Set(table.keys), Set(scanned))
        for name in scanned {
            let entry = try XCTUnwrap(table[name])
            XCTAssertEqual(entry.scriptPath,
                           "Sources/ConformanceApps/" + name + "/script.json")
            XCTAssertGreaterThan(entry.windowSize.width, 0)
            XCTAssertGreaterThan(entry.windowSize.height, 0)
        }
    }
}
