import Foundation
import GameKit

func testGKEnumRawValues() {
    precondition(GKAccessPoint.Location.topLeading.rawValue == 0)
    precondition(GKAccessPoint.Location.topTrailing.rawValue == 1)
    precondition(GKAccessPoint.Location.bottomLeading.rawValue == 2)
    precondition(GKAccessPoint.Location.bottomTrailing.rawValue == 3)
    precondition(GKAccessPoint.Location(rawValue: 0) == .topLeading)
    precondition(GKAccessPoint.Location.topLeading != .bottomTrailing)
    var locationHasher = Hasher()
    GKAccessPoint.Location.topLeading.hash(into: &locationHasher)
    _ = locationHasher.finalize()

    precondition(GKChallengeState.invalid.rawValue == 0)
    precondition(GKChallengeState.pending.rawValue == 1)
    precondition(GKChallengeState.completed.rawValue == 2)
    precondition(GKChallengeState.declined.rawValue == 3)
    precondition(GKChallengeState(rawValue: 2) == .completed)
    precondition(GKChallengeState.pending != .declined)
    var challengeHasher = Hasher()
    GKChallengeState.pending.hash(into: &challengeHasher)
    _ = challengeHasher.finalize()

    precondition(GKConnectionState.notConnected.rawValue == 0)
    precondition(GKConnectionState.connected.rawValue == 1)
    precondition(GKConnectionState(rawValue: 1) == .connected)
    precondition(GKConnectionState.connected != .notConnected)
    var connectionHasher = Hasher()
    GKConnectionState.connected.hash(into: &connectionHasher)
    _ = connectionHasher.finalize()

    precondition(GKFriendsAuthorizationStatus.notDetermined.rawValue == 0)
    precondition(GKFriendsAuthorizationStatus.restricted.rawValue == 1)
    precondition(GKFriendsAuthorizationStatus.denied.rawValue == 2)
    precondition(GKFriendsAuthorizationStatus.authorized.rawValue == 3)
    precondition(GKFriendsAuthorizationStatus(rawValue: 3) == .authorized)
    precondition(GKFriendsAuthorizationStatus.denied != .authorized)
    var friendsHasher = Hasher()
    GKFriendsAuthorizationStatus.authorized.hash(into: &friendsHasher)
    _ = friendsHasher.finalize()

    precondition(GKGameActivityPlayStyle.unspecified.rawValue == 0)
    precondition(GKGameActivityPlayStyle.synchronous.rawValue == 1)
    precondition(GKGameActivityPlayStyle.asynchronous.rawValue == 2)
    precondition(GKGameActivityPlayStyle(rawValue: 1) == .synchronous)
    precondition(GKGameActivityPlayStyle.synchronous != .asynchronous)
    var playHasher = Hasher()
    GKGameActivityPlayStyle.synchronous.hash(into: &playHasher)
    _ = playHasher.finalize()

    precondition(GKGameActivity.State.initialized.rawValue == 0)
    precondition(GKGameActivity.State.active.rawValue == 1)
    precondition(GKGameActivity.State.paused.rawValue == 2)
    precondition(GKGameActivity.State.ended.rawValue == 4)
    precondition(GKGameActivity.State(rawValue: 4) == .ended)
    precondition(GKGameActivity.State.active != .paused)
    var stateHasher = Hasher()
    GKGameActivity.State.active.hash(into: &stateHasher)
    _ = stateHasher.finalize()

    precondition(GKGameCenterViewControllerState.default.rawValue == -1)
    precondition(GKGameCenterViewControllerState.leaderboards.rawValue == 0)
    precondition(GKGameCenterViewControllerState.achievements.rawValue == 1)
    precondition(GKGameCenterViewControllerState.challenges.rawValue == 2)
    precondition(GKGameCenterViewControllerState.localPlayerProfile.rawValue == 3)
    precondition(GKGameCenterViewControllerState.dashboard.rawValue == 4)
    precondition(GKGameCenterViewControllerState.localPlayerFriendsList.rawValue == 5)
    precondition(GKGameCenterViewControllerState(rawValue: 4) == .dashboard)
    precondition(GKGameCenterViewControllerState.achievements != .challenges)
    var gcHasher = Hasher()
    GKGameCenterViewControllerState.dashboard.hash(into: &gcHasher)
    _ = gcHasher.finalize()

    precondition(GKInviteRecipientResponse.accepted.rawValue == 0)
    precondition(GKInviteRecipientResponse.declined.rawValue == 1)
    precondition(GKInviteRecipientResponse.failed.rawValue == 2)
    precondition(GKInviteRecipientResponse.incompatible.rawValue == 3)
    precondition(GKInviteRecipientResponse.unableToConnect.rawValue == 4)
    precondition(GKInviteRecipientResponse.noAnswer.rawValue == 5)
    precondition(GKInviteRecipientResponse.inviteeResponseAccepted == .accepted)
    precondition(GKInviteRecipientResponse.inviteeResponseDeclined == .declined)
    precondition(GKInviteRecipientResponse.inviteeResponseFailed == .failed)
    precondition(GKInviteRecipientResponse.inviteeResponseIncompatible == .incompatible)
    precondition(GKInviteRecipientResponse.inviteeResponseUnableToConnect == .unableToConnect)
    precondition(GKInviteRecipientResponse.inviteeResponseNoAnswer == .noAnswer)
    let alias: GKInviteeResponse = .accepted
    precondition(alias == GKInviteRecipientResponse.accepted)
    precondition(GKInviteRecipientResponse(rawValue: 0) == .accepted)
    precondition(GKInviteRecipientResponse.accepted != .declined)
    var inviteHasher = Hasher()
    GKInviteRecipientResponse.accepted.hash(into: &inviteHasher)
    _ = inviteHasher.finalize()

    precondition(GKLeaderboard.PlayerScope.global.rawValue == 0)
    precondition(GKLeaderboard.PlayerScope.friendsOnly.rawValue == 1)
    precondition(GKLeaderboard.TimeScope.today.rawValue == 0)
    precondition(GKLeaderboard.TimeScope.week.rawValue == 1)
    precondition(GKLeaderboard.TimeScope.allTime.rawValue == 2)
    precondition(GKLeaderboard.LeaderboardType.classic.rawValue == 0)
    precondition(GKLeaderboard.LeaderboardType.recurring.rawValue == 1)
    precondition(GKLeaderboard.PlayerScope(rawValue: 1) == .friendsOnly)
    precondition(GKLeaderboard.TimeScope(rawValue: 2) == .allTime)
    precondition(GKLeaderboard.LeaderboardType(rawValue: 0) == .classic)
    precondition(GKLeaderboard.PlayerScope.global != .friendsOnly)
    precondition(GKLeaderboard.TimeScope.today != .week)
    precondition(GKLeaderboard.LeaderboardType.classic != .recurring)
    var scopeHasher = Hasher()
    GKLeaderboard.PlayerScope.global.hash(into: &scopeHasher)
    GKLeaderboard.TimeScope.allTime.hash(into: &scopeHasher)
    GKLeaderboard.LeaderboardType.classic.hash(into: &scopeHasher)
    _ = scopeHasher.finalize()

    precondition(GKMatch.SendDataMode.reliable.rawValue == 0)
    precondition(GKMatch.SendDataMode.unreliable.rawValue == 1)
    precondition(GKMatch.SendDataMode(rawValue: 0) == .reliable)
    precondition(GKMatch.SendDataMode.reliable != .unreliable)
    var sendHasher = Hasher()
    GKMatch.SendDataMode.reliable.hash(into: &sendHasher)
    _ = sendHasher.finalize()

    precondition(GKMatchType.peerToPeer.rawValue == 0)
    precondition(GKMatchType.hosted.rawValue == 1)
    precondition(GKMatchType.turnBased.rawValue == 2)
    precondition(GKMatchType(rawValue: 1) == .hosted)
    precondition(GKMatchType.hosted != .turnBased)
    var matchTypeHasher = Hasher()
    GKMatchType.hosted.hash(into: &matchTypeHasher)
    _ = matchTypeHasher.finalize()

    precondition(GKMatchmakingMode.default.rawValue == 0)
    precondition(GKMatchmakingMode.nearbyOnly.rawValue == 1)
    precondition(GKMatchmakingMode.automatchOnly.rawValue == 2)
    precondition(GKMatchmakingMode.inviteOnly.rawValue == 3)
    precondition(GKMatchmakingMode(rawValue: 3) == .inviteOnly)
    precondition(GKMatchmakingMode.nearbyOnly != .inviteOnly)
    var modeHasher = Hasher()
    GKMatchmakingMode.inviteOnly.hash(into: &modeHasher)
    _ = modeHasher.finalize()

    precondition(GKPlayer.PhotoSize.small.rawValue == 0)
    precondition(GKPlayer.PhotoSize.normal.rawValue == 1)
    precondition(GKPlayer.PhotoSize(rawValue: 1) == .normal)
    precondition(GKPlayer.PhotoSize.small != .normal)
    var photoHasher = Hasher()
    GKPlayer.PhotoSize.small.hash(into: &photoHasher)
    _ = photoHasher.finalize()

    precondition(GKPlayerConnectionState.unknown.rawValue == 0)
    precondition(GKPlayerConnectionState.connected.rawValue == 1)
    precondition(GKPlayerConnectionState.disconnected.rawValue == 2)
    precondition(GKPlayerConnectionState(rawValue: 2) == .disconnected)
    precondition(GKPlayerConnectionState.connected != .disconnected)
    var pcsHasher = Hasher()
    GKPlayerConnectionState.connected.hash(into: &pcsHasher)
    _ = pcsHasher.finalize()

    precondition(GKTransportType.unreliable.rawValue == 0)
    precondition(GKTransportType.reliable.rawValue == 1)
    precondition(GKTransportType(rawValue: 1) == .reliable)
    precondition(GKTransportType.reliable != .unreliable)
    var transportHasher = Hasher()
    GKTransportType.reliable.hash(into: &transportHasher)
    _ = transportHasher.finalize()

    precondition(GKTurnBasedExchangeStatus.unknown.rawValue == 0)
    precondition(GKTurnBasedExchangeStatus.active.rawValue == 1)
    precondition(GKTurnBasedExchangeStatus.complete.rawValue == 2)
    precondition(GKTurnBasedExchangeStatus.resolved.rawValue == 3)
    precondition(GKTurnBasedExchangeStatus.canceled.rawValue == 4)
    precondition(GKTurnBasedExchangeStatus(rawValue: 3) == .resolved)
    precondition(GKTurnBasedExchangeStatus.active != .canceled)
    var exchangeHasher = Hasher()
    GKTurnBasedExchangeStatus.active.hash(into: &exchangeHasher)
    _ = exchangeHasher.finalize()

    precondition(GKTurnBasedMatch.Outcome.none.rawValue == 0)
    precondition(GKTurnBasedMatch.Outcome.quit.rawValue == 1)
    precondition(GKTurnBasedMatch.Outcome.won.rawValue == 2)
    precondition(GKTurnBasedMatch.Outcome.lost.rawValue == 3)
    precondition(GKTurnBasedMatch.Outcome.tied.rawValue == 4)
    precondition(GKTurnBasedMatch.Outcome.timeExpired.rawValue == 5)
    precondition(GKTurnBasedMatch.Outcome.first.rawValue == 6)
    precondition(GKTurnBasedMatch.Outcome.second.rawValue == 7)
    precondition(GKTurnBasedMatch.Outcome.third.rawValue == 8)
    precondition(GKTurnBasedMatch.Outcome.fourth.rawValue == 9)
    precondition(GKTurnBasedMatch.Outcome.customRange.rawValue == 0xFF0000)
    precondition(GKTurnBasedMatch.Outcome(rawValue: 2) == .won)
    precondition(GKTurnBasedMatch.Outcome.won != .lost)
    var outcomeHasher = Hasher()
    GKTurnBasedMatch.Outcome.won.hash(into: &outcomeHasher)
    _ = outcomeHasher.finalize()

    precondition(GKTurnBasedMatch.Status.unknown.rawValue == 0)
    precondition(GKTurnBasedMatch.Status.open.rawValue == 1)
    precondition(GKTurnBasedMatch.Status.ended.rawValue == 2)
    precondition(GKTurnBasedMatch.Status.matching.rawValue == 3)
    precondition(GKTurnBasedMatch.Status(rawValue: 1) == .open)
    precondition(GKTurnBasedMatch.Status.open != .ended)
    var statusHasher = Hasher()
    GKTurnBasedMatch.Status.open.hash(into: &statusHasher)
    _ = statusHasher.finalize()

    precondition(GKTurnBasedParticipant.Status.unknown.rawValue == 0)
    precondition(GKTurnBasedParticipant.Status.invited.rawValue == 1)
    precondition(GKTurnBasedParticipant.Status.declined.rawValue == 2)
    precondition(GKTurnBasedParticipant.Status.matching.rawValue == 3)
    precondition(GKTurnBasedParticipant.Status.active.rawValue == 4)
    precondition(GKTurnBasedParticipant.Status.done.rawValue == 5)
    precondition(GKTurnBasedParticipant.Status(rawValue: 4) == .active)
    precondition(GKTurnBasedParticipant.Status.active != .done)
    var partHasher = Hasher()
    GKTurnBasedParticipant.Status.active.hash(into: &partHasher)
    _ = partHasher.finalize()

    precondition(GKVoiceChat.PlayerState.connected.rawValue == 0)
    precondition(GKVoiceChat.PlayerState.disconnected.rawValue == 1)
    precondition(GKVoiceChat.PlayerState.speaking.rawValue == 2)
    precondition(GKVoiceChat.PlayerState.silent.rawValue == 3)
    precondition(GKVoiceChat.PlayerState.connecting.rawValue == 4)
    precondition(GKVoiceChat.PlayerState(rawValue: 2) == .speaking)
    precondition(GKVoiceChat.PlayerState.speaking != .silent)
    var voiceHasher = Hasher()
    GKVoiceChat.PlayerState.speaking.hash(into: &voiceHasher)
    _ = voiceHasher.finalize()
}

func testGKReleaseStateOptionSet() {
    precondition(GKReleaseState.released.rawValue == 1)
    precondition(GKReleaseState.prereleased.rawValue == 2)
    let empty = GKReleaseState()
    precondition(empty.isEmpty)
    precondition(GKReleaseState(rawValue: 0).isEmpty)
    var both: GKReleaseState = [.released, .prereleased]
    precondition(both.contains(.released))
    precondition(both.contains(.prereleased))
    precondition(both.union(.released) == both)
    precondition(both.intersection(.released) == .released)
    precondition(both.symmetricDifference(.released) == .prereleased)
    precondition(both.subtracting(.prereleased) == .released)
    precondition(both.isSuperset(of: .released))
    precondition(both.isSubset(of: [.released, .prereleased]))
    precondition(!both.isStrictSubset(of: .released))
    precondition(both.isStrictSuperset(of: .released))
    precondition(!both.isDisjoint(with: .released))
    both.formUnion(.released)
    both.formIntersection(.prereleased)
    precondition(both == .prereleased)
    both.formSymmetricDifference(.released)
    both.subtract(.released)
    _ = GKReleaseState([.released])
    let inserted = both.insert(.prereleased)
    _ = inserted
    _ = both.update(with: .released)
    _ = both.remove(.released)
    precondition(GKReleaseState.released != .prereleased)
}
