import Foundation
import AVKit
#if canImport(Observation)
import Observation
#endif

private func avkitOnMainView<T>(_ body: @MainActor () -> T) -> T {
    MainActor.assumeIsolated(body)
}

private struct ProbeButtonStyle: ButtonStyle {}
private struct ProbePrimitiveButtonStyle: PrimitiveButtonStyle {}
private struct ProbePickerStyle: PickerStyle {}
private struct ProbeToggleStyle: ToggleStyle {}
private struct ProbeLabelStyle: LabelStyle {}
private struct ProbeLabeledContentStyle: LabeledContentStyle {}
private struct ProbeListStyle: ListStyle {}
private struct ProbeMenuStyle: MenuStyle {}
private struct ProbeFormStyle: FormStyle {}
private struct ProbeGaugeStyle: GaugeStyle {}
private struct ProbeGroupBoxStyle: GroupBoxStyle {}
private struct ProbeIndexViewStyle: IndexViewStyle {}
private struct ProbeProgressViewStyle: ProgressViewStyle {}
private struct ProbeTabViewStyle: TabViewStyle {}
private struct ProbeTableStyle: TableStyle {}
private struct ProbeTextFieldStyle: TextFieldStyle {}
private struct ProbeTextEditorStyle: TextEditorStyle {}
private struct ProbeDatePickerStyle: DatePickerStyle {}
private struct ProbeDisclosureGroupStyle: DisclosureGroupStyle {}
private struct ProbeControlGroupStyle: ControlGroupStyle {}
private struct ProbeNavigationViewStyle: NavigationViewStyle {}
private struct ProbeNavigationSplitViewStyle: NavigationSplitViewStyle {}
private struct ProbeTipViewStyle: TipViewStyle {}
private struct ProbeTextRenderer: TextRenderer {}
private struct ProbeTextSelectability: TextSelectability {}
private struct ProbePref: PreferenceKey { typealias Value = Int }
private struct ProbeLayoutKey: LayoutValueKey { typealias Value = Int }
private final class ProbeObservable: ObservableObject {}
#if canImport(Observation)
@Observable
private final class ProbeObserved {}
#else
private final class ProbeObserved {}
#endif
private struct ProbeChart: AXChartDescriptorRepresentable {}
private struct ProbeFile: FileDocument {}
private struct ProbeUTType: UTType {}
private struct ProbeGesture: Gesture {}
private struct ProbeModifier {}
private struct ProbeFormatting: AttributedTextFormattingDefinition {}
private struct ProbeTransition: Transition {}
private struct ProbeSymbolEffect: SymbolEffect, DiscreteSymbolEffect, IndefiniteSymbolEffect {}
private struct ProbePresentationSizing: PresentationSizing {}
private struct ProbeNavigationTransition: NavigationTransition {}
private struct ProbeScrollTargetBehavior: ScrollTargetBehavior {}
private struct ProbePublisher: Publisher {
    typealias Output = Int
    typealias Failure = Never
}
private struct ProbeItem: Identifiable { var id: Int { 0 } }
private struct ProbeRotorItem: Identifiable {
    var id: Int { 0 }
    var label: String { "probe" }
}
private struct ProbeTransfer: Transferable {}
private struct ProbeKeyframes: Keyframes {}
private struct ProbeInsettableShape: InsettableShape {}
private struct ProbeRoundedShape: RoundedRectangularShape {}
private struct ProbeContentMode: ContentMode {}
private struct ProbeSearchScopeActivation: SearchScopeActivation {}
private struct ProbeDropDelegate: DropDelegate {}
private struct ProbeTaskExecutor: TaskExecutor {}
private struct ProbeToolbar: ToolbarContent {}
private struct ProbeCustomToolbar: CustomizableToolbarContent {}
private struct ProbeRotorContent: AccessibilityRotorContent {}
private struct ProbeLocalizedError: AVKit.LocalizedError {}
private struct ProbeFocusInteractions: FocusInteractions {}
private struct ProbePreviewContext: PreviewContext {}
private struct ProbeAttributeScope: AVKit.AttributeScope {}
private struct ProbeGestureRecognizer: UIGestureRecognizerRepresentable {}

extension Array: AVKit.MutableCollection {}

private let probeIndexRange: Range<String.Index> = {
    let sample = "x"
    return sample.startIndex..<sample.endIndex
}()

extension AVKit.AttributeScopes {
    fileprivate var probeScope: ProbeAttributeScope.Type {
        ProbeAttributeScope.self
    }
}

extension EnvironmentValues {
    var probe: Int {
        get { 0 }
        set { _ = newValue }
    }
}

extension FocusedValues {
    var probe: Int? {
        get { nil }
        set { _ = newValue }
    }
}

extension ContainerValues {
    var probe: Int {
        get { 0 }
        set { _ = newValue }
    }
}

func testVideoPlayerViewSurfaceNoops() {
    avkitOnMainView {
        let video = VideoPlayer(player: nil)
        _ = video.onCameraCaptureEvent(isEnabled: true, primaryAction: { _ in }, secondaryAction: { _ in })
        _ = video.onCameraCaptureEvent(isEnabled: true, defaultSoundDisabled: true, primaryAction: { _ in }, secondaryAction: { _ in })
        _ = video.onCameraCaptureEvent(isEnabled: true, defaultSoundDisabled: true, primaryAction: { _ in }, secondaryAction: { _ in })
        _ = video.onCameraCaptureEvent(isEnabled: true, defaultSoundDisabled: true, action: { _ in })
        _ = video.onCameraCaptureEvent(isEnabled: true, defaultSoundDisabled: true, action: { _ in })
        _ = video.onCameraCaptureEvent(isEnabled: true, action: { _ in })
        _ = video.tipViewStyle(ProbeTipViewStyle())
        _ = video.popoverTip(nil, isPresented: nil, attachmentAnchor: PopoverAttachmentAnchor(), arrowEdges: .all, action: { _ in })
        _ = video.popoverTip(nil, isPresented: nil, attachmentAnchor: PopoverAttachmentAnchor(), arrowEdge: nil as Edge?, action: { _ in })
        _ = video.popoverTip(nil, arrowEdge: nil as Edge?, action: { _ in })
        _ = video.tipImageSize(.zero)
        _ = video.tipBackground(Color())
        _ = video.tipImageStyle(Color())
        _ = video.tipImageStyle(Color(), Color(), Color())
        _ = video.tipImageStyle(Color(), Color())
        _ = video.tipCornerRadius(0, antialiased: true)
        _ = video.tipBackgroundInteraction(PresentationBackgroundInteraction())
        _ = video.tipAnchor(0)
        _ = video.navigationViewStyle(ProbeNavigationViewStyle())
        _ = video.navigationSplitViewColumnWidth(min: nil as CGFloat?, ideal: 0, max: nil as CGFloat?)
        _ = video.navigationSplitViewColumnWidth(0)
        _ = video.navigationSplitViewStyle(ProbeNavigationSplitViewStyle())
        _ = video.tabViewCustomization(nil)
        _ = video.tabViewSidebarFooter(content: { EmptyView() })
        _ = video.tabViewSidebarHeader(content: { EmptyView() })
        _ = video.tabViewBottomAccessory(content: { EmptyView() })
        _ = video.tabViewSearchActivation(TabSearchActivation())
        _ = video.tabViewSidebarBottomBar(content: { EmptyView() })
        _ = video.tabViewStyle(ProbeTabViewStyle())
        _ = video.indexViewStyle(ProbeIndexViewStyle())
        _ = video.progressViewStyle(ProbeProgressViewStyle())
        _ = video.background(ignoresSafeAreaEdges: .all)
        _ = video.background(in: ProbeInsettableShape(), fillStyle: FillStyle())
        _ = video.background(in: DefaultGlassEffectShape(), fillStyle: FillStyle())
        _ = video.background(alignment: Alignment.center, content: { EmptyView() })
        _ = video.background(Color(), ignoresSafeAreaEdges: .all)
        _ = video.background(Color(), in: ProbeInsettableShape(), fillStyle: FillStyle())
        _ = video.background(Color(), in: DefaultGlassEffectShape(), fillStyle: FillStyle())
        _ = video.background(EmptyView(), alignment: Alignment.center)
        _ = video.brightness(0)
        _ = video.dialogIcon(nil as Image?)
        _ = video.fontDesign(nil as Font.Design?)
        _ = video.fontWeight(nil as Font.Weight?)
        _ = video.gaugeStyle(ProbeGaugeStyle())
        _ = video.imageScale(Image.Scale())
        _ = video.labelStyle(ProbeLabelStyle())
        _ = video.lineHeight(nil as AttributedString.LineHeight?)
        _ = video.monospaced(true)
        _ = video.onKeyPress(characters: CharacterSet(), phases: KeyPress.Phases(), action: { _ in KeyPress.Result() })
        _ = video.onKeyPress(keys: Set<KeyEquivalent>(), phases: KeyPress.Phases(), action: { _ in KeyPress.Result() })
        _ = video.onKeyPress(phases: KeyPress.Phases(), action: { _ in KeyPress.Result() })
        _ = video.onKeyPress(KeyEquivalent(), action: { KeyPress.Result() })
        _ = video.onKeyPress(KeyEquivalent(), phases: KeyPress.Phases(), action: { _ in KeyPress.Result() })
        _ = video.preference(key: ProbePref.self, value: 0)
        _ = video.saturation(0)
        _ = video.searchable(text: Binding(wrappedValue: "probe"), isPresented: Binding(wrappedValue: true), placement: .automatic, prompt: LocalizedStringResource("probe"))
        _ = video.searchable(text: Binding(wrappedValue: "probe"), isPresented: Binding(wrappedValue: true), placement: .automatic, prompt: LocalizedStringKey("probe"))
        _ = video.searchable(text: Binding(wrappedValue: "probe"), isPresented: Binding(wrappedValue: true), placement: .automatic, prompt: nil as Text?)
        _ = video.searchable(text: Binding(wrappedValue: "probe"), isPresented: Binding(wrappedValue: true), placement: .automatic, prompt: "probe")
        _ = video.searchable(text: Binding(wrappedValue: "probe"), editableTokens: Binding(wrappedValue: [ProbeItem()]), isPresented: Binding(wrappedValue: true), placement: .automatic, prompt: LocalizedStringResource("probe"), token: { _ in EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), editableTokens: Binding(wrappedValue: [ProbeItem()]), isPresented: Binding(wrappedValue: true), placement: .automatic, prompt: LocalizedStringKey("probe"), token: { _ in EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), editableTokens: Binding(wrappedValue: [ProbeItem()]), isPresented: Binding(wrappedValue: true), placement: .automatic, prompt: nil as Text?, token: { _ in EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), editableTokens: Binding(wrappedValue: [ProbeItem()]), isPresented: Binding(wrappedValue: true), placement: .automatic, prompt: "probe", token: { _ in EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), editableTokens: Binding(wrappedValue: [ProbeItem()]), placement: .automatic, prompt: LocalizedStringResource("probe"), token: { _ in EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), editableTokens: Binding(wrappedValue: [ProbeItem()]), placement: .automatic, prompt: LocalizedStringKey("probe"), token: { _ in EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), editableTokens: Binding(wrappedValue: [ProbeItem()]), placement: .automatic, prompt: nil as Text?, token: { _ in EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), editableTokens: Binding(wrappedValue: [ProbeItem()]), placement: .automatic, prompt: "probe", token: { _ in EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), tokens: Binding(wrappedValue: [ProbeItem()]), isPresented: Binding(wrappedValue: true), placement: .automatic, prompt: LocalizedStringResource("probe"), token: { _ in EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), tokens: Binding(wrappedValue: [ProbeItem()]), isPresented: Binding(wrappedValue: true), placement: .automatic, prompt: LocalizedStringKey("probe"), token: { _ in EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), tokens: Binding(wrappedValue: [ProbeItem()]), isPresented: Binding(wrappedValue: true), placement: .automatic, prompt: nil as Text?, token: { _ in EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), tokens: Binding(wrappedValue: [ProbeItem()]), isPresented: Binding(wrappedValue: true), placement: .automatic, prompt: "probe", token: { _ in EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), tokens: Binding(wrappedValue: [ProbeItem()]), suggestedTokens: Binding(wrappedValue: [ProbeItem()]), isPresented: Binding(wrappedValue: true), placement: .automatic, prompt: LocalizedStringResource("probe"), token: { _ in EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), tokens: Binding(wrappedValue: [ProbeItem()]), suggestedTokens: Binding(wrappedValue: [ProbeItem()]), isPresented: Binding(wrappedValue: true), placement: .automatic, prompt: LocalizedStringKey("probe"), token: { _ in EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), tokens: Binding(wrappedValue: [ProbeItem()]), suggestedTokens: Binding(wrappedValue: [ProbeItem()]), isPresented: Binding(wrappedValue: true), placement: .automatic, prompt: nil as Text?, token: { _ in EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), tokens: Binding(wrappedValue: [ProbeItem()]), suggestedTokens: Binding(wrappedValue: [ProbeItem()]), isPresented: Binding(wrappedValue: true), placement: .automatic, prompt: "probe", token: { _ in EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), tokens: Binding(wrappedValue: [ProbeItem()]), suggestedTokens: Binding(wrappedValue: [ProbeItem()]), placement: .automatic, prompt: LocalizedStringResource("probe"), token: { _ in EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), tokens: Binding(wrappedValue: [ProbeItem()]), suggestedTokens: Binding(wrappedValue: [ProbeItem()]), placement: .automatic, prompt: LocalizedStringKey("probe"), token: { _ in EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), tokens: Binding(wrappedValue: [ProbeItem()]), suggestedTokens: Binding(wrappedValue: [ProbeItem()]), placement: .automatic, prompt: nil as Text?, token: { _ in EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), tokens: Binding(wrappedValue: [ProbeItem()]), suggestedTokens: Binding(wrappedValue: [ProbeItem()]), placement: .automatic, prompt: "probe", token: { _ in EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), tokens: Binding(wrappedValue: [ProbeItem()]), placement: .automatic, prompt: LocalizedStringResource("probe"), token: { _ in EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), tokens: Binding(wrappedValue: [ProbeItem()]), placement: .automatic, prompt: LocalizedStringKey("probe"), token: { _ in EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), tokens: Binding(wrappedValue: [ProbeItem()]), placement: .automatic, prompt: nil as Text?, token: { _ in EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), tokens: Binding(wrappedValue: [ProbeItem()]), placement: .automatic, prompt: "probe", token: { _ in EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), placement: .automatic, prompt: LocalizedStringKey("probe"), suggestions: { EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), placement: .automatic, prompt: nil as Text?, suggestions: { EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), placement: .automatic, prompt: "probe", suggestions: { EmptyView() })
        _ = video.searchable(text: Binding(wrappedValue: "probe"), placement: .automatic, prompt: LocalizedStringResource("probe"))
        _ = video.searchable(text: Binding(wrappedValue: "probe"), placement: .automatic, prompt: LocalizedStringKey("probe"))
        _ = video.searchable(text: Binding(wrappedValue: "probe"), placement: .automatic, prompt: nil as Text?)
        _ = video.searchable(text: Binding(wrappedValue: "probe"), placement: .automatic, prompt: "probe")
        _ = video.tableStyle(ProbeTableStyle())
        _ = video.transition(AnyTransition())
        _ = video.transition(ProbeTransition())
        _ = video.unredacted()
        _ = video.accentColor(nil as Color?)
        _ = video.actionSheet(isPresented: Binding(wrappedValue: true), content: { ActionSheet() })
        _ = video.actionSheet(item: Binding(wrappedValue: nil as ProbeItem?), content: { _ in ActionSheet() })
        _ = video.aspectRatio(nil as CGFloat?, contentMode: ProbeContentMode())
        _ = video.aspectRatio(.zero, contentMode: ProbeContentMode())
        _ = video.buttonStyle(ProbePrimitiveButtonStyle())
        _ = video.buttonStyle(ProbeButtonStyle())
        _ = video.colorEffect(Shader(), isEnabled: true)
        _ = video.colorInvert()
        _ = video.colorScheme(ColorScheme())
        _ = video.contextMenu(forSelectionType: Int.self, menu: { _ in EmptyView() }, primaryAction: nil)
        _ = video.contextMenu(menuItems: { EmptyView() }, preview: { EmptyView() })
        _ = video.contextMenu(menuItems: { EmptyView() })
        _ = video.contextMenu(nil as ContextMenu<EmptyView>?)
        _ = video.controlSize(ControlSize())
        _ = video.controlSize(ControlSize()...ControlSize())
        _ = video.environment(nil as ProbeObserved?)
        _ = video.environment(\.probe, 0)
        _ = video.glassEffect(.regular, in: DefaultGlassEffectShape())
        _ = video.hoverEffect(.automatic, isEnabled: true)
        _ = video.hoverEffect(.automatic, isEnabled: true)
        _ = video.hoverEffect(.automatic)
        _ = video.hueRotation(Angle())
        _ = video.layerEffect(Shader(), maxSampleOffset: .zero, isEnabled: true)
        _ = video.layoutValue(key: ProbeLayoutKey.self, value: 0)
        _ = video.lineSpacing(0)
        _ = video.onDisappear(perform: nil)
        _ = video.pickerStyle(ProbePickerStyle())
        _ = video.refreshable(action: {})
        _ = video.safeAreaBar(edge: VerticalEdge(), alignment: HorizontalAlignment.center, spacing: nil as CGFloat?, content: { EmptyView() })
        _ = video.safeAreaBar(edge: .trailing, alignment: VerticalAlignment.center, spacing: nil as CGFloat?, content: { EmptyView() })
        _ = video.scaleEffect(x: 0, y: 0, anchor: UnitPoint.center)
        _ = video.scaleEffect(0, anchor: UnitPoint.center)
        _ = video.scaleEffect(.zero, anchor: UnitPoint.center)
        _ = video.scaledToFit()
        _ = video.submitLabel(SubmitLabel())
        _ = video.submitScope(true)
        _ = video.toggleStyle(ProbeToggleStyle())
        _ = video.toolbarRole(ToolbarRole())
        _ = video.transaction(value: 0, { _ in })
        _ = video.transaction({ _ in }, body: { _ in EmptyView() })
        _ = video.transaction({ _ in })
        _ = video.buttonSizing(ButtonSizing())
        _ = video.contentShape(DefaultGlassEffectShape(), eoFill: true)
        _ = video.contentShape(ContentShapeKinds(), DefaultGlassEffectShape(), eoFill: true)
        _ = video.cornerRadius(0, antialiased: true)
        _ = video.defaultFocus(FocusState<Int>.Binding(), 0, priority: .automatic)
        _ = video.drawingGroup(opaque: true, colorMode: .nonLinear)
        _ = video.fileExporter(isPresented: Binding(wrappedValue: true), item: nil as ProbeTransfer?, contentTypes: [ProbeUTType() as any UTType], defaultFilename: nil as String?, onCompletion: { _ in }, onCancellation: {})
        _ = video.fileExporter(isPresented: Binding(wrappedValue: true), items: [ProbeTransfer()], contentTypes: [ProbeUTType() as any UTType], onCompletion: { _ in }, onCancellation: {})
        _ = video.fileExporter(isPresented: Binding(wrappedValue: true), document: nil as ProbeFile?, contentType: ProbeUTType() as any UTType, defaultFilename: nil as String?, onCompletion: { _ in })
        _ = video.fileExporter(isPresented: Binding(wrappedValue: true), document: nil as ProbeFile?, contentType: ProbeUTType() as any UTType, defaultFilename: nil as String?, onCompletion: { _ in })
        _ = video.fileExporter(isPresented: Binding(wrappedValue: true), document: nil as ProbeFile?, contentTypes: [ProbeUTType() as any UTType], defaultFilename: nil as String?, onCompletion: { _ in }, onCancellation: {})
        _ = video.fileExporter(isPresented: Binding(wrappedValue: true), document: nil as ProbeFile?, contentTypes: [ProbeUTType() as any UTType], defaultFilename: nil as String?, onCompletion: { _ in }, onCancellation: {})
        _ = video.fileExporter(isPresented: Binding(wrappedValue: true), documents: [ProbeFile()], contentType: ProbeUTType() as any UTType, onCompletion: { _ in })
        _ = video.fileExporter(isPresented: Binding(wrappedValue: true), documents: [ProbeFile()], contentType: ProbeUTType() as any UTType, onCompletion: { _ in })
        _ = video.fileExporter(isPresented: Binding(wrappedValue: true), documents: [ProbeFile()], contentTypes: [ProbeUTType() as any UTType], onCompletion: { _ in }, onCancellation: {})
        _ = video.fileExporter(isPresented: Binding(wrappedValue: true), documents: [ProbeFile()], contentTypes: [ProbeUTType() as any UTType], onCompletion: { _ in }, onCancellation: {})
        _ = video.fileImporter(isPresented: Binding(wrappedValue: true), allowedContentTypes: [ProbeUTType() as any UTType], onCompletion: { _ in })
        _ = video.fileImporter(isPresented: Binding(wrappedValue: true), allowedContentTypes: [ProbeUTType() as any UTType], allowsMultipleSelection: true, onCompletion: { _ in }, onCancellation: {})
        _ = video.fileImporter(isPresented: Binding(wrappedValue: true), allowedContentTypes: [ProbeUTType() as any UTType], allowsMultipleSelection: true, onCompletion: { _ in })
        _ = video.findDisabled(true)
        _ = video.focusedValue(nil as ProbeObserved?)
        _ = video.focusedValue(\.probe, nil as Int?)
        _ = video.focusedValue(\.probe, 0)
        _ = video.itemProvider(nil)
        _ = video.keyboardType(UIKeyboardType())
        _ = video.labelsHidden()
        _ = video.listItemTint(nil as ListItemTint?)
        _ = video.listItemTint(nil as Color?)
        _ = video.moveDisabled(true)
        _ = video.onTapGesture(count: 0, coordinateSpace: .local, perform: { _ in })
        _ = video.onTapGesture(count: 0, coordinateSpace: .local, perform: { _ in })
        _ = video.onTapGesture(count: 0, perform: {})
        _ = video.renameAction(FocusState<Bool>.Binding())
        _ = video.renameAction({})
        _ = video.scaledToFill()
        _ = video.scenePadding(ScenePadding(), edges: .all)
        _ = video.scenePadding(.all)
        _ = video.searchScopes(Binding(wrappedValue: 0), activation: ProbeSearchScopeActivation(), { EmptyView() })
        _ = video.searchScopes(Binding(wrappedValue: 0), scopes: { EmptyView() })
        _ = video.swipeActions(edge: .trailing, allowsFullSwipe: true, content: { EmptyView() })
        _ = video.symbolEffect(ProbeSymbolEffect(), options: SymbolEffectOptions(), value: 0)
        _ = video.symbolEffect(ProbeSymbolEffect(), options: SymbolEffectOptions(), isActive: true)
        _ = video.textRenderer(ProbeTextRenderer())
        _ = video.userActivity("probe", element: nil as Int?, { _, _ in })
        _ = video.userActivity("probe", isActive: true, { _ in })
        _ = video.visualEffect({ _, _ in EmptyVisualEffect() })
        _ = video.accessibility(identifier: "probe")
        _ = video.accessibility(inputLabels: [Text()])
        _ = video.accessibility(removeTraits: AccessibilityTraits())
        _ = video.accessibility(sortPriority: 0)
        _ = video.accessibility(activationPoint: UnitPoint.center)
        _ = video.accessibility(activationPoint: .zero)
        _ = video.accessibility(selectionIdentifier: 0)
        _ = video.accessibility(hint: Text())
        _ = video.accessibility(label: Text())
        _ = video.accessibility(value: Text())
        _ = video.accessibility(hidden: true)
        _ = video.accessibility(addTraits: AccessibilityTraits())
        _ = video.colorMultiply(Color())
        _ = video.findNavigator(isPresented: Binding(wrappedValue: true))
        _ = video.focusedObject(ProbeObservable())
        _ = video.focusedObject(nil as ProbeObservable?)
        _ = video.geometryGroup()
        _ = video.glassEffectID(0 as Int?, in: Namespace.ID())
        _ = video.groupBoxStyle(ProbeGroupBoxStyle())
        _ = video.listRowInsets(nil as EdgeInsets?)
        _ = video.listRowInsets(.all, nil as CGFloat?)
        _ = video.menuIndicator(.automatic)
        _ = video.phaseAnimator([false], content: { _, _ in EmptyView() }, animation: { (_: Bool) in .default })
        _ = video.phaseAnimator([false], trigger: 0, content: { _, _ in EmptyView() }, animation: { (_: Bool) in .default })
        _ = video.previewDevice(nil as PreviewDevice?)
        _ = video.previewLayout(PreviewLayout())
        _ = video.safeAreaInset(edge: VerticalEdge(), alignment: HorizontalAlignment.center, spacing: nil as CGFloat?, content: { EmptyView() })
        _ = video.safeAreaInset(edge: .trailing, alignment: VerticalAlignment.center, spacing: nil as CGFloat?, content: { EmptyView() })
        _ = video.searchFocused(FocusState<Int>.Binding(), equals: 0)
        _ = video.searchFocused(FocusState<Bool>.Binding())
        _ = video.strikethrough(true, pattern: .solid, color: nil as Color?)
        _ = video.symbolVariant(SymbolVariants())
        _ = video.textSelection(ProbeTextSelectability())
        _ = video.alignmentGuide(VerticalAlignment.center, computeValue: { _ in 0 })
        _ = video.alignmentGuide(HorizontalAlignment.center, computeValue: { _ in 0 })
        _ = video.baselineOffset(0)
        _ = video.containerShape(ProbeInsettableShape())
        _ = video.containerShape(ProbeRoundedShape())
        _ = video.containerValue(\.probe, 0)
        _ = video.contentMargins(0, for: ContentMarginPlacement())
        _ = video.contentMargins(.all, nil as CGFloat?, for: ContentMarginPlacement())
        _ = video.contentMargins(.all, EdgeInsets(), for: ContentMarginPlacement())
        _ = video.contentToolbar(for: ContentToolbarPlacement(), content: { ProbeToolbar() })
        _ = video.contentToolbar(for: ContentToolbarPlacement(), content: { EmptyView() })
        _ = video.deleteDisabled(true)
        _ = video.gridCellAnchor(UnitPoint.center)
        _ = video.layoutPriority(0)
        _ = video.listRowSpacing(nil as CGFloat?)
        _ = video.previewContext(ProbePreviewContext())
        _ = video.rotationEffect(Angle(), anchor: UnitPoint.center)
        _ = video.scrollDisabled(true)
        _ = video.scrollPosition(id: Binding(wrappedValue: nil as Int?), anchor: nil as UnitPoint?)
        _ = video.scrollPosition(Binding(wrappedValue: ScrollPosition()), anchor: nil as UnitPoint?)
        _ = video.sectionActions(content: { EmptyView() })
        _ = video.textFieldStyle(ProbeTextFieldStyle())
        _ = video.truncationMode(Text.TruncationMode())
        _ = video.backgroundStyle(Color())
        _ = video.badgeProminence(BadgeProminence())
        _ = video.coordinateSpace(name: 0)
        _ = video.coordinateSpace(NamedCoordinateSpace())
        _ = video.datePickerStyle(ProbeDatePickerStyle())
        _ = video.dropDestination(for: ProbeTransfer.self, action: { _, _ in true }, isTargeted: { _ in })
        _ = video.dropDestination(for: ProbeTransfer.self, isEnabled: true, action: { _, _ in })
        _ = video.dynamicTypeSize(DynamicTypeSize())
        _ = video.dynamicTypeSize(DynamicTypeSize()...DynamicTypeSize())
        _ = video.foregroundColor(nil as Color?)
        _ = video.foregroundStyle(Color())
        _ = video.foregroundStyle(Color(), Color(), Color())
        _ = video.foregroundStyle(Color(), Color())
        _ = video.fullScreenCover(isPresented: Binding(wrappedValue: true), onDismiss: nil, content: { EmptyView() })
        _ = video.fullScreenCover(item: Binding(wrappedValue: nil as ProbeItem?), onDismiss: nil, content: { _ in EmptyView() })
        _ = video.gridCellColumns(0)
        _ = video.ignoresSafeArea(SafeAreaRegions(), edges: .all)
        _ = video.monospacedDigit()
        _ = video.navigationTitle(LocalizedStringResource("probe"))
        _ = video.navigationTitle(LocalizedStringKey("probe"))
        _ = video.navigationTitle(Text())
        _ = video.navigationTitle(Binding(wrappedValue: "probe"))
        _ = video.navigationTitle("probe")
        _ = video.navigationTitle({ EmptyView() })
        _ = video.onPencilSqueeze(perform: { _ in })
        _ = video.replaceDisabled(true)
        _ = video.safeAreaPadding(0)
        _ = video.safeAreaPadding(EdgeInsets())
        _ = video.safeAreaPadding(.all, nil as CGFloat?)
        _ = video.searchSelection(Binding(wrappedValue: nil as TextSelection?))
        _ = video.sensoryFeedback(trigger: 0, { _, _ in nil })
        _ = video.sensoryFeedback(trigger: 0, { nil })
        _ = video.sensoryFeedback(SensoryFeedback(), trigger: 0, condition: { _, _ in true })
        _ = video.sensoryFeedback(SensoryFeedback(), trigger: 0)
        _ = video.statusBarHidden(true)
        _ = video.textContentType(nil as UITextContentType?)
        _ = video.textEditorStyle(ProbeTextEditorStyle())
        _ = video.transformEffect(CGAffineTransform())
        _ = video.allowsHitTesting(true)
        _ = video.allowsTightening(true)
        _ = video.anchorPreference(key: ProbePref.self, value: Anchor<Int>.Source(), transform: { _ in 0 })
        _ = video.compositingGroup()
        _ = video.distortionEffect(Shader(), maxSampleOffset: .zero, isEnabled: true)
        _ = video.glassEffectUnion(id: 0 as Int?, namespace: Namespace.ID())
        _ = video.headerProminence(Prominence())
        _ = video.keyboardShortcut(KeyEquivalent(), modifiers: .command, localization: KeyboardShortcut.Localization())
        _ = video.keyboardShortcut(KeyEquivalent(), modifiers: .command)
        _ = video.keyboardShortcut(KeyboardShortcut())
        _ = video.keyboardShortcut(nil as KeyboardShortcut?)
        _ = video.keyframeAnimator(initialValue: 0, trigger: 0, content: { _, _ in EmptyView() }, keyframes: { _ in ProbeKeyframes() })
        _ = video.keyframeAnimator(initialValue: 0, repeating: true, content: { _, _ in EmptyView() }, keyframes: { _ in ProbeKeyframes() })
        _ = video.labelsVisibility(.automatic)
        _ = video.listRowSeparator(.automatic, edges: .all)
        _ = video.luminanceToAlpha()
        _ = video.onGeometryChange(for: Int.self, of: { _ in 0 }, action: { _, _ in })
        _ = video.onGeometryChange(for: Int.self, of: { _ in 0 }, action: { _ in })
        _ = video.privacySensitive(true)
        _ = video.projectionEffect(ProjectionTransform())
        _ = video.rotation3DEffect(Angle(), axis: (x: 0, y: 0, z: 0), anchor: UnitPoint.center, anchorZ: 0, perspective: 0)
        _ = video.scrollIndicators(ScrollIndicatorVisibility(), axes: .horizontal)
        _ = video.scrollTransition(topLeading: .interactive, bottomTrailing: .interactive, axis: nil as Axis?, transition: { _, _ in EmptyVisualEffect() })
        _ = video.scrollTransition(.interactive, axis: nil as Axis?, transition: { _, _ in EmptyVisualEffect() })
        _ = video.searchCompletion("probe")
        _ = video.searchCompletion(ProbeItem())
        _ = video.toolbarTitleMenu(content: { EmptyView() })
        _ = video.writingDirection(strategy: Text.WritingDirectionStrategy())
        _ = video.accessibilityHint(LocalizedStringResource("probe"), isEnabled: true)
        _ = video.accessibilityHint(LocalizedStringKey("probe"), isEnabled: true)
        _ = video.accessibilityHint(Text(), isEnabled: true)
        _ = video.accessibilityHint("probe", isEnabled: true)
        _ = video.accessibilityHint(LocalizedStringResource("probe"))
        _ = video.accessibilityHint(LocalizedStringKey("probe"))
        _ = video.accessibilityHint(Text())
        _ = video.accessibilityHint("probe")
        _ = video.buttonBorderShape(ButtonBorderShape())
        _ = video.contentTransition(ContentTransition())
        _ = video.controlGroupStyle(ProbeControlGroupStyle())
        _ = video.defaultAppStorage(UserDefaults.standard)
        _ = video.environmentObject(ProbeObservable())
        _ = video.fileDialogMessage(LocalizedStringResource("probe"))
        _ = video.fileDialogMessage(LocalizedStringKey("probe"))
        _ = video.fileDialogMessage(nil as Text?)
        _ = video.fileDialogMessage("probe")
        _ = video.focusedSceneValue(nil as ProbeObserved?)
        _ = video.focusedSceneValue(\.probe, nil as Int?)
        _ = video.focusedSceneValue(\.probe, 0)
        _ = video.listRowBackground(nil as EmptyView?)
        _ = video.onContinuousHover(coordinateSpace: .local, perform: { _ in })
        _ = video.onContinuousHover(coordinateSpace: .local, perform: { _ in })
        _ = video.onPencilDoubleTap(perform: { _ in })
        _ = video.searchSuggestions(.automatic, for: .all)
        _ = video.searchSuggestions({ EmptyView() })
        _ = video.sectionIndexLabel(nil as Text?)
        _ = video.sectionIndexLabel(nil as String?)
        _ = video.selectionDisabled(true)
        _ = video.toolbarBackground(.automatic, for: ToolbarPlacement())
        _ = video.toolbarBackground(Color(), for: ToolbarPlacement())
        _ = video.toolbarVisibility(.automatic, for: ToolbarPlacement())
        _ = video.accessibilityLabel(content: { _ in EmptyView() })
        _ = video.accessibilityLabel(LocalizedStringResource("probe"), isEnabled: true)
        _ = video.accessibilityLabel(LocalizedStringKey("probe"), isEnabled: true)
        _ = video.accessibilityLabel(Text(), isEnabled: true)
        _ = video.accessibilityLabel("probe", isEnabled: true)
        _ = video.accessibilityLabel(LocalizedStringResource("probe"))
        _ = video.accessibilityLabel(LocalizedStringKey("probe"))
        _ = video.accessibilityLabel(Text())
        _ = video.accessibilityLabel("probe")
        _ = video.accessibilityRotor(LocalizedStringResource("probe"), textRanges: [probeIndexRange])
        _ = video.accessibilityRotor(AccessibilitySystemRotor(), textRanges: [probeIndexRange])
        _ = video.accessibilityRotor(LocalizedStringKey("probe"), textRanges: [probeIndexRange])
        _ = video.accessibilityRotor(Text(), textRanges: [probeIndexRange])
        _ = video.accessibilityRotor("probe", textRanges: [probeIndexRange])
        _ = video.accessibilityRotor(LocalizedStringResource("probe"), entries: [ProbeRotorItem()], entryLabel: \.label)
        _ = video.accessibilityRotor(AccessibilitySystemRotor(), entries: [ProbeRotorItem()], entryLabel: \.label)
        _ = video.accessibilityRotor(LocalizedStringKey("probe"), entries: [ProbeRotorItem()], entryLabel: \.label)
        _ = video.accessibilityRotor(Text(), entries: [ProbeRotorItem()], entryLabel: \.label)
        _ = video.accessibilityRotor("probe", entries: [ProbeRotorItem()], entryLabel: \.label)
        _ = video.accessibilityRotor(LocalizedStringResource("probe"), entries: [ProbeRotorItem()], entryID: \.id, entryLabel: \.label)
        _ = video.accessibilityRotor(AccessibilitySystemRotor(), entries: [ProbeRotorItem()], entryID: \.id, entryLabel: \.label)
        _ = video.accessibilityRotor(LocalizedStringKey("probe"), entries: [ProbeRotorItem()], entryID: \.id, entryLabel: \.label)
        _ = video.accessibilityRotor(Text(), entries: [ProbeRotorItem()], entryID: \.id, entryLabel: \.label)
        _ = video.accessibilityRotor("probe", entries: [ProbeRotorItem()], entryID: \.id, entryLabel: \.label)
        _ = video.accessibilityRotor(LocalizedStringResource("probe"), entries: { ProbeRotorContent() })
        _ = video.accessibilityRotor(AccessibilitySystemRotor(), entries: { ProbeRotorContent() })
        _ = video.accessibilityRotor(LocalizedStringKey("probe"), entries: { ProbeRotorContent() })
        _ = video.accessibilityRotor(Text(), entries: { ProbeRotorContent() })
        _ = video.accessibilityRotor("probe", entries: { ProbeRotorContent() })
        _ = video.accessibilityValue(LocalizedStringResource("probe"), isEnabled: true)
        _ = video.accessibilityValue(LocalizedStringKey("probe"), isEnabled: true)
        _ = video.accessibilityValue(Text(), isEnabled: true)
        _ = video.accessibilityValue("probe", isEnabled: true)
        _ = video.accessibilityValue(LocalizedStringResource("probe"))
        _ = video.accessibilityValue(LocalizedStringKey("probe"))
        _ = video.accessibilityValue(Text())
        _ = video.accessibilityValue("probe")
        _ = video.autocapitalization(UITextAutocapitalizationType())
        _ = video.confirmationDialog(LocalizedStringResource("probe"), isPresented: Binding(wrappedValue: true), titleVisibility: .automatic, presenting: nil as Int?, actions: { _ in EmptyView() }, message: { _ in EmptyView() })
        _ = video.confirmationDialog(LocalizedStringKey("probe"), isPresented: Binding(wrappedValue: true), titleVisibility: .automatic, presenting: nil as Int?, actions: { _ in EmptyView() }, message: { _ in EmptyView() })
        _ = video.confirmationDialog(Text(), isPresented: Binding(wrappedValue: true), titleVisibility: .automatic, presenting: nil as Int?, actions: { _ in EmptyView() }, message: { _ in EmptyView() })
        _ = video.confirmationDialog("probe", isPresented: Binding(wrappedValue: true), titleVisibility: .automatic, presenting: nil as Int?, actions: { _ in EmptyView() }, message: { _ in EmptyView() })
        _ = video.confirmationDialog(LocalizedStringResource("probe"), isPresented: Binding(wrappedValue: true), titleVisibility: .automatic, presenting: nil as Int?, actions: { _ in EmptyView() })
        _ = video.confirmationDialog(LocalizedStringKey("probe"), isPresented: Binding(wrappedValue: true), titleVisibility: .automatic, presenting: nil as Int?, actions: { _ in EmptyView() })
        _ = video.confirmationDialog(Text(), isPresented: Binding(wrappedValue: true), titleVisibility: .automatic, presenting: nil as Int?, actions: { _ in EmptyView() })
        _ = video.confirmationDialog("probe", isPresented: Binding(wrappedValue: true), titleVisibility: .automatic, presenting: nil as Int?, actions: { _ in EmptyView() })
        _ = video.confirmationDialog(LocalizedStringResource("probe"), isPresented: Binding(wrappedValue: true), titleVisibility: .automatic, actions: { EmptyView() }, message: { EmptyView() })
        _ = video.confirmationDialog(LocalizedStringKey("probe"), isPresented: Binding(wrappedValue: true), titleVisibility: .automatic, actions: { EmptyView() }, message: { EmptyView() })
        _ = video.confirmationDialog(Text(), isPresented: Binding(wrappedValue: true), titleVisibility: .automatic, actions: { EmptyView() }, message: { EmptyView() })
        _ = video.confirmationDialog("probe", isPresented: Binding(wrappedValue: true), titleVisibility: .automatic, actions: { EmptyView() }, message: { EmptyView() })
        _ = video.confirmationDialog(LocalizedStringResource("probe"), isPresented: Binding(wrappedValue: true), titleVisibility: .automatic, actions: { EmptyView() })
        _ = video.confirmationDialog(LocalizedStringKey("probe"), isPresented: Binding(wrappedValue: true), titleVisibility: .automatic, actions: { EmptyView() })
        _ = video.confirmationDialog(Text(), isPresented: Binding(wrappedValue: true), titleVisibility: .automatic, actions: { EmptyView() })
        _ = video.confirmationDialog("probe", isPresented: Binding(wrappedValue: true), titleVisibility: .automatic, actions: { EmptyView() })
        _ = video.defaultHoverEffect(nil as HoverEffect?)
        _ = video.defaultHoverEffect(.automatic)
        _ = video.focusedSceneObject(ProbeObservable())
        _ = video.focusedSceneObject(nil as ProbeObservable?)
        _ = video.listSectionMargins(.all, nil as CGFloat?)
        _ = video.listSectionSpacing(0)
        _ = video.listSectionSpacing(ListSectionSpacing())
        _ = video.minimumScaleFactor(0)
        _ = video.navigationBarItems(leading: EmptyView(), trailing: EmptyView())
        _ = video.navigationBarItems(leading: EmptyView())
        _ = video.navigationBarItems(trailing: EmptyView())
        _ = video.navigationBarTitle(LocalizedStringKey("probe"), displayMode: NavigationBarItem.TitleDisplayMode())
        _ = video.navigationBarTitle(Text(), displayMode: NavigationBarItem.TitleDisplayMode())
        _ = video.navigationBarTitle("probe", displayMode: NavigationBarItem.TitleDisplayMode())
        _ = video.navigationBarTitle(LocalizedStringKey("probe"))
        _ = video.navigationBarTitle(Text())
        _ = video.navigationBarTitle("probe")
        _ = video.navigationDocument(ProbeTransfer(), preview: SharePreview<ProbeTransfer, ProbeTransfer>())
        _ = video.navigationDocument(ProbeTransfer(), preview: SharePreview<ProbeTransfer, Never>())
        _ = video.navigationDocument(ProbeTransfer(), preview: SharePreview<Never, Never>())
        _ = video.navigationDocument(ProbeTransfer(), preview: SharePreview<Never, ProbeTransfer>())
        _ = video.navigationDocument(URL(fileURLWithPath: "/"))
        _ = video.navigationDocument(ProbeTransfer())
        _ = video.navigationSubtitle(LocalizedStringResource("probe"))
        _ = video.navigationSubtitle(LocalizedStringKey("probe"))
        _ = video.navigationSubtitle(Text())
        _ = video.navigationSubtitle("probe")
        _ = video.onLongPressGesture(minimumDuration: 0, maximumDistance: 0, perform: {}, onPressingChanged: nil)
        _ = video.onLongPressGesture(minimumDuration: 0, maximumDistance: 0, pressing: nil, perform: {})
        _ = video.onLongPressGesture(minimumDuration: 0, perform: {}, onPressingChanged: nil)
        _ = video.onLongPressGesture(minimumDuration: 0, pressing: nil, perform: {})
        _ = video.onPreferenceChange(ProbePref.self, perform: { _ in })
        _ = video.presentationSizing(ProbePresentationSizing())
        _ = video.previewDisplayName(nil as String?)
        _ = video.scrollClipDisabled(true)
        _ = video.scrollTargetLayout(isEnabled: true)
        _ = video.tableColumnHeaders(.automatic)
        _ = video.toolbarColorScheme(nil as ColorScheme?, for: ToolbarPlacement())
        _ = video.accessibilityAction(named: LocalizedStringResource("probe"), {})
        _ = video.accessibilityAction(named: LocalizedStringKey("probe"), {})
        _ = video.accessibilityAction(named: Text(), {})
        _ = video.accessibilityAction(named: "probe", {})
        _ = video.accessibilityAction(action: {}, label: { EmptyView() })
        _ = video.accessibilityAction(.default, {})
        _ = video.accessibilityHidden(true, isEnabled: true)
        _ = video.accessibilityHidden(true)
        _ = video.allowedDynamicRange(nil as Image.DynamicRange?)
        _ = video.containerBackground(for: ContainerBackgroundPlacement(), alignment: Alignment.center, content: { EmptyView() })
        _ = video.containerBackground(Color(), for: ContainerBackgroundPlacement())
        _ = video.defaultScrollAnchor(nil as UnitPoint?, for: ScrollAnchorRole())
        _ = video.defaultScrollAnchor(nil as UnitPoint?)
        _ = video.focusEffectDisabled(true)
        _ = video.gridCellUnsizedAxes(.horizontal)
        _ = video.gridColumnAlignment(HorizontalAlignment.center)
        _ = video.handGestureShortcut(HandGestureShortcut(), isEnabled: true)
        _ = video.highPriorityGesture(ProbeGesture(), name: "probe", isEnabled: true)
        _ = video.highPriorityGesture(ProbeGesture(), including: .all)
        _ = video.highPriorityGesture(ProbeGesture(), isEnabled: true)
        _ = video.hoverEffectDisabled(true)
        _ = video.labeledContentStyle(ProbeLabeledContentStyle())
        _ = video.navigationBarHidden(true)
        _ = video.onScrollPhaseChange({ _, _ in })
        _ = video.onScrollPhaseChange({ _, _, _ in })
        _ = video.presentationDetents(Set<PresentationDetent>(), selection: Binding(wrappedValue: PresentationDetent()))
        _ = video.presentationDetents(Set<PresentationDetent>())
        _ = video.scrollInputBehavior(ScrollInputBehavior(), for: ScrollInputKind())
        _ = video.simultaneousGesture(ProbeGesture(), name: "probe", isEnabled: true)
        _ = video.simultaneousGesture(ProbeGesture(), including: .all)
        _ = video.simultaneousGesture(ProbeGesture(), isEnabled: true)
        _ = video.speechAdjustedPitch(0)
        _ = video.symbolRenderingMode(nil as SymbolRenderingMode?)
        _ = video.transformPreference(ProbePref.self, { _ in })
        _ = video.typesettingLanguage(Locale.Language(), isEnabled: true)
        _ = video.typesettingLanguage(TypesettingLanguage(), isEnabled: true)
        _ = video.accessibilityActions(category: AccessibilityActionCategory(), { EmptyView() })
        _ = video.accessibilityActions({ EmptyView() })
        _ = video.accessibilityElement(children: .ignore)
        _ = video.accessibilityFocused(AccessibilityFocusState<Int>.Binding(), equals: 0)
        _ = video.accessibilityFocused(AccessibilityFocusState<Bool>.Binding())
        _ = video.accessibilityHeading(AccessibilityHeadingLevel())
        _ = video.buttonRepeatBehavior(ButtonRepeatBehavior())
        _ = video.defersSystemGestures(on: .all)
        _ = video.disclosureGroupStyle(ProbeDisclosureGroupStyle())
        _ = video.fileDialogURLEnabled(Predicate<URL>())
        _ = video.inspectorColumnWidth(min: nil as CGFloat?, ideal: 0, max: nil as CGFloat?)
        _ = video.inspectorColumnWidth(0)
        _ = video.invalidatableContent(true)
        _ = video.listRowSeparatorTint(nil as Color?, edges: .all)
        _ = video.listSectionSeparator(.automatic, edges: .all)
        _ = video.navigationTransition(ProbeNavigationTransition())
        _ = video.preferredColorScheme(nil as ColorScheme?)
        _ = video.scrollBounceBehavior(ScrollBounceBehavior(), axes: .horizontal)
        _ = video.scrollTargetBehavior(ProbeScrollTargetBehavior())
        _ = video.symbolEffectsRemoved(true)
        _ = video.transformEnvironment(\.probe, transform: { _ in })
        _ = video.typeSelectEquivalent(LocalizedStringResource("probe"))
        _ = video.typeSelectEquivalent(LocalizedStringKey("probe"))
        _ = video.typeSelectEquivalent(nil as Text?)
        _ = video.typeSelectEquivalent("probe")
        _ = video.writingToolsBehavior(WritingToolsBehavior())
        _ = video.accessibilityChildren(children: { EmptyView() })
        _ = video.containerCornerOffset(.all, sizeToFit: true)
        _ = video.disableAutocorrection(nil as Bool?)
        _ = video.edgesIgnoringSafeArea(.all)
        _ = video.glassEffectTransition(GlassEffectTransition())
        _ = video.handlesExternalEvents(preferring: Set<String>(), allowing: Set<String>())
        _ = video.matchedGeometryEffect(id: 0, in: Namespace.ID(), properties: MatchedGeometryProperties(), anchor: UnitPoint.center, isSource: true)
        _ = video.navigationDestination(isPresented: Binding(wrappedValue: true), destination: { EmptyView() })
        _ = video.navigationDestination(for: Int.self, destination: { _ in EmptyView() })
        _ = video.navigationDestination(item: Binding(wrappedValue: nil as Int?), destination: { _ in EmptyView() })
        _ = video.scrollEdgeEffectStyle(nil as ScrollEdgeEffectStyle?, for: .all)
        _ = video.scrollIndicatorsFlash(trigger: 0)
        _ = video.scrollIndicatorsFlash(onAppear: true)
        _ = video.searchToolbarBehavior(SearchToolbarBehavior())
        _ = video.sliderThumbVisibility(.automatic)
        _ = video.springLoadingBehavior(SpringLoadingBehavior())
        _ = video.textSelectionAffinity(TextSelectionAffinity())
        _ = video.accessibilityAddTraits(AccessibilityTraits())
        _ = video.accessibilityDragPoint(UnitPoint.center, description: LocalizedStringResource("probe"), isEnabled: true)
        _ = video.accessibilityDragPoint(UnitPoint.center, description: LocalizedStringKey("probe"), isEnabled: true)
        _ = video.accessibilityDragPoint(UnitPoint.center, description: Text(), isEnabled: true)
        _ = video.accessibilityDragPoint(UnitPoint.center, description: "probe", isEnabled: true)
        _ = video.accessibilityDragPoint(UnitPoint.center, description: LocalizedStringResource("probe"))
        _ = video.accessibilityDragPoint(UnitPoint.center, description: LocalizedStringKey("probe"))
        _ = video.accessibilityDragPoint(UnitPoint.center, description: Text())
        _ = video.accessibilityDragPoint(UnitPoint.center, description: "probe")
        _ = video.accessibilityDropPoint(UnitPoint.center, description: LocalizedStringResource("probe"), isEnabled: true)
        _ = video.accessibilityDropPoint(UnitPoint.center, description: LocalizedStringKey("probe"), isEnabled: true)
        _ = video.accessibilityDropPoint(UnitPoint.center, description: Text(), isEnabled: true)
        _ = video.accessibilityDropPoint(UnitPoint.center, description: "probe", isEnabled: true)
        _ = video.accessibilityDropPoint(UnitPoint.center, description: LocalizedStringResource("probe"))
        _ = video.accessibilityDropPoint(UnitPoint.center, description: LocalizedStringKey("probe"))
        _ = video.accessibilityDropPoint(UnitPoint.center, description: Text())
        _ = video.accessibilityDropPoint(UnitPoint.center, description: "probe")
        _ = video.autocorrectionDisabled(true)
        _ = video.containerRelativeFrame(.horizontal, count: 0, span: 0, spacing: 0, alignment: Alignment.center)
        _ = video.containerRelativeFrame(.horizontal, alignment: Alignment.center)
        _ = video.containerRelativeFrame(.horizontal, alignment: Alignment.center, { _, _ in 0 })
        _ = video.labelReservedIconWidth(0)
        _ = video.multilineTextAlignment(strategy: Text.AlignmentStrategy())
        _ = video.multilineTextAlignment(TextAlignment())
        _ = video.onContinueUserActivity("probe", perform: { _ in })
        _ = video.onScrollGeometryChange(for: Int.self, of: { _ in 0 }, action: { _, _ in })
        _ = video.overlayPreferenceValue(ProbePref.self, alignment: Alignment.center, { _ in EmptyView() })
        _ = video.overlayPreferenceValue(ProbePref.self, { _ in EmptyView() })
        _ = video.paletteSelectionEffect(PaletteSelectionEffect())
        _ = video.presentationBackground(alignment: Alignment.center, content: { EmptyView() })
        _ = video.presentationBackground(Color())
        _ = video.scrollEdgeEffectHidden(true, for: .all)
        _ = video.tabBarMinimizeBehavior(TabBarMinimizeBehavior())
        _ = video.toolbarForegroundStyle(Color(), for: ToolbarPlacement())
        _ = video.accessibilityIdentifier("probe", isEnabled: true)
        _ = video.accessibilityIdentifier("probe")
        _ = video.accessibilityRotorEntry(id: 0, in: Namespace.ID())
        _ = video.accessibilityZoomAction({ _ in })
        _ = video.dialogSuppressionToggle(isSuppressed: Binding(wrappedValue: true))
        _ = video.dialogSuppressionToggle(LocalizedStringResource("probe"), isSuppressed: Binding(wrappedValue: true))
        _ = video.dialogSuppressionToggle(LocalizedStringKey("probe"), isSuppressed: Binding(wrappedValue: true))
        _ = video.dialogSuppressionToggle(Text(), isSuppressed: Binding(wrappedValue: true))
        _ = video.dialogSuppressionToggle("probe", isSuppressed: Binding(wrappedValue: true))
        _ = video.labelIconToTitleSpacing(0)
        _ = video.layoutDirectionBehavior(LayoutDirectionBehavior())
        _ = video.matchedTransitionSource(id: 0, in: Namespace.ID(), configuration: { _ in EmptyMatchedTransitionSourceConfiguration() })
        _ = video.matchedTransitionSource(id: 0, in: Namespace.ID())
        _ = video.scrollContentBackground(.automatic)
        _ = video.scrollDismissesKeyboard(ScrollDismissesKeyboardMode())
        _ = video.searchDictationBehavior(TextInputDictationBehavior())
        _ = video.symbolVariableValueMode(nil as SymbolVariableValueMode?)
        _ = video.toolbarTitleDisplayMode(ToolbarTitleDisplayMode())
        _ = video.accessibilityDirectTouch(true, options: .all)
        _ = video.accessibilityInputLabels([LocalizedStringKey("probe")], isEnabled: true)
        _ = video.accessibilityInputLabels([Text()], isEnabled: true)
        _ = video.accessibilityInputLabels(["probe"], isEnabled: true)
        _ = video.accessibilityInputLabels([LocalizedStringKey("probe")])
        _ = video.accessibilityInputLabels([Text()])
        _ = video.accessibilityInputLabels(["probe"])
        _ = video.accessibilityLabeledPair(role: AccessibilityLabeledPairRole(), id: 0, in: Namespace.ID())
        _ = video.accessibilityLinkedGroup(id: 0, in: Namespace.ID())
        _ = video.fileDialogBrowserOptions(FileDialogBrowserOptions())
        _ = video.listSectionSeparatorTint(nil as Color?, edges: .all)
        _ = video.materialActiveAppearance(MaterialActiveAppearance())
        _ = video.onScrollVisibilityChange(threshold: 0, { _ in })
        _ = video.persistentSystemOverlays(.automatic)
        _ = video.presentationCornerRadius(nil as CGFloat?)
        _ = video.symbolColorRenderingMode(nil as SymbolColorRenderingMode?)
        _ = video.accessibilityDefaultFocus(AccessibilityFocusState<Int>.Binding(), 0)
        _ = video.accessibilityRemoveTraits(AccessibilityTraits())
        _ = video.accessibilityScrollAction({ _ in })
        _ = video.accessibilityScrollStatus(LocalizedStringResource("probe"), isEnabled: true)
        _ = video.accessibilityScrollStatus(LocalizedStringKey("probe"), isEnabled: true)
        _ = video.accessibilityScrollStatus(Text(), isEnabled: true)
        _ = video.accessibilityScrollStatus("probe", isEnabled: true)
        _ = video.accessibilitySortPriority(0)
        _ = video.backgroundExtensionEffect(isEnabled: true)
        _ = video.backgroundExtensionEffect()
        _ = video.backgroundPreferenceValue(ProbePref.self, alignment: Alignment.center, { _ in EmptyView() })
        _ = video.backgroundPreferenceValue(ProbePref.self, { _ in EmptyView() })
        _ = video.fileDialogCustomizationID("probe")
        _ = video.fileExporterFilenameLabel(LocalizedStringResource("probe"))
        _ = video.fileExporterFilenameLabel(LocalizedStringKey("probe"))
        _ = video.fileExporterFilenameLabel(nil as Text?)
        _ = video.fileExporterFilenameLabel("probe")
        _ = video.menuActionDismissBehavior(MenuActionDismissBehavior())
        _ = video.onInteractiveResizeChange({ _ in })
        _ = video.presentationDragIndicator(.automatic)
        _ = video.speechAnnouncementsQueued(true)
        _ = video.speechSpellsOutCharacters(true)
        _ = video.transformAnchorPreference(key: ProbePref.self, value: Anchor<Int>.Source(), transform: { _, _ in })
        _ = video.accessibilityCustomContent(LocalizedStringResource("probe"), Text(), importance: AXCustomContent.Importance())
        _ = video.accessibilityCustomContent(LocalizedStringResource("probe"), LocalizedStringResource("probe"), importance: AXCustomContent.Importance())
        _ = video.accessibilityCustomContent(LocalizedStringResource("probe"), "probe", importance: AXCustomContent.Importance())
        _ = video.accessibilityCustomContent(AccessibilityCustomContentKey(), LocalizedStringResource("probe"), importance: AXCustomContent.Importance())
        _ = video.accessibilityCustomContent(AccessibilityCustomContentKey(), LocalizedStringKey("probe"), importance: AXCustomContent.Importance())
        _ = video.accessibilityCustomContent(AccessibilityCustomContentKey(), nil as Text?, importance: AXCustomContent.Importance())
        _ = video.accessibilityCustomContent(AccessibilityCustomContentKey(), "probe", importance: AXCustomContent.Importance())
        _ = video.accessibilityCustomContent(LocalizedStringKey("probe"), Text(), importance: AXCustomContent.Importance())
        _ = video.accessibilityCustomContent(LocalizedStringKey("probe"), LocalizedStringKey("probe"), importance: AXCustomContent.Importance())
        _ = video.accessibilityCustomContent(LocalizedStringKey("probe"), "probe", importance: AXCustomContent.Importance())
        _ = video.accessibilityCustomContent(Text(), Text(), importance: AXCustomContent.Importance())
        _ = video.accessibilityCustomContent("probe", "probe", importance: AXCustomContent.Importance())
        _ = video.documentBrowserContextMenu({ _ in EmptyView() })
        _ = video.fileDialogDefaultDirectory(nil as URL?)
        _ = video.interactiveDismissDisabled(true)
        _ = video.listSectionIndexVisibility(.automatic)
        _ = video.accessibilityRepresentation(representation: { EmptyView() })
        _ = video.fileDialogConfirmationLabel(LocalizedStringResource("probe"))
        _ = video.fileDialogConfirmationLabel(LocalizedStringKey("probe"))
        _ = video.fileDialogConfirmationLabel(nil as Text?)
        _ = video.fileDialogConfirmationLabel("probe")
        _ = video.previewInterfaceOrientation(InterfaceOrientation())
        _ = video.textInputAutocapitalization(nil as TextInputAutocapitalization?)
        _ = video.toolbarBackgroundVisibility(.automatic, for: ToolbarPlacement())
        _ = video.accessibilityActivationPoint(UnitPoint.center, isEnabled: true)
        _ = video.accessibilityActivationPoint(.zero, isEnabled: true)
        _ = video.accessibilityActivationPoint(UnitPoint.center)
        _ = video.accessibilityActivationPoint(.zero)
        _ = video.accessibilityChartDescriptor(ProbeChart())
        _ = video.accessibilityTextContentType(AccessibilityTextContentType())
        _ = video.allowsWindowActivationEvents()
        _ = video.allowsWindowActivationEvents(nil as Bool?)
        _ = video.accessibilityAdjustableAction({ _ in })
        _ = video.assistiveAccessNavigationIcon(systemImage: "probe")
        _ = video.assistiveAccessNavigationIcon(Image())
        _ = video.navigationBarBackButtonHidden(true)
        _ = video.navigationBarTitleDisplayMode(NavigationBarItem.TitleDisplayMode())
        _ = video.presentationCompactAdaptation(horizontal: PresentationAdaptation(), vertical: PresentationAdaptation())
        _ = video.presentationCompactAdaptation(PresentationAdaptation())
        _ = video.id(0)
        _ = video.interactionActivityTrackingTag("probe")
        _ = video.onScrollTargetVisibilityChange(idType: Int.self, threshold: 0, { _ in })
        _ = video.presentationContentInteraction(PresentationContentInteraction())
        _ = video.defaultAdaptableTabBarPlacement(.automatic)
        _ = video.speechAlwaysIncludesPunctuation(true)
        _ = video.accessibilityIgnoresInvertColors(true)
        _ = video.writingToolsAffordanceVisibility(.automatic)
        _ = video.navigationLinkIndicatorVisibility(.automatic)
        _ = video.presentationBackgroundInteraction(PresentationBackgroundInteraction())
        _ = video.searchPresentationToolbarBehavior(SearchPresentationToolbarBehavior())
        _ = video.windowToolbarFullScreenVisibility(WindowToolbarFullScreenVisibility())
        _ = video.attributedTextFormattingDefinition(ProbeFormatting())
        _ = video.attributedTextFormattingDefinition(ProbeAttributeScope.self)
        _ = video.attributedTextFormattingDefinition(\.probeScope as KeyPath<AVKit.AttributeScopes, ProbeAttributeScope.Type>)
        _ = video.fileDialogImportsUnresolvedAliases(true)
        _ = video.flipsForRightToLeftLayoutDirection(true)
        _ = video.accessibilityShowsLargeContentViewer()
        _ = video.accessibilityShowsLargeContentViewer({ EmptyView() })
        _ = video.textInputFormattingControlVisibility(.automatic, for: TextInputFormattingControlPlacement.Set())
        _ = video.accessibilityRespondsToUserInteraction(true, isEnabled: true)
        _ = video.accessibilityRespondsToUserInteraction(true)
        _ = video.tag(0, includeOptional: true)
        _ = video.blur(radius: 0, opaque: true)
        _ = video.bold(true)
        _ = video.font(nil as Font?)
        _ = video.help(LocalizedStringResource("probe"))
        _ = video.help(LocalizedStringKey("probe"))
        _ = video.help(Text())
        _ = video.help("probe")
        _ = video.mask(alignment: Alignment.center, { EmptyView() })
        _ = video.mask(EmptyView())
        _ = video.task(id: 0, name: nil as String?, executorPreference: ProbeTaskExecutor(), priority: .userInitiated, file: "probe", line: 0, {})
        _ = video.task(id: 0, priority: .userInitiated, {})
        _ = video.task(priority: .userInitiated, {})
        _ = video.tint(nil as Color?)
        _ = video.tint(nil as Color?)
        _ = video.alert(isPresented: Binding(wrappedValue: true), error: nil as ProbeLocalizedError?, actions: { _ in EmptyView() }, message: { _ in EmptyView() })
        _ = video.alert(isPresented: Binding(wrappedValue: true), error: nil as ProbeLocalizedError?, actions: { EmptyView() })
        _ = video.alert(isPresented: Binding(wrappedValue: true), content: { Alert() })
        _ = video.alert(item: Binding(wrappedValue: nil as ProbeItem?), content: { _ in Alert() })
        _ = video.alert(LocalizedStringResource("probe"), isPresented: Binding(wrappedValue: true), presenting: nil as Int?, actions: { _ in EmptyView() }, message: { _ in EmptyView() })
        _ = video.alert(LocalizedStringKey("probe"), isPresented: Binding(wrappedValue: true), presenting: nil as Int?, actions: { _ in EmptyView() }, message: { _ in EmptyView() })
        _ = video.alert(Text(), isPresented: Binding(wrappedValue: true), presenting: nil as Int?, actions: { _ in EmptyView() }, message: { _ in EmptyView() })
        _ = video.alert("probe", isPresented: Binding(wrappedValue: true), presenting: nil as Int?, actions: { _ in EmptyView() }, message: { _ in EmptyView() })
        _ = video.alert(LocalizedStringResource("probe"), isPresented: Binding(wrappedValue: true), presenting: nil as Int?, actions: { _ in EmptyView() })
        _ = video.alert(LocalizedStringKey("probe"), isPresented: Binding(wrappedValue: true), presenting: nil as Int?, actions: { _ in EmptyView() })
        _ = video.alert(Text(), isPresented: Binding(wrappedValue: true), presenting: nil as Int?, actions: { _ in EmptyView() })
        _ = video.alert("probe", isPresented: Binding(wrappedValue: true), presenting: nil as Int?, actions: { _ in EmptyView() })
        _ = video.alert(LocalizedStringResource("probe"), isPresented: Binding(wrappedValue: true), actions: { EmptyView() }, message: { EmptyView() })
        _ = video.alert(LocalizedStringKey("probe"), isPresented: Binding(wrappedValue: true), actions: { EmptyView() }, message: { EmptyView() })
        _ = video.alert(Text(), isPresented: Binding(wrappedValue: true), actions: { EmptyView() }, message: { EmptyView() })
        _ = video.alert("probe", isPresented: Binding(wrappedValue: true), actions: { EmptyView() }, message: { EmptyView() })
        _ = video.alert(LocalizedStringResource("probe"), isPresented: Binding(wrappedValue: true), actions: { EmptyView() })
        _ = video.alert(LocalizedStringKey("probe"), isPresented: Binding(wrappedValue: true), actions: { EmptyView() })
        _ = video.alert(Text(), isPresented: Binding(wrappedValue: true), actions: { EmptyView() })
        _ = video.alert("probe", isPresented: Binding(wrappedValue: true), actions: { EmptyView() })
        _ = video.badge(nil as LocalizedStringResource?)
        _ = video.badge(nil as LocalizedStringKey?)
        _ = video.badge(nil as Text?)
        _ = video.badge(0)
        _ = video.badge(nil as String?)
        _ = video.frame(width: nil as CGFloat?, height: nil as CGFloat?, alignment: Alignment.center)
        _ = video.frame(minWidth: nil as CGFloat?, idealWidth: nil as CGFloat?, maxWidth: nil as CGFloat?, minHeight: nil as CGFloat?, idealHeight: nil as CGFloat?, maxHeight: nil as CGFloat?, alignment: Alignment.center)
        _ = video.frame()
        _ = video.sheet(isPresented: Binding(wrappedValue: true), onDismiss: nil, content: { EmptyView() })
        _ = video.sheet(item: Binding(wrappedValue: nil as ProbeItem?), onDismiss: nil, content: { _ in EmptyView() })
        _ = video.border(Color(), width: 0)
        _ = video.hidden()
        _ = video.italic(true)
        _ = video.offset(x: 0, y: 0)
        _ = video.offset(.zero)
        _ = video.onDrag({ NSItemProvider() }, preview: { EmptyView() })
        _ = video.onDrag({ NSItemProvider() })
        _ = video.onDrop(of: [ProbeUTType() as any UTType], isTargeted: nil, perform: { _, _ in true })
        _ = video.onDrop(of: [ProbeUTType() as any UTType], isTargeted: nil, perform: { _ in true })
        _ = video.onDrop(of: ["probe"], isTargeted: nil, perform: { _, _ in true })
        _ = video.onDrop(of: ["probe"], isTargeted: nil, perform: { _ in true })
        _ = video.onDrop(of: [ProbeUTType() as any UTType], delegate: ProbeDropDelegate())
        _ = video.onDrop(of: ["probe"], delegate: ProbeDropDelegate())
        _ = video.shadow(color: Color(), radius: 0, x: 0, y: 0)
        _ = video.zIndex(0)
        _ = video.clipped(antialiased: true)
        _ = video.focused(FocusState<Int>.Binding(), equals: 0)
        _ = video.focused(FocusState<Bool>.Binding())
        _ = video.gesture(ProbeGesture(), name: "probe", isEnabled: true)
        _ = video.gesture(ProbeGesture(), including: .all)
        _ = video.gesture(ProbeGesture(), isEnabled: true)
        _ = video.gesture(ProbeGestureRecognizer())
        _ = video.kerning(0)
        _ = video.onHover(perform: { _ in })
        _ = video.opacity(0)
        _ = video.overlay(alignment: Alignment.center, content: { EmptyView() })
        _ = video.overlay(Color(), ignoresSafeAreaEdges: .all)
        _ = video.overlay(Color(), in: DefaultGlassEffectShape(), fillStyle: FillStyle())
        _ = video.overlay(EmptyView(), alignment: Alignment.center)
        _ = video.padding(0)
        _ = video.padding(EdgeInsets())
        _ = video.padding(.all, nil as CGFloat?)
        _ = video.popover(isPresented: Binding(wrappedValue: true), attachmentAnchor: PopoverAttachmentAnchor(), arrowEdge: nil as Edge?, content: { EmptyView() })
        _ = video.popover(item: Binding(wrappedValue: nil as ProbeItem?), attachmentAnchor: PopoverAttachmentAnchor(), arrowEdge: nil as Edge?, content: { _ in EmptyView() })
        _ = video.tabItem({ EmptyView() })
        _ = video.toolbar(id: "probe", content: { ProbeCustomToolbar() })
        _ = video.toolbar(content: { ProbeToolbar() })
        _ = video.toolbar(content: { EmptyView() })
        _ = video.toolbar(removing: nil as ToolbarDefaultItemKind?)
        _ = video.toolbar(.automatic, for: ToolbarPlacement())
        _ = video.contrast(0)
        _ = video.disabled(true)
        _ = video.modifier(0)
        _ = video.onAppear(perform: nil)
        _ = video.onChange(of: 0, initial: true, { _, _ in })
        _ = video.onChange(of: 0, initial: true, {})
        _ = video.onChange(of: 0, perform: { _ in })
        _ = video.onSubmit(of: .text, {})
        _ = video.position(x: 0, y: 0)
        _ = video.position(.zero)
        _ = video.redacted(reason: RedactionReasons())
        _ = video.textCase(nil as Text.Case?)
        _ = video.tracking(0)
        _ = video.animation(nil as Animation?, body: { _ in EmptyView() })
        _ = video.animation(nil as Animation?, value: 0)
        _ = video.animation(nil as Animation?)
        _ = video.blendMode(BlendMode())
        _ = video.clipShape(DefaultGlassEffectShape(), style: FillStyle())
        _ = video.draggable(ProbeTransfer(), preview: { EmptyView() })
        _ = video.draggable(ProbeTransfer())
        _ = video.fileMover(isPresented: Binding(wrappedValue: true), file: nil as URL?, onCompletion: { _ in }, onCancellation: {})
        _ = video.fileMover(isPresented: Binding(wrappedValue: true), file: nil as URL?, onCompletion: { _ in })
        _ = video.fileMover(isPresented: Binding(wrappedValue: true), files: [URL(fileURLWithPath: "/")], onCompletion: { _ in }, onCancellation: {})
        _ = video.fileMover(isPresented: Binding(wrappedValue: true), files: [URL(fileURLWithPath: "/")], onCompletion: { _ in })
        _ = video.fixedSize(horizontal: true, vertical: true)
        _ = video.fixedSize()
        _ = video.focusable(true, interactions: ProbeFocusInteractions())
        _ = video.focusable(true)
        _ = video.fontWidth(nil as Font.Width?)
        _ = video.formStyle(ProbeFormStyle())
        _ = video.grayscale(0)
        _ = video.inspector(isPresented: Binding(wrappedValue: true), content: { EmptyView() })
        _ = video.lineLimit(0, reservesSpace: true)
        _ = video.lineLimit(0...1)
        _ = video.lineLimit(nil as Int?)
        _ = video.lineLimit(0...)
        _ = video.lineLimit(...1)
        _ = video.listStyle(ProbeListStyle())
        _ = video.menuOrder(MenuOrder())
        _ = video.menuStyle(ProbeMenuStyle())
        _ = video.onOpenURL(prefersInApp: true)
        _ = video.onOpenURL(perform: { _ in })
        _ = video.onReceive(ProbePublisher(), perform: { _ in })
        _ = video.statusBar(hidden: true)
        _ = video.textScale(Text.Scale(), isEnabled: true)
        _ = video.underline(true, pattern: .solid, color: nil as Color?)
    }
}
