/*
 * mach/thread_act.h -- machorun's clean-room stand-in for MIG output.
 *
 * NOT Apple's header, and not MIG's either.  Apple's copy carries no licence
 * block because nobody wrote it: it is generated by MIG from
 * xnu:osfmk/mach/thread_act.defs, which IS published -- but running MIG means porting
 * a Mach-specific code generator to Linux.  docs/SDK_SURVEY.md §2.3 measured
 * the alternative and recommended it: the ten MIG headers declare 237 routines
 * between them, the whole test corpus links against 10 Mach symbols, and
 * objc4's source names 6.  So these are hand-written, exactly as
 * vendor/objc4-priv/ already is for 25 Apple SPI headers.
 *
 * THE RULE FOR THIS FILE: it declares a routine only if
 * darwin/usr/lib/libSystem.B.dylib EXPORTS it.  A Mach routine we have not
 * implemented is absent, so calling it is an undeclared-identifier error at
 * compile time rather than a missing symbol at load time -- loud aborts over
 * silent stubs, and scripts/gen_tbd.sh keeps the two sides honest.
 *
 * WHAT THIS OMITS versus MIG's output: the MIG message structs
 * (__Request__*_t / __Reply__*_t), the *_MSG_COUNT constants, the AUTOTEST
 * function tables, and every routine we do not implement.  Nothing that omits
 * is ABI: the structs are the on-the-wire form of a Mach RPC, and machorun
 * does not do Mach RPC -- darwin/src/mach.c services these calls directly.
 */

#ifndef _mach_thread_act_user_
#define _mach_thread_act_user_

#include <mach/std_types.h>
#include <mach/mach_types.h>
#include <mach/thread_info.h>
#include <mach/thread_status.h>
#include <mach/thread_special_ports.h>
#include <sys/cdefs.h>

__BEGIN_DECLS

/* THE ONE EXCEPTION to this file's rule, stated precisely.
 *
 * objc4's objc-cache.mm needs thread_get_state DECLARED in order to compile:
 * _get_pc_for_thread() reads ARM_THREAD_STATE64 to decide whether a thread is
 * inside a cache-reading function.  Nothing here IMPLEMENTS it -- grep
 * darwin/src/mach.c -- and libSystem.B.dylib does not export it.
 *
 * That is not a hole being hidden.  It is measured: the resulting
 * libobjc.A.dylib does not import _thread_get_state at all, because
 * _collecting_in_critical() is unreachable in this configuration and the
 * optimiser drops its caller before the linker sees it.  scripts/gen_tbd.sh
 * re-checks that on every build -- an import nothing exports is a hard failure
 * there, not a surprise at load time.
 *
 * A guest that really calls thread_get_state gets machorun's normal
 * undefined-symbol abort, naming _thread_get_state.
 * docs/UNIMPLEMENTED.md#mach-thread-state records it.
 *
 * mach_thread_self() -- which guests actually use, and which we do implement --
 * is in <mach/mach_init.h>, which is xnu's own and vendored. */
extern kern_return_t thread_get_state(thread_act_t target_act,
                                      thread_state_flavor_t flavor,
                                      thread_state_t old_state,
                                      mach_msg_type_number_t *old_stateCnt);

__END_DECLS

#endif /* _mach_thread_act_user_ */
