import CoreFoundation
import Foundation
import ColorSync

func testNamedProfileConstantPayloads() {
    precondition(csString(kColorSyncGenericGrayProfile) == "com.apple.ColorSync.GenericGray")
    precondition(csString(kColorSyncGenericGrayGamma22Profile) == "com.apple.ColorSync.GenericGrayGamma2.2")
    precondition(csString(kColorSyncGenericRGBProfile) == "com.apple.ColorSync.GenericRGB")
    precondition(csString(kColorSyncGenericCMYKProfile) == "com.apple.ColorSync.GenericCMYK")
    precondition(csString(kColorSyncDisplayP3Profile) == "com.apple.ColorSync.DisplayP3")
    precondition(csString(kColorSyncSRGBProfile) == "com.apple.ColorSync.sRGB")
    precondition(csString(kColorSyncAdobeRGB1998Profile) == "com.apple.ColorSync.AdobeRGB1998")
    precondition(csString(kColorSyncGenericLabProfile) == "com.apple.ColorSync.GenericLab")
    precondition(csString(kColorSyncGenericXYZProfile) == "com.apple.ColorSync.GenericXYZ")
    precondition(csString(kColorSyncACESCGLinearProfile) == "com.apple.ColorSync.ACESCGLinear")
    precondition(csString(kColorSyncDCIP3Profile) == "com.apple.ColorSync.DCIP3")
    precondition(csString(kColorSyncITUR709Profile) == "com.apple.ColorSync.ITUR709")
    precondition(csString(kColorSyncITUR2020Profile) == "com.apple.ColorSync.ITUR2020")
    precondition(csString(kColorSyncROMMRGBProfile) == "com.apple.ColorSync.ROMMRGB")
    precondition(csString(kColorSyncWebSafeColorsProfile) == "com.apple.ColorSync.WebSafeColors")
    precondition(csString(kColorSyncSRGBProfile) != csString(kColorSyncDisplayP3Profile))
}

func testProfileInfoKeyConstantPayloads() {
    precondition(csString(kColorSyncProfileHeader) == "com.apple.ColorSync.ProfileHeader")
    precondition(csString(kColorSyncProfileClass) == "com.apple.ColorSync.ProfileClass")
    precondition(csString(kColorSyncProfileColorSpace) == "com.apple.ColorSync.ProfileColorSpace")
    precondition(csString(kColorSyncProfilePCS) == "com.apple.ColorSync.PCS")
    precondition(csString(kColorSyncProfileURL) == "com.apple.ColorSync.ProfileURL")
    precondition(csString(kColorSyncProfileDescription) == "com.apple.ColorSync.ProfileDescription")
    precondition(csString(kColorSyncProfileMD5Digest) == "com.apple.ColorSync.ProfileMD5Digest")
    precondition(csString(kColorSyncProfileIsValid) == "com.apple.ColorSync.ProfileIsValid")
    precondition(csString(kColorSyncProfileCacheSeed) == "com.apple.ColorSync.ProfileCacheSeed")
}

func testICCSignatureConstantPayloads() {
    precondition(csString(kColorSyncSigAToB0Tag) == "A2B0")
    precondition(csString(kColorSyncSigAToB1Tag) == "A2B1")
    precondition(csString(kColorSyncSigAToB2Tag) == "A2B2")
    precondition(csString(kColorSyncSigBToA0Tag) == "B2A0")
    precondition(csString(kColorSyncSigBToA1Tag) == "B2A1")
    precondition(csString(kColorSyncSigBToA2Tag) == "B2A2")
    precondition(csString(kColorSyncSigCmykData) == "CMYK")
    precondition(csString(kColorSyncSigGrayData) == "GRAY")
    precondition(csString(kColorSyncSigLabData) == "Lab ")
    precondition(csString(kColorSyncSigRgbData) == "RGB ")
    precondition(csString(kColorSyncSigXYZData) == "XYZ ")
    precondition(csString(kColorSyncSigAbstractClass) == "abst")
    precondition(csString(kColorSyncSigBlueTRCTag) == "bTRC")
    precondition(csString(kColorSyncSigBlueColorantTag) == "bXYZ")
    precondition(csString(kColorSyncSigMediaBlackPointTag) == "bkpt")
    precondition(csString(kColorSyncSigCopyrightTag) == "cprt")
    precondition(csString(kColorSyncSigProfileDescriptionTag) == "desc")
    precondition(csString(kColorSyncSigDeviceModelDescTag) == "dmdd")
    precondition(csString(kColorSyncSigDeviceMfgDescTag) == "dmnd")
    precondition(csString(kColorSyncSigGreenTRCTag) == "gTRC")
    precondition(csString(kColorSyncSigGreenColorantTag) == "gXYZ")
    precondition(csString(kColorSyncSigGamutTag) == "gamt")
    precondition(csString(kColorSyncSigGrayTRCTag) == "kTRC")
    precondition(csString(kColorSyncSigLinkClass) == "link")
    precondition(csString(kColorSyncSigDisplayClass) == "mntr")
    precondition(csString(kColorSyncSigNamedColor2Tag) == "ncl2")
    precondition(csString(kColorSyncSigNamedColorClass) == "nmcl")
    precondition(csString(kColorSyncSigPreview0Tag) == "pre0")
    precondition(csString(kColorSyncSigPreview1Tag) == "pre1")
    precondition(csString(kColorSyncSigPreview2Tag) == "pre2")
    precondition(csString(kColorSyncSigOutputClass) == "prtr")
    precondition(csString(kColorSyncSigProfileSequenceDescTag) == "pseq")
    precondition(csString(kColorSyncSigRedTRCTag) == "rTRC")
    precondition(csString(kColorSyncSigRedColorantTag) == "rXYZ")
    precondition(csString(kColorSyncSigInputClass) == "scnr")
    precondition(csString(kColorSyncSigColorSpaceClass) == "spac")
    precondition(csString(kColorSyncSigTechnologyTag) == "tech")
    precondition(csString(kColorSyncSigViewingConditionsTag) == "view")
    precondition(csString(kColorSyncSigViewingCondDescTag) == "vued")
    precondition(csString(kColorSyncSigMediaWhitePointTag) == "wtpt")
}

func testTransformKeyConstantPayloads() {
    precondition(csString(kColorSyncProfile) == "com.apple.ColorSync.Profile")
    precondition(csString(kColorSyncRenderingIntent) == "com.apple.ColorSync.RenderingIntent")
    precondition(csString(kColorSyncRenderingIntentPerceptual) == "com.apple.ColorSync.Perceptual")
    precondition(csString(kColorSyncRenderingIntentRelative) == "com.apple.ColorSync.RelativeColorimetric")
    precondition(csString(kColorSyncRenderingIntentSaturation) == "com.apple.ColorSync.Saturation")
    precondition(csString(kColorSyncRenderingIntentAbsolute) == "com.apple.ColorSync.AbsoluteColorimetric")
    precondition(csString(kColorSyncRenderingIntentUseProfileHeader) == "com.apple.ColorSync.UseProfileHeader")
    precondition(csString(kColorSyncTransformTag) == "com.apple.ColorSync.TransformTag")
    precondition(csString(kColorSyncTransformDeviceToPCS) == "com.apple.ColorSync.TransformDeviceToPCS")
    precondition(csString(kColorSyncTransformPCSToPCS) == "com.apple.ColorSync.TransformPCSToPCS")
    precondition(csString(kColorSyncTransformPCSToDevice) == "com.apple.ColorSync.TransformPCSToDevice")
    precondition(csString(kColorSyncTransformDeviceToDevice) == "com.apple.ColorSync.TransformDeviceToDevice")
    precondition(csString(kColorSyncTransformGamutCheck) == "com.apple.ColorSync.TransformGamutCheck")
    precondition(csString(kColorSyncBlackPointCompensation) == "com.apple.ColorSync.BlackPointCompensation")
    precondition(csString(kColorSyncPreferredCMM) == "com.apple.ColorSync.PreferredCMM")
    precondition(csString(kColorSyncConvertQuality) == "com.apple.ColorSync.ConvertQuality")
    precondition(csString(kColorSyncBestQuality) == "com.apple.ColorSync.BestQuality")
    precondition(csString(kColorSyncNormalQuality) == "com.apple.ColorSync.NormalQuality")
    precondition(csString(kColorSyncDraftQuality) == "com.apple.ColorSync.DraftQuality")
    precondition(csString(kColorSyncConvertUseExtendedRange) == "com.apple.ColorSync.ConvertUseExtendedRange")
    precondition(csString(kColorSyncDoNotSubstituteProfiles) == "com.apple.ColorSync.DoNotSubstituteProfiles")
    precondition(csString(kColorSyncExtendedRange) == "com.apple.ColorSync.ExtendedRange")
    precondition(csString(kColorSyncHDRDerivative) == "com.apple.ColorSync.HDRDerivative")
    precondition(csString(kColorSyncPQDerivative) == "com.apple.ColorSync.PQDerivative")
    precondition(csString(kColorSyncHLGDerivative) == "com.apple.ColorSync.HLGDerivative")
    precondition(csString(kColorSyncTransformInfo) == "com.apple.ColorSync.TransformInfo")
    precondition(csString(kColorSyncTransformCreator) == "com.apple.ColorSync.TransformCreator")
    precondition(csString(kColorSyncTransformSrcSpace) == "com.apple.ColorSync.TransformSrcSpace")
    precondition(csString(kColorSyncTransformDstSpace) == "com.apple.ColorSync.TransformDstSpace")
    precondition(csString(kColorSyncTransformUseITU709OETF) == "com.apple.ColorSync.TransformUseITU709OETF")
    precondition(csString(kColorSyncTransformProfileSequnce) == "com.apple.ColorSync.TransformProfileSequnce")
}

func testCMMCodeFragmentConstantPayloads() {
    precondition(csString(kColorSyncTransformCodeFragmentType) == "com.apple.cmm.CodeFragmentType")
    precondition(csString(kColorSyncTransformCodeFragmentMD5) == "com.apple.cmm.CodeFragmentMD5")
    precondition(csString(kColorSyncTransformFullConversionData) == "com.apple.cmm.FullConversion")
    precondition(csString(kColorSyncTransformSimplifiedConversionData) == "com.apple.cmm.SimplifiedConversion")
    precondition(csString(kColorSyncTransformParametricConversionData) == "com.apple.cmm.ParametricConversion")
    precondition(csString(kColorSyncConversionMatrix) == "com.apple.cmm.Matrix")
    precondition(csString(kColorSyncConversionParamCurve0) == "com.apple.cmm.ParamCurve0")
    precondition(csString(kColorSyncConversionParamCurve1) == "com.apple.cmm.ParamCurve1")
    precondition(csString(kColorSyncConversionParamCurve2) == "com.apple.cmm.ParamCurve2")
    precondition(csString(kColorSyncConversionParamCurve3) == "com.apple.cmm.ParamCurve3")
    precondition(csString(kColorSyncConversionParamCurve4) == "com.apple.cmm.ParamCurve4")
    precondition(csString(kColorSyncConversion1DLut) == "com.apple.cmm.1D-LUT")
    precondition(csString(kColorSyncConversionGridPoints) == "com.apple.cmm.GridPointCount")
    precondition(csString(kColorSyncConversionChannelID) == "com.apple.cmm.ChannelID")
    precondition(csString(kColorSyncConversion3DLut) == "com.apple.cmm.3D-LUT")
    precondition(csString(kColorSyncConversionNDLut) == "com.apple.cmm.ND-LUT")
    precondition(csString(kColorSyncConversionInpChan) == "com.apple.cmm.InputChannels")
    precondition(csString(kColorSyncConversionOutChan) == "com.apple.cmm.OutputChannels")
    precondition(csString(kColorSyncConversionBPC) == "com.apple.cmm.BPC")
    precondition(csString(kColorSyncFixedPointRange) == "com.apple.cmm.FixedPointRange")
}
