import Foundation

open class AVMetadataBodyObject: AVMetadataObject, @unchecked Sendable {
  public override init() { super.init() }
  public var bodyID: Int { 0 }
}

open class AVMetadataCatBodyObject: AVMetadataBodyObject, @unchecked Sendable {
  public override init() { super.init() }
}

open class AVMetadataCatHeadObject: AVMetadataObject, @unchecked Sendable {
  public override init() { super.init() }
}

open class AVMetadataDogBodyObject: AVMetadataBodyObject, @unchecked Sendable {
  public override init() { super.init() }
}

open class AVMetadataDogHeadObject: AVMetadataObject, @unchecked Sendable {
  public override init() { super.init() }
}

public struct AVMetadataExtraAttributeKey: RawRepresentable, Hashable, Sendable, ExpressibleByStringLiteral {
  public let rawValue: String
  public init(rawValue: String) { self.rawValue = rawValue }
  public init(stringLiteral value: String) { self.init(rawValue: value) }
  public static let valueURI = AVMetadataExtraAttributeKey(rawValue: "valueURI")
  public static let baseURI = AVMetadataExtraAttributeKey(rawValue: "baseURI")
  public static let info = AVMetadataExtraAttributeKey(rawValue: "info")
}

open class AVMetadataFaceObject: AVMetadataObject, @unchecked Sendable {
  public override init() { super.init() }
  public var faceID: Int { 0 }
  public var hasRollAngle: Bool { false }
  public var rollAngle: CGFloat { 0 }
  public var hasYawAngle: Bool { false }
  public var yawAngle: CGFloat { 0 }
}

public struct AVMetadataFormat: RawRepresentable, Hashable, Sendable, ExpressibleByStringLiteral {
  public let rawValue: String
  public init(rawValue: String) { self.rawValue = rawValue }
  public init(stringLiteral value: String) { self.init(rawValue: value) }
  public static let quickTimeUserData = AVMetadataFormat(rawValue: "quickTimeUserData")
  public static let isoUserData = AVMetadataFormat(rawValue: "isoUserData")
  public static let quickTimeMetadata = AVMetadataFormat(rawValue: "quickTimeMetadata")
  public static let iTunesMetadata = AVMetadataFormat(rawValue: "iTunesMetadata")
  public static let id3Metadata = AVMetadataFormat(rawValue: "id3Metadata")
  public static let hlsMetadata = AVMetadataFormat(rawValue: "hlsMetadata")
  public static let unknown = AVMetadataFormat(rawValue: "unknown")
}

open class AVMetadataGroup: NSObject, @unchecked Sendable {
  public override init() { super.init() }
  public var items: [AVMetadataItem] { [] }
  public var classifyingLabel: String? { nil }
  public var uniqueID: String? { nil }
}

open class AVMetadataHumanBodyObject: AVMetadataBodyObject, @unchecked Sendable {
  public override init() { super.init() }
}

open class AVMetadataHumanFullBodyObject: AVMetadataBodyObject, @unchecked Sendable {
  public override init() { super.init() }
}

public struct AVMetadataIdentifier: RawRepresentable, Hashable, Sendable, ExpressibleByStringLiteral {
  public let rawValue: String
  public init(rawValue: String) { self.rawValue = rawValue }
  public init(stringLiteral value: String) { self.init(rawValue: value) }
  public static let commonIdentifierTitle = AVMetadataIdentifier(rawValue: "commonIdentifierTitle")
  public static let commonIdentifierCreator = AVMetadataIdentifier(rawValue: "commonIdentifierCreator")
  public static let commonIdentifierSubject = AVMetadataIdentifier(rawValue: "commonIdentifierSubject")
  public static let commonIdentifierDescription = AVMetadataIdentifier(rawValue: "commonIdentifierDescription")
  public static let commonIdentifierPublisher = AVMetadataIdentifier(rawValue: "commonIdentifierPublisher")
  public static let commonIdentifierContributor = AVMetadataIdentifier(rawValue: "commonIdentifierContributor")
  public static let commonIdentifierCreationDate = AVMetadataIdentifier(rawValue: "commonIdentifierCreationDate")
  public static let commonIdentifierLastModifiedDate = AVMetadataIdentifier(rawValue: "commonIdentifierLastModifiedDate")
  public static let commonIdentifierType = AVMetadataIdentifier(rawValue: "commonIdentifierType")
  public static let commonIdentifierFormat = AVMetadataIdentifier(rawValue: "commonIdentifierFormat")
  public static let commonIdentifierAssetIdentifier = AVMetadataIdentifier(rawValue: "commonIdentifierAssetIdentifier")
  public static let commonIdentifierSource = AVMetadataIdentifier(rawValue: "commonIdentifierSource")
  public static let commonIdentifierLanguage = AVMetadataIdentifier(rawValue: "commonIdentifierLanguage")
  public static let commonIdentifierRelation = AVMetadataIdentifier(rawValue: "commonIdentifierRelation")
  public static let commonIdentifierLocation = AVMetadataIdentifier(rawValue: "commonIdentifierLocation")
  public static let commonIdentifierCopyrights = AVMetadataIdentifier(rawValue: "commonIdentifierCopyrights")
  public static let commonIdentifierAlbumName = AVMetadataIdentifier(rawValue: "commonIdentifierAlbumName")
  public static let commonIdentifierAuthor = AVMetadataIdentifier(rawValue: "commonIdentifierAuthor")
  public static let commonIdentifierArtist = AVMetadataIdentifier(rawValue: "commonIdentifierArtist")
  public static let commonIdentifierArtwork = AVMetadataIdentifier(rawValue: "commonIdentifierArtwork")
  public static let commonIdentifierMake = AVMetadataIdentifier(rawValue: "commonIdentifierMake")
  public static let commonIdentifierModel = AVMetadataIdentifier(rawValue: "commonIdentifierModel")
  public static let commonIdentifierSoftware = AVMetadataIdentifier(rawValue: "commonIdentifierSoftware")
  public static let commonIdentifierAccessibilityDescription = AVMetadataIdentifier(rawValue: "commonIdentifierAccessibilityDescription")
  public static let quickTimeUserDataAlbum = AVMetadataIdentifier(rawValue: "quickTimeUserDataAlbum")
  public static let quickTimeUserDataArranger = AVMetadataIdentifier(rawValue: "quickTimeUserDataArranger")
  public static let quickTimeUserDataArtist = AVMetadataIdentifier(rawValue: "quickTimeUserDataArtist")
  public static let quickTimeUserDataAuthor = AVMetadataIdentifier(rawValue: "quickTimeUserDataAuthor")
  public static let quickTimeUserDataChapter = AVMetadataIdentifier(rawValue: "quickTimeUserDataChapter")
  public static let quickTimeUserDataComment = AVMetadataIdentifier(rawValue: "quickTimeUserDataComment")
  public static let quickTimeUserDataComposer = AVMetadataIdentifier(rawValue: "quickTimeUserDataComposer")
  public static let quickTimeUserDataCopyright = AVMetadataIdentifier(rawValue: "quickTimeUserDataCopyright")
  public static let quickTimeUserDataCreationDate = AVMetadataIdentifier(rawValue: "quickTimeUserDataCreationDate")
  public static let quickTimeUserDataDescription = AVMetadataIdentifier(rawValue: "quickTimeUserDataDescription")
  public static let quickTimeUserDataDirector = AVMetadataIdentifier(rawValue: "quickTimeUserDataDirector")
  public static let quickTimeUserDataDisclaimer = AVMetadataIdentifier(rawValue: "quickTimeUserDataDisclaimer")
  public static let quickTimeUserDataEncodedBy = AVMetadataIdentifier(rawValue: "quickTimeUserDataEncodedBy")
  public static let quickTimeUserDataFullName = AVMetadataIdentifier(rawValue: "quickTimeUserDataFullName")
  public static let quickTimeUserDataGenre = AVMetadataIdentifier(rawValue: "quickTimeUserDataGenre")
  public static let quickTimeUserDataHostComputer = AVMetadataIdentifier(rawValue: "quickTimeUserDataHostComputer")
  public static let quickTimeUserDataInformation = AVMetadataIdentifier(rawValue: "quickTimeUserDataInformation")
  public static let quickTimeUserDataKeywords = AVMetadataIdentifier(rawValue: "quickTimeUserDataKeywords")
  public static let quickTimeUserDataMake = AVMetadataIdentifier(rawValue: "quickTimeUserDataMake")
  public static let quickTimeUserDataModel = AVMetadataIdentifier(rawValue: "quickTimeUserDataModel")
  public static let quickTimeUserDataOriginalArtist = AVMetadataIdentifier(rawValue: "quickTimeUserDataOriginalArtist")
  public static let quickTimeUserDataOriginalFormat = AVMetadataIdentifier(rawValue: "quickTimeUserDataOriginalFormat")
  public static let quickTimeUserDataOriginalSource = AVMetadataIdentifier(rawValue: "quickTimeUserDataOriginalSource")
  public static let quickTimeUserDataPerformers = AVMetadataIdentifier(rawValue: "quickTimeUserDataPerformers")
  public static let quickTimeUserDataProducer = AVMetadataIdentifier(rawValue: "quickTimeUserDataProducer")
  public static let quickTimeUserDataPublisher = AVMetadataIdentifier(rawValue: "quickTimeUserDataPublisher")
  public static let quickTimeUserDataProduct = AVMetadataIdentifier(rawValue: "quickTimeUserDataProduct")
  public static let quickTimeUserDataSoftware = AVMetadataIdentifier(rawValue: "quickTimeUserDataSoftware")
  public static let quickTimeUserDataSpecialPlaybackRequirements = AVMetadataIdentifier(rawValue: "quickTimeUserDataSpecialPlaybackRequirements")
  public static let quickTimeUserDataTrack = AVMetadataIdentifier(rawValue: "quickTimeUserDataTrack")
  public static let quickTimeUserDataWarning = AVMetadataIdentifier(rawValue: "quickTimeUserDataWarning")
  public static let quickTimeUserDataWriter = AVMetadataIdentifier(rawValue: "quickTimeUserDataWriter")
  public static let quickTimeUserDataURLLink = AVMetadataIdentifier(rawValue: "quickTimeUserDataURLLink")
  public static let quickTimeUserDataLocationISO6709 = AVMetadataIdentifier(rawValue: "quickTimeUserDataLocationISO6709")
  public static let quickTimeUserDataTrackName = AVMetadataIdentifier(rawValue: "quickTimeUserDataTrackName")
  public static let quickTimeUserDataCredits = AVMetadataIdentifier(rawValue: "quickTimeUserDataCredits")
  public static let quickTimeUserDataPhonogramRights = AVMetadataIdentifier(rawValue: "quickTimeUserDataPhonogramRights")
  public static let quickTimeUserDataTaggedCharacteristic = AVMetadataIdentifier(rawValue: "quickTimeUserDataTaggedCharacteristic")
  public static let quickTimeUserDataAccessibilityDescription = AVMetadataIdentifier(rawValue: "quickTimeUserDataAccessibilityDescription")
  public static let isoUserDataCopyright = AVMetadataIdentifier(rawValue: "isoUserDataCopyright")
  public static let isoUserDataDate = AVMetadataIdentifier(rawValue: "isoUserDataDate")
  public static let isoUserDataTaggedCharacteristic = AVMetadataIdentifier(rawValue: "isoUserDataTaggedCharacteristic")
  public static let isoUserDataAccessibilityDescription = AVMetadataIdentifier(rawValue: "isoUserDataAccessibilityDescription")
  public static let identifier3GPUserDataCopyright = AVMetadataIdentifier(rawValue: "identifier3GPUserDataCopyright")
  public static let identifier3GPUserDataAuthor = AVMetadataIdentifier(rawValue: "identifier3GPUserDataAuthor")
  public static let identifier3GPUserDataPerformer = AVMetadataIdentifier(rawValue: "identifier3GPUserDataPerformer")
  public static let identifier3GPUserDataGenre = AVMetadataIdentifier(rawValue: "identifier3GPUserDataGenre")
  public static let identifier3GPUserDataRecordingYear = AVMetadataIdentifier(rawValue: "identifier3GPUserDataRecordingYear")
  public static let identifier3GPUserDataLocation = AVMetadataIdentifier(rawValue: "identifier3GPUserDataLocation")
  public static let identifier3GPUserDataTitle = AVMetadataIdentifier(rawValue: "identifier3GPUserDataTitle")
  public static let identifier3GPUserDataDescription = AVMetadataIdentifier(rawValue: "identifier3GPUserDataDescription")
  public static let identifier3GPUserDataCollection = AVMetadataIdentifier(rawValue: "identifier3GPUserDataCollection")
  public static let identifier3GPUserDataUserRating = AVMetadataIdentifier(rawValue: "identifier3GPUserDataUserRating")
  public static let identifier3GPUserDataThumbnail = AVMetadataIdentifier(rawValue: "identifier3GPUserDataThumbnail")
  public static let identifier3GPUserDataAlbumAndTrack = AVMetadataIdentifier(rawValue: "identifier3GPUserDataAlbumAndTrack")
  public static let identifier3GPUserDataKeywordList = AVMetadataIdentifier(rawValue: "identifier3GPUserDataKeywordList")
  public static let identifier3GPUserDataMediaClassification = AVMetadataIdentifier(rawValue: "identifier3GPUserDataMediaClassification")
  public static let identifier3GPUserDataMediaRating = AVMetadataIdentifier(rawValue: "identifier3GPUserDataMediaRating")
  public static let quickTimeMetadataAuthor = AVMetadataIdentifier(rawValue: "quickTimeMetadataAuthor")
  public static let quickTimeMetadataComment = AVMetadataIdentifier(rawValue: "quickTimeMetadataComment")
  public static let quickTimeMetadataCopyright = AVMetadataIdentifier(rawValue: "quickTimeMetadataCopyright")
  public static let quickTimeMetadataCreationDate = AVMetadataIdentifier(rawValue: "quickTimeMetadataCreationDate")
  public static let quickTimeMetadataDirector = AVMetadataIdentifier(rawValue: "quickTimeMetadataDirector")
  public static let quickTimeMetadataDisplayName = AVMetadataIdentifier(rawValue: "quickTimeMetadataDisplayName")
  public static let quickTimeMetadataInformation = AVMetadataIdentifier(rawValue: "quickTimeMetadataInformation")
  public static let quickTimeMetadataKeywords = AVMetadataIdentifier(rawValue: "quickTimeMetadataKeywords")
  public static let quickTimeMetadataProducer = AVMetadataIdentifier(rawValue: "quickTimeMetadataProducer")
  public static let quickTimeMetadataPublisher = AVMetadataIdentifier(rawValue: "quickTimeMetadataPublisher")
  public static let quickTimeMetadataAlbum = AVMetadataIdentifier(rawValue: "quickTimeMetadataAlbum")
  public static let quickTimeMetadataArtist = AVMetadataIdentifier(rawValue: "quickTimeMetadataArtist")
  public static let quickTimeMetadataArtwork = AVMetadataIdentifier(rawValue: "quickTimeMetadataArtwork")
  public static let quickTimeMetadataDescription = AVMetadataIdentifier(rawValue: "quickTimeMetadataDescription")
  public static let quickTimeMetadataSoftware = AVMetadataIdentifier(rawValue: "quickTimeMetadataSoftware")
  public static let quickTimeMetadataYear = AVMetadataIdentifier(rawValue: "quickTimeMetadataYear")
  public static let quickTimeMetadataGenre = AVMetadataIdentifier(rawValue: "quickTimeMetadataGenre")
  public static let quickTimeMetadataiXML = AVMetadataIdentifier(rawValue: "quickTimeMetadataiXML")
  public static let quickTimeMetadataLocationISO6709 = AVMetadataIdentifier(rawValue: "quickTimeMetadataLocationISO6709")
  public static let quickTimeMetadataMake = AVMetadataIdentifier(rawValue: "quickTimeMetadataMake")
  public static let quickTimeMetadataModel = AVMetadataIdentifier(rawValue: "quickTimeMetadataModel")
  public static let quickTimeMetadataArranger = AVMetadataIdentifier(rawValue: "quickTimeMetadataArranger")
  public static let quickTimeMetadataEncodedBy = AVMetadataIdentifier(rawValue: "quickTimeMetadataEncodedBy")
  public static let quickTimeMetadataOriginalArtist = AVMetadataIdentifier(rawValue: "quickTimeMetadataOriginalArtist")
  public static let quickTimeMetadataPerformer = AVMetadataIdentifier(rawValue: "quickTimeMetadataPerformer")
  public static let quickTimeMetadataComposer = AVMetadataIdentifier(rawValue: "quickTimeMetadataComposer")
  public static let quickTimeMetadataCredits = AVMetadataIdentifier(rawValue: "quickTimeMetadataCredits")
  public static let quickTimeMetadataPhonogramRights = AVMetadataIdentifier(rawValue: "quickTimeMetadataPhonogramRights")
  public static let quickTimeMetadataCameraIdentifier = AVMetadataIdentifier(rawValue: "quickTimeMetadataCameraIdentifier")
  public static let quickTimeMetadataCameraFrameReadoutTime = AVMetadataIdentifier(rawValue: "quickTimeMetadataCameraFrameReadoutTime")
  public static let quickTimeMetadataTitle = AVMetadataIdentifier(rawValue: "quickTimeMetadataTitle")
  public static let quickTimeMetadataCollectionUser = AVMetadataIdentifier(rawValue: "quickTimeMetadataCollectionUser")
  public static let quickTimeMetadataRatingUser = AVMetadataIdentifier(rawValue: "quickTimeMetadataRatingUser")
  public static let quickTimeMetadataLocationName = AVMetadataIdentifier(rawValue: "quickTimeMetadataLocationName")
  public static let quickTimeMetadataLocationBody = AVMetadataIdentifier(rawValue: "quickTimeMetadataLocationBody")
  public static let quickTimeMetadataLocationNote = AVMetadataIdentifier(rawValue: "quickTimeMetadataLocationNote")
  public static let quickTimeMetadataLocationRole = AVMetadataIdentifier(rawValue: "quickTimeMetadataLocationRole")
  public static let quickTimeMetadataLocationDate = AVMetadataIdentifier(rawValue: "quickTimeMetadataLocationDate")
  public static let quickTimeMetadataDirectionFacing = AVMetadataIdentifier(rawValue: "quickTimeMetadataDirectionFacing")
  public static let quickTimeMetadataDirectionMotion = AVMetadataIdentifier(rawValue: "quickTimeMetadataDirectionMotion")
  public static let quickTimeMetadataPreferredAffineTransform = AVMetadataIdentifier(rawValue: "quickTimeMetadataPreferredAffineTransform")
  public static let quickTimeMetadataDetectedFace = AVMetadataIdentifier(rawValue: "quickTimeMetadataDetectedFace")
  public static let quickTimeMetadataDetectedHumanBody = AVMetadataIdentifier(rawValue: "quickTimeMetadataDetectedHumanBody")
  public static let quickTimeMetadataDetectedCatBody = AVMetadataIdentifier(rawValue: "quickTimeMetadataDetectedCatBody")
  public static let quickTimeMetadataDetectedDogBody = AVMetadataIdentifier(rawValue: "quickTimeMetadataDetectedDogBody")
  public static let quickTimeMetadataDetectedSalientObject = AVMetadataIdentifier(rawValue: "quickTimeMetadataDetectedSalientObject")
  public static let quickTimeMetadataVideoOrientation = AVMetadataIdentifier(rawValue: "quickTimeMetadataVideoOrientation")
  public static let quickTimeMetadataContentIdentifier = AVMetadataIdentifier(rawValue: "quickTimeMetadataContentIdentifier")
  public static let quickTimeMetadataAccessibilityDescription = AVMetadataIdentifier(rawValue: "quickTimeMetadataAccessibilityDescription")
  public static let quickTimeMetadataIsMontage = AVMetadataIdentifier(rawValue: "quickTimeMetadataIsMontage")
  public static let quickTimeMetadataFullFrameRatePlaybackIntent = AVMetadataIdentifier(rawValue: "quickTimeMetadataFullFrameRatePlaybackIntent")
  public static let quickTimeMetadataCinematicVideoIntent = AVMetadataIdentifier(rawValue: "quickTimeMetadataCinematicVideoIntent")
  public static let quickTimeMetadataCameraISOSensitivity = AVMetadataIdentifier(rawValue: "quickTimeMetadataCameraISOSensitivity")
  public static let quickTimeMetadataCameraWhiteBalance = AVMetadataIdentifier(rawValue: "quickTimeMetadataCameraWhiteBalance")
  public static let quickTimeMetadataWhiteBalanceByCCTWhiteBalanceFactors = AVMetadataIdentifier(rawValue: "quickTimeMetadataWhiteBalanceByCCTWhiteBalanceFactors")
  public static let quickTimeMetadataWhiteBalanceByCCTColorMatrices = AVMetadataIdentifier(rawValue: "quickTimeMetadataWhiteBalanceByCCTColorMatrices")
  public static let quickTimeMetadataCameraShutterSpeedAngle = AVMetadataIdentifier(rawValue: "quickTimeMetadataCameraShutterSpeedAngle")
  public static let quickTimeMetadataCameraShutterSpeedTime = AVMetadataIdentifier(rawValue: "quickTimeMetadataCameraShutterSpeedTime")
  public static let quickTimeMetadataCameraLensIrisFNumber = AVMetadataIdentifier(rawValue: "quickTimeMetadataCameraLensIrisFNumber")
  public static let quickTimeMetadataCameraLensModel = AVMetadataIdentifier(rawValue: "quickTimeMetadataCameraLensModel")
  public static let quickTimeMetadataCameraFocalLength35mmEquivalent = AVMetadataIdentifier(rawValue: "quickTimeMetadataCameraFocalLength35mmEquivalent")
  public static let quickTimeMetadataAutoLivePhoto = AVMetadataIdentifier(rawValue: "quickTimeMetadataAutoLivePhoto")
  public static let quickTimeMetadataLivePhotoVitalityScore = AVMetadataIdentifier(rawValue: "quickTimeMetadataLivePhotoVitalityScore")
  public static let quickTimeMetadataLivePhotoVitalityScoringVersion = AVMetadataIdentifier(rawValue: "quickTimeMetadataLivePhotoVitalityScoringVersion")
  public static let quickTimeMetadataSpatialOverCaptureQualityScore = AVMetadataIdentifier(rawValue: "quickTimeMetadataSpatialOverCaptureQualityScore")
  public static let quickTimeMetadataSpatialOverCaptureQualityScoringVersion = AVMetadataIdentifier(rawValue: "quickTimeMetadataSpatialOverCaptureQualityScoringVersion")
  public static let quickTimeMetadataLocationHorizontalAccuracyInMeters = AVMetadataIdentifier(rawValue: "quickTimeMetadataLocationHorizontalAccuracyInMeters")
  public static let iTunesMetadataAlbum = AVMetadataIdentifier(rawValue: "iTunesMetadataAlbum")
  public static let iTunesMetadataArtist = AVMetadataIdentifier(rawValue: "iTunesMetadataArtist")
  public static let iTunesMetadataUserComment = AVMetadataIdentifier(rawValue: "iTunesMetadataUserComment")
  public static let iTunesMetadataCoverArt = AVMetadataIdentifier(rawValue: "iTunesMetadataCoverArt")
  public static let iTunesMetadataCopyright = AVMetadataIdentifier(rawValue: "iTunesMetadataCopyright")
  public static let iTunesMetadataReleaseDate = AVMetadataIdentifier(rawValue: "iTunesMetadataReleaseDate")
  public static let iTunesMetadataEncodedBy = AVMetadataIdentifier(rawValue: "iTunesMetadataEncodedBy")
  public static let iTunesMetadataPredefinedGenre = AVMetadataIdentifier(rawValue: "iTunesMetadataPredefinedGenre")
  public static let iTunesMetadataUserGenre = AVMetadataIdentifier(rawValue: "iTunesMetadataUserGenre")
  public static let iTunesMetadataSongName = AVMetadataIdentifier(rawValue: "iTunesMetadataSongName")
  public static let iTunesMetadataTrackSubTitle = AVMetadataIdentifier(rawValue: "iTunesMetadataTrackSubTitle")
  public static let iTunesMetadataEncodingTool = AVMetadataIdentifier(rawValue: "iTunesMetadataEncodingTool")
  public static let iTunesMetadataComposer = AVMetadataIdentifier(rawValue: "iTunesMetadataComposer")
  public static let iTunesMetadataAlbumArtist = AVMetadataIdentifier(rawValue: "iTunesMetadataAlbumArtist")
  public static let iTunesMetadataAccountKind = AVMetadataIdentifier(rawValue: "iTunesMetadataAccountKind")
  public static let iTunesMetadataAppleID = AVMetadataIdentifier(rawValue: "iTunesMetadataAppleID")
  public static let iTunesMetadataArtistID = AVMetadataIdentifier(rawValue: "iTunesMetadataArtistID")
  public static let iTunesMetadataSongID = AVMetadataIdentifier(rawValue: "iTunesMetadataSongID")
  public static let iTunesMetadataDiscCompilation = AVMetadataIdentifier(rawValue: "iTunesMetadataDiscCompilation")
  public static let iTunesMetadataDiscNumber = AVMetadataIdentifier(rawValue: "iTunesMetadataDiscNumber")
  public static let iTunesMetadataGenreID = AVMetadataIdentifier(rawValue: "iTunesMetadataGenreID")
  public static let iTunesMetadataGrouping = AVMetadataIdentifier(rawValue: "iTunesMetadataGrouping")
  public static let iTunesMetadataPlaylistID = AVMetadataIdentifier(rawValue: "iTunesMetadataPlaylistID")
  public static let iTunesMetadataContentRating = AVMetadataIdentifier(rawValue: "iTunesMetadataContentRating")
  public static let iTunesMetadataBeatsPerMin = AVMetadataIdentifier(rawValue: "iTunesMetadataBeatsPerMin")
  public static let iTunesMetadataTrackNumber = AVMetadataIdentifier(rawValue: "iTunesMetadataTrackNumber")
  public static let iTunesMetadataArtDirector = AVMetadataIdentifier(rawValue: "iTunesMetadataArtDirector")
  public static let iTunesMetadataArranger = AVMetadataIdentifier(rawValue: "iTunesMetadataArranger")
  public static let iTunesMetadataAuthor = AVMetadataIdentifier(rawValue: "iTunesMetadataAuthor")
  public static let iTunesMetadataLyrics = AVMetadataIdentifier(rawValue: "iTunesMetadataLyrics")
  public static let iTunesMetadataAcknowledgement = AVMetadataIdentifier(rawValue: "iTunesMetadataAcknowledgement")
  public static let iTunesMetadataConductor = AVMetadataIdentifier(rawValue: "iTunesMetadataConductor")
  public static let iTunesMetadataDescription = AVMetadataIdentifier(rawValue: "iTunesMetadataDescription")
  public static let iTunesMetadataDirector = AVMetadataIdentifier(rawValue: "iTunesMetadataDirector")
  public static let iTunesMetadataEQ = AVMetadataIdentifier(rawValue: "iTunesMetadataEQ")
  public static let iTunesMetadataLinerNotes = AVMetadataIdentifier(rawValue: "iTunesMetadataLinerNotes")
  public static let iTunesMetadataRecordCompany = AVMetadataIdentifier(rawValue: "iTunesMetadataRecordCompany")
  public static let iTunesMetadataOriginalArtist = AVMetadataIdentifier(rawValue: "iTunesMetadataOriginalArtist")
  public static let iTunesMetadataPhonogramRights = AVMetadataIdentifier(rawValue: "iTunesMetadataPhonogramRights")
  public static let iTunesMetadataProducer = AVMetadataIdentifier(rawValue: "iTunesMetadataProducer")
  public static let iTunesMetadataPerformer = AVMetadataIdentifier(rawValue: "iTunesMetadataPerformer")
  public static let iTunesMetadataPublisher = AVMetadataIdentifier(rawValue: "iTunesMetadataPublisher")
  public static let iTunesMetadataSoundEngineer = AVMetadataIdentifier(rawValue: "iTunesMetadataSoundEngineer")
  public static let iTunesMetadataSoloist = AVMetadataIdentifier(rawValue: "iTunesMetadataSoloist")
  public static let iTunesMetadataCredits = AVMetadataIdentifier(rawValue: "iTunesMetadataCredits")
  public static let iTunesMetadataThanks = AVMetadataIdentifier(rawValue: "iTunesMetadataThanks")
  public static let iTunesMetadataOnlineExtras = AVMetadataIdentifier(rawValue: "iTunesMetadataOnlineExtras")
  public static let iTunesMetadataExecProducer = AVMetadataIdentifier(rawValue: "iTunesMetadataExecProducer")
  public static let id3MetadataAudioEncryption = AVMetadataIdentifier(rawValue: "id3MetadataAudioEncryption")
  public static let id3MetadataAttachedPicture = AVMetadataIdentifier(rawValue: "id3MetadataAttachedPicture")
  public static let id3MetadataAudioSeekPointIndex = AVMetadataIdentifier(rawValue: "id3MetadataAudioSeekPointIndex")
  public static let id3MetadataComments = AVMetadataIdentifier(rawValue: "id3MetadataComments")
  public static let id3MetadataCommercial = AVMetadataIdentifier(rawValue: "id3MetadataCommercial")
  public static let id3MetadataCommerical = AVMetadataIdentifier(rawValue: "id3MetadataCommerical")
  public static let id3MetadataEncryption = AVMetadataIdentifier(rawValue: "id3MetadataEncryption")
  public static let id3MetadataEqualization = AVMetadataIdentifier(rawValue: "id3MetadataEqualization")
  public static let id3MetadataEqualization2 = AVMetadataIdentifier(rawValue: "id3MetadataEqualization2")
  public static let id3MetadataEventTimingCodes = AVMetadataIdentifier(rawValue: "id3MetadataEventTimingCodes")
  public static let id3MetadataGeneralEncapsulatedObject = AVMetadataIdentifier(rawValue: "id3MetadataGeneralEncapsulatedObject")
  public static let id3MetadataGroupIdentifier = AVMetadataIdentifier(rawValue: "id3MetadataGroupIdentifier")
  public static let id3MetadataInvolvedPeopleList_v23 = AVMetadataIdentifier(rawValue: "id3MetadataInvolvedPeopleList_v23")
  public static let id3MetadataLink = AVMetadataIdentifier(rawValue: "id3MetadataLink")
  public static let id3MetadataMusicCDIdentifier = AVMetadataIdentifier(rawValue: "id3MetadataMusicCDIdentifier")
  public static let id3MetadataMPEGLocationLookupTable = AVMetadataIdentifier(rawValue: "id3MetadataMPEGLocationLookupTable")
  public static let id3MetadataOwnership = AVMetadataIdentifier(rawValue: "id3MetadataOwnership")
  public static let id3MetadataPrivate = AVMetadataIdentifier(rawValue: "id3MetadataPrivate")
  public static let id3MetadataPlayCounter = AVMetadataIdentifier(rawValue: "id3MetadataPlayCounter")
  public static let id3MetadataPopularimeter = AVMetadataIdentifier(rawValue: "id3MetadataPopularimeter")
  public static let id3MetadataPositionSynchronization = AVMetadataIdentifier(rawValue: "id3MetadataPositionSynchronization")
  public static let id3MetadataRecommendedBufferSize = AVMetadataIdentifier(rawValue: "id3MetadataRecommendedBufferSize")
  public static let id3MetadataRelativeVolumeAdjustment = AVMetadataIdentifier(rawValue: "id3MetadataRelativeVolumeAdjustment")
  public static let id3MetadataRelativeVolumeAdjustment2 = AVMetadataIdentifier(rawValue: "id3MetadataRelativeVolumeAdjustment2")
  public static let id3MetadataReverb = AVMetadataIdentifier(rawValue: "id3MetadataReverb")
  public static let id3MetadataSeek = AVMetadataIdentifier(rawValue: "id3MetadataSeek")
  public static let id3MetadataSignature = AVMetadataIdentifier(rawValue: "id3MetadataSignature")
  public static let id3MetadataSynchronizedLyric = AVMetadataIdentifier(rawValue: "id3MetadataSynchronizedLyric")
  public static let id3MetadataSynchronizedTempoCodes = AVMetadataIdentifier(rawValue: "id3MetadataSynchronizedTempoCodes")
  public static let id3MetadataAlbumTitle = AVMetadataIdentifier(rawValue: "id3MetadataAlbumTitle")
  public static let id3MetadataBeatsPerMinute = AVMetadataIdentifier(rawValue: "id3MetadataBeatsPerMinute")
  public static let id3MetadataComposer = AVMetadataIdentifier(rawValue: "id3MetadataComposer")
  public static let id3MetadataContentType = AVMetadataIdentifier(rawValue: "id3MetadataContentType")
  public static let id3MetadataCopyright = AVMetadataIdentifier(rawValue: "id3MetadataCopyright")
  public static let id3MetadataDate = AVMetadataIdentifier(rawValue: "id3MetadataDate")
  public static let id3MetadataEncodingTime = AVMetadataIdentifier(rawValue: "id3MetadataEncodingTime")
  public static let id3MetadataPlaylistDelay = AVMetadataIdentifier(rawValue: "id3MetadataPlaylistDelay")
  public static let id3MetadataOriginalReleaseTime = AVMetadataIdentifier(rawValue: "id3MetadataOriginalReleaseTime")
  public static let id3MetadataRecordingTime = AVMetadataIdentifier(rawValue: "id3MetadataRecordingTime")
  public static let id3MetadataReleaseTime = AVMetadataIdentifier(rawValue: "id3MetadataReleaseTime")
  public static let id3MetadataTaggingTime = AVMetadataIdentifier(rawValue: "id3MetadataTaggingTime")
  public static let id3MetadataEncodedBy = AVMetadataIdentifier(rawValue: "id3MetadataEncodedBy")
  public static let id3MetadataLyricist = AVMetadataIdentifier(rawValue: "id3MetadataLyricist")
  public static let id3MetadataFileType = AVMetadataIdentifier(rawValue: "id3MetadataFileType")
  public static let id3MetadataTime = AVMetadataIdentifier(rawValue: "id3MetadataTime")
  public static let id3MetadataInvolvedPeopleList_v24 = AVMetadataIdentifier(rawValue: "id3MetadataInvolvedPeopleList_v24")
  public static let id3MetadataContentGroupDescription = AVMetadataIdentifier(rawValue: "id3MetadataContentGroupDescription")
  public static let id3MetadataTitleDescription = AVMetadataIdentifier(rawValue: "id3MetadataTitleDescription")
  public static let id3MetadataSubTitle = AVMetadataIdentifier(rawValue: "id3MetadataSubTitle")
  public static let id3MetadataInitialKey = AVMetadataIdentifier(rawValue: "id3MetadataInitialKey")
  public static let id3MetadataLanguage = AVMetadataIdentifier(rawValue: "id3MetadataLanguage")
  public static let id3MetadataLength = AVMetadataIdentifier(rawValue: "id3MetadataLength")
  public static let id3MetadataMusicianCreditsList = AVMetadataIdentifier(rawValue: "id3MetadataMusicianCreditsList")
  public static let id3MetadataMediaType = AVMetadataIdentifier(rawValue: "id3MetadataMediaType")
  public static let id3MetadataMood = AVMetadataIdentifier(rawValue: "id3MetadataMood")
  public static let id3MetadataOriginalAlbumTitle = AVMetadataIdentifier(rawValue: "id3MetadataOriginalAlbumTitle")
  public static let id3MetadataOriginalFilename = AVMetadataIdentifier(rawValue: "id3MetadataOriginalFilename")
  public static let id3MetadataOriginalLyricist = AVMetadataIdentifier(rawValue: "id3MetadataOriginalLyricist")
  public static let id3MetadataOriginalArtist = AVMetadataIdentifier(rawValue: "id3MetadataOriginalArtist")
  public static let id3MetadataOriginalReleaseYear = AVMetadataIdentifier(rawValue: "id3MetadataOriginalReleaseYear")
  public static let id3MetadataFileOwner = AVMetadataIdentifier(rawValue: "id3MetadataFileOwner")
  public static let id3MetadataLeadPerformer = AVMetadataIdentifier(rawValue: "id3MetadataLeadPerformer")
  public static let id3MetadataBand = AVMetadataIdentifier(rawValue: "id3MetadataBand")
  public static let id3MetadataConductor = AVMetadataIdentifier(rawValue: "id3MetadataConductor")
  public static let id3MetadataModifiedBy = AVMetadataIdentifier(rawValue: "id3MetadataModifiedBy")
  public static let id3MetadataPartOfASet = AVMetadataIdentifier(rawValue: "id3MetadataPartOfASet")
  public static let id3MetadataProducedNotice = AVMetadataIdentifier(rawValue: "id3MetadataProducedNotice")
  public static let id3MetadataPublisher = AVMetadataIdentifier(rawValue: "id3MetadataPublisher")
  public static let id3MetadataTrackNumber = AVMetadataIdentifier(rawValue: "id3MetadataTrackNumber")
  public static let id3MetadataRecordingDates = AVMetadataIdentifier(rawValue: "id3MetadataRecordingDates")
  public static let id3MetadataInternetRadioStationName = AVMetadataIdentifier(rawValue: "id3MetadataInternetRadioStationName")
  public static let id3MetadataInternetRadioStationOwner = AVMetadataIdentifier(rawValue: "id3MetadataInternetRadioStationOwner")
  public static let id3MetadataSize = AVMetadataIdentifier(rawValue: "id3MetadataSize")
  public static let id3MetadataAlbumSortOrder = AVMetadataIdentifier(rawValue: "id3MetadataAlbumSortOrder")
  public static let id3MetadataPerformerSortOrder = AVMetadataIdentifier(rawValue: "id3MetadataPerformerSortOrder")
  public static let id3MetadataTitleSortOrder = AVMetadataIdentifier(rawValue: "id3MetadataTitleSortOrder")
  public static let id3MetadataInternationalStandardRecordingCode = AVMetadataIdentifier(rawValue: "id3MetadataInternationalStandardRecordingCode")
  public static let id3MetadataEncodedWith = AVMetadataIdentifier(rawValue: "id3MetadataEncodedWith")
  public static let id3MetadataSetSubtitle = AVMetadataIdentifier(rawValue: "id3MetadataSetSubtitle")
  public static let id3MetadataYear = AVMetadataIdentifier(rawValue: "id3MetadataYear")
  public static let id3MetadataUserText = AVMetadataIdentifier(rawValue: "id3MetadataUserText")
  public static let id3MetadataUniqueFileIdentifier = AVMetadataIdentifier(rawValue: "id3MetadataUniqueFileIdentifier")
  public static let id3MetadataTermsOfUse = AVMetadataIdentifier(rawValue: "id3MetadataTermsOfUse")
  public static let id3MetadataUnsynchronizedLyric = AVMetadataIdentifier(rawValue: "id3MetadataUnsynchronizedLyric")
  public static let id3MetadataCommercialInformation = AVMetadataIdentifier(rawValue: "id3MetadataCommercialInformation")
  public static let id3MetadataCopyrightInformation = AVMetadataIdentifier(rawValue: "id3MetadataCopyrightInformation")
  public static let id3MetadataOfficialAudioFileWebpage = AVMetadataIdentifier(rawValue: "id3MetadataOfficialAudioFileWebpage")
  public static let id3MetadataOfficialArtistWebpage = AVMetadataIdentifier(rawValue: "id3MetadataOfficialArtistWebpage")
  public static let id3MetadataOfficialAudioSourceWebpage = AVMetadataIdentifier(rawValue: "id3MetadataOfficialAudioSourceWebpage")
  public static let id3MetadataOfficialInternetRadioStationHomepage = AVMetadataIdentifier(rawValue: "id3MetadataOfficialInternetRadioStationHomepage")
  public static let id3MetadataPayment = AVMetadataIdentifier(rawValue: "id3MetadataPayment")
  public static let id3MetadataOfficialPublisherWebpage = AVMetadataIdentifier(rawValue: "id3MetadataOfficialPublisherWebpage")
  public static let id3MetadataUserURL = AVMetadataIdentifier(rawValue: "id3MetadataUserURL")
  public static let icyMetadataStreamTitle = AVMetadataIdentifier(rawValue: "icyMetadataStreamTitle")
  public static let icyMetadataStreamURL = AVMetadataIdentifier(rawValue: "icyMetadataStreamURL")
}

open class AVMetadataItem: NSObject, @unchecked Sendable {
  public override init() { super.init() }
  public var identifier: AVMetadataIdentifier? { nil }
  public var extendedLanguageTag: String? { nil }
  public var locale: Locale? { nil }
  public var time: CMTime { .zero }
  public var duration: CMTime { .zero }
  public var dataType: String? { nil }
  public var value: (any NSCopying & NSObjectProtocol)? { nil }
  public var extraAttributes: [AVMetadataExtraAttributeKey : Any]? { nil }
  public var startDate: Date? { nil }
  public var stringValue: String? { nil }
  public var numberValue: NSNumber? { nil }
  public var dateValue: Date? { nil }
  public var dataValue: Data? { nil }
  public class func metadataItems(from metadataItems: [AVMetadataItem], filteredAndSortedAccordingToPreferredLanguages preferredLanguages: [String]) -> [AVMetadataItem] { [] }
  public class func metadataItems(from metadataItems: [AVMetadataItem], filteredByIdentifier identifier: AVMetadataIdentifier) -> [AVMetadataItem] { [] }
  public class func metadataItems(from metadataItems: [AVMetadataItem], filteredBy metadataItemFilter: AVMetadataItemFilter) -> [AVMetadataItem] { [] }
  public class func identifier(forKey key: Any, keySpace: AVMetadataKeySpace) -> AVMetadataIdentifier? { nil }
  public class func keySpace(forIdentifier identifier: AVMetadataIdentifier) -> AVMetadataKeySpace? { nil }
  public class func key(forIdentifier identifier: AVMetadataIdentifier) -> Any? { nil }
  public var key: (any NSCopying & NSObjectProtocol)? { nil }
  public var commonKey: AVMetadataKey? { nil }
  public var keySpace: AVMetadataKeySpace? { nil }
  public init(propertiesOf metadataItem: AVMetadataItem, valueLoadingHandler handler: @escaping (AVMetadataItemValueRequest) -> Void) {}
  public init(propertiesOfMetadataItem metadataItem: AVMetadataItem, valueLoadingHandler handler: @escaping (AVMetadataItemValueRequest) -> Void) {}
  public class func metadataItems(from metadataItems: [AVMetadataItem], with locale: Locale) -> [AVMetadataItem] { [] }
  public class func metadataItems(from metadataItems: [AVMetadataItem], withKey key: Any?, keySpace: AVMetadataKeySpace?) -> [AVMetadataItem] { [] }
}

open class AVMetadataItemFilter: NSObject, @unchecked Sendable {
  public override init() { super.init() }
  public class func forSharing() -> AVMetadataItemFilter { AVMetadataItemFilter() }
}

open class AVMetadataItemValueRequest: NSObject, @unchecked Sendable {
  public override init() { super.init() }
  public weak var metadataItem: AVMetadataItem? { nil }
  public func respond(value: any NSCopying & NSObjectProtocol) {}
  public func respond(error: any Error) {}
}

public struct AVMetadataKey: RawRepresentable, Hashable, Sendable, ExpressibleByStringLiteral {
  public let rawValue: String
  public init(rawValue: String) { self.rawValue = rawValue }
  public init(stringLiteral value: String) { self.init(rawValue: value) }
  public static let commonKeyTitle = AVMetadataKey(rawValue: "commonKeyTitle")
  public static let commonKeyCreator = AVMetadataKey(rawValue: "commonKeyCreator")
  public static let commonKeySubject = AVMetadataKey(rawValue: "commonKeySubject")
  public static let commonKeyDescription = AVMetadataKey(rawValue: "commonKeyDescription")
  public static let commonKeyPublisher = AVMetadataKey(rawValue: "commonKeyPublisher")
  public static let commonKeyContributor = AVMetadataKey(rawValue: "commonKeyContributor")
  public static let commonKeyCreationDate = AVMetadataKey(rawValue: "commonKeyCreationDate")
  public static let commonKeyLastModifiedDate = AVMetadataKey(rawValue: "commonKeyLastModifiedDate")
  public static let commonKeyType = AVMetadataKey(rawValue: "commonKeyType")
  public static let commonKeyFormat = AVMetadataKey(rawValue: "commonKeyFormat")
  public static let commonKeyIdentifier = AVMetadataKey(rawValue: "commonKeyIdentifier")
  public static let commonKeySource = AVMetadataKey(rawValue: "commonKeySource")
  public static let commonKeyLanguage = AVMetadataKey(rawValue: "commonKeyLanguage")
  public static let commonKeyRelation = AVMetadataKey(rawValue: "commonKeyRelation")
  public static let commonKeyLocation = AVMetadataKey(rawValue: "commonKeyLocation")
  public static let commonKeyCopyrights = AVMetadataKey(rawValue: "commonKeyCopyrights")
  public static let commonKeyAlbumName = AVMetadataKey(rawValue: "commonKeyAlbumName")
  public static let commonKeyAuthor = AVMetadataKey(rawValue: "commonKeyAuthor")
  public static let commonKeyArtist = AVMetadataKey(rawValue: "commonKeyArtist")
  public static let commonKeyArtwork = AVMetadataKey(rawValue: "commonKeyArtwork")
  public static let commonKeyMake = AVMetadataKey(rawValue: "commonKeyMake")
  public static let commonKeyModel = AVMetadataKey(rawValue: "commonKeyModel")
  public static let commonKeySoftware = AVMetadataKey(rawValue: "commonKeySoftware")
  public static let commonKeyAccessibilityDescription = AVMetadataKey(rawValue: "commonKeyAccessibilityDescription")
  public static let quickTimeUserDataKeyAlbum = AVMetadataKey(rawValue: "quickTimeUserDataKeyAlbum")
  public static let quickTimeUserDataKeyArranger = AVMetadataKey(rawValue: "quickTimeUserDataKeyArranger")
  public static let quickTimeUserDataKeyArtist = AVMetadataKey(rawValue: "quickTimeUserDataKeyArtist")
  public static let quickTimeUserDataKeyAuthor = AVMetadataKey(rawValue: "quickTimeUserDataKeyAuthor")
  public static let quickTimeUserDataKeyChapter = AVMetadataKey(rawValue: "quickTimeUserDataKeyChapter")
  public static let quickTimeUserDataKeyComment = AVMetadataKey(rawValue: "quickTimeUserDataKeyComment")
  public static let quickTimeUserDataKeyComposer = AVMetadataKey(rawValue: "quickTimeUserDataKeyComposer")
  public static let quickTimeUserDataKeyCopyright = AVMetadataKey(rawValue: "quickTimeUserDataKeyCopyright")
  public static let quickTimeUserDataKeyCreationDate = AVMetadataKey(rawValue: "quickTimeUserDataKeyCreationDate")
  public static let quickTimeUserDataKeyDescription = AVMetadataKey(rawValue: "quickTimeUserDataKeyDescription")
  public static let quickTimeUserDataKeyDirector = AVMetadataKey(rawValue: "quickTimeUserDataKeyDirector")
  public static let quickTimeUserDataKeyDisclaimer = AVMetadataKey(rawValue: "quickTimeUserDataKeyDisclaimer")
  public static let quickTimeUserDataKeyEncodedBy = AVMetadataKey(rawValue: "quickTimeUserDataKeyEncodedBy")
  public static let quickTimeUserDataKeyFullName = AVMetadataKey(rawValue: "quickTimeUserDataKeyFullName")
  public static let quickTimeUserDataKeyGenre = AVMetadataKey(rawValue: "quickTimeUserDataKeyGenre")
  public static let quickTimeUserDataKeyHostComputer = AVMetadataKey(rawValue: "quickTimeUserDataKeyHostComputer")
  public static let quickTimeUserDataKeyInformation = AVMetadataKey(rawValue: "quickTimeUserDataKeyInformation")
  public static let quickTimeUserDataKeyKeywords = AVMetadataKey(rawValue: "quickTimeUserDataKeyKeywords")
  public static let quickTimeUserDataKeyMake = AVMetadataKey(rawValue: "quickTimeUserDataKeyMake")
  public static let quickTimeUserDataKeyModel = AVMetadataKey(rawValue: "quickTimeUserDataKeyModel")
  public static let quickTimeUserDataKeyOriginalArtist = AVMetadataKey(rawValue: "quickTimeUserDataKeyOriginalArtist")
  public static let quickTimeUserDataKeyOriginalFormat = AVMetadataKey(rawValue: "quickTimeUserDataKeyOriginalFormat")
  public static let quickTimeUserDataKeyOriginalSource = AVMetadataKey(rawValue: "quickTimeUserDataKeyOriginalSource")
  public static let quickTimeUserDataKeyPerformers = AVMetadataKey(rawValue: "quickTimeUserDataKeyPerformers")
  public static let quickTimeUserDataKeyProducer = AVMetadataKey(rawValue: "quickTimeUserDataKeyProducer")
  public static let quickTimeUserDataKeyPublisher = AVMetadataKey(rawValue: "quickTimeUserDataKeyPublisher")
  public static let quickTimeUserDataKeyProduct = AVMetadataKey(rawValue: "quickTimeUserDataKeyProduct")
  public static let quickTimeUserDataKeySoftware = AVMetadataKey(rawValue: "quickTimeUserDataKeySoftware")
  public static let quickTimeUserDataKeySpecialPlaybackRequirements = AVMetadataKey(rawValue: "quickTimeUserDataKeySpecialPlaybackRequirements")
  public static let quickTimeUserDataKeyTrack = AVMetadataKey(rawValue: "quickTimeUserDataKeyTrack")
  public static let quickTimeUserDataKeyWarning = AVMetadataKey(rawValue: "quickTimeUserDataKeyWarning")
  public static let quickTimeUserDataKeyWriter = AVMetadataKey(rawValue: "quickTimeUserDataKeyWriter")
  public static let quickTimeUserDataKeyURLLink = AVMetadataKey(rawValue: "quickTimeUserDataKeyURLLink")
  public static let quickTimeUserDataKeyLocationISO6709 = AVMetadataKey(rawValue: "quickTimeUserDataKeyLocationISO6709")
  public static let quickTimeUserDataKeyTrackName = AVMetadataKey(rawValue: "quickTimeUserDataKeyTrackName")
  public static let quickTimeUserDataKeyCredits = AVMetadataKey(rawValue: "quickTimeUserDataKeyCredits")
  public static let quickTimeUserDataKeyPhonogramRights = AVMetadataKey(rawValue: "quickTimeUserDataKeyPhonogramRights")
  public static let quickTimeUserDataKeyTaggedCharacteristic = AVMetadataKey(rawValue: "quickTimeUserDataKeyTaggedCharacteristic")
  public static let quickTimeUserDataKeyAccessibilityDescription = AVMetadataKey(rawValue: "quickTimeUserDataKeyAccessibilityDescription")
  public static let isoUserDataKeyCopyright = AVMetadataKey(rawValue: "isoUserDataKeyCopyright")
  public static let isoUserDataKeyTaggedCharacteristic = AVMetadataKey(rawValue: "isoUserDataKeyTaggedCharacteristic")
  public static let isoUserDataKeyDate = AVMetadataKey(rawValue: "isoUserDataKeyDate")
  public static let isoUserDataKeyAccessibilityDescription = AVMetadataKey(rawValue: "isoUserDataKeyAccessibilityDescription")
  public static let metadata3GPUserDataKeyCopyright = AVMetadataKey(rawValue: "metadata3GPUserDataKeyCopyright")
  public static let metadata3GPUserDataKeyAuthor = AVMetadataKey(rawValue: "metadata3GPUserDataKeyAuthor")
  public static let metadata3GPUserDataKeyPerformer = AVMetadataKey(rawValue: "metadata3GPUserDataKeyPerformer")
  public static let metadata3GPUserDataKeyGenre = AVMetadataKey(rawValue: "metadata3GPUserDataKeyGenre")
  public static let metadata3GPUserDataKeyRecordingYear = AVMetadataKey(rawValue: "metadata3GPUserDataKeyRecordingYear")
  public static let metadata3GPUserDataKeyLocation = AVMetadataKey(rawValue: "metadata3GPUserDataKeyLocation")
  public static let metadata3GPUserDataKeyTitle = AVMetadataKey(rawValue: "metadata3GPUserDataKeyTitle")
  public static let metadata3GPUserDataKeyDescription = AVMetadataKey(rawValue: "metadata3GPUserDataKeyDescription")
  public static let metadata3GPUserDataKeyCollection = AVMetadataKey(rawValue: "metadata3GPUserDataKeyCollection")
  public static let metadata3GPUserDataKeyUserRating = AVMetadataKey(rawValue: "metadata3GPUserDataKeyUserRating")
  public static let metadata3GPUserDataKeyThumbnail = AVMetadataKey(rawValue: "metadata3GPUserDataKeyThumbnail")
  public static let metadata3GPUserDataKeyAlbumAndTrack = AVMetadataKey(rawValue: "metadata3GPUserDataKeyAlbumAndTrack")
  public static let metadata3GPUserDataKeyKeywordList = AVMetadataKey(rawValue: "metadata3GPUserDataKeyKeywordList")
  public static let metadata3GPUserDataKeyMediaClassification = AVMetadataKey(rawValue: "metadata3GPUserDataKeyMediaClassification")
  public static let metadata3GPUserDataKeyMediaRating = AVMetadataKey(rawValue: "metadata3GPUserDataKeyMediaRating")
  public static let quickTimeMetadataKeyAuthor = AVMetadataKey(rawValue: "quickTimeMetadataKeyAuthor")
  public static let quickTimeMetadataKeyComment = AVMetadataKey(rawValue: "quickTimeMetadataKeyComment")
  public static let quickTimeMetadataKeyCopyright = AVMetadataKey(rawValue: "quickTimeMetadataKeyCopyright")
  public static let quickTimeMetadataKeyCreationDate = AVMetadataKey(rawValue: "quickTimeMetadataKeyCreationDate")
  public static let quickTimeMetadataKeyDirector = AVMetadataKey(rawValue: "quickTimeMetadataKeyDirector")
  public static let quickTimeMetadataKeyDisplayName = AVMetadataKey(rawValue: "quickTimeMetadataKeyDisplayName")
  public static let quickTimeMetadataKeyInformation = AVMetadataKey(rawValue: "quickTimeMetadataKeyInformation")
  public static let quickTimeMetadataKeyKeywords = AVMetadataKey(rawValue: "quickTimeMetadataKeyKeywords")
  public static let quickTimeMetadataKeyProducer = AVMetadataKey(rawValue: "quickTimeMetadataKeyProducer")
  public static let quickTimeMetadataKeyPublisher = AVMetadataKey(rawValue: "quickTimeMetadataKeyPublisher")
  public static let quickTimeMetadataKeyAlbum = AVMetadataKey(rawValue: "quickTimeMetadataKeyAlbum")
  public static let quickTimeMetadataKeyArtist = AVMetadataKey(rawValue: "quickTimeMetadataKeyArtist")
  public static let quickTimeMetadataKeyArtwork = AVMetadataKey(rawValue: "quickTimeMetadataKeyArtwork")
  public static let quickTimeMetadataKeyDescription = AVMetadataKey(rawValue: "quickTimeMetadataKeyDescription")
  public static let quickTimeMetadataKeySoftware = AVMetadataKey(rawValue: "quickTimeMetadataKeySoftware")
  public static let quickTimeMetadataKeyYear = AVMetadataKey(rawValue: "quickTimeMetadataKeyYear")
  public static let quickTimeMetadataKeyGenre = AVMetadataKey(rawValue: "quickTimeMetadataKeyGenre")
  public static let quickTimeMetadataKeyiXML = AVMetadataKey(rawValue: "quickTimeMetadataKeyiXML")
  public static let quickTimeMetadataKeyLocationISO6709 = AVMetadataKey(rawValue: "quickTimeMetadataKeyLocationISO6709")
  public static let quickTimeMetadataKeyMake = AVMetadataKey(rawValue: "quickTimeMetadataKeyMake")
  public static let quickTimeMetadataKeyModel = AVMetadataKey(rawValue: "quickTimeMetadataKeyModel")
  public static let quickTimeMetadataKeyArranger = AVMetadataKey(rawValue: "quickTimeMetadataKeyArranger")
  public static let quickTimeMetadataKeyEncodedBy = AVMetadataKey(rawValue: "quickTimeMetadataKeyEncodedBy")
  public static let quickTimeMetadataKeyOriginalArtist = AVMetadataKey(rawValue: "quickTimeMetadataKeyOriginalArtist")
  public static let quickTimeMetadataKeyPerformer = AVMetadataKey(rawValue: "quickTimeMetadataKeyPerformer")
  public static let quickTimeMetadataKeyComposer = AVMetadataKey(rawValue: "quickTimeMetadataKeyComposer")
  public static let quickTimeMetadataKeyCredits = AVMetadataKey(rawValue: "quickTimeMetadataKeyCredits")
  public static let quickTimeMetadataKeyPhonogramRights = AVMetadataKey(rawValue: "quickTimeMetadataKeyPhonogramRights")
  public static let quickTimeMetadataKeyCameraIdentifier = AVMetadataKey(rawValue: "quickTimeMetadataKeyCameraIdentifier")
  public static let quickTimeMetadataKeyCameraFrameReadoutTime = AVMetadataKey(rawValue: "quickTimeMetadataKeyCameraFrameReadoutTime")
  public static let quickTimeMetadataKeyTitle = AVMetadataKey(rawValue: "quickTimeMetadataKeyTitle")
  public static let quickTimeMetadataKeyCollectionUser = AVMetadataKey(rawValue: "quickTimeMetadataKeyCollectionUser")
  public static let quickTimeMetadataKeyRatingUser = AVMetadataKey(rawValue: "quickTimeMetadataKeyRatingUser")
  public static let quickTimeMetadataKeyLocationName = AVMetadataKey(rawValue: "quickTimeMetadataKeyLocationName")
  public static let quickTimeMetadataKeyLocationBody = AVMetadataKey(rawValue: "quickTimeMetadataKeyLocationBody")
  public static let quickTimeMetadataKeyLocationNote = AVMetadataKey(rawValue: "quickTimeMetadataKeyLocationNote")
  public static let quickTimeMetadataKeyLocationRole = AVMetadataKey(rawValue: "quickTimeMetadataKeyLocationRole")
  public static let quickTimeMetadataKeyLocationDate = AVMetadataKey(rawValue: "quickTimeMetadataKeyLocationDate")
  public static let quickTimeMetadataKeyDirectionFacing = AVMetadataKey(rawValue: "quickTimeMetadataKeyDirectionFacing")
  public static let quickTimeMetadataKeyDirectionMotion = AVMetadataKey(rawValue: "quickTimeMetadataKeyDirectionMotion")
  public static let quickTimeMetadataKeyContentIdentifier = AVMetadataKey(rawValue: "quickTimeMetadataKeyContentIdentifier")
  public static let quickTimeMetadataKeyAccessibilityDescription = AVMetadataKey(rawValue: "quickTimeMetadataKeyAccessibilityDescription")
  public static let quickTimeMetadataKeyIsMontage = AVMetadataKey(rawValue: "quickTimeMetadataKeyIsMontage")
  public static let quickTimeMetadataKeyFullFrameRatePlaybackIntent = AVMetadataKey(rawValue: "quickTimeMetadataKeyFullFrameRatePlaybackIntent")
  public static let quickTimeMetadataKeyCinematicVideoIntent = AVMetadataKey(rawValue: "quickTimeMetadataKeyCinematicVideoIntent")
  public static let quickTimeMetadataKeyCameraISOSensitivity = AVMetadataKey(rawValue: "quickTimeMetadataKeyCameraISOSensitivity")
  public static let quickTimeMetadataKeyCameraWhiteBalance = AVMetadataKey(rawValue: "quickTimeMetadataKeyCameraWhiteBalance")
  public static let quickTimeMetadataKeyWhiteBalanceByCCTWhiteBalanceFactors = AVMetadataKey(rawValue: "quickTimeMetadataKeyWhiteBalanceByCCTWhiteBalanceFactors")
  public static let quickTimeMetadataKeyWhiteBalanceByCCTColorMatrices = AVMetadataKey(rawValue: "quickTimeMetadataKeyWhiteBalanceByCCTColorMatrices")
  public static let quickTimeMetadataKeyCameraShutterSpeedAngle = AVMetadataKey(rawValue: "quickTimeMetadataKeyCameraShutterSpeedAngle")
  public static let quickTimeMetadataKeyCameraShutterSpeedTime = AVMetadataKey(rawValue: "quickTimeMetadataKeyCameraShutterSpeedTime")
  public static let quickTimeMetadataKeyCameraLensIrisFNumber = AVMetadataKey(rawValue: "quickTimeMetadataKeyCameraLensIrisFNumber")
  public static let quickTimeMetadataKeyCameraLensModel = AVMetadataKey(rawValue: "quickTimeMetadataKeyCameraLensModel")
  public static let quickTimeMetadataKeyCameraFocalLength35mmEquivalent = AVMetadataKey(rawValue: "quickTimeMetadataKeyCameraFocalLength35mmEquivalent")
  public static let iTunesMetadataKeyAlbum = AVMetadataKey(rawValue: "iTunesMetadataKeyAlbum")
  public static let iTunesMetadataKeyArtist = AVMetadataKey(rawValue: "iTunesMetadataKeyArtist")
  public static let iTunesMetadataKeyUserComment = AVMetadataKey(rawValue: "iTunesMetadataKeyUserComment")
  public static let iTunesMetadataKeyCoverArt = AVMetadataKey(rawValue: "iTunesMetadataKeyCoverArt")
  public static let iTunesMetadataKeyCopyright = AVMetadataKey(rawValue: "iTunesMetadataKeyCopyright")
  public static let iTunesMetadataKeyReleaseDate = AVMetadataKey(rawValue: "iTunesMetadataKeyReleaseDate")
  public static let iTunesMetadataKeyEncodedBy = AVMetadataKey(rawValue: "iTunesMetadataKeyEncodedBy")
  public static let iTunesMetadataKeyPredefinedGenre = AVMetadataKey(rawValue: "iTunesMetadataKeyPredefinedGenre")
  public static let iTunesMetadataKeyUserGenre = AVMetadataKey(rawValue: "iTunesMetadataKeyUserGenre")
  public static let iTunesMetadataKeySongName = AVMetadataKey(rawValue: "iTunesMetadataKeySongName")
  public static let iTunesMetadataKeyTrackSubTitle = AVMetadataKey(rawValue: "iTunesMetadataKeyTrackSubTitle")
  public static let iTunesMetadataKeyEncodingTool = AVMetadataKey(rawValue: "iTunesMetadataKeyEncodingTool")
  public static let iTunesMetadataKeyComposer = AVMetadataKey(rawValue: "iTunesMetadataKeyComposer")
  public static let iTunesMetadataKeyAlbumArtist = AVMetadataKey(rawValue: "iTunesMetadataKeyAlbumArtist")
  public static let iTunesMetadataKeyAccountKind = AVMetadataKey(rawValue: "iTunesMetadataKeyAccountKind")
  public static let iTunesMetadataKeyAppleID = AVMetadataKey(rawValue: "iTunesMetadataKeyAppleID")
  public static let iTunesMetadataKeyArtistID = AVMetadataKey(rawValue: "iTunesMetadataKeyArtistID")
  public static let iTunesMetadataKeySongID = AVMetadataKey(rawValue: "iTunesMetadataKeySongID")
  public static let iTunesMetadataKeyDiscCompilation = AVMetadataKey(rawValue: "iTunesMetadataKeyDiscCompilation")
  public static let iTunesMetadataKeyDiscNumber = AVMetadataKey(rawValue: "iTunesMetadataKeyDiscNumber")
  public static let iTunesMetadataKeyGenreID = AVMetadataKey(rawValue: "iTunesMetadataKeyGenreID")
  public static let iTunesMetadataKeyGrouping = AVMetadataKey(rawValue: "iTunesMetadataKeyGrouping")
  public static let iTunesMetadataKeyPlaylistID = AVMetadataKey(rawValue: "iTunesMetadataKeyPlaylistID")
  public static let iTunesMetadataKeyContentRating = AVMetadataKey(rawValue: "iTunesMetadataKeyContentRating")
  public static let iTunesMetadataKeyBeatsPerMin = AVMetadataKey(rawValue: "iTunesMetadataKeyBeatsPerMin")
  public static let iTunesMetadataKeyTrackNumber = AVMetadataKey(rawValue: "iTunesMetadataKeyTrackNumber")
  public static let iTunesMetadataKeyArtDirector = AVMetadataKey(rawValue: "iTunesMetadataKeyArtDirector")
  public static let iTunesMetadataKeyArranger = AVMetadataKey(rawValue: "iTunesMetadataKeyArranger")
  public static let iTunesMetadataKeyAuthor = AVMetadataKey(rawValue: "iTunesMetadataKeyAuthor")
  public static let iTunesMetadataKeyLyrics = AVMetadataKey(rawValue: "iTunesMetadataKeyLyrics")
  public static let iTunesMetadataKeyAcknowledgement = AVMetadataKey(rawValue: "iTunesMetadataKeyAcknowledgement")
  public static let iTunesMetadataKeyConductor = AVMetadataKey(rawValue: "iTunesMetadataKeyConductor")
  public static let iTunesMetadataKeyDescription = AVMetadataKey(rawValue: "iTunesMetadataKeyDescription")
  public static let iTunesMetadataKeyDirector = AVMetadataKey(rawValue: "iTunesMetadataKeyDirector")
  public static let iTunesMetadataKeyEQ = AVMetadataKey(rawValue: "iTunesMetadataKeyEQ")
  public static let iTunesMetadataKeyLinerNotes = AVMetadataKey(rawValue: "iTunesMetadataKeyLinerNotes")
  public static let iTunesMetadataKeyRecordCompany = AVMetadataKey(rawValue: "iTunesMetadataKeyRecordCompany")
  public static let iTunesMetadataKeyOriginalArtist = AVMetadataKey(rawValue: "iTunesMetadataKeyOriginalArtist")
  public static let iTunesMetadataKeyPhonogramRights = AVMetadataKey(rawValue: "iTunesMetadataKeyPhonogramRights")
  public static let iTunesMetadataKeyProducer = AVMetadataKey(rawValue: "iTunesMetadataKeyProducer")
  public static let iTunesMetadataKeyPerformer = AVMetadataKey(rawValue: "iTunesMetadataKeyPerformer")
  public static let iTunesMetadataKeyPublisher = AVMetadataKey(rawValue: "iTunesMetadataKeyPublisher")
  public static let iTunesMetadataKeySoundEngineer = AVMetadataKey(rawValue: "iTunesMetadataKeySoundEngineer")
  public static let iTunesMetadataKeySoloist = AVMetadataKey(rawValue: "iTunesMetadataKeySoloist")
  public static let iTunesMetadataKeyCredits = AVMetadataKey(rawValue: "iTunesMetadataKeyCredits")
  public static let iTunesMetadataKeyThanks = AVMetadataKey(rawValue: "iTunesMetadataKeyThanks")
  public static let iTunesMetadataKeyOnlineExtras = AVMetadataKey(rawValue: "iTunesMetadataKeyOnlineExtras")
  public static let iTunesMetadataKeyExecProducer = AVMetadataKey(rawValue: "iTunesMetadataKeyExecProducer")
  public static let id3MetadataKeyAudioEncryption = AVMetadataKey(rawValue: "id3MetadataKeyAudioEncryption")
  public static let id3MetadataKeyAttachedPicture = AVMetadataKey(rawValue: "id3MetadataKeyAttachedPicture")
  public static let id3MetadataKeyAudioSeekPointIndex = AVMetadataKey(rawValue: "id3MetadataKeyAudioSeekPointIndex")
  public static let id3MetadataKeyComments = AVMetadataKey(rawValue: "id3MetadataKeyComments")
  public static let id3MetadataKeyCommercial = AVMetadataKey(rawValue: "id3MetadataKeyCommercial")
  public static let id3MetadataKeyCommerical = AVMetadataKey(rawValue: "id3MetadataKeyCommerical")
  public static let id3MetadataKeyEncryption = AVMetadataKey(rawValue: "id3MetadataKeyEncryption")
  public static let id3MetadataKeyEqualization = AVMetadataKey(rawValue: "id3MetadataKeyEqualization")
  public static let id3MetadataKeyEqualization2 = AVMetadataKey(rawValue: "id3MetadataKeyEqualization2")
  public static let id3MetadataKeyEventTimingCodes = AVMetadataKey(rawValue: "id3MetadataKeyEventTimingCodes")
  public static let id3MetadataKeyGeneralEncapsulatedObject = AVMetadataKey(rawValue: "id3MetadataKeyGeneralEncapsulatedObject")
  public static let id3MetadataKeyGroupIdentifier = AVMetadataKey(rawValue: "id3MetadataKeyGroupIdentifier")
  public static let id3MetadataKeyInvolvedPeopleList_v23 = AVMetadataKey(rawValue: "id3MetadataKeyInvolvedPeopleList_v23")
  public static let id3MetadataKeyLink = AVMetadataKey(rawValue: "id3MetadataKeyLink")
  public static let id3MetadataKeyMusicCDIdentifier = AVMetadataKey(rawValue: "id3MetadataKeyMusicCDIdentifier")
  public static let id3MetadataKeyMPEGLocationLookupTable = AVMetadataKey(rawValue: "id3MetadataKeyMPEGLocationLookupTable")
  public static let id3MetadataKeyOwnership = AVMetadataKey(rawValue: "id3MetadataKeyOwnership")
  public static let id3MetadataKeyPrivate = AVMetadataKey(rawValue: "id3MetadataKeyPrivate")
  public static let id3MetadataKeyPlayCounter = AVMetadataKey(rawValue: "id3MetadataKeyPlayCounter")
  public static let id3MetadataKeyPopularimeter = AVMetadataKey(rawValue: "id3MetadataKeyPopularimeter")
  public static let id3MetadataKeyPositionSynchronization = AVMetadataKey(rawValue: "id3MetadataKeyPositionSynchronization")
  public static let id3MetadataKeyRecommendedBufferSize = AVMetadataKey(rawValue: "id3MetadataKeyRecommendedBufferSize")
  public static let id3MetadataKeyRelativeVolumeAdjustment = AVMetadataKey(rawValue: "id3MetadataKeyRelativeVolumeAdjustment")
  public static let id3MetadataKeyRelativeVolumeAdjustment2 = AVMetadataKey(rawValue: "id3MetadataKeyRelativeVolumeAdjustment2")
  public static let id3MetadataKeyReverb = AVMetadataKey(rawValue: "id3MetadataKeyReverb")
  public static let id3MetadataKeySeek = AVMetadataKey(rawValue: "id3MetadataKeySeek")
  public static let id3MetadataKeySignature = AVMetadataKey(rawValue: "id3MetadataKeySignature")
  public static let id3MetadataKeySynchronizedLyric = AVMetadataKey(rawValue: "id3MetadataKeySynchronizedLyric")
  public static let id3MetadataKeySynchronizedTempoCodes = AVMetadataKey(rawValue: "id3MetadataKeySynchronizedTempoCodes")
  public static let id3MetadataKeyAlbumTitle = AVMetadataKey(rawValue: "id3MetadataKeyAlbumTitle")
  public static let id3MetadataKeyBeatsPerMinute = AVMetadataKey(rawValue: "id3MetadataKeyBeatsPerMinute")
  public static let id3MetadataKeyComposer = AVMetadataKey(rawValue: "id3MetadataKeyComposer")
  public static let id3MetadataKeyContentType = AVMetadataKey(rawValue: "id3MetadataKeyContentType")
  public static let id3MetadataKeyCopyright = AVMetadataKey(rawValue: "id3MetadataKeyCopyright")
  public static let id3MetadataKeyDate = AVMetadataKey(rawValue: "id3MetadataKeyDate")
  public static let id3MetadataKeyEncodingTime = AVMetadataKey(rawValue: "id3MetadataKeyEncodingTime")
  public static let id3MetadataKeyPlaylistDelay = AVMetadataKey(rawValue: "id3MetadataKeyPlaylistDelay")
  public static let id3MetadataKeyOriginalReleaseTime = AVMetadataKey(rawValue: "id3MetadataKeyOriginalReleaseTime")
  public static let id3MetadataKeyRecordingTime = AVMetadataKey(rawValue: "id3MetadataKeyRecordingTime")
  public static let id3MetadataKeyReleaseTime = AVMetadataKey(rawValue: "id3MetadataKeyReleaseTime")
  public static let id3MetadataKeyTaggingTime = AVMetadataKey(rawValue: "id3MetadataKeyTaggingTime")
  public static let id3MetadataKeyEncodedBy = AVMetadataKey(rawValue: "id3MetadataKeyEncodedBy")
  public static let id3MetadataKeyLyricist = AVMetadataKey(rawValue: "id3MetadataKeyLyricist")
  public static let id3MetadataKeyFileType = AVMetadataKey(rawValue: "id3MetadataKeyFileType")
  public static let id3MetadataKeyTime = AVMetadataKey(rawValue: "id3MetadataKeyTime")
  public static let id3MetadataKeyInvolvedPeopleList_v24 = AVMetadataKey(rawValue: "id3MetadataKeyInvolvedPeopleList_v24")
  public static let id3MetadataKeyContentGroupDescription = AVMetadataKey(rawValue: "id3MetadataKeyContentGroupDescription")
  public static let id3MetadataKeyTitleDescription = AVMetadataKey(rawValue: "id3MetadataKeyTitleDescription")
  public static let id3MetadataKeySubTitle = AVMetadataKey(rawValue: "id3MetadataKeySubTitle")
  public static let id3MetadataKeyInitialKey = AVMetadataKey(rawValue: "id3MetadataKeyInitialKey")
  public static let id3MetadataKeyLanguage = AVMetadataKey(rawValue: "id3MetadataKeyLanguage")
  public static let id3MetadataKeyLength = AVMetadataKey(rawValue: "id3MetadataKeyLength")
  public static let id3MetadataKeyMusicianCreditsList = AVMetadataKey(rawValue: "id3MetadataKeyMusicianCreditsList")
  public static let id3MetadataKeyMediaType = AVMetadataKey(rawValue: "id3MetadataKeyMediaType")
  public static let id3MetadataKeyMood = AVMetadataKey(rawValue: "id3MetadataKeyMood")
  public static let id3MetadataKeyOriginalAlbumTitle = AVMetadataKey(rawValue: "id3MetadataKeyOriginalAlbumTitle")
  public static let id3MetadataKeyOriginalFilename = AVMetadataKey(rawValue: "id3MetadataKeyOriginalFilename")
  public static let id3MetadataKeyOriginalLyricist = AVMetadataKey(rawValue: "id3MetadataKeyOriginalLyricist")
  public static let id3MetadataKeyOriginalArtist = AVMetadataKey(rawValue: "id3MetadataKeyOriginalArtist")
  public static let id3MetadataKeyOriginalReleaseYear = AVMetadataKey(rawValue: "id3MetadataKeyOriginalReleaseYear")
  public static let id3MetadataKeyFileOwner = AVMetadataKey(rawValue: "id3MetadataKeyFileOwner")
  public static let id3MetadataKeyLeadPerformer = AVMetadataKey(rawValue: "id3MetadataKeyLeadPerformer")
  public static let id3MetadataKeyBand = AVMetadataKey(rawValue: "id3MetadataKeyBand")
  public static let id3MetadataKeyConductor = AVMetadataKey(rawValue: "id3MetadataKeyConductor")
  public static let id3MetadataKeyModifiedBy = AVMetadataKey(rawValue: "id3MetadataKeyModifiedBy")
  public static let id3MetadataKeyPartOfASet = AVMetadataKey(rawValue: "id3MetadataKeyPartOfASet")
  public static let id3MetadataKeyProducedNotice = AVMetadataKey(rawValue: "id3MetadataKeyProducedNotice")
  public static let id3MetadataKeyPublisher = AVMetadataKey(rawValue: "id3MetadataKeyPublisher")
  public static let id3MetadataKeyTrackNumber = AVMetadataKey(rawValue: "id3MetadataKeyTrackNumber")
  public static let id3MetadataKeyRecordingDates = AVMetadataKey(rawValue: "id3MetadataKeyRecordingDates")
  public static let id3MetadataKeyInternetRadioStationName = AVMetadataKey(rawValue: "id3MetadataKeyInternetRadioStationName")
  public static let id3MetadataKeyInternetRadioStationOwner = AVMetadataKey(rawValue: "id3MetadataKeyInternetRadioStationOwner")
  public static let id3MetadataKeySize = AVMetadataKey(rawValue: "id3MetadataKeySize")
  public static let id3MetadataKeyAlbumSortOrder = AVMetadataKey(rawValue: "id3MetadataKeyAlbumSortOrder")
  public static let id3MetadataKeyPerformerSortOrder = AVMetadataKey(rawValue: "id3MetadataKeyPerformerSortOrder")
  public static let id3MetadataKeyTitleSortOrder = AVMetadataKey(rawValue: "id3MetadataKeyTitleSortOrder")
  public static let id3MetadataKeyInternationalStandardRecordingCode = AVMetadataKey(rawValue: "id3MetadataKeyInternationalStandardRecordingCode")
  public static let id3MetadataKeyEncodedWith = AVMetadataKey(rawValue: "id3MetadataKeyEncodedWith")
  public static let id3MetadataKeySetSubtitle = AVMetadataKey(rawValue: "id3MetadataKeySetSubtitle")
  public static let id3MetadataKeyYear = AVMetadataKey(rawValue: "id3MetadataKeyYear")
  public static let id3MetadataKeyUserText = AVMetadataKey(rawValue: "id3MetadataKeyUserText")
  public static let id3MetadataKeyUniqueFileIdentifier = AVMetadataKey(rawValue: "id3MetadataKeyUniqueFileIdentifier")
  public static let id3MetadataKeyTermsOfUse = AVMetadataKey(rawValue: "id3MetadataKeyTermsOfUse")
  public static let id3MetadataKeyUnsynchronizedLyric = AVMetadataKey(rawValue: "id3MetadataKeyUnsynchronizedLyric")
  public static let id3MetadataKeyCommercialInformation = AVMetadataKey(rawValue: "id3MetadataKeyCommercialInformation")
  public static let id3MetadataKeyCopyrightInformation = AVMetadataKey(rawValue: "id3MetadataKeyCopyrightInformation")
  public static let id3MetadataKeyOfficialAudioFileWebpage = AVMetadataKey(rawValue: "id3MetadataKeyOfficialAudioFileWebpage")
  public static let id3MetadataKeyOfficialArtistWebpage = AVMetadataKey(rawValue: "id3MetadataKeyOfficialArtistWebpage")
  public static let id3MetadataKeyOfficialAudioSourceWebpage = AVMetadataKey(rawValue: "id3MetadataKeyOfficialAudioSourceWebpage")
  public static let id3MetadataKeyOfficialInternetRadioStationHomepage = AVMetadataKey(rawValue: "id3MetadataKeyOfficialInternetRadioStationHomepage")
  public static let id3MetadataKeyPayment = AVMetadataKey(rawValue: "id3MetadataKeyPayment")
  public static let id3MetadataKeyOfficialPublisherWebpage = AVMetadataKey(rawValue: "id3MetadataKeyOfficialPublisherWebpage")
  public static let id3MetadataKeyUserURL = AVMetadataKey(rawValue: "id3MetadataKeyUserURL")
  public static let icyMetadataKeyStreamTitle = AVMetadataKey(rawValue: "icyMetadataKeyStreamTitle")
  public static let icyMetadataKeyStreamURL = AVMetadataKey(rawValue: "icyMetadataKeyStreamURL")
}

public struct AVMetadataKeySpace: RawRepresentable, Hashable, Sendable, ExpressibleByStringLiteral {
  public let rawValue: String
  public init(rawValue: String) { self.rawValue = rawValue }
  public init(stringLiteral value: String) { self.init(rawValue: value) }
  public static let common = AVMetadataKeySpace(rawValue: "common")
  public static let quickTimeUserData = AVMetadataKeySpace(rawValue: "quickTimeUserData")
  public static let isoUserData = AVMetadataKeySpace(rawValue: "isoUserData")
  public static let quickTimeMetadata = AVMetadataKeySpace(rawValue: "quickTimeMetadata")
  public static let iTunes = AVMetadataKeySpace(rawValue: "iTunes")
  public static let id3 = AVMetadataKeySpace(rawValue: "id3")
  public static let icy = AVMetadataKeySpace(rawValue: "icy")
  public static let hlsDateRange = AVMetadataKeySpace(rawValue: "hlsDateRange")
  public static let audioFile = AVMetadataKeySpace(rawValue: "audioFile")
}

open class AVMetadataMachineReadableCodeObject: AVMetadataObject, @unchecked Sendable {
  public override init() { super.init() }
  public var corners: [CGPoint] { [] }
  public var stringValue: String? { nil }
  public var descriptor: CIBarcodeDescriptor? { nil }
}

open class AVMetadataObject: NSObject, @unchecked Sendable {
  public override init() { super.init() }
  public struct ObjectType: RawRepresentable, Hashable, Sendable, ExpressibleByStringLiteral {
    public let rawValue: String
    public init(rawValue: String) { self.rawValue = rawValue }
    public init(stringLiteral value: String) { self.init(rawValue: value) }
    public static let humanBody = ObjectType(rawValue: "humanBody")
    public static let humanFullBody = ObjectType(rawValue: "humanFullBody")
    public static let catHead = ObjectType(rawValue: "catHead")
    public static let catBody = ObjectType(rawValue: "catBody")
    public static let dogHead = ObjectType(rawValue: "dogHead")
    public static let dogBody = ObjectType(rawValue: "dogBody")
    public static let salientObject = ObjectType(rawValue: "salientObject")
    public static let face = ObjectType(rawValue: "face")
    public static let upce = ObjectType(rawValue: "upce")
    public static let code39 = ObjectType(rawValue: "code39")
    public static let code39Mod43 = ObjectType(rawValue: "code39Mod43")
    public static let ean13 = ObjectType(rawValue: "ean13")
    public static let ean8 = ObjectType(rawValue: "ean8")
    public static let code93 = ObjectType(rawValue: "code93")
    public static let code128 = ObjectType(rawValue: "code128")
    public static let pdf417 = ObjectType(rawValue: "pdf417")
    public static let qr = ObjectType(rawValue: "qr")
    public static let aztec = ObjectType(rawValue: "aztec")
    public static let interleaved2of5 = ObjectType(rawValue: "interleaved2of5")
    public static let itf14 = ObjectType(rawValue: "itf14")
    public static let dataMatrix = ObjectType(rawValue: "dataMatrix")
    public static let codabar = ObjectType(rawValue: "codabar")
    public static let gs1DataBar = ObjectType(rawValue: "gs1DataBar")
    public static let gs1DataBarExpanded = ObjectType(rawValue: "gs1DataBarExpanded")
    public static let gs1DataBarLimited = ObjectType(rawValue: "gs1DataBarLimited")
    public static let microQR = ObjectType(rawValue: "microQR")
    public static let microPDF417 = ObjectType(rawValue: "microPDF417")
  }
  public var time: CMTime { .zero }
  public var duration: CMTime { .zero }
  public var bounds: CGRect { .zero }
  public var type: AVMetadataObject.ObjectType { AVMetadataObject.ObjectType(rawValue: "") }
  public var groupID: Int { 0 }
  public var objectID: Int { 0 }
  public var cinematicVideoFocusMode: AVCaptureDevice.CinematicVideoFocusMode { AVCaptureDevice.CinematicVideoFocusMode(rawValue: 0)! }
  public var isFixedFocus: Bool { false }
}

open class AVMetadataSalientObject: AVMetadataObject, @unchecked Sendable {
  public override init() { super.init() }
}
