import Foundation
import Network

private func expect(_ condition: Bool, _ message: String) {
    precondition(condition, message)
}

func testCStructRawValueInitializers() {
    expect(nw_ws_opcode_t(rawValue: 1).rawValue == 1, "ws opcode")
    expect(nw_ws_opcode_t(2).rawValue == 2, "ws opcode init")
    expect(nw_ip_version_t(rawValue: 1).rawValue == 1, "ip version")
    expect(nw_ip_version_t(2).rawValue == 2, "ip version init")
    expect(nw_ws_version_t(rawValue: 1).rawValue == 1, "ws version")
    expect(nw_ws_version_t(0).rawValue == 0, "ws version init")
    expect(nw_ip_ecn_flag_t(rawValue: 3).rawValue == 3, "ecn")
    expect(nw_ip_ecn_flag_t(1).rawValue == 1, "ecn init")
    expect(nw_path_status_t(rawValue: 1).rawValue == 1, "path status")
    expect(nw_path_status_t(2).rawValue == 2, "path status init")
    expect(nw_error_domain_t(rawValue: 1).rawValue == 1, "error domain")
    expect(nw_error_domain_t(3).rawValue == 3, "error domain init")
    expect(nw_link_quality_t(rawValue: 20).rawValue == 20, "link quality")
    expect(nw_link_quality_t(10).rawValue == 10, "link quality init")
    expect(nw_browser_state_t(rawValue: 1).rawValue == 1, "browser state")
    expect(nw_browser_state_t(2).rawValue == 2, "browser state init")
    expect(nw_endpoint_type_t(rawValue: 2).rawValue == 2, "endpoint type")
    expect(nw_endpoint_type_t(4).rawValue == 4, "endpoint type init")
    expect(nw_service_class_t(rawValue: 1).rawValue == 1, "service class")
    expect(nw_service_class_t(5).rawValue == 5, "service class init")
    expect(nw_ws_close_code_t(rawValue: 1000).rawValue == 1000, "ws close")
    expect(nw_ws_close_code_t(1001).rawValue == 1001, "ws close init")
    expect(nw_interface_type_t(rawValue: 4).rawValue == 4, "interface type")
    expect(nw_interface_type_t(1).rawValue == 1, "interface type init")
    expect(nw_listener_state_t(rawValue: 2).rawValue == 2, "listener state")
    expect(nw_listener_state_t(3).rawValue == 3, "listener state init")
    expect(nw_connection_state_t(rawValue: 3).rawValue == 3, "connection state")
    expect(nw_connection_state_t(4).rawValue == 4, "connection state init")
    expect(nw_quic_stream_type_t(rawValue: 1).rawValue == 1, "quic stream")
    expect(nw_quic_stream_type_t(2).rawValue == 2, "quic stream init")
    expect(nw_multipath_service_t(rawValue: 1).rawValue == 1, "multipath service")
    expect(nw_multipath_service_t(0).rawValue == 0, "multipath service init")
    expect(nw_multipath_version_t(rawValue: 0).rawValue == 0, "multipath version")
    expect(nw_multipath_version_t(1).rawValue == 1, "multipath version init")
    expect(nw_ws_response_status_t(rawValue: 1).rawValue == 1, "ws response")
    expect(nw_ws_response_status_t(2).rawValue == 2, "ws response init")
    expect(nw_framer_start_result_t(rawValue: 1).rawValue == 1, "framer start")
    expect(nw_framer_start_result_t(2).rawValue == 2, "framer start init")
    expect(nw_txt_record_find_key_t(rawValue: 1).rawValue == 1, "txt find")
    expect(nw_txt_record_find_key_t(4).rawValue == 4, "txt find init")
    expect(nw_interface_radio_type_t(rawValue: 4).rawValue == 4, "radio")
    expect(nw_interface_radio_type_t(6).rawValue == 6, "radio init")
    expect(nw_connection_group_state_t(rawValue: 2).rawValue == 2, "group state")
    expect(nw_connection_group_state_t(3).rawValue == 3, "group state init")
    expect(nw_path_unsatisfied_reason_t(rawValue: 0).rawValue == 0, "unsatisfied")
    expect(nw_path_unsatisfied_reason_t(1).rawValue == 1, "unsatisfied init")
    expect(nw_report_resolution_source_t(rawValue: 1).rawValue == 1, "resolution source")
    expect(nw_report_resolution_source_t(2).rawValue == 2, "resolution source init")
    expect(nw_data_transfer_report_state_t(rawValue: 1).rawValue == 1, "dtr state")
    expect(nw_data_transfer_report_state_t(2).rawValue == 2, "dtr state init")
    expect(nw_report_resolution_protocol_t(rawValue: 2).rawValue == 2, "resolution proto")
    expect(nw_report_resolution_protocol_t(1).rawValue == 1, "resolution proto init")
    expect(nw_ip_local_address_preference_t(rawValue: 1).rawValue == 1, "ip preference")
    expect(nw_ip_local_address_preference_t(2).rawValue == 2, "ip preference init")
    expect(nw_parameters_expired_dns_behavior_t(rawValue: 1).rawValue == 1, "expired dns")
    expect(nw_parameters_expired_dns_behavior_t(2).rawValue == 2, "expired dns init")
    expect(nw_parameters_attribution_t(rawValue: 1)?.rawValue == 1, "attribution")
}
