// swift-tools-version:5.9
// Generated by Tools/ingest/objc_pods_package.py — do not edit by hand.
// Objective-C CocoaPods at their Podfile.lock versions, as Clang targets
// built against OpenUIKit (route b). Pods/ is the pods' own source.
import PackageDescription
import Foundation

let root = URL(fileURLWithPath: #filePath).deletingLastPathComponent().path
let openUIKit: [Target.Dependency] = [
    .product(name: "OpenUIKit", package: "OpenUIKit"),
    .product(name: "OpenUIKitObjCSupport", package: "OpenUIKit"),
    .product(name: "OpenUIKitObjCBridge", package: "OpenUIKit"),
    .product(name: "OpenUIKitObjCClasses", package: "OpenUIKit"),
]
func podFlags(arc: Bool, headers: [String]) -> [CSetting] {
    [.unsafeFlags([arc ? "-fobjc-arc" : "-fno-objc-arc",
                   "-include", root + "/Support/Pod-prefix.pch", "-I", root + "/Support",
                   "-DSWIFT_CLASS(SWIFT_NAME)=SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA",
                   "-DSWIFT_CLASS_NAMED(SWIFT_NAME)=SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA",
                  ] + headers.flatMap { ["-I", root + "/Targets/" + $0] })]
}

let package = Package(
    name: "EidolonPods",
    platforms: [.macOS(.v11), .iOS("26.0")],
    products: [
        .library(name: "ARCollectionViewMasonryLayout", targets: ["ARCollectionViewMasonryLayout"]),
        .library(name: "ARTiledImageView", targets: ["ARTiledImageView"]),
        .library(name: "Artsy_UIFonts", targets: ["Artsy_UIFonts"]),
        .library(name: "Artsy_UIButtons", targets: ["Artsy_UIButtons"]),
        .library(name: "Artsy_UIColors", targets: ["Artsy_UIColors"]),
        .library(name: "Artsy_UILabels", targets: ["Artsy_UILabels"]),
        .library(name: "DZNWebViewController", targets: ["DZNWebViewController"]),
        .library(name: "ECPhoneNumberFormatter", targets: ["ECPhoneNumberFormatter"]),
        .library(name: "FLKAutoLayout", targets: ["FLKAutoLayout"]),
        .library(name: "ISO8601DateFormatter", targets: ["ISO8601DateFormatter"]),
        .library(name: "NJKWebViewProgress", targets: ["NJKWebViewProgress"]),
        .library(name: "ORStackView", targets: ["ORStackView"]),
        .library(name: "SDWebImage", targets: ["SDWebImage"]),
        .library(name: "SVProgressHUD", targets: ["SVProgressHUD"]),
        .library(name: "UIImageViewAligned", targets: ["UIImageViewAligned"]),
        .library(name: "UIView_BooleanAnimations", targets: ["UIView_BooleanAnimations"]),
        .library(name: "XNGMarkdownParser", targets: ["XNGMarkdownParser"]),
    ],
    dependencies: [
        .package(name: "OpenUIKit", path: "../.."),
    ],
    targets: [
        .target(
            name: "PodsUIKitUmbrella",
            path: "Targets/PodsUIKitUmbrella",
            publicHeadersPath: "include"
        ),
        .target(
            name: "ARCollectionViewMasonryLayout",
            dependencies: openUIKit + ["PodsUIKitUmbrella"],
            path: "Targets/ARCollectionViewMasonryLayout",
            publicHeadersPath: "include",
            cSettings: podFlags(arc: true, headers: [
                "ARCollectionViewMasonryLayout/include/ARCollectionViewMasonryLayout",
            ])
        ),
        .target(
            name: "ARTiledImageView",
            dependencies: openUIKit + ["PodsUIKitUmbrella", "SDWebImage"],
            path: "Targets/ARTiledImageView",
            publicHeadersPath: "include",
            cSettings: podFlags(arc: true, headers: [
                "ARTiledImageView/include/ARTiledImageView",
                "SDWebImage/include/SDWebImage",
            ]),
            linkerSettings: [.linkedFramework("CoreGraphics")]
        ),
        .target(
            name: "Artsy_UIFonts",
            dependencies: openUIKit + ["PodsUIKitUmbrella"],
            path: "Targets/Artsy_UIFonts",
            publicHeadersPath: "include",
            cSettings: podFlags(arc: true, headers: [
                "Artsy_UIFonts/include/Artsy_UIFonts",
            ]),
            linkerSettings: [.linkedFramework("CoreText")]
        ),
        .target(
            name: "Artsy_UIButtons",
            dependencies: openUIKit + ["PodsUIKitUmbrella", "Artsy_UIColors", "Artsy_UIFonts", "UIView_BooleanAnimations"],
            path: "Targets/Artsy_UIButtons",
            publicHeadersPath: "include",
            cSettings: podFlags(arc: true, headers: [
                "Artsy_UIButtons/include/Artsy_UIButtons",
                "Artsy_UIColors/include/Artsy_UIColors",
                "Artsy_UIFonts/include/Artsy_UIFonts",
                "UIView_BooleanAnimations/include/UIView_BooleanAnimations",
            ])
        ),
        .target(
            name: "Artsy_UIColors",
            dependencies: openUIKit + ["PodsUIKitUmbrella"],
            path: "Targets/Artsy_UIColors",
            publicHeadersPath: "include",
            cSettings: podFlags(arc: true, headers: [
                "Artsy_UIColors/include/Artsy_UIColors",
            ])
        ),
        .target(
            name: "Artsy_UILabels",
            dependencies: openUIKit + ["PodsUIKitUmbrella", "Artsy_UIColors", "Artsy_UIFonts"],
            path: "Targets/Artsy_UILabels",
            publicHeadersPath: "include",
            cSettings: podFlags(arc: true, headers: [
                "Artsy_UILabels/include/Artsy_UILabels",
                "Artsy_UIColors/include/Artsy_UIColors",
                "Artsy_UIFonts/include/Artsy_UIFonts",
            ])
        ),
        .target(
            name: "DZNWebViewController",
            dependencies: openUIKit + ["PodsUIKitUmbrella", "NJKWebViewProgress"],
            path: "Targets/DZNWebViewController",
            publicHeadersPath: "include",
            cSettings: podFlags(arc: true, headers: [
                "DZNWebViewController/include/DZNWebViewController",
                "NJKWebViewProgress/include/NJKWebViewProgress",
            ])
        ),
        .target(
            name: "ECPhoneNumberFormatter",
            dependencies: openUIKit + ["PodsUIKitUmbrella"],
            path: "Targets/ECPhoneNumberFormatter",
            publicHeadersPath: "include",
            cSettings: podFlags(arc: false, headers: [
                "ECPhoneNumberFormatter/include/ECPhoneNumberFormatter",
            ])
        ),
        .target(
            name: "FLKAutoLayout",
            dependencies: openUIKit + ["PodsUIKitUmbrella"],
            path: "Targets/FLKAutoLayout",
            publicHeadersPath: "include",
            cSettings: podFlags(arc: true, headers: [
                "FLKAutoLayout/include/FLKAutoLayout",
            ])
        ),
        .target(
            name: "ISO8601DateFormatter",
            dependencies: openUIKit + ["PodsUIKitUmbrella"],
            path: "Targets/ISO8601DateFormatter",
            publicHeadersPath: "include",
            cSettings: podFlags(arc: false, headers: [
                "ISO8601DateFormatter/include/ISO8601DateFormatter",
            ])
        ),
        .target(
            name: "NJKWebViewProgress",
            dependencies: openUIKit + ["PodsUIKitUmbrella"],
            path: "Targets/NJKWebViewProgress",
            publicHeadersPath: "include",
            cSettings: podFlags(arc: true, headers: [
                "NJKWebViewProgress/include/NJKWebViewProgress",
            ])
        ),
        .target(
            name: "ORStackView",
            dependencies: openUIKit + ["PodsUIKitUmbrella", "FLKAutoLayout"],
            path: "Targets/ORStackView",
            publicHeadersPath: "include",
            cSettings: podFlags(arc: true, headers: [
                "ORStackView/include/ORStackView",
                "FLKAutoLayout/include/FLKAutoLayout",
            ])
        ),
        .target(
            name: "SDWebImage",
            dependencies: openUIKit + ["PodsUIKitUmbrella"],
            path: "Targets/SDWebImage",
            publicHeadersPath: "include",
            cSettings: podFlags(arc: true, headers: [
                "SDWebImage/include/SDWebImage",
            ]),
            linkerSettings: [.linkedFramework("ImageIO")]
        ),
        .target(
            name: "SVProgressHUD",
            dependencies: openUIKit + ["PodsUIKitUmbrella"],
            path: "Targets/SVProgressHUD",
            publicHeadersPath: "include",
            cSettings: podFlags(arc: true, headers: [
                "SVProgressHUD/include/SVProgressHUD",
            ]),
            linkerSettings: [.linkedFramework("QuartzCore")]
        ),
        .target(
            name: "UIImageViewAligned",
            dependencies: openUIKit + ["PodsUIKitUmbrella"],
            path: "Targets/UIImageViewAligned",
            publicHeadersPath: "include",
            cSettings: podFlags(arc: true, headers: [
                "UIImageViewAligned/include/UIImageViewAligned",
            ])
        ),
        .target(
            name: "UIView_BooleanAnimations",
            dependencies: openUIKit + ["PodsUIKitUmbrella"],
            path: "Targets/UIView_BooleanAnimations",
            publicHeadersPath: "include",
            cSettings: podFlags(arc: true, headers: [
                "UIView_BooleanAnimations/include/UIView_BooleanAnimations",
            ])
        ),
        .target(
            name: "XNGMarkdownParser",
            dependencies: openUIKit + ["PodsUIKitUmbrella"],
            path: "Targets/XNGMarkdownParser",
            publicHeadersPath: "include",
            cSettings: podFlags(arc: true, headers: [
                "XNGMarkdownParser/include/XNGMarkdownParser",
            ])
        ),
    ]
)
