import Foundation
@_spi(OpenUIKitHost) import MediaPlayer

func testEnumRawValues() {
    precondition(MPChangeLanguageOptionSetting.none.rawValue == 0)
    precondition(MPChangeLanguageOptionSetting.nowPlayingItemOnly.rawValue == 1)
    precondition(MPChangeLanguageOptionSetting.permanent.rawValue == 2)
    precondition(MPChangeLanguageOptionSetting.none != .permanent)
    _ = MPChangeLanguageOptionSetting.none.hashValue
    var languageHasher = Hasher()
    MPChangeLanguageOptionSetting.permanent.hash(into: &languageHasher)
    _ = languageHasher.finalize()

    precondition(MPMediaGrouping.title.rawValue == 0)
    precondition(MPMediaGrouping.album.rawValue == 1)
    precondition(MPMediaGrouping.artist.rawValue == 2)
    precondition(MPMediaGrouping.albumArtist.rawValue == 3)
    precondition(MPMediaGrouping.composer.rawValue == 4)
    precondition(MPMediaGrouping.genre.rawValue == 5)
    precondition(MPMediaGrouping.playlist.rawValue == 6)
    precondition(MPMediaGrouping.podcastTitle.rawValue == 7)
    precondition(MPMediaGrouping.title != .album)
    _ = MPMediaGrouping.album.hashValue
    var groupingHasher = Hasher()
    MPMediaGrouping.genre.hash(into: &groupingHasher)
    _ = groupingHasher.finalize()

    precondition(MPMediaLibraryAuthorizationStatus.notDetermined.rawValue == 0)
    precondition(MPMediaLibraryAuthorizationStatus.denied.rawValue == 1)
    precondition(MPMediaLibraryAuthorizationStatus.restricted.rawValue == 2)
    precondition(MPMediaLibraryAuthorizationStatus.authorized.rawValue == 3)
    precondition(MPMediaLibraryAuthorizationStatus.denied != .authorized)
    _ = MPMediaLibraryAuthorizationStatus.denied.hashValue
    var authHasher = Hasher()
    MPMediaLibraryAuthorizationStatus.authorized.hash(into: &authHasher)
    _ = authHasher.finalize()

    precondition(MPMediaPredicateComparison.equalTo.rawValue == 0)
    precondition(MPMediaPredicateComparison.contains.rawValue == 1)
    precondition(MPMediaPredicateComparison.equalTo != .contains)
    _ = MPMediaPredicateComparison.equalTo.hashValue
    var predicateHasher = Hasher()
    MPMediaPredicateComparison.contains.hash(into: &predicateHasher)
    _ = predicateHasher.finalize()

    precondition(MPMovieControlStyle.none.rawValue == 0)
    precondition(MPMovieControlStyle.embedded.rawValue == 1)
    precondition(MPMovieControlStyle.fullscreen.rawValue == 2)
    precondition(MPMovieControlStyle.none != .fullscreen)
    _ = MPMovieControlStyle.none.hashValue
    var controlHasher = Hasher()
    MPMovieControlStyle.embedded.hash(into: &controlHasher)
    _ = controlHasher.finalize()

    precondition(MPMovieFinishReason.playbackEnded.rawValue == 0)
    precondition(MPMovieFinishReason.playbackError.rawValue == 1)
    precondition(MPMovieFinishReason.userExited.rawValue == 2)
    precondition(MPMovieFinishReason.playbackEnded != .userExited)
    _ = MPMovieFinishReason.playbackEnded.hashValue
    var finishHasher = Hasher()
    MPMovieFinishReason.playbackError.hash(into: &finishHasher)
    _ = finishHasher.finalize()

    precondition(MPMoviePlaybackState.stopped.rawValue == 0)
    precondition(MPMoviePlaybackState.playing.rawValue == 1)
    precondition(MPMoviePlaybackState.paused.rawValue == 2)
    precondition(MPMoviePlaybackState.interrupted.rawValue == 3)
    precondition(MPMoviePlaybackState.seekingForward.rawValue == 4)
    precondition(MPMoviePlaybackState.seekingBackward.rawValue == 5)
    precondition(MPMoviePlaybackState.stopped != .playing)
    _ = MPMoviePlaybackState.stopped.hashValue
    var moviePlaybackHasher = Hasher()
    MPMoviePlaybackState.paused.hash(into: &moviePlaybackHasher)
    _ = moviePlaybackHasher.finalize()

    precondition(MPMovieRepeatMode.none.rawValue == 0)
    precondition(MPMovieRepeatMode.one.rawValue == 1)
    precondition(MPMovieRepeatMode.none != .one)
    _ = MPMovieRepeatMode.none.hashValue
    var movieRepeatHasher = Hasher()
    MPMovieRepeatMode.one.hash(into: &movieRepeatHasher)
    _ = movieRepeatHasher.finalize()

    precondition(MPMovieScalingMode.none.rawValue == 0)
    precondition(MPMovieScalingMode.aspectFit.rawValue == 1)
    precondition(MPMovieScalingMode.aspectFill.rawValue == 2)
    precondition(MPMovieScalingMode.fill.rawValue == 3)
    precondition(MPMovieScalingMode.none != .fill)
    _ = MPMovieScalingMode.none.hashValue
    var scalingHasher = Hasher()
    MPMovieScalingMode.fill.hash(into: &scalingHasher)
    _ = scalingHasher.finalize()

    precondition(MPMovieSourceType.unknown.rawValue == 0)
    precondition(MPMovieSourceType.file.rawValue == 1)
    precondition(MPMovieSourceType.streaming.rawValue == 2)
    precondition(MPMovieSourceType.unknown != .file)
    _ = MPMovieSourceType.unknown.hashValue
    var sourceHasher = Hasher()
    MPMovieSourceType.file.hash(into: &sourceHasher)
    _ = sourceHasher.finalize()

    precondition(MPMovieTimeOption.nearestKeyFrame.rawValue == 0)
    precondition(MPMovieTimeOption.exact.rawValue == 1)
    precondition(MPMovieTimeOption.exact != .nearestKeyFrame)
    _ = MPMovieTimeOption.exact.hashValue
    var timeHasher = Hasher()
    MPMovieTimeOption.nearestKeyFrame.hash(into: &timeHasher)
    _ = timeHasher.finalize()

    precondition(MPMusicPlaybackState.stopped.rawValue == 0)
    precondition(MPMusicPlaybackState.playing.rawValue == 1)
    precondition(MPMusicPlaybackState.paused.rawValue == 2)
    precondition(MPMusicPlaybackState.interrupted.rawValue == 3)
    precondition(MPMusicPlaybackState.seekingForward.rawValue == 4)
    precondition(MPMusicPlaybackState.seekingBackward.rawValue == 5)
    precondition(MPMusicPlaybackState.stopped != .playing)
    _ = MPMusicPlaybackState.stopped.hashValue
    var musicPlaybackHasher = Hasher()
    MPMusicPlaybackState.playing.hash(into: &musicPlaybackHasher)
    _ = musicPlaybackHasher.finalize()
    precondition(Set([MPMusicPlaybackState.stopped, .playing]).count == 2)

    precondition(MPMusicRepeatMode.default.rawValue == 0)
    precondition(MPMusicRepeatMode.none.rawValue == 1)
    precondition(MPMusicRepeatMode.one.rawValue == 2)
    precondition(MPMusicRepeatMode.all.rawValue == 3)
    precondition(MPMusicRepeatMode.none != .all)
    _ = MPMusicRepeatMode.none.hashValue
    var musicRepeatHasher = Hasher()
    MPMusicRepeatMode.all.hash(into: &musicRepeatHasher)
    _ = musicRepeatHasher.finalize()

    precondition(MPMusicShuffleMode.default.rawValue == 0)
    precondition(MPMusicShuffleMode.off.rawValue == 1)
    precondition(MPMusicShuffleMode.songs.rawValue == 2)
    precondition(MPMusicShuffleMode.albums.rawValue == 3)
    precondition(MPMusicShuffleMode.off != .songs)
    _ = MPMusicShuffleMode.off.hashValue
    var shuffleHasher = Hasher()
    MPMusicShuffleMode.songs.hash(into: &shuffleHasher)
    _ = shuffleHasher.finalize()

    precondition(MPNowPlayingInfoLanguageOptionType.audible.rawValue == 0)
    precondition(MPNowPlayingInfoLanguageOptionType.legible.rawValue == 1)
    precondition(MPNowPlayingInfoLanguageOptionType.audible != .legible)
    _ = MPNowPlayingInfoLanguageOptionType.audible.hashValue
    var optionTypeHasher = Hasher()
    MPNowPlayingInfoLanguageOptionType.legible.hash(into: &optionTypeHasher)
    _ = optionTypeHasher.finalize()

    precondition(MPNowPlayingInfoMediaType.none.rawValue == 0)
    precondition(MPNowPlayingInfoMediaType.audio.rawValue == 1)
    precondition(MPNowPlayingInfoMediaType.video.rawValue == 2)
    precondition(MPNowPlayingInfoMediaType.audio != .video)
    _ = MPNowPlayingInfoMediaType.audio.hashValue
    var mediaTypeHasher = Hasher()
    MPNowPlayingInfoMediaType.video.hash(into: &mediaTypeHasher)
    _ = mediaTypeHasher.finalize()

    precondition(MPNowPlayingPlaybackState.unknown.rawValue == 0)
    precondition(MPNowPlayingPlaybackState.playing.rawValue == 1)
    precondition(MPNowPlayingPlaybackState.paused.rawValue == 2)
    precondition(MPNowPlayingPlaybackState.stopped.rawValue == 3)
    precondition(MPNowPlayingPlaybackState.interrupted.rawValue == 4)
    precondition(MPNowPlayingPlaybackState.stopped != .playing)
    _ = MPNowPlayingPlaybackState.stopped.hashValue
    var nowPlayingHasher = Hasher()
    MPNowPlayingPlaybackState.paused.hash(into: &nowPlayingHasher)
    _ = nowPlayingHasher.finalize()

    precondition(MPRemoteCommandHandlerStatus.success.rawValue == 0)
    precondition(MPRemoteCommandHandlerStatus.noSuchContent.rawValue == 100)
    precondition(MPRemoteCommandHandlerStatus.noActionableNowPlayingItem.rawValue == 110)
    precondition(MPRemoteCommandHandlerStatus.deviceNotFound.rawValue == 120)
    precondition(MPRemoteCommandHandlerStatus.commandFailed.rawValue == 200)
    precondition(MPRemoteCommandHandlerStatus.success != .commandFailed)
    _ = MPRemoteCommandHandlerStatus.success.hashValue
    var handlerHasher = Hasher()
    MPRemoteCommandHandlerStatus.commandFailed.hash(into: &handlerHasher)
    _ = handlerHasher.finalize()

    precondition(MPRepeatType.off.rawValue == 0)
    precondition(MPRepeatType.one.rawValue == 1)
    precondition(MPRepeatType.all.rawValue == 2)
    precondition(MPRepeatType.off != .all)
    _ = MPRepeatType.off.hashValue
    var repeatHasher = Hasher()
    MPRepeatType.all.hash(into: &repeatHasher)
    _ = repeatHasher.finalize()

    precondition(MPSeekCommandEventType.beginSeeking.rawValue == 0)
    precondition(MPSeekCommandEventType.endSeeking.rawValue == 1)
    precondition(MPSeekCommandEventType.beginSeeking != .endSeeking)
    _ = MPSeekCommandEventType.beginSeeking.hashValue
    var seekHasher = Hasher()
    MPSeekCommandEventType.endSeeking.hash(into: &seekHasher)
    _ = seekHasher.finalize()

    precondition(MPShuffleType.off.rawValue == 0)
    precondition(MPShuffleType.items.rawValue == 1)
    precondition(MPShuffleType.collections.rawValue == 2)
    precondition(MPShuffleType.off != .items)
    _ = MPShuffleType.off.hashValue
    var shuffleTypeHasher = Hasher()
    MPShuffleType.items.hash(into: &shuffleTypeHasher)
    _ = shuffleTypeHasher.finalize()
}

func testOptionSetBits() {
    precondition(MPMediaType.music.rawValue == 1)
    precondition(MPMediaType.podcast.rawValue == 2)
    precondition(MPMediaType.audioBook.rawValue == 4)
    precondition(MPMediaType.audioITunesU.rawValue == 8)
    precondition(MPMediaType.anyAudio.rawValue == 255)
    precondition(MPMediaType.movie.rawValue == 256)
    precondition(MPMediaType.tvShow.rawValue == 512)
    precondition(MPMediaType.videoPodcast.rawValue == 1024)
    precondition(MPMediaType.musicVideo.rawValue == 2048)
    precondition(MPMediaType.videoITunesU.rawValue == 4096)
    precondition(MPMediaType.homeVideo.rawValue == 8192)
    precondition(MPMediaType.anyVideo.rawValue == 65280)
    precondition(MPMediaType.any.rawValue == ~UInt(0))
    precondition(MPMediaType.music.contains(.music))
    precondition(MPMediaType.anyAudio.contains(.podcast))
    precondition(!MPMediaType.music.contains(.movie))
    precondition(MPMediaType.music.union(.podcast).contains(.podcast))
    precondition(MPMediaType.music.intersection(.anyAudio) == .music)
    precondition(MPMediaType.music.isDisjoint(with: .movie))
    precondition(MPMediaType.anyAudio.isSuperset(of: .music))
    precondition(MPMediaType.music.isSubset(of: .anyAudio))
    precondition(MPMediaType.music.isStrictSubset(of: .anyAudio))
    precondition(MPMediaType.anyAudio.isStrictSuperset(of: .music))
    precondition(!MPMediaType.music.isEmpty)
    precondition(MPMediaType().isEmpty)
    precondition(MPMediaType.music != .movie)
    var types = MPMediaType.music
    _ = types.insert(.podcast)
    precondition(types.contains(.podcast))
    _ = types.remove(.podcast)
    _ = types.update(with: .audioBook)
    types.formUnion(.audioBook)
    types.formIntersection(.anyAudio)
    types.formSymmetricDifference(.music)
    types.subtract(.audioBook)
    _ = types.subtracting(.podcast)
    _ = types.symmetricDifference(.movie)
    let fromSeq = MPMediaType([.music, .podcast])
    precondition(fromSeq.contains(.music) && fromSeq.contains(.podcast))
    let lit: MPMediaType = [.music, .podcast]
    precondition(lit.contains(.podcast))
    _ = MPMediaType(rawValue: 1)

    precondition(MPMediaPlaylistAttribute.onTheGo.rawValue == 1)
    precondition(MPMediaPlaylistAttribute.smart.rawValue == 2)
    precondition(MPMediaPlaylistAttribute.genius.rawValue == 4)
    precondition(MPMediaPlaylistAttribute.smart.contains(.smart))
    precondition(MPMediaPlaylistAttribute.smart.union(.genius).contains(.genius))
    precondition(MPMediaPlaylistAttribute.smart.intersection(.genius).isEmpty)
    precondition(MPMediaPlaylistAttribute.smart.isDisjoint(with: .genius))
    precondition(MPMediaPlaylistAttribute([.smart, .genius]).isSuperset(of: .smart))
    precondition(MPMediaPlaylistAttribute.smart.isSubset(of: [.smart, .genius]))
    precondition(MPMediaPlaylistAttribute.smart.isStrictSubset(of: [.smart, .genius]))
    precondition(MPMediaPlaylistAttribute([.smart, .genius]).isStrictSuperset(of: .smart))
    precondition(MPMediaPlaylistAttribute().isEmpty)
    precondition(MPMediaPlaylistAttribute.smart != .genius)
    var playlist = MPMediaPlaylistAttribute.smart
    _ = playlist.insert(.genius)
    _ = playlist.remove(.genius)
    _ = playlist.update(with: .onTheGo)
    playlist.formUnion(.genius)
    playlist.formIntersection(.smart)
    playlist.formSymmetricDifference(.onTheGo)
    playlist.subtract(.smart)
    _ = playlist.subtracting(.genius)
    _ = playlist.symmetricDifference(.smart)
    _ = MPMediaPlaylistAttribute(rawValue: 1)

    precondition(MPMovieLoadState.playable.rawValue == 1)
    precondition(MPMovieLoadState.playthroughOK.rawValue == 2)
    precondition(MPMovieLoadState.stalled.rawValue == 4)
    precondition(MPMovieLoadState.playable.contains(.playable))
    precondition(MPMovieLoadState.playable.union(.stalled).contains(.stalled))
    precondition(MPMovieLoadState.playable.intersection(.stalled).isEmpty)
    precondition(MPMovieLoadState.playable.isDisjoint(with: .stalled))
    precondition(MPMovieLoadState([.playable, .stalled]).isSuperset(of: .playable))
    precondition(MPMovieLoadState.playable.isSubset(of: [.playable, .stalled]))
    precondition(MPMovieLoadState.playable.isStrictSubset(of: [.playable, .stalled]))
    precondition(MPMovieLoadState([.playable, .stalled]).isStrictSuperset(of: .playable))
    precondition(MPMovieLoadState().isEmpty)
    precondition(MPMovieLoadState.playable != .stalled)
    var load = MPMovieLoadState.playable
    _ = load.insert(.stalled)
    _ = load.remove(.stalled)
    _ = load.update(with: .playthroughOK)
    load.formUnion(.stalled)
    load.formIntersection(.playable)
    load.formSymmetricDifference(.playthroughOK)
    load.subtract(.playable)
    _ = load.subtracting(.stalled)
    _ = load.symmetricDifference(.playable)
    _ = MPMovieLoadState(rawValue: 1)

    precondition(MPMovieMediaTypeMask.video.rawValue == 1)
    precondition(MPMovieMediaTypeMask.audio.rawValue == 2)
    precondition(MPMovieMediaTypeMask.audio.contains(.audio))
    precondition(MPMovieMediaTypeMask.video.union(.audio).contains(.audio))
    precondition(MPMovieMediaTypeMask.video.intersection(.audio).isEmpty)
    precondition(MPMovieMediaTypeMask.video.isDisjoint(with: .audio))
    precondition(MPMovieMediaTypeMask([.video, .audio]).isSuperset(of: .video))
    precondition(MPMovieMediaTypeMask.video.isSubset(of: [.video, .audio]))
    precondition(MPMovieMediaTypeMask.video.isStrictSubset(of: [.video, .audio]))
    precondition(MPMovieMediaTypeMask([.video, .audio]).isStrictSuperset(of: .video))
    precondition(MPMovieMediaTypeMask().isEmpty)
    precondition(MPMovieMediaTypeMask.video != .audio)
    var mask = MPMovieMediaTypeMask.video
    _ = mask.insert(.audio)
    _ = mask.remove(.audio)
    _ = mask.update(with: .audio)
    mask.formUnion(.audio)
    mask.formIntersection(.video)
    mask.formSymmetricDifference(.audio)
    mask.subtract(.video)
    _ = mask.subtracting(.audio)
    _ = mask.symmetricDifference(.video)
    _ = MPMovieMediaTypeMask(rawValue: 1)
}
