import Foundation
import AVFAudio
@_spi(OpenUIKitHost) import AVFAudio
#if canImport(CoreAudioTypes)
import CoreAudioTypes
#endif
#if canImport(AudioToolbox)
import AudioToolbox
#endif

func testAVFAudioOptionSets() {
    var buffer = AVAudioPlayerNodeBufferOptions()
    precondition(buffer.isEmpty)
    _ = buffer.insert(.loops)
    precondition(buffer.contains(.loops))
    _ = buffer.insert(.interrupts)
    _ = buffer.insert(.interruptsAtLoop)
    precondition(buffer.contains(.interrupts) && buffer.contains(.interruptsAtLoop))
    precondition(buffer.isSuperset(of: .loops))
    precondition(!buffer.isDisjoint(with: .loops))
    precondition(buffer.isSubset(of: buffer))
    precondition(!buffer.isStrictSubset(of: buffer))
    precondition(!buffer.isStrictSuperset(of: buffer))
    let subtracted = buffer.subtracting(.loops)
    precondition(!subtracted.contains(.loops))
    buffer.subtract(.interrupts)
    _ = buffer.remove(.interruptsAtLoop)
    _ = buffer.update(with: .loops)
    buffer.formUnion(.interrupts)
    buffer.formIntersection(.loops)
    buffer.formSymmetricDifference(.interruptsAtLoop)
    let unioned = AVAudioPlayerNodeBufferOptions.loops.union(.interrupts)
    _ = unioned.intersection(.loops)
    _ = unioned.symmetricDifference(.interrupts)
    precondition(AVAudioPlayerNodeBufferOptions.loops != .interrupts)
    _ = AVAudioPlayerNodeBufferOptions(rawValue: 1)
    _ = AVAudioPlayerNodeBufferOptions([.loops])
    _ = AVAudioPlayerNodeBufferOptions()

    var category = AVAudioSession.CategoryOptions()
    _ = category.insert(.mixWithOthers)
    _ = category.insert(.duckOthers)
    _ = category.insert(.allowBluetooth)
    _ = category.insert(.defaultToSpeaker)
    _ = category.insert(.interruptSpokenAudioAndMixWithOthers)
    _ = category.insert(.allowBluetoothA2DP)
    _ = category.insert(.allowAirPlay)
    _ = category.insert(.overrideMutedMicrophoneInterruption)
    _ = category.insert(.allowBluetoothHFP)
    _ = category.insert(.bluetoothHighQualityRecording)
    precondition(category.contains(.mixWithOthers))
    _ = category.union(.duckOthers)
    _ = category.intersection(.mixWithOthers)
    _ = category.symmetricDifference(.allowAirPlay)
    _ = category.subtracting(.duckOthers)
    category.formUnion(.allowBluetooth)
    category.formIntersection(.mixWithOthers)
    category.formSymmetricDifference(.allowAirPlay)
    category.subtract(.duckOthers)
    _ = category.remove(.allowBluetooth)
    _ = category.update(with: .mixWithOthers)
    _ = category.isDisjoint(with: .allowAirPlay)
    _ = category.isSubset(of: category)
    _ = category.isSuperset(of: .mixWithOthers)
    _ = category.isStrictSubset(of: category)
    _ = category.isStrictSuperset(of: .mixWithOthers)
    _ = category.isEmpty
    precondition(AVAudioSession.CategoryOptions.mixWithOthers != .duckOthers)
    _ = AVAudioSession.CategoryOptions(rawValue: 1)
    _ = AVAudioSession.CategoryOptions([.mixWithOthers])

    var active = AVAudioSession.SetActiveOptions()
    _ = active.insert(.notifyOthersOnDeactivation)
    _ = active.union(.notifyOthersOnDeactivation)
    _ = active.intersection(.notifyOthersOnDeactivation)
    _ = active.symmetricDifference(.notifyOthersOnDeactivation)
    _ = active.subtracting(.notifyOthersOnDeactivation)
    active.formUnion(.notifyOthersOnDeactivation)
    active.formIntersection(.notifyOthersOnDeactivation)
    active.formSymmetricDifference(.notifyOthersOnDeactivation)
    active.subtract(.notifyOthersOnDeactivation)
    _ = active.remove(.notifyOthersOnDeactivation)
    _ = active.update(with: .notifyOthersOnDeactivation)
    _ = active.isDisjoint(with: .notifyOthersOnDeactivation)
    _ = active.isSubset(of: active)
    _ = active.isSuperset(of: [])
    _ = active.isStrictSubset(of: [.notifyOthersOnDeactivation])
    _ = active.isStrictSuperset(of: [])
    _ = active.isEmpty
    _ = AVAudioSession.SetActiveOptions(rawValue: 1)
    _ = AVAudioSession.SetActiveOptions([.notifyOthersOnDeactivation])
    _ = AVAudioSession.SetActiveOptions()
    precondition(AVAudioSession.SetActiveOptions.notifyOthersOnDeactivation != [])

    var interruption = AVAudioSession.InterruptionOptions()
    _ = interruption.insert(.shouldResume)
    _ = interruption.union(.shouldResume)
    _ = interruption.intersection(.shouldResume)
    _ = interruption.symmetricDifference(.shouldResume)
    _ = interruption.subtracting(.shouldResume)
    interruption.formUnion(.shouldResume)
    interruption.formIntersection(.shouldResume)
    interruption.formSymmetricDifference(.shouldResume)
    interruption.subtract(.shouldResume)
    _ = interruption.remove(.shouldResume)
    _ = interruption.update(with: .shouldResume)
    _ = interruption.isDisjoint(with: .shouldResume)
    _ = interruption.isSubset(of: interruption)
    _ = interruption.isSuperset(of: [])
    _ = interruption.isStrictSubset(of: [.shouldResume])
    _ = interruption.isStrictSuperset(of: [])
    _ = interruption.isEmpty
    _ = AVAudioSession.InterruptionOptions(rawValue: 1)
    _ = AVAudioSession.InterruptionOptions([.shouldResume])
    precondition(AVAudioSession.InterruptionOptions.shouldResume != [])

    var activation = AVAudioSessionActivationOptions()
    _ = activation.insert(AVAudioSessionActivationOptions(rawValue: 1))
    _ = activation.union([])
    _ = activation.intersection([])
    _ = activation.symmetricDifference([])
    _ = activation.subtracting([])
    activation.formUnion([])
    activation.formIntersection([])
    activation.formSymmetricDifference([])
    activation.subtract([])
    _ = activation.remove(AVAudioSessionActivationOptions(rawValue: 1))
    _ = activation.update(with: AVAudioSessionActivationOptions(rawValue: 1))
    _ = activation.isDisjoint(with: [])
    _ = activation.isSubset(of: activation)
    _ = activation.isSuperset(of: [])
    _ = activation.isStrictSubset(of: activation)
    _ = activation.isStrictSuperset(of: [])
    _ = activation.isEmpty
    _ = AVAudioSessionActivationOptions(rawValue: 0)
    _ = AVAudioSessionActivationOptions([])
    _ = AVAudioSessionActivationOptions()
    precondition(AVAudioSessionActivationOptions() != AVAudioSessionActivationOptions(rawValue: 1))

    var load = AVMusicSequenceLoadOptions()
    _ = load.insert(.smf_ChannelsToTracks)
    _ = load.union(.smf_ChannelsToTracks)
    _ = load.intersection(.smf_ChannelsToTracks)
    _ = load.symmetricDifference(.smf_ChannelsToTracks)
    _ = load.subtracting(.smf_ChannelsToTracks)
    load.formUnion(.smf_ChannelsToTracks)
    load.formIntersection(.smf_ChannelsToTracks)
    load.formSymmetricDifference(.smf_ChannelsToTracks)
    load.subtract(.smf_ChannelsToTracks)
    _ = load.remove(.smf_ChannelsToTracks)
    _ = load.update(with: .smf_ChannelsToTracks)
    _ = load.isDisjoint(with: .smf_ChannelsToTracks)
    _ = load.isSubset(of: load)
    _ = load.isSuperset(of: [])
    _ = load.isStrictSubset(of: [.smf_ChannelsToTracks])
    _ = load.isStrictSuperset(of: [])
    _ = load.isEmpty
    _ = AVMusicSequenceLoadOptions(rawValue: 1)
    _ = AVMusicSequenceLoadOptions([.smf_ChannelsToTracks])
    precondition(AVMusicSequenceLoadOptions.smf_ChannelsToTracks != [])

    var traits = AVSpeechSynthesisVoice.Traits()
    _ = traits.insert(.isNoveltyVoice)
    _ = traits.insert(.isPersonalVoice)
    _ = traits.union(.isNoveltyVoice)
    _ = traits.intersection(.isPersonalVoice)
    _ = traits.symmetricDifference(.isNoveltyVoice)
    _ = traits.subtracting(.isPersonalVoice)
    traits.formUnion(.isNoveltyVoice)
    traits.formIntersection(.isPersonalVoice)
    traits.formSymmetricDifference(.isNoveltyVoice)
    traits.subtract(.isPersonalVoice)
    _ = traits.remove(.isNoveltyVoice)
    _ = traits.update(with: .isPersonalVoice)
    _ = traits.isDisjoint(with: .isNoveltyVoice)
    _ = traits.isSubset(of: traits)
    _ = traits.isSuperset(of: [])
    _ = traits.isStrictSubset(of: traits)
    _ = traits.isStrictSuperset(of: [])
    _ = traits.isEmpty
    _ = AVSpeechSynthesisVoice.Traits(rawValue: 1)
    _ = AVSpeechSynthesisVoice.Traits([.isNoveltyVoice])
    precondition(AVSpeechSynthesisVoice.Traits.isNoveltyVoice != .isPersonalVoice)
}

