void objc_msgSend(void) {}
void objc_msgSendSuper2(void) {}
void objc_retain(void) {}
void objc_release(void) {}
void objc_autoreleaseReturnValue(void) {}
void objc_getProperty(void) {}
void objc_setProperty_nonatomic(void) {}
void objc_storeStrong(void) {}
void _objc_empty_cache(void) {}
void objc_opt_class(void) {}
void objc_opt_self(void) {}
void objc_alloc(void) {}
