#!/bin/bash
# build_ud_score_guest.sh -- build the #87 step 4 GUEST scoreboard binary.
#
#   scripts/build_ud_score_guest.sh
#
# Compiles tests/ud_score_guest.swift together with a GENERATED Swift file that
# embeds the Darwin golden byte-for-byte, then links it exactly the way
# link_ud_guest.sh links the smoke runner -- same objects, same .tbd-first
# library order, same freshness refusal.
#
# THE GOLDEN IS REGENERATED FROM THE COMMITTED FILE ON EVERY BUILD, never
# hand-carried. If the oracle re-emits it, the next build picks it up and its
# sha256 changes on the scoreboard's own header, so a board and the golden it
# was scored against can always be tied together after the fact.
set -euo pipefail

W=${W:-/work}
R=${R:-/repo}
SDK=${SDK:-$W/fe/sysroot}
LLD=${LLD_BIN:-/usr/lib/llvm-18/bin}
TRIPLE=${TRIPLE:-arm64-apple-macos13.0}
COMPILE_TRIPLE=${COMPILE_TRIPLE:-arm64-apple-macos15.0}
OUT=${OUT:-$W/bin/ud_score_guest}
GEN=${GEN:-$W/oracle/GuestGolden.swift}

# The generated file is produced on the HOST by scripts/stage_ud_oracle.sh --
# this container has no python. Refuse rather than compile without it: an
# absent golden would give an empty scoreboard, and an empty scoreboard scores
# 100%.
if [ ! -f "$GEN" ]; then
    echo "FATAL: the embedded golden is not staged at $GEN" >&2
    echo "  Run on the macOS host:  scripts/stage_ud_oracle.sh" >&2
    exit 2
fi
echo "==> golden: $(grep -m1 '// sha256:' "$GEN" || echo '(no sha line)')"
echo "            $(grep -m1 '// Rows:' "$GEN" || true)"

# The runner is TOP-LEVEL CODE, and in a whole-module build Swift allows that
# in exactly one file, named main.swift. Copying it under that name is the
# whole reason for this step -- compiled under its own name the error is
# "statements are not allowed at the top level", which reads like a problem
# with the code rather than with its filename.
BUILDDIR=$W/fe/score-src
rm -rf "$BUILDDIR"; mkdir -p "$BUILDDIR"
cp "$R/tests/ud_score_guest.swift" "$BUILDDIR/main.swift"
cp "$GEN" "$BUILDDIR/GuestGolden.swift"

# THE ROUTE LINE. A scoreboard has to name what it measured, or a number from
# it cannot be attributed to anything later. "The guest route" is not an
# artifact -- these five files are, and any of them can move independently:
# the port source, the CF seam it talks through, our CoreFoundation, the
# FoundationEssentials module, and the golden. Hashing them AT BUILD TIME and
# baking them into the binary means the board carries its own provenance,
# rather than a report writer recalling it afterwards.
sha() { [ -f "$1" ] && sha256sum "$1" | cut -c1-16 || echo "MISSING"; }
{
  echo "// GENERATED by scripts/build_ud_score_guest.sh -- DO NOT EDIT."
  echo "let ROUTE: [(String, String)] = ["
  echo "  (\"port\",       \"UserDefaults.swift            $(sha "$R/src/overlay/UserDefaults.swift")\"),"
  echo "  (\"seam\",       \"UserDefaultsBridge_Guest.swift $(sha "$R/src/overlay/UserDefaultsBridge_Guest.swift")\"),"
  echo "  (\"CoreFoundation\", \"libCFTest.dylib          $(sha "$W/lib/libCFTest.dylib")\"),"
  echo "  (\"FoundationEssentials\", \"FoundationEssentials.o $(sha "$W/fe/module/FoundationEssentials.o")\"),"
  echo "  (\"port object\", \"UserDefaultsGuest.o           $(sha "$W/fe/UserDefaultsGuest.o")\"),"
  echo "]"
} > "$BUILDDIR/Provenance.swift"
cat "$BUILDDIR/Provenance.swift" | sed 's/^/    /'

# COMPILE at macOS 15, LINK at 13. Not a mismatch to paper over: the
# FoundationEssentials module this runner imports declares a minimum deployment
# target of macOS 15.0, so compiling below it is a hard error; the guest root's
# other objects were built the same way and link at 13.0 with a warning. Using
# one number for both would either fail to compile or change the binary's
# LC_BUILD_VERSION away from the configuration already proven to load.
echo "==> compiling the scoreboard runner (target $COMPILE_TRIPLE)"
swiftc -c -O -wmo -module-name ud_score_guest \
  -target "$COMPILE_TRIPLE" -sdk "$SDK" \
  -I "$W/fe/module" -I "$W/fe" -I "$W/fe/collections" -I "$W/fe/os" \
  -I "$R/include/CFPreferencesMinimal" \
  -module-cache-path "$W/fe/modcache" \
  "$BUILDDIR/main.swift" "$BUILDDIR/GuestGolden.swift" "$BUILDDIR/Provenance.swift" \
  -o "$W/fe/score_runner.o"

echo "==> linking"
OUT="$OUT" RUNNER="$W/fe/score_runner.o" bash "$R/scripts/link_ud_guest.sh"
