#!/bin/bash
# Build libc++'s SOURCE library as Darwin Mach-O arm64, on Linux.
#
#   scripts/build_libcxx_src.sh <libcxx-source-dir> [outdir]
#
# machorun's libc++.1.dylib exports 105 symbols directly (plus 367 re-exported
# from libc++abi, which is why its .tbd correctly advertises 472 -- `nm` on a
# re-exporting dylib UNDER-reports what it vends, and that has now misled two
# people in opposite directions). What it does not carry is the parts of libc++
# that need a real implementation rather than a header: std::mutex,
# std::condition_variable, __call_once, locale, the streams.
#
# ICU is the consumer that needs them. Linking ICU against the stub left seven
# undefined C++ symbols -- mutex::lock/unlock/~, condition_variable::
# notify_all/wait/~, and __call_once.
#
# THE INCLUDE CONFIGURATION IS THE WHOLE TRICK, and I got it wrong three times
# before asking the compiler properly. What works:
#
#     -isysroot $SDK -I $S/src -D_LIBCPP_BUILDING_LIBRARY
#
# and nothing else. Specifically NOT `-nostdinc++ -I $S/include`, which is the
# canonical way to build libc++ against its OWN headers -- that needs
# __config_site and __assertion_handler, both generated by CMake, and produces a
# cascade of misleading errors about std::intmax_t and using_if_exists that look
# like a broken sysroot and are not.
#
# The sysroot's usr/include/c++/v1 is the installed LLVM 18 tree, complete with
# __config_site, and it MATCHES the sources (_LIBCPP_VERSION 180100 on both).
# So the headers are already configured; only libc++'s build-only headers under
# src/ have to be added. A one-line probe settled it after three rounds of
# include-path archaeology:
#
#     printf '#include <cstdint>\n#include <mutex>\nstd::mutex m;\n' | clang++ ...
#
# Compile with clang-18, not the default clang 17: the headers are LLVM 18 and
# the sources are C++20.
set -euo pipefail
S=${1:?usage: build_libcxx_src.sh <libcxx-source-dir> [outdir]}
OUT=${2:-/work/cxxthread}
SDK=${SDK:-/work/sdk/MacOSX.sdk}
CXX=${CXX:-/usr/lib/llvm-18/bin/clang++}
SHIM=${SHIM:-/work/icu-out/shim}

[ -d "$S/src" ] || { echo "build_libcxx_src: no $S/src" >&2; exit 2; }

mkdir -p "$OUT/obj" "$OUT/log"
: > "$OUT/FAIL.txt"
pass=0; fail=0

for src in "$S"/src/*.cpp; do
  b=$(basename "$src" .cpp)

  # tz.cpp is DELIBERATELY SKIPPED, and recorded rather than silently dropped.
  # libc++ 18's tz.cpp knows only `#if defined(__linux__)` for the IANA tzdb
  # directory and hits `#error "unknown path to the IANA Time Zone Database"`
  # on any other target -- a real portability gap in libc++ itself, not
  # something wrong with our sysroot. Darwin's path is the same
  # /usr/share/zoneinfo/, so the fix is a one-line branch, but NOTHING IN THIS
  # STACK USES std::chrono::tzdb: ICU carries its own timezone code and CF uses
  # CFTimeZone. Patching upstream for an unused feature would be inventing a
  # claim we cannot test. Add the branch when something consumes it.
  if [ "$b" = "tz" ]; then
    echo "  skip tz.cpp (no Darwin tzdb branch upstream; nothing consumes it)"
    continue
  fi

  # locale.cpp reaches <langinfo.h>, which machorun's sysroot does not carry.
  # build_icu.sh already stages a declaration-only shim for exactly this, so
  # reuse it rather than writing a second one -- a second shim is a second
  # thing to keep in step.
  extra=()
  [ "$b" = "locale" ] && extra=(-idirafter "$SHIM")

  if $CXX -target arm64-apple-macos13.0 -isysroot "$SDK" -std=c++20 -Os \
       -I "$S/src" -D_LIBCPP_BUILDING_LIBRARY "${extra[@]}" \
       -c "$src" -o "$OUT/obj/$b.o" 2>"$OUT/log/$b.err"; then
    pass=$((pass+1))
  else
    fail=$((fail+1)); echo "$b" >> "$OUT/FAIL.txt"
  fi
done

echo "libc++ src: PASS=$pass FAIL=$fail"
if [ "$fail" -gt 0 ]; then
  while read -r b; do
    printf '  %-26s %s\n' "$b" \
      "$(grep -m1 'error:' "$OUT/log/$b.err" | sed 's/.*error: //' | cut -c1-56)"
  done < "$OUT/FAIL.txt"
  exit 1
fi

rm -f "$OUT/libcxxsrc.a"
llvm-ar-18 rcs "$OUT/libcxxsrc.a" "$OUT/obj"/*.o
ls -la "$OUT/libcxxsrc.a"

# LINK THIS ARCHIVE NORMALLY, NEVER WITH -force_load. Pulling every member in
# drags locale.cpp's whole xlocale and wide-character surface into any consumer
# that did not ask for it: measured, ICU's undefined count went from 6 to 56
# purely from -force_load, and every one of the extra 50 was a libSystem symbol
# nothing actually calls. The linker extracting only what is referenced is the
# point of an archive.
echo
echo "NOTE: link with '\$OUT/libcxxsrc.a' positionally, NOT -force_load."
