#!/usr/bin/env python3
"""Emit asm `.set` aliases for symbols whose Darwin alias mechanism does not work.

    scripts/gen_alias_shims.py <CF_SOURCE_DIR> [<LIBDISPATCH_SOURCE_DIR>]

WHY THIS EXISTS: THREE ALIAS MECHANISMS, ONLY ONE SURVIVES
----------------------------------------------------------
Measured, not assumed:

    __attribute__((alias))   clang: "aliases are not supported on darwin"
    -alias_list              ld64.lld: "Option `-alias_list' is not yet
                             implemented. Stay tuned..." -- WARNS, EXITS 0,
                             AND PRODUCES NOTHING
    .set in inline asm       works (proven by ___CFConstantStringClassReference)

The middle one is the dangerous one. A build flag that is accepted and ignored
is the linker-level version of a stub that returns, except a stub at least runs.
It was caught only by counting the symbol in the artifact rather than reading
the link's exit code, which is why the verification at the bottom of this file
counts exports and never trusts a return value.

WHAT IS BEING ALIASED, AND WHY IT IS MISSING
--------------------------------------------
corelibs guards 99 alias declarations in CFLocaleKeys.c with

    // Aliases for other platforms.
    #if TARGET_OS_LINUX || TARGET_OS_BSD || TARGET_OS_WIN32 || TARGET_OS_WASI

because on Darwin these old un-suffixed names come from Apple's CoreFoundation.
We are TARGET_OS_MAC by target triple and corelibs by implementation, so we take
Apple's branch without Apple's code and get neither. Same for libdispatch's
_dispatch_queue_attr_concurrent, which Darwin supplies via -alias_list.

THE LIST IS DERIVED, NEVER TRANSCRIBED
--------------------------------------
Both sets are parsed out of the upstream sources -- CFLocaleKeys.c's own alias
block and libdispatch's own libdispatch.aliases. A transcribed list is a fact
with no version in it: upstream adds aliases and nothing here would notice.

This also fixes the count. Only SIX of the 99 appeared as undefined at CF's own
link, because a link reports what its current consumers happen to reference, not
what is absent. Hand-fixing the six would have left 93 landmines, each surfacing
later as an unlocalised failure somewhere else. Same lower-bound shape as
"ICU 1" becoming "ICU 12" once the blocking layer was resolved.

WHY THE ALIASES ARE APPENDED TO THE DEFINING SOURCE, NOT PUT IN A NEW FILE
--------------------------------------------------------------------------
`.set` is an assembler-level equality. The target symbol has to be visible in
the SAME translation unit, which is why the constant-string alias lives in
NSCFConstantString.m beside the class it aliases. So these are appended to
CFLocaleKeys.c and to libdispatch's init.c rather than collected into a
shims.c, where every `.set` would reference a symbol the assembler cannot see.
"""
import os
import re
import sys

# CF_EXPORT CFStringRef const kCFGregorianCalendar __attribute__((alias ("kCFCalendarIdentifierGregorian")));
CF_ALIAS = re.compile(
    r"^\s*CF_EXPORT\s+\w+\s+const\s+(\w+)\s*__attribute__\(\(\s*alias\s*\(\s*\"([^\"]+)\"\s*\)\s*\)\)\s*;",
    re.M)

MARK = "/* GENERATED by scripts/gen_alias_shims.py -- asm .set aliases */"


def cf_aliases(path):
    """(alias, target) pairs from CFLocaleKeys.c's own declarations."""
    with open(path, errors="replace") as fh:
        return CF_ALIAS.findall(fh.read())


def dispatch_aliases(path):
    """(alias, target) from libdispatch.aliases.

    ld64's -alias_list format is `<real_symbol> <alias_name>` per line, comments
    with '#'. These are already assembler names, underscore included, so unlike
    the CF set they are NOT prefixed again.
    """
    out = []
    with open(path, errors="replace") as fh:
        for line in fh:
            line = line.split("#")[0].strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) == 2:
                real, alias = parts
                out.append((alias, real))
    return out


def emit(pairs, prefix):
    """One .set per pair, guarded so a missing target is a link error, not silence."""
    body = [MARK,
            "/* .set makes two names denote one address. The target must be in this",
            " * same translation unit -- an assembler equality cannot reach across",
            " * objects, which is why this block is appended to the defining source",
            " * rather than collected elsewhere. */",
            "__asm__("]
    for alias, target in pairs:
        a, t = prefix + alias, prefix + target
        body.append(f'    ".globl {a}\\n"')
        body.append(f'    ".set   {a}, {t}\\n"')
    body.append(");")
    return "\n".join(body) + "\n"


def append_once(path, text, label):
    with open(path, errors="replace") as fh:
        src = fh.read()
    if MARK in src:
        print(f"  {label}: already generated")
        return 0
    with open(path, "a") as fh:
        fh.write("\n" + text)
    return 1


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    cf = sys.argv[1]
    ld = sys.argv[2] if len(sys.argv) > 2 else None

    keys = os.path.join(cf, "CFLocaleKeys.c")
    pairs = cf_aliases(keys)
    if not pairs:
        # An empty parse would silently generate nothing and report success,
        # leaving all 99 absent. Refuse instead.
        sys.exit(f"gen_alias_shims: parsed ZERO aliases from {keys} -- refusing "
                 f"to emit an empty shim, which would look like a pass and fix "
                 f"nothing.")
    print(f"gen_alias_shims: {len(pairs)} CF aliases derived from CFLocaleKeys.c")
    append_once(keys, emit(pairs, "_"), "CFLocaleKeys.c")

    # LIBDISPATCH IS DISABLED, AND THE REASON IS A THIRD FAILED MECHANISM.
    #
    # _dispatch_queue_attr_concurrent aliases _dispatch_queue_attrs, which is a
    # `const struct dispatch_queue_attr_s []` -- an array in a const data
    # section. ld64.lld refuses:
    #
    #     ld64.lld: error: TODO: support aliasing to symbols of kind 1
    #
    # So ALL THREE mechanisms fail for this one symbol, where the CF constants
    # needed only the third:
    #
    #     __attribute__((alias))  rejected by clang on Darwin
    #     -alias_list             accepted and IGNORED by ld64.lld
    #     .set                    works for the CF pointers, REFUSED here
    #
    # .set working for `CFStringRef const` and not for an array member is the
    # distinction, and it is not one anybody would predict from "aliases work".
    # The remaining route is corelibs' own `#ifndef __APPLE__` manual
    # definition, which needs a patch rather than a generator.
    #
    # Left in place but off, because a negative result with its error message is
    # worth more than a deleted branch someone re-derives.
    if ld and os.environ.get("GEN_DISPATCH_ALIASES"):
        al = os.path.join(ld, "xcodeconfig", "libdispatch.aliases")
        init = os.path.join(ld, "src", "init.c")
        if os.path.exists(al) and os.path.exists(init):
            dpairs = dispatch_aliases(al)
            if not dpairs:
                sys.exit(f"gen_alias_shims: parsed ZERO aliases from {al}")
            # Only those whose target this TU actually defines; the file also
            # lists $V2 symbol-version aliases that are not ours to make.
            want = [(a, t) for a, t in dpairs if "$" not in a and "$" not in t]
            print(f"gen_alias_shims: {len(want)} dispatch aliases derived from "
                  f"libdispatch.aliases (of {len(dpairs)}; $-versioned skipped)")
            append_once(init, emit(want, ""), "libdispatch init.c")


if __name__ == "__main__":
    main()
