#!/usr/bin/env python3
"""Generate the three mechanical clean-room availability headers.

    python3 sdk/local/gen_availability.py

writes sdk/local/AvailabilityVersions.h, sdk/local/AvailabilityMacros.h and
sdk/local/sys/_symbol_aliasing.h.  The outputs are COMMITTED; this script
exists so they can be regenerated rather than hand-edited, and so the encoding
rule below is written down once instead of 5,000 times.

Why these three are generated and not vendored
----------------------------------------------
`AvailabilityVersions.h` matches nothing in any apple-oss-distributions repo
(docs/SDK_SURVEY.md §2.4).  `AvailabilityMacros.h` matches only a stale xnu
EXTERNAL_HEADERS snapshot.  `sys/_symbol_aliasing.h` IS generated upstream --
by xnu:bsd/sys/make_symbol_aliasing.sh -- but that script's first act is to run
`<sdk>/usr/local/libexec/availability.pl`, which ships only in Apple's INTERNAL
SDK and is in neither the public SDK nor any published repo.  So the generator
is published and its input is not, which puts the header here.

The encoding rule (Apple's, and public: it is what the constants evaluate to)
------------------------------------------------------------------------------
    macOS 10.0 - 10.9   major*100 + minor*10 + patch     __MAC_10_6  == 1060
    macOS 10.10 +       major*10000 + minor*100 + patch  __MAC_10_13 == 101300
    every other OS      major*10000 + minor*100 + patch  __IPHONE_10_0 == 100000

scripts/sdk_check_abi.sh diffs the values these produce against Apple's own SDK
on the macOS oracle, so the rule is verified rather than asserted.

What this omits versus Apple's headers
--------------------------------------
Only major.minor is emitted for every OS, plus major.minor.patch for the macOS
10.x era where Apple used patch-level availability.  A guest that names, say,
__MAC_13_1_2 gets an undeclared-identifier error -- a loud abort, which is the
house rule, rather than a silently wrong number.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# (macro stem, human name, [(major, [minors])])
MACOS = [(10, range(0, 17)), (11, range(0, 8)), (12, range(0, 8)),
         (13, range(0, 8)), (14, range(0, 8)), (15, range(0, 8)),
         (16, range(0, 1)), (26, range(0, 5))]
IOSISH = [(2, range(0, 3)), (3, range(0, 3)), (4, range(0, 4)), (5, range(0, 2)),
          (6, range(0, 2)), (7, range(0, 2)), (8, range(0, 5)), (9, range(0, 4)),
          (10, range(0, 4)), (11, range(0, 5)), (12, range(0, 5)),
          (13, range(0, 8)), (14, range(0, 9)), (15, range(0, 7)),
          (16, range(0, 8)), (17, range(0, 8)), (18, range(0, 8)),
          (19, range(0, 8)), (26, range(0, 5))]


def enc(plat, maj, mnr, pat=0):
    if plat == "MAC" and maj == 10 and mnr <= 9:
        return maj * 100 + mnr * 10 + pat
    return maj * 10000 + mnr * 100 + pat


def versions(plat):
    """Yield (macro_suffix, value) in definition order."""
    table = MACOS if plat == "MAC" else IOSISH
    for maj, minors in table:
        for mnr in minors:
            yield "%d_%d" % (maj, mnr), enc(plat, maj, mnr)
            # patch-level constants: the macOS 10.x era only, see the docstring
            if plat == "MAC" and maj == 10:
                for pat in range(1, 10):
                    yield "%d_%d_%d" % (maj, mnr, pat), enc(plat, maj, mnr, pat)


BANNER = """\
/*
 * %s -- machorun's clean-room replacement.
 *
 * NOT Apple's header.  Generated by sdk/local/gen_availability.py; see that
 * file for the encoding rule, for why this one is not vendored from
 * apple-oss-distributions, and for exactly what it omits.
 *
 * machorun ships no public API whose availability anyone checks, so every
 * availability ATTRIBUTE in this SDK expands to nothing.  What survives is the
 * arithmetic: the version constants, which real headers compare against.
 */
"""

PLATFORMS = [
    ("MAC", "__MAC"), ("IPHONE", "__IPHONE"), ("TVOS", "__TVOS"),
    ("WATCHOS", "__WATCHOS"), ("VISIONOS", "__VISIONOS"),
    ("BRIDGEOS", "__BRIDGEOS"), ("DRIVERKIT", "__DRIVERKIT"),
]


def gen_versions():
    o = [BANNER % "AvailabilityVersions.h",
         "#ifndef __AVAILABILITY_VERSIONS__",
         "#define __AVAILABILITY_VERSIONS__",
         "",
         "#define __MACHORUN_SDK__ 1",
         "",
         "/* 'not available on this platform', larger than any real version */",
         ]
    for _, stem in PLATFORMS:
        o.append("#define %-40s %s" % (stem + "_NA", "9999"))
    o.append("")
    for plat, stem in PLATFORMS:
        o.append("/* ---- %s ---- */" % plat)
        for suf, val in versions(plat):
            o.append("#define %-40s %d" % (stem + "_" + suf, val))
        o.append("")

    o.append("/* AvailabilityMacros.h's spelling of the same macOS numbers.  Apple")
    o.append(" * switched prefix at 11.0: MAC_OS_X_VERSION_10_15, MAC_OS_VERSION_11_0. */")
    for suf, val in versions("MAC"):
        name = ("MAC_OS_X_VERSION_" if suf.startswith("10_") else "MAC_OS_VERSION_") + suf
        o.append("#define %-40s %d" % (name, val))
    o.append("")

    o.append("""\
/* Deployment target and SDK ceiling.
 *
 * clang predefines __ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__ for an Apple
 * target (110000 for -target arm64-apple-macos11); everything below is derived
 * from it rather than assumed, so changing DARWIN_TARGET changes these too.
 * MAX_ALLOWED is pinned to this SDK's own ceiling. */
#ifndef __MAC_OS_X_VERSION_MIN_REQUIRED
  #ifdef __ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__
    #define __MAC_OS_X_VERSION_MIN_REQUIRED __ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__
  #else
    #define __MAC_OS_X_VERSION_MIN_REQUIRED __MAC_11_0
  #endif
#endif
#ifndef __MAC_OS_X_VERSION_MAX_ALLOWED
  #define __MAC_OS_X_VERSION_MAX_ALLOWED __MAC_26_0
#endif

/* We do not target these, and no reached header defines them for us.  They are
 * declared so that `#if __IPHONE_OS_VERSION_MIN_REQUIRED >= __IPHONE_x_y` in a
 * vendored header takes the false branch instead of failing to parse. */
#ifndef __IPHONE_OS_VERSION_MIN_REQUIRED
  #define __IPHONE_OS_VERSION_MIN_REQUIRED 0
#endif
#ifndef __IPHONE_OS_VERSION_MAX_ALLOWED
  #define __IPHONE_OS_VERSION_MAX_ALLOWED 0
#endif
#ifndef __TV_OS_VERSION_MIN_REQUIRED
  #define __TV_OS_VERSION_MIN_REQUIRED 0
#endif
#ifndef __TV_OS_VERSION_MAX_ALLOWED
  #define __TV_OS_VERSION_MAX_ALLOWED 0
#endif
#ifndef __WATCH_OS_VERSION_MIN_REQUIRED
  #define __WATCH_OS_VERSION_MIN_REQUIRED 0
#endif
#ifndef __WATCH_OS_VERSION_MAX_ALLOWED
  #define __WATCH_OS_VERSION_MAX_ALLOWED 0
#endif
#ifndef __VISION_OS_VERSION_MIN_REQUIRED
  #define __VISION_OS_VERSION_MIN_REQUIRED 0
#endif
#ifndef __VISION_OS_VERSION_MAX_ALLOWED
  #define __VISION_OS_VERSION_MAX_ALLOWED 0
#endif
#ifndef __BRIDGE_OS_VERSION_MIN_REQUIRED
  #define __BRIDGE_OS_VERSION_MIN_REQUIRED 0
#endif
#ifndef __BRIDGE_OS_VERSION_MAX_ALLOWED
  #define __BRIDGE_OS_VERSION_MAX_ALLOWED 0
#endif
#ifndef __DRIVERKIT_VERSION_MIN_REQUIRED
  #define __DRIVERKIT_VERSION_MIN_REQUIRED 0
#endif
#ifndef __DRIVERKIT_VERSION_MAX_ALLOWED
  #define __DRIVERKIT_VERSION_MAX_ALLOWED 0
#endif

#endif /* __AVAILABILITY_VERSIONS__ */""")
    return "\n".join(o) + "\n"


def gen_macros():
    o = [BANNER % "AvailabilityMacros.h",
         "#ifndef __AVAILABILITYMACROS__",
         "#define __AVAILABILITYMACROS__",
         "",
         "#include <AvailabilityVersions.h>",
         "#include <TargetConditionals.h>",
         "",
         "/* The pre-__API_AVAILABLE family.  Every one is a diagnostic, and this",
         " * SDK emits no availability diagnostics, so every one is empty. */",
         "#define DEPRECATED_ATTRIBUTE",
         "#define DEPRECATED_MSG_ATTRIBUTE(_msg)",
         "#define UNAVAILABLE_ATTRIBUTE",
         "#define WEAK_IMPORT_ATTRIBUTE __attribute__((weak_import))",
         "#define AVAILABLE_MAC_OS_X_VERSION_10_0_AND_LATER",
         ""]
    seen = set()
    for suf, _ in versions("MAC"):
        name = ("MAC_OS_X_VERSION_" if suf.startswith("10_") else "MAC_OS_VERSION_") + suf
        for form in ("AVAILABLE_%s_AND_LATER",
                     "AVAILABLE_%s_AND_LATER_BUT_DEPRECATED",
                     "DEPRECATED_IN_%s_AND_LATER"):
            m = form % name
            if m in seen:
                continue
            seen.add(m)
            o.append("#define " + m)
    o.append("")
    o.append("""\
/* The two-version and _BUT_DEPRECATED_IN_ forms take arguments; they are the
 * same diagnostic and the same nothing. */
#define AVAILABLE_MAC_OS_X_VERSION_10_0_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_0
#define DEPRECATED_MSG_ATTRIBUTE_IN(_msg)

#endif /* __AVAILABILITYMACROS__ */""")
    return "\n".join(o) + "\n"


def gen_symbol_aliasing():
    o = [BANNER % "sys/_symbol_aliasing.h",
         "#ifndef _CDEFS_H_",
         '# error "Never use <sys/_symbol_aliasing.h> directly.  Use <sys/cdefs.h> instead."',
         "#endif",
         "",
         "/* sys/cdefs.h token-pastes a version macro name onto these:",
         " *   __DARWIN_ALIAS_STARTING(__MAC_10_6, __IPHONE_2_0, sym)",
         " *     -> __DARWIN_ALIAS_STARTING_MAC___MAC_10_6(sym)   on macOS",
         " * Each expands to its argument when the deployment target is at least",
         " * that version, and to nothing otherwise -- which is what selects the",
         " * $UNIX2003 / $INODE64 symbol variants. */",
         ""]
    for plat, stem, envmacro in (
            ("MAC", "__MAC", "__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__"),
            ("IPHONE", "__IPHONE", "__ENVIRONMENT_IPHONE_OS_VERSION_MIN_REQUIRED__")):
        o.append("/* ---- %s ---- */" % plat)
        o.append("#define __DARWIN_ALIAS_STARTING_%s_%s_NA(x)" % (plat, stem))
        for suf, val in versions(plat):
            name = "__DARWIN_ALIAS_STARTING_%s_%s_%s" % (plat, stem, suf)
            o.append("#if defined(%s) && %s >= %d" % (envmacro, envmacro, val))
            o.append("#define %s(x) x" % name)
            o.append("#else")
            o.append("#define %s(x)" % name)
            o.append("#endif")
        o.append("")
    return "\n".join(o) + "\n"


def main():
    out = {
        "AvailabilityVersions.h": gen_versions(),
        "AvailabilityMacros.h": gen_macros(),
        os.path.join("sys", "_symbol_aliasing.h"): gen_symbol_aliasing(),
    }
    for rel, text in out.items():
        p = os.path.join(HERE, rel)
        os.makedirs(os.path.dirname(p), exist_ok=True)
        with open(p, "w") as f:
            f.write(text)
        print("   %-32s %5d lines" % (rel, text.count("\n")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
