/// Graph-present global constants. Numeric values were measured from the
/// pinned Xcode 26.1 iPhoneOS SDK with a compile-time Apple-oracle probe.
/// The checked-in agent runtime locks those observed values down on Linux.

public var CA_PREFER_FIXED_POINT: Int32 { 1 }
public var COREAUDIOTYPES_VERSION: Int32 { 20211130 }

public var kAppleLosslessFormatFlag_16BitSourceData: AudioFormatFlags { 1 }
public var kAppleLosslessFormatFlag_20BitSourceData: AudioFormatFlags { 2 }
public var kAppleLosslessFormatFlag_24BitSourceData: AudioFormatFlags { 3 }
public var kAppleLosslessFormatFlag_32BitSourceData: AudioFormatFlags { 4 }

public var kAudioChannelLabel_Unknown: AudioChannelLabel { 4294967295 }
public var kAudioChannelLabel_Unused: AudioChannelLabel { 0 }
public var kAudioChannelLabel_UseCoordinates: AudioChannelLabel { 100 }
public var kAudioChannelLabel_Left: AudioChannelLabel { 1 }
public var kAudioChannelLabel_Right: AudioChannelLabel { 2 }
public var kAudioChannelLabel_Center: AudioChannelLabel { 3 }
public var kAudioChannelLabel_LFEScreen: AudioChannelLabel { 4 }
public var kAudioChannelLabel_LeftSurround: AudioChannelLabel { 5 }
public var kAudioChannelLabel_RightSurround: AudioChannelLabel { 6 }
public var kAudioChannelLabel_LeftCenter: AudioChannelLabel { 7 }
public var kAudioChannelLabel_RightCenter: AudioChannelLabel { 8 }
public var kAudioChannelLabel_CenterSurround: AudioChannelLabel { 9 }
public var kAudioChannelLabel_LeftSurroundDirect: AudioChannelLabel { 10 }
public var kAudioChannelLabel_RightSurroundDirect: AudioChannelLabel { 11 }
public var kAudioChannelLabel_TopCenterSurround: AudioChannelLabel { 12 }
public var kAudioChannelLabel_VerticalHeightLeft: AudioChannelLabel { 13 }
public var kAudioChannelLabel_VerticalHeightCenter: AudioChannelLabel { 14 }
public var kAudioChannelLabel_VerticalHeightRight: AudioChannelLabel { 15 }
public var kAudioChannelLabel_TopBackLeft: AudioChannelLabel { 16 }
public var kAudioChannelLabel_TopBackCenter: AudioChannelLabel { 17 }
public var kAudioChannelLabel_TopBackRight: AudioChannelLabel { 18 }
public var kAudioChannelLabel_RearSurroundLeft: AudioChannelLabel { 33 }
public var kAudioChannelLabel_RearSurroundRight: AudioChannelLabel { 34 }
public var kAudioChannelLabel_LeftWide: AudioChannelLabel { 35 }
public var kAudioChannelLabel_RightWide: AudioChannelLabel { 36 }
public var kAudioChannelLabel_LFE2: AudioChannelLabel { 37 }
public var kAudioChannelLabel_LeftTotal: AudioChannelLabel { 38 }
public var kAudioChannelLabel_RightTotal: AudioChannelLabel { 39 }
public var kAudioChannelLabel_HearingImpaired: AudioChannelLabel { 40 }
public var kAudioChannelLabel_Narration: AudioChannelLabel { 41 }
public var kAudioChannelLabel_Mono: AudioChannelLabel { 42 }
public var kAudioChannelLabel_DialogCentricMix: AudioChannelLabel { 43 }
public var kAudioChannelLabel_CenterSurroundDirect: AudioChannelLabel { 44 }
public var kAudioChannelLabel_Haptic: AudioChannelLabel { 45 }
public var kAudioChannelLabel_LeftTopMiddle: AudioChannelLabel { 49 }
public var kAudioChannelLabel_RightTopMiddle: AudioChannelLabel { 51 }
public var kAudioChannelLabel_LeftTopRear: AudioChannelLabel { 52 }
public var kAudioChannelLabel_CenterTopRear: AudioChannelLabel { 53 }
public var kAudioChannelLabel_RightTopRear: AudioChannelLabel { 54 }
public var kAudioChannelLabel_LeftTopFront: AudioChannelLabel { 13 }
public var kAudioChannelLabel_CenterTopFront: AudioChannelLabel { 14 }
public var kAudioChannelLabel_RightTopFront: AudioChannelLabel { 15 }
public var kAudioChannelLabel_CenterTopMiddle: AudioChannelLabel { 12 }
public var kAudioChannelLabel_LeftSideSurround: AudioChannelLabel { 55 }
public var kAudioChannelLabel_RightSideSurround: AudioChannelLabel { 56 }
public var kAudioChannelLabel_LeftBackSurround: AudioChannelLabel { 63 }
public var kAudioChannelLabel_RightBackSurround: AudioChannelLabel { 64 }
public var kAudioChannelLabel_LeftBottom: AudioChannelLabel { 57 }
public var kAudioChannelLabel_RightBottom: AudioChannelLabel { 58 }
public var kAudioChannelLabel_CenterBottom: AudioChannelLabel { 59 }
public var kAudioChannelLabel_LeftEdgeOfScreen: AudioChannelLabel { 65 }
public var kAudioChannelLabel_RightEdgeOfScreen: AudioChannelLabel { 66 }
public var kAudioChannelLabel_LeftTopSurround: AudioChannelLabel { 60 }
public var kAudioChannelLabel_RightTopSurround: AudioChannelLabel { 61 }
public var kAudioChannelLabel_LFE3: AudioChannelLabel { 62 }
public var kAudioChannelLabel_Object: AudioChannelLabel { 262144 }
public var kAudioChannelLabel_BinauralLeft: AudioChannelLabel { 208 }
public var kAudioChannelLabel_BinauralRight: AudioChannelLabel { 209 }
public var kAudioChannelLabel_Ambisonic_W: AudioChannelLabel { 200 }
public var kAudioChannelLabel_Ambisonic_X: AudioChannelLabel { 201 }
public var kAudioChannelLabel_Ambisonic_Y: AudioChannelLabel { 202 }
public var kAudioChannelLabel_Ambisonic_Z: AudioChannelLabel { 203 }
public var kAudioChannelLabel_MS_Mid: AudioChannelLabel { 204 }
public var kAudioChannelLabel_MS_Side: AudioChannelLabel { 205 }
public var kAudioChannelLabel_XY_X: AudioChannelLabel { 206 }
public var kAudioChannelLabel_XY_Y: AudioChannelLabel { 207 }
public var kAudioChannelLabel_HeadphonesLeft: AudioChannelLabel { 301 }
public var kAudioChannelLabel_HeadphonesRight: AudioChannelLabel { 302 }
public var kAudioChannelLabel_ClickTrack: AudioChannelLabel { 304 }
public var kAudioChannelLabel_ForeignLanguage: AudioChannelLabel { 305 }
public var kAudioChannelLabel_Discrete: AudioChannelLabel { 400 }
public var kAudioChannelLabel_HOA_ACN: AudioChannelLabel { 500 }
public var kAudioChannelLabel_HOA_SN3D: AudioChannelLabel { 131072 }
public var kAudioChannelLabel_HOA_N3D: AudioChannelLabel { 196608 }
public var kAudioChannelLabel_BeginReserved: AudioChannelLabel { 4026531840 }
public var kAudioChannelLabel_EndReserved: AudioChannelLabel { 4294967294 }
public var kAudioChannelLabel_Discrete_0: AudioChannelLabel { 65536 }
public var kAudioChannelLabel_Discrete_1: AudioChannelLabel { 65537 }
public var kAudioChannelLabel_Discrete_2: AudioChannelLabel { 65538 }
public var kAudioChannelLabel_Discrete_3: AudioChannelLabel { 65539 }
public var kAudioChannelLabel_Discrete_4: AudioChannelLabel { 65540 }
public var kAudioChannelLabel_Discrete_5: AudioChannelLabel { 65541 }
public var kAudioChannelLabel_Discrete_6: AudioChannelLabel { 65542 }
public var kAudioChannelLabel_Discrete_7: AudioChannelLabel { 65543 }
public var kAudioChannelLabel_Discrete_8: AudioChannelLabel { 65544 }
public var kAudioChannelLabel_Discrete_9: AudioChannelLabel { 65545 }
public var kAudioChannelLabel_Discrete_10: AudioChannelLabel { 65546 }
public var kAudioChannelLabel_Discrete_11: AudioChannelLabel { 65547 }
public var kAudioChannelLabel_Discrete_12: AudioChannelLabel { 65548 }
public var kAudioChannelLabel_Discrete_13: AudioChannelLabel { 65549 }
public var kAudioChannelLabel_Discrete_14: AudioChannelLabel { 65550 }
public var kAudioChannelLabel_Discrete_15: AudioChannelLabel { 65551 }
public var kAudioChannelLabel_Discrete_65535: AudioChannelLabel { 131071 }
public var kAudioChannelLabel_HOA_ACN_0: AudioChannelLabel { 131072 }
public var kAudioChannelLabel_HOA_ACN_1: AudioChannelLabel { 131073 }
public var kAudioChannelLabel_HOA_ACN_2: AudioChannelLabel { 131074 }
public var kAudioChannelLabel_HOA_ACN_3: AudioChannelLabel { 131075 }
public var kAudioChannelLabel_HOA_ACN_4: AudioChannelLabel { 131076 }
public var kAudioChannelLabel_HOA_ACN_5: AudioChannelLabel { 131077 }
public var kAudioChannelLabel_HOA_ACN_6: AudioChannelLabel { 131078 }
public var kAudioChannelLabel_HOA_ACN_7: AudioChannelLabel { 131079 }
public var kAudioChannelLabel_HOA_ACN_8: AudioChannelLabel { 131080 }
public var kAudioChannelLabel_HOA_ACN_9: AudioChannelLabel { 131081 }
public var kAudioChannelLabel_HOA_ACN_10: AudioChannelLabel { 131082 }
public var kAudioChannelLabel_HOA_ACN_11: AudioChannelLabel { 131083 }
public var kAudioChannelLabel_HOA_ACN_12: AudioChannelLabel { 131084 }
public var kAudioChannelLabel_HOA_ACN_13: AudioChannelLabel { 131085 }
public var kAudioChannelLabel_HOA_ACN_14: AudioChannelLabel { 131086 }
public var kAudioChannelLabel_HOA_ACN_15: AudioChannelLabel { 131087 }
public var kAudioChannelLabel_HOA_ACN_65024: AudioChannelLabel { 196096 }

public var kAudioChannelLayoutTag_AAC_3_0: AudioChannelLayoutTag { 7471107 }
public var kAudioChannelLayoutTag_AAC_4_0: AudioChannelLayoutTag { 7602180 }
public var kAudioChannelLayoutTag_AAC_5_0: AudioChannelLayoutTag { 7864325 }
public var kAudioChannelLayoutTag_AAC_5_1: AudioChannelLayoutTag { 8126470 }
public var kAudioChannelLayoutTag_AAC_6_0: AudioChannelLayoutTag { 9240582 }
public var kAudioChannelLayoutTag_AAC_6_1: AudioChannelLayoutTag { 9306119 }
public var kAudioChannelLayoutTag_AAC_7_0: AudioChannelLayoutTag { 9371655 }
public var kAudioChannelLayoutTag_AAC_7_1: AudioChannelLayoutTag { 8323080 }
public var kAudioChannelLayoutTag_AAC_7_1_B: AudioChannelLayoutTag { 11993096 }
public var kAudioChannelLayoutTag_AAC_7_1_C: AudioChannelLayoutTag { 12058632 }
public var kAudioChannelLayoutTag_AAC_Octagonal: AudioChannelLayoutTag { 9437192 }
public var kAudioChannelLayoutTag_AAC_Quadraphonic: AudioChannelLayoutTag { 7077892 }
public var kAudioChannelLayoutTag_AC3_1_0_1: AudioChannelLayoutTag { 9764866 }
public var kAudioChannelLayoutTag_AC3_2_1_1: AudioChannelLayoutTag { 10027012 }
public var kAudioChannelLayoutTag_AC3_3_0: AudioChannelLayoutTag { 9830403 }
public var kAudioChannelLayoutTag_AC3_3_0_1: AudioChannelLayoutTag { 9961476 }
public var kAudioChannelLayoutTag_AC3_3_1: AudioChannelLayoutTag { 9895940 }
public var kAudioChannelLayoutTag_AC3_3_1_1: AudioChannelLayoutTag { 10092549 }
public var kAudioChannelLayoutTag_Ambisonic_B_Format: AudioChannelLayoutTag { 7012356 }
public var kAudioChannelLayoutTag_Atmos_5_1_2: AudioChannelLayoutTag { 12713992 }
public var kAudioChannelLayoutTag_Atmos_5_1_4: AudioChannelLayoutTag { 12779530 }
public var kAudioChannelLayoutTag_Atmos_7_1_2: AudioChannelLayoutTag { 12845066 }
public var kAudioChannelLayoutTag_Atmos_7_1_4: AudioChannelLayoutTag { 12582924 }
public var kAudioChannelLayoutTag_Atmos_9_1_6: AudioChannelLayoutTag { 12648464 }
public var kAudioChannelLayoutTag_AudioUnit_4: AudioChannelLayoutTag { 7077892 }
public var kAudioChannelLayoutTag_AudioUnit_5: AudioChannelLayoutTag { 7143429 }
public var kAudioChannelLayoutTag_AudioUnit_5_0: AudioChannelLayoutTag { 7733253 }
public var kAudioChannelLayoutTag_AudioUnit_5_1: AudioChannelLayoutTag { 7929862 }
public var kAudioChannelLayoutTag_AudioUnit_6: AudioChannelLayoutTag { 7208966 }
public var kAudioChannelLayoutTag_AudioUnit_6_0: AudioChannelLayoutTag { 9109510 }
public var kAudioChannelLayoutTag_AudioUnit_6_1: AudioChannelLayoutTag { 8192007 }
public var kAudioChannelLayoutTag_AudioUnit_7_0: AudioChannelLayoutTag { 9175047 }
public var kAudioChannelLayoutTag_AudioUnit_7_0_Front: AudioChannelLayoutTag { 9699335 }
public var kAudioChannelLayoutTag_AudioUnit_7_1: AudioChannelLayoutTag { 8388616 }
public var kAudioChannelLayoutTag_AudioUnit_7_1_Front: AudioChannelLayoutTag { 8257544 }
public var kAudioChannelLayoutTag_AudioUnit_8: AudioChannelLayoutTag { 7274504 }
public var kAudioChannelLayoutTag_BeginReserved: AudioChannelLayoutTag { 4026531840 }
public var kAudioChannelLayoutTag_Binaural: AudioChannelLayoutTag { 6946818 }
public var kAudioChannelLayoutTag_CICP_1: AudioChannelLayoutTag { 6553601 }
public var kAudioChannelLayoutTag_CICP_10: AudioChannelLayoutTag { 8650756 }
public var kAudioChannelLayoutTag_CICP_11: AudioChannelLayoutTag { 8192007 }
public var kAudioChannelLayoutTag_CICP_12: AudioChannelLayoutTag { 8388616 }
public var kAudioChannelLayoutTag_CICP_13: AudioChannelLayoutTag { 13369368 }
public var kAudioChannelLayoutTag_CICP_14: AudioChannelLayoutTag { 13434888 }
public var kAudioChannelLayoutTag_CICP_15: AudioChannelLayoutTag { 13500428 }
public var kAudioChannelLayoutTag_CICP_16: AudioChannelLayoutTag { 13565962 }
public var kAudioChannelLayoutTag_CICP_17: AudioChannelLayoutTag { 13631500 }
public var kAudioChannelLayoutTag_CICP_18: AudioChannelLayoutTag { 13697038 }
public var kAudioChannelLayoutTag_CICP_19: AudioChannelLayoutTag { 13762572 }
public var kAudioChannelLayoutTag_CICP_2: AudioChannelLayoutTag { 6619138 }
public var kAudioChannelLayoutTag_CICP_20: AudioChannelLayoutTag { 13828110 }
public var kAudioChannelLayoutTag_CICP_3: AudioChannelLayoutTag { 7405571 }
public var kAudioChannelLayoutTag_CICP_4: AudioChannelLayoutTag { 7536644 }
public var kAudioChannelLayoutTag_CICP_5: AudioChannelLayoutTag { 7667717 }
public var kAudioChannelLayoutTag_CICP_6: AudioChannelLayoutTag { 7929862 }
public var kAudioChannelLayoutTag_CICP_7: AudioChannelLayoutTag { 8323080 }
public var kAudioChannelLayoutTag_CICP_9: AudioChannelLayoutTag { 8585219 }
public var kAudioChannelLayoutTag_Cube: AudioChannelLayoutTag { 7340040 }
public var kAudioChannelLayoutTag_DTS_3_1: AudioChannelLayoutTag { 11010052 }
public var kAudioChannelLayoutTag_DTS_4_1: AudioChannelLayoutTag { 11075589 }
public var kAudioChannelLayoutTag_DTS_6_0_A: AudioChannelLayoutTag { 11141126 }
public var kAudioChannelLayoutTag_DTS_6_0_B: AudioChannelLayoutTag { 11206662 }
public var kAudioChannelLayoutTag_DTS_6_0_C: AudioChannelLayoutTag { 11272198 }
public var kAudioChannelLayoutTag_DTS_6_1_A: AudioChannelLayoutTag { 11337735 }
public var kAudioChannelLayoutTag_DTS_6_1_B: AudioChannelLayoutTag { 11403271 }
public var kAudioChannelLayoutTag_DTS_6_1_C: AudioChannelLayoutTag { 11468807 }
public var kAudioChannelLayoutTag_DTS_6_1_D: AudioChannelLayoutTag { 11927559 }
public var kAudioChannelLayoutTag_DTS_7_0: AudioChannelLayoutTag { 11534343 }
public var kAudioChannelLayoutTag_DTS_7_1: AudioChannelLayoutTag { 11599880 }
public var kAudioChannelLayoutTag_DTS_8_0_A: AudioChannelLayoutTag { 11665416 }
public var kAudioChannelLayoutTag_DTS_8_0_B: AudioChannelLayoutTag { 11730952 }
public var kAudioChannelLayoutTag_DTS_8_1_A: AudioChannelLayoutTag { 11796489 }
public var kAudioChannelLayoutTag_DTS_8_1_B: AudioChannelLayoutTag { 11862025 }
public var kAudioChannelLayoutTag_DVD_0: AudioChannelLayoutTag { 6553601 }
public var kAudioChannelLayoutTag_DVD_1: AudioChannelLayoutTag { 6619138 }
public var kAudioChannelLayoutTag_DVD_10: AudioChannelLayoutTag { 8912900 }
public var kAudioChannelLayoutTag_DVD_11: AudioChannelLayoutTag { 8978437 }
public var kAudioChannelLayoutTag_DVD_12: AudioChannelLayoutTag { 7929862 }
public var kAudioChannelLayoutTag_DVD_13: AudioChannelLayoutTag { 7536644 }
public var kAudioChannelLayoutTag_DVD_14: AudioChannelLayoutTag { 7667717 }
public var kAudioChannelLayoutTag_DVD_15: AudioChannelLayoutTag { 8912900 }
public var kAudioChannelLayoutTag_DVD_16: AudioChannelLayoutTag { 8978437 }
public var kAudioChannelLayoutTag_DVD_17: AudioChannelLayoutTag { 7929862 }
public var kAudioChannelLayoutTag_DVD_18: AudioChannelLayoutTag { 9043973 }
public var kAudioChannelLayoutTag_DVD_19: AudioChannelLayoutTag { 7733253 }
public var kAudioChannelLayoutTag_DVD_2: AudioChannelLayoutTag { 8585219 }
public var kAudioChannelLayoutTag_DVD_20: AudioChannelLayoutTag { 7995398 }
public var kAudioChannelLayoutTag_DVD_3: AudioChannelLayoutTag { 8650756 }
public var kAudioChannelLayoutTag_DVD_4: AudioChannelLayoutTag { 8716291 }
public var kAudioChannelLayoutTag_DVD_5: AudioChannelLayoutTag { 8781828 }
public var kAudioChannelLayoutTag_DVD_6: AudioChannelLayoutTag { 8847365 }
public var kAudioChannelLayoutTag_DVD_7: AudioChannelLayoutTag { 7405571 }
public var kAudioChannelLayoutTag_DVD_8: AudioChannelLayoutTag { 7536644 }
public var kAudioChannelLayoutTag_DVD_9: AudioChannelLayoutTag { 7667717 }
public var kAudioChannelLayoutTag_DiscreteInOrder: AudioChannelLayoutTag { 9633792 }
public var kAudioChannelLayoutTag_EAC3_6_1_A: AudioChannelLayoutTag { 10289159 }
public var kAudioChannelLayoutTag_EAC3_6_1_B: AudioChannelLayoutTag { 10354695 }
public var kAudioChannelLayoutTag_EAC3_6_1_C: AudioChannelLayoutTag { 10420231 }
public var kAudioChannelLayoutTag_EAC3_7_1_A: AudioChannelLayoutTag { 10485768 }
public var kAudioChannelLayoutTag_EAC3_7_1_B: AudioChannelLayoutTag { 10551304 }
public var kAudioChannelLayoutTag_EAC3_7_1_C: AudioChannelLayoutTag { 10616840 }
public var kAudioChannelLayoutTag_EAC3_7_1_D: AudioChannelLayoutTag { 10682376 }
public var kAudioChannelLayoutTag_EAC3_7_1_E: AudioChannelLayoutTag { 10747912 }
public var kAudioChannelLayoutTag_EAC3_7_1_F: AudioChannelLayoutTag { 10813448 }
public var kAudioChannelLayoutTag_EAC3_7_1_G: AudioChannelLayoutTag { 10878984 }
public var kAudioChannelLayoutTag_EAC3_7_1_H: AudioChannelLayoutTag { 10944520 }
public var kAudioChannelLayoutTag_EAC_6_0_A: AudioChannelLayoutTag { 10158086 }
public var kAudioChannelLayoutTag_EAC_7_0_A: AudioChannelLayoutTag { 10223623 }
public var kAudioChannelLayoutTag_Emagic_Default_7_1: AudioChannelLayoutTag { 8454152 }
public var kAudioChannelLayoutTag_EndReserved: AudioChannelLayoutTag { 4294901759 }
public var kAudioChannelLayoutTag_HOA_ACN_N3D: AudioChannelLayoutTag { 12517376 }
public var kAudioChannelLayoutTag_HOA_ACN_SN3D: AudioChannelLayoutTag { 12451840 }
public var kAudioChannelLayoutTag_Hexagonal: AudioChannelLayoutTag { 7208966 }
public var kAudioChannelLayoutTag_ITU_1_0: AudioChannelLayoutTag { 6553601 }
public var kAudioChannelLayoutTag_ITU_2_0: AudioChannelLayoutTag { 6619138 }
public var kAudioChannelLayoutTag_ITU_2_1: AudioChannelLayoutTag { 8585219 }
public var kAudioChannelLayoutTag_ITU_2_2: AudioChannelLayoutTag { 8650756 }
public var kAudioChannelLayoutTag_ITU_3_0: AudioChannelLayoutTag { 7405571 }
public var kAudioChannelLayoutTag_ITU_3_1: AudioChannelLayoutTag { 7536644 }
public var kAudioChannelLayoutTag_ITU_3_2: AudioChannelLayoutTag { 7667717 }
public var kAudioChannelLayoutTag_ITU_3_2_1: AudioChannelLayoutTag { 7929862 }
public var kAudioChannelLayoutTag_ITU_3_4_1: AudioChannelLayoutTag { 8388616 }
public var kAudioChannelLayoutTag_Logic_4_0_A: AudioChannelLayoutTag { 7536644 }
public var kAudioChannelLayoutTag_Logic_4_0_B: AudioChannelLayoutTag { 7602180 }
public var kAudioChannelLayoutTag_Logic_4_0_C: AudioChannelLayoutTag { 12910596 }
public var kAudioChannelLayoutTag_Logic_5_0_A: AudioChannelLayoutTag { 7667717 }
public var kAudioChannelLayoutTag_Logic_5_0_B: AudioChannelLayoutTag { 7733253 }
public var kAudioChannelLayoutTag_Logic_5_0_C: AudioChannelLayoutTag { 7798789 }
public var kAudioChannelLayoutTag_Logic_5_0_D: AudioChannelLayoutTag { 7864325 }
public var kAudioChannelLayoutTag_Logic_5_1_A: AudioChannelLayoutTag { 7929862 }
public var kAudioChannelLayoutTag_Logic_5_1_B: AudioChannelLayoutTag { 7995398 }
public var kAudioChannelLayoutTag_Logic_5_1_C: AudioChannelLayoutTag { 8060934 }
public var kAudioChannelLayoutTag_Logic_5_1_D: AudioChannelLayoutTag { 8126470 }
public var kAudioChannelLayoutTag_Logic_6_0_A: AudioChannelLayoutTag { 9240582 }
public var kAudioChannelLayoutTag_Logic_6_0_B: AudioChannelLayoutTag { 12976134 }
public var kAudioChannelLayoutTag_Logic_6_0_C: AudioChannelLayoutTag { 9109510 }
public var kAudioChannelLayoutTag_Logic_6_1_A: AudioChannelLayoutTag { 9306119 }
public var kAudioChannelLayoutTag_Logic_6_1_B: AudioChannelLayoutTag { 13041671 }
public var kAudioChannelLayoutTag_Logic_6_1_C: AudioChannelLayoutTag { 8192007 }
public var kAudioChannelLayoutTag_Logic_6_1_D: AudioChannelLayoutTag { 13107207 }
public var kAudioChannelLayoutTag_Logic_7_1_A: AudioChannelLayoutTag { 8388616 }
public var kAudioChannelLayoutTag_Logic_7_1_B: AudioChannelLayoutTag { 13172744 }
public var kAudioChannelLayoutTag_Logic_7_1_C: AudioChannelLayoutTag { 8388616 }
public var kAudioChannelLayoutTag_Logic_7_1_SDDS_A: AudioChannelLayoutTag { 8257544 }
public var kAudioChannelLayoutTag_Logic_7_1_SDDS_B: AudioChannelLayoutTag { 8323080 }
public var kAudioChannelLayoutTag_Logic_7_1_SDDS_C: AudioChannelLayoutTag { 8454152 }
public var kAudioChannelLayoutTag_Logic_Atmos_5_1_2: AudioChannelLayoutTag { 12713992 }
public var kAudioChannelLayoutTag_Logic_Atmos_5_1_4: AudioChannelLayoutTag { 12779530 }
public var kAudioChannelLayoutTag_Logic_Atmos_7_1_2: AudioChannelLayoutTag { 12845066 }
public var kAudioChannelLayoutTag_Logic_Atmos_7_1_4_A: AudioChannelLayoutTag { 12582924 }
public var kAudioChannelLayoutTag_Logic_Atmos_7_1_4_B: AudioChannelLayoutTag { 13238284 }
public var kAudioChannelLayoutTag_Logic_Atmos_7_1_6: AudioChannelLayoutTag { 13303822 }
public var kAudioChannelLayoutTag_Logic_Mono: AudioChannelLayoutTag { 6553601 }
public var kAudioChannelLayoutTag_Logic_Quadraphonic: AudioChannelLayoutTag { 7077892 }
public var kAudioChannelLayoutTag_Logic_Stereo: AudioChannelLayoutTag { 6619138 }
public var kAudioChannelLayoutTag_MPEG_1_0: AudioChannelLayoutTag { 6553601 }
public var kAudioChannelLayoutTag_MPEG_2_0: AudioChannelLayoutTag { 6619138 }
public var kAudioChannelLayoutTag_MPEG_3_0_A: AudioChannelLayoutTag { 7405571 }
public var kAudioChannelLayoutTag_MPEG_3_0_B: AudioChannelLayoutTag { 7471107 }
public var kAudioChannelLayoutTag_MPEG_4_0_A: AudioChannelLayoutTag { 7536644 }
public var kAudioChannelLayoutTag_MPEG_4_0_B: AudioChannelLayoutTag { 7602180 }
public var kAudioChannelLayoutTag_MPEG_5_0_A: AudioChannelLayoutTag { 7667717 }
public var kAudioChannelLayoutTag_MPEG_5_0_B: AudioChannelLayoutTag { 7733253 }
public var kAudioChannelLayoutTag_MPEG_5_0_C: AudioChannelLayoutTag { 7798789 }
public var kAudioChannelLayoutTag_MPEG_5_0_D: AudioChannelLayoutTag { 7864325 }
public var kAudioChannelLayoutTag_MPEG_5_0_E: AudioChannelLayoutTag { 14155781 }
public var kAudioChannelLayoutTag_MPEG_5_1_A: AudioChannelLayoutTag { 7929862 }
public var kAudioChannelLayoutTag_MPEG_5_1_B: AudioChannelLayoutTag { 7995398 }
public var kAudioChannelLayoutTag_MPEG_5_1_C: AudioChannelLayoutTag { 8060934 }
public var kAudioChannelLayoutTag_MPEG_5_1_D: AudioChannelLayoutTag { 8126470 }
public var kAudioChannelLayoutTag_MPEG_5_1_E: AudioChannelLayoutTag { 14221318 }
public var kAudioChannelLayoutTag_MPEG_6_1_A: AudioChannelLayoutTag { 8192007 }
public var kAudioChannelLayoutTag_MPEG_6_1_B: AudioChannelLayoutTag { 14286855 }
public var kAudioChannelLayoutTag_MPEG_7_1_A: AudioChannelLayoutTag { 8257544 }
public var kAudioChannelLayoutTag_MPEG_7_1_B: AudioChannelLayoutTag { 8323080 }
public var kAudioChannelLayoutTag_MPEG_7_1_C: AudioChannelLayoutTag { 8388616 }
public var kAudioChannelLayoutTag_MPEG_7_1_D: AudioChannelLayoutTag { 14352392 }
public var kAudioChannelLayoutTag_MatrixStereo: AudioChannelLayoutTag { 6750210 }
public var kAudioChannelLayoutTag_MidSide: AudioChannelLayoutTag { 6815746 }
public var kAudioChannelLayoutTag_Mono: AudioChannelLayoutTag { 6553601 }
public var kAudioChannelLayoutTag_Octagonal: AudioChannelLayoutTag { 7274504 }
public var kAudioChannelLayoutTag_Ogg_3_0: AudioChannelLayoutTag { 9830403 }
public var kAudioChannelLayoutTag_Ogg_4_0: AudioChannelLayoutTag { 12124164 }
public var kAudioChannelLayoutTag_Ogg_5_0: AudioChannelLayoutTag { 13893637 }
public var kAudioChannelLayoutTag_Ogg_5_1: AudioChannelLayoutTag { 13959174 }
public var kAudioChannelLayoutTag_Ogg_6_1: AudioChannelLayoutTag { 14024711 }
public var kAudioChannelLayoutTag_Ogg_7_1: AudioChannelLayoutTag { 14090248 }
public var kAudioChannelLayoutTag_Pentagonal: AudioChannelLayoutTag { 7143429 }
public var kAudioChannelLayoutTag_Quadraphonic: AudioChannelLayoutTag { 7077892 }
public var kAudioChannelLayoutTag_SMPTE_DTV: AudioChannelLayoutTag { 8519688 }
public var kAudioChannelLayoutTag_Stereo: AudioChannelLayoutTag { 6619138 }
public var kAudioChannelLayoutTag_StereoHeadphones: AudioChannelLayoutTag { 6684674 }
public var kAudioChannelLayoutTag_TMH_10_2_full: AudioChannelLayoutTag { 9568277 }
public var kAudioChannelLayoutTag_TMH_10_2_std: AudioChannelLayoutTag { 9502736 }
public var kAudioChannelLayoutTag_Unknown: AudioChannelLayoutTag { 4294901760 }
public var kAudioChannelLayoutTag_UseChannelBitmap: AudioChannelLayoutTag { 65536 }
public var kAudioChannelLayoutTag_UseChannelDescriptions: AudioChannelLayoutTag { 0 }
public var kAudioChannelLayoutTag_WAVE_2_1: AudioChannelLayoutTag { 8716291 }
public var kAudioChannelLayoutTag_WAVE_3_0: AudioChannelLayoutTag { 7405571 }
public var kAudioChannelLayoutTag_WAVE_4_0_A: AudioChannelLayoutTag { 8650756 }
public var kAudioChannelLayoutTag_WAVE_4_0_B: AudioChannelLayoutTag { 12124164 }
public var kAudioChannelLayoutTag_WAVE_5_0_A: AudioChannelLayoutTag { 7667717 }
public var kAudioChannelLayoutTag_WAVE_5_0_B: AudioChannelLayoutTag { 12189701 }
public var kAudioChannelLayoutTag_WAVE_5_1_A: AudioChannelLayoutTag { 7929862 }
public var kAudioChannelLayoutTag_WAVE_5_1_B: AudioChannelLayoutTag { 12255238 }
public var kAudioChannelLayoutTag_WAVE_6_1: AudioChannelLayoutTag { 12320775 }
public var kAudioChannelLayoutTag_WAVE_7_1: AudioChannelLayoutTag { 12386312 }
public var kAudioChannelLayoutTag_XY: AudioChannelLayoutTag { 6881282 }

public var kAudioFormatDVIIntelIMA: AudioFormatID { 1836253201 }
public var kAudioFormatMicrosoftGSM: AudioFormatID { 1836253233 }
public var kAudioFormatLinearPCM: AudioFormatID { 1819304813 }
public var kAudioFormatAC3: AudioFormatID { 1633889587 }
public var kAudioFormat60958AC3: AudioFormatID { 1667326771 }
public var kAudioFormatAppleIMA4: AudioFormatID { 1768775988 }
public var kAudioFormatMPEG4AAC: AudioFormatID { 1633772320 }
public var kAudioFormatMPEG4CELP: AudioFormatID { 1667591280 }
public var kAudioFormatMPEG4HVXC: AudioFormatID { 1752594531 }
public var kAudioFormatMPEG4TwinVQ: AudioFormatID { 1953986161 }
public var kAudioFormatMACE3: AudioFormatID { 1296122675 }
public var kAudioFormatMACE6: AudioFormatID { 1296122678 }
public var kAudioFormatULaw: AudioFormatID { 1970037111 }
public var kAudioFormatALaw: AudioFormatID { 1634492791 }
public var kAudioFormatQDesign: AudioFormatID { 1363430723 }
public var kAudioFormatQDesign2: AudioFormatID { 1363430706 }
public var kAudioFormatQUALCOMM: AudioFormatID { 1365470320 }
public var kAudioFormatMPEGLayer1: AudioFormatID { 778924081 }
public var kAudioFormatMPEGLayer2: AudioFormatID { 778924082 }
public var kAudioFormatMPEGLayer3: AudioFormatID { 778924083 }
public var kAudioFormatTimeCode: AudioFormatID { 1953066341 }
public var kAudioFormatMIDIStream: AudioFormatID { 1835623529 }
public var kAudioFormatParameterValueStream: AudioFormatID { 1634760307 }
public var kAudioFormatAppleLossless: AudioFormatID { 1634492771 }
public var kAudioFormatMPEG4AAC_HE: AudioFormatID { 1633772392 }
public var kAudioFormatMPEG4AAC_LD: AudioFormatID { 1633772396 }
public var kAudioFormatMPEG4AAC_ELD: AudioFormatID { 1633772389 }
public var kAudioFormatMPEG4AAC_ELD_SBR: AudioFormatID { 1633772390 }
public var kAudioFormatMPEG4AAC_ELD_V2: AudioFormatID { 1633772391 }
public var kAudioFormatMPEG4AAC_HE_V2: AudioFormatID { 1633772400 }
public var kAudioFormatMPEG4AAC_Spatial: AudioFormatID { 1633772403 }
public var kAudioFormatMPEGD_USAC: AudioFormatID { 1970495843 }
public var kAudioFormatAMR: AudioFormatID { 1935764850 }
public var kAudioFormatAMR_WB: AudioFormatID { 1935767394 }
public var kAudioFormatAudible: AudioFormatID { 1096107074 }
public var kAudioFormatiLBC: AudioFormatID { 1768710755 }
public var kAudioFormatAES3: AudioFormatID { 1634038579 }
public var kAudioFormatEnhancedAC3: AudioFormatID { 1700998451 }
public var kAudioFormatFLAC: AudioFormatID { 1718378851 }
public var kAudioFormatOpus: AudioFormatID { 1869641075 }
public var kAudioFormatAPAC: AudioFormatID { 1634754915 }

public var kAudioFormatFlagIsFloat: AudioFormatFlags { 1 }
public var kAudioFormatFlagIsBigEndian: AudioFormatFlags { 2 }
public var kAudioFormatFlagIsSignedInteger: AudioFormatFlags { 4 }
public var kAudioFormatFlagIsPacked: AudioFormatFlags { 8 }
public var kAudioFormatFlagIsAlignedHigh: AudioFormatFlags { 16 }
public var kAudioFormatFlagIsNonInterleaved: AudioFormatFlags { 32 }
public var kAudioFormatFlagIsNonMixable: AudioFormatFlags { 64 }
public var kAudioFormatFlagsAreAllClear: AudioFormatFlags { 2147483648 }
public var kLinearPCMFormatFlagIsFloat: AudioFormatFlags { 1 }
public var kLinearPCMFormatFlagIsBigEndian: AudioFormatFlags { 2 }
public var kLinearPCMFormatFlagIsSignedInteger: AudioFormatFlags { 4 }
public var kLinearPCMFormatFlagIsPacked: AudioFormatFlags { 8 }
public var kLinearPCMFormatFlagIsAlignedHigh: AudioFormatFlags { 16 }
public var kLinearPCMFormatFlagIsNonInterleaved: AudioFormatFlags { 32 }
public var kLinearPCMFormatFlagIsNonMixable: AudioFormatFlags { 64 }
public var kLinearPCMFormatFlagsAreAllClear: AudioFormatFlags { 2147483648 }
public var kLinearPCMFormatFlagsSampleFractionShift: AudioFormatFlags { 7 }
public var kLinearPCMFormatFlagsSampleFractionMask: AudioFormatFlags { 8064 }
public var kAudioFormatFlagsNativeEndian: AudioFormatFlags { 0 }
public var kAudioFormatFlagsNativeFloatPacked: AudioFormatFlags { 9 }
public var kAudioFormatFlagsCanonical: AudioFormatFlags { 12 }
public var kAudioFormatFlagsAudioUnitCanonical: AudioFormatFlags { 3116 }

public let kAudioStreamAnyRate: Float64 = 0.0
public var kAudioUnitSampleFractionBits: Int32 { 24 }

public var kAudio_NoError: OSStatus { 0 }
public var kAudio_UnimplementedError: OSStatus { -4 }
public var kAudio_FileNotFoundError: OSStatus { -43 }
public var kAudio_FilePermissionError: OSStatus { -54 }
public var kAudio_TooManyFilesOpenError: OSStatus { -42 }
public var kAudio_ParamError: OSStatus { -50 }
public var kAudio_MemFullError: OSStatus { -108 }
public var kAudio_BadFilePathError: OSStatus { 561017960 }

public var AVAudioSessionErrorInsufficientPriority: Int { 561017449 }
