import Foundation
import AVFoundation

func testAVCaptureEnumRawValues() {
    precondition(AVCaptureCameraLensSmudgeDetectionStatus.disabled.rawValue == 0)
    precondition(AVCaptureCameraLensSmudgeDetectionStatus(rawValue: 0) == .disabled)
    precondition(AVCaptureCameraLensSmudgeDetectionStatus.smudgeNotDetected.rawValue == 1)
    precondition(AVCaptureCameraLensSmudgeDetectionStatus(rawValue: 1) == .smudgeNotDetected)
    precondition(AVCaptureCameraLensSmudgeDetectionStatus.smudged.rawValue == 2)
    precondition(AVCaptureCameraLensSmudgeDetectionStatus(rawValue: 2) == .smudged)
    precondition(AVCaptureCameraLensSmudgeDetectionStatus.unknown.rawValue == 3)
    precondition(AVCaptureCameraLensSmudgeDetectionStatus(rawValue: 3) == .unknown)
    precondition(AVCaptureColorSpace.HLG_BT2020.rawValue == 2)
    precondition(AVCaptureColorSpace(rawValue: 2) == .HLG_BT2020)
    precondition(AVCaptureColorSpace.P3_D65.rawValue == 1)
    precondition(AVCaptureColorSpace(rawValue: 1) == .P3_D65)
    precondition(AVCaptureColorSpace.appleLog.rawValue == 3)
    precondition(AVCaptureColorSpace(rawValue: 3) == .appleLog)
    precondition(AVCaptureColorSpace.appleLog2.rawValue == 4)
    precondition(AVCaptureColorSpace(rawValue: 4) == .appleLog2)
    precondition(AVCaptureColorSpace.sRGB.rawValue == 0)
    precondition(AVCaptureColorSpace(rawValue: 0) == .sRGB)
    precondition(AVCaptureDevice.AutoFocusRangeRestriction.far.rawValue == 2)
    precondition(AVCaptureDevice.AutoFocusRangeRestriction(rawValue: 2) == .far)
    precondition(AVCaptureDevice.AutoFocusRangeRestriction.near.rawValue == 1)
    precondition(AVCaptureDevice.AutoFocusRangeRestriction(rawValue: 1) == .near)
    precondition(AVCaptureDevice.AutoFocusRangeRestriction.none.rawValue == 0)
    precondition(AVCaptureDevice.AutoFocusRangeRestriction(rawValue: 0) == .none)
    precondition(AVCaptureDevice.CenterStageControlMode.app.rawValue == 1)
    precondition(AVCaptureDevice.CenterStageControlMode(rawValue: 1) == .app)
    precondition(AVCaptureDevice.CenterStageControlMode.cooperative.rawValue == 2)
    precondition(AVCaptureDevice.CenterStageControlMode(rawValue: 2) == .cooperative)
    precondition(AVCaptureDevice.CenterStageControlMode.user.rawValue == 0)
    precondition(AVCaptureDevice.CenterStageControlMode(rawValue: 0) == .user)
    precondition(AVCaptureDevice.CinematicVideoFocusMode.none.rawValue == 0)
    precondition(AVCaptureDevice.CinematicVideoFocusMode(rawValue: 0) == .none)
    precondition(AVCaptureDevice.CinematicVideoFocusMode.strong.rawValue == 1)
    precondition(AVCaptureDevice.CinematicVideoFocusMode(rawValue: 1) == .strong)
    precondition(AVCaptureDevice.CinematicVideoFocusMode.weak.rawValue == 2)
    precondition(AVCaptureDevice.CinematicVideoFocusMode(rawValue: 2) == .weak)
    precondition(AVCaptureDevice.ExposureMode.autoExpose.rawValue == 1)
    precondition(AVCaptureDevice.ExposureMode(rawValue: 1) == .autoExpose)
    precondition(AVCaptureDevice.ExposureMode.continuousAutoExposure.rawValue == 2)
    precondition(AVCaptureDevice.ExposureMode(rawValue: 2) == .continuousAutoExposure)
    precondition(AVCaptureDevice.ExposureMode.custom.rawValue == 3)
    precondition(AVCaptureDevice.ExposureMode(rawValue: 3) == .custom)
    precondition(AVCaptureDevice.ExposureMode.locked.rawValue == 0)
    precondition(AVCaptureDevice.ExposureMode(rawValue: 0) == .locked)
    precondition(AVCaptureDevice.FlashMode.auto.rawValue == 2)
    precondition(AVCaptureDevice.FlashMode(rawValue: 2) == .auto)
    precondition(AVCaptureDevice.FlashMode.off.rawValue == 0)
    precondition(AVCaptureDevice.FlashMode(rawValue: 0) == .off)
    precondition(AVCaptureDevice.FlashMode.on.rawValue == 1)
    precondition(AVCaptureDevice.FlashMode(rawValue: 1) == .on)
    precondition(AVCaptureDevice.FocusMode.autoFocus.rawValue == 1)
    precondition(AVCaptureDevice.FocusMode(rawValue: 1) == .autoFocus)
    precondition(AVCaptureDevice.FocusMode.continuousAutoFocus.rawValue == 2)
    precondition(AVCaptureDevice.FocusMode(rawValue: 2) == .continuousAutoFocus)
    precondition(AVCaptureDevice.FocusMode.locked.rawValue == 0)
    precondition(AVCaptureDevice.FocusMode(rawValue: 0) == .locked)
    precondition(AVCaptureDevice.Format.AutoFocusSystem.contrastDetection.rawValue == 1)
    precondition(AVCaptureDevice.Format.AutoFocusSystem(rawValue: 1) == .contrastDetection)
    precondition(AVCaptureDevice.Format.AutoFocusSystem.none.rawValue == 0)
    precondition(AVCaptureDevice.Format.AutoFocusSystem(rawValue: 0) == .none)
    precondition(AVCaptureDevice.Format.AutoFocusSystem.phaseDetection.rawValue == 2)
    precondition(AVCaptureDevice.Format.AutoFocusSystem(rawValue: 2) == .phaseDetection)
    precondition(AVCaptureDevice.LensStabilizationStatus.active.rawValue == 2)
    precondition(AVCaptureDevice.LensStabilizationStatus(rawValue: 2) == .active)
    precondition(AVCaptureDevice.LensStabilizationStatus.off.rawValue == 1)
    precondition(AVCaptureDevice.LensStabilizationStatus(rawValue: 1) == .off)
    precondition(AVCaptureDevice.LensStabilizationStatus.outOfRange.rawValue == 3)
    precondition(AVCaptureDevice.LensStabilizationStatus(rawValue: 3) == .outOfRange)
    precondition(AVCaptureDevice.LensStabilizationStatus.unavailable.rawValue == 4)
    precondition(AVCaptureDevice.LensStabilizationStatus(rawValue: 4) == .unavailable)
    precondition(AVCaptureDevice.LensStabilizationStatus.unsupported.rawValue == 0)
    precondition(AVCaptureDevice.LensStabilizationStatus(rawValue: 0) == .unsupported)
    precondition(AVCaptureDevice.MicrophoneMode.standard.rawValue == 0)
    precondition(AVCaptureDevice.MicrophoneMode(rawValue: 0) == .standard)
    precondition(AVCaptureDevice.MicrophoneMode.voiceIsolation.rawValue == 2)
    precondition(AVCaptureDevice.MicrophoneMode(rawValue: 2) == .voiceIsolation)
    precondition(AVCaptureDevice.MicrophoneMode.wideSpectrum.rawValue == 1)
    precondition(AVCaptureDevice.MicrophoneMode(rawValue: 1) == .wideSpectrum)
    precondition(AVCaptureDevice.Position.back.rawValue == 1)
    precondition(AVCaptureDevice.Position(rawValue: 1) == .back)
    precondition(AVCaptureDevice.Position.front.rawValue == 2)
    precondition(AVCaptureDevice.Position(rawValue: 2) == .front)
    precondition(AVCaptureDevice.Position.unspecified.rawValue == 0)
    precondition(AVCaptureDevice.Position(rawValue: 0) == .unspecified)
    precondition(AVCaptureDevice.PrimaryConstituentDeviceSwitchingBehavior.auto.rawValue == 1)
    precondition(AVCaptureDevice.PrimaryConstituentDeviceSwitchingBehavior(rawValue: 1) == .auto)
    precondition(AVCaptureDevice.PrimaryConstituentDeviceSwitchingBehavior.locked.rawValue == 3)
    precondition(AVCaptureDevice.PrimaryConstituentDeviceSwitchingBehavior(rawValue: 3) == .locked)
    precondition(AVCaptureDevice.PrimaryConstituentDeviceSwitchingBehavior.restricted.rawValue == 2)
    precondition(AVCaptureDevice.PrimaryConstituentDeviceSwitchingBehavior(rawValue: 2) == .restricted)
    precondition(AVCaptureDevice.PrimaryConstituentDeviceSwitchingBehavior.unsupported.rawValue == 0)
    precondition(AVCaptureDevice.PrimaryConstituentDeviceSwitchingBehavior(rawValue: 0) == .unsupported)
    precondition(AVCaptureDevice.SystemUserInterface.microphoneModes.rawValue == 1)
    precondition(AVCaptureDevice.SystemUserInterface(rawValue: 1) == .microphoneModes)
    precondition(AVCaptureDevice.SystemUserInterface.videoEffects.rawValue == 0)
    precondition(AVCaptureDevice.SystemUserInterface(rawValue: 0) == .videoEffects)
    precondition(AVCaptureDevice.TorchMode.auto.rawValue == 2)
    precondition(AVCaptureDevice.TorchMode(rawValue: 2) == .auto)
    precondition(AVCaptureDevice.TorchMode.off.rawValue == 0)
    precondition(AVCaptureDevice.TorchMode(rawValue: 0) == .off)
    precondition(AVCaptureDevice.TorchMode.on.rawValue == 1)
    precondition(AVCaptureDevice.TorchMode(rawValue: 1) == .on)
    precondition(AVCaptureDevice.WhiteBalanceMode.autoWhiteBalance.rawValue == 1)
    precondition(AVCaptureDevice.WhiteBalanceMode(rawValue: 1) == .autoWhiteBalance)
    precondition(AVCaptureDevice.WhiteBalanceMode.continuousAutoWhiteBalance.rawValue == 2)
    precondition(AVCaptureDevice.WhiteBalanceMode(rawValue: 2) == .continuousAutoWhiteBalance)
    precondition(AVCaptureDevice.WhiteBalanceMode.locked.rawValue == 0)
    precondition(AVCaptureDevice.WhiteBalanceMode(rawValue: 0) == .locked)
    precondition(AVCaptureMultichannelAudioMode.firstOrderAmbisonics.rawValue == 2)
    precondition(AVCaptureMultichannelAudioMode(rawValue: 2) == .firstOrderAmbisonics)
    precondition(AVCaptureMultichannelAudioMode.none.rawValue == 0)
    precondition(AVCaptureMultichannelAudioMode(rawValue: 0) == .none)
    precondition(AVCaptureMultichannelAudioMode.stereo.rawValue == 1)
    precondition(AVCaptureMultichannelAudioMode(rawValue: 1) == .stereo)
    precondition(AVCaptureOutput.DataDroppedReason.discontinuity.rawValue == 3)
    precondition(AVCaptureOutput.DataDroppedReason(rawValue: 3) == .discontinuity)
    precondition(AVCaptureOutput.DataDroppedReason.lateData.rawValue == 1)
    precondition(AVCaptureOutput.DataDroppedReason(rawValue: 1) == .lateData)
    precondition(AVCaptureOutput.DataDroppedReason.none.rawValue == 0)
    precondition(AVCaptureOutput.DataDroppedReason(rawValue: 0) == .none)
    precondition(AVCaptureOutput.DataDroppedReason.outOfBuffers.rawValue == 2)
    precondition(AVCaptureOutput.DataDroppedReason(rawValue: 2) == .outOfBuffers)
    precondition(AVCapturePhotoOutput.CaptureReadiness.notReadyMomentarily.rawValue == 2)
    precondition(AVCapturePhotoOutput.CaptureReadiness(rawValue: 2) == .notReadyMomentarily)
    precondition(AVCapturePhotoOutput.CaptureReadiness.notReadyWaitingForCapture.rawValue == 3)
    precondition(AVCapturePhotoOutput.CaptureReadiness(rawValue: 3) == .notReadyWaitingForCapture)
    precondition(AVCapturePhotoOutput.CaptureReadiness.notReadyWaitingForProcessing.rawValue == 4)
    precondition(AVCapturePhotoOutput.CaptureReadiness(rawValue: 4) == .notReadyWaitingForProcessing)
    precondition(AVCapturePhotoOutput.CaptureReadiness.ready.rawValue == 1)
    precondition(AVCapturePhotoOutput.CaptureReadiness(rawValue: 1) == .ready)
    precondition(AVCapturePhotoOutput.CaptureReadiness.sessionNotRunning.rawValue == 0)
    precondition(AVCapturePhotoOutput.CaptureReadiness(rawValue: 0) == .sessionNotRunning)
    precondition(AVCapturePhotoOutput.QualityPrioritization.balanced.rawValue == 1)
    precondition(AVCapturePhotoOutput.QualityPrioritization(rawValue: 1) == .balanced)
    precondition(AVCapturePhotoOutput.QualityPrioritization.quality.rawValue == 2)
    precondition(AVCapturePhotoOutput.QualityPrioritization(rawValue: 2) == .quality)
    precondition(AVCapturePhotoOutput.QualityPrioritization.speed.rawValue == 0)
    precondition(AVCapturePhotoOutput.QualityPrioritization(rawValue: 0) == .speed)
    precondition(AVCaptureSession.InterruptionReason.audioDeviceInUseByAnotherClient.rawValue == 1)
    precondition(AVCaptureSession.InterruptionReason(rawValue: 1) == .audioDeviceInUseByAnotherClient)
    precondition(AVCaptureSession.InterruptionReason.sensitiveContentMitigationActivated.rawValue == 5)
    precondition(AVCaptureSession.InterruptionReason(rawValue: 5) == .sensitiveContentMitigationActivated)
    precondition(AVCaptureSession.InterruptionReason.videoDeviceInUseByAnotherClient.rawValue == 2)
    precondition(AVCaptureSession.InterruptionReason(rawValue: 2) == .videoDeviceInUseByAnotherClient)
    precondition(AVCaptureSession.InterruptionReason.videoDeviceNotAvailableDueToSystemPressure.rawValue == 4)
    precondition(AVCaptureSession.InterruptionReason(rawValue: 4) == .videoDeviceNotAvailableDueToSystemPressure)
    precondition(AVCaptureSession.InterruptionReason.videoDeviceNotAvailableInBackground.rawValue == 0)
    precondition(AVCaptureSession.InterruptionReason(rawValue: 0) == .videoDeviceNotAvailableInBackground)
    precondition(AVCaptureSession.InterruptionReason.videoDeviceNotAvailableWithMultipleForegroundApps.rawValue == 3)
    precondition(AVCaptureSession.InterruptionReason(rawValue: 3) == .videoDeviceNotAvailableWithMultipleForegroundApps)
    precondition(AVCaptureTimecode.SourceType.external.rawValue == 2)
    precondition(AVCaptureTimecode.SourceType(rawValue: 2) == .external)
    precondition(AVCaptureTimecode.SourceType.frameCount.rawValue == 0)
    precondition(AVCaptureTimecode.SourceType(rawValue: 0) == .frameCount)
    precondition(AVCaptureTimecode.SourceType.realTimeClock.rawValue == 1)
    precondition(AVCaptureTimecode.SourceType(rawValue: 1) == .realTimeClock)
    precondition(AVCaptureTimecodeGenerator.SynchronizationStatus.notRequired.rawValue == 7)
    precondition(AVCaptureTimecodeGenerator.SynchronizationStatus(rawValue: 7) == .notRequired)
    precondition(AVCaptureTimecodeGenerator.SynchronizationStatus.sourceSelected.rawValue == 1)
    precondition(AVCaptureTimecodeGenerator.SynchronizationStatus(rawValue: 1) == .sourceSelected)
    precondition(AVCaptureTimecodeGenerator.SynchronizationStatus.sourceUnavailable.rawValue == 5)
    precondition(AVCaptureTimecodeGenerator.SynchronizationStatus(rawValue: 5) == .sourceUnavailable)
    precondition(AVCaptureTimecodeGenerator.SynchronizationStatus.sourceUnsupported.rawValue == 6)
    precondition(AVCaptureTimecodeGenerator.SynchronizationStatus(rawValue: 6) == .sourceUnsupported)
    precondition(AVCaptureTimecodeGenerator.SynchronizationStatus.synchronized.rawValue == 3)
    precondition(AVCaptureTimecodeGenerator.SynchronizationStatus(rawValue: 3) == .synchronized)
    precondition(AVCaptureTimecodeGenerator.SynchronizationStatus.synchronizing.rawValue == 2)
    precondition(AVCaptureTimecodeGenerator.SynchronizationStatus(rawValue: 2) == .synchronizing)
    precondition(AVCaptureTimecodeGenerator.SynchronizationStatus.timedOut.rawValue == 4)
    precondition(AVCaptureTimecodeGenerator.SynchronizationStatus(rawValue: 4) == .timedOut)
    precondition(AVCaptureTimecodeGenerator.SynchronizationStatus.unknown.rawValue == 0)
    precondition(AVCaptureTimecodeGenerator.SynchronizationStatus(rawValue: 0) == .unknown)
    precondition(AVCaptureVideoOrientation.landscapeLeft.rawValue == 3)
    precondition(AVCaptureVideoOrientation(rawValue: 3) == .landscapeLeft)
    precondition(AVCaptureVideoOrientation.landscapeRight.rawValue == 2)
    precondition(AVCaptureVideoOrientation(rawValue: 2) == .landscapeRight)
    precondition(AVCaptureVideoOrientation.portrait.rawValue == 0)
    precondition(AVCaptureVideoOrientation(rawValue: 0) == .portrait)
    precondition(AVCaptureVideoOrientation.portraitUpsideDown.rawValue == 1)
    precondition(AVCaptureVideoOrientation(rawValue: 1) == .portraitUpsideDown)
    precondition(AVCaptureVideoStabilizationMode.auto.rawValue == 7)
    precondition(AVCaptureVideoStabilizationMode(rawValue: 7) == .auto)
    precondition(AVCaptureVideoStabilizationMode.cinematic.rawValue == 2)
    precondition(AVCaptureVideoStabilizationMode(rawValue: 2) == .cinematic)
    precondition(AVCaptureVideoStabilizationMode.cinematicExtended.rawValue == 3)
    precondition(AVCaptureVideoStabilizationMode(rawValue: 3) == .cinematicExtended)
    precondition(AVCaptureVideoStabilizationMode.cinematicExtendedEnhanced.rawValue == 5)
    precondition(AVCaptureVideoStabilizationMode(rawValue: 5) == .cinematicExtendedEnhanced)
    precondition(AVCaptureVideoStabilizationMode.lowLatency.rawValue == 6)
    precondition(AVCaptureVideoStabilizationMode(rawValue: 6) == .lowLatency)
    precondition(AVCaptureVideoStabilizationMode.off.rawValue == 0)
    precondition(AVCaptureVideoStabilizationMode(rawValue: 0) == .off)
    precondition(AVCaptureVideoStabilizationMode.previewOptimized.rawValue == 4)
    precondition(AVCaptureVideoStabilizationMode(rawValue: 4) == .previewOptimized)
    precondition(AVCaptureVideoStabilizationMode.standard.rawValue == 1)
    precondition(AVCaptureVideoStabilizationMode(rawValue: 1) == .standard)
    precondition(AVDepthData.Accuracy.absolute.rawValue == 1)
    precondition(AVDepthData.Accuracy(rawValue: 1) == .absolute)
    precondition(AVDepthData.Accuracy.relative.rawValue == 0)
    precondition(AVDepthData.Accuracy(rawValue: 0) == .relative)
    precondition(AVDepthData.Quality.high.rawValue == 1)
    precondition(AVDepthData.Quality(rawValue: 1) == .high)
    precondition(AVDepthData.Quality.low.rawValue == 0)
    precondition(AVDepthData.Quality(rawValue: 0) == .low)
    precondition(AVAuthorizationStatus.notDetermined.rawValue == 0)
    precondition(AVAuthorizationStatus(rawValue: 0) == .notDetermined)
    precondition(AVAuthorizationStatus.restricted.rawValue == 1)
    precondition(AVAuthorizationStatus(rawValue: 1) == .restricted)
    precondition(AVAuthorizationStatus.denied.rawValue == 2)
    precondition(AVAuthorizationStatus(rawValue: 2) == .denied)
    precondition(AVAuthorizationStatus.authorized.rawValue == 3)
    precondition(AVAuthorizationStatus(rawValue: 3) == .authorized)
}

func testAVCaptureDeviceTypeAndPresetRawValues() {
    precondition(AVCaptureDevice.AspectRatio.ratio1x1.rawValue == "ratio1x1")
    precondition(AVCaptureDevice.AspectRatio(rawValue: "ratio1x1") == .ratio1x1)
    precondition(AVCaptureDevice.AspectRatio.ratio16x9.rawValue == "ratio16x9")
    precondition(AVCaptureDevice.AspectRatio(rawValue: "ratio16x9") == .ratio16x9)
    precondition(AVCaptureDevice.AspectRatio.ratio9x16.rawValue == "ratio9x16")
    precondition(AVCaptureDevice.AspectRatio(rawValue: "ratio9x16") == .ratio9x16)
    precondition(AVCaptureDevice.AspectRatio.ratio4x3.rawValue == "ratio4x3")
    precondition(AVCaptureDevice.AspectRatio(rawValue: "ratio4x3") == .ratio4x3)
    precondition(AVCaptureDevice.AspectRatio.ratio3x4.rawValue == "ratio3x4")
    precondition(AVCaptureDevice.AspectRatio(rawValue: "ratio3x4") == .ratio3x4)
    precondition(AVCaptureDevice.DeviceType.external.rawValue == "external")
    precondition(AVCaptureDevice.DeviceType(rawValue: "external") == .external)
    precondition(AVCaptureDevice.DeviceType.microphone.rawValue == "microphone")
    precondition(AVCaptureDevice.DeviceType(rawValue: "microphone") == .microphone)
    precondition(AVCaptureDevice.DeviceType.builtInWideAngleCamera.rawValue == "builtInWideAngleCamera")
    precondition(AVCaptureDevice.DeviceType(rawValue: "builtInWideAngleCamera") == .builtInWideAngleCamera)
    precondition(AVCaptureDevice.DeviceType.builtInTelephotoCamera.rawValue == "builtInTelephotoCamera")
    precondition(AVCaptureDevice.DeviceType(rawValue: "builtInTelephotoCamera") == .builtInTelephotoCamera)
    precondition(AVCaptureDevice.DeviceType.builtInUltraWideCamera.rawValue == "builtInUltraWideCamera")
    precondition(AVCaptureDevice.DeviceType(rawValue: "builtInUltraWideCamera") == .builtInUltraWideCamera)
    precondition(AVCaptureDevice.DeviceType.builtInDualCamera.rawValue == "builtInDualCamera")
    precondition(AVCaptureDevice.DeviceType(rawValue: "builtInDualCamera") == .builtInDualCamera)
    precondition(AVCaptureDevice.DeviceType.builtInDualWideCamera.rawValue == "builtInDualWideCamera")
    precondition(AVCaptureDevice.DeviceType(rawValue: "builtInDualWideCamera") == .builtInDualWideCamera)
    precondition(AVCaptureDevice.DeviceType.builtInTripleCamera.rawValue == "builtInTripleCamera")
    precondition(AVCaptureDevice.DeviceType(rawValue: "builtInTripleCamera") == .builtInTripleCamera)
    precondition(AVCaptureDevice.DeviceType.builtInTrueDepthCamera.rawValue == "builtInTrueDepthCamera")
    precondition(AVCaptureDevice.DeviceType(rawValue: "builtInTrueDepthCamera") == .builtInTrueDepthCamera)
    precondition(AVCaptureDevice.DeviceType.builtInLiDARDepthCamera.rawValue == "builtInLiDARDepthCamera")
    precondition(AVCaptureDevice.DeviceType(rawValue: "builtInLiDARDepthCamera") == .builtInLiDARDepthCamera)
    precondition(AVCaptureDevice.DeviceType.continuityCamera.rawValue == "continuityCamera")
    precondition(AVCaptureDevice.DeviceType(rawValue: "continuityCamera") == .continuityCamera)
    precondition(AVCaptureDevice.DeviceType.builtInDuoCamera.rawValue == "builtInDuoCamera")
    precondition(AVCaptureDevice.DeviceType(rawValue: "builtInDuoCamera") == .builtInDuoCamera)
    precondition(AVCaptureDevice.DeviceType.builtInMicrophone.rawValue == "builtInMicrophone")
    precondition(AVCaptureDevice.DeviceType(rawValue: "builtInMicrophone") == .builtInMicrophone)
    precondition(AVCaptureDevice.SystemPressureState.Level.nominal.rawValue == "nominal")
    precondition(AVCaptureDevice.SystemPressureState.Level(rawValue: "nominal") == .nominal)
    precondition(AVCaptureDevice.SystemPressureState.Level.fair.rawValue == "fair")
    precondition(AVCaptureDevice.SystemPressureState.Level(rawValue: "fair") == .fair)
    precondition(AVCaptureDevice.SystemPressureState.Level.serious.rawValue == "serious")
    precondition(AVCaptureDevice.SystemPressureState.Level(rawValue: "serious") == .serious)
    precondition(AVCaptureDevice.SystemPressureState.Level.critical.rawValue == "critical")
    precondition(AVCaptureDevice.SystemPressureState.Level(rawValue: "critical") == .critical)
    precondition(AVCaptureDevice.SystemPressureState.Level.shutdown.rawValue == "shutdown")
    precondition(AVCaptureDevice.SystemPressureState.Level(rawValue: "shutdown") == .shutdown)
    precondition(AVCaptureReactionType.thumbsUp.rawValue == "thumbsUp")
    precondition(AVCaptureReactionType(rawValue: "thumbsUp") == .thumbsUp)
    precondition(AVCaptureReactionType.thumbsDown.rawValue == "thumbsDown")
    precondition(AVCaptureReactionType(rawValue: "thumbsDown") == .thumbsDown)
    precondition(AVCaptureReactionType.balloons.rawValue == "balloons")
    precondition(AVCaptureReactionType(rawValue: "balloons") == .balloons)
    precondition(AVCaptureReactionType.heart.rawValue == "heart")
    precondition(AVCaptureReactionType(rawValue: "heart") == .heart)
    precondition(AVCaptureReactionType.fireworks.rawValue == "fireworks")
    precondition(AVCaptureReactionType(rawValue: "fireworks") == .fireworks)
    precondition(AVCaptureReactionType.rain.rawValue == "rain")
    precondition(AVCaptureReactionType(rawValue: "rain") == .rain)
    precondition(AVCaptureReactionType.confetti.rawValue == "confetti")
    precondition(AVCaptureReactionType(rawValue: "confetti") == .confetti)
    precondition(AVCaptureReactionType.lasers.rawValue == "lasers")
    precondition(AVCaptureReactionType(rawValue: "lasers") == .lasers)
    precondition(AVCaptureSceneMonitoringStatus.notEnoughLight.rawValue == "notEnoughLight")
    precondition(AVCaptureSceneMonitoringStatus(rawValue: "notEnoughLight") == .notEnoughLight)
    precondition(AVCaptureSession.Preset.photo.rawValue == "photo")
    precondition(AVCaptureSession.Preset(rawValue: "photo") == .photo)
    precondition(AVCaptureSession.Preset.high.rawValue == "high")
    precondition(AVCaptureSession.Preset(rawValue: "high") == .high)
    precondition(AVCaptureSession.Preset.medium.rawValue == "medium")
    precondition(AVCaptureSession.Preset(rawValue: "medium") == .medium)
    precondition(AVCaptureSession.Preset.low.rawValue == "low")
    precondition(AVCaptureSession.Preset(rawValue: "low") == .low)
    precondition(AVCaptureSession.Preset.cif352x288.rawValue == "cif352x288")
    precondition(AVCaptureSession.Preset(rawValue: "cif352x288") == .cif352x288)
    precondition(AVCaptureSession.Preset.vga640x480.rawValue == "vga640x480")
    precondition(AVCaptureSession.Preset(rawValue: "vga640x480") == .vga640x480)
    precondition(AVCaptureSession.Preset.hd1280x720.rawValue == "hd1280x720")
    precondition(AVCaptureSession.Preset(rawValue: "hd1280x720") == .hd1280x720)
    precondition(AVCaptureSession.Preset.hd1920x1080.rawValue == "hd1920x1080")
    precondition(AVCaptureSession.Preset(rawValue: "hd1920x1080") == .hd1920x1080)
    precondition(AVCaptureSession.Preset.hd4K3840x2160.rawValue == "hd4K3840x2160")
    precondition(AVCaptureSession.Preset(rawValue: "hd4K3840x2160") == .hd4K3840x2160)
    precondition(AVCaptureSession.Preset.iFrame960x540.rawValue == "iFrame960x540")
    precondition(AVCaptureSession.Preset(rawValue: "iFrame960x540") == .iFrame960x540)
    precondition(AVCaptureSession.Preset.iFrame1280x720.rawValue == "iFrame1280x720")
    precondition(AVCaptureSession.Preset(rawValue: "iFrame1280x720") == .iFrame1280x720)
    precondition(AVCaptureSession.Preset.inputPriority.rawValue == "inputPriority")
    precondition(AVCaptureSession.Preset(rawValue: "inputPriority") == .inputPriority)
    precondition(AVSemanticSegmentationMatte.MatteType.skin.rawValue == "skin")
    precondition(AVSemanticSegmentationMatte.MatteType(rawValue: "skin") == .skin)
    precondition(AVSemanticSegmentationMatte.MatteType.hair.rawValue == "hair")
    precondition(AVSemanticSegmentationMatte.MatteType(rawValue: "hair") == .hair)
    precondition(AVSemanticSegmentationMatte.MatteType.teeth.rawValue == "teeth")
    precondition(AVSemanticSegmentationMatte.MatteType(rawValue: "teeth") == .teeth)
    precondition(AVSemanticSegmentationMatte.MatteType.glasses.rawValue == "glasses")
    precondition(AVSemanticSegmentationMatte.MatteType(rawValue: "glasses") == .glasses)
}
