#!/bin/zsh
# gen_conformance_registry.sh [outfile]
#
# Scan Sources/ConformanceApps for app directories (a folder that contains
# both <Name>App.swift and script.json) and write the generated
# Registry.swift that materialises each app's one-line
# `ConformanceApps.register` into `ConformanceApps.registry`.
#
# Checked in. A test asserts that regenerating it changes nothing:
#   scripts/gen_conformance_registry.sh /tmp/Registry.swift
#   diff -u Sources/ConformanceApps/Registry.swift /tmp/Registry.swift
#
# Default outfile is Sources/ConformanceApps/Registry.swift.
set -e
cd "$(dirname "$0")/.."
OUT=${1:-Sources/ConformanceApps/Registry.swift}

apps=()
for d in Sources/ConformanceApps/*(/N); do
  name=${d:t}
  [[ -f "$d/${name}App.swift" && -f "$d/script.json" ]] || continue
  apps+=$name
done
apps=(${(o)apps})

if [[ ${#apps} -eq 0 ]]; then
  echo "gen_conformance_registry: no apps under Sources/ConformanceApps" >&2
  exit 2
fi

{
  print '// GENERATED by scripts/gen_conformance_registry.sh — do not edit.'
  print '// Regenerating this file must change nothing (ConformanceRegistryTests).'
  print '// Source of truth: one-line ConformanceApps.register in each'
  print '// Sources/ConformanceApps/<App>/<App>App.swift, discovered by scanning'
  print '// that directory. MEASURED: the six apps (NavFlow, Forms,'
  print '// TableEditor, Feed, Modal, Pager) keep SKIP_CAPTURE=1 scores'
  print '// against /tmp/conformance-<App> goldens after switching openhost and'
  print '// confprobe onto this table.'
  print 'import UIKit'
  print ''
  print 'extension ConformanceApps {'
  print '    /// App names in directory-scan order (sorted). Safe to read off the'
  print '    /// main actor — used by openhost'\''s usage text and confprobe.'
  print '    public static let names: [String] = ['
  for name in $apps; do
    print "        \"${name}\","
  done
  print '    ]'
  print ''
  print '    /// Force every app'\''s one-line `static let _register<Name>` to run.'
  print '    /// Swift initialises those lets lazily; without this scan-driven'
  print '    /// list, `registry` would stay empty.'
  print '    @MainActor'
  print '    static func loadRegistry() {'
  for name in $apps; do
    print "        _ = _register${name}"
  done
  print '    }'
  print '}'
} > "$OUT"

echo "wrote $OUT (${#apps} app(s): ${(j:, :)apps})"
