#!/usr/bin/env bash
# gen_conformance_registry.sh [outfile]
#
# Scan Sources/ConformanceApps for app directories (a folder that contains
# both <Name>App.swift and script.json) and write the generated
# Registry.swift that materialises each app's one-line
# `ConformanceApps.register` into `ConformanceApps.registry`.
#
# Checked in. A test asserts that regenerating it changes nothing:
#   scripts/gen_conformance_registry.sh /tmp/Registry.swift
#   diff -u Sources/ConformanceApps/Registry.swift /tmp/Registry.swift
#
# Default outfile is Sources/ConformanceApps/Registry.swift.
#
# Portable bash (Linux trial 2026-09-05, swift:6.2-noble has no zsh): the
# previous zsh glob `*(/N)` died under bash at line 19. Same directory
# scan, same bytes out.
set -e
cd "$(dirname "$0")/.."
OUT=${1:-Sources/ConformanceApps/Registry.swift}

apps=()
for d in Sources/ConformanceApps/*/; do
  [ -d "$d" ] || continue
  name=$(basename "$d")
  [ -f "$d/${name}App.swift" ] && [ -f "$d/script.json" ] || continue
  apps+=("$name")
done

if [ ${#apps[@]} -eq 0 ]; then
  echo "gen_conformance_registry: no apps under Sources/ConformanceApps" >&2
  exit 2
fi

# Directory-scan order is sorted (ConformanceRegistryTests).
sorted=$(printf '%s\n' "${apps[@]}" | LC_ALL=C sort)
apps=()
while IFS= read -r name; do
  [ -n "$name" ] && apps+=("$name")
done <<EOF
$sorted
EOF

join_apps() {
  local i s=""
  for i in "${apps[@]}"; do
    if [ -n "$s" ]; then s="$s, $i"; else s="$i"; fi
  done
  printf '%s' "$s"
}

{
  printf '%s\n' '// GENERATED by scripts/gen_conformance_registry.sh — do not edit.'
  printf '%s\n' '// Regenerating this file must change nothing (ConformanceRegistryTests).'
  printf '%s\n' '// Source of truth: one-line ConformanceApps.register in each'
  printf '%s\n' '// Sources/ConformanceApps/<App>/<App>App.swift, discovered by scanning'
  printf '%s\n' '// that directory. MEASURED: the six existing apps (NavFlow, Forms,'
  printf '%s\n' '// TableEditor, Feed, Modal, Tabs) keep byte-identical SKIP_CAPTURE=1 scores'
  printf '%s\n' '// against /tmp/conformance-<App> goldens after switching openhost and'
  printf '%s\n' '// confprobe onto this table.'
  printf '%s\n' 'import UIKit'
  printf '%s\n' ''
  printf '%s\n' 'extension ConformanceApps {'
  printf '%s\n' '    /// App names in directory-scan order (sorted). Safe to read off the'
  printf '%s\n' "    /// main actor — used by openhost's usage text and confprobe."
  printf '%s\n' '    public static let names: [String] = ['
  for name in "${apps[@]}"; do
    printf '        "%s",\n' "$name"
  done
  printf '%s\n' '    ]'
  printf '%s\n' ''
  printf '%s\n' '    /// Force every app'\''s one-line `static let _register<Name>` to run.'
  printf '%s\n' '    /// Swift initialises those lets lazily; without this scan-driven'
  printf '%s\n' '    /// list, `registry` would stay empty.'
  printf '%s\n' '    @MainActor'
  printf '%s\n' '    static func loadRegistry() {'
  for name in "${apps[@]}"; do
    printf '        _ = _register%s\n' "$name"
  done
  printf '%s\n' '    }'
  printf '%s\n' '}'
} > "$OUT"

echo "wrote $OUT (${#apps[@]} app(s): $(join_apps))"
