#!/bin/zsh
# hillclimb.sh [max-agents] — one round of the fidelity hill-climb:
#
#   1. score:  fresh iOS suite capture (scripts/ios_suite.sh), real-app
#              screens, Catalyst gate, any conformance-app flows found under
#              /tmp/conformance-* -> scoreboard/latest.{json,md} (committed by
#              the operator with the round);
#   2. pick:   the worst rows with status "fail" (below their bar, not listed
#              in scoreboard/open.txt as measured-open), one task each, up to
#              max-agents (default 3); scenes of one family (same prefix
#              before the first '_') share a task;
#   3. launch: scripts/agent_fanout.sh on the generated task list
#              (scratch/hillclimb/tasks-<head>.txt), briefed by
#              docs/AGENT_BRIEF_ORACLE.md.
#
# Merging stays with the operator: scripts/agent_merge.sh <branch> per
# finished agent, then run this again. Every round leaves a scoreboard
# behind, so the history of the climb is `git log -- uikit/scoreboard`.
#
#   scripts/hillclimb.sh 3
#   SKIP_CAPTURE=1 scripts/hillclimb.sh 3     # reuse the last suite goldens
#   PICK_ONLY=1 scripts/hillclimb.sh          # score + write tasks, no launch
set -e
setopt null_glob
cd "$(dirname "$0")/.."
MAXA=${1:-3}
MODELS=(cursor-grok-4.6-high)   # every local agent: Grok 4.6 High (not fast)

echo "==> score"
if [[ -z "${SKIP_CAPTURE:-}" ]]; then zsh scripts/ios_suite.sh /tmp/ios_suite >/dev/null 2>&1 || true
else SKIP_CAPTURE=1 zsh scripts/ios_suite.sh /tmp/ios_suite >/dev/null 2>&1 || true; fi
swift build -c release --product openrender >/dev/null
rm -rf /tmp/hc_gate /tmp/hc_app
./.build/release/openrender render /tmp/hc_gate fixtures/scenes/*.json >/dev/null
OPENUIKIT_REALAPP_SCALE=3 OPENUIKIT_FORCE_IOS=1 ./.build/release/openrender realapp /tmp/hc_app >/dev/null
conf=(/tmp/conformance-*)
confargs=()
(( ${#conf} > 0 )) && confargs=(--conformance "${conf[@]}")
python3 scripts/scoreboard.py --suite /tmp/ios_suite --realapp-out /tmp/hc_app --gate-out /tmp/hc_gate \
  "${confargs[@]}" --write | tail -25

echo "==> pick"
HEAD=$(git rev-parse --short HEAD)
mkdir -p ../scratch/hillclimb
TASKS=$(cd ../scratch/hillclimb && pwd)/tasks-$HEAD.txt
python3 - "$TASKS" "$MAXA" "${MODELS[@]}" <<'PY'
import json, sys, collections
tasks_path, maxa, models = sys.argv[1], int(sys.argv[2]), sys.argv[3:]
board = json.load(open("scoreboard/latest.json"))
fails = [r for r in board["rows"] if r["status"] == "fail"]
groups = collections.OrderedDict()
for r in fails:                                   # worst first (rows are sorted by score)
    fam = r["scene"].split(":")[0].split("_")[0]
    groups.setdefault(fam, []).append(r)
lines = ["# generated by scripts/hillclimb.sh at " + board["head"]]
for k, (fam, rows) in enumerate(list(groups.items())[:maxa]):
    names = ", ".join(f"{r['scene']} ({r['score']:.2f} against a {r['threshold']} bar, blob {r['blob']:.0f} pt², {r['layout_issues']} layout issues)" for r in rows)
    scenes = " ".join(r["scene"].split(":")[0] for r in rows)
    kind = rows[0]["category"]
    if kind == "realapp":
        task = (f"Real-app screen(s) below their floor: {names}. Regenerate the goldens with scripts/realapp_probe_sim.sh /tmp/golden_realapp_ios, "
                f"render with OPENUIKIT_REALAPP_SCALE=3 OPENUIKIT_FORCE_IOS=1 ./.build/release/openrender realapp /tmp/app-$AGENT, compare with "
                f"Tools/compare/compare_realapp.py --scale 3, read the largest blob and the layout dump, find the rule with a probe scene, fix it under the iOS cut.")
    elif kind == "conformance":
        app = rows[0]["scene"].split(":")[0]
        task = (f"Conformance app '{app}' captures below the bar: {names}. Run scripts/conformance_flow.sh /tmp/conformance-{app} {app}, read report/<capture>/sheet.png and the frame dumps, "
                f"find the rule with a probe, fix it under the iOS cut; the app's source is shared with the simulator probe and must not change.")
    else:
        task = (f"Scenes below their bar: {names}. Run scripts/oracle_flow.sh /tmp/flow-$AGENT {scenes}, read report/<scene>/sheet.png, diff.png and both layout dumps, "
                f"chase frames before pixels, write a probe scene for whatever the report does not explain, and fix the rule under the iOS cut with its measurement in the code comment "
                f"and a row in docs/REAL_APP_TEST.md. If the difference turns out to be unmodellable, add the scene to scoreboard/open.txt with the reason instead of forcing it.")
    lines.append(f"hc-{fam}|{models[k % len(models)]}|{task}")
open(tasks_path, "w").write("\n".join(lines) + "\n")
print("\n".join(lines[1:]) or "nothing to climb")
PY
[[ -n "${PICK_ONLY:-}" ]] && exit 0
if (( $(grep -vc '^#' "$TASKS") == 0 )); then echo "nothing to launch"; exit 0; fi
echo "==> launch"
exec zsh scripts/agent_fanout.sh "$TASKS" "$MAXA"
