import Foundation
import MetalPerformanceShaders

func testMPSEnumRawValues() {
    precondition(MPSAccelerationStructureStatus.unbuilt.rawValue == 0)
    precondition(MPSAccelerationStructureStatus.built.rawValue == 1)
    precondition(MPSAlphaType.nonPremultiplied.rawValue == 0)
    precondition(MPSAlphaType.premultiplied.rawValue == 1)
    precondition(MPSAlphaType.alphaIsOne.rawValue == 2)
    precondition(MPSBoundingBoxIntersectionTestType.default.rawValue == 0)
    precondition(MPSBoundingBoxIntersectionTestType.axisAligned.rawValue == 1)
    precondition(MPSBoundingBoxIntersectionTestType.fast.rawValue == 2)
    precondition(MPSCNNBinaryConvolutionFlags.none.rawValue == 0)
    precondition(MPSCNNBinaryConvolutionFlags.useBetaScaling.rawValue == 1)
    precondition(MPSCNNBinaryConvolutionType.binaryWeights.rawValue == 0)
    precondition(MPSCNNBinaryConvolutionType.XNOR.rawValue == 1)
    precondition(MPSCNNBinaryConvolutionType.AND.rawValue == 2)
    precondition(MPSCNNConvolutionFlags.none.rawValue == 0)
    precondition(MPSCNNConvolutionWeightsLayout.OHWI.rawValue == 0)
    precondition(MPSCNNLossType.meanAbsoluteError.rawValue == 0)
    precondition(MPSCNNLossType.meanSquaredError.rawValue == 1)
    precondition(MPSCNNLossType.softMaxCrossEntropy.rawValue == 2)
    precondition(MPSCNNLossType.sigmoidCrossEntropy.rawValue == 3)
    precondition(MPSCNNLossType.categoricalCrossEntropy.rawValue == 4)
    precondition(MPSCNNLossType.hinge.rawValue == 5)
    precondition(MPSCNNLossType.huber.rawValue == 6)
    precondition(MPSCNNLossType.cosineDistance.rawValue == 7)
    precondition(MPSCNNLossType.log.rawValue == 8)
    precondition(MPSCNNLossType.kullbackLeiblerDivergence.rawValue == 9)
    precondition(MPSCNNLossType.count.rawValue == 10)
    precondition(MPSCNNNeuronType.none.rawValue == 0)
    precondition(MPSCNNNeuronType.reLU.rawValue == 1)
    precondition(MPSCNNNeuronType.linear.rawValue == 2)
    precondition(MPSCNNNeuronType.sigmoid.rawValue == 3)
    precondition(MPSCNNNeuronType.hardSigmoid.rawValue == 4)
    precondition(MPSCNNNeuronType.tanH.rawValue == 5)
    precondition(MPSCNNNeuronType.absolute.rawValue == 6)
    precondition(MPSCNNNeuronType.softPlus.rawValue == 7)
    precondition(MPSCNNNeuronType.softSign.rawValue == 8)
    precondition(MPSCNNNeuronType.ELU.rawValue == 9)
    precondition(MPSCNNNeuronType.pReLU.rawValue == 10)
    precondition(MPSCNNNeuronType.reLUN.rawValue == 11)
    precondition(MPSCNNNeuronType.power.rawValue == 12)
    precondition(MPSCNNNeuronType.exponential.rawValue == 13)
    precondition(MPSCNNNeuronType.logarithm.rawValue == 14)
    precondition(MPSCNNNeuronType.geLU.rawValue == 15)
    precondition(MPSCNNNeuronType.count.rawValue == 16)
    precondition(MPSCNNReductionType.none.rawValue == 0)
    precondition(MPSCNNReductionType.sum.rawValue == 1)
    precondition(MPSCNNReductionType.mean.rawValue == 2)
    precondition(MPSCNNReductionType.sumByNonZeroWeights.rawValue == 3)
    precondition(MPSCNNReductionType.count.rawValue == 4)
    precondition(MPSCNNWeightsQuantizationType.none.rawValue == 0)
    precondition(MPSCNNWeightsQuantizationType.linear.rawValue == 1)
    precondition(MPSCNNWeightsQuantizationType.lookupTable.rawValue == 2)
    precondition(MPSDataLayout.HeightxWidthxFeatureChannels.rawValue == 0)
    precondition(MPSDataLayout.featureChannelsxHeightxWidth.rawValue == 1)
    precondition(MPSDataType.invalid.rawValue == 0)
    precondition(MPSDataType.uInt8.rawValue == 8)
    precondition(MPSDataType.uInt16.rawValue == 16)
    precondition(MPSDataType.uInt32.rawValue == 32)
    precondition(MPSDataType.uInt64.rawValue == 64)
    precondition(MPSDataType.uInt4.rawValue == 4)
    precondition(MPSDataType.uInt2.rawValue == 2)
    precondition(MPSDataType.floatBit.rawValue == 0x1000_0000)
    precondition(MPSDataType.float16.rawValue == 0x1000_0010)
    precondition(MPSDataType.float32.rawValue == 0x1000_0020)
    precondition(MPSDataType.signedBit.rawValue == 0x2000_0000)
    precondition(MPSDataType.int8.rawValue == 0x2000_0008)
    precondition(MPSDataType.int16.rawValue == 0x2000_0010)
    precondition(MPSDataType.int32.rawValue == 0x2000_0020)
    precondition(MPSDataType.int64.rawValue == 0x2000_0040)
    precondition(MPSDataType.int4.rawValue == 0x2000_0004)
    precondition(MPSDataType.int2.rawValue == 0x2000_0002)
    precondition(MPSDataType.normalizedBit.rawValue == 0x4000_0000)
    precondition(MPSDataType.unorm1.rawValue == 0x4000_0001)
    precondition(MPSDataType.unorm8.rawValue == 0x4000_0008)
    precondition(MPSDataType.alternateEncodingBit.rawValue == 0x8000_0000)
    precondition(MPSDataType.bFloat16.rawValue == 0x8000_0010)
    precondition(MPSDataType.complexBit.rawValue == 0x0100_0000)
    precondition(MPSDataType.complexFloat16.rawValue == 0x1100_0010)
    precondition(MPSDataType.complexFloat32.rawValue == 0x1100_0020)
    precondition(MPSDataType.bool.rawValue == 0x0800_0000)
    precondition(MPSDataType.intBit == .signedBit)
    precondition(MPSFloatDataTypeBit.signBit.rawValue == 0x0080_0000)
    precondition(MPSFloatDataTypeBit.exponentBit.rawValue == 0x007F_0000)
    precondition(MPSFloatDataTypeBit.mantissaBit.rawValue == 0x0000_FFFF)
    precondition(MPSFloatDataTypeShift.signShift.rawValue == 23)
    precondition(MPSFloatDataTypeShift.exponentShift.rawValue == 16)
    precondition(MPSFloatDataTypeShift.mantissaShift.rawValue == 0)
    precondition(MPSImageEdgeMode.zero.rawValue == 0)
    precondition(MPSImageEdgeMode.clamp.rawValue == 1)
    precondition(MPSImageEdgeMode.mirror.rawValue == 2)
    precondition(MPSImageEdgeMode.mirrorWithEdge.rawValue == 3)
    precondition(MPSImageEdgeMode.constant.rawValue == 4)
    precondition(MPSImageFeatureChannelFormat.none.rawValue == 0)
    precondition(MPSImageFeatureChannelFormat.unorm8.rawValue == 1)
    precondition(MPSImageFeatureChannelFormat.unorm16.rawValue == 2)
    precondition(MPSImageFeatureChannelFormat.float16.rawValue == 3)
    precondition(MPSImageFeatureChannelFormat.float32.rawValue == 4)
    precondition(MPSImageFeatureChannelFormat.count.rawValue == 6)
    precondition(MPSIntersectionDataType.distance.rawValue == 0)
    precondition(MPSIntersectionDataType.distancePrimitiveIndex.rawValue == 1)
    precondition(MPSIntersectionDataType.distancePrimitiveIndexCoordinates.rawValue == 2)
    precondition(MPSIntersectionDataType.distancePrimitiveIndexInstanceIndex.rawValue == 3)
    precondition(MPSIntersectionDataType.distancePrimitiveIndexInstanceIndexCoordinates.rawValue == 4)
    precondition(MPSIntersectionDataType.distancePrimitiveIndexBufferIndex.rawValue == 5)
    precondition(MPSIntersectionDataType.distancePrimitiveIndexBufferIndexCoordinates.rawValue == 6)
    precondition(MPSIntersectionDataType.distancePrimitiveIndexBufferIndexInstanceIndex.rawValue == 7)
    precondition(MPSIntersectionDataType.distancePrimitiveIndexBufferIndexInstanceIndexCoordinates.rawValue == 8)
    precondition(MPSIntersectionType.nearest.rawValue == 0)
    precondition(MPSIntersectionType.any.rawValue == 1)
    precondition(MPSMatrixDecompositionStatus.success.rawValue == 0)
    precondition(MPSMatrixDecompositionStatus.failure.rawValue == -1)
    precondition(MPSMatrixDecompositionStatus.singular.rawValue == -2)
    precondition(MPSMatrixDecompositionStatus.nonPositiveDefinite.rawValue == -3)
    precondition(MPSNNRegularizationType.None.rawValue == 0)
    precondition(MPSNNRegularizationType.L1.rawValue == 1)
    precondition(MPSNNRegularizationType.L2.rawValue == 2)
    precondition(MPSPolygonType.triangle.rawValue == 0)
    precondition(MPSPolygonType.quadrilateral.rawValue == 1)
    precondition(MPSPurgeableState.allocationDeferred.rawValue == 0)
    precondition(MPSPurgeableState.keepCurrent.rawValue == 1)
    precondition(MPSPurgeableState.nonVolatile.rawValue == 2)
    precondition(MPSPurgeableState.volatile.rawValue == 3)
    precondition(MPSPurgeableState.empty.rawValue == 4)
    precondition(MPSRNNBidirectionalCombineMode.none.rawValue == 0)
    precondition(MPSRNNBidirectionalCombineMode.add.rawValue == 1)
    precondition(MPSRNNBidirectionalCombineMode.concatenate.rawValue == 2)
    precondition(MPSRNNSequenceDirection.forward.rawValue == 0)
    precondition(MPSRNNSequenceDirection.backward.rawValue == 1)
    precondition(MPSRayDataType.originDirection.rawValue == 0)
    precondition(MPSRayDataType.packedOriginDirection.rawValue == 1)
    precondition(MPSRayDataType.originMinDistanceDirectionMaxDistance.rawValue == 2)
    precondition(MPSRayDataType.originMaskDirectionMaxDistance.rawValue == 3)
    precondition(MPSRayMaskOperator.and.rawValue == 0)
    precondition(MPSRayMaskOperator.notAnd.rawValue == 1)
    precondition(MPSRayMaskOperator.or.rawValue == 2)
    precondition(MPSRayMaskOperator.notOr.rawValue == 3)
    precondition(MPSRayMaskOperator.xor.rawValue == 4)
    precondition(MPSRayMaskOperator.notXor.rawValue == 5)
    precondition(MPSRayMaskOperator.equal.rawValue == 6)
    precondition(MPSRayMaskOperator.notEqual.rawValue == 7)
    precondition(MPSRayMaskOperator.lessThan.rawValue == 8)
    precondition(MPSRayMaskOperator.lessThanOrEqualTo.rawValue == 9)
    precondition(MPSRayMaskOperator.greaterThan.rawValue == 10)
    precondition(MPSRayMaskOperator.greaterThanOrEqualTo.rawValue == 11)
    precondition(MPSStateResourceType.none.rawValue == 0)
    precondition(MPSStateResourceType.buffer.rawValue == 1)
    precondition(MPSStateResourceType.texture.rawValue == 2)
    precondition(MPSTemporalWeighting.average.rawValue == 0)
    precondition(MPSTemporalWeighting.exponentialMovingAverage.rawValue == 1)
    precondition(MPSTransformType.identity.rawValue == 0)
    precondition(MPSTransformType.float4x4.rawValue == 1)
    precondition(MPSTriangleIntersectionTestType.default.rawValue == 0)
    precondition(MPSTriangleIntersectionTestType.watertight.rawValue == 1)
    precondition(MPSRNNMatrixId.singleGateInputWeights.rawValue == 0)
    precondition(MPSRNNMatrixId.SingleGateInputWeights.rawValue == 29)
    precondition(MPSDataType.float32 != .float16)
    precondition(MPSImageEdgeMode.clamp != .zero)
    _ = MPSDataType(rawValue: 0x1000_0020)
    _ = MPSImageEdgeMode(rawValue: 1)
    _ = MPSRayDataType(rawValue: 0)
    _ = MPSRayMaskOperator(rawValue: 3)
    var hasher = Hasher()
    MPSDataType.float32.hash(into: &hasher)
    MPSImageEdgeMode.clamp.hash(into: &hasher)
    MPSRayDataType.originDirection.hash(into: &hasher)
    MPSRayMaskOperator.and.hash(into: &hasher)
    _ = MPSDataType.float32.hashValue
    _ = MPSImageEdgeMode.clamp.hashValue
    _ = MPSRayDataType.originDirection.hashValue
    _ = MPSRayMaskOperator.xor.hashValue
    precondition(MPSSizeofMPSDataType(.float32) == 4)
    precondition(MPSSizeofMPSDataType(.float16) == 2)
    precondition(MPSSizeofMPSDataType(.uInt8) == 1)
    precondition(MPSSizeofMPSDataType(.invalid) == 0)
    precondition(MPSDataTypeBitsCount(.float32) == 32)
    precondition(MPSDataTypeBitsCount(.int8) == 8)
    precondition(MPSDataTypeBitsCount(.bool) == 1)
    precondition(MPSDataTypeBitsCount(.uInt4) == 4)
    precondition(MPSDataTypeBitsCount(.complexFloat16) == 32)
    precondition(MPSDataTypeBitsCount(.complexFloat32) == 64)
    precondition(MPSDataTypeBitsCount(.unorm1) == 1)
}

func testMPSOptionSetAlgebra() {
    precondition(MPSKernelOptions.none.rawValue == 0)
    precondition(MPSKernelOptions.skipAPIValidation.rawValue == 1)
    precondition(MPSKernelOptions.allowReducedPrecision.rawValue == 2)
    precondition(MPSKernelOptions.disableInternalTiling.rawValue == 4)
    precondition(MPSKernelOptions.insertDebugGroups.rawValue == 8)
    precondition(MPSKernelOptions.verbose.rawValue == 16)
    var options: MPSKernelOptions = [.skipAPIValidation, .allowReducedPrecision]
    precondition(options.contains(.skipAPIValidation))
    precondition(options.contains(.allowReducedPrecision))
    precondition(!options.contains(.verbose))
    options.formUnion(.verbose)
    precondition(options.contains(.verbose))
    options.formIntersection([.verbose, .skipAPIValidation])
    precondition(options.contains(.verbose))
    precondition(!options.contains(.allowReducedPrecision))
    options.formSymmetricDifference(.verbose)
    precondition(!options.contains(.verbose))
    _ = options.insert(.insertDebugGroups)
    _ = options.remove(.insertDebugGroups)
    _ = options.update(with: .disableInternalTiling)
    precondition(options.union(.verbose).contains(.verbose))
    precondition(options.intersection(.none).isEmpty || true)
    precondition(options.subtracting(.disableInternalTiling).isDisjoint(with: .disableInternalTiling) || options.contains(.disableInternalTiling))
    var copy = options
    copy.subtract(.disableInternalTiling)
    precondition(MPSKernelOptions().isEmpty)
    precondition(MPSKernelOptions(rawValue: 1).contains(.skipAPIValidation))
    let fromSeq = MPSKernelOptions([.verbose, .skipAPIValidation])
    precondition(fromSeq.contains(.verbose))
    let literal: MPSKernelOptions = [.verbose]
    precondition(literal.isSubset(of: [.verbose, .skipAPIValidation]))
    precondition(MPSKernelOptions.skipAPIValidation.isSuperset(of: .skipAPIValidation))
    precondition(!MPSKernelOptions.none.isStrictSubset(of: .none))
    precondition(MPSKernelOptions.none.isStrictSubset(of: .verbose))
    precondition(MPSKernelOptions.verbose.isStrictSuperset(of: .none))
    _ = MPSKernelOptions.skipAPIValidation != .verbose
    precondition(MPSAccelerationStructureUsage.refit.rawValue == 1)
    precondition(MPSAccelerationStructureUsage.frequentRebuild.rawValue == 2)
    precondition(MPSAccelerationStructureUsage.preferGPUBuild.rawValue == 4)
    precondition(MPSAccelerationStructureUsage.preferCPUBuild.rawValue == 8)
    precondition(MPSAliasingStrategy.default.rawValue == 0)
    precondition(MPSAliasingStrategy.shallAlias.rawValue == 1)
    precondition(MPSAliasingStrategy.shallNotAlias.rawValue == 2)
    precondition(MPSAliasingStrategy.aliasingReserved.contains(.shallAlias))
    precondition(MPSAliasingStrategy.preferTemporaryMemory.rawValue == 4)
    precondition(MPSAliasingStrategy.preferNonTemporaryMemory.rawValue == 8)
    precondition(MPSCNNBatchNormalizationFlags.Default.rawValue == 0)
    precondition(MPSCNNBatchNormalizationFlags.CalculateStatisticsAutomatic.rawValue == 0)
    precondition(MPSCNNBatchNormalizationFlags.calculateStatisticsAlways.rawValue == 1)
    precondition(MPSCNNBatchNormalizationFlags.calculateStatisticsNever.rawValue == 2)
    precondition(MPSCNNBatchNormalizationFlags.calculateStatisticsMask.rawValue == 3)
    precondition(MPSCNNConvolutionGradientOption.gradientWithData.rawValue == 1)
    precondition(MPSCNNConvolutionGradientOption.gradientWithWeightsAndBias.rawValue == 2)
    precondition(MPSCNNConvolutionGradientOption.all.contains(.gradientWithData))
    precondition(MPSDeviceOptions.Default.rawValue == 0)
    precondition(MPSDeviceOptions.lowPower.rawValue == 1)
    precondition(MPSDeviceOptions.skipRemovable.rawValue == 2)
    precondition(MPSMatrixRandomDistribution.default.rawValue == 0)
    precondition(MPSMatrixRandomDistribution.uniform.rawValue == 1)
    precondition(MPSMatrixRandomDistribution.normal.rawValue == 2)
    precondition(MPSNDArrayQuantizationScheme.none.rawValue == 0)
    precondition(MPSNDArrayQuantizationScheme.typeAffine.rawValue == 1)
    precondition(MPSNDArrayQuantizationScheme.typeLUT.rawValue == 2)
    precondition(MPSNNComparisonType.equal.rawValue == 0)
    precondition(MPSNNComparisonType.notEqual.rawValue == 1)
    precondition(MPSNNComparisonType.less.rawValue == 2)
    precondition(MPSNNComparisonType.lessOrEqual.rawValue == 3)
    precondition(MPSNNComparisonType.greater.rawValue == 4)
    precondition(MPSNNComparisonType.greaterOrEqual.rawValue == 5)
    precondition(MPSNNConvolutionAccumulatorPrecisionOption.half.rawValue == 0)
    precondition(MPSNNConvolutionAccumulatorPrecisionOption.float.rawValue == 1)
    precondition(MPSNNPaddingMethod.centered.rawValue == 0)
    precondition(MPSNNPaddingMethod.alignTopLeft.rawValue == 1)
    precondition(MPSNNPaddingMethod.alignBottomRight.rawValue == 2)
    precondition(MPSNNPaddingMethod.align_reserved.rawValue == 3)
    precondition(MPSNNPaddingMethod.alignMask.rawValue == 3)
    precondition(MPSNNPaddingMethod.topLeft.rawValue == 0)
    precondition(MPSNNPaddingMethod.addRemainderToTopRight.rawValue == 4)
    precondition(MPSNNPaddingMethod.addRemainderToBottomLeft.rawValue == 8)
    precondition(MPSNNPaddingMethod.addRemainderToBottomRight.rawValue == 12)
    precondition(MPSNNPaddingMethod.addRemainderToMask.rawValue == 12)
    precondition(MPSNNPaddingMethod.validOnly.rawValue == 0)
    precondition(MPSNNPaddingMethod.sizeSame.rawValue == 16)
    precondition(MPSNNPaddingMethod.sizeFull.rawValue == 32)
    precondition(MPSNNPaddingMethod.size_reserved.rawValue == 48)
    precondition(MPSNNPaddingMethod.sizeMask.rawValue == 48)
    precondition(MPSNNPaddingMethod.excludeEdges.rawValue == 64)
    precondition(MPSNNPaddingMethod.custom.rawValue == 1 << 13)
    precondition(MPSNNPaddingMethod.customAllowForNodeFusion.rawValue == 1 << 14)
    precondition(MPSNNPaddingMethod.customWhitelistForNodeFusion.rawValue == 1 << 14)
    precondition(MPSNNTrainingStyle.UpdateDeviceNone.rawValue == 0)
    precondition(MPSNNTrainingStyle.updateDeviceCPU.rawValue == 1)
    precondition(MPSNNTrainingStyle.updateDeviceGPU.rawValue == 2)
    precondition(MPSRayMaskOptions.primitive.rawValue == 1)
    precondition(MPSRayMaskOptions.instance.rawValue == 2)
    var rayMask: MPSRayMaskOptions = [.primitive]
    _ = rayMask.insert(.instance)
    precondition(rayMask.contains(.instance))
    _ = MPSRayMaskOptions(rawValue: 3)
    _ = MPSRayMaskOptions()
    _ = MPSAccelerationStructureUsage(rawValue: 1)
    _ = MPSAliasingStrategy(rawValue: 1)
    _ = MPSDeviceOptions(rawValue: 1)
}

func testMPSConstantVars() {
    precondition(MPSCustomKernelIndexDestIndex.rawValue == 0)
    precondition(MPSCustomKernelIndexSrc0Index.rawValue == 1)
    precondition(MPSCustomKernelIndexSrc1Index.rawValue == 2)
    precondition(MPSCustomKernelIndexSrc2Index.rawValue == 3)
    precondition(MPSCustomKernelIndexSrc3Index.rawValue == 4)
    precondition(MPSCustomKernelIndexSrc4Index.rawValue == 5)
    precondition(MPSCustomKernelIndexUserDataIndex.rawValue == 6)
    _ = MPSCustomKernelIndex(0)
    _ = MPSCustomKernelIndex(rawValue: 1)
    precondition(MPSDeviceCapsNull.rawValue == 0)
    precondition(MPSDeviceIsAppleDevice.rawValue == 1)
    precondition(MPSDeviceSupportsFloat32Filtering.rawValue == 2)
    precondition(MPSDeviceSupportsSimdShuffle.rawValue == 4)
    precondition(MPSDeviceSupportsSimdReduction.rawValue == 8)
    precondition(MPSDeviceSupportsQuadShuffle.rawValue == 16)
    precondition(MPSDeviceSupportsSimdShuffleAndFill.rawValue == 32)
    precondition(MPSDeviceSupportsSimdgroupBarrier.rawValue == 64)
    precondition(MPSDeviceSupportsReadWriteTextures.rawValue == 128)
    precondition(MPSDeviceSupportsReadableArrayOfTextures.rawValue == 256)
    precondition(MPSDeviceSupportsWritableArrayOfTextures.rawValue == 512)
    precondition(MPSDeviceSupportsNorm16BicubicFiltering.rawValue == 1024)
    precondition(MPSDeviceSupportsFloat16BicubicFiltering.rawValue == 2048)
    precondition(MPSDeviceSupportsBFloat16Arithmetic.rawValue == 4096)
    precondition(MPSDeviceCapsLast.rawValue == 8192)
    _ = MPSDeviceCapsValues(0)
    _ = MPSDeviceCapsValues(rawValue: 1)
    precondition(MPSImageType2d.rawValue == 0)
    precondition(MPSImageType2d_array.rawValue == 1)
    precondition(MPSImageTypeArray2d.rawValue == 2)
    precondition(MPSImageTypeArray2d_array.rawValue == 3)
    precondition(MPSImageType2d_noAlpha.rawValue == 4)
    precondition(MPSImageType2d_array_noAlpha.rawValue == 5)
    precondition(MPSImageTypeArray2d_noAlpha.rawValue == 6)
    precondition(MPSImageTypeArray2d_array_noAlpha.rawValue == 7)
    precondition(MPSImageType_typeMask.rawValue == 0x3)
    precondition(MPSImageType_noAlpha.rawValue == 0x4)
    precondition(MPSImageType_ArrayMask.rawValue == 0x8)
    precondition(MPSImageType_BatchMask.rawValue == 0x10)
    precondition(MPSImageType_mask.rawValue == 0x1F)
    precondition(MPSImageType_texelFormatShift.rawValue == 5)
    precondition(MPSImageType_texelFormatMask.rawValue == 0xE0)
    precondition(MPSImageType_texelFormatStandard.rawValue == 0)
    precondition(MPSImageType_texelFormatUnorm8.rawValue == 1 << 5)
    precondition(MPSImageType_texelFormatFloat16.rawValue == 2 << 5)
    precondition(MPSImageType_texelFormatBFloat16.rawValue == 3 << 5)
    precondition(MPSImageType_bitCount.rawValue == 8)
    _ = MPSImageType(0)
    _ = MPSImageType(rawValue: 1)
    precondition(MPSFunctionConstantNone == -1)
    precondition(MPSFunctionConstantNoneArray.0 == -1)
    precondition(MPSRectNoClip.size.width > 0)
    precondition(MPSBatchSizeIndex == 0)
    precondition(MPSDeviceCapsIndex == 1)
    precondition(MPSFunctionConstantIndex == 2)
    precondition(MPSFunctionConstantIndexReserved == 3)
    precondition(MPSNDArrayConstantIndex == 4)
    precondition(MPSNDArrayConstantMultiDestDstAddressingIndex == 5)
    precondition(MPSNDArrayConstantMultiDestIndex == 6)
    precondition(MPSNDArrayConstantMultiDestIndex0 == 7)
    precondition(MPSNDArrayConstantMultiDestIndex1 == 8)
    precondition(MPSNDArrayConstantMultiDestSrcAddressingIndex == 9)
    precondition(MPSTextureLinkingConstantIndex == 10)
    precondition(MPSUserAvailableFunctionConstantStartIndex == 11)
    precondition(MPSUserConstantIndex == 12)
    let _: MPSDeviceCaps = 0
    let _: MPSFunctionConstant = MPSFunctionConstantNone
    let _: MPSFunctionConstantInMetal = 0
    _ = MetalPerformanceShadersModule.moduleName
}
