import Foundation
import Dispatch
import GameController

func testDeviceInputNameConstants() {
    precondition(GCProductCategoryArcadeStick == "Arcade Stick")
    precondition(GCProductCategoryCoalescedRemote == "Coalesced Remote")
    precondition(GCProductCategoryControlCenterRemote == "Control Center Remote")
    precondition(GCProductCategoryDualSense == "DualSense")
    precondition(GCProductCategoryDualShock4 == "DualShock4")
    precondition(GCProductCategoryHID == "HID")
    precondition(GCProductCategoryKeyboard == "Keyboard")
    precondition(GCProductCategoryMFi == "MFi")
    precondition(GCProductCategoryMouse == "Mouse")
    precondition(GCProductCategorySiriRemote1stGen == "Siri Remote 1st Gen")
    precondition(GCProductCategorySiriRemote2ndGen == "Siri Remote 2nd Gen")
    precondition(GCProductCategorySpatialController == "Spatial Controller")
    precondition(GCProductCategoryUniversalElectronicsRemote == "Universal Electronics Remote")
    precondition(GCProductCategoryXboxOne == "Xbox One")
    precondition(GCInputDirectionalCardinalDpad == "Cardinal D-pad")
    precondition(GCInputDirectionalCenterButton == "Center Button")
    precondition(GCInputDirectionalDpad == "Directional D-pad")
    precondition(GCInputDirectionalTouchSurfaceButton == "Touch Surface Button")
    precondition(GCInputMicroGamepadButtonA == "Button A")
    precondition(GCInputMicroGamepadButtonMenu == "Button Menu")
    precondition(GCInputMicroGamepadButtonX == "Button X")
    precondition(GCInputMicroGamepadDpad == "Direction Pad")
    precondition(GCInputButtonA == "Button A")
    precondition(GCInputButtonB == "Button B")
    precondition(GCInputButtonX == "Button X")
    precondition(GCInputButtonY == "Button Y")
    precondition(GCInputButtonHome == "Button Home")
    precondition(GCInputButtonMenu == "Button Menu")
    precondition(GCInputButtonShare == "Button Share")
    precondition(GCInputButtonOptions == "Button Options")
    precondition(GCInputLeftTrigger == "Left Trigger")
    precondition(GCInputRightTrigger == "Right Trigger")
    precondition(GCInputLeftShoulder == "Left Shoulder")
    precondition(GCInputRightShoulder == "Right Shoulder")
    precondition(GCInputDirectionPad == "Direction Pad")
    precondition(GCInputLeftThumbstick == "Left Thumbstick")
    precondition(GCInputRightThumbstick == "Right Thumbstick")
    precondition(GCInputLeftThumbstickButton == "Left Thumbstick Button")
    precondition(GCInputRightThumbstickButton == "Right Thumbstick Button")
    precondition(GCInputXboxPaddleOne == "Paddle 1")
    precondition(GCInputXboxPaddleTwo == "Paddle 2")
    precondition(GCInputXboxPaddleThree == "Paddle 3")
    precondition(GCInputXboxPaddleFour == "Paddle 4")
    precondition(GCInputDualShockTouchpadOne == "Touchpad 1")
    precondition(GCInputDualShockTouchpadTwo == "Touchpad 2")
    precondition(GCInputDualShockTouchpadButton == "Touchpad Button")
    precondition(kIOHIDGCSyntheticDeviceKey == "GCSyntheticDevice")
    precondition(GCCurrentExtendedGamepadSnapshotDataVersion == .version2)
    precondition(GCCurrentMicroGamepadSnapshotDataVersion == .version1)
    precondition(GCHapticDurationInfinite == -1)
    precondition(GCHapticsLocality.all.rawValue == "All")
    precondition(GCHapticsLocality.`default`.rawValue == "Default")
    precondition(GCHapticsLocality.handles.rawValue == "Handles")
    precondition(GCHapticsLocality.leftHandle.rawValue == "LeftHandle")
    precondition(GCHapticsLocality.rightHandle.rawValue == "RightHandle")
    precondition(GCHapticsLocality.triggers.rawValue == "Triggers")
    precondition(GCHapticsLocality.leftTrigger.rawValue == "LeftTrigger")
    precondition(GCHapticsLocality.rightTrigger.rawValue == "RightTrigger")
    precondition(GCHapticsLocality.all != .handles)
    _ = GCHapticsLocality(rawValue: "All")
    _ = GCHapticsLocality.self
    var hasher = Hasher()
    GCHapticsLocality.all.hash(into: &hasher)
    _ = hasher.finalize()
    _ = Set([GCHapticsLocality.all, .default, .handles, .leftHandle, .rightHandle, .triggers, .leftTrigger, .rightTrigger])
}
