import CoreAudioTypes

private func require(_ condition: Bool, _ message: String) {
    if !condition {
        fatalError("COREAUDIOTYPES_TEST_FAIL: \(message)")
    }
}

private func requireEqual<T: Equatable>(_ actual: T, _ expected: T, _ message: String) {
    require(actual == expected, "\(message): \(actual) != \(expected)")
}

func testConstantAndMemberRawValues() {
    requireEqual(AVAudioSessionErrorInsufficientPriority, 561017449, "AVAudioSessionErrorInsufficientPriority")
    requireEqual(kAudioChannelLabel_Ambisonic_W, 200, "kAudioChannelLabel_Ambisonic_W")
    requireEqual(kAudioChannelLabel_Ambisonic_X, 201, "kAudioChannelLabel_Ambisonic_X")
    requireEqual(kAudioChannelLabel_Ambisonic_Y, 202, "kAudioChannelLabel_Ambisonic_Y")
    requireEqual(kAudioChannelLabel_Ambisonic_Z, 203, "kAudioChannelLabel_Ambisonic_Z")
    requireEqual(kAudioChannelLabel_BeginReserved, 4026531840, "kAudioChannelLabel_BeginReserved")
    requireEqual(kAudioChannelLabel_BinauralLeft, 208, "kAudioChannelLabel_BinauralLeft")
    requireEqual(kAudioChannelLabel_BinauralRight, 209, "kAudioChannelLabel_BinauralRight")
    requireEqual(kAudioChannelLabel_Center, 3, "kAudioChannelLabel_Center")
    requireEqual(kAudioChannelLabel_CenterBottom, 59, "kAudioChannelLabel_CenterBottom")
    requireEqual(kAudioChannelLabel_CenterSurround, 9, "kAudioChannelLabel_CenterSurround")
    requireEqual(kAudioChannelLabel_CenterSurroundDirect, 44, "kAudioChannelLabel_CenterSurroundDirect")
    requireEqual(kAudioChannelLabel_CenterTopFront, 14, "kAudioChannelLabel_CenterTopFront")
    requireEqual(kAudioChannelLabel_CenterTopMiddle, 12, "kAudioChannelLabel_CenterTopMiddle")
    requireEqual(kAudioChannelLabel_CenterTopRear, 53, "kAudioChannelLabel_CenterTopRear")
    requireEqual(kAudioChannelLabel_ClickTrack, 304, "kAudioChannelLabel_ClickTrack")
    requireEqual(kAudioChannelLabel_DialogCentricMix, 43, "kAudioChannelLabel_DialogCentricMix")
    requireEqual(kAudioChannelLabel_Discrete, 400, "kAudioChannelLabel_Discrete")
    requireEqual(kAudioChannelLabel_Discrete_0, 65536, "kAudioChannelLabel_Discrete_0")
    requireEqual(kAudioChannelLabel_Discrete_1, 65537, "kAudioChannelLabel_Discrete_1")
    requireEqual(kAudioChannelLabel_Discrete_10, 65546, "kAudioChannelLabel_Discrete_10")
    requireEqual(kAudioChannelLabel_Discrete_11, 65547, "kAudioChannelLabel_Discrete_11")
    requireEqual(kAudioChannelLabel_Discrete_12, 65548, "kAudioChannelLabel_Discrete_12")
    requireEqual(kAudioChannelLabel_Discrete_13, 65549, "kAudioChannelLabel_Discrete_13")
    requireEqual(kAudioChannelLabel_Discrete_14, 65550, "kAudioChannelLabel_Discrete_14")
    requireEqual(kAudioChannelLabel_Discrete_15, 65551, "kAudioChannelLabel_Discrete_15")
    requireEqual(kAudioChannelLabel_Discrete_2, 65538, "kAudioChannelLabel_Discrete_2")
    requireEqual(kAudioChannelLabel_Discrete_3, 65539, "kAudioChannelLabel_Discrete_3")
    requireEqual(kAudioChannelLabel_Discrete_4, 65540, "kAudioChannelLabel_Discrete_4")
    requireEqual(kAudioChannelLabel_Discrete_5, 65541, "kAudioChannelLabel_Discrete_5")
    requireEqual(kAudioChannelLabel_Discrete_6, 65542, "kAudioChannelLabel_Discrete_6")
    requireEqual(kAudioChannelLabel_Discrete_65535, 131071, "kAudioChannelLabel_Discrete_65535")
    requireEqual(kAudioChannelLabel_Discrete_7, 65543, "kAudioChannelLabel_Discrete_7")
    requireEqual(kAudioChannelLabel_Discrete_8, 65544, "kAudioChannelLabel_Discrete_8")
    requireEqual(kAudioChannelLabel_Discrete_9, 65545, "kAudioChannelLabel_Discrete_9")
    requireEqual(kAudioChannelLabel_EndReserved, 4294967294, "kAudioChannelLabel_EndReserved")
    requireEqual(kAudioChannelLabel_ForeignLanguage, 305, "kAudioChannelLabel_ForeignLanguage")
    requireEqual(kAudioChannelLabel_HOA_ACN, 500, "kAudioChannelLabel_HOA_ACN")
    requireEqual(kAudioChannelLabel_HOA_ACN_0, 131072, "kAudioChannelLabel_HOA_ACN_0")
    requireEqual(kAudioChannelLabel_HOA_ACN_1, 131073, "kAudioChannelLabel_HOA_ACN_1")
    requireEqual(kAudioChannelLabel_HOA_ACN_10, 131082, "kAudioChannelLabel_HOA_ACN_10")
    requireEqual(kAudioChannelLabel_HOA_ACN_11, 131083, "kAudioChannelLabel_HOA_ACN_11")
    requireEqual(kAudioChannelLabel_HOA_ACN_12, 131084, "kAudioChannelLabel_HOA_ACN_12")
    requireEqual(kAudioChannelLabel_HOA_ACN_13, 131085, "kAudioChannelLabel_HOA_ACN_13")
    requireEqual(kAudioChannelLabel_HOA_ACN_14, 131086, "kAudioChannelLabel_HOA_ACN_14")
    requireEqual(kAudioChannelLabel_HOA_ACN_15, 131087, "kAudioChannelLabel_HOA_ACN_15")
    requireEqual(kAudioChannelLabel_HOA_ACN_2, 131074, "kAudioChannelLabel_HOA_ACN_2")
    requireEqual(kAudioChannelLabel_HOA_ACN_3, 131075, "kAudioChannelLabel_HOA_ACN_3")
    requireEqual(kAudioChannelLabel_HOA_ACN_4, 131076, "kAudioChannelLabel_HOA_ACN_4")
    requireEqual(kAudioChannelLabel_HOA_ACN_5, 131077, "kAudioChannelLabel_HOA_ACN_5")
    requireEqual(kAudioChannelLabel_HOA_ACN_6, 131078, "kAudioChannelLabel_HOA_ACN_6")
    requireEqual(kAudioChannelLabel_HOA_ACN_65024, 196096, "kAudioChannelLabel_HOA_ACN_65024")
    requireEqual(kAudioChannelLabel_HOA_ACN_7, 131079, "kAudioChannelLabel_HOA_ACN_7")
    requireEqual(kAudioChannelLabel_HOA_ACN_8, 131080, "kAudioChannelLabel_HOA_ACN_8")
    requireEqual(kAudioChannelLabel_HOA_ACN_9, 131081, "kAudioChannelLabel_HOA_ACN_9")
    requireEqual(kAudioChannelLabel_HOA_N3D, 196608, "kAudioChannelLabel_HOA_N3D")
    requireEqual(kAudioChannelLabel_HOA_SN3D, 131072, "kAudioChannelLabel_HOA_SN3D")
    requireEqual(kAudioChannelLabel_Haptic, 45, "kAudioChannelLabel_Haptic")
    requireEqual(kAudioChannelLabel_HeadphonesLeft, 301, "kAudioChannelLabel_HeadphonesLeft")
    requireEqual(kAudioChannelLabel_HeadphonesRight, 302, "kAudioChannelLabel_HeadphonesRight")
    requireEqual(kAudioChannelLabel_HearingImpaired, 40, "kAudioChannelLabel_HearingImpaired")
    requireEqual(kAudioChannelLabel_LFE2, 37, "kAudioChannelLabel_LFE2")
    requireEqual(kAudioChannelLabel_LFE3, 62, "kAudioChannelLabel_LFE3")
    requireEqual(kAudioChannelLabel_LFEScreen, 4, "kAudioChannelLabel_LFEScreen")
    requireEqual(kAudioChannelLabel_Left, 1, "kAudioChannelLabel_Left")
    requireEqual(kAudioChannelLabel_LeftBackSurround, 63, "kAudioChannelLabel_LeftBackSurround")
    requireEqual(kAudioChannelLabel_LeftBottom, 57, "kAudioChannelLabel_LeftBottom")
    requireEqual(kAudioChannelLabel_LeftCenter, 7, "kAudioChannelLabel_LeftCenter")
    requireEqual(kAudioChannelLabel_LeftEdgeOfScreen, 65, "kAudioChannelLabel_LeftEdgeOfScreen")
    requireEqual(kAudioChannelLabel_LeftSideSurround, 55, "kAudioChannelLabel_LeftSideSurround")
    requireEqual(kAudioChannelLabel_LeftSurround, 5, "kAudioChannelLabel_LeftSurround")
    requireEqual(kAudioChannelLabel_LeftSurroundDirect, 10, "kAudioChannelLabel_LeftSurroundDirect")
    requireEqual(kAudioChannelLabel_LeftTopFront, 13, "kAudioChannelLabel_LeftTopFront")
    requireEqual(kAudioChannelLabel_LeftTopMiddle, 49, "kAudioChannelLabel_LeftTopMiddle")
    requireEqual(kAudioChannelLabel_LeftTopRear, 52, "kAudioChannelLabel_LeftTopRear")
    requireEqual(kAudioChannelLabel_LeftTopSurround, 60, "kAudioChannelLabel_LeftTopSurround")
    requireEqual(kAudioChannelLabel_LeftTotal, 38, "kAudioChannelLabel_LeftTotal")
    requireEqual(kAudioChannelLabel_LeftWide, 35, "kAudioChannelLabel_LeftWide")
    requireEqual(kAudioChannelLabel_MS_Mid, 204, "kAudioChannelLabel_MS_Mid")
    requireEqual(kAudioChannelLabel_MS_Side, 205, "kAudioChannelLabel_MS_Side")
    requireEqual(kAudioChannelLabel_Mono, 42, "kAudioChannelLabel_Mono")
    requireEqual(kAudioChannelLabel_Narration, 41, "kAudioChannelLabel_Narration")
    requireEqual(kAudioChannelLabel_Object, 262144, "kAudioChannelLabel_Object")
    requireEqual(kAudioChannelLabel_RearSurroundLeft, 33, "kAudioChannelLabel_RearSurroundLeft")
    requireEqual(kAudioChannelLabel_RearSurroundRight, 34, "kAudioChannelLabel_RearSurroundRight")
    requireEqual(kAudioChannelLabel_Right, 2, "kAudioChannelLabel_Right")
    requireEqual(kAudioChannelLabel_RightBackSurround, 64, "kAudioChannelLabel_RightBackSurround")
    requireEqual(kAudioChannelLabel_RightBottom, 58, "kAudioChannelLabel_RightBottom")
    requireEqual(kAudioChannelLabel_RightCenter, 8, "kAudioChannelLabel_RightCenter")
    requireEqual(kAudioChannelLabel_RightEdgeOfScreen, 66, "kAudioChannelLabel_RightEdgeOfScreen")
    requireEqual(kAudioChannelLabel_RightSideSurround, 56, "kAudioChannelLabel_RightSideSurround")
    requireEqual(kAudioChannelLabel_RightSurround, 6, "kAudioChannelLabel_RightSurround")
    requireEqual(kAudioChannelLabel_RightSurroundDirect, 11, "kAudioChannelLabel_RightSurroundDirect")
    requireEqual(kAudioChannelLabel_RightTopFront, 15, "kAudioChannelLabel_RightTopFront")
    requireEqual(kAudioChannelLabel_RightTopMiddle, 51, "kAudioChannelLabel_RightTopMiddle")
    requireEqual(kAudioChannelLabel_RightTopRear, 54, "kAudioChannelLabel_RightTopRear")
    requireEqual(kAudioChannelLabel_RightTopSurround, 61, "kAudioChannelLabel_RightTopSurround")
    requireEqual(kAudioChannelLabel_RightTotal, 39, "kAudioChannelLabel_RightTotal")
    requireEqual(kAudioChannelLabel_RightWide, 36, "kAudioChannelLabel_RightWide")
    requireEqual(kAudioChannelLabel_TopBackCenter, 17, "kAudioChannelLabel_TopBackCenter")
    requireEqual(kAudioChannelLabel_TopBackLeft, 16, "kAudioChannelLabel_TopBackLeft")
    requireEqual(kAudioChannelLabel_TopBackRight, 18, "kAudioChannelLabel_TopBackRight")
    requireEqual(kAudioChannelLabel_TopCenterSurround, 12, "kAudioChannelLabel_TopCenterSurround")
    requireEqual(kAudioChannelLabel_Unknown, 4294967295, "kAudioChannelLabel_Unknown")
    requireEqual(kAudioChannelLabel_Unused, 0, "kAudioChannelLabel_Unused")
    requireEqual(kAudioChannelLabel_UseCoordinates, 100, "kAudioChannelLabel_UseCoordinates")
    requireEqual(kAudioChannelLabel_VerticalHeightCenter, 14, "kAudioChannelLabel_VerticalHeightCenter")
    requireEqual(kAudioChannelLabel_VerticalHeightLeft, 13, "kAudioChannelLabel_VerticalHeightLeft")
    requireEqual(kAudioChannelLabel_VerticalHeightRight, 15, "kAudioChannelLabel_VerticalHeightRight")
    requireEqual(kAudioChannelLabel_XY_X, 206, "kAudioChannelLabel_XY_X")
    requireEqual(kAudioChannelLabel_XY_Y, 207, "kAudioChannelLabel_XY_Y")
    requireEqual(kAudioChannelLayoutTag_AAC_3_0, 7471107, "kAudioChannelLayoutTag_AAC_3_0")
    requireEqual(kAudioChannelLayoutTag_AAC_4_0, 7602180, "kAudioChannelLayoutTag_AAC_4_0")
    requireEqual(kAudioChannelLayoutTag_AAC_5_0, 7864325, "kAudioChannelLayoutTag_AAC_5_0")
    requireEqual(kAudioChannelLayoutTag_AAC_5_1, 8126470, "kAudioChannelLayoutTag_AAC_5_1")
    requireEqual(kAudioChannelLayoutTag_AAC_6_0, 9240582, "kAudioChannelLayoutTag_AAC_6_0")
    requireEqual(kAudioChannelLayoutTag_AAC_6_1, 9306119, "kAudioChannelLayoutTag_AAC_6_1")
    requireEqual(kAudioChannelLayoutTag_AAC_7_0, 9371655, "kAudioChannelLayoutTag_AAC_7_0")
    requireEqual(kAudioChannelLayoutTag_AAC_7_1, 8323080, "kAudioChannelLayoutTag_AAC_7_1")
    requireEqual(kAudioChannelLayoutTag_AAC_7_1_B, 11993096, "kAudioChannelLayoutTag_AAC_7_1_B")
    requireEqual(kAudioChannelLayoutTag_AAC_7_1_C, 12058632, "kAudioChannelLayoutTag_AAC_7_1_C")
    requireEqual(kAudioChannelLayoutTag_AAC_Octagonal, 9437192, "kAudioChannelLayoutTag_AAC_Octagonal")
    requireEqual(kAudioChannelLayoutTag_AAC_Quadraphonic, 7077892, "kAudioChannelLayoutTag_AAC_Quadraphonic")
    requireEqual(kAudioChannelLayoutTag_AC3_1_0_1, 9764866, "kAudioChannelLayoutTag_AC3_1_0_1")
    requireEqual(kAudioChannelLayoutTag_AC3_2_1_1, 10027012, "kAudioChannelLayoutTag_AC3_2_1_1")
    requireEqual(kAudioChannelLayoutTag_AC3_3_0, 9830403, "kAudioChannelLayoutTag_AC3_3_0")
    requireEqual(kAudioChannelLayoutTag_AC3_3_0_1, 9961476, "kAudioChannelLayoutTag_AC3_3_0_1")
    requireEqual(kAudioChannelLayoutTag_AC3_3_1, 9895940, "kAudioChannelLayoutTag_AC3_3_1")
    requireEqual(kAudioChannelLayoutTag_AC3_3_1_1, 10092549, "kAudioChannelLayoutTag_AC3_3_1_1")
    requireEqual(kAudioChannelLayoutTag_Ambisonic_B_Format, 7012356, "kAudioChannelLayoutTag_Ambisonic_B_Format")
    requireEqual(kAudioChannelLayoutTag_Atmos_5_1_2, 12713992, "kAudioChannelLayoutTag_Atmos_5_1_2")
    requireEqual(kAudioChannelLayoutTag_Atmos_5_1_4, 12779530, "kAudioChannelLayoutTag_Atmos_5_1_4")
    requireEqual(kAudioChannelLayoutTag_Atmos_7_1_2, 12845066, "kAudioChannelLayoutTag_Atmos_7_1_2")
    requireEqual(kAudioChannelLayoutTag_Atmos_7_1_4, 12582924, "kAudioChannelLayoutTag_Atmos_7_1_4")
    requireEqual(kAudioChannelLayoutTag_Atmos_9_1_6, 12648464, "kAudioChannelLayoutTag_Atmos_9_1_6")
    requireEqual(kAudioChannelLayoutTag_AudioUnit_4, 7077892, "kAudioChannelLayoutTag_AudioUnit_4")
    requireEqual(kAudioChannelLayoutTag_AudioUnit_5, 7143429, "kAudioChannelLayoutTag_AudioUnit_5")
    requireEqual(kAudioChannelLayoutTag_AudioUnit_5_0, 7733253, "kAudioChannelLayoutTag_AudioUnit_5_0")
    requireEqual(kAudioChannelLayoutTag_AudioUnit_5_1, 7929862, "kAudioChannelLayoutTag_AudioUnit_5_1")
    requireEqual(kAudioChannelLayoutTag_AudioUnit_6, 7208966, "kAudioChannelLayoutTag_AudioUnit_6")
    requireEqual(kAudioChannelLayoutTag_AudioUnit_6_0, 9109510, "kAudioChannelLayoutTag_AudioUnit_6_0")
    requireEqual(kAudioChannelLayoutTag_AudioUnit_6_1, 8192007, "kAudioChannelLayoutTag_AudioUnit_6_1")
    requireEqual(kAudioChannelLayoutTag_AudioUnit_7_0, 9175047, "kAudioChannelLayoutTag_AudioUnit_7_0")
    requireEqual(kAudioChannelLayoutTag_AudioUnit_7_0_Front, 9699335, "kAudioChannelLayoutTag_AudioUnit_7_0_Front")
    requireEqual(kAudioChannelLayoutTag_AudioUnit_7_1, 8388616, "kAudioChannelLayoutTag_AudioUnit_7_1")
    requireEqual(kAudioChannelLayoutTag_AudioUnit_7_1_Front, 8257544, "kAudioChannelLayoutTag_AudioUnit_7_1_Front")
    requireEqual(kAudioChannelLayoutTag_AudioUnit_8, 7274504, "kAudioChannelLayoutTag_AudioUnit_8")
    requireEqual(kAudioChannelLayoutTag_BeginReserved, 4026531840, "kAudioChannelLayoutTag_BeginReserved")
    requireEqual(kAudioChannelLayoutTag_Binaural, 6946818, "kAudioChannelLayoutTag_Binaural")
    requireEqual(kAudioChannelLayoutTag_CICP_1, 6553601, "kAudioChannelLayoutTag_CICP_1")
    requireEqual(kAudioChannelLayoutTag_CICP_10, 8650756, "kAudioChannelLayoutTag_CICP_10")
    requireEqual(kAudioChannelLayoutTag_CICP_11, 8192007, "kAudioChannelLayoutTag_CICP_11")
    requireEqual(kAudioChannelLayoutTag_CICP_12, 8388616, "kAudioChannelLayoutTag_CICP_12")
    requireEqual(kAudioChannelLayoutTag_CICP_13, 13369368, "kAudioChannelLayoutTag_CICP_13")
    requireEqual(kAudioChannelLayoutTag_CICP_14, 13434888, "kAudioChannelLayoutTag_CICP_14")
    requireEqual(kAudioChannelLayoutTag_CICP_15, 13500428, "kAudioChannelLayoutTag_CICP_15")
    requireEqual(kAudioChannelLayoutTag_CICP_16, 13565962, "kAudioChannelLayoutTag_CICP_16")
    requireEqual(kAudioChannelLayoutTag_CICP_17, 13631500, "kAudioChannelLayoutTag_CICP_17")
    requireEqual(kAudioChannelLayoutTag_CICP_18, 13697038, "kAudioChannelLayoutTag_CICP_18")
    requireEqual(kAudioChannelLayoutTag_CICP_19, 13762572, "kAudioChannelLayoutTag_CICP_19")
    requireEqual(kAudioChannelLayoutTag_CICP_2, 6619138, "kAudioChannelLayoutTag_CICP_2")
    requireEqual(kAudioChannelLayoutTag_CICP_20, 13828110, "kAudioChannelLayoutTag_CICP_20")
    requireEqual(kAudioChannelLayoutTag_CICP_3, 7405571, "kAudioChannelLayoutTag_CICP_3")
    requireEqual(kAudioChannelLayoutTag_CICP_4, 7536644, "kAudioChannelLayoutTag_CICP_4")
    requireEqual(kAudioChannelLayoutTag_CICP_5, 7667717, "kAudioChannelLayoutTag_CICP_5")
    requireEqual(kAudioChannelLayoutTag_CICP_6, 7929862, "kAudioChannelLayoutTag_CICP_6")
    requireEqual(kAudioChannelLayoutTag_CICP_7, 8323080, "kAudioChannelLayoutTag_CICP_7")
    requireEqual(kAudioChannelLayoutTag_CICP_9, 8585219, "kAudioChannelLayoutTag_CICP_9")
    requireEqual(kAudioChannelLayoutTag_Cube, 7340040, "kAudioChannelLayoutTag_Cube")
    requireEqual(kAudioChannelLayoutTag_DTS_3_1, 11010052, "kAudioChannelLayoutTag_DTS_3_1")
    requireEqual(kAudioChannelLayoutTag_DTS_4_1, 11075589, "kAudioChannelLayoutTag_DTS_4_1")
    requireEqual(kAudioChannelLayoutTag_DTS_6_0_A, 11141126, "kAudioChannelLayoutTag_DTS_6_0_A")
    requireEqual(kAudioChannelLayoutTag_DTS_6_0_B, 11206662, "kAudioChannelLayoutTag_DTS_6_0_B")
    requireEqual(kAudioChannelLayoutTag_DTS_6_0_C, 11272198, "kAudioChannelLayoutTag_DTS_6_0_C")
    requireEqual(kAudioChannelLayoutTag_DTS_6_1_A, 11337735, "kAudioChannelLayoutTag_DTS_6_1_A")
    requireEqual(kAudioChannelLayoutTag_DTS_6_1_B, 11403271, "kAudioChannelLayoutTag_DTS_6_1_B")
    requireEqual(kAudioChannelLayoutTag_DTS_6_1_C, 11468807, "kAudioChannelLayoutTag_DTS_6_1_C")
    requireEqual(kAudioChannelLayoutTag_DTS_6_1_D, 11927559, "kAudioChannelLayoutTag_DTS_6_1_D")
    requireEqual(kAudioChannelLayoutTag_DTS_7_0, 11534343, "kAudioChannelLayoutTag_DTS_7_0")
    requireEqual(kAudioChannelLayoutTag_DTS_7_1, 11599880, "kAudioChannelLayoutTag_DTS_7_1")
    requireEqual(kAudioChannelLayoutTag_DTS_8_0_A, 11665416, "kAudioChannelLayoutTag_DTS_8_0_A")
    requireEqual(kAudioChannelLayoutTag_DTS_8_0_B, 11730952, "kAudioChannelLayoutTag_DTS_8_0_B")
    requireEqual(kAudioChannelLayoutTag_DTS_8_1_A, 11796489, "kAudioChannelLayoutTag_DTS_8_1_A")
    requireEqual(kAudioChannelLayoutTag_DTS_8_1_B, 11862025, "kAudioChannelLayoutTag_DTS_8_1_B")
    requireEqual(kAudioChannelLayoutTag_DVD_0, 6553601, "kAudioChannelLayoutTag_DVD_0")
    requireEqual(kAudioChannelLayoutTag_DVD_1, 6619138, "kAudioChannelLayoutTag_DVD_1")
    requireEqual(kAudioChannelLayoutTag_DVD_10, 8912900, "kAudioChannelLayoutTag_DVD_10")
    requireEqual(kAudioChannelLayoutTag_DVD_11, 8978437, "kAudioChannelLayoutTag_DVD_11")
    requireEqual(kAudioChannelLayoutTag_DVD_12, 7929862, "kAudioChannelLayoutTag_DVD_12")
    requireEqual(kAudioChannelLayoutTag_DVD_13, 7536644, "kAudioChannelLayoutTag_DVD_13")
    requireEqual(kAudioChannelLayoutTag_DVD_14, 7667717, "kAudioChannelLayoutTag_DVD_14")
    requireEqual(kAudioChannelLayoutTag_DVD_15, 8912900, "kAudioChannelLayoutTag_DVD_15")
    requireEqual(kAudioChannelLayoutTag_DVD_16, 8978437, "kAudioChannelLayoutTag_DVD_16")
    requireEqual(kAudioChannelLayoutTag_DVD_17, 7929862, "kAudioChannelLayoutTag_DVD_17")
    requireEqual(kAudioChannelLayoutTag_DVD_18, 9043973, "kAudioChannelLayoutTag_DVD_18")
    requireEqual(kAudioChannelLayoutTag_DVD_19, 7733253, "kAudioChannelLayoutTag_DVD_19")
    requireEqual(kAudioChannelLayoutTag_DVD_2, 8585219, "kAudioChannelLayoutTag_DVD_2")
    requireEqual(kAudioChannelLayoutTag_DVD_20, 7995398, "kAudioChannelLayoutTag_DVD_20")
    requireEqual(kAudioChannelLayoutTag_DVD_3, 8650756, "kAudioChannelLayoutTag_DVD_3")
    requireEqual(kAudioChannelLayoutTag_DVD_4, 8716291, "kAudioChannelLayoutTag_DVD_4")
    requireEqual(kAudioChannelLayoutTag_DVD_5, 8781828, "kAudioChannelLayoutTag_DVD_5")
    requireEqual(kAudioChannelLayoutTag_DVD_6, 8847365, "kAudioChannelLayoutTag_DVD_6")
    requireEqual(kAudioChannelLayoutTag_DVD_7, 7405571, "kAudioChannelLayoutTag_DVD_7")
    requireEqual(kAudioChannelLayoutTag_DVD_8, 7536644, "kAudioChannelLayoutTag_DVD_8")
    requireEqual(kAudioChannelLayoutTag_DVD_9, 7667717, "kAudioChannelLayoutTag_DVD_9")
    requireEqual(kAudioChannelLayoutTag_DiscreteInOrder, 9633792, "kAudioChannelLayoutTag_DiscreteInOrder")
    requireEqual(kAudioChannelLayoutTag_EAC3_6_1_A, 10289159, "kAudioChannelLayoutTag_EAC3_6_1_A")
    requireEqual(kAudioChannelLayoutTag_EAC3_6_1_B, 10354695, "kAudioChannelLayoutTag_EAC3_6_1_B")
    requireEqual(kAudioChannelLayoutTag_EAC3_6_1_C, 10420231, "kAudioChannelLayoutTag_EAC3_6_1_C")
    requireEqual(kAudioChannelLayoutTag_EAC3_7_1_A, 10485768, "kAudioChannelLayoutTag_EAC3_7_1_A")
    requireEqual(kAudioChannelLayoutTag_EAC3_7_1_B, 10551304, "kAudioChannelLayoutTag_EAC3_7_1_B")
    requireEqual(kAudioChannelLayoutTag_EAC3_7_1_C, 10616840, "kAudioChannelLayoutTag_EAC3_7_1_C")
    requireEqual(kAudioChannelLayoutTag_EAC3_7_1_D, 10682376, "kAudioChannelLayoutTag_EAC3_7_1_D")
    requireEqual(kAudioChannelLayoutTag_EAC3_7_1_E, 10747912, "kAudioChannelLayoutTag_EAC3_7_1_E")
    requireEqual(kAudioChannelLayoutTag_EAC3_7_1_F, 10813448, "kAudioChannelLayoutTag_EAC3_7_1_F")
    requireEqual(kAudioChannelLayoutTag_EAC3_7_1_G, 10878984, "kAudioChannelLayoutTag_EAC3_7_1_G")
    requireEqual(kAudioChannelLayoutTag_EAC3_7_1_H, 10944520, "kAudioChannelLayoutTag_EAC3_7_1_H")
    requireEqual(kAudioChannelLayoutTag_EAC_6_0_A, 10158086, "kAudioChannelLayoutTag_EAC_6_0_A")
    requireEqual(kAudioChannelLayoutTag_EAC_7_0_A, 10223623, "kAudioChannelLayoutTag_EAC_7_0_A")
    requireEqual(kAudioChannelLayoutTag_Emagic_Default_7_1, 8454152, "kAudioChannelLayoutTag_Emagic_Default_7_1")
    requireEqual(kAudioChannelLayoutTag_EndReserved, 4294901759, "kAudioChannelLayoutTag_EndReserved")
    requireEqual(kAudioChannelLayoutTag_HOA_ACN_N3D, 12517376, "kAudioChannelLayoutTag_HOA_ACN_N3D")
    requireEqual(kAudioChannelLayoutTag_HOA_ACN_SN3D, 12451840, "kAudioChannelLayoutTag_HOA_ACN_SN3D")
    requireEqual(kAudioChannelLayoutTag_Hexagonal, 7208966, "kAudioChannelLayoutTag_Hexagonal")
    requireEqual(kAudioChannelLayoutTag_ITU_1_0, 6553601, "kAudioChannelLayoutTag_ITU_1_0")
    requireEqual(kAudioChannelLayoutTag_ITU_2_0, 6619138, "kAudioChannelLayoutTag_ITU_2_0")
    requireEqual(kAudioChannelLayoutTag_ITU_2_1, 8585219, "kAudioChannelLayoutTag_ITU_2_1")
    requireEqual(kAudioChannelLayoutTag_ITU_2_2, 8650756, "kAudioChannelLayoutTag_ITU_2_2")
    requireEqual(kAudioChannelLayoutTag_ITU_3_0, 7405571, "kAudioChannelLayoutTag_ITU_3_0")
    requireEqual(kAudioChannelLayoutTag_ITU_3_1, 7536644, "kAudioChannelLayoutTag_ITU_3_1")
    requireEqual(kAudioChannelLayoutTag_ITU_3_2, 7667717, "kAudioChannelLayoutTag_ITU_3_2")
    requireEqual(kAudioChannelLayoutTag_ITU_3_2_1, 7929862, "kAudioChannelLayoutTag_ITU_3_2_1")
    requireEqual(kAudioChannelLayoutTag_ITU_3_4_1, 8388616, "kAudioChannelLayoutTag_ITU_3_4_1")
    requireEqual(kAudioChannelLayoutTag_Logic_4_0_A, 7536644, "kAudioChannelLayoutTag_Logic_4_0_A")
    requireEqual(kAudioChannelLayoutTag_Logic_4_0_B, 7602180, "kAudioChannelLayoutTag_Logic_4_0_B")
    requireEqual(kAudioChannelLayoutTag_Logic_4_0_C, 12910596, "kAudioChannelLayoutTag_Logic_4_0_C")
    requireEqual(kAudioChannelLayoutTag_Logic_5_0_A, 7667717, "kAudioChannelLayoutTag_Logic_5_0_A")
    requireEqual(kAudioChannelLayoutTag_Logic_5_0_B, 7733253, "kAudioChannelLayoutTag_Logic_5_0_B")
    requireEqual(kAudioChannelLayoutTag_Logic_5_0_C, 7798789, "kAudioChannelLayoutTag_Logic_5_0_C")
    requireEqual(kAudioChannelLayoutTag_Logic_5_0_D, 7864325, "kAudioChannelLayoutTag_Logic_5_0_D")
    requireEqual(kAudioChannelLayoutTag_Logic_5_1_A, 7929862, "kAudioChannelLayoutTag_Logic_5_1_A")
    requireEqual(kAudioChannelLayoutTag_Logic_5_1_B, 7995398, "kAudioChannelLayoutTag_Logic_5_1_B")
    requireEqual(kAudioChannelLayoutTag_Logic_5_1_C, 8060934, "kAudioChannelLayoutTag_Logic_5_1_C")
    requireEqual(kAudioChannelLayoutTag_Logic_5_1_D, 8126470, "kAudioChannelLayoutTag_Logic_5_1_D")
    requireEqual(kAudioChannelLayoutTag_Logic_6_0_A, 9240582, "kAudioChannelLayoutTag_Logic_6_0_A")
    requireEqual(kAudioChannelLayoutTag_Logic_6_0_B, 12976134, "kAudioChannelLayoutTag_Logic_6_0_B")
    requireEqual(kAudioChannelLayoutTag_Logic_6_0_C, 9109510, "kAudioChannelLayoutTag_Logic_6_0_C")
    requireEqual(kAudioChannelLayoutTag_Logic_6_1_A, 9306119, "kAudioChannelLayoutTag_Logic_6_1_A")
    requireEqual(kAudioChannelLayoutTag_Logic_6_1_B, 13041671, "kAudioChannelLayoutTag_Logic_6_1_B")
    requireEqual(kAudioChannelLayoutTag_Logic_6_1_C, 8192007, "kAudioChannelLayoutTag_Logic_6_1_C")
    requireEqual(kAudioChannelLayoutTag_Logic_6_1_D, 13107207, "kAudioChannelLayoutTag_Logic_6_1_D")
    requireEqual(kAudioChannelLayoutTag_Logic_7_1_A, 8388616, "kAudioChannelLayoutTag_Logic_7_1_A")
    requireEqual(kAudioChannelLayoutTag_Logic_7_1_B, 13172744, "kAudioChannelLayoutTag_Logic_7_1_B")
    requireEqual(kAudioChannelLayoutTag_Logic_7_1_C, 8388616, "kAudioChannelLayoutTag_Logic_7_1_C")
    requireEqual(kAudioChannelLayoutTag_Logic_7_1_SDDS_A, 8257544, "kAudioChannelLayoutTag_Logic_7_1_SDDS_A")
    requireEqual(kAudioChannelLayoutTag_Logic_7_1_SDDS_B, 8323080, "kAudioChannelLayoutTag_Logic_7_1_SDDS_B")
    requireEqual(kAudioChannelLayoutTag_Logic_7_1_SDDS_C, 8454152, "kAudioChannelLayoutTag_Logic_7_1_SDDS_C")
    requireEqual(kAudioChannelLayoutTag_Logic_Atmos_5_1_2, 12713992, "kAudioChannelLayoutTag_Logic_Atmos_5_1_2")
    requireEqual(kAudioChannelLayoutTag_Logic_Atmos_5_1_4, 12779530, "kAudioChannelLayoutTag_Logic_Atmos_5_1_4")
    requireEqual(kAudioChannelLayoutTag_Logic_Atmos_7_1_2, 12845066, "kAudioChannelLayoutTag_Logic_Atmos_7_1_2")
    requireEqual(kAudioChannelLayoutTag_Logic_Atmos_7_1_4_A, 12582924, "kAudioChannelLayoutTag_Logic_Atmos_7_1_4_A")
    requireEqual(kAudioChannelLayoutTag_Logic_Atmos_7_1_4_B, 13238284, "kAudioChannelLayoutTag_Logic_Atmos_7_1_4_B")
    requireEqual(kAudioChannelLayoutTag_Logic_Atmos_7_1_6, 13303822, "kAudioChannelLayoutTag_Logic_Atmos_7_1_6")
    requireEqual(kAudioChannelLayoutTag_Logic_Mono, 6553601, "kAudioChannelLayoutTag_Logic_Mono")
    requireEqual(kAudioChannelLayoutTag_Logic_Quadraphonic, 7077892, "kAudioChannelLayoutTag_Logic_Quadraphonic")
    requireEqual(kAudioChannelLayoutTag_Logic_Stereo, 6619138, "kAudioChannelLayoutTag_Logic_Stereo")
    requireEqual(kAudioChannelLayoutTag_MPEG_1_0, 6553601, "kAudioChannelLayoutTag_MPEG_1_0")
    requireEqual(kAudioChannelLayoutTag_MPEG_2_0, 6619138, "kAudioChannelLayoutTag_MPEG_2_0")
    requireEqual(kAudioChannelLayoutTag_MPEG_3_0_A, 7405571, "kAudioChannelLayoutTag_MPEG_3_0_A")
    requireEqual(kAudioChannelLayoutTag_MPEG_3_0_B, 7471107, "kAudioChannelLayoutTag_MPEG_3_0_B")
    requireEqual(kAudioChannelLayoutTag_MPEG_4_0_A, 7536644, "kAudioChannelLayoutTag_MPEG_4_0_A")
    requireEqual(kAudioChannelLayoutTag_MPEG_4_0_B, 7602180, "kAudioChannelLayoutTag_MPEG_4_0_B")
    requireEqual(kAudioChannelLayoutTag_MPEG_5_0_A, 7667717, "kAudioChannelLayoutTag_MPEG_5_0_A")
    requireEqual(kAudioChannelLayoutTag_MPEG_5_0_B, 7733253, "kAudioChannelLayoutTag_MPEG_5_0_B")
    requireEqual(kAudioChannelLayoutTag_MPEG_5_0_C, 7798789, "kAudioChannelLayoutTag_MPEG_5_0_C")
    requireEqual(kAudioChannelLayoutTag_MPEG_5_0_D, 7864325, "kAudioChannelLayoutTag_MPEG_5_0_D")
    requireEqual(kAudioChannelLayoutTag_MPEG_5_0_E, 14155781, "kAudioChannelLayoutTag_MPEG_5_0_E")
    requireEqual(kAudioChannelLayoutTag_MPEG_5_1_A, 7929862, "kAudioChannelLayoutTag_MPEG_5_1_A")
    requireEqual(kAudioChannelLayoutTag_MPEG_5_1_B, 7995398, "kAudioChannelLayoutTag_MPEG_5_1_B")
    requireEqual(kAudioChannelLayoutTag_MPEG_5_1_C, 8060934, "kAudioChannelLayoutTag_MPEG_5_1_C")
    requireEqual(kAudioChannelLayoutTag_MPEG_5_1_D, 8126470, "kAudioChannelLayoutTag_MPEG_5_1_D")
    requireEqual(kAudioChannelLayoutTag_MPEG_5_1_E, 14221318, "kAudioChannelLayoutTag_MPEG_5_1_E")
    requireEqual(kAudioChannelLayoutTag_MPEG_6_1_A, 8192007, "kAudioChannelLayoutTag_MPEG_6_1_A")
    requireEqual(kAudioChannelLayoutTag_MPEG_6_1_B, 14286855, "kAudioChannelLayoutTag_MPEG_6_1_B")
    requireEqual(kAudioChannelLayoutTag_MPEG_7_1_A, 8257544, "kAudioChannelLayoutTag_MPEG_7_1_A")
    requireEqual(kAudioChannelLayoutTag_MPEG_7_1_B, 8323080, "kAudioChannelLayoutTag_MPEG_7_1_B")
    requireEqual(kAudioChannelLayoutTag_MPEG_7_1_C, 8388616, "kAudioChannelLayoutTag_MPEG_7_1_C")
    requireEqual(kAudioChannelLayoutTag_MPEG_7_1_D, 14352392, "kAudioChannelLayoutTag_MPEG_7_1_D")
    requireEqual(kAudioChannelLayoutTag_MatrixStereo, 6750210, "kAudioChannelLayoutTag_MatrixStereo")
    requireEqual(kAudioChannelLayoutTag_MidSide, 6815746, "kAudioChannelLayoutTag_MidSide")
    requireEqual(kAudioChannelLayoutTag_Mono, 6553601, "kAudioChannelLayoutTag_Mono")
    requireEqual(kAudioChannelLayoutTag_Octagonal, 7274504, "kAudioChannelLayoutTag_Octagonal")
    requireEqual(kAudioChannelLayoutTag_Ogg_3_0, 9830403, "kAudioChannelLayoutTag_Ogg_3_0")
    requireEqual(kAudioChannelLayoutTag_Ogg_4_0, 12124164, "kAudioChannelLayoutTag_Ogg_4_0")
    requireEqual(kAudioChannelLayoutTag_Ogg_5_0, 13893637, "kAudioChannelLayoutTag_Ogg_5_0")
    requireEqual(kAudioChannelLayoutTag_Ogg_5_1, 13959174, "kAudioChannelLayoutTag_Ogg_5_1")
    requireEqual(kAudioChannelLayoutTag_Ogg_6_1, 14024711, "kAudioChannelLayoutTag_Ogg_6_1")
    requireEqual(kAudioChannelLayoutTag_Ogg_7_1, 14090248, "kAudioChannelLayoutTag_Ogg_7_1")
    requireEqual(kAudioChannelLayoutTag_Pentagonal, 7143429, "kAudioChannelLayoutTag_Pentagonal")
    requireEqual(kAudioChannelLayoutTag_Quadraphonic, 7077892, "kAudioChannelLayoutTag_Quadraphonic")
    requireEqual(kAudioChannelLayoutTag_SMPTE_DTV, 8519688, "kAudioChannelLayoutTag_SMPTE_DTV")
    requireEqual(kAudioChannelLayoutTag_Stereo, 6619138, "kAudioChannelLayoutTag_Stereo")
    requireEqual(kAudioChannelLayoutTag_StereoHeadphones, 6684674, "kAudioChannelLayoutTag_StereoHeadphones")
    requireEqual(kAudioChannelLayoutTag_TMH_10_2_full, 9568277, "kAudioChannelLayoutTag_TMH_10_2_full")
    requireEqual(kAudioChannelLayoutTag_TMH_10_2_std, 9502736, "kAudioChannelLayoutTag_TMH_10_2_std")
    requireEqual(kAudioChannelLayoutTag_Unknown, 4294901760, "kAudioChannelLayoutTag_Unknown")
    requireEqual(kAudioChannelLayoutTag_UseChannelBitmap, 65536, "kAudioChannelLayoutTag_UseChannelBitmap")
    requireEqual(kAudioChannelLayoutTag_UseChannelDescriptions, 0, "kAudioChannelLayoutTag_UseChannelDescriptions")
    requireEqual(kAudioChannelLayoutTag_WAVE_2_1, 8716291, "kAudioChannelLayoutTag_WAVE_2_1")
    requireEqual(kAudioChannelLayoutTag_WAVE_3_0, 7405571, "kAudioChannelLayoutTag_WAVE_3_0")
    requireEqual(kAudioChannelLayoutTag_WAVE_4_0_A, 8650756, "kAudioChannelLayoutTag_WAVE_4_0_A")
    requireEqual(kAudioChannelLayoutTag_WAVE_4_0_B, 12124164, "kAudioChannelLayoutTag_WAVE_4_0_B")
    requireEqual(kAudioChannelLayoutTag_WAVE_5_0_A, 7667717, "kAudioChannelLayoutTag_WAVE_5_0_A")
    requireEqual(kAudioChannelLayoutTag_WAVE_5_0_B, 12189701, "kAudioChannelLayoutTag_WAVE_5_0_B")
    requireEqual(kAudioChannelLayoutTag_WAVE_5_1_A, 7929862, "kAudioChannelLayoutTag_WAVE_5_1_A")
    requireEqual(kAudioChannelLayoutTag_WAVE_5_1_B, 12255238, "kAudioChannelLayoutTag_WAVE_5_1_B")
    requireEqual(kAudioChannelLayoutTag_WAVE_6_1, 12320775, "kAudioChannelLayoutTag_WAVE_6_1")
    requireEqual(kAudioChannelLayoutTag_WAVE_7_1, 12386312, "kAudioChannelLayoutTag_WAVE_7_1")
    requireEqual(kAudioChannelLayoutTag_XY, 6881282, "kAudioChannelLayoutTag_XY")
    requireEqual(kAppleLosslessFormatFlag_16BitSourceData, 1, "kAppleLosslessFormatFlag_16BitSourceData")
    requireEqual(kAppleLosslessFormatFlag_20BitSourceData, 2, "kAppleLosslessFormatFlag_20BitSourceData")
    requireEqual(kAppleLosslessFormatFlag_24BitSourceData, 3, "kAppleLosslessFormatFlag_24BitSourceData")
    requireEqual(kAppleLosslessFormatFlag_32BitSourceData, 4, "kAppleLosslessFormatFlag_32BitSourceData")
    requireEqual(kAudioFormatFlagIsAlignedHigh, 16, "kAudioFormatFlagIsAlignedHigh")
    requireEqual(kAudioFormatFlagIsBigEndian, 2, "kAudioFormatFlagIsBigEndian")
    requireEqual(kAudioFormatFlagIsFloat, 1, "kAudioFormatFlagIsFloat")
    requireEqual(kAudioFormatFlagIsNonInterleaved, 32, "kAudioFormatFlagIsNonInterleaved")
    requireEqual(kAudioFormatFlagIsNonMixable, 64, "kAudioFormatFlagIsNonMixable")
    requireEqual(kAudioFormatFlagIsPacked, 8, "kAudioFormatFlagIsPacked")
    requireEqual(kAudioFormatFlagIsSignedInteger, 4, "kAudioFormatFlagIsSignedInteger")
    requireEqual(kAudioFormatFlagsAreAllClear, 2147483648, "kAudioFormatFlagsAreAllClear")
    requireEqual(kLinearPCMFormatFlagIsAlignedHigh, 16, "kLinearPCMFormatFlagIsAlignedHigh")
    requireEqual(kLinearPCMFormatFlagIsBigEndian, 2, "kLinearPCMFormatFlagIsBigEndian")
    requireEqual(kLinearPCMFormatFlagIsFloat, 1, "kLinearPCMFormatFlagIsFloat")
    requireEqual(kLinearPCMFormatFlagIsNonInterleaved, 32, "kLinearPCMFormatFlagIsNonInterleaved")
    requireEqual(kLinearPCMFormatFlagIsNonMixable, 64, "kLinearPCMFormatFlagIsNonMixable")
    requireEqual(kLinearPCMFormatFlagIsPacked, 8, "kLinearPCMFormatFlagIsPacked")
    requireEqual(kLinearPCMFormatFlagIsSignedInteger, 4, "kLinearPCMFormatFlagIsSignedInteger")
    requireEqual(kLinearPCMFormatFlagsAreAllClear, 2147483648, "kLinearPCMFormatFlagsAreAllClear")
    requireEqual(kLinearPCMFormatFlagsSampleFractionMask, 8064, "kLinearPCMFormatFlagsSampleFractionMask")
    requireEqual(kLinearPCMFormatFlagsSampleFractionShift, 7, "kLinearPCMFormatFlagsSampleFractionShift")
    requireEqual(kAudioFormatFlagsAudioUnitCanonical, 3116, "kAudioFormatFlagsAudioUnitCanonical")
    requireEqual(kAudioFormatFlagsCanonical, 12, "kAudioFormatFlagsCanonical")
    requireEqual(kAudioFormatFlagsNativeEndian, 0, "kAudioFormatFlagsNativeEndian")
    requireEqual(kAudioFormatFlagsNativeFloatPacked, 9, "kAudioFormatFlagsNativeFloatPacked")
    requireEqual(kAudioFormat60958AC3, 1667326771, "kAudioFormat60958AC3")
    requireEqual(kAudioFormatAC3, 1633889587, "kAudioFormatAC3")
    requireEqual(kAudioFormatAES3, 1634038579, "kAudioFormatAES3")
    requireEqual(kAudioFormatALaw, 1634492791, "kAudioFormatALaw")
    requireEqual(kAudioFormatAMR, 1935764850, "kAudioFormatAMR")
    requireEqual(kAudioFormatAMR_WB, 1935767394, "kAudioFormatAMR_WB")
    requireEqual(kAudioFormatAPAC, 1634754915, "kAudioFormatAPAC")
    requireEqual(kAudioFormatAppleIMA4, 1768775988, "kAudioFormatAppleIMA4")
    requireEqual(kAudioFormatAppleLossless, 1634492771, "kAudioFormatAppleLossless")
    requireEqual(kAudioFormatAudible, 1096107074, "kAudioFormatAudible")
    requireEqual(kAudioFormatDVIIntelIMA, 1836253201, "kAudioFormatDVIIntelIMA")
    requireEqual(kAudioFormatEnhancedAC3, 1700998451, "kAudioFormatEnhancedAC3")
    requireEqual(kAudioFormatFLAC, 1718378851, "kAudioFormatFLAC")
    requireEqual(kAudioFormatLinearPCM, 1819304813, "kAudioFormatLinearPCM")
    requireEqual(kAudioFormatMACE3, 1296122675, "kAudioFormatMACE3")
    requireEqual(kAudioFormatMACE6, 1296122678, "kAudioFormatMACE6")
    requireEqual(kAudioFormatMIDIStream, 1835623529, "kAudioFormatMIDIStream")
    requireEqual(kAudioFormatMPEG4AAC, 1633772320, "kAudioFormatMPEG4AAC")
    requireEqual(kAudioFormatMPEG4AAC_ELD, 1633772389, "kAudioFormatMPEG4AAC_ELD")
    requireEqual(kAudioFormatMPEG4AAC_ELD_SBR, 1633772390, "kAudioFormatMPEG4AAC_ELD_SBR")
    requireEqual(kAudioFormatMPEG4AAC_ELD_V2, 1633772391, "kAudioFormatMPEG4AAC_ELD_V2")
    requireEqual(kAudioFormatMPEG4AAC_HE, 1633772392, "kAudioFormatMPEG4AAC_HE")
    requireEqual(kAudioFormatMPEG4AAC_HE_V2, 1633772400, "kAudioFormatMPEG4AAC_HE_V2")
    requireEqual(kAudioFormatMPEG4AAC_LD, 1633772396, "kAudioFormatMPEG4AAC_LD")
    requireEqual(kAudioFormatMPEG4AAC_Spatial, 1633772403, "kAudioFormatMPEG4AAC_Spatial")
    requireEqual(kAudioFormatMPEG4CELP, 1667591280, "kAudioFormatMPEG4CELP")
    requireEqual(kAudioFormatMPEG4HVXC, 1752594531, "kAudioFormatMPEG4HVXC")
    requireEqual(kAudioFormatMPEG4TwinVQ, 1953986161, "kAudioFormatMPEG4TwinVQ")
    requireEqual(kAudioFormatMPEGD_USAC, 1970495843, "kAudioFormatMPEGD_USAC")
    requireEqual(kAudioFormatMPEGLayer1, 778924081, "kAudioFormatMPEGLayer1")
    requireEqual(kAudioFormatMPEGLayer2, 778924082, "kAudioFormatMPEGLayer2")
    requireEqual(kAudioFormatMPEGLayer3, 778924083, "kAudioFormatMPEGLayer3")
    requireEqual(kAudioFormatMicrosoftGSM, 1836253233, "kAudioFormatMicrosoftGSM")
    requireEqual(kAudioFormatOpus, 1869641075, "kAudioFormatOpus")
    requireEqual(kAudioFormatParameterValueStream, 1634760307, "kAudioFormatParameterValueStream")
    requireEqual(kAudioFormatQDesign, 1363430723, "kAudioFormatQDesign")
    requireEqual(kAudioFormatQDesign2, 1363430706, "kAudioFormatQDesign2")
    requireEqual(kAudioFormatQUALCOMM, 1365470320, "kAudioFormatQUALCOMM")
    requireEqual(kAudioFormatTimeCode, 1953066341, "kAudioFormatTimeCode")
    requireEqual(kAudioFormatULaw, 1970037111, "kAudioFormatULaw")
    requireEqual(kAudioFormatiLBC, 1768710755, "kAudioFormatiLBC")
    requireEqual(kAudio_BadFilePathError, 561017960, "kAudio_BadFilePathError")
    requireEqual(kAudio_FileNotFoundError, -43, "kAudio_FileNotFoundError")
    requireEqual(kAudio_FilePermissionError, -54, "kAudio_FilePermissionError")
    requireEqual(kAudio_MemFullError, -108, "kAudio_MemFullError")
    requireEqual(kAudio_NoError, 0, "kAudio_NoError")
    requireEqual(kAudio_ParamError, -50, "kAudio_ParamError")
    requireEqual(kAudio_TooManyFilesOpenError, -42, "kAudio_TooManyFilesOpenError")
    requireEqual(kAudio_UnimplementedError, -4, "kAudio_UnimplementedError")
    requireEqual(kAudioStreamAnyRate, 0.0, "kAudioStreamAnyRate")
    requireEqual(CA_PREFER_FIXED_POINT, 1, "CA_PREFER_FIXED_POINT")
    requireEqual(COREAUDIOTYPES_VERSION, 20211130, "COREAUDIOTYPES_VERSION")
    requireEqual(kAudioUnitSampleFractionBits, 24, "kAudioUnitSampleFractionBits")
    requireEqual(AudioChannelBitmap.bit_Center.rawValue, UInt32(1 << 2), "AudioChannelBitmap.bit_Center")
    requireEqual(AudioChannelBitmap.bit_CenterSurround.rawValue, UInt32(1 << 8), "AudioChannelBitmap.bit_CenterSurround")
    requireEqual(AudioChannelBitmap.bit_CenterTopFront.rawValue, UInt32(1 << 13), "AudioChannelBitmap.bit_CenterTopFront")
    requireEqual(AudioChannelBitmap.bit_CenterTopMiddle.rawValue, UInt32(1 << 11), "AudioChannelBitmap.bit_CenterTopMiddle")
    requireEqual(AudioChannelBitmap.bit_CenterTopRear.rawValue, UInt32(1 << 25), "AudioChannelBitmap.bit_CenterTopRear")
    requireEqual(AudioChannelBitmap.bit_LFEScreen.rawValue, UInt32(1 << 3), "AudioChannelBitmap.bit_LFEScreen")
    requireEqual(AudioChannelBitmap.bit_Left.rawValue, UInt32(1 << 0), "AudioChannelBitmap.bit_Left")
    requireEqual(AudioChannelBitmap.bit_LeftCenter.rawValue, UInt32(1 << 6), "AudioChannelBitmap.bit_LeftCenter")
    requireEqual(AudioChannelBitmap.bit_LeftSurround.rawValue, UInt32(1 << 4), "AudioChannelBitmap.bit_LeftSurround")
    requireEqual(AudioChannelBitmap.bit_LeftSurroundDirect.rawValue, UInt32(1 << 9), "AudioChannelBitmap.bit_LeftSurroundDirect")
    requireEqual(AudioChannelBitmap.bit_LeftTopFront.rawValue, UInt32(1 << 12), "AudioChannelBitmap.bit_LeftTopFront")
    requireEqual(AudioChannelBitmap.bit_LeftTopMiddle.rawValue, UInt32(1 << 21), "AudioChannelBitmap.bit_LeftTopMiddle")
    requireEqual(AudioChannelBitmap.bit_LeftTopRear.rawValue, UInt32(1 << 24), "AudioChannelBitmap.bit_LeftTopRear")
    requireEqual(AudioChannelBitmap.bit_Right.rawValue, UInt32(1 << 1), "AudioChannelBitmap.bit_Right")
    requireEqual(AudioChannelBitmap.bit_RightCenter.rawValue, UInt32(1 << 7), "AudioChannelBitmap.bit_RightCenter")
    requireEqual(AudioChannelBitmap.bit_RightSurround.rawValue, UInt32(1 << 5), "AudioChannelBitmap.bit_RightSurround")
    requireEqual(AudioChannelBitmap.bit_RightSurroundDirect.rawValue, UInt32(1 << 10), "AudioChannelBitmap.bit_RightSurroundDirect")
    requireEqual(AudioChannelBitmap.bit_RightTopFront.rawValue, UInt32(1 << 14), "AudioChannelBitmap.bit_RightTopFront")
    requireEqual(AudioChannelBitmap.bit_RightTopMiddle.rawValue, UInt32(1 << 23), "AudioChannelBitmap.bit_RightTopMiddle")
    requireEqual(AudioChannelBitmap.bit_RightTopRear.rawValue, UInt32(1 << 26), "AudioChannelBitmap.bit_RightTopRear")
    requireEqual(AudioChannelBitmap.bit_TopBackCenter.rawValue, UInt32(1 << 16), "AudioChannelBitmap.bit_TopBackCenter")
    requireEqual(AudioChannelBitmap.bit_TopBackLeft.rawValue, UInt32(1 << 15), "AudioChannelBitmap.bit_TopBackLeft")
    requireEqual(AudioChannelBitmap.bit_TopBackRight.rawValue, UInt32(1 << 17), "AudioChannelBitmap.bit_TopBackRight")
    requireEqual(AudioChannelBitmap.bit_TopCenterSurround.rawValue, UInt32(1 << 11), "AudioChannelBitmap.bit_TopCenterSurround")
    requireEqual(AudioChannelBitmap.bit_VerticalHeightCenter.rawValue, UInt32(1 << 13), "AudioChannelBitmap.bit_VerticalHeightCenter")
    requireEqual(AudioChannelBitmap.bit_VerticalHeightLeft.rawValue, UInt32(1 << 12), "AudioChannelBitmap.bit_VerticalHeightLeft")
    requireEqual(AudioChannelBitmap.bit_VerticalHeightRight.rawValue, UInt32(1 << 14), "AudioChannelBitmap.bit_VerticalHeightRight")
    requireEqual(AudioChannelCoordinateIndex.coordinates_Azimuth, .coordinates_LeftRight, "AudioChannelCoordinateIndex.coordinates_Azimuth")
    requireEqual(AudioChannelCoordinateIndex.coordinates_Azimuth.rawValue, AudioChannelCoordinateIndex.coordinates_LeftRight.rawValue, "AudioChannelCoordinateIndex.coordinates_Azimuth.rawValue")
    requireEqual(AudioChannelCoordinateIndex.coordinates_BackFront.rawValue, 1, "AudioChannelCoordinateIndex.coordinates_BackFront")
    requireEqual(AudioChannelCoordinateIndex.coordinates_Distance, .coordinates_DownUp, "AudioChannelCoordinateIndex.coordinates_Distance")
    requireEqual(AudioChannelCoordinateIndex.coordinates_Distance.rawValue, AudioChannelCoordinateIndex.coordinates_DownUp.rawValue, "AudioChannelCoordinateIndex.coordinates_Distance.rawValue")
    requireEqual(AudioChannelCoordinateIndex.coordinates_DownUp.rawValue, 2, "AudioChannelCoordinateIndex.coordinates_DownUp")
    requireEqual(AudioChannelCoordinateIndex.coordinates_Elevation, .coordinates_BackFront, "AudioChannelCoordinateIndex.coordinates_Elevation")
    requireEqual(AudioChannelCoordinateIndex.coordinates_Elevation.rawValue, AudioChannelCoordinateIndex.coordinates_BackFront.rawValue, "AudioChannelCoordinateIndex.coordinates_Elevation.rawValue")
    requireEqual(AudioChannelCoordinateIndex.coordinates_LeftRight.rawValue, 0, "AudioChannelCoordinateIndex.coordinates_LeftRight")
    requireEqual(AudioChannelFlags.meters.rawValue, UInt32(1 << 2), "AudioChannelFlags.meters")
    requireEqual(AudioChannelFlags.rectangularCoordinates.rawValue, UInt32(1 << 0), "AudioChannelFlags.rectangularCoordinates")
    requireEqual(AudioChannelFlags.sphericalCoordinates.rawValue, UInt32(1 << 1), "AudioChannelFlags.sphericalCoordinates")
    requireEqual(AudioTimeStampFlags.hostTimeValid.rawValue, UInt32(1 << 1), "AudioTimeStampFlags.hostTimeValid")
    requireEqual(AudioTimeStampFlags.rateScalarValid.rawValue, UInt32(1 << 2), "AudioTimeStampFlags.rateScalarValid")
    requireEqual(AudioTimeStampFlags.smpteTimeValid.rawValue, UInt32(1 << 4), "AudioTimeStampFlags.smpteTimeValid")
    requireEqual(AudioTimeStampFlags.sampleHostTimeValid, [.sampleTimeValid, .hostTimeValid], "AudioTimeStampFlags.sampleHostTimeValid")
    requireEqual(
        AudioTimeStampFlags.sampleHostTimeValid.rawValue,
        AudioTimeStampFlags.sampleTimeValid.union(.hostTimeValid).rawValue,
        "AudioTimeStampFlags.sampleHostTimeValid.rawValue"
    )
    requireEqual(AudioTimeStampFlags.sampleTimeValid.rawValue, UInt32(1 << 0), "AudioTimeStampFlags.sampleTimeValid")
    requireEqual(AudioTimeStampFlags.wordClockTimeValid.rawValue, UInt32(1 << 3), "AudioTimeStampFlags.wordClockTimeValid")
    requireEqual(MPEG4ObjectID.AAC_LC.rawValue, 2, "MPEG4ObjectID.AAC_LC")
    requireEqual(MPEG4ObjectID.AAC_LTP.rawValue, 4, "MPEG4ObjectID.AAC_LTP")
    requireEqual(MPEG4ObjectID.aac_Main.rawValue, 1, "MPEG4ObjectID.aac_Main")
    requireEqual(MPEG4ObjectID.AAC_SBR.rawValue, 5, "MPEG4ObjectID.AAC_SBR")
    requireEqual(MPEG4ObjectID.AAC_SSR.rawValue, 3, "MPEG4ObjectID.AAC_SSR")
    requireEqual(MPEG4ObjectID.aac_Scalable.rawValue, 6, "MPEG4ObjectID.aac_Scalable")
    requireEqual(MPEG4ObjectID.CELP.rawValue, 8, "MPEG4ObjectID.CELP")
    requireEqual(MPEG4ObjectID.HVXC.rawValue, 9, "MPEG4ObjectID.HVXC")
    requireEqual(MPEG4ObjectID.twinVQ.rawValue, 7, "MPEG4ObjectID.twinVQ")
    requireEqual(SMPTETimeFlags.running.rawValue, UInt32(1 << 1), "SMPTETimeFlags.running")
    requireEqual(SMPTETimeFlags.valid.rawValue, UInt32(1 << 0), "SMPTETimeFlags.valid")
    requireEqual(SMPTETimeType.type2398.rawValue, 11, "SMPTETimeType.type2398")
    requireEqual(SMPTETimeType.type24.rawValue, 0, "SMPTETimeType.type24")
    requireEqual(SMPTETimeType.type25.rawValue, 1, "SMPTETimeType.type25")
    requireEqual(SMPTETimeType.type2997.rawValue, 4, "SMPTETimeType.type2997")
    requireEqual(SMPTETimeType.type2997Drop.rawValue, 5, "SMPTETimeType.type2997Drop")
    requireEqual(SMPTETimeType.type30.rawValue, 3, "SMPTETimeType.type30")
    requireEqual(SMPTETimeType.type30Drop.rawValue, 2, "SMPTETimeType.type30Drop")
    requireEqual(SMPTETimeType.type50.rawValue, 10, "SMPTETimeType.type50")
    requireEqual(SMPTETimeType.type5994.rawValue, 7, "SMPTETimeType.type5994")
    requireEqual(SMPTETimeType.type5994Drop.rawValue, 9, "SMPTETimeType.type5994Drop")
    requireEqual(SMPTETimeType.type60.rawValue, 6, "SMPTETimeType.type60")
    requireEqual(SMPTETimeType.type60Drop.rawValue, 8, "SMPTETimeType.type60Drop")
}

