import Foundation
@_spi(OpenUIKitHost) import Contacts

func testEnumRawValues() {
    expect(CNAuthorizationStatus.notDetermined.rawValue == 0, "auth notDetermined")
    expect(CNAuthorizationStatus.restricted.rawValue == 1, "auth restricted")
    expect(CNAuthorizationStatus.denied.rawValue == 2, "auth denied")
    expect(CNAuthorizationStatus.authorized.rawValue == 3, "auth authorized")
    expect(CNAuthorizationStatus.limited.rawValue == 4, "auth limited")
    expect(CNAuthorizationStatus.limited != CNAuthorizationStatus.denied, "auth inequality")
    expect(CNAuthorizationStatus(rawValue: 0) == .notDetermined, "auth rawValue init")
    expect(CNAuthorizationStatus.authorized.hashValue == CNAuthorizationStatus(rawValue: 3)?.hashValue, "auth hashValue")
    var hasher = Hasher()
    CNAuthorizationStatus.authorized.hash(into: &hasher)

    expect(CNContactSortOrder.none.rawValue == 0, "sort none")
    expect(CNContactSortOrder.userDefault.rawValue == 1, "sort userDefault")
    expect(CNContactSortOrder.givenName.rawValue == 2, "sort given")
    expect(CNContactSortOrder.familyName.rawValue == 3, "sort family")
    expect(CNContactSortOrder.givenName != .familyName, "sort inequality")
    expect(CNContactSortOrder(rawValue: 3) == .familyName, "sort rawValue init")
    expect(CNContactSortOrder.givenName.hashValue == CNContactSortOrder(rawValue: 2)?.hashValue, "sort hashValue")
    CNContactSortOrder.givenName.hash(into: &hasher)

    expect(CNContactType.person.rawValue == 0, "person type")
    expect(CNContactType.organization.rawValue == 1, "org type")
    expect(CNContactType.person != .organization, "contact type inequality")
    expect(CNContactType(rawValue: 1) == .organization, "type rawValue init")
    expect(CNContactType.person.hashValue == CNContactType(rawValue: 0)?.hashValue, "type hashValue")
    CNContactType.person.hash(into: &hasher)

    expect(CNEntityType.contacts.rawValue == 0, "entity")
    expect(CNEntityType(rawValue: 0) == .contacts, "entity rawValue init")
    expect(CNEntityType.contacts.hashValue == CNEntityType(rawValue: 0)?.hashValue, "entity hashValue")
    expect(!(CNEntityType.contacts != .contacts), "entity inequality")
    expect(CNEntityType(rawValue: 99) == nil, "entity missing rawValue")
    CNEntityType.contacts.hash(into: &hasher)

    expect(CNContainerType.unassigned.rawValue == 0, "unassigned")
    expect(CNContainerType.local.rawValue == 1, "local container type")
    expect(CNContainerType.exchange.rawValue == 2, "exchange")
    expect(CNContainerType.cardDAV.rawValue == 3, "carddav")
    expect(CNContainerType.local != .exchange, "container inequality")
    expect(CNContainerType(rawValue: 3) == .cardDAV, "container rawValue init")
    expect(CNContainerType.local.hashValue == CNContainerType(rawValue: 1)?.hashValue, "container hashValue")
    CNContainerType.local.hash(into: &hasher)

    expect(CNContactDisplayNameOrder.userDefault.rawValue == 0, "display userDefault")
    expect(CNContactDisplayNameOrder.givenNameFirst.rawValue == 1, "display given first")
    expect(CNContactDisplayNameOrder.familyNameFirst.rawValue == 2, "display order")
    expect(CNContactDisplayNameOrder.givenNameFirst != .familyNameFirst, "display inequality")
    expect(CNContactDisplayNameOrder(rawValue: 2) == .familyNameFirst, "display rawValue init")
    expect(CNContactDisplayNameOrder.givenNameFirst.hashValue == CNContactDisplayNameOrder(rawValue: 1)?.hashValue, "display hashValue")
    CNContactDisplayNameOrder.givenNameFirst.hash(into: &hasher)

    expect(CNContactFormatterStyle.fullName.rawValue == 0, "full name style")
    expect(CNContactFormatterStyle.phoneticFullName.rawValue == 1, "formatter style")
    expect(CNContactFormatterStyle.fullName != .phoneticFullName, "formatter inequality")
    expect(CNContactFormatterStyle(rawValue: 1) == .phoneticFullName, "formatter rawValue init")
    expect(CNContactFormatterStyle.fullName.hashValue == CNContactFormatterStyle(rawValue: 0)?.hashValue, "formatter hashValue")
    CNContactFormatterStyle.fullName.hash(into: &hasher)

    expect(CNPostalAddressFormatterStyle.mailingAddress.rawValue == 0, "postal style")
    expect(CNPostalAddressFormatterStyle(rawValue: 0) == .mailingAddress, "postal rawValue init")
    expect(
        CNPostalAddressFormatterStyle.mailingAddress.hashValue
            == CNPostalAddressFormatterStyle(rawValue: 0)?.hashValue,
        "postal hashValue"
    )
    expect(!(CNPostalAddressFormatterStyle.mailingAddress != .mailingAddress), "postal inequality")
    expect(CNPostalAddressFormatterStyle(rawValue: 9) == nil, "postal missing rawValue")
    CNPostalAddressFormatterStyle.mailingAddress.hash(into: &hasher)

    expect(CNError.Code.communicationError.rawValue == 1, "communicationError")
    expect(CNError.Code.dataAccessError.rawValue == 2, "dataAccessError")
    expect(CNError.Code.authorizationDenied.rawValue == 100, "authorizationDenied")
    expect(CNError.Code.noAccessableWritableContainers.rawValue == 101, "noAccessableWritableContainers")
    expect(CNError.Code.unauthorizedKeys.rawValue == 102, "unauthorizedKeys")
    expect(CNError.Code.featureDisabledByUser.rawValue == 103, "featureDisabledByUser")
    expect(CNError.Code.featureNotAvailable.rawValue == 104, "featureNotAvailable")
    expect(CNError.Code.recordDoesNotExist.rawValue == 200, "recordDoesNotExist")
    expect(CNError.Code.insertedRecordAlreadyExists.rawValue == 201, "insertedRecordAlreadyExists")
    expect(CNError.Code.containmentCycle.rawValue == 202, "containmentCycle")
    expect(CNError.Code.containmentScope.rawValue == 203, "containmentScope")
    expect(CNError.Code.recordIdentifierInvalid.rawValue == 204, "recordIdentifierInvalid")
    expect(CNError.Code.recordNotWritable.rawValue == 205, "recordNotWritable")
    expect(CNError.Code.parentRecordDoesNotExist.rawValue == 206, "parentRecordDoesNotExist")
    expect(CNError.Code.parentContainerNotWritable.rawValue == 207, "parentContainerNotWritable")
    expect(CNError.Code.validationMultipleErrors.rawValue == 300, "validationMultipleErrors")
    expect(CNError.Code.validationTypeMismatch.rawValue == 301, "validationTypeMismatch")
    expect(CNError.Code.validationConfigurationError.rawValue == 302, "validationConfigurationError")
    expect(CNError.Code.predicateInvalid.rawValue == 400, "predicateInvalid")
    expect(CNError.Code.policyViolation.rawValue == 500, "policyViolation")
    expect(CNError.Code.clientIdentifierInvalid.rawValue == 600, "clientIdentifierInvalid")
    expect(CNError.Code.clientIdentifierDoesNotExist.rawValue == 601, "clientIdentifierDoesNotExist")
    expect(CNError.Code.clientIdentifierCollision.rawValue == 602, "clientIdentifierCollision")
    expect(CNError.Code.changeHistoryExpired.rawValue == 700, "changeHistoryExpired")
    expect(CNError.Code.changeHistoryInvalidAnchor.rawValue == 701, "changeHistoryInvalidAnchor")
    expect(CNError.Code.changeHistoryInvalidFetchRequest.rawValue == 702, "changeHistoryInvalidFetchRequest")
    expect(CNError.Code.vCardMalformed.rawValue == 800, "vCardMalformed")
    expect(CNError.Code.vCardSummarizationError.rawValue == 801, "vCardSummarizationError")
    expect(CNError.Code(rawValue: 100) == .authorizationDenied, "error rawValue init")
    expect(CNError.Code.authorizationDenied != .featureNotAvailable, "error code inequality")
    expect(CNError.Code.authorizationDenied.hashValue == CNError.Code(rawValue: 100)?.hashValue, "error hashValue")
    CNError.Code.authorizationDenied.hash(into: &hasher)
    _ = hasher.finalize()
}
