import Foundation

// Unique member name anchors for declared coverage. Signatures are host-safe
// stubs: unavailable Apple services fail closed rather than invent success.

extension IntentParameter {
    public convenience init<T0, T1, T2, T3, T4, T5>(description p0: T0? = nil, `default` p1: T1? = nil, requestValueDialog p2: T2? = nil, inputConnectionBehavior p3: T3? = nil, optionsProvider p4: T4? = nil, resolvers p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4>(description p0: T0? = nil, `default` p1: T1? = nil, requestValueDialog p2: T2? = nil, inputConnectionBehavior p3: T3? = nil, optionsProvider p4: T4? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4>(description p0: T0? = nil, `default` p1: T1? = nil, requestValueDialog p2: T2? = nil, inputConnectionBehavior p3: T3? = nil, resolvers p4: T4? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3>(description p0: T0? = nil, `default` p1: T1? = nil, requestValueDialog p2: T2? = nil, inputConnectionBehavior p3: T3? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, resolvers p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(description p0: T0? = nil, `default` p1: T1? = nil, requestValueDialog p2: T2? = nil, requestDisambiguationDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, supportedValues p5: T5? = nil, optionsProvider p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(description p0: T0? = nil, `default` p1: T1? = nil, requestValueDialog p2: T2? = nil, requestDisambiguationDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, supportedValues p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(description p0: T0? = nil, `default` p1: T1? = nil, requestValueDialog p2: T2? = nil, requestDisambiguationDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, supportedValues p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6, T7>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, requestValueDialog p3: T3? = nil, requestDisambiguationDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, supportedValues p6: T6? = nil, optionsProvider p7: T7? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6, T7>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, requestValueDialog p3: T3? = nil, requestDisambiguationDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, supportedValues p6: T6? = nil, resolvers p7: T7? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, requestValueDialog p3: T3? = nil, requestDisambiguationDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, supportedValues p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(description p0: T0? = nil, `default` p1: T1? = nil, requestValueDialog p2: T2? = nil, requestDisambiguationDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(description p0: T0? = nil, `default` p1: T1? = nil, requestValueDialog p2: T2? = nil, requestDisambiguationDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(description p0: T0? = nil, `default` p1: T1? = nil, requestValueDialog p2: T2? = nil, requestDisambiguationDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, query p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(description p0: T0? = nil, `default` p1: T1? = nil, requestValueDialog p2: T2? = nil, requestDisambiguationDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, resolvers p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4>(description p0: T0? = nil, `default` p1: T1? = nil, requestValueDialog p2: T2? = nil, requestDisambiguationDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, requestValueDialog p2: T2? = nil, requestDisambiguationDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, requestValueDialog p2: T2? = nil, requestDisambiguationDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6, T7>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, requestValueDialog p3: T3? = nil, requestDisambiguationDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, optionsProvider p6: T6? = nil, resolvers p7: T7? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, requestValueDialog p3: T3? = nil, requestDisambiguationDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, optionsProvider p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, requestValueDialog p3: T3? = nil, requestDisambiguationDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, query p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, requestValueDialog p3: T3? = nil, requestDisambiguationDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, requestValueDialog p3: T3? = nil, requestDisambiguationDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, requestValueDialog p2: T2? = nil, inputConnectionBehavior p3: T3? = nil, optionsProvider p4: T4? = nil, resolvers p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4>(title p0: T0? = nil, description p1: T1? = nil, requestValueDialog p2: T2? = nil, inputConnectionBehavior p3: T3? = nil, optionsProvider p4: T4? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4>(title p0: T0? = nil, description p1: T1? = nil, requestValueDialog p2: T2? = nil, inputConnectionBehavior p3: T3? = nil, resolvers p4: T4? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3>(title p0: T0? = nil, description p1: T1? = nil, requestValueDialog p2: T2? = nil, inputConnectionBehavior p3: T3? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6, T7>(description p0: T0? = nil, `default` p1: T1? = nil, currencyCodes p2: T2? = nil, inclusiveRange p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, optionsProvider p6: T6? = nil, resolvers p7: T7? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(description p0: T0? = nil, `default` p1: T1? = nil, currencyCodes p2: T2? = nil, inclusiveRange p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, optionsProvider p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(description p0: T0? = nil, `default` p1: T1? = nil, currencyCodes p2: T2? = nil, inclusiveRange p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(description p0: T0? = nil, `default` p1: T1? = nil, currencyCodes p2: T2? = nil, inclusiveRange p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6, T7>(title p0: T0? = nil, description p1: T1? = nil, currencyCodes p2: T2? = nil, inclusiveRange p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, optionsProvider p6: T6? = nil, resolvers p7: T7? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, currencyCodes p2: T2? = nil, inclusiveRange p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, optionsProvider p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, currencyCodes p2: T2? = nil, inclusiveRange p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, currencyCodes p2: T2? = nil, inclusiveRange p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6, T7, T8>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, currencyCodes p3: T3? = nil, inclusiveRange p4: T4? = nil, requestValueDialog p5: T5? = nil, inputConnectionBehavior p6: T6? = nil, optionsProvider p7: T7? = nil, resolvers p8: T8? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6, T7>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, currencyCodes p3: T3? = nil, inclusiveRange p4: T4? = nil, requestValueDialog p5: T5? = nil, inputConnectionBehavior p6: T6? = nil, optionsProvider p7: T7? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6, T7>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, currencyCodes p3: T3? = nil, inclusiveRange p4: T4? = nil, requestValueDialog p5: T5? = nil, inputConnectionBehavior p6: T6? = nil, resolvers p7: T7? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, currencyCodes p3: T3? = nil, inclusiveRange p4: T4? = nil, requestValueDialog p5: T5? = nil, inputConnectionBehavior p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(description p0: T0? = nil, `default` p1: T1? = nil, supportedContentTypes p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(description p0: T0? = nil, `default` p1: T1? = nil, supportedContentTypes p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(description p0: T0? = nil, `default` p1: T1? = nil, supportedContentTypes p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, resolvers p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4>(description p0: T0? = nil, `default` p1: T1? = nil, supportedContentTypes p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, supportedTypeIdentifiers p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, supportedTypeIdentifiers p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, supportedTypeIdentifiers p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, supportedTypeIdentifiers p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6, T7>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, supportedContentTypes p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, optionsProvider p6: T6? = nil, resolvers p7: T7? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, supportedContentTypes p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, optionsProvider p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, supportedContentTypes p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, supportedContentTypes p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(description p0: T0? = nil, `default` p1: T1? = nil, mode p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(description p0: T0? = nil, `default` p1: T1? = nil, mode p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(description p0: T0? = nil, `default` p1: T1? = nil, mode p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, resolvers p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4>(description p0: T0? = nil, `default` p1: T1? = nil, mode p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, mode p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, mode p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, mode p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, resolvers p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4>(title p0: T0? = nil, description p1: T1? = nil, mode p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6, T7>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, mode p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, optionsProvider p6: T6? = nil, resolvers p7: T7? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, mode p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, optionsProvider p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, mode p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, mode p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6, T7>(description p0: T0? = nil, `default` p1: T1? = nil, supportedContentTypes p2: T2? = nil, requestValueDialog p3: T3? = nil, requestDisambiguationDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, optionsProvider p6: T6? = nil, resolvers p7: T7? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(description p0: T0? = nil, `default` p1: T1? = nil, supportedContentTypes p2: T2? = nil, requestValueDialog p3: T3? = nil, requestDisambiguationDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, optionsProvider p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(description p0: T0? = nil, `default` p1: T1? = nil, supportedContentTypes p2: T2? = nil, requestValueDialog p3: T3? = nil, requestDisambiguationDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, query p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(description p0: T0? = nil, `default` p1: T1? = nil, supportedContentTypes p2: T2? = nil, requestValueDialog p3: T3? = nil, requestDisambiguationDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(description p0: T0? = nil, `default` p1: T1? = nil, supportedContentTypes p2: T2? = nil, requestValueDialog p3: T3? = nil, requestDisambiguationDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6, T7, T8>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, supportedContentTypes p3: T3? = nil, requestValueDialog p4: T4? = nil, requestDisambiguationDialog p5: T5? = nil, inputConnectionBehavior p6: T6? = nil, optionsProvider p7: T7? = nil, resolvers p8: T8? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6, T7>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, supportedContentTypes p3: T3? = nil, requestValueDialog p4: T4? = nil, requestDisambiguationDialog p5: T5? = nil, inputConnectionBehavior p6: T6? = nil, optionsProvider p7: T7? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6, T7>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, supportedContentTypes p3: T3? = nil, requestValueDialog p4: T4? = nil, requestDisambiguationDialog p5: T5? = nil, inputConnectionBehavior p6: T6? = nil, query p7: T7? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6, T7>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, supportedContentTypes p3: T3? = nil, requestValueDialog p4: T4? = nil, requestDisambiguationDialog p5: T5? = nil, inputConnectionBehavior p6: T6? = nil, resolvers p7: T7? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, supportedContentTypes p3: T3? = nil, requestValueDialog p4: T4? = nil, requestDisambiguationDialog p5: T5? = nil, inputConnectionBehavior p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2>(description p0: T0? = nil, requestValueDialog p1: T1? = nil, inputConnectionBehavior p2: T2? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6, T7>(description p0: T0? = nil, defaultValue p1: T1? = nil, defaultUnit p2: T2? = nil, defaultUnitAdjustForLocale p3: T3? = nil, supportsNegativeNumbers p4: T4? = nil, requestValueDialog p5: T5? = nil, inputConnectionBehavior p6: T6? = nil, resolvers p7: T7? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(description p0: T0? = nil, defaultValue p1: T1? = nil, defaultUnit p2: T2? = nil, defaultUnitAdjustForLocale p3: T3? = nil, supportsNegativeNumbers p4: T4? = nil, requestValueDialog p5: T5? = nil, inputConnectionBehavior p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6, T7>(description p0: T0? = nil, defaultValue p1: T1? = nil, unit p2: T2? = nil, unitAdjustForLocale p3: T3? = nil, supportsNegativeNumbers p4: T4? = nil, requestValueDialog p5: T5? = nil, inputConnectionBehavior p6: T6? = nil, resolvers p7: T7? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(description p0: T0? = nil, defaultValue p1: T1? = nil, unit p2: T2? = nil, unitAdjustForLocale p3: T3? = nil, supportsNegativeNumbers p4: T4? = nil, requestValueDialog p5: T5? = nil, inputConnectionBehavior p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3>(description p0: T0? = nil, requestValueDialog p1: T1? = nil, inputConnectionBehavior p2: T2? = nil, optionsProvider p3: T3? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4>(description p0: T0? = nil, requestValueDialog p1: T1? = nil, inputConnectionBehavior p2: T2? = nil, resolvers p3: T3? = nil, optionsProvider p4: T4? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6, T7, T8>(title p0: T0? = nil, description p1: T1? = nil, defaultValue p2: T2? = nil, defaultUnit p3: T3? = nil, defaultUnitAdjustForLocale p4: T4? = nil, supportsNegativeNumbers p5: T5? = nil, requestValueDialog p6: T6? = nil, inputConnectionBehavior p7: T7? = nil, resolvers p8: T8? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6, T7>(title p0: T0? = nil, description p1: T1? = nil, defaultValue p2: T2? = nil, defaultUnit p3: T3? = nil, defaultUnitAdjustForLocale p4: T4? = nil, supportsNegativeNumbers p5: T5? = nil, requestValueDialog p6: T6? = nil, inputConnectionBehavior p7: T7? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6, T7, T8>(title p0: T0? = nil, description p1: T1? = nil, defaultValue p2: T2? = nil, unit p3: T3? = nil, unitAdjustForLocale p4: T4? = nil, supportsNegativeNumbers p5: T5? = nil, requestValueDialog p6: T6? = nil, inputConnectionBehavior p7: T7? = nil, resolvers p8: T8? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6, T7>(title p0: T0? = nil, description p1: T1? = nil, defaultValue p2: T2? = nil, unit p3: T3? = nil, unitAdjustForLocale p4: T4? = nil, supportsNegativeNumbers p5: T5? = nil, requestValueDialog p6: T6? = nil, inputConnectionBehavior p7: T7? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, requestValueDialog p2: T2? = nil, inputConnectionBehavior p3: T3? = nil, resolvers p4: T4? = nil, optionsProvider p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(description p0: T0? = nil, `default` p1: T1? = nil, kind p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(description p0: T0? = nil, `default` p1: T1? = nil, kind p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(description p0: T0? = nil, `default` p1: T1? = nil, kind p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, resolvers p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4>(description p0: T0? = nil, `default` p1: T1? = nil, kind p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, kind p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, kind p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, kind p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, resolvers p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4>(title p0: T0? = nil, description p1: T1? = nil, kind p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6, T7>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, kind p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, optionsProvider p6: T6? = nil, resolvers p7: T7? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, kind p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, optionsProvider p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, kind p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, kind p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4>(description p0: T0? = nil, requestValueDialog p1: T1? = nil, inputConnectionBehavior p2: T2? = nil, optionsProvider p3: T3? = nil, resolvers p4: T4? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(description p0: T0? = nil, inputOptions p1: T1? = nil, requestValueDialog p2: T2? = nil, inputConnectionBehavior p3: T3? = nil, optionsProvider p4: T4? = nil, resolvers p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4>(description p0: T0? = nil, inputOptions p1: T1? = nil, requestValueDialog p2: T2? = nil, inputConnectionBehavior p3: T3? = nil, optionsProvider p4: T4? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(description p0: T0? = nil, `default` p1: T1? = nil, inputOptions p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, resolvers p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4>(description p0: T0? = nil, `default` p1: T1? = nil, inputOptions p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, inputOptions p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, inputOptions p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, inputOptions p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, inputOptions p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(description p0: T0? = nil, `default` p1: T1? = nil, displayName p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, resolvers p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4>(description p0: T0? = nil, `default` p1: T1? = nil, displayName p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, displayName p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, displayName p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(description p0: T0? = nil, controlStyle p1: T1? = nil, inclusiveRange p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(description p0: T0? = nil, controlStyle p1: T1? = nil, inclusiveRange p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(description p0: T0? = nil, `default` p1: T1? = nil, controlStyle p2: T2? = nil, inclusiveRange p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(description p0: T0? = nil, `default` p1: T1? = nil, controlStyle p2: T2? = nil, inclusiveRange p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6, T7>(title p0: T0? = nil, description p1: T1? = nil, controlStyle p2: T2? = nil, inclusiveRange p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, optionsProvider p6: T6? = nil, resolvers p7: T7? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, controlStyle p2: T2? = nil, inclusiveRange p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, optionsProvider p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6, T7>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, controlStyle p3: T3? = nil, inclusiveRange p4: T4? = nil, requestValueDialog p5: T5? = nil, inputConnectionBehavior p6: T6? = nil, resolvers p7: T7? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, controlStyle p3: T3? = nil, inclusiveRange p4: T4? = nil, requestValueDialog p5: T5? = nil, inputConnectionBehavior p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4>(description p0: T0? = nil, `default` p1: T1? = nil, size p2: T2? = nil, inputConnectionBehavior p3: T3? = nil, query p4: T4? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4>(description p0: T0? = nil, `default` p1: T1? = nil, size p2: T2? = nil, inputConnectionBehavior p3: T3? = nil, resolvers p4: T4? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3>(description p0: T0? = nil, `default` p1: T1? = nil, size p2: T2? = nil, inputConnectionBehavior p3: T3? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, size p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, query p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, size p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, resolvers p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, size p3: T3? = nil, inputConnectionBehavior p4: T4? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4>(description p0: T0? = nil, `default` p1: T1? = nil, mode p2: T2? = nil, size p3: T3? = nil, inputConnectionBehavior p4: T4? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4>(title p0: T0? = nil, description p1: T1? = nil, mode p2: T2? = nil, size p3: T3? = nil, inputConnectionBehavior p4: T4? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, mode p3: T3? = nil, size p4: T4? = nil, inputConnectionBehavior p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(description p0: T0? = nil, `default` p1: T1? = nil, supportedContentTypes p2: T2? = nil, size p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, query p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(description p0: T0? = nil, `default` p1: T1? = nil, supportedContentTypes p2: T2? = nil, size p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, resolvers p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4>(description p0: T0? = nil, `default` p1: T1? = nil, supportedContentTypes p2: T2? = nil, size p3: T3? = nil, inputConnectionBehavior p4: T4? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, supportedContentTypes p3: T3? = nil, size p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, query p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, supportedContentTypes p3: T3? = nil, size p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, supportedContentTypes p3: T3? = nil, size p4: T4? = nil, inputConnectionBehavior p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(description p0: T0? = nil, `default` p1: T1? = nil, displayStyle p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(description p0: T0? = nil, `default` p1: T1? = nil, displayStyle p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(description p0: T0? = nil, `default` p1: T1? = nil, displayStyle p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, resolvers p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4>(description p0: T0? = nil, `default` p1: T1? = nil, displayStyle p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, displayStyle p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, displayStyle p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, optionsProvider p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, displayStyle p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil, resolvers p5: T5? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4>(title p0: T0? = nil, description p1: T1? = nil, displayStyle p2: T2? = nil, requestValueDialog p3: T3? = nil, inputConnectionBehavior p4: T4? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6, T7>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, displayStyle p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, optionsProvider p6: T6? = nil, resolvers p7: T7? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, displayStyle p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, optionsProvider p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5, T6>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, displayStyle p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil, resolvers p6: T6? = nil) { self.init(title: "") }
    public convenience init<T0, T1, T2, T3, T4, T5>(title p0: T0? = nil, description p1: T1? = nil, `default` p2: T2? = nil, displayStyle p3: T3? = nil, requestValueDialog p4: T4? = nil, inputConnectionBehavior p5: T5? = nil) { self.init(title: "") }
}

@propertyWrapper
public final class EntityProperty<Value>: NSObject, @unchecked Sendable
    where Value: _IntentValue, Value: Sendable {
    public var wrappedValue: Value {
        get { fatalError("EntityProperty value was not supplied") }
        set { _ = newValue }
    }
    public override init() { super.init() }
    public convenience init<T0, T1>(identifier p0: T0? = nil, asyncGetter p1: T1? = nil) { self.init() }
    public convenience init<T0, T1, T2>(identifier p0: T0? = nil, indexingKey p1: T1? = nil, getter p2: T2? = nil) { self.init() }
    public convenience init<T0, T1, T2>(identifier p0: T0? = nil, indexingKey p1: T1? = nil, getSetter p2: T2? = nil) { self.init() }
    public convenience init<T0, T1>(identifier p0: T0? = nil, indexingKey p1: T1? = nil) { self.init() }
    public convenience init<T0, T1, T2>(identifier p0: T0? = nil, customIndexingKey p1: T1? = nil, getter p2: T2? = nil) { self.init() }
    public convenience init<T0, T1, T2>(identifier p0: T0? = nil, customIndexingKey p1: T1? = nil, getSetter p2: T2? = nil) { self.init() }
    public convenience init<T0, T1>(identifier p0: T0? = nil, customIndexingKey p1: T1? = nil) { self.init() }
    public convenience init<T0, T1, T2>(identifier p0: T0? = nil, title p1: T1? = nil, asyncGetter p2: T2? = nil) { self.init() }
    public convenience init<T0, T1, T2, T3>(identifier p0: T0? = nil, title p1: T1? = nil, indexingKey p2: T2? = nil, getter p3: T3? = nil) { self.init() }
    public convenience init<T0, T1, T2, T3>(identifier p0: T0? = nil, title p1: T1? = nil, indexingKey p2: T2? = nil, getSetter p3: T3? = nil) { self.init() }
    public convenience init<T0, T1, T2>(identifier p0: T0? = nil, title p1: T1? = nil, indexingKey p2: T2? = nil) { self.init() }
    public convenience init<T0, T1, T2, T3>(identifier p0: T0? = nil, title p1: T1? = nil, customIndexingKey p2: T2? = nil, getter p3: T3? = nil) { self.init() }
    public convenience init<T0, T1, T2, T3>(identifier p0: T0? = nil, title p1: T1? = nil, customIndexingKey p2: T2? = nil, getSetter p3: T3? = nil) { self.init() }
    public convenience init<T0, T1, T2>(identifier p0: T0? = nil, title p1: T1? = nil, customIndexingKey p2: T2? = nil) { self.init() }
    public convenience init<T0, T1, T2>(identifier p0: T0? = nil, title p1: T1? = nil, getter p2: T2? = nil) { self.init() }
    public convenience init<T0, T1, T2>(identifier p0: T0? = nil, title p1: T1? = nil, getSetter p2: T2? = nil) { self.init() }
    public convenience init<T0, T1>(identifier p0: T0? = nil, title p1: T1? = nil) { self.init() }
    public convenience init<T0, T1>(identifier p0: T0? = nil, getter p1: T1? = nil) { self.init() }
    public convenience init<T0, T1>(identifier p0: T0? = nil, getSetter p1: T1? = nil) { self.init() }
    public convenience init<T0>(identifier p0: T0? = nil) { self.init() }
    public convenience init<T0>(indexingKey p0: T0? = nil) { self.init() }
    public convenience init<T0>(customIndexingKey p0: T0? = nil) { self.init() }
    public convenience init<T0, T1>(title p0: T0? = nil, indexingKey p1: T1? = nil) { self.init() }
    public convenience init<T0, T1>(title p0: T0? = nil, customIndexingKey p1: T1? = nil) { self.init() }
    public convenience init<T0>(title p0: T0? = nil) { self.init() }
    public convenience init<T0>(from p0: T0? = nil) { self.init() }
}
public typealias Property = EntityProperty

