import Accelerate
import Foundation

func testCStructFields0() {
    let s0 = DSPComplex()
    _ = s0.imag
    _ = s0.real
    let s1 = DSPDoubleComplex()
    _ = s1.imag
    _ = s1.real
    let s2 = DSPDoubleSplitComplex()
    _ = s2.imagp
    _ = s2.realp
    let s3 = DSPSplitComplex()
    _ = s3.imagp
    _ = s3.realp
    let s4 = vImageChannelDescription()
    _ = s4.full
    _ = s4.max
    _ = s4.min
    _ = s4.zero
    let s5 = vImageRGBPrimaries()
    _ = s5.blue_x
    _ = s5.blue_y
    _ = s5.green_x
    _ = s5.green_y
    _ = s5.red_x
    _ = s5.red_y
    _ = s5.white_x
    _ = s5.white_y
    let s6 = vImageTransferFunction()
    _ = s6.c0
    _ = s6.c1
    _ = s6.c2
    _ = s6.c3
    _ = s6.c4
    _ = s6.c5
    _ = s6.cutoff
    _ = s6.gamma
    let s7 = vImageWhitePoint()
    _ = s7.white_x
    _ = s7.white_y
}

func testCStructFields1() {
    let s8 = vImage_ARGBToYpCbCr()
    _ = s8.opaque
    let s9 = vImage_ARGBToYpCbCrMatrix()
    _ = s9.B_Cb_R_Cr
    _ = s9.B_Cr
    _ = s9.B_Yp
    _ = s9.G_Cb
    _ = s9.G_Cr
    _ = s9.G_Yp
    _ = s9.R_Cb
    _ = s9.R_Yp
    let s10 = vImage_AffineTransform()
    _ = s10.a
    _ = s10.b
    _ = s10.c
    _ = s10.d
    _ = s10.tx
    _ = s10.ty
    let s11 = vImage_AffineTransform_Double()
    _ = s11.a
    _ = s11.b
    _ = s11.c
    _ = s11.d
    _ = s11.tx
    _ = s11.ty
    let s12 = vImage_Buffer()
    _ = s12.data
    _ = s12.height
    _ = s12.rowBytes
    _ = s12.width
    let s13 = vImage_PerpsectiveTransform()
    _ = s13.a
    _ = s13.b
    _ = s13.c
    _ = s13.d
    _ = s13.tx
    _ = s13.ty
    _ = s13.v
    _ = s13.vx
    _ = s13.vy
    let s14 = vImage_YpCbCrPixelRange()
    _ = s14.CbCrMax
    _ = s14.CbCrMin
    _ = s14.CbCrRangeMax
    _ = s14.CbCr_bias
    _ = s14.YpMax
    _ = s14.YpMin
    _ = s14.YpRangeMax
    _ = s14.Yp_bias
    let s15 = vImage_YpCbCrToARGB()
    _ = s15.opaque
}

func testCStructFields2() {
    let s16 = vImage_YpCbCrToARGBMatrix()
    _ = s16.Cb_B
    _ = s16.Cb_G
    _ = s16.Cr_G
    _ = s16.Cr_R
    _ = s16.Yp
    let s17 = BNNSActivation()
    _ = s17.alpha
    _ = s17.beta
    _ = s17.function
    _ = s17.ioffset
    _ = s17.ioffset_per_channel
    _ = s17.iscale
    _ = s17.iscale_per_channel
    _ = s17.ishift
    _ = s17.ishift_per_channel
    let s18 = BNNSArithmeticBinary()
    _ = s18.in1
    _ = s18.in1_type
    _ = s18.in2
    _ = s18.in2_type
    _ = s18.out
    _ = s18.out_type
    let s19 = BNNSArithmeticTernary()
    _ = s19.in1
    _ = s19.in1_type
    _ = s19.in2
    _ = s19.in2_type
    _ = s19.in3
    _ = s19.in3_type
    _ = s19.out
    _ = s19.out_type
    let s20 = BNNSArithmeticUnary()
    _ = s20.in_type
    _ = s20.out
    _ = s20.out_type
    let s21 = BNNSConvolutionLayerParameters()
    _ = s21.activation
    _ = s21.bias
    _ = s21.in_channels
    _ = s21.k_height
    _ = s21.k_width
    _ = s21.out_channels
    _ = s21.weights
    _ = s21.x_padding
    _ = s21.x_stride
    _ = s21.y_padding
    _ = s21.y_stride
    let s22 = BNNSFilterParameters()
    _ = s22.alloc_memory
    _ = s22.flags
    _ = s22.free_memory
    _ = s22.n_threads
    let s23 = BNNSFullyConnectedLayerParameters()
    _ = s23.activation
    _ = s23.bias
    _ = s23.in_size
    _ = s23.out_size
    _ = s23.weights
}

func testCStructFields3() {
    let s24 = BNNSImageStackDescriptor()
    _ = s24.channels
    _ = s24.data_bias
    _ = s24.data_scale
    _ = s24.data_type
    _ = s24.height
    _ = s24.image_stride
    _ = s24.row_stride
    _ = s24.width
    let s25 = BNNSLSTMDataDescriptor()
    _ = s25.cell_state_desc
    _ = s25.data_desc
    _ = s25.hidden_desc
    let s26 = BNNSLSTMGateDescriptor()
    _ = s26.activation
    _ = s26.b_desc
    _ = s26.cw_desc
    _ = s26.hw_desc
    _ = s26.iw_desc
    let s27 = BNNSLayerData()
    _ = s27.data
    _ = s27.data_bias
    _ = s27.data_scale
    _ = s27.data_table
    _ = s27.data_type
    let s28 = BNNSLayerParametersActivation()
    _ = s28.activation
    _ = s28.axis_flags
    _ = s28.i_desc
    _ = s28.o_desc
    let s29 = BNNSLayerParametersArithmetic()
    _ = s29.activation
    _ = s29.arithmetic_function
    _ = s29.arithmetic_function_fields
    let s30 = BNNSLayerParametersBroadcastMatMul()
    _ = s30.a_is_weights
    _ = s30.alpha
    _ = s30.b_is_weights
    _ = s30.beta
    _ = s30.iA_desc
    _ = s30.iB_desc
    _ = s30.o_desc
    _ = s30.quadratic
    _ = s30.transA
    _ = s30.transB
    let s31 = BNNSLayerParametersConvolution()
    _ = s31.activation
    _ = s31.bias
    _ = s31.groups
    _ = s31.i_desc
    _ = s31.o_desc
    _ = s31.pad
    _ = s31.w_desc
    _ = s31.x_dilation_stride
    _ = s31.x_padding
    _ = s31.x_stride
    _ = s31.y_dilation_stride
    _ = s31.y_padding
    _ = s31.y_stride
}

func testCStructFields4() {
    let s32 = BNNSLayerParametersCropResize()
    _ = s32.box_coordinate_mode
    _ = s32.extrapolation_value
    _ = s32.method
    _ = s32.normalized_coordinates
    _ = s32.sampling_mode
    _ = s32.spatial_scale
    let s33 = BNNSLayerParametersDropout()
    _ = s33.control
    _ = s33.i_desc
    _ = s33.o_desc
    _ = s33.rate
    _ = s33.seed
    let s34 = BNNSLayerParametersEmbedding()
    _ = s34.dictionary
    _ = s34.flags
    _ = s34.i_desc
    _ = s34.max_norm
    _ = s34.norm_type
    _ = s34.o_desc
    _ = s34.padding_idx
    let s35 = BNNSLayerParametersFullyConnected()
    _ = s35.activation
    _ = s35.bias
    _ = s35.i_desc
    _ = s35.o_desc
    _ = s35.w_desc
    let s36 = BNNSLayerParametersGram()
    _ = s36.alpha
    _ = s36.i_desc
    _ = s36.o_desc
    let s37 = BNNSLayerParametersLSTM()
    _ = s37.batch_size
    _ = s37.candidate_gate
    _ = s37.dropout
    _ = s37.forget_gate
    _ = s37.hidden_activation
    _ = s37.hidden_size
    _ = s37.input_descriptor
    _ = s37.input_gate
    _ = s37.input_size
    _ = s37.lstm_flags
    _ = s37.num_layers
    _ = s37.output_descriptor
    _ = s37.output_gate
    _ = s37.seq_len
    _ = s37.sequence_descriptor
    let s38 = BNNSLayerParametersLossBase()
    _ = s38.function
    _ = s38.i_desc
    _ = s38.o_desc
    _ = s38.reduction
    let s39 = BNNSLayerParametersLossHuber()
    _ = s39.function
    _ = s39.huber_delta
    _ = s39.i_desc
    _ = s39.o_desc
    _ = s39.reduction
}

func testCStructFields5() {
    let s40 = BNNSLayerParametersLossSigmoidCrossEntropy()
    _ = s40.function
    _ = s40.i_desc
    _ = s40.label_smooth
    _ = s40.o_desc
    _ = s40.reduction
    let s41 = BNNSLayerParametersLossSoftmaxCrossEntropy()
    _ = s41.function
    _ = s41.i_desc
    _ = s41.label_smooth
    _ = s41.o_desc
    _ = s41.reduction
    let s42 = BNNSLayerParametersLossYolo()
    _ = s42.anchor_box_size
    _ = s42.anchors_data
    _ = s42.function
    _ = s42.huber_delta
    _ = s42.i_desc
    _ = s42.no_object_maximum_iou
    _ = s42.number_of_anchor_boxes
    _ = s42.number_of_grid_columns
    _ = s42.number_of_grid_rows
    _ = s42.o_desc
    _ = s42.object_minimum_iou
    _ = s42.reduction
    _ = s42.rescore
    _ = s42.scale_classification
    _ = s42.scale_no_object
    _ = s42.scale_object
    _ = s42.scale_wh
    _ = s42.scale_xy
    let s43 = BNNSLayerParametersMultiheadAttention()
    _ = s43.add_zero_attn
    _ = s43.dropout
    _ = s43.key
    _ = s43.key_attn_bias
    _ = s43.output
    _ = s43.query
    _ = s43.seed
    _ = s43.value
    _ = s43.value_attn_bias
    let s44 = BNNSLayerParametersNormalization()
    _ = s44.activation
    _ = s44.beta_desc
    _ = s44.epsilon
    _ = s44.gamma_desc
    _ = s44.i_desc
    _ = s44.momentum
    _ = s44.moving_mean_desc
    _ = s44.moving_variance_desc
    _ = s44.normalization_axis
    _ = s44.num_groups
    _ = s44.o_desc
    let s45 = BNNSLayerParametersPadding()
    _ = s45.i_desc
    _ = s45.o_desc
    _ = s45.padding_mode
    _ = s45.padding_size
    _ = s45.padding_value
    let s46 = BNNSLayerParametersPermute()
    _ = s46.i_desc
    _ = s46.o_desc
    _ = s46.permutation
    let s47 = BNNSLayerParametersPooling()
    _ = s47.activation
    _ = s47.bias
    _ = s47.i_desc
    _ = s47.k_height
    _ = s47.k_width
    _ = s47.o_desc
    _ = s47.pad
    _ = s47.pooling_function
    _ = s47.x_dilation_stride
    _ = s47.x_padding
    _ = s47.x_stride
    _ = s47.y_dilation_stride
    _ = s47.y_padding
    _ = s47.y_stride
}

func testCStructFields6() {
    let s48 = BNNSLayerParametersQuantization()
    _ = s48.axis_mask
    _ = s48.bias
    _ = s48.function
    _ = s48.i_desc
    _ = s48.o_desc
    _ = s48.scale
    let s49 = BNNSLayerParametersReduction()
    _ = s49.epsilon
    _ = s49.i_desc
    _ = s49.o_desc
    _ = s49.reduce_func
    _ = s49.w_desc
    let s50 = BNNSLayerParametersResize()
    _ = s50.align_corners
    _ = s50.i_desc
    _ = s50.method
    _ = s50.o_desc
    let s51 = BNNSLayerParametersTensorContraction()
    _ = s51.alpha
    _ = s51.beta
    _ = s51.iA_desc
    _ = s51.iB_desc
    _ = s51.o_desc
    _ = s51.operation
    let s52 = BNNSMHAProjectionParameters()
    _ = s52.bias
    _ = s52.target_desc
    _ = s52.weights
    let s53 = BNNSNDArrayDescriptor()
    _ = s53.data
    _ = s53.data_bias
    _ = s53.data_scale
    _ = s53.data_type
    _ = s53.flags
    _ = s53.layout
    _ = s53.size
    _ = s53.stride
    _ = s53.table_data
    _ = s53.table_data_type
    let s54 = BNNSOptimizerAdamFields()
    _ = s54.beta1
    _ = s54.beta2
    _ = s54.clip_gradients
    _ = s54.clip_gradients_max
    _ = s54.clip_gradients_min
    _ = s54.epsilon
    _ = s54.gradient_scale
    _ = s54.learning_rate
    _ = s54.regularization_func
    _ = s54.regularization_scale
    _ = s54.time_step
    let s55 = BNNSOptimizerAdamWithClippingFields()
    _ = s55.beta1
    _ = s55.beta2
    _ = s55.clip_gradients_max
    _ = s55.clip_gradients_max_norm
    _ = s55.clip_gradients_min
    _ = s55.clip_gradients_use_norm
    _ = s55.clipping_func
    _ = s55.epsilon
    _ = s55.gradient_scale
    _ = s55.learning_rate
    _ = s55.regularization_func
    _ = s55.regularization_scale
    _ = s55.time_step
}

func testCStructFields7() {
    let s56 = BNNSOptimizerRMSPropFields()
    _ = s56.alpha
    _ = s56.centered
    _ = s56.clip_gradients
    _ = s56.clip_gradients_max
    _ = s56.clip_gradients_min
    _ = s56.epsilon
    _ = s56.gradient_scale
    _ = s56.learning_rate
    _ = s56.momentum
    _ = s56.regularization_func
    _ = s56.regularization_scale
    let s57 = BNNSOptimizerRMSPropWithClippingFields()
    _ = s57.alpha
    _ = s57.centered
    _ = s57.clip_gradients_max
    _ = s57.clip_gradients_max_norm
    _ = s57.clip_gradients_min
    _ = s57.clip_gradients_use_norm
    _ = s57.clipping_func
    _ = s57.epsilon
    _ = s57.gradient_scale
    _ = s57.learning_rate
    _ = s57.momentum
    _ = s57.regularization_func
    _ = s57.regularization_scale
    let s58 = BNNSOptimizerSGDMomentumFields()
    _ = s58.clip_gradients
    _ = s58.clip_gradients_max
    _ = s58.clip_gradients_min
    _ = s58.gradient_scale
    _ = s58.learning_rate
    _ = s58.momentum
    _ = s58.nesterov
    _ = s58.regularization_func
    _ = s58.regularization_scale
    _ = s58.sgd_momentum_variant
    let s59 = BNNSOptimizerSGDMomentumWithClippingFields()
    _ = s59.clip_gradients_max
    _ = s59.clip_gradients_max_norm
    _ = s59.clip_gradients_min
    _ = s59.clip_gradients_use_norm
    _ = s59.clipping_func
    _ = s59.gradient_scale
    _ = s59.learning_rate
    _ = s59.momentum
    _ = s59.nesterov
    _ = s59.regularization_func
    _ = s59.regularization_scale
    _ = s59.sgd_momentum_variant
    let s60 = BNNSPoolingLayerParameters()
    _ = s60.activation
    _ = s60.bias
    _ = s60.in_channels
    _ = s60.k_height
    _ = s60.k_width
    _ = s60.out_channels
    _ = s60.pooling_function
    _ = s60.x_padding
    _ = s60.x_stride
    _ = s60.y_padding
    _ = s60.y_stride
    let s61 = BNNSSparsityParameters()
    _ = s61.flags
    _ = s61.sparsity_ratio
    _ = s61.sparsity_type
    _ = s61.target_system
    let s62 = BNNSTensor()
    _ = s62.data
    _ = s62.data_size_in_bytes
    _ = s62.data_type
    _ = s62.name
    _ = s62.rank
    _ = s62.shape
    _ = s62.stride
    let s63 = BNNSVectorDescriptor()
    _ = s63.data_bias
    _ = s63.data_scale
    _ = s63.data_type
    _ = s63.size
}

func testCStructFields8() {
    let s64 = DenseMatrix_Complex_Double()
    _ = s64.attributes
    _ = s64.columnCount
    _ = s64.columnStride
    _ = s64.data
    _ = s64.rowCount
    let s65 = DenseMatrix_Complex_Float()
    _ = s65.attributes
    _ = s65.columnCount
    _ = s65.columnStride
    _ = s65.data
    _ = s65.rowCount
    let s66 = DenseMatrix_Double()
    _ = s66.attributes
    _ = s66.columnCount
    _ = s66.columnStride
    _ = s66.data
    _ = s66.rowCount
    let s67 = DenseMatrix_Float()
    _ = s67.attributes
    _ = s67.columnCount
    _ = s67.columnStride
    _ = s67.data
    _ = s67.rowCount
    let s68 = DenseVector_Complex_Double()
    _ = s68.count
    _ = s68.data
    let s69 = DenseVector_Complex_Float()
    _ = s69.count
    _ = s69.data
    let s70 = DenseVector_Double()
    _ = s70.count
    _ = s70.data
    let s71 = DenseVector_Float()
    _ = s71.count
    _ = s71.data
}

func testCStructFields9() {
    let s72 = SparseAttributesComplex_t()
    _ = s72.conjugate_transpose
    _ = s72.kind
    _ = s72.transpose
    _ = s72.triangle
    let s73 = SparseAttributes_t()
    _ = s73.kind
    _ = s73.transpose
    _ = s73.triangle
    let s74 = SparseCGOptions()
    _ = s74.atol
    _ = s74.maxIterations
    _ = s74.reportError
    _ = s74.reportStatus
    _ = s74.rtol
    let s75 = SparseGMRESOptions()
    _ = s75.atol
    _ = s75.maxIterations
    _ = s75.nvec
    _ = s75.reportError
    _ = s75.reportStatus
    _ = s75.rtol
    _ = s75.variant
    let s76 = SparseIterativeMethod()
    _ = s76.method
    _ = s76.options
    let s77 = SparseLSMROptions()
    _ = s77.atol
    _ = s77.btol
    _ = s77.conditionLimit
    _ = s77.convergenceTest
    _ = s77.lambda
    _ = s77.maxIterations
    _ = s77.nvec
    _ = s77.reportError
    _ = s77.reportStatus
    _ = s77.rtol
    let s78 = SparseMatrixStructure()
    _ = s78.attributes
    _ = s78.blockSize
    _ = s78.columnCount
    _ = s78.columnStarts
    _ = s78.rowCount
    _ = s78.rowIndices
    let s79 = SparseMatrixStructureComplex()
    _ = s79.attributes
    _ = s79.blockSize
    _ = s79.columnCount
    _ = s79.columnStarts
    _ = s79.rowCount
    _ = s79.rowIndices
}

func testCStructFields10() {
    let s80 = SparseMatrix_Complex_Double()
    _ = s80.data
    _ = s80.structure
    let s81 = SparseMatrix_Complex_Float()
    _ = s81.data
    _ = s81.structure
    let s82 = SparseMatrix_Double()
    _ = s82.data
    _ = s82.structure
    let s83 = SparseMatrix_Float()
    _ = s83.data
    _ = s83.structure
    let s84 = SparseNumericFactorOptions()
    _ = s84.control
    _ = s84.pivotTolerance
    _ = s84.scaling
    _ = s84.scalingMethod
    _ = s84.zeroTolerance
    let s85 = SparseOpaqueFactorization_Complex_Double()
    _ = s85.attributes
    _ = s85.numericFactorization
    _ = s85.solveWorkspaceRequiredPerRHS
    _ = s85.solveWorkspaceRequiredStatic
    _ = s85.status
    _ = s85.symbolicFactorization
    _ = s85.userFactorStorage
    let s86 = SparseOpaqueFactorization_Complex_Float()
    _ = s86.attributes
    _ = s86.numericFactorization
    _ = s86.solveWorkspaceRequiredPerRHS
    _ = s86.solveWorkspaceRequiredStatic
    _ = s86.status
    _ = s86.symbolicFactorization
    _ = s86.userFactorStorage
    let s87 = SparseOpaqueFactorization_Double()
    _ = s87.attributes
    _ = s87.numericFactorization
    _ = s87.solveWorkspaceRequiredPerRHS
    _ = s87.solveWorkspaceRequiredStatic
    _ = s87.status
    _ = s87.symbolicFactorization
    _ = s87.userFactorStorage
}

func testCStructFields11() {
    let s88 = SparseOpaqueFactorization_Float()
    _ = s88.attributes
    _ = s88.numericFactorization
    _ = s88.solveWorkspaceRequiredPerRHS
    _ = s88.solveWorkspaceRequiredStatic
    _ = s88.status
    _ = s88.symbolicFactorization
    _ = s88.userFactorStorage
    let s89 = SparseOpaquePreconditioner_Complex_Double()
    _ = s89.apply
    _ = s89.mem
    _ = s89.type
    let s90 = SparseOpaquePreconditioner_Complex_Float()
    _ = s90.apply
    _ = s90.mem
    _ = s90.type
    let s91 = SparseOpaquePreconditioner_Double()
    _ = s91.apply
    _ = s91.mem
    _ = s91.type
    let s92 = SparseOpaquePreconditioner_Float()
    _ = s92.apply
    _ = s92.mem
    _ = s92.type
    let s93 = SparseOpaqueSubfactor_Complex_Double()
    _ = s93.attributes
    _ = s93.contents
    _ = s93.factor
    _ = s93.workspaceRequiredPerRHS
    _ = s93.workspaceRequiredStatic
    let s94 = SparseOpaqueSubfactor_Complex_Float()
    _ = s94.attributes
    _ = s94.contents
    _ = s94.factor
    _ = s94.workspaceRequiredPerRHS
    _ = s94.workspaceRequiredStatic
    let s95 = SparseOpaqueSubfactor_Double()
    _ = s95.attributes
    _ = s95.contents
    _ = s95.factor
    _ = s95.workspaceRequiredPerRHS
    _ = s95.workspaceRequiredStatic
}

func testCStructFields12() {
    let s96 = SparseOpaqueSubfactor_Float()
    _ = s96.attributes
    _ = s96.contents
    _ = s96.factor
    _ = s96.workspaceRequiredPerRHS
    _ = s96.workspaceRequiredStatic
    let s97 = SparseOpaqueSymbolicFactorization()
    _ = s97.attributes
    _ = s97.blockSize
    _ = s97.columnCount
    _ = s97.factorSize_Double
    _ = s97.factorSize_Float
    _ = s97.factorization
    _ = s97.rowCount
    _ = s97.status
    _ = s97.type
    _ = s97.workspaceSize_Double
    _ = s97.workspaceSize_Float
    let s98 = SparseSymbolicFactorOptions()
    _ = s98.control
    _ = s98.free
    _ = s98.ignoreRowsAndColumns
    _ = s98.malloc
    _ = s98.order
    _ = s98.orderMethod
    _ = s98.reportError
    let s99 = bnns_graph_argument_t()
    _ = s99.data_ptr_size
    let s100 = bnns_graph_compile_options_t()
    _ = s100.data
    _ = s100.size
    let s101 = bnns_graph_context_t()
    _ = s101.data
    _ = s101.size
    let s102 = bnns_graph_shape_t()
    _ = s102.rank
    _ = s102.shape
    let s103 = bnns_graph_t()
    _ = s103.data
    _ = s103.size
}

func testCStructFields13() {
    let s104 = bnns_user_message_data_t()
    _ = s104.data
    _ = s104.size
    let s105 = quadrature_integrate_function()
    _ = s105.fun
    _ = s105.fun_arg
    let s106 = quadrature_integrate_options()
    _ = s106.abs_tolerance
    _ = s106.integrator
    _ = s106.max_intervals
    _ = s106.qag_points_per_interval
    _ = s106.rel_tolerance
    let s107 = vDSP_int24()
    _ = s107.bytes
    let s108 = vDSP_uint24()
    _ = s108.bytes
}
