import Accelerate
import Foundation

// Apple-measured raw values from scratch/oracle-2026-09-14/sparse-enum-2026-09-15.txt
// (macOS 26.1 / Xcode 26.1, `import Accelerate` probe via xcrun swiftc).
// Each test below is table-driven over one enum family (sharing allowed).

func testSparseOracleFactorizationExtraValues() {
    precondition(SparseFactorizationLDLTSBK.rawValue == 3)
    precondition(SparseFactorization_t(rawValue: 3) == SparseFactorizationLDLTSBK)
    precondition(SparseFactorizationLDLTTPP.rawValue == 4)
    precondition(SparseFactorization_t(rawValue: 4) == SparseFactorizationLDLTTPP)
    precondition(SparseFactorizationLU.rawValue == 80)
    precondition(SparseFactorization_t(rawValue: 80) == SparseFactorizationLU)
    precondition(SparseFactorizationLUUnpivoted.rawValue == 81)
    precondition(SparseFactorization_t(rawValue: 81) == SparseFactorizationLUUnpivoted)
    precondition(SparseFactorizationLUSPP.rawValue == 82)
    precondition(SparseFactorization_t(rawValue: 82) == SparseFactorizationLUSPP)
    precondition(SparseFactorizationLUTPP.rawValue == 83)
    precondition(SparseFactorization_t(rawValue: 83) == SparseFactorizationLUTPP)
}

func testSparseOracleStatusValues() {
    precondition(SparseFactorizationFailed.rawValue == -1)
    precondition(SparseStatus_t(rawValue: -1) == SparseFactorizationFailed)
    precondition(SparseMatrixIsSingular.rawValue == -2)
    precondition(SparseStatus_t(rawValue: -2) == SparseMatrixIsSingular)
    precondition(SparseInternalError.rawValue == -3)
    precondition(SparseStatus_t(rawValue: -3) == SparseInternalError)
    precondition(SparseParameterError.rawValue == -4)
    precondition(SparseStatus_t(rawValue: -4) == SparseParameterError)
    precondition(SparseStatusOK.rawValue == 0)
    precondition(SparseStatus_t(rawValue: 0) == SparseStatusOK)
    precondition(SparseStatusReleased.rawValue == -2147483647)
    precondition(SparseStatus_t(rawValue: -2147483647) == SparseStatusReleased)
}

func testSparseOracleSubfactorTriangleUpdateValues() {
    precondition(SparseSubfactorInvalid.rawValue == 0)
    precondition(SparseSubfactor_t(rawValue: 0) == SparseSubfactorInvalid)
    precondition(SparseSubfactorP.rawValue == 1)
    precondition(SparseSubfactor_t(rawValue: 1) == SparseSubfactorP)
    precondition(SparseSubfactorS.rawValue == 2)
    precondition(SparseSubfactor_t(rawValue: 2) == SparseSubfactorS)
    precondition(SparseSubfactorL.rawValue == 3)
    precondition(SparseSubfactor_t(rawValue: 3) == SparseSubfactorL)
    precondition(SparseSubfactorD.rawValue == 4)
    precondition(SparseSubfactor_t(rawValue: 4) == SparseSubfactorD)
    precondition(SparseSubfactorPLPS.rawValue == 5)
    precondition(SparseSubfactor_t(rawValue: 5) == SparseSubfactorPLPS)
    precondition(SparseSubfactorQ.rawValue == 6)
    precondition(SparseSubfactor_t(rawValue: 6) == SparseSubfactorQ)
    precondition(SparseSubfactorR.rawValue == 7)
    precondition(SparseSubfactor_t(rawValue: 7) == SparseSubfactorR)
    precondition(SparseSubfactorRP.rawValue == 8)
    precondition(SparseSubfactor_t(rawValue: 8) == SparseSubfactorRP)
    precondition(SparseSubfactorSr.rawValue == 9)
    precondition(SparseSubfactor_t(rawValue: 9) == SparseSubfactorSr)
    precondition(SparseSubfactorSc.rawValue == 10)
    precondition(SparseSubfactor_t(rawValue: 10) == SparseSubfactorSc)
    precondition(SparseUpperTriangle.rawValue == 0)
    precondition(SparseTriangle_t(rawValue: 0) == SparseUpperTriangle)
    precondition(SparseLowerTriangle.rawValue == 1)
    precondition(SparseTriangle_t(rawValue: 1) == SparseLowerTriangle)
    precondition(SparseUpdatePartialRefactor.rawValue == 0)
    precondition(SparseUpdate_t(rawValue: 0) == SparseUpdatePartialRefactor)
}

func testSparseOracleKindOrderScalingValues() {
    precondition(SparseOrdinary.rawValue == 0)
    precondition(SparseKind_t(rawValue: 0) == SparseOrdinary)
    precondition(SparseTriangular.rawValue == 1)
    precondition(SparseKind_t(rawValue: 1) == SparseTriangular)
    precondition(SparseUnitTriangular.rawValue == 2)
    precondition(SparseKind_t(rawValue: 2) == SparseUnitTriangular)
    precondition(SparseSymmetric.rawValue == 3)
    precondition(SparseKind_t(rawValue: 3) == SparseSymmetric)
    precondition(SparseHermitian.rawValue == 7)
    precondition(SparseKind_t(rawValue: 7) == SparseHermitian)
    precondition(SparseOrderDefault.rawValue == 0)
    precondition(SparseOrder_t(rawValue: 0) == SparseOrderDefault)
    precondition(SparseOrderUser.rawValue == 1)
    precondition(SparseOrder_t(rawValue: 1) == SparseOrderUser)
    precondition(SparseOrderAMD.rawValue == 2)
    precondition(SparseOrder_t(rawValue: 2) == SparseOrderAMD)
    precondition(SparseOrderMetis.rawValue == 3)
    precondition(SparseOrder_t(rawValue: 3) == SparseOrderMetis)
    precondition(SparseOrderCOLAMD.rawValue == 4)
    precondition(SparseOrder_t(rawValue: 4) == SparseOrderCOLAMD)
    precondition(SparseOrderMTMetis.rawValue == 5)
    precondition(SparseOrder_t(rawValue: 5) == SparseOrderMTMetis)
    precondition(SparseScalingDefault.rawValue == 0)
    precondition(SparseScaling_t(rawValue: 0) == SparseScalingDefault)
    precondition(SparseScalingUser.rawValue == 1)
    precondition(SparseScaling_t(rawValue: 1) == SparseScalingUser)
    precondition(SparseScalingEquilibriationInf.rawValue == 2)
    precondition(SparseScaling_t(rawValue: 2) == SparseScalingEquilibriationInf)
    precondition(SparseScalingHungarianScalingOnly.rawValue == 3)
    precondition(SparseScaling_t(rawValue: 3) == SparseScalingHungarianScalingOnly)
    precondition(SparseScalingHungarianScalingAndOrdering.rawValue == 4)
    precondition(SparseScaling_t(rawValue: 4) == SparseScalingHungarianScalingAndOrdering)
}

func testSparseOracleIterativePreconditionerValues() {
    precondition(SparseVariantDQGMRES.rawValue == 0)
    precondition(SparseGMRESVariant_t(rawValue: 0) == SparseVariantDQGMRES)
    precondition(SparseVariantGMRES.rawValue == 1)
    precondition(SparseGMRESVariant_t(rawValue: 1) == SparseVariantGMRES)
    precondition(SparseVariantFGMRES.rawValue == 2)
    precondition(SparseGMRESVariant_t(rawValue: 2) == SparseVariantFGMRES)
    precondition(SparseIterativeIllConditioned.rawValue == -2)
    precondition(SparseIterativeStatus_t(rawValue: -2) == SparseIterativeIllConditioned)
    precondition(SparseIterativeInternalError.rawValue == -99)
    precondition(SparseIterativeStatus_t(rawValue: -99) == SparseIterativeInternalError)
    precondition(SparseIterativeMaxIterations.rawValue == 1)
    precondition(SparseIterativeStatus_t(rawValue: 1) == SparseIterativeMaxIterations)
    precondition(SparsePreconditionerDiagScaling.rawValue == 3)
    precondition(SparsePreconditioner_t(rawValue: 3) == SparsePreconditionerDiagScaling)
    precondition(SparsePreconditionerDiagonal.rawValue == 2)
    precondition(SparsePreconditioner_t(rawValue: 2) == SparsePreconditionerDiagonal)
    precondition(SparsePreconditionerUser.rawValue == 1)
    precondition(SparsePreconditioner_t(rawValue: 1) == SparsePreconditionerUser)
    precondition(SparseLSMRCTDefault.rawValue == 0)
    precondition(SparseLSMRConvergenceTest_t(rawValue: 0) == SparseLSMRCTDefault)
    precondition(SparseLSMRCTFongSaunders.rawValue == 1)
    precondition(SparseLSMRConvergenceTest_t(rawValue: 1) == SparseLSMRCTFongSaunders)
}

func testSparseOracleLegacyStatusValues() {
    precondition(SPARSE_SUCCESS.rawValue == 0)
    precondition(sparse_status(rawValue: 0) == SPARSE_SUCCESS)
    precondition(SPARSE_ILLEGAL_PARAMETER.rawValue == -1000)
    precondition(sparse_status(rawValue: -1000) == SPARSE_ILLEGAL_PARAMETER)
    precondition(SPARSE_CANNOT_SET_PROPERTY.rawValue == -1001)
    precondition(sparse_status(rawValue: -1001) == SPARSE_CANNOT_SET_PROPERTY)
    precondition(SPARSE_SYSTEM_ERROR.rawValue == -1002)
    precondition(sparse_status(rawValue: -1002) == SPARSE_SYSTEM_ERROR)
    precondition(SPARSE_UPPER_TRIANGULAR.rawValue == 1)
    precondition(sparse_matrix_property(rawValue: 1) == SPARSE_UPPER_TRIANGULAR)
    precondition(SPARSE_LOWER_TRIANGULAR.rawValue == 2)
    precondition(sparse_matrix_property(rawValue: 2) == SPARSE_LOWER_TRIANGULAR)
    precondition(SPARSE_UPPER_SYMMETRIC.rawValue == 4)
    precondition(sparse_matrix_property(rawValue: 4) == SPARSE_UPPER_SYMMETRIC)
    precondition(SPARSE_LOWER_SYMMETRIC.rawValue == 8)
    precondition(sparse_matrix_property(rawValue: 8) == SPARSE_LOWER_SYMMETRIC)
    precondition(SPARSE_NORM_R1.rawValue == 179)
    precondition(sparse_norm(rawValue: 179) == SPARSE_NORM_R1)
}

func testQuadratureOracleValues() {
    precondition(QUADRATURE_INTEGRATE_QNG.rawValue == 0)
    precondition(quadrature_integrator(rawValue: 0) == QUADRATURE_INTEGRATE_QNG)
    precondition(QUADRATURE_INTEGRATE_QAG.rawValue == 1)
    precondition(quadrature_integrator(rawValue: 1) == QUADRATURE_INTEGRATE_QAG)
    precondition(QUADRATURE_INTEGRATE_QAGS.rawValue == 2)
    precondition(quadrature_integrator(rawValue: 2) == QUADRATURE_INTEGRATE_QAGS)
    precondition(QUADRATURE_SUCCESS.rawValue == 0)
    precondition(quadrature_status(rawValue: 0) == QUADRATURE_SUCCESS)
    precondition(QUADRATURE_ERROR.rawValue == -1)
    precondition(quadrature_status(rawValue: -1) == QUADRATURE_ERROR)
    precondition(QUADRATURE_INVALID_ARG_ERROR.rawValue == -2)
    precondition(quadrature_status(rawValue: -2) == QUADRATURE_INVALID_ARG_ERROR)
    precondition(QUADRATURE_ALLOC_ERROR.rawValue == -3)
    precondition(quadrature_status(rawValue: -3) == QUADRATURE_ALLOC_ERROR)
    precondition(QUADRATURE_INTERNAL_ERROR.rawValue == -99)
    precondition(quadrature_status(rawValue: -99) == QUADRATURE_INTERNAL_ERROR)
    precondition(QUADRATURE_INTEGRATE_MAX_EVAL_ERROR.rawValue == -101)
    precondition(quadrature_status(rawValue: -101) == QUADRATURE_INTEGRATE_MAX_EVAL_ERROR)
    precondition(QUADRATURE_INTEGRATE_BAD_BEHAVIOUR_ERROR.rawValue == -102)
    precondition(quadrature_status(rawValue: -102) == QUADRATURE_INTEGRATE_BAD_BEHAVIOUR_ERROR)
}

func testLAOracleStatusValues() {
    precondition(LA_WARNING_POORLY_CONDITIONED == 1000)
    precondition(LA_INTERNAL_ERROR == -1000)
    precondition(LA_INVALID_PARAMETER_ERROR == -1001)
    precondition(LA_DIMENSION_MISMATCH_ERROR == -1002)
    precondition(LA_PRECISION_MISMATCH_ERROR == -1003)
    precondition(LA_SINGULAR_ERROR == -1004)
    precondition(LA_SLICE_OUT_OF_BOUNDS_ERROR == -1005)
    precondition(LA_L1_NORM == 1)
    precondition(LA_L2_NORM == 2)
    precondition(LA_LINF_NORM == 3)
}

func testLAOracleHintAttributeValues() {
    precondition(LA_NO_HINT == 0)
    precondition(LA_ATTRIBUTE_ENABLE_LOGGING == 1)
    precondition(LA_DEFAULT_ATTRIBUTES == 0)
    precondition(LA_FEATURE_SYMMETRIC == 65536)
    precondition(LA_FEATURE_POSITIVE_DEFINITE == 131072)
    precondition(LA_FEATURE_DIAGONALLY_DOMINANT == 262144)
    precondition(LA_SCALAR_TYPE_DOUBLE == 16384)
    precondition(LA_SCALAR_TYPE_FLOAT == 32768)
    precondition(LA_SHAPE_DIAGONAL == 1)
    precondition(LA_SHAPE_LOWER_TRIANGULAR == 2)
    precondition(LA_SHAPE_UPPER_TRIANGULAR == 4)
}

func testOracleWorkspaceVersionValues() {
    precondition(QUADRATURE_INTEGRATE_QAG_WORKSPACE_PER_INTERVAL == 32)
    precondition(QUADRATURE_INTEGRATE_QAGS_WORKSPACE_PER_INTERVAL == 152)
    precondition(USE_NON_APPLE_STANDARD_DATATYPES == 1)
    precondition(VIMAGE_AFFINETRANSFORM_DOUBLE_IS_AVAILABLE == 1)
    precondition(VIMAGE_CGAFFINETRANSFORM_IS_AVAILABLE == 1)
    precondition(vDSP_Version0 == 1123)
    precondition(vDSP_Version1 == 40)
}
