import Accelerate
import Foundation

func testSoBNNSRemBBatch0() {
    _ = BNNSActivationFunction.self
    precondition(BNNSActivationFunction(rawValue: 0).rawValue == 0)
    precondition(BNNSActivationFunction(0) == BNNSActivationFunction(rawValue: 0))
    precondition(BNNSActivationFunction(rawValue: 0) != BNNSActivationFunction(rawValue: 1))
    _ = BNNSArithmeticFunction.self
    precondition(BNNSArithmeticFunction(rawValue: 0).rawValue == 0)
    precondition(BNNSArithmeticFunction(0) == BNNSArithmeticFunction(rawValue: 0))
    precondition(BNNSArithmeticFunction(rawValue: 0) != BNNSArithmeticFunction(rawValue: 1))
    _ = BNNSLinearSamplingMode.self
    precondition(BNNSLinearSamplingMode(rawValue: 0).rawValue == 0)
    precondition(BNNSLinearSamplingMode(0) == BNNSLinearSamplingMode(rawValue: 0))
    precondition(BNNSLinearSamplingMode(rawValue: 0) != BNNSLinearSamplingMode(rawValue: 1))
    _ = BNNSRelationalOperator.self
    precondition(BNNSRelationalOperator(rawValue: 0).rawValue == 0)
    precondition(BNNSRelationalOperator(0) == BNNSRelationalOperator(rawValue: 0))
    precondition(BNNSRelationalOperator(rawValue: 0) != BNNSRelationalOperator(rawValue: 1))
    _ = BNNSGraphArgumentIntent.self
    precondition(BNNSGraphArgumentIntent(rawValue: 0).rawValue == 0)
    precondition(BNNSGraphArgumentIntent(0) == BNNSGraphArgumentIntent(rawValue: 0))
    precondition(BNNSGraphArgumentIntent(rawValue: 0) != BNNSGraphArgumentIntent(rawValue: 1))
    _ = BNNSInterpolationMethod.self
    precondition(BNNSInterpolationMethod(rawValue: 0).rawValue == 0)
    precondition(BNNSInterpolationMethod(0) == BNNSInterpolationMethod(rawValue: 0))
    precondition(BNNSInterpolationMethod(rawValue: 0) != BNNSInterpolationMethod(rawValue: 1))
    _ = BNNSLossReductionFunction.self
    precondition(BNNSLossReductionFunction(rawValue: 0).rawValue == 0)
    precondition(BNNSLossReductionFunction(0) == BNNSLossReductionFunction(rawValue: 0))
    precondition(BNNSLossReductionFunction(rawValue: 0) != BNNSLossReductionFunction(rawValue: 1))
    _ = BNNSRandomGeneratorMethod.self
    precondition(BNNSRandomGeneratorMethod(rawValue: 0).rawValue == 0)
    precondition(BNNSRandomGeneratorMethod(0) == BNNSRandomGeneratorMethod(rawValue: 0))
    precondition(BNNSRandomGeneratorMethod(rawValue: 0) != BNNSRandomGeneratorMethod(rawValue: 1))
    _ = BNNSFlags.self
    precondition(BNNSFlags(rawValue: 1).rawValue == 1)
    precondition(BNNSFlags(1) == BNNSFlags(rawValue: 1))
    _ = BNNSFlags.Element.self
    _ = BNNSFlags.ArrayLiteralElement.self
    let bfRem: BNNSFlags = [BNNSFlags(rawValue: 1)]
    precondition(bfRem.rawValue == 1)
    _ = BNNSLSTMDataDescriptor.self
    let cBNNSLSTMDataDescriptor = BNNSLSTMDataDescriptor()
    _ = cBNNSLSTMDataDescriptor.cell_state_desc
    _ = cBNNSLSTMDataDescriptor.data_desc
    _ = cBNNSLSTMDataDescriptor.hidden_desc
    _ = BNNSLSTMDataDescriptor(data_desc: BNNSNDArrayDescriptor(), hidden_desc: BNNSNDArrayDescriptor(), cell_state_desc: BNNSNDArrayDescriptor())
    _ = BNNSLSTMGateDescriptor.self
    let cBNNSLSTMGateDescriptor = BNNSLSTMGateDescriptor()
    _ = cBNNSLSTMGateDescriptor.activation
    _ = cBNNSLSTMGateDescriptor.b_desc
    _ = cBNNSLSTMGateDescriptor.cw_desc
    _ = cBNNSLSTMGateDescriptor.hw_desc
    _ = cBNNSLSTMGateDescriptor.iw_desc
    _ = BNNSLSTMGateDescriptor(iw_desc: (BNNSNDArrayDescriptor(), BNNSNDArrayDescriptor()), hw_desc: BNNSNDArrayDescriptor(), cw_desc: BNNSNDArrayDescriptor(), b_desc: BNNSNDArrayDescriptor(), activation: BNNSActivation())
    _ = BNNSSparsityParameters.self
    let cBNNSSparsityParameters = BNNSSparsityParameters()
    _ = cBNNSSparsityParameters.flags
    _ = cBNNSSparsityParameters.sparsity_ratio
    _ = cBNNSSparsityParameters.sparsity_type
    _ = cBNNSSparsityParameters.target_system
    _ = BNNSSparsityParameters(flags: 0, sparsity_ratio: (0, 0), sparsity_type: BNNSSparsityType(rawValue: 0), target_system: BNNSTargetSystem(rawValue: 0))
    _ = BNNSLayerParametersGram.self
    let cBNNSLayerParametersGram = BNNSLayerParametersGram()
    _ = cBNNSLayerParametersGram.alpha
    _ = cBNNSLayerParametersGram.i_desc
    _ = cBNNSLayerParametersGram.o_desc
    _ = BNNSLayerParametersGram(alpha: 0, i_desc: BNNSNDArrayDescriptor(), o_desc: BNNSNDArrayDescriptor())
    _ = BNNSLayerParametersResize.self
    let cBNNSLayerParametersResize = BNNSLayerParametersResize()
    _ = cBNNSLayerParametersResize.align_corners
    _ = cBNNSLayerParametersResize.i_desc
    _ = cBNNSLayerParametersResize.method
    _ = cBNNSLayerParametersResize.o_desc
    _ = BNNSLayerParametersResize(method: BNNSInterpolationMethod(rawValue: 0), i_desc: BNNSNDArrayDescriptor(), o_desc: BNNSNDArrayDescriptor(), align_corners: false)
    _ = BNNSLayerParametersDropout.self
    let cBNNSLayerParametersDropout = BNNSLayerParametersDropout()
    _ = cBNNSLayerParametersDropout.control
    _ = cBNNSLayerParametersDropout.i_desc
    _ = cBNNSLayerParametersDropout.o_desc
    _ = cBNNSLayerParametersDropout.rate
    _ = cBNNSLayerParametersDropout.seed
    _ = BNNSLayerParametersDropout(i_desc: BNNSNDArrayDescriptor(), o_desc: BNNSNDArrayDescriptor(), rate: 0, seed: 0, control: 0)
}

func testSoBNNSRemBBatch1() {
    _ = BNNSLayerParametersPadding.self
    let dBNNSLayerParametersPadding = BNNSLayerParametersPadding()
    _ = dBNNSLayerParametersPadding.i_desc
    _ = dBNNSLayerParametersPadding.o_desc
    _ = dBNNSLayerParametersPadding.padding_mode
    _ = dBNNSLayerParametersPadding.padding_size
    _ = dBNNSLayerParametersPadding.padding_value
    _ = BNNSLayerParametersPadding(i_desc: BNNSNDArrayDescriptor(), o_desc: BNNSNDArrayDescriptor(), padding_size: ((0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0)), padding_mode: BNNSPaddingMode(rawValue: 0), padding_value: 0)
    _ = BNNSLayerParametersPermute.self
    let dBNNSLayerParametersPermute = BNNSLayerParametersPermute()
    _ = dBNNSLayerParametersPermute.i_desc
    _ = dBNNSLayerParametersPermute.o_desc
    _ = dBNNSLayerParametersPermute.permutation
    _ = BNNSLayerParametersPermute(i_desc: BNNSNDArrayDescriptor(), o_desc: BNNSNDArrayDescriptor(), permutation: (0, 0, 0, 0, 0, 0, 0, 0))
    _ = BNNSLayerParametersPooling.self
    let dBNNSLayerParametersPooling = BNNSLayerParametersPooling()
    _ = dBNNSLayerParametersPooling.activation
    _ = dBNNSLayerParametersPooling.bias
    _ = dBNNSLayerParametersPooling.i_desc
    _ = dBNNSLayerParametersPooling.k_height
    _ = dBNNSLayerParametersPooling.k_width
    _ = dBNNSLayerParametersPooling.o_desc
    _ = dBNNSLayerParametersPooling.pad
    _ = dBNNSLayerParametersPooling.pooling_function
    _ = dBNNSLayerParametersPooling.x_dilation_stride
    _ = dBNNSLayerParametersPooling.x_padding
    _ = dBNNSLayerParametersPooling.x_stride
    _ = dBNNSLayerParametersPooling.y_dilation_stride
    _ = dBNNSLayerParametersPooling.y_padding
    _ = dBNNSLayerParametersPooling.y_stride
    _ = BNNSLayerParametersPooling(i_desc: BNNSNDArrayDescriptor(), o_desc: BNNSNDArrayDescriptor(), bias: BNNSNDArrayDescriptor(), activation: BNNSActivation(), pooling_function: BNNSPoolingFunction(rawValue: 0), k_width: 0, k_height: 0, x_stride: 0, y_stride: 0, x_dilation_stride: 0, y_dilation_stride: 0, x_padding: 0, y_padding: 0, pad: (0, 0, 0, 0))
    _ = BNNSLayerParametersConvolution.self
    let dBNNSLayerParametersConvolution = BNNSLayerParametersConvolution()
    _ = dBNNSLayerParametersConvolution.activation
    _ = dBNNSLayerParametersConvolution.bias
    _ = dBNNSLayerParametersConvolution.groups
    _ = dBNNSLayerParametersConvolution.i_desc
    _ = dBNNSLayerParametersConvolution.o_desc
    _ = dBNNSLayerParametersConvolution.pad
    _ = dBNNSLayerParametersConvolution.w_desc
    _ = dBNNSLayerParametersConvolution.x_dilation_stride
    _ = dBNNSLayerParametersConvolution.x_padding
    _ = dBNNSLayerParametersConvolution.x_stride
    _ = dBNNSLayerParametersConvolution.y_dilation_stride
    _ = dBNNSLayerParametersConvolution.y_padding
    _ = dBNNSLayerParametersConvolution.y_stride
    _ = BNNSLayerParametersConvolution(i_desc: BNNSNDArrayDescriptor(), w_desc: BNNSNDArrayDescriptor(), o_desc: BNNSNDArrayDescriptor(), bias: BNNSNDArrayDescriptor(), activation: BNNSActivation(), x_stride: 0, y_stride: 0, x_dilation_stride: 0, y_dilation_stride: 0, x_padding: 0, y_padding: 0, groups: 0, pad: (0, 0, 0, 0))
    _ = BNNSLayerParametersQuantization.self
    let dBNNSLayerParametersQuantization = BNNSLayerParametersQuantization()
    _ = dBNNSLayerParametersQuantization.axis_mask
    _ = dBNNSLayerParametersQuantization.bias
    _ = dBNNSLayerParametersQuantization.function
    _ = dBNNSLayerParametersQuantization.i_desc
    _ = dBNNSLayerParametersQuantization.o_desc
    _ = dBNNSLayerParametersQuantization.scale
    _ = BNNSLayerParametersQuantization(axis_mask: 0, function: BNNSQuantizerFunction(rawValue: 0), i_desc: BNNSNDArrayDescriptor(), o_desc: BNNSNDArrayDescriptor(), scale: BNNSNDArrayDescriptor(), bias: BNNSNDArrayDescriptor())
    _ = BNNSLayerParametersNormalization.self
    let dBNNSLayerParametersNormalization = BNNSLayerParametersNormalization()
    _ = dBNNSLayerParametersNormalization.activation
    _ = dBNNSLayerParametersNormalization.beta_desc
    _ = dBNNSLayerParametersNormalization.epsilon
    _ = dBNNSLayerParametersNormalization.gamma_desc
    _ = dBNNSLayerParametersNormalization.i_desc
    _ = dBNNSLayerParametersNormalization.momentum
    _ = dBNNSLayerParametersNormalization.moving_mean_desc
    _ = dBNNSLayerParametersNormalization.moving_variance_desc
    _ = dBNNSLayerParametersNormalization.normalization_axis
    _ = dBNNSLayerParametersNormalization.num_groups
    _ = dBNNSLayerParametersNormalization.o_desc
    _ = BNNSLayerParametersNormalization(i_desc: BNNSNDArrayDescriptor(), o_desc: BNNSNDArrayDescriptor(), beta_desc: BNNSNDArrayDescriptor(), gamma_desc: BNNSNDArrayDescriptor(), moving_mean_desc: BNNSNDArrayDescriptor(), moving_variance_desc: BNNSNDArrayDescriptor(), momentum: 0, epsilon: 0, activation: BNNSActivation(), num_groups: 0, normalization_axis: 0)
    _ = BNNSLayerParametersFullyConnected.self
    let dBNNSLayerParametersFullyConnected = BNNSLayerParametersFullyConnected()
    _ = dBNNSLayerParametersFullyConnected.activation
    _ = dBNNSLayerParametersFullyConnected.bias
    _ = dBNNSLayerParametersFullyConnected.i_desc
    _ = dBNNSLayerParametersFullyConnected.o_desc
    _ = dBNNSLayerParametersFullyConnected.w_desc
    _ = BNNSLayerParametersFullyConnected(i_desc: BNNSNDArrayDescriptor(), w_desc: BNNSNDArrayDescriptor(), o_desc: BNNSNDArrayDescriptor(), bias: BNNSNDArrayDescriptor(), activation: BNNSActivation())
    _ = BNNSLayerParametersBroadcastMatMul.self
    let dBNNSLayerParametersBroadcastMatMul = BNNSLayerParametersBroadcastMatMul()
    _ = dBNNSLayerParametersBroadcastMatMul.a_is_weights
    _ = dBNNSLayerParametersBroadcastMatMul.alpha
    _ = dBNNSLayerParametersBroadcastMatMul.b_is_weights
    _ = dBNNSLayerParametersBroadcastMatMul.beta
    _ = dBNNSLayerParametersBroadcastMatMul.iA_desc
    _ = dBNNSLayerParametersBroadcastMatMul.iB_desc
    _ = dBNNSLayerParametersBroadcastMatMul.o_desc
    _ = dBNNSLayerParametersBroadcastMatMul.quadratic
    _ = dBNNSLayerParametersBroadcastMatMul.transA
    _ = dBNNSLayerParametersBroadcastMatMul.transB
    _ = BNNSLayerParametersBroadcastMatMul(alpha: 0, beta: 0, transA: false, transB: false, quadratic: false, a_is_weights: false, b_is_weights: false, iA_desc: BNNSNDArrayDescriptor(), iB_desc: BNNSNDArrayDescriptor(), o_desc: BNNSNDArrayDescriptor())
}

func testSoBNNSRemBBatch2() {
    _ = BNNSLayerParametersMultiheadAttention.self
    let eBNNSLayerParametersMultiheadAttention = BNNSLayerParametersMultiheadAttention()
    _ = eBNNSLayerParametersMultiheadAttention.add_zero_attn
    _ = eBNNSLayerParametersMultiheadAttention.dropout
    _ = eBNNSLayerParametersMultiheadAttention.key
    _ = eBNNSLayerParametersMultiheadAttention.key_attn_bias
    _ = eBNNSLayerParametersMultiheadAttention.output
    _ = eBNNSLayerParametersMultiheadAttention.query
    _ = eBNNSLayerParametersMultiheadAttention.seed
    _ = eBNNSLayerParametersMultiheadAttention.value
    _ = eBNNSLayerParametersMultiheadAttention.value_attn_bias
    _ = BNNSLayerParametersMultiheadAttention(query: BNNSMHAProjectionParameters(), key: BNNSMHAProjectionParameters(), value: BNNSMHAProjectionParameters(), add_zero_attn: false, key_attn_bias: BNNSNDArrayDescriptor(), value_attn_bias: BNNSNDArrayDescriptor(), output: BNNSMHAProjectionParameters(), dropout: 0, seed: 0)
    _ = BNNSLayerParametersLossSigmoidCrossEntropy.self
    let eBNNSLayerParametersLossSigmoidCrossEntropy = BNNSLayerParametersLossSigmoidCrossEntropy()
    _ = eBNNSLayerParametersLossSigmoidCrossEntropy.function
    _ = eBNNSLayerParametersLossSigmoidCrossEntropy.i_desc
    _ = eBNNSLayerParametersLossSigmoidCrossEntropy.label_smooth
    _ = eBNNSLayerParametersLossSigmoidCrossEntropy.o_desc
    _ = eBNNSLayerParametersLossSigmoidCrossEntropy.reduction
    _ = BNNSLayerParametersLossSigmoidCrossEntropy(function: BNNSLossFunction(rawValue: 0), i_desc: BNNSNDArrayDescriptor(), o_desc: BNNSNDArrayDescriptor(), reduction: BNNSLossReductionFunction(rawValue: 0), label_smooth: 0)
    _ = BNNSLayerParametersLossSoftmaxCrossEntropy.self
    let eBNNSLayerParametersLossSoftmaxCrossEntropy = BNNSLayerParametersLossSoftmaxCrossEntropy()
    _ = eBNNSLayerParametersLossSoftmaxCrossEntropy.function
    _ = eBNNSLayerParametersLossSoftmaxCrossEntropy.i_desc
    _ = eBNNSLayerParametersLossSoftmaxCrossEntropy.label_smooth
    _ = eBNNSLayerParametersLossSoftmaxCrossEntropy.o_desc
    _ = eBNNSLayerParametersLossSoftmaxCrossEntropy.reduction
    _ = BNNSLayerParametersLossSoftmaxCrossEntropy(function: BNNSLossFunction(rawValue: 0), i_desc: BNNSNDArrayDescriptor(), o_desc: BNNSNDArrayDescriptor(), reduction: BNNSLossReductionFunction(rawValue: 0), label_smooth: 0)
    _ = BNNSLayerParametersLossBase.self
    let eBNNSLayerParametersLossBase = BNNSLayerParametersLossBase()
    _ = eBNNSLayerParametersLossBase.function
    _ = eBNNSLayerParametersLossBase.i_desc
    _ = eBNNSLayerParametersLossBase.o_desc
    _ = eBNNSLayerParametersLossBase.reduction
    _ = BNNSLayerParametersLossBase(function: BNNSLossFunction(rawValue: 0), i_desc: BNNSNDArrayDescriptor(), o_desc: BNNSNDArrayDescriptor(), reduction: BNNSLossReductionFunction(rawValue: 0))
    _ = BNNSLayerParametersLossHuber.self
    let eBNNSLayerParametersLossHuber = BNNSLayerParametersLossHuber()
    _ = eBNNSLayerParametersLossHuber.function
    _ = eBNNSLayerParametersLossHuber.huber_delta
    _ = eBNNSLayerParametersLossHuber.i_desc
    _ = eBNNSLayerParametersLossHuber.o_desc
    _ = eBNNSLayerParametersLossHuber.reduction
    _ = BNNSLayerParametersLossHuber(function: BNNSLossFunction(rawValue: 0), i_desc: BNNSNDArrayDescriptor(), o_desc: BNNSNDArrayDescriptor(), reduction: BNNSLossReductionFunction(rawValue: 0), huber_delta: 0)
    _ = BNNSLayerParametersLossYolo.self
    let eBNNSLayerParametersLossYolo = BNNSLayerParametersLossYolo()
    _ = eBNNSLayerParametersLossYolo.anchor_box_size
    _ = eBNNSLayerParametersLossYolo.anchors_data
    _ = eBNNSLayerParametersLossYolo.function
    _ = eBNNSLayerParametersLossYolo.huber_delta
    _ = eBNNSLayerParametersLossYolo.i_desc
    _ = eBNNSLayerParametersLossYolo.no_object_maximum_iou
    _ = eBNNSLayerParametersLossYolo.number_of_anchor_boxes
    _ = eBNNSLayerParametersLossYolo.number_of_grid_columns
    _ = eBNNSLayerParametersLossYolo.number_of_grid_rows
    _ = eBNNSLayerParametersLossYolo.o_desc
    _ = eBNNSLayerParametersLossYolo.object_minimum_iou
    _ = eBNNSLayerParametersLossYolo.reduction
    _ = eBNNSLayerParametersLossYolo.rescore
    _ = eBNNSLayerParametersLossYolo.scale_classification
    _ = eBNNSLayerParametersLossYolo.scale_no_object
    _ = eBNNSLayerParametersLossYolo.scale_object
    _ = eBNNSLayerParametersLossYolo.scale_wh
    _ = eBNNSLayerParametersLossYolo.scale_xy
    _ = BNNSLayerParametersReduction.self
    let eBNNSLayerParametersReduction = BNNSLayerParametersReduction()
    _ = eBNNSLayerParametersReduction.epsilon
    _ = eBNNSLayerParametersReduction.i_desc
    _ = eBNNSLayerParametersReduction.o_desc
    _ = eBNNSLayerParametersReduction.reduce_func
    _ = eBNNSLayerParametersReduction.w_desc
    _ = BNNSLayerParametersReduction(i_desc: BNNSNDArrayDescriptor(), o_desc: BNNSNDArrayDescriptor(), w_desc: BNNSNDArrayDescriptor(), reduce_func: BNNSReduceFunction(rawValue: 0), epsilon: 0)
    _ = BNNSLayerParametersActivation.self
    let eBNNSLayerParametersActivation = BNNSLayerParametersActivation()
    _ = eBNNSLayerParametersActivation.activation
    _ = eBNNSLayerParametersActivation.axis_flags
    _ = eBNNSLayerParametersActivation.i_desc
    _ = eBNNSLayerParametersActivation.o_desc
    _ = BNNSLayerParametersActivation(i_desc: BNNSNDArrayDescriptor(), o_desc: BNNSNDArrayDescriptor(), activation: BNNSActivation(), axis_flags: 0)
    _ = BNNSLayerParametersCropResize.self
    let eBNNSLayerParametersCropResize = BNNSLayerParametersCropResize()
    _ = eBNNSLayerParametersCropResize.box_coordinate_mode
    _ = eBNNSLayerParametersCropResize.extrapolation_value
    _ = eBNNSLayerParametersCropResize.method
    _ = eBNNSLayerParametersCropResize.normalized_coordinates
    _ = eBNNSLayerParametersCropResize.sampling_mode
    _ = eBNNSLayerParametersCropResize.spatial_scale
    _ = BNNSLayerParametersCropResize(normalized_coordinates: false, spatial_scale: 0, extrapolation_value: 0, sampling_mode: BNNSLinearSamplingMode(rawValue: 0), box_coordinate_mode: BNNSBoxCoordinateMode(rawValue: 0), method: BNNSInterpolationMethod(rawValue: 0))
    _ = BNNSLayerParametersEmbedding.self
    let eBNNSLayerParametersEmbedding = BNNSLayerParametersEmbedding()
    _ = eBNNSLayerParametersEmbedding.dictionary
    _ = eBNNSLayerParametersEmbedding.flags
    _ = eBNNSLayerParametersEmbedding.i_desc
    _ = eBNNSLayerParametersEmbedding.max_norm
    _ = eBNNSLayerParametersEmbedding.norm_type
    _ = eBNNSLayerParametersEmbedding.o_desc
    _ = eBNNSLayerParametersEmbedding.padding_idx
    _ = BNNSLayerParametersEmbedding(flags: BNNSEmbeddingFlags(rawValue: 0), i_desc: BNNSNDArrayDescriptor(), o_desc: BNNSNDArrayDescriptor(), dictionary: BNNSNDArrayDescriptor(), padding_idx: 0, max_norm: 0, norm_type: 0)
    _ = BNNSLayerParametersLSTM.self
    let eBNNSLayerParametersLSTM = BNNSLayerParametersLSTM()
    _ = eBNNSLayerParametersLSTM.batch_size
    _ = eBNNSLayerParametersLSTM.candidate_gate
    _ = eBNNSLayerParametersLSTM.dropout
    _ = eBNNSLayerParametersLSTM.forget_gate
    _ = eBNNSLayerParametersLSTM.hidden_activation
    _ = eBNNSLayerParametersLSTM.hidden_size
    _ = eBNNSLayerParametersLSTM.input_descriptor
    _ = eBNNSLayerParametersLSTM.input_gate
    _ = eBNNSLayerParametersLSTM.input_size
    _ = eBNNSLayerParametersLSTM.lstm_flags
    _ = eBNNSLayerParametersLSTM.num_layers
    _ = eBNNSLayerParametersLSTM.output_descriptor
    _ = eBNNSLayerParametersLSTM.output_gate
    _ = eBNNSLayerParametersLSTM.seq_len
    _ = eBNNSLayerParametersLSTM.sequence_descriptor
    _ = BNNSLayerParametersLSTM(input_size: 0, hidden_size: 0, batch_size: 0, num_layers: 0, seq_len: 0, dropout: 0, lstm_flags: 0, sequence_descriptor: BNNSNDArrayDescriptor(), input_descriptor: BNNSLSTMDataDescriptor(), output_descriptor: BNNSLSTMDataDescriptor(), input_gate: BNNSLSTMGateDescriptor(), forget_gate: BNNSLSTMGateDescriptor(), candidate_gate: BNNSLSTMGateDescriptor(), output_gate: BNNSLSTMGateDescriptor(), hidden_activation: BNNSActivation())
    _ = BNNSLayerParametersTensorContraction.self
    let eBNNSLayerParametersTensorContraction = BNNSLayerParametersTensorContraction()
    _ = eBNNSLayerParametersTensorContraction.alpha
    _ = eBNNSLayerParametersTensorContraction.beta
    _ = eBNNSLayerParametersTensorContraction.iA_desc
    _ = eBNNSLayerParametersTensorContraction.iB_desc
    _ = eBNNSLayerParametersTensorContraction.o_desc
    _ = eBNNSLayerParametersTensorContraction.operation
}

func testSoBNNSRemBBatch3() {
    _ = BNNSOptimizerAdamFields.self
    let fBNNSOptimizerAdamFields = BNNSOptimizerAdamFields()
    _ = fBNNSOptimizerAdamFields.beta1
    _ = fBNNSOptimizerAdamFields.beta2
    _ = fBNNSOptimizerAdamFields.clip_gradients
    _ = fBNNSOptimizerAdamFields.clip_gradients_max
    _ = fBNNSOptimizerAdamFields.clip_gradients_min
    _ = fBNNSOptimizerAdamFields.epsilon
    _ = fBNNSOptimizerAdamFields.gradient_scale
    _ = fBNNSOptimizerAdamFields.learning_rate
    _ = fBNNSOptimizerAdamFields.regularization_func
    _ = fBNNSOptimizerAdamFields.regularization_scale
    _ = fBNNSOptimizerAdamFields.time_step
    _ = BNNSOptimizerAdamFields(learning_rate: 0, beta1: 0, beta2: 0, time_step: 0, epsilon: 0, gradient_scale: 0, regularization_scale: 0, clip_gradients: false, clip_gradients_min: 0, clip_gradients_max: 0, regularization_func: BNNSOptimizerRegularizationFunction(rawValue: 0))
    _ = BNNSOptimizerRMSPropFields.self
    let fBNNSOptimizerRMSPropFields = BNNSOptimizerRMSPropFields()
    _ = fBNNSOptimizerRMSPropFields.alpha
    _ = fBNNSOptimizerRMSPropFields.centered
    _ = fBNNSOptimizerRMSPropFields.clip_gradients
    _ = fBNNSOptimizerRMSPropFields.clip_gradients_max
    _ = fBNNSOptimizerRMSPropFields.clip_gradients_min
    _ = fBNNSOptimizerRMSPropFields.epsilon
    _ = fBNNSOptimizerRMSPropFields.gradient_scale
    _ = fBNNSOptimizerRMSPropFields.learning_rate
    _ = fBNNSOptimizerRMSPropFields.momentum
    _ = fBNNSOptimizerRMSPropFields.regularization_func
    _ = fBNNSOptimizerRMSPropFields.regularization_scale
    _ = BNNSOptimizerRMSPropFields(learning_rate: 0, alpha: 0, epsilon: 0, centered: false, momentum: 0, gradient_scale: 0, regularization_scale: 0, clip_gradients: false, clip_gradients_min: 0, clip_gradients_max: 0, regularization_func: BNNSOptimizerRegularizationFunction(rawValue: 0))
    _ = BNNSOptimizerSGDMomentumFields.self
    let fBNNSOptimizerSGDMomentumFields = BNNSOptimizerSGDMomentumFields()
    _ = fBNNSOptimizerSGDMomentumFields.clip_gradients
    _ = fBNNSOptimizerSGDMomentumFields.clip_gradients_max
    _ = fBNNSOptimizerSGDMomentumFields.clip_gradients_min
    _ = fBNNSOptimizerSGDMomentumFields.gradient_scale
    _ = fBNNSOptimizerSGDMomentumFields.learning_rate
    _ = fBNNSOptimizerSGDMomentumFields.momentum
    _ = fBNNSOptimizerSGDMomentumFields.nesterov
    _ = fBNNSOptimizerSGDMomentumFields.regularization_func
    _ = fBNNSOptimizerSGDMomentumFields.regularization_scale
    _ = fBNNSOptimizerSGDMomentumFields.sgd_momentum_variant
    _ = BNNSOptimizerSGDMomentumFields(learning_rate: 0, momentum: 0, gradient_scale: 0, regularization_scale: 0, clip_gradients: false, clip_gradients_min: 0, clip_gradients_max: 0, nesterov: false, regularization_func: BNNSOptimizerRegularizationFunction(rawValue: 0), sgd_momentum_variant: BNNSOptimizerSGDMomentumVariant(rawValue: 0))
    _ = BNNSOptimizerAdamWithClippingFields.self
    let fBNNSOptimizerAdamWithClippingFields = BNNSOptimizerAdamWithClippingFields()
    _ = fBNNSOptimizerAdamWithClippingFields.beta1
    _ = fBNNSOptimizerAdamWithClippingFields.beta2
    _ = fBNNSOptimizerAdamWithClippingFields.clip_gradients_max
    _ = fBNNSOptimizerAdamWithClippingFields.clip_gradients_max_norm
    _ = fBNNSOptimizerAdamWithClippingFields.clip_gradients_min
    _ = fBNNSOptimizerAdamWithClippingFields.clip_gradients_use_norm
    _ = fBNNSOptimizerAdamWithClippingFields.clipping_func
    _ = fBNNSOptimizerAdamWithClippingFields.epsilon
    _ = fBNNSOptimizerAdamWithClippingFields.gradient_scale
    _ = fBNNSOptimizerAdamWithClippingFields.learning_rate
    _ = fBNNSOptimizerAdamWithClippingFields.regularization_func
    _ = fBNNSOptimizerAdamWithClippingFields.regularization_scale
    _ = fBNNSOptimizerAdamWithClippingFields.time_step
    _ = BNNSOptimizerAdamWithClippingFields(learning_rate: 0, beta1: 0, beta2: 0, time_step: 0, epsilon: 0, gradient_scale: 0, regularization_scale: 0, regularization_func: BNNSOptimizerRegularizationFunction(rawValue: 0), clipping_func: BNNSOptimizerClippingFunction(rawValue: 0), clip_gradients_min: 0, clip_gradients_max: 0, clip_gradients_max_norm: 0, clip_gradients_use_norm: 0)
    _ = BNNSOptimizerRMSPropWithClippingFields.self
    let fBNNSOptimizerRMSPropWithClippingFields = BNNSOptimizerRMSPropWithClippingFields()
    _ = fBNNSOptimizerRMSPropWithClippingFields.alpha
    _ = fBNNSOptimizerRMSPropWithClippingFields.centered
    _ = fBNNSOptimizerRMSPropWithClippingFields.clip_gradients_max
    _ = fBNNSOptimizerRMSPropWithClippingFields.clip_gradients_max_norm
    _ = fBNNSOptimizerRMSPropWithClippingFields.clip_gradients_min
    _ = fBNNSOptimizerRMSPropWithClippingFields.clip_gradients_use_norm
    _ = fBNNSOptimizerRMSPropWithClippingFields.clipping_func
    _ = fBNNSOptimizerRMSPropWithClippingFields.epsilon
    _ = fBNNSOptimizerRMSPropWithClippingFields.gradient_scale
    _ = fBNNSOptimizerRMSPropWithClippingFields.learning_rate
    _ = fBNNSOptimizerRMSPropWithClippingFields.momentum
    _ = fBNNSOptimizerRMSPropWithClippingFields.regularization_func
    _ = fBNNSOptimizerRMSPropWithClippingFields.regularization_scale
    _ = BNNSOptimizerRMSPropWithClippingFields(learning_rate: 0, alpha: 0, epsilon: 0, centered: false, momentum: 0, gradient_scale: 0, regularization_scale: 0, regularization_func: BNNSOptimizerRegularizationFunction(rawValue: 0), clipping_func: BNNSOptimizerClippingFunction(rawValue: 0), clip_gradients_min: 0, clip_gradients_max: 0, clip_gradients_max_norm: 0, clip_gradients_use_norm: 0)
    _ = BNNSOptimizerSGDMomentumWithClippingFields.self
    let fBNNSOptimizerSGDMomentumWithClippingFields = BNNSOptimizerSGDMomentumWithClippingFields()
    _ = fBNNSOptimizerSGDMomentumWithClippingFields.clip_gradients_max
    _ = fBNNSOptimizerSGDMomentumWithClippingFields.clip_gradients_max_norm
    _ = fBNNSOptimizerSGDMomentumWithClippingFields.clip_gradients_min
    _ = fBNNSOptimizerSGDMomentumWithClippingFields.clip_gradients_use_norm
    _ = fBNNSOptimizerSGDMomentumWithClippingFields.clipping_func
    _ = fBNNSOptimizerSGDMomentumWithClippingFields.gradient_scale
    _ = fBNNSOptimizerSGDMomentumWithClippingFields.learning_rate
    _ = fBNNSOptimizerSGDMomentumWithClippingFields.momentum
    _ = fBNNSOptimizerSGDMomentumWithClippingFields.nesterov
    _ = fBNNSOptimizerSGDMomentumWithClippingFields.regularization_func
    _ = fBNNSOptimizerSGDMomentumWithClippingFields.regularization_scale
    _ = fBNNSOptimizerSGDMomentumWithClippingFields.sgd_momentum_variant
    _ = BNNSOptimizerSGDMomentumWithClippingFields(learning_rate: 0, momentum: 0, gradient_scale: 0, regularization_scale: 0, nesterov: false, regularization_func: BNNSOptimizerRegularizationFunction(rawValue: 0), sgd_momentum_variant: BNNSOptimizerSGDMomentumVariant(rawValue: 0), clipping_func: BNNSOptimizerClippingFunction(rawValue: 0), clip_gradients_min: 0, clip_gradients_max: 0, clip_gradients_max_norm: 0, clip_gradients_use_norm: 0)
    _ = BNNSMHAProjectionParameters.self
    let fBNNSMHAProjectionParameters = BNNSMHAProjectionParameters()
    _ = fBNNSMHAProjectionParameters.bias
    _ = fBNNSMHAProjectionParameters.target_desc
    _ = fBNNSMHAProjectionParameters.weights
    _ = BNNSMHAProjectionParameters(target_desc: BNNSNDArrayDescriptor(), weights: BNNSNDArrayDescriptor(), bias: BNNSNDArrayDescriptor())
    _ = BNNSImageStackDescriptor.self
    let fBNNSImageStackDescriptor = BNNSImageStackDescriptor()
    _ = fBNNSImageStackDescriptor.channels
    _ = fBNNSImageStackDescriptor.data_bias
    _ = fBNNSImageStackDescriptor.data_scale
    _ = fBNNSImageStackDescriptor.data_type
    _ = fBNNSImageStackDescriptor.height
    _ = fBNNSImageStackDescriptor.image_stride
    _ = fBNNSImageStackDescriptor.row_stride
    _ = fBNNSImageStackDescriptor.width
    _ = BNNSImageStackDescriptor(width: 0, height: 0, channels: 0, row_stride: 0, image_stride: 0, data_type: BNNSDataType(rawValue: 0))
    _ = BNNSImageStackDescriptor.self
    let f2BNNSImageStackDescriptor = BNNSImageStackDescriptor()
    _ = f2BNNSImageStackDescriptor.channels
    _ = f2BNNSImageStackDescriptor.data_bias
    _ = f2BNNSImageStackDescriptor.data_scale
    _ = f2BNNSImageStackDescriptor.data_type
    _ = f2BNNSImageStackDescriptor.height
    _ = f2BNNSImageStackDescriptor.image_stride
    _ = f2BNNSImageStackDescriptor.row_stride
    _ = f2BNNSImageStackDescriptor.width
    _ = BNNSImageStackDescriptor(width: 0, height: 0, channels: 0, row_stride: 0, image_stride: 0, data_type: BNNSDataType(rawValue: 0), data_scale: 0, data_bias: 0)
    _ = BNNSPoolingLayerParameters.self
    let fBNNSPoolingLayerParameters = BNNSPoolingLayerParameters()
    _ = fBNNSPoolingLayerParameters.activation
    _ = fBNNSPoolingLayerParameters.bias
    _ = fBNNSPoolingLayerParameters.in_channels
    _ = fBNNSPoolingLayerParameters.k_height
    _ = fBNNSPoolingLayerParameters.k_width
    _ = fBNNSPoolingLayerParameters.out_channels
    _ = fBNNSPoolingLayerParameters.pooling_function
    _ = fBNNSPoolingLayerParameters.x_padding
    _ = fBNNSPoolingLayerParameters.x_stride
    _ = fBNNSPoolingLayerParameters.y_padding
    _ = fBNNSPoolingLayerParameters.y_stride
    _ = BNNSPoolingLayerParameters(x_stride: 0, y_stride: 0, x_padding: 0, y_padding: 0, k_width: 0, k_height: 0, in_channels: 0, out_channels: 0, pooling_function: BNNSPoolingFunction(rawValue: 0), bias: BNNSLayerData(), activation: BNNSActivation())
    _ = BNNSConvolutionLayerParameters.self
    let fBNNSConvolutionLayerParameters = BNNSConvolutionLayerParameters()
    _ = fBNNSConvolutionLayerParameters.activation
    _ = fBNNSConvolutionLayerParameters.bias
    _ = fBNNSConvolutionLayerParameters.in_channels
    _ = fBNNSConvolutionLayerParameters.k_height
    _ = fBNNSConvolutionLayerParameters.k_width
    _ = fBNNSConvolutionLayerParameters.out_channels
    _ = fBNNSConvolutionLayerParameters.weights
    _ = fBNNSConvolutionLayerParameters.x_padding
    _ = fBNNSConvolutionLayerParameters.x_stride
    _ = fBNNSConvolutionLayerParameters.y_padding
    _ = fBNNSConvolutionLayerParameters.y_stride
    _ = BNNSConvolutionLayerParameters(x_stride: 0, y_stride: 0, x_padding: 0, y_padding: 0, k_width: 0, k_height: 0, in_channels: 0, out_channels: 0, weights: BNNSLayerData(), bias: BNNSLayerData(), activation: BNNSActivation())
    _ = BNNSFullyConnectedLayerParameters.self
    let f2BNNSFullyConnectedLayerParameters = BNNSFullyConnectedLayerParameters()
    _ = f2BNNSFullyConnectedLayerParameters.activation
    _ = f2BNNSFullyConnectedLayerParameters.bias
    _ = f2BNNSFullyConnectedLayerParameters.in_size
    _ = f2BNNSFullyConnectedLayerParameters.out_size
    _ = f2BNNSFullyConnectedLayerParameters.weights
    _ = BNNSFullyConnectedLayerParameters(in_size: 0, out_size: 0, weights: BNNSLayerData(), bias: BNNSLayerData(), activation: BNNSActivation())
    _ = bnns_user_message_data_t.self
    let fbnns_user_message_data_t = bnns_user_message_data_t()
    _ = fbnns_user_message_data_t.data
    _ = fbnns_user_message_data_t.size
    _ = bnns_user_message_data_t(size: 0, data: nil)
    _ = bnns_graph_compile_options_t.self
    let fbnns_graph_compile_options_t = bnns_graph_compile_options_t()
    _ = fbnns_graph_compile_options_t.data
    _ = fbnns_graph_compile_options_t.size
    _ = bnns_graph_compile_options_t(data: nil, size: 0)
    _ = BNNSGraphOptimizationPreference.self
    precondition(BNNSGraphOptimizationPreference(rawValue: 0).rawValue == 0)
    precondition(BNNSGraphOptimizationPreference(0) == BNNSGraphOptimizationPreference(rawValue: 0))
    precondition(BNNSGraphOptimizationPreference(rawValue: 0) != BNNSGraphOptimizationPreference(rawValue: 1))
    _ = BNNSOptimizerSGDMomentumVariant.self
    precondition(BNNSOptimizerSGDMomentumVariant(rawValue: 0).rawValue == 0)
    precondition(BNNSOptimizerSGDMomentumVariant(0) == BNNSOptimizerSGDMomentumVariant(rawValue: 0))
    precondition(BNNSOptimizerSGDMomentumVariant(rawValue: 0) != BNNSOptimizerSGDMomentumVariant(rawValue: 1))
    _ = BNNSOptimizerRegularizationFunction.self
    precondition(BNNSOptimizerRegularizationFunction(rawValue: 0).rawValue == 0)
    precondition(BNNSOptimizerRegularizationFunction(0) == BNNSOptimizerRegularizationFunction(rawValue: 0))
    precondition(BNNSOptimizerRegularizationFunction(rawValue: 0) != BNNSOptimizerRegularizationFunction(rawValue: 1))
    _ = BNNSOptimizerClippingFunction.self
    precondition(BNNSOptimizerClippingFunction(rawValue: 0).rawValue == 0)
    precondition(BNNSOptimizerClippingFunction(0) == BNNSOptimizerClippingFunction(rawValue: 0))
    precondition(BNNSOptimizerClippingFunction(rawValue: 0) != BNNSOptimizerClippingFunction(rawValue: 1))
    var arithFieldsRem: [UInt8] = [0]
    arithFieldsRem.withUnsafeMutableBytes { afp in
        _ = BNNSLayerParametersArithmetic(arithmetic_function: BNNSArithmeticFunction(rawValue: 3), arithmetic_function_fields: afp.baseAddress!, activation: BNNSActivation())
    }
    _ = BNNSLayerParametersArithmetic().activation
}
