import Accelerate
import Foundation

func testVForceCUnary() {
    var x: [Float] = [0.25, 0.5, 0.75]
    var y = [Float](repeating: 0, count: 3)
    var n: Int32 = 3
    vvexpf(&y, &x, &n)
    precondition(abs(y[0] - Foundation.exp(Float(0.25))) < 0.0001)
    vvexp2f(&y, &x, &n)
    vvexpm1f(&y, &x, &n)
    vvlogf(&y, &x, &n)
    vvlog2f(&y, &x, &n)
    vvlog10f(&y, &x, &n)
    vvlog1pf(&y, &x, &n)
    vvlogbf(&y, &x, &n)
    vvsinf(&y, &x, &n)
    vvcosf(&y, &x, &n)
    vvtanf(&y, &x, &n)
    vvasinf(&y, &x, &n)
    vvacosf(&y, &x, &n)
    vvatanf(&y, &x, &n)
    vvsinhf(&y, &x, &n)
    vvcoshf(&y, &x, &n)
    vvtanhf(&y, &x, &n)
    vvasinhf(&y, &x, &n)
    var ac: [Float] = [1.5, 2, 3]
    vvacoshf(&y, &ac, &n)
    var ath: [Float] = [0.1, 0.2, 0.3]
    vvatanhf(&y, &ath, &n)
    vvsqrtf(&y, &x, &n)
    vvceilf(&y, &x, &n)
    vvfloorf(&y, &x, &n)
    vvintf(&y, &x, &n)
    vvnintf(&y, &x, &n)
    vvrecf(&y, &x, &n)
    vvrsqrtf(&y, &x, &n)
    vvfabsf(&y, &x, &n)
    vvcbrtf(&y, &x, &n)
    vvsinpif(&y, &x, &n)
    vvcospif(&y, &x, &n)
    vvtanpif(&y, &x, &n)
    var s = [Float](repeating: 0, count: 3)
    var c = [Float](repeating: 0, count: 3)
    vvsincosf(&s, &c, &x, &n)
    var dx: [Double] = [0.25, 0.5, 0.75]
    var dy = [Double](repeating: 0, count: 3)
    vvexp(&dy, &dx, &n)
    vvexp2(&dy, &dx, &n)
    vvexpm1(&dy, &dx, &n)
    vvlog(&dy, &dx, &n)
    vvlog2(&dy, &dx, &n)
    vvlog10(&dy, &dx, &n)
    vvlog1p(&dy, &dx, &n)
    vvlogb(&dy, &dx, &n)
    vvsin(&dy, &dx, &n)
    vvcos(&dy, &dx, &n)
    vvtan(&dy, &dx, &n)
    vvasin(&dy, &dx, &n)
    vvacos(&dy, &dx, &n)
    vvatan(&dy, &dx, &n)
    vvsinh(&dy, &dx, &n)
    vvcosh(&dy, &dx, &n)
    vvtanh(&dy, &dx, &n)
    vvasinh(&dy, &dx, &n)
    var dac: [Double] = [1.5, 2, 3]
    vvacosh(&dy, &dac, &n)
    var dath: [Double] = [0.1, 0.2, 0.3]
    vvatanh(&dy, &dath, &n)
    vvsqrt(&dy, &dx, &n)
    vvceil(&dy, &dx, &n)
    vvfloor(&dy, &dx, &n)
    vvint(&dy, &dx, &n)
    vvnint(&dy, &dx, &n)
    vvrec(&dy, &dx, &n)
    vvrsqrt(&dy, &dx, &n)
    vvfabs(&dy, &dx, &n)
    vvcbrt(&dy, &dx, &n)
    vvsinpi(&dy, &dx, &n)
    vvcospi(&dy, &dx, &n)
    vvtanpi(&dy, &dx, &n)
    var ds = [Double](repeating: 0, count: 3)
    var dc = [Double](repeating: 0, count: 3)
    vvsincos(&ds, &dc, &dx, &n)
}

func testVForceCBinary() {
    var x: [Float] = [2, 3, 4]
    var y: [Float] = [2, 2, 2]
    var z = [Float](repeating: 0, count: 3)
    var n: Int32 = 3
    vvpowf(&z, &x, &y, &n)
    precondition(abs(z[0] - 4) < 0.0001)
    vvpowsf(&z, &x, &y, &n)
    vvdivf(&z, &x, &y, &n)
    vvfmodf(&z, &x, &y, &n)
    vvremainderf(&z, &x, &y, &n)
    vvatan2f(&z, &x, &y, &n)
    vvcopysignf(&z, &x, &y, &n)
    vvnextafterf(&z, &x, &y, &n)
    var dx: [Double] = [2, 3, 4]
    var dy: [Double] = [2, 2, 2]
    var dz = [Double](repeating: 0, count: 3)
    vvpow(&dz, &dx, &dy, &n)
    vvpows(&dz, &dx, &dy, &n)
    vvdiv(&dz, &dx, &dy, &n)
    vvfmod(&dz, &dx, &dy, &n)
    vvremainder(&dz, &dx, &dy, &n)
    vvatan2(&dz, &dx, &dy, &n)
    vvcopysign(&dz, &dx, &dy, &n)
    vvnextafter(&dz, &dx, &dy, &n)
}
