import Accelerate
import Foundation

func testVForceUnaryFloat() {
    let input: [Float] = [0.25, 0.5, 0.75]
    var out = [Float](repeating: 0, count: 3)
    vForce.exp(input, result: &out)
    precondition(abs(out[0] - Foundation.exp(Float(0.25))) < 0.0001)
    _ = vForce.exp(input)
    vForce.exp2(input, result: &out)
    _ = vForce.exp2(input)
    vForce.expm1(input, result: &out)
    _ = vForce.expm1(input)
    vForce.log(input, result: &out)
    _ = vForce.log(input)
    vForce.log2(input, result: &out)
    _ = vForce.log2(input)
    vForce.log10(input, result: &out)
    _ = vForce.log10(input)
    vForce.log1p(input, result: &out)
    _ = vForce.log1p(input)
    vForce.logb(input, result: &out)
    _ = vForce.logb(input)
    vForce.sin(input, result: &out)
    _ = vForce.sin(input)
    vForce.cos(input, result: &out)
    _ = vForce.cos(input)
    vForce.tan(input, result: &out)
    _ = vForce.tan(input)
    vForce.asin(input, result: &out)
    _ = vForce.asin(input)
    vForce.acos(input, result: &out)
    _ = vForce.acos(input)
    vForce.atan(input, result: &out)
    _ = vForce.atan(input)
    vForce.sinh(input, result: &out)
    _ = vForce.sinh(input)
    vForce.cosh(input, result: &out)
    _ = vForce.cosh(input)
    vForce.tanh(input, result: &out)
    _ = vForce.tanh(input)
    vForce.asinh(input, result: &out)
    _ = vForce.asinh(input)
    let acoshIn: [Float] = [1.5, 2, 3]
    vForce.acosh(acoshIn, result: &out)
    _ = vForce.acosh(acoshIn)
    let atanhIn: [Float] = [0.1, 0.2, 0.3]
    vForce.atanh(atanhIn, result: &out)
    _ = vForce.atanh(atanhIn)
    vForce.sqrt(input, result: &out)
    _ = vForce.sqrt(input)
    vForce.ceil(input, result: &out)
    _ = vForce.ceil(input)
    vForce.floor(input, result: &out)
    _ = vForce.floor(input)
    vForce.trunc(input, result: &out)
    _ = vForce.trunc(input)
    vForce.reciprocal(input, result: &out)
    _ = vForce.reciprocal(input)
    vForce.rsqrt(input, result: &out)
    _ = vForce.rsqrt(input)
    vForce.nearestInteger(input, result: &out)
    _ = vForce.nearestInteger(input)
    vForce.sinPi(input, result: &out)
    _ = vForce.sinPi(input)
    vForce.cosPi(input, result: &out)
    _ = vForce.cosPi(input)
    vForce.tanPi(input, result: &out)
    _ = vForce.tanPi(input)
    var s = [Float](repeating: 0, count: 3)
    var c = [Float](repeating: 0, count: 3)
    vForce.sincos(input, sinResult: &s, cosResult: &c)
    precondition(abs(s[1] - Foundation.sin(Float(0.5))) < 0.0001)
}

func testVForceUnaryDouble() {
    let input: [Double] = [0.25, 0.5, 0.75]
    var out = [Double](repeating: 0, count: 3)
    vForce.exp(input, result: &out)
    _ = vForce.exp(input)
    vForce.exp2(input, result: &out)
    _ = vForce.exp2(input)
    vForce.expm1(input, result: &out)
    _ = vForce.expm1(input)
    vForce.log(input, result: &out)
    _ = vForce.log(input)
    vForce.log2(input, result: &out)
    _ = vForce.log2(input)
    vForce.log10(input, result: &out)
    _ = vForce.log10(input)
    vForce.log1p(input, result: &out)
    _ = vForce.log1p(input)
    vForce.logb(input, result: &out)
    _ = vForce.logb(input)
    vForce.sin(input, result: &out)
    _ = vForce.sin(input)
    vForce.cos(input, result: &out)
    _ = vForce.cos(input)
    vForce.tan(input, result: &out)
    _ = vForce.tan(input)
    vForce.asin(input, result: &out)
    _ = vForce.asin(input)
    vForce.acos(input, result: &out)
    _ = vForce.acos(input)
    vForce.atan(input, result: &out)
    _ = vForce.atan(input)
    vForce.sinh(input, result: &out)
    _ = vForce.sinh(input)
    vForce.cosh(input, result: &out)
    _ = vForce.cosh(input)
    vForce.tanh(input, result: &out)
    _ = vForce.tanh(input)
    vForce.asinh(input, result: &out)
    _ = vForce.asinh(input)
    let acoshIn: [Double] = [1.5, 2, 3]
    vForce.acosh(acoshIn, result: &out)
    _ = vForce.acosh(acoshIn)
    let atanhIn: [Double] = [0.1, 0.2, 0.3]
    vForce.atanh(atanhIn, result: &out)
    _ = vForce.atanh(atanhIn)
    vForce.sqrt(input, result: &out)
    _ = vForce.sqrt(input)
    vForce.ceil(input, result: &out)
    _ = vForce.ceil(input)
    vForce.floor(input, result: &out)
    _ = vForce.floor(input)
    vForce.trunc(input, result: &out)
    _ = vForce.trunc(input)
    vForce.reciprocal(input, result: &out)
    _ = vForce.reciprocal(input)
    vForce.rsqrt(input, result: &out)
    _ = vForce.rsqrt(input)
    vForce.nearestInteger(input, result: &out)
    _ = vForce.nearestInteger(input)
    vForce.sinPi(input, result: &out)
    _ = vForce.sinPi(input)
    vForce.cosPi(input, result: &out)
    _ = vForce.cosPi(input)
    vForce.tanPi(input, result: &out)
    _ = vForce.tanPi(input)
    var s = [Double](repeating: 0, count: 3)
    var c = [Double](repeating: 0, count: 3)
    vForce.sincos(input, sinResult: &s, cosResult: &c)
}

func testVForceBinary() {
    let bases: [Float] = [2, 3, 4]
    let exponents: [Float] = [2, 2, 2]
    var out = [Float](repeating: 0, count: 3)
    vForce.pow(bases: bases, exponents: exponents, result: &out)
    precondition(out[0] == 4)
    _ = vForce.pow(bases: bases, exponents: exponents)
    vForce.atan2(x: inputX(), y: bases, result: &out)
    _ = vForce.atan2(x: bases, y: exponents)
    vForce.copysign(magnitudes: bases, signs: [-1, 1, -1], result: &out)
    _ = vForce.copysign(magnitudes: bases, signs: exponents)
    vForce.remainder(dividends: bases, divisors: exponents, result: &out)
    _ = vForce.remainder(dividends: bases, divisors: exponents)
    vForce.truncatingRemainder(dividends: bases, divisors: exponents, result: &out)
    _ = vForce.truncatingRemainder(dividends: bases, divisors: exponents)
    let db: [Double] = [2, 3, 4]
    let de: [Double] = [2, 2, 2]
    var dout = [Double](repeating: 0, count: 3)
    vForce.pow(bases: db, exponents: de, result: &dout)
    _ = vForce.pow(bases: db, exponents: de)
    vForce.atan2(x: db, y: de, result: &dout)
    _ = vForce.atan2(x: db, y: de)
    vForce.copysign(magnitudes: db, signs: de, result: &dout)
    _ = vForce.copysign(magnitudes: db, signs: de)
    vForce.remainder(dividends: db, divisors: de, result: &dout)
    _ = vForce.remainder(dividends: db, divisors: de)
    vForce.truncatingRemainder(dividends: db, divisors: de, result: &dout)
    _ = vForce.truncatingRemainder(dividends: db, divisors: de)
}

private func inputX() -> [Float] { [1, 2, 3] }
