import Accelerate
import Foundation

func testVImageCBufferFlags0() {
    var pixels: [UInt8] = [1, 2, 3, 4]
    pixels.withUnsafeMutableBytes { sb in
        var inb = vImage_Buffer(data: sb.baseAddress, height: 2, width: 2, rowBytes: 2)
        var outb = vImage_Buffer(data: sb.baseAddress, height: 2, width: 2, rowBytes: 2)
        _ = vImageByteSwap_Planar16U(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageClipToAlpha_ARGB8888(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageClipToAlpha_ARGBFFFF(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageClipToAlpha_RGBA8888(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageClipToAlpha_RGBAFFFF(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageContrastStretch_ARGB8888(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageContrastStretch_Planar8(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_12UTo16U(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_16Fto16Q12(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_16Fto16U(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_16Q12to16F(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_16Q12to16U(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_16Q12to8(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_16Q12toF(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_16UTo12U(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_16UToPlanar8(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_16Uto16F(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_16Uto16Q12(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_8to16Q12(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_ARGB1555toARGB8888(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_ARGB1555toRGB565(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_ARGB8888toARGB1555(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_ARGB8888toRGB565(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_BGRA8888toRGB565(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_Fto16Q12(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_Planar16FtoPlanar8(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_Planar16FtoPlanarF(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_Planar1toPlanar8(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_Planar2toPlanar8(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_Planar4toPlanar8(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_Planar8To16U(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_Planar8toPlanar16F(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_PlanarFtoPlanar16F(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_RGB565toRGB888(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_RGBA5551toRGB565(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_RGBA5551toRGBA8888(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_RGBA8888toRGB565(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageConvert_RGBA8888toRGBA5551(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageEqualization_ARGB8888(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageEqualization_Planar8(&inb, &outb, vImage_Flags(kvImageNoFlags))
    }
}

func testVImageCBufferFlags1() {
    var pixels: [UInt8] = [1, 2, 3, 4]
    pixels.withUnsafeMutableBytes { sb in
        var inb = vImage_Buffer(data: sb.baseAddress, height: 2, width: 2, rowBytes: 2)
        var outb = vImage_Buffer(data: sb.baseAddress, height: 2, width: 2, rowBytes: 2)
        _ = vImageHorizontalReflect_ARGB16F(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageHorizontalReflect_ARGB16S(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageHorizontalReflect_ARGB16U(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageHorizontalReflect_ARGB8888(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageHorizontalReflect_ARGBFFFF(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageHorizontalReflect_CbCr16F(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageHorizontalReflect_Planar16F(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageHorizontalReflect_Planar16U(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageHorizontalReflect_Planar8(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageHorizontalReflect_PlanarF(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImagePremultiplyData_ARGB16Q12(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImagePremultiplyData_ARGB16U(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImagePremultiplyData_ARGB8888(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImagePremultiplyData_ARGBFFFF(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImagePremultiplyData_RGBA16F(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImagePremultiplyData_RGBA16Q12(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImagePremultiplyData_RGBA16U(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImagePremultiplyData_RGBA8888(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImagePremultiplyData_RGBAFFFF(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageUnpremultiplyData_ARGB16Q12(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageUnpremultiplyData_ARGB16U(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageUnpremultiplyData_ARGB8888(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageUnpremultiplyData_ARGBFFFF(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageUnpremultiplyData_RGBA16F(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageUnpremultiplyData_RGBA16Q12(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageUnpremultiplyData_RGBA16U(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageUnpremultiplyData_RGBA8888(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageUnpremultiplyData_RGBAFFFF(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageVerticalReflect_ARGB16F(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageVerticalReflect_ARGB16S(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageVerticalReflect_ARGB16U(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageVerticalReflect_ARGB8888(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageVerticalReflect_ARGBFFFF(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageVerticalReflect_CbCr16F(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageVerticalReflect_Planar16F(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageVerticalReflect_Planar16U(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageVerticalReflect_Planar8(&inb, &outb, vImage_Flags(kvImageNoFlags))
        _ = vImageVerticalReflect_PlanarF(&inb, &outb, vImage_Flags(kvImageNoFlags))
    }
}

