import Accelerate
import Foundation

// Pixel/image constants are checked against their pinned numeric definitions.

func testVImagePinnedConstantValues0() {
    precondition(kvImageARGB16Q12 == vImageARGBType(rawValue: 0))
    precondition(kvImageARGB16U == vImageARGBType(rawValue: 1))
    precondition(kvImageARGB8888 == vImageARGBType(rawValue: 2))
    precondition(kvImageMDTableHint_16Q12 == vImageMDTableUsageHint(rawValue: 0))
    precondition(kvImageMDTableHint_Float == vImageMDTableUsageHint(rawValue: 1))
    precondition(kvImage420Yp8_Cb8_Cr8 == vImageYpCbCrType(rawValue: 0))
    precondition(kvImage420Yp8_CbCr8 == vImageYpCbCrType(rawValue: 1))
    precondition(kvImage422CbYpCrYp16 == vImageYpCbCrType(rawValue: 2))
    precondition(kvImage422CbYpCrYp8 == vImageYpCbCrType(rawValue: 3))
    precondition(kvImage422CbYpCrYp8_AA8 == vImageYpCbCrType(rawValue: 4))
    precondition(kvImage422CrYpCbYpCbYpCbYpCrYpCrYp10 == vImageYpCbCrType(rawValue: 5))
    precondition(kvImage422YpCbYpCr8 == vImageYpCbCrType(rawValue: 6))
    precondition(kvImage444AYpCbCr16 == vImageYpCbCrType(rawValue: 7))
    precondition(kvImage444AYpCbCr8 == vImageYpCbCrType(rawValue: 8))
    precondition(kvImage444CbYpCrA8 == vImageYpCbCrType(rawValue: 9))
    precondition(kvImage444CrYpCb10 == vImageYpCbCrType(rawValue: 10))
    precondition(kvImage444CrYpCb8 == vImageYpCbCrType(rawValue: 11))
    precondition(kvImageFullInterpolation == vImage_InterpolationMethod(rawValue: 1))
    precondition(kvImageHalfInterpolation == vImage_InterpolationMethod(rawValue: 2))
    precondition(kvImageNoInterpolation == vImage_InterpolationMethod(rawValue: 0))
    precondition(kRotate0DegreesClockwise == 10)
    precondition(kRotate0DegreesCounterClockwise == 11)
    precondition(kRotate180DegreesClockwise == 12)
    precondition(kRotate180DegreesCounterClockwise == 13)
    precondition(kRotate270DegreesClockwise == 14)
    precondition(kRotate270DegreesCounterClockwise == 15)
    precondition(kRotate90DegreesClockwise == 16)
    precondition(kRotate90DegreesCounterClockwise == 17)
    precondition(kvImageBufferTypeCode_Alpha == 18)
    precondition(kvImageBufferTypeCode_CGFormat == 19)
    precondition(kvImageBufferTypeCode_CMYK_Black == 20)
    precondition(kvImageBufferTypeCode_CMYK_Cyan == 21)
    precondition(kvImageBufferTypeCode_CMYK_Magenta == 22)
    precondition(kvImageBufferTypeCode_CMYK_Yellow == 23)
    precondition(kvImageBufferTypeCode_Cb == 24)
    precondition(kvImageBufferTypeCode_Chroma == 25)
    precondition(kvImageBufferTypeCode_Chunky == 26)
    precondition(kvImageBufferTypeCode_ColorSpaceChannel1 == 27)
    precondition(kvImageBufferTypeCode_ColorSpaceChannel10 == 28)
    precondition(kvImageBufferTypeCode_ColorSpaceChannel11 == 29)
    precondition(kvImageBufferTypeCode_ColorSpaceChannel12 == 30)
    precondition(kvImageBufferTypeCode_ColorSpaceChannel13 == 31)
}

func testVImagePinnedConstantValues1() {
    precondition(kvImageBufferTypeCode_ColorSpaceChannel14 == 32)
    precondition(kvImageBufferTypeCode_ColorSpaceChannel15 == 33)
    precondition(kvImageBufferTypeCode_ColorSpaceChannel16 == 34)
    precondition(kvImageBufferTypeCode_ColorSpaceChannel2 == 35)
    precondition(kvImageBufferTypeCode_ColorSpaceChannel3 == 36)
    precondition(kvImageBufferTypeCode_ColorSpaceChannel4 == 37)
    precondition(kvImageBufferTypeCode_ColorSpaceChannel5 == 38)
    precondition(kvImageBufferTypeCode_ColorSpaceChannel6 == 39)
    precondition(kvImageBufferTypeCode_ColorSpaceChannel7 == 40)
    precondition(kvImageBufferTypeCode_ColorSpaceChannel8 == 41)
    precondition(kvImageBufferTypeCode_ColorSpaceChannel9 == 42)
    precondition(kvImageBufferTypeCode_Cr == 43)
    precondition(kvImageBufferTypeCode_EndOfList == 44)
    precondition(kvImageBufferTypeCode_Indexed == 45)
    precondition(kvImageBufferTypeCode_LAB_A == 46)
    precondition(kvImageBufferTypeCode_LAB_B == 47)
    precondition(kvImageBufferTypeCode_LAB_L == 48)
    precondition(kvImageBufferTypeCode_Luminance == 49)
    precondition(kvImageBufferTypeCode_Monochrome == 50)
    precondition(kvImageBufferTypeCode_RGB_Blue == 51)
    precondition(kvImageBufferTypeCode_RGB_Green == 52)
    precondition(kvImageBufferTypeCode_RGB_Red == 53)
    precondition(kvImageBufferTypeCode_UniqueFormatCount == 54)
    precondition(kvImageBufferTypeCode_XYZ_X == 55)
    precondition(kvImageBufferTypeCode_XYZ_Y == 56)
    precondition(kvImageBufferTypeCode_XYZ_Z == 57)
    precondition(kvImageCVImageFormat_AlphaIsOneHint == 58)
    precondition(kvImageCVImageFormat_ChromaSiting == 59)
    precondition(kvImageCVImageFormat_ColorSpace == 60)
    precondition(kvImageCVImageFormat_ConversionMatrix == 61)
    precondition(kvImageCVImageFormat_NoError == 62)
    precondition(kvImageCVImageFormat_VideoChannelDescription == 63)
    precondition(kvImageConvert_DitherAtkinson == 4)
    precondition(kvImageConvert_DitherFloydSteinberg == 3)
    precondition(kvImageConvert_DitherNone == 0)
    precondition(kvImageConvert_DitherOrdered == 1)
    precondition(kvImageConvert_DitherOrderedReproducible == 2)
    precondition(kvImageConvert_OrderedGaussianBlue == 0)
    precondition(kvImageConvert_OrderedNoiseShapeMask == 1)
    precondition(kvImageConvert_OrderedUniformBlue == 2)
    precondition(kvImageGamma_11_over_5_half_precision == 5)
}
