import Foundation

/// HID Keyboard/Keypad usage-page codes published by Apple's `GCKeyCodes.h`.
public struct GCKeyCode: RawRepresentable, Hashable, Sendable {
    public var rawValue: Int
    public init(rawValue: Int) { self.rawValue = rawValue }
}

extension GCKeyCode {
    public static let application = GCKeyCode(rawValue: 101)
    public static let backslash = GCKeyCode(rawValue: 49)
    public static let capsLock = GCKeyCode(rawValue: 57)
    public static let closeBracket = GCKeyCode(rawValue: 48)
    public static let comma = GCKeyCode(rawValue: 54)
    public static let deleteForward = GCKeyCode(rawValue: 76)
    public static let deleteOrBackspace = GCKeyCode(rawValue: 42)
    public static let downArrow = GCKeyCode(rawValue: 81)
    public static let eight = GCKeyCode(rawValue: 37)
    public static let end = GCKeyCode(rawValue: 77)
    public static let equalSign = GCKeyCode(rawValue: 46)
    public static let escape = GCKeyCode(rawValue: 41)
    public static let F1 = GCKeyCode(rawValue: 58)
    public static let F10 = GCKeyCode(rawValue: 67)
    public static let F11 = GCKeyCode(rawValue: 68)
    public static let F12 = GCKeyCode(rawValue: 69)
    public static let F13 = GCKeyCode(rawValue: 104)
    public static let F14 = GCKeyCode(rawValue: 105)
    public static let F15 = GCKeyCode(rawValue: 106)
    public static let F16 = GCKeyCode(rawValue: 107)
    public static let F17 = GCKeyCode(rawValue: 108)
    public static let F18 = GCKeyCode(rawValue: 109)
    public static let F19 = GCKeyCode(rawValue: 110)
    public static let F2 = GCKeyCode(rawValue: 59)
    public static let F20 = GCKeyCode(rawValue: 111)
    public static let F3 = GCKeyCode(rawValue: 60)
    public static let F4 = GCKeyCode(rawValue: 61)
    public static let F5 = GCKeyCode(rawValue: 62)
    public static let F6 = GCKeyCode(rawValue: 63)
    public static let F7 = GCKeyCode(rawValue: 64)
    public static let F8 = GCKeyCode(rawValue: 65)
    public static let F9 = GCKeyCode(rawValue: 66)
    public static let five = GCKeyCode(rawValue: 34)
    public static let four = GCKeyCode(rawValue: 33)
    public static let graveAccentAndTilde = GCKeyCode(rawValue: 53)
    public static let home = GCKeyCode(rawValue: 74)
    public static let hyphen = GCKeyCode(rawValue: 45)
    public static let insert = GCKeyCode(rawValue: 73)
    public static let international1 = GCKeyCode(rawValue: 135)
    public static let international2 = GCKeyCode(rawValue: 136)
    public static let international3 = GCKeyCode(rawValue: 137)
    public static let international4 = GCKeyCode(rawValue: 138)
    public static let international5 = GCKeyCode(rawValue: 139)
    public static let international6 = GCKeyCode(rawValue: 140)
    public static let international7 = GCKeyCode(rawValue: 141)
    public static let international8 = GCKeyCode(rawValue: 142)
    public static let international9 = GCKeyCode(rawValue: 143)
    public static let keyA = GCKeyCode(rawValue: 4)
    public static let keyB = GCKeyCode(rawValue: 5)
    public static let keyC = GCKeyCode(rawValue: 6)
    public static let keyD = GCKeyCode(rawValue: 7)
    public static let keyE = GCKeyCode(rawValue: 8)
    public static let keyF = GCKeyCode(rawValue: 9)
    public static let keyG = GCKeyCode(rawValue: 10)
    public static let keyH = GCKeyCode(rawValue: 11)
    public static let keyI = GCKeyCode(rawValue: 12)
    public static let keyJ = GCKeyCode(rawValue: 13)
    public static let keyK = GCKeyCode(rawValue: 14)
    public static let keyL = GCKeyCode(rawValue: 15)
    public static let keyM = GCKeyCode(rawValue: 16)
    public static let keyN = GCKeyCode(rawValue: 17)
    public static let keyO = GCKeyCode(rawValue: 18)
    public static let keyP = GCKeyCode(rawValue: 19)
    public static let keyQ = GCKeyCode(rawValue: 20)
    public static let keyR = GCKeyCode(rawValue: 21)
    public static let keyS = GCKeyCode(rawValue: 22)
    public static let keyT = GCKeyCode(rawValue: 23)
    public static let keyU = GCKeyCode(rawValue: 24)
    public static let keyV = GCKeyCode(rawValue: 25)
    public static let keyW = GCKeyCode(rawValue: 26)
    public static let keyX = GCKeyCode(rawValue: 27)
    public static let keyY = GCKeyCode(rawValue: 28)
    public static let keyZ = GCKeyCode(rawValue: 29)
    public static let keypad0 = GCKeyCode(rawValue: 98)
    public static let keypad1 = GCKeyCode(rawValue: 89)
    public static let keypad2 = GCKeyCode(rawValue: 90)
    public static let keypad3 = GCKeyCode(rawValue: 91)
    public static let keypad4 = GCKeyCode(rawValue: 92)
    public static let keypad5 = GCKeyCode(rawValue: 93)
    public static let keypad6 = GCKeyCode(rawValue: 94)
    public static let keypad7 = GCKeyCode(rawValue: 95)
    public static let keypad8 = GCKeyCode(rawValue: 96)
    public static let keypad9 = GCKeyCode(rawValue: 97)
    public static let keypadAsterisk = GCKeyCode(rawValue: 85)
    public static let keypadEnter = GCKeyCode(rawValue: 88)
    public static let keypadEqualSign = GCKeyCode(rawValue: 103)
    public static let keypadHyphen = GCKeyCode(rawValue: 86)
    public static let keypadNumLock = GCKeyCode(rawValue: 83)
    public static let keypadPeriod = GCKeyCode(rawValue: 99)
    public static let keypadPlus = GCKeyCode(rawValue: 87)
    public static let keypadSlash = GCKeyCode(rawValue: 84)
    public static let LANG1 = GCKeyCode(rawValue: 144)
    public static let LANG2 = GCKeyCode(rawValue: 145)
    public static let LANG3 = GCKeyCode(rawValue: 146)
    public static let LANG4 = GCKeyCode(rawValue: 147)
    public static let LANG5 = GCKeyCode(rawValue: 148)
    public static let LANG6 = GCKeyCode(rawValue: 149)
    public static let LANG7 = GCKeyCode(rawValue: 150)
    public static let LANG8 = GCKeyCode(rawValue: 151)
    public static let LANG9 = GCKeyCode(rawValue: 152)
    public static let leftAlt = GCKeyCode(rawValue: 226)
    public static let leftArrow = GCKeyCode(rawValue: 80)
    public static let leftControl = GCKeyCode(rawValue: 224)
    public static let leftGUI = GCKeyCode(rawValue: 227)
    public static let leftShift = GCKeyCode(rawValue: 225)
    public static let nine = GCKeyCode(rawValue: 38)
    public static let nonUSBackslash = GCKeyCode(rawValue: 100)
    public static let nonUSPound = GCKeyCode(rawValue: 50)
    public static let one = GCKeyCode(rawValue: 30)
    public static let openBracket = GCKeyCode(rawValue: 47)
    public static let pageDown = GCKeyCode(rawValue: 78)
    public static let pageUp = GCKeyCode(rawValue: 75)
    public static let pause = GCKeyCode(rawValue: 72)
    public static let period = GCKeyCode(rawValue: 55)
    public static let power = GCKeyCode(rawValue: 102)
    public static let printScreen = GCKeyCode(rawValue: 70)
    public static let quote = GCKeyCode(rawValue: 52)
    public static let returnOrEnter = GCKeyCode(rawValue: 40)
    public static let rightAlt = GCKeyCode(rawValue: 230)
    public static let rightArrow = GCKeyCode(rawValue: 79)
    public static let rightControl = GCKeyCode(rawValue: 228)
    public static let rightGUI = GCKeyCode(rawValue: 231)
    public static let rightShift = GCKeyCode(rawValue: 229)
    public static let scrollLock = GCKeyCode(rawValue: 71)
    public static let semicolon = GCKeyCode(rawValue: 51)
    public static let seven = GCKeyCode(rawValue: 36)
    public static let six = GCKeyCode(rawValue: 35)
    public static let slash = GCKeyCode(rawValue: 56)
    public static let spacebar = GCKeyCode(rawValue: 44)
    public static let tab = GCKeyCode(rawValue: 43)
    public static let three = GCKeyCode(rawValue: 32)
    public static let two = GCKeyCode(rawValue: 31)
    public static let upArrow = GCKeyCode(rawValue: 82)
    public static let zero = GCKeyCode(rawValue: 39)
}

// Portable key-name strings. Apple's exact NSString payloads remain an oracle question.
public let GCKeyA = "A"
public let GCKeyApplication = "Application"
public let GCKeyB = "B"
public let GCKeyBackslash = "Backslash"
public let GCKeyC = "C"
public let GCKeyCapsLock = "CapsLock"
public let GCKeyCloseBracket = "CloseBracket"
public let GCKeyComma = "Comma"
public let GCKeyD = "D"
public let GCKeyDeleteForward = "DeleteForward"
public let GCKeyDeleteOrBackspace = "DeleteOrBackspace"
public let GCKeyDownArrow = "DownArrow"
public let GCKeyE = "E"
public let GCKeyEight = "Eight"
public let GCKeyEnd = "End"
public let GCKeyEqualSign = "EqualSign"
public let GCKeyEscape = "Escape"
public let GCKeyF = "F"
public let GCKeyF1 = "F1"
public let GCKeyF10 = "F10"
public let GCKeyF11 = "F11"
public let GCKeyF12 = "F12"
public let GCKeyF13 = "F13"
public let GCKeyF14 = "F14"
public let GCKeyF15 = "F15"
public let GCKeyF16 = "F16"
public let GCKeyF17 = "F17"
public let GCKeyF18 = "F18"
public let GCKeyF19 = "F19"
public let GCKeyF2 = "F2"
public let GCKeyF20 = "F20"
public let GCKeyF3 = "F3"
public let GCKeyF4 = "F4"
public let GCKeyF5 = "F5"
public let GCKeyF6 = "F6"
public let GCKeyF7 = "F7"
public let GCKeyF8 = "F8"
public let GCKeyF9 = "F9"
public let GCKeyFive = "Five"
public let GCKeyFour = "Four"
public let GCKeyG = "G"
public let GCKeyGraveAccentAndTilde = "GraveAccentAndTilde"
public let GCKeyH = "H"
public let GCKeyHome = "Home"
public let GCKeyHyphen = "Hyphen"
public let GCKeyI = "I"
public let GCKeyInsert = "Insert"
public let GCKeyInternational1 = "International1"
public let GCKeyInternational2 = "International2"
public let GCKeyInternational3 = "International3"
public let GCKeyInternational4 = "International4"
public let GCKeyInternational5 = "International5"
public let GCKeyInternational6 = "International6"
public let GCKeyInternational7 = "International7"
public let GCKeyInternational8 = "International8"
public let GCKeyInternational9 = "International9"
public let GCKeyJ = "J"
public let GCKeyK = "K"
public let GCKeyKeypad0 = "Keypad0"
public let GCKeyKeypad1 = "Keypad1"
public let GCKeyKeypad2 = "Keypad2"
public let GCKeyKeypad3 = "Keypad3"
public let GCKeyKeypad4 = "Keypad4"
public let GCKeyKeypad5 = "Keypad5"
public let GCKeyKeypad6 = "Keypad6"
public let GCKeyKeypad7 = "Keypad7"
public let GCKeyKeypad8 = "Keypad8"
public let GCKeyKeypad9 = "Keypad9"
public let GCKeyKeypadAsterisk = "KeypadAsterisk"
public let GCKeyKeypadEnter = "KeypadEnter"
public let GCKeyKeypadEqualSign = "KeypadEqualSign"
public let GCKeyKeypadHyphen = "KeypadHyphen"
public let GCKeyKeypadNumLock = "KeypadNumLock"
public let GCKeyKeypadPeriod = "KeypadPeriod"
public let GCKeyKeypadPlus = "KeypadPlus"
public let GCKeyKeypadSlash = "KeypadSlash"
public let GCKeyL = "L"
public let GCKeyLANG1 = "LANG1"
public let GCKeyLANG2 = "LANG2"
public let GCKeyLANG3 = "LANG3"
public let GCKeyLANG4 = "LANG4"
public let GCKeyLANG5 = "LANG5"
public let GCKeyLANG6 = "LANG6"
public let GCKeyLANG7 = "LANG7"
public let GCKeyLANG8 = "LANG8"
public let GCKeyLANG9 = "LANG9"
public let GCKeyLeftAlt = "LeftAlt"
public let GCKeyLeftArrow = "LeftArrow"
public let GCKeyLeftControl = "LeftControl"
public let GCKeyLeftGUI = "LeftGUI"
public let GCKeyLeftShift = "LeftShift"
public let GCKeyM = "M"
public let GCKeyN = "N"
public let GCKeyNine = "Nine"
public let GCKeyNonUSBackslash = "NonUSBackslash"
public let GCKeyNonUSPound = "NonUSPound"
public let GCKeyO = "O"
public let GCKeyOne = "One"
public let GCKeyOpenBracket = "OpenBracket"
public let GCKeyP = "P"
public let GCKeyPageDown = "PageDown"
public let GCKeyPageUp = "PageUp"
public let GCKeyPause = "Pause"
public let GCKeyPeriod = "Period"
public let GCKeyPower = "Power"
public let GCKeyPrintScreen = "PrintScreen"
public let GCKeyQ = "Q"
public let GCKeyQuote = "Quote"
public let GCKeyR = "R"
public let GCKeyReturnOrEnter = "ReturnOrEnter"
public let GCKeyRightAlt = "RightAlt"
public let GCKeyRightArrow = "RightArrow"
public let GCKeyRightControl = "RightControl"
public let GCKeyRightGUI = "RightGUI"
public let GCKeyRightShift = "RightShift"
public let GCKeyS = "S"
public let GCKeyScrollLock = "ScrollLock"
public let GCKeySemicolon = "Semicolon"
public let GCKeySeven = "Seven"
public let GCKeySix = "Six"
public let GCKeySlash = "Slash"
public let GCKeySpacebar = "Spacebar"
public let GCKeyT = "T"
public let GCKeyTab = "Tab"
public let GCKeyThree = "Three"
public let GCKeyTwo = "Two"
public let GCKeyU = "U"
public let GCKeyUpArrow = "UpArrow"
public let GCKeyV = "V"
public let GCKeyW = "W"
public let GCKeyX = "X"
public let GCKeyY = "Y"
public let GCKeyZ = "Z"
public let GCKeyZero = "Zero"
