import OpenGLES

func testGLESFunctionsAttrib() {
    ogWithContext {
        _ = glGetError()
        glVertexAttrib1f(0, 0)
        glVertexAttrib1fv(0, nil)
        glVertexAttrib2f(0, 0, 0)
        glVertexAttrib2fv(0, nil)
        glVertexAttrib3f(0, 0, 0, 0)
        glVertexAttrib3fv(0, nil)
        glVertexAttrib4f(0, 0, 0, 0, 0)
        glVertexAttrib4fv(0, nil)
        glVertexAttribDivisor(0, 0)
        glVertexAttribDivisorEXT(0, 0)
        glVertexAttribI4i(0, 0, 0, 0, 0)
        glVertexAttribI4iv(0, nil)
        glVertexAttribI4ui(0, 0, 0, 0, 0)
        glVertexAttribI4uiv(0, nil)
        glVertexAttribIPointer(0, 0, 0, 0, nil)
        glVertexAttribPointer(0, 0, 0, 0, 0, nil)
        _ = glGetError()
    }
}

func testGLESFunctionsBuffer() {
    ogWithContext {
        _ = glGetError()
        glBufferData(0, 0, nil, 0)
        glBufferSubData(0, 0, 0, nil)
        glCopyBufferSubData(0, 0, 0, 0, 0)
        glFlushMappedBufferRange(0, 0, 0)
        glFlushMappedBufferRangeEXT(0, 0, 0)
        _ = glMapBufferOES(0, 0)
        _ = glMapBufferRange(0, 0, 0, 0)
        _ = glMapBufferRangeEXT(0, 0, 0, 0)
        _ = glUnmapBuffer(0)
        _ = glUnmapBufferOES(0)
        _ = glGetError()
    }
}

func testGLESFunctionsDraw() {
    ogWithContext {
        _ = glGetError()
        glClear(0)
        glClearBufferfi(0, 0, 0, 0)
        glClearBufferfv(0, 0, nil)
        glClearBufferiv(0, 0, nil)
        glClearBufferuiv(0, 0, nil)
        glClearColor(0, 0, 0, 0)
        glClearColorx(0, 0, 0, 0)
        glClearDepthf(0)
        glClearDepthx(0)
        glClearStencil(0)
        glDiscardFramebufferEXT(0, 0, nil)
        glDrawArrays(0, 0, 0)
        glDrawArraysInstanced(0, 0, 0, 0)
        glDrawArraysInstancedEXT(0, 0, 0, 0)
        glDrawBuffers(0, nil)
        glDrawElements(0, 0, 0, nil)
        glDrawElementsInstanced(0, 0, 0, nil, 0)
        glDrawElementsInstancedEXT(0, 0, 0, nil, 0)
        glDrawRangeElements(0, 0, 0, 0, 0, nil)
        glDrawTexfOES(0, 0, 0, 0, 0)
        glDrawTexfvOES(nil)
        glDrawTexiOES(0, 0, 0, 0, 0)
        glDrawTexivOES(nil)
        glDrawTexsOES(0, 0, 0, 0, 0)
        glDrawTexsvOES(nil)
        glDrawTexxOES(0, 0, 0, 0, 0)
        glDrawTexxvOES(nil)
        glFinish()
        glFlush()
        glReadBuffer(0)
        glReadPixels(0, 0, 0, 0, 0, 0, nil)
        _ = glGetError()
    }
}

func testGLESFunctionsES1() {
    ogWithContext {
        _ = glGetError()
        glClipPlanef(0, nil)
        glClipPlanex(0, nil)
        glColor4f(0, 0, 0, 0)
        glColor4ub(0, 0, 0, 0)
        glColor4x(0, 0, 0, 0)
        glColorPointer(0, 0, 0, nil)
        glFogf(0, 0)
        glFogfv(0, nil)
        glFogx(0, 0)
        glFogxv(0, nil)
        glLightModelf(0, 0)
        glLightModelfv(0, nil)
        glLightModelx(0, 0)
        glLightModelxv(0, nil)
        glLightf(0, 0, 0)
        glLightfv(0, 0, nil)
        glLightx(0, 0, 0)
        glLightxv(0, 0, nil)
        glLogicOp(0)
        glMaterialf(0, 0, 0)
        glMaterialfv(0, 0, nil)
        glMaterialx(0, 0, 0)
        glMaterialxv(0, 0, nil)
        glNormal3f(0, 0, 0)
        glNormal3x(0, 0, 0)
        glNormalPointer(0, 0, nil)
        glPointParameterf(0, 0)
        glPointParameterfv(0, nil)
        glPointParameterx(0, 0)
        glPointParameterxv(0, nil)
        glPointSize(0)
        glPointSizePointerOES(0, 0, nil)
        glPointSizex(0)
        glShadeModel(0)
        glVertexPointer(0, 0, 0, nil)
        _ = glGetError()
    }
}

func testGLESFunctionsFramebuffer() {
    ogWithContext {
        _ = glGetError()
        glBlitFramebuffer(0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
        _ = glCheckFramebufferStatus(0)
        _ = glCheckFramebufferStatusOES(0)
        glFramebufferRenderbuffer(0, 0, 0, 0)
        glFramebufferRenderbufferOES(0, 0, 0, 0)
        glFramebufferTexture2D(0, 0, 0, 0, 0)
        glFramebufferTexture2DOES(0, 0, 0, 0, 0)
        glFramebufferTextureLayer(0, 0, 0, 0, 0)
        glInvalidateFramebuffer(0, 0, nil)
        glInvalidateSubFramebuffer(0, 0, nil, 0, 0, 0, 0)
        glRenderbufferStorage(0, 0, 0, 0)
        glRenderbufferStorageMultisample(0, 0, 0, 0, 0)
        glRenderbufferStorageMultisampleAPPLE(0, 0, 0, 0, 0)
        glRenderbufferStorageOES(0, 0, 0, 0)
        _ = glGetError()
    }
}

func testGLESFunctionsGets() {
    ogWithContext {
        _ = glGetError()
        glGetActiveAttrib(0, 0, 0, nil, nil, nil, nil)
        glGetActiveUniform(0, 0, 0, nil, nil, nil, nil)
        glGetActiveUniformBlockName(0, 0, 0, nil, nil)
        glGetActiveUniformBlockiv(0, 0, 0, nil)
        glGetActiveUniformsiv(0, 0, nil, 0, nil)
        glGetAttachedShaders(0, 0, nil, nil)
        _ = glGetAttribLocation(0, nil)
        glGetBooleanv(0, nil)
        glGetBufferParameteri64v(0, 0, nil)
        glGetBufferParameteriv(0, 0, nil)
        glGetBufferPointerv(0, 0, nil)
        glGetBufferPointervOES(0, 0, nil)
        glGetClipPlanef(0, nil)
        glGetClipPlanex(0, nil)
        _ = glGetError()
        glGetFixedv(0, nil)
        glGetFloatv(0, nil)
        _ = glGetFragDataLocation(0, nil)
        glGetFramebufferAttachmentParameteriv(0, 0, 0, nil)
        glGetFramebufferAttachmentParameterivOES(0, 0, 0, nil)
        glGetInteger64i_v(0, 0, nil)
        glGetInteger64v(0, nil)
        glGetInteger64vAPPLE(0, nil)
        glGetIntegeri_v(0, 0, nil)
        glGetIntegerv(0, nil)
        glGetInternalformativ(0, 0, 0, 0, nil)
        glGetLightfv(0, 0, nil)
        glGetLightxv(0, 0, nil)
        glGetMaterialfv(0, 0, nil)
        glGetMaterialxv(0, 0, nil)
        glGetObjectLabelEXT(0, 0, 0, nil, nil)
        glGetPointerv(0, nil)
        glGetProgramBinary(0, 0, nil, nil, nil)
        glGetProgramInfoLog(0, 0, nil, nil)
        glGetProgramPipelineInfoLogEXT(0, 0, nil, nil)
        glGetProgramPipelineivEXT(0, 0, nil)
        glGetProgramiv(0, 0, nil)
        glGetQueryObjectuiv(0, 0, nil)
        glGetQueryObjectuivEXT(0, 0, nil)
        glGetQueryiv(0, 0, nil)
        glGetQueryivEXT(0, 0, nil)
        glGetRenderbufferParameteriv(0, 0, nil)
        glGetRenderbufferParameterivOES(0, 0, nil)
        glGetSamplerParameterfv(0, 0, nil)
        glGetSamplerParameteriv(0, 0, nil)
        glGetShaderInfoLog(0, 0, nil, nil)
        glGetShaderPrecisionFormat(0, 0, nil, nil)
        glGetShaderSource(0, 0, nil, nil)
        glGetShaderiv(0, 0, nil)
        _ = glGetString(0)
        _ = glGetStringi(0, 0)
        glGetSynciv(nil, 0, 0, nil, nil)
        glGetSyncivAPPLE(nil, 0, 0, nil, nil)
        glGetTexEnvfv(0, 0, nil)
        glGetTexEnviv(0, 0, nil)
        glGetTexEnvxv(0, 0, nil)
        glGetTexParameterfv(0, 0, nil)
        glGetTexParameteriv(0, 0, nil)
        glGetTexParameterxv(0, 0, nil)
        glGetTransformFeedbackVarying(0, 0, 0, nil, nil, nil, nil)
        _ = glGetUniformBlockIndex(0, nil)
        glGetUniformIndices(0, 0, nil, nil)
        _ = glGetUniformLocation(0, nil)
        glGetUniformfv(0, 0, nil)
        glGetUniformiv(0, 0, nil)
        glGetUniformuiv(0, 0, nil)
        glGetVertexAttribIiv(0, 0, nil)
        glGetVertexAttribIuiv(0, 0, nil)
        glGetVertexAttribPointerv(0, 0, nil)
        glGetVertexAttribfv(0, 0, nil)
        glGetVertexAttribiv(0, 0, nil)
        _ = glGetError()
    }
}

func testGLESFunctionsMatrix() {
    ogWithContext {
        _ = glGetError()
        glFrustumf(0, 0, 0, 0, 0, 0)
        glFrustumx(0, 0, 0, 0, 0, 0)
        glLoadIdentity()
        glLoadMatrixf(nil)
        glLoadMatrixx(nil)
        glLoadPaletteFromModelViewMatrixOES()
        glMatrixIndexPointerOES(0, 0, 0, nil)
        glMatrixMode(0)
        glMultMatrixf(nil)
        glMultMatrixx(nil)
        glMultiTexCoord4f(0, 0, 0, 0, 0)
        glMultiTexCoord4x(0, 0, 0, 0, 0)
        glOrthof(0, 0, 0, 0, 0, 0)
        glOrthox(0, 0, 0, 0, 0, 0)
        glPopGroupMarkerEXT()
        glPopMatrix()
        glPushGroupMarkerEXT(0, nil)
        glPushMatrix()
        glRotatef(0, 0, 0, 0)
        glRotatex(0, 0, 0, 0)
        glScalef(0, 0, 0)
        glScalex(0, 0, 0)
        glTranslatef(0, 0, 0)
        glTranslatex(0, 0, 0)
        _ = glGetError()
    }
}

func testGLESFunctionsNames() {
    ogWithContext {
        _ = glGetError()
        glBindAttribLocation(0, 0, nil)
        glBindBuffer(0, 0)
        glBindBufferBase(0, 0, 0)
        glBindBufferRange(0, 0, 0, 0, 0)
        glBindFramebuffer(0, 0)
        glBindFramebufferOES(0, 0)
        glBindProgramPipelineEXT(0)
        glBindRenderbuffer(0, 0)
        glBindRenderbufferOES(0, 0)
        glBindSampler(0, 0)
        glBindTexture(0, 0)
        glBindTransformFeedback(0, 0)
        glBindVertexArray(0)
        glBindVertexArrayOES(0)
        glDeleteBuffers(0, nil)
        glDeleteFramebuffers(0, nil)
        glDeleteFramebuffersOES(0, nil)
        glDeleteProgram(0)
        glDeleteProgramPipelinesEXT(0, nil)
        glDeleteQueries(0, nil)
        glDeleteQueriesEXT(0, nil)
        glDeleteRenderbuffers(0, nil)
        glDeleteRenderbuffersOES(0, nil)
        glDeleteSamplers(0, nil)
        glDeleteShader(0)
        glDeleteSync(nil)
        glDeleteSyncAPPLE(nil)
        glDeleteTextures(0, nil)
        glDeleteTransformFeedbacks(0, nil)
        glDeleteVertexArrays(0, nil)
        glDeleteVertexArraysOES(0, nil)
        glGenBuffers(0, nil)
        glGenFramebuffers(0, nil)
        glGenFramebuffersOES(0, nil)
        glGenProgramPipelinesEXT(0, nil)
        glGenQueries(0, nil)
        glGenQueriesEXT(0, nil)
        glGenRenderbuffers(0, nil)
        glGenRenderbuffersOES(0, nil)
        glGenSamplers(0, nil)
        glGenTextures(0, nil)
        glGenTransformFeedbacks(0, nil)
        glGenVertexArrays(0, nil)
        glGenVertexArraysOES(0, nil)
        glGenerateMipmap(0)
        glGenerateMipmapOES(0)
        _ = glIsBuffer(0)
        _ = glIsEnabled(0)
        _ = glIsFramebuffer(0)
        _ = glIsFramebufferOES(0)
        _ = glIsProgram(0)
        _ = glIsProgramPipelineEXT(0)
        _ = glIsQuery(0)
        _ = glIsQueryEXT(0)
        _ = glIsRenderbuffer(0)
        _ = glIsRenderbufferOES(0)
        _ = glIsSampler(0)
        _ = glIsShader(0)
        _ = glIsSync(nil)
        _ = glIsSyncAPPLE(nil)
        _ = glIsTexture(0)
        _ = glIsTransformFeedback(0)
        _ = glIsVertexArray(0)
        _ = glIsVertexArrayOES(0)
        _ = glGetError()
    }
}

func testGLESFunctionsOther() {
    ogWithContext {
        _ = glGetError()
        glActiveShaderProgramEXT(0, 0)
        glBeginTransformFeedback(0)
        glCurrentPaletteMatrixOES(0)
        glEndTransformFeedback()
        glInsertEventMarkerEXT(0, nil)
        glLabelObjectEXT(0, 0, 0, nil)
        glPauseTransformFeedback()
        glProgramBinary(0, 0, nil, 0)
        glProgramParameteri(0, 0, 0)
        glProgramParameteriEXT(0, 0, 0)
        glProgramUniform1fEXT(0, 0, 0)
        glProgramUniform1fvEXT(0, 0, 0, nil)
        glProgramUniform1iEXT(0, 0, 0)
        glProgramUniform1ivEXT(0, 0, 0, nil)
        glProgramUniform1uiEXT(0, 0, 0)
        glProgramUniform1uivEXT(0, 0, 0, nil)
        glProgramUniform2fEXT(0, 0, 0, 0)
        glProgramUniform2fvEXT(0, 0, 0, nil)
        glProgramUniform2iEXT(0, 0, 0, 0)
        glProgramUniform2ivEXT(0, 0, 0, nil)
        glProgramUniform2uiEXT(0, 0, 0, 0)
        glProgramUniform2uivEXT(0, 0, 0, nil)
        glProgramUniform3fEXT(0, 0, 0, 0, 0)
        glProgramUniform3fvEXT(0, 0, 0, nil)
        glProgramUniform3iEXT(0, 0, 0, 0, 0)
        glProgramUniform3ivEXT(0, 0, 0, nil)
        glProgramUniform3uiEXT(0, 0, 0, 0, 0)
        glProgramUniform3uivEXT(0, 0, 0, nil)
        glProgramUniform4fEXT(0, 0, 0, 0, 0, 0)
        glProgramUniform4fvEXT(0, 0, 0, nil)
        glProgramUniform4iEXT(0, 0, 0, 0, 0, 0)
        glProgramUniform4ivEXT(0, 0, 0, nil)
        glProgramUniform4uiEXT(0, 0, 0, 0, 0, 0)
        glProgramUniform4uivEXT(0, 0, 0, nil)
        glProgramUniformMatrix2fvEXT(0, 0, 0, 0, nil)
        glProgramUniformMatrix2x3fvEXT(0, 0, 0, 0, nil)
        glProgramUniformMatrix2x4fvEXT(0, 0, 0, 0, nil)
        glProgramUniformMatrix3fvEXT(0, 0, 0, 0, nil)
        glProgramUniformMatrix3x2fvEXT(0, 0, 0, 0, nil)
        glProgramUniformMatrix3x4fvEXT(0, 0, 0, 0, nil)
        glProgramUniformMatrix4fvEXT(0, 0, 0, 0, nil)
        glProgramUniformMatrix4x2fvEXT(0, 0, 0, 0, nil)
        glProgramUniformMatrix4x3fvEXT(0, 0, 0, 0, nil)
        glResolveMultisampleFramebufferAPPLE()
        glResumeTransformFeedback()
        glTransformFeedbackVaryings(0, 0, nil, 0)
        glWeightPointerOES(0, 0, 0, nil)
        _ = glGetError()
    }
}

func testGLESFunctionsQuery() {
    ogWithContext {
        _ = glGetError()
        glBeginQuery(0, 0)
        glBeginQueryEXT(0, 0)
        glEndQuery(0)
        glEndQueryEXT(0)
        _ = glGetError()
    }
}

func testGLESFunctionsRaster() {
    ogWithContext {
        _ = glGetError()
        glAlphaFunc(0, 0)
        glAlphaFuncx(0, 0)
        glBlendColor(0, 0, 0, 0)
        glBlendEquation(0)
        glBlendEquationOES(0)
        glBlendEquationSeparate(0, 0)
        glBlendEquationSeparateOES(0, 0)
        glBlendFunc(0, 0)
        glBlendFuncSeparate(0, 0, 0, 0)
        glBlendFuncSeparateOES(0, 0, 0, 0)
        glColorMask(0, 0, 0, 0)
        glCullFace(0)
        glDepthFunc(0)
        glDepthMask(0)
        glDepthRangef(0, 0)
        glDepthRangex(0, 0)
        glDisable(0)
        glDisableClientState(0)
        glDisableVertexAttribArray(0)
        glEnable(0)
        glEnableClientState(0)
        glEnableVertexAttribArray(0)
        glFrontFace(0)
        glHint(0, 0)
        glLineWidth(0)
        glLineWidthx(0)
        glPolygonOffset(0, 0)
        glPolygonOffsetx(0, 0)
        glSampleCoverage(0, 0)
        glSampleCoveragex(0, 0)
        glSamplerParameterf(0, 0, 0)
        glSamplerParameterfv(0, 0, nil)
        glSamplerParameteri(0, 0, 0)
        glSamplerParameteriv(0, 0, nil)
        glScissor(0, 0, 0, 0)
        glStencilFunc(0, 0, 0)
        glStencilFuncSeparate(0, 0, 0, 0)
        glStencilMask(0)
        glStencilMaskSeparate(0, 0)
        glStencilOp(0, 0, 0)
        glStencilOpSeparate(0, 0, 0, 0)
        glViewport(0, 0, 0, 0)
        _ = glGetError()
    }
}

func testGLESFunctionsShader() {
    ogWithContext {
        _ = glGetError()
        glAttachShader(0, 0)
        glCompileShader(0)
        _ = glCreateProgram()
        _ = glCreateShader(0)
        _ = glCreateShaderProgramvEXT(0, 0, nil)
        glDetachShader(0, 0)
        glLinkProgram(0)
        glReleaseShaderCompiler()
        glShaderBinary(0, nil, 0, nil, 0)
        glShaderSource(0, 0, nil, nil)
        glUniform1f(0, 0)
        glUniform1fv(0, 0, nil)
        glUniform1i(0, 0)
        glUniform1iv(0, 0, nil)
        glUniform1ui(0, 0)
        glUniform1uiv(0, 0, nil)
        glUniform2f(0, 0, 0)
        glUniform2fv(0, 0, nil)
        glUniform2i(0, 0, 0)
        glUniform2iv(0, 0, nil)
        glUniform2ui(0, 0, 0)
        glUniform2uiv(0, 0, nil)
        glUniform3f(0, 0, 0, 0)
        glUniform3fv(0, 0, nil)
        glUniform3i(0, 0, 0, 0)
        glUniform3iv(0, 0, nil)
        glUniform3ui(0, 0, 0, 0)
        glUniform3uiv(0, 0, nil)
        glUniform4f(0, 0, 0, 0, 0)
        glUniform4fv(0, 0, nil)
        glUniform4i(0, 0, 0, 0, 0)
        glUniform4iv(0, 0, nil)
        glUniform4ui(0, 0, 0, 0, 0)
        glUniform4uiv(0, 0, nil)
        glUniformBlockBinding(0, 0, 0)
        glUniformMatrix2fv(0, 0, 0, nil)
        glUniformMatrix2x3fv(0, 0, 0, nil)
        glUniformMatrix2x4fv(0, 0, 0, nil)
        glUniformMatrix3fv(0, 0, 0, nil)
        glUniformMatrix3x2fv(0, 0, 0, nil)
        glUniformMatrix3x4fv(0, 0, 0, nil)
        glUniformMatrix4fv(0, 0, 0, nil)
        glUniformMatrix4x2fv(0, 0, 0, nil)
        glUniformMatrix4x3fv(0, 0, 0, nil)
        glUseProgram(0)
        glUseProgramStagesEXT(0, 0, 0)
        glValidateProgram(0)
        glValidateProgramPipelineEXT(0)
        _ = glGetError()
    }
}

func testGLESFunctionsSync() {
    ogWithContext {
        _ = glGetError()
        _ = glClientWaitSync(nil, 0, 0)
        _ = glClientWaitSyncAPPLE(nil, 0, 0)
        _ = glFenceSync(0, 0)
        _ = glFenceSyncAPPLE(0, 0)
        glWaitSync(nil, 0, 0)
        glWaitSyncAPPLE(nil, 0, 0)
        _ = glGetError()
    }
}

func testGLESFunctionsTexture() {
    ogWithContext {
        _ = glGetError()
        glActiveTexture(0)
        glClientActiveTexture(0)
        glCompressedTexImage2D(0, 0, 0, 0, 0, 0, 0, nil)
        glCompressedTexImage3D(0, 0, 0, 0, 0, 0, 0, 0, nil)
        glCompressedTexSubImage2D(0, 0, 0, 0, 0, 0, 0, 0, nil)
        glCompressedTexSubImage3D(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, nil)
        glCopyTexImage2D(0, 0, 0, 0, 0, 0, 0, 0)
        glCopyTexSubImage2D(0, 0, 0, 0, 0, 0, 0, 0)
        glCopyTexSubImage3D(0, 0, 0, 0, 0, 0, 0, 0, 0)
        glCopyTextureLevelsAPPLE(0, 0, 0, 0)
        glPixelStorei(0, 0)
        glTexCoordPointer(0, 0, 0, nil)
        glTexEnvf(0, 0, 0)
        glTexEnvfv(0, 0, nil)
        glTexEnvi(0, 0, 0)
        glTexEnviv(0, 0, nil)
        glTexEnvx(0, 0, 0)
        glTexEnvxv(0, 0, nil)
        glTexImage2D(0, 0, 0, 0, 0, 0, 0, 0, nil)
        glTexImage3D(0, 0, 0, 0, 0, 0, 0, 0, 0, nil)
        glTexParameterf(0, 0, 0)
        glTexParameterfv(0, 0, nil)
        glTexParameteri(0, 0, 0)
        glTexParameteriv(0, 0, nil)
        glTexParameterx(0, 0, 0)
        glTexParameterxv(0, 0, nil)
        glTexStorage2D(0, 0, 0, 0, 0)
        glTexStorage2DEXT(0, 0, 0, 0, 0)
        glTexStorage3D(0, 0, 0, 0, 0, 0)
        glTexSubImage2D(0, 0, 0, 0, 0, 0, 0, 0, nil)
        glTexSubImage3D(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, nil)
        _ = glGetError()
    }
}

