// Glean Swift surface Focus uses, as data (no network, no Rust FFI).
//
// glean-swift 58.0.0 (724814f167bf42e33fafa856f7d19fc752beca2c) is a binary
// xcframework (`Package.swift` `.binaryTarget` + Glean.xcframework.zip).
// mozilla/glean v58.0.0 Swift sources (`glean-core/ios/Glean/Glean.swift`)
// call into that FFI (`gleanInitialize`, HttpPingUploader). Neither row
// compiles on Linux corelibs or the guest. This module carries the exact
// names Blockzilla references; record/set/add store in-process so tests
// can read them back. Not the previous Settings-only harness stub.
//
// MEASURED mozilla-mobile/focus-ios a2832521 Blockzilla (sources never
// patched). GleanMetrics is generated by glean_parser at Xcode build from
// metrics.yaml and is NOT in the checkout, so the nested types live here.

import Foundation

public struct Configuration {
    public var channel: String?
    public var dataPath: String?
    public var maxEvents: Int?
    public var logLevel: String?
    public var enableEventTimestamps: Bool
    public var experimentationId: String?

    public init(
        channel: String? = nil,
        dataPath: String? = nil,
        maxEvents: Int? = nil,
        logLevel: String? = nil,
        enableEventTimestamps: Bool = true,
        experimentationId: String? = nil
    ) {
        self.channel = channel
        self.dataPath = dataPath
        self.maxEvents = maxEvents
        self.logLevel = logLevel
        self.enableEventTimestamps = enableEventTimestamps
        self.experimentationId = experimentationId
    }
}

public struct BuildInfo: Sendable {
    public var buildDate: DateComponents
    public init(buildDate: DateComponents) {
        self.buildDate = buildDate
    }
}

public final class Glean: @unchecked Sendable {
    public static let shared = Glean()
    public private(set) var uploadEnabled = false
    public private(set) var initialized = false
    public private(set) var configuration: Configuration?
    public private(set) var lastCustomURL: URL?

    private init() {}

    public func initialize(
        uploadEnabled: Bool,
        configuration: Configuration = Configuration(),
        buildInfo: BuildInfo
    ) {
        _ = buildInfo
        self.uploadEnabled = uploadEnabled
        self.configuration = configuration
        self.initialized = true
    }

    public func setUploadEnabled(_ enabled: Bool) {
        uploadEnabled = enabled
    }

    public func handleCustomUrl(url: URL) {
        lastCustomURL = url
    }
}

public final class CounterMetricType: @unchecked Sendable {
    private let lock = NSLock()
    private var value: Int32 = 0
    public init() {}
    public func add(_ amount: Int32 = 1) {
        lock.lock()
        value += amount
        lock.unlock()
    }
    public func testGetValue() -> Int32 {
        lock.lock()
        defer { lock.unlock() }
        return value
    }
}

public final class StringMetricType: @unchecked Sendable {
    private let lock = NSLock()
    private var value: String?
    public init() {}
    public func set(_ value: String) {
        lock.lock()
        self.value = value
        lock.unlock()
    }
    public func testGetValue() -> String? {
        lock.lock()
        defer { lock.unlock() }
        return value
    }
}

public final class BooleanMetricType: @unchecked Sendable {
    private let lock = NSLock()
    private var value: Bool?
    public init() {}
    public func set(_ value: Bool) {
        lock.lock()
        self.value = value
        lock.unlock()
    }
    public func testGetValue() -> Bool? {
        lock.lock()
        defer { lock.unlock() }
        return value
    }
}

public final class QuantityMetricType: @unchecked Sendable {
    private let lock = NSLock()
    private var value: Int64?
    public init() {}
    public func set(_ value: Int64) {
        lock.lock()
        self.value = value
        lock.unlock()
    }
    public func testGetValue() -> Int64? {
        lock.lock()
        defer { lock.unlock() }
        return value
    }
}

public final class EventMetricType<Extra>: @unchecked Sendable {
    private let lock = NSLock()
    private var extras: [Extra] = []
    public init() {}
    public func record(_ extra: Extra) {
        lock.lock()
        extras.append(extra)
        lock.unlock()
    }
    public func testGetCount() -> Int {
        lock.lock()
        defer { lock.unlock() }
        return extras.count
    }
}

extension EventMetricType where Extra == Void {
    public func record() { record(()) }
}

public final class LabeledMetricType<T>: @unchecked Sendable {
    private let lock = NSLock()
    private var labels: [String: T] = [:]
    private let make: () -> T
    public init(_ make: @escaping () -> T) {
        self.make = make
    }
    public subscript(label: String) -> T {
        lock.lock()
        defer { lock.unlock() }
        if let existing = labels[label] { return existing }
        let created = make()
        labels[label] = created
        return created
    }
}

// MARK: - GleanMetrics (Focus a2832521 call sites)

public enum GleanMetrics {
    public enum GleanBuild {
        public static let info = BuildInfo(
            buildDate: DateComponents(
                calendar: Calendar(identifier: .gregorian),
                timeZone: TimeZone(secondsFromGMT: 0),
                year: 2024, month: 3, day: 2
            )
        )
    }

    public enum App {
        public static let openedAsDefaultBrowser = CounterMetricType()
        public static let keyboardType = StringMetricType()
    }

    public enum Browser {
        public static let totalUriCount = CounterMetricType()
        public static let pdfViewerUsed = CounterMetricType()
    }

    public enum BrowserSearch {
        public static let inContent = LabeledMetricType { CounterMetricType() }
        public static let withAds = LabeledMetricType { CounterMetricType() }
        public static let adClicks = LabeledMetricType { CounterMetricType() }
        public static let searchCount = LabeledMetricType { CounterMetricType() }
    }

    public enum BrowserMenu {
        public struct BrowserMenuActionExtra {
            public var item: String
            public init(item: String) { self.item = item }
        }
        public static let browserMenuAction = EventMetricType<BrowserMenuActionExtra>()
    }

    public enum DefaultBrowserOnboarding {
        public static let goToSettingsPressed = CounterMetricType()
        public static let skipButtonTapped = EventMetricType<Void>()
    }

    public enum MozillaProducts {
        public static let hasFirefoxInstalled = BooleanMetricType()
    }

    public enum Onboarding {
        public struct CardViewExtra {
            public var cardType: String
            public init(cardType: String) { self.cardType = cardType }
        }
        public struct CloseTapExtra {
            public var cardType: String
            public init(cardType: String) { self.cardType = cardType }
        }
        public struct PrimaryButtonTapExtra {
            public var cardType: String
            public init(cardType: String) { self.cardType = cardType }
        }
        public static let cardView = EventMetricType<CardViewExtra>()
        public static let closeTap = EventMetricType<CloseTapExtra>()
        public static let primaryButtonTap = EventMetricType<PrimaryButtonTapExtra>()
    }

    public enum Preferences {
        public static let userTheme = StringMetricType()
    }

    public enum Search {
        public static let defaultEngine = StringMetricType()
    }

    public enum SearchSuggestions {
        public struct SearchTappedExtra {
            public var engineName: String
            public init(engineName: String) { self.engineName = engineName }
        }
        public struct SuggestionTappedExtra {
            public var engineName: String
            public init(engineName: String) { self.engineName = engineName }
        }
        public static let autocompleteArrowTapped = EventMetricType<Void>()
        public static let searchTapped = EventMetricType<SearchTappedExtra>()
        public static let suggestionTapped = EventMetricType<SuggestionTappedExtra>()
    }

    public enum SettingsScreen {
        public static let setAsDefaultBrowserPressed = CounterMetricType()
        public static let autocompleteDomainAdded = CounterMetricType()
    }

    public enum Shortcuts {
        public static let shortcutAddedCounter = CounterMetricType()
        public static let shortcutOpenedCounter = CounterMetricType()
        public static let shortcutRemovedCounter = LabeledMetricType { CounterMetricType() }
        public static let shortcutsOnHomeNumber = QuantityMetricType()
    }

    public enum ShowSearchSuggestions {
        public struct ChangedFromSettingsExtra {
            public var isEnabled: Bool
            public init(isEnabled: Bool) { self.isEnabled = isEnabled }
        }
        public static let changedFromSettings = EventMetricType<ChangedFromSettingsExtra>()
        public static let disabledFromPanel = EventMetricType<Void>()
        public static let enabledFromPanel = EventMetricType<Void>()
    }

    public enum Siri {
        public static let eraseInBackground = EventMetricType<Void>()
        public static let eraseAndOpen = EventMetricType<Void>()
        public static let openFavoriteSite = EventMetricType<Void>()
    }

    public enum TrackingProtection {
        public struct TrackingProtectionChangedExtra {
            public var isEnabled: Bool
            public init(isEnabled: Bool) { self.isEnabled = isEnabled }
        }
        public struct TrackerSettingChangedExtra {
            public var isEnabled: Bool
            public var sourceOfChange: String
            public var trackerChanged: String
            public init(isEnabled: Bool, sourceOfChange: String, trackerChanged: String) {
                self.isEnabled = isEnabled
                self.sourceOfChange = sourceOfChange
                self.trackerChanged = trackerChanged
            }
        }
        public static let trackingProtectionChanged = EventMetricType<TrackingProtectionChangedExtra>()
        public static let trackerSettingChanged = EventMetricType<TrackerSettingChangedExtra>()
        public static let hasEverChangedEtp = BooleanMetricType()
        public static let hasAdvertisingBlocked = BooleanMetricType()
        public static let hasAnalyticsBlocked = BooleanMetricType()
        public static let hasContentBlocked = BooleanMetricType()
        public static let hasSocialBlocked = BooleanMetricType()
        public static let toolbarShieldClicked = CounterMetricType()
    }

    public enum UrlInteraction {
        public static let pasteAndGo = EventMetricType<Void>()
        public static let dragStarted = EventMetricType<Void>()
        public static let dropEnded = EventMetricType<Void>()
    }

    public enum Webview {
        public static let fail = EventMetricType<Void>()
        public static let failProvisional = EventMetricType<Void>()
    }
}
