#!/bin/bash
# gen_darwin_modulemap.sh <sysroot> -- declare a Clang `Darwin` module over the
# headers a given sysroot ACTUALLY stages.
#
# GENERATED, NOT COPIED, AND GENERATED AGAINST THE TARGET. Apple's own
# Darwin.modulemap (machorun/build/sdk/MacOSX.sdk/usr/include/Darwin.modulemap,
# 4551 bytes, 49 submodules) references 51 headers of which machorun's curated
# sdk/ stages 16 -- copying it wholesale would name 35 absent headers and create
# 35 new latent gaps, which is the class of bug this exists to fix.
#
# AND IT MUST BE GENERATED AGAINST THE SYSROOT IT WILL BE INSTALLED INTO. A
# first attempt generated from scratch/sysroot and installed into
# scratch/sysroot_full, which build_full.sh deliberately strips of quartz
# headers -- so the modulemap named quartz/anim_group.h and the build failed on
# a header the modulemap itself had invented. Same latent gap, committed one
# step after writing the warning about it. Hence a script taking the target as
# an argument rather than a checked-in file.
set -euo pipefail
S="${1:?usage: gen_darwin_modulemap.sh <sysroot>}/usr/include"
[ -d "$S" ] || { echo "no $S" >&2; exit 1; }
{
    echo "// GENERATED by full/sdk-gaps/gen_darwin_modulemap.sh -- do not edit."
    echo "// Covers only headers present in this sysroot."
    echo "module Darwin [system] [extern_c] {"
    ( cd "$S" && find . -name '*.h' ! -path './objc/*' | sed 's|^\./||' | sort \
      | while IFS= read -r h; do printf '  header "%s"\n' "$h"; done )
    echo "  export *"
    echo "}"
} > "$S/Darwin.modulemap"
grep -q 'extern module Darwin' "$S/module.modulemap" 2>/dev/null \
  || printf '\nextern module Darwin "Darwin.modulemap"\n' >> "$S/module.modulemap"
echo "Darwin.modulemap: $(grep -c '^  header' "$S/Darwin.modulemap") headers"
