#!/bin/bash
# Generate darwin/src/sysconf_table.h by MEASURING both platforms.
#
# The sibling of scripts/gen_errno_table.sh, and needed for the same reason
# with a starker number: of the 128 _SC_* names that exist on both systems,
# ALL 128 have different values. Not one agrees. Darwin's _SC_PAGESIZE is 29
# and Linux's is 30; Darwin's _SC_NPROCESSORS_ONLN is 58 and Linux's is 84.
#
# sysconf was a raw forward, so every query a guest made was answered from the
# wrong row of glibc's table. MEASURED before the fix:
#
#     sysconf(_SC_PAGESIZE)         -> 200809   (macOS: 16384)
#     sysconf(_SC_NPROCESSORS_ONLN) -> -1       (macOS: 16)
#     sysconf(_SC_OPEN_MAX)         -> 16       (macOS: 1048576)
#
# The third is the dangerous one. 200809 is obvious nonsense and -1 is a
# failure, but 16 is a perfectly plausible open-file limit, and a guest that
# sized a table with it would simply be wrong.
#
# The mapping is by NAME, not by hand: each side is asked for the value it
# gives a name, and the pair is recorded. A hand-written table across 128
# entries would be a guess with a typo in it.
#
# Needs macOS (for the Darwin values) and Docker with the test-bed image (for
# the Linux ones). Run from a macOS host:
#
#   scripts/gen_sysconf_table.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/darwin/src/sysconf_table.h"
IMAGE="${MACHORUN_IMAGE:-machorun-testbed:24.04}"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

[ "$(uname -s)" = "Darwin" ] || { echo "gen_sysconf_table.sh: needs macOS for the Darwin half" >&2; exit 64; }

# Darwin spells them as plain #defines, so the preprocessor lists them directly.
xcrun clang -E -dM -include unistd.h - </dev/null \
    | awk '/^#define _SC_[A-Z0-9_]+ [0-9]+$/{print $2, $3}' | sort > "$WORK/darwin"

# glibc spells them as ENUM MEMBERS with a `#define _SC_X _SC_X` alias, so the
# preprocessor cannot print their values -- asking for #define lines returns
# nothing at all, which looks exactly like "glibc has none of these". Compile
# a program that prints each one instead, guarded by #ifdef so a name glibc
# lacks is skipped rather than failing the build.
{
    echo '#include <unistd.h>'
    echo '#include <stdio.h>'
    echo 'int main(void){'
    awk '{print "#ifdef " $1 "\n  printf(\"" $1 " %d\\n\", (int)" $1 ");\n#endif"}' "$WORK/darwin"
    echo '  return 0; }'
} > "$WORK/probe.c"

docker run --rm --platform linux/arm64 -v "$WORK:/w" "$IMAGE" \
    bash -c 'cc -o /w/probe /w/probe.c && /w/probe' | sort > "$WORK/linux"

join "$WORK/darwin" "$WORK/linux" > "$WORK/pairs"
n_common=$(wc -l < "$WORK/pairs" | tr -d ' ')
n_diff=$(awk '$2 != $3' "$WORK/pairs" | wc -l | tr -d ' ')
max_d=$(awk '{if ($2+0 > m) m = $2+0} END{print m+1}' "$WORK/pairs")

{
    cat <<HDR
/* sysconf_table.h -- GENERATED by scripts/gen_sysconf_table.sh. Do not edit.
 *
 * Measured $(date +%Y-%m-%d) on $(sw_vers -productName) $(sw_vers -productVersion) and the test-bed image.
 * $n_common _SC_* names exist on both systems and $n_diff of them have
 * DIFFERENT values -- which is all of them. sysconf therefore cannot be
 * forwarded; every query would read the wrong row of glibc's table.
 *
 * -1 means "Darwin has no _SC_ with that number". sysconf's documented answer
 * for an unrecognised name is -1 with errno EINVAL, so refusing is a real
 * answer here rather than a failure to produce one -- which matters, because
 * the alternative is returning a number that looks like an answer.
 */
#ifndef MACHORUN_SYSCONF_TABLE_H
#define MACHORUN_SYSCONF_TABLE_H

/* Darwin _SC_ value -> Linux _SC_ value. */
#define MR_SYSCONF_D2L_N $max_d
static const short mr_sysconf_d2l[$max_d] = {
HDR
    # DENSE, with an explicit -1 in every unmapped slot. A sparse table with
    # designated initialisers would leave the gaps as 0 -- and glibc's
    # _SC_ARG_MAX IS 0, so "absent" and "the first entry" would be the same
    # value. The generator's own check below caught that before it shipped.
    awk -v n="$max_d" '
        { d[$2] = $3; name[$2] = $1 }
        END {
            for (i = 0; i < n; i++)
                if (i in d) printf "    [%d] = %d,  /* %s */\n", i, d[i], name[i]
                else        printf "    [%d] = -1,\n", i
        }' "$WORK/pairs"
    cat <<'FTR'
};

#endif /* MACHORUN_SYSCONF_TABLE_H */
FTR
} > "$OUT"

# Sanity: every slot in the emitted array must be present, since the lookup
# indexes it directly and reads -1 as "no such name".
emitted=$(grep -c '^    \[' "$OUT")
if [ "$emitted" != "$max_d" ]; then
    echo "gen_sysconf_table.sh: emitted $emitted rows for a table of $max_d" >&2
    exit 1
fi

printf '   %s -> %s names, %s differing (all of them), table size %s\n' \
    "$OUT" "$n_common" "$n_diff" "$max_d"
