#!/bin/bash
# Generate darwin/src/errno_table.h by MEASURING both platforms.
#
# 54 of the 87 errno names that exist on both systems have different values
# (EAGAIN is 35 on Darwin and 11 on Linux; EDEADLK is 11 on Darwin and 35 on
# Linux -- they are each other's). Those constants are compiled into the guest,
# so libSystem has to translate rather than forward. A hand-written table would
# be a guess; this one is a measurement, and re-running the script re-takes it.
#
# Needs: macOS (for the Darwin values) and Docker with the test-bed image (for
# the Linux ones). Run it from a macOS host:
#
#   scripts/gen_errno_table.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/darwin/src/errno_table.h"
IMAGE="${MACHORUN_IMAGE:-machorun-testbed:24.04}"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

[ "$(uname -s)" = "Darwin" ] || { echo "gen_errno_table.sh: needs macOS for the Darwin half" >&2; exit 64; }

# The names each platform defines as a plain integer literal, intersected.
xcrun clang -E -dM -include errno.h - </dev/null \
    | awk '/^#define E[A-Z0-9_]+ [0-9]+$/{print $2}' | sort -u > "$WORK/n_darwin"
docker run --rm --platform linux/arm64 "$IMAGE" bash -c \
    'clang -E -dM -D_GNU_SOURCE -include errno.h - </dev/null | awk "/^#define E[A-Z0-9_]+ [0-9]+\$/{print \$2}" | sort -u' \
    > "$WORK/n_linux"
comm -12 "$WORK/n_darwin" "$WORK/n_linux" > "$WORK/n_common"

python3 - "$WORK/n_common" "$WORK/probe.c" <<'PY'
import sys
names = [l.strip() for l in open(sys.argv[1]) if l.strip()]
body = "".join('  printf("%s %%d\\n", %s);\n' % (n, n) for n in names)
open(sys.argv[2], "w").write(
    "#include <errno.h>\n#include <stdio.h>\nint main(void){\n" + body + "  return 0;\n}\n")
PY

xcrun clang -o "$WORK/p_darwin" "$WORK/probe.c"
"$WORK/p_darwin" | sort > "$WORK/v_darwin"
cp "$WORK/probe.c" "$WORK/probe_in.c"
docker run --rm --platform linux/arm64 -v "$WORK:/w" -w /w "$IMAGE" \
    bash -c 'clang -D_GNU_SOURCE -o p_linux probe_in.c && ./p_linux' | sort > "$WORK/v_linux"

# Darwin's own strerror text, taken from macOS rather than invented. Our
# strerror() must be byte-identical to Apple's for the numbers a guest holds:
# translating the number and asking glibc would be a second guess, and glibc
# does not agree with Darwin on every string.
cat > "$WORK/se.c" <<'EOF'
#include <stdio.h>
#include <string.h>
#include <errno.h>
int main(void){
    for (int i = 0; i <= ELAST; i++) printf("%d\t%s\n", i, strerror(i));
    return 0;
}
EOF
xcrun clang -o "$WORK/p_se" "$WORK/se.c"
"$WORK/p_se" > "$WORK/v_strerror"

python3 - "$WORK/v_darwin" "$WORK/v_linux" "$OUT" "$WORK/v_strerror" <<'PY'
import sys, datetime
d = dict(l.split() for l in open(sys.argv[1]))
l = dict(x.split() for x in open(sys.argv[2]))
pairs = sorted((int(l[k]), int(d[k]), k) for k in d if k in l)

# Both directions, indexed by value. A name that exists on only one side is
# left out entirely: mapping it to "the same number" would silently alias some
# unrelated errno on the other platform.
lin2dar, dar2lin = {}, {}
for lv, dv, name in pairs:
    lin2dar.setdefault(lv, (dv, name))
    dar2lin.setdefault(dv, (lv, name))

def table(m, name, count):
    hi = max(m) + 1
    out = ["#define %s %d" % (count, hi), "static const short %s[%d] = {" % (name, hi)]
    for i in range(hi):
        if i in m:
            out.append("    [%d] = %d,%s" % (i, m[i][0], "  /* %s */" % m[i][1]))
        else:
            out.append("    [%d] = -1," % i)
    out.append("};")
    return "\n".join(out)

strs = []
for line in open(sys.argv[4]):
    n, _, text = line.rstrip("\n").partition("\t")
    strs.append((int(n), text))
strtab = "#define MR_STRERROR_N %d\nstatic const char *const mr_strerror_darwin[%d] = {\n%s};" % (
    len(strs), len(strs),
    "".join('    [%d] = "%s",\n' % (n, t.replace('\\', '\\\\').replace('"', '\\"')) for n, t in strs))

hdr = '''/* errno_table.h -- GENERATED by scripts/gen_errno_table.sh. Do not edit.
 *
 * Measured %s on macOS %s and Ubuntu 24.04/aarch64.
 * %d errno names exist on both systems; %d of them have DIFFERENT values.
 * -1 means "this platform has no errno with that number", which is a real
 * answer and not a failure: the translation refuses rather than aliasing.
 */
#ifndef MACHORUN_ERRNO_TABLE_H
#define MACHORUN_ERRNO_TABLE_H

/* Linux errno value -> Darwin errno value. */
%s

/* Darwin errno value -> Linux errno value. */
%s

/* Darwin's own strerror() text, index = Darwin errno. Out of range, Darwin
   prints "Unknown error: %%d"; strerror(0) is "Undefined error: 0". */
%s

#endif
''' % (datetime.date.today().isoformat(),
       __import__("platform").mac_ver()[0],
       len(pairs), sum(1 for lv, dv, _ in pairs if lv != dv),
       table(lin2dar, "mr_errno_l2d", "MR_ERRNO_L2D_N"),
       table(dar2lin, "mr_errno_d2l", "MR_ERRNO_D2L_N"),
       strtab)
open(sys.argv[3], "w").write(hdr)
print("wrote %s: %d names, %d differ" %
      (sys.argv[3], len(pairs), sum(1 for lv, dv, _ in pairs if lv != dv)))
PY
