#!/usr/bin/env python3
"""gen_guest_golden.py -- embed the Darwin golden into a Swift source file.

    scripts/gen_guest_golden.py <golden.txt> <out.swift>

WHY EMBED RATHER THAN READ AT RUNTIME. The guest runs under machorun against a
guest root; a runtime file read would add a path, a staging step and a failure
mode that has nothing to do with UserDefaults, and "the golden was not found"
would present as an empty scoreboard -- which scores 100%. Embedding makes the
golden part of the binary, so a guest that runs at all has it.

WHAT IT REFUSES ON. The point of this file is that it does NOT retype anything:
it copies bytes and records their sha256. It refuses if the golden is empty, if
any line is malformed, or if the row counts do not match what the file's own
header claims -- because a truncated golden is the failure that scores well.
"""
import hashlib
import sys

if len(sys.argv) != 3:
    sys.exit(__doc__)
src, dst = sys.argv[1], sys.argv[2]

raw = open(src, "rb").read()
text = raw.decode("utf-8")
sha = hashlib.sha256(raw).hexdigest()

# Validate before embedding. Counting here rather than trusting the header is
# the point: the header is a claim, the lines are the fact.
cols = {}
for n, line in enumerate(text.split("\n"), 1):
    if not line or line.startswith("#"):
        continue
    parts = line.split("\t")
    if len(parts) != 3:
        sys.exit("REFUSING: %s line %d has %d fields, expected 3: %r"
                 % (src, n, len(parts), line[:100]))
    if parts[0] not in ("D", "C"):
        sys.exit("REFUSING: %s line %d has unknown column %r" % (src, n, parts[0]))
    cols[parts[0]] = cols.get(parts[0], 0) + 1

if not cols:
    sys.exit("REFUSING: %s contains no data rows at all" % src)
for want in ("D", "C"):
    if cols.get(want, 0) == 0:
        sys.exit("REFUSING: %s has no %s rows; the guest needs both a "
                 "correct-answers column and a must-fail column" % (src, want))

if '"""#' in text:
    sys.exit("REFUSING: the golden contains the raw-string terminator")

with open(dst, "w", encoding="utf-8") as f:
    f.write("// GENERATED by scripts/gen_guest_golden.py -- DO NOT EDIT.\n")
    f.write("// Source: %s\n" % src)
    f.write("// sha256: %s\n" % sha)
    f.write("// Rows: D=%d (real Foundation) C=%d (corelibs' rules)\n"
            % (cols["D"], cols["C"]))
    f.write("//\n")
    f.write("// This is a byte copy. Nothing here was retyped, and the guest\n")
    f.write("// runner parses it with the same unescaping the emitter used.\n")
    f.write("\n")
    f.write("let GOLDEN_SHA256 = \"%s\"\n" % sha)
    f.write("let GOLDEN_ROWS_D = %d\n" % cols["D"])
    f.write("let GOLDEN_ROWS_C = %d\n" % cols["C"])
    f.write("let GOLDEN_TEXT = #\"\"\"\n")
    f.write(text)
    if not text.endswith("\n"):
        f.write("\n")
    f.write("\"\"\"#\n")

print("wrote %s" % dst)
print("  sha256 %s" % sha)
print("  D %d rows (real Foundation) · C %d rows (corelibs)" % (cols["D"], cols["C"]))
