#!/bin/bash
# Harvest the ObjC classes our Foundation ACTUALLY EMITS, for the registration
# guard to check against.
#
#   scripts/harvest_ns_classes.sh <objdir> [outfile]
#
# Writes docs/cf-census/ns-classes.txt, which scripts/check_registration.py
# reads to decide whether a BRIDGED type's class exists.
#
# WHY FROM OBJECT FILES AND NOT FROM `grep @implementation`:
#
# A class counts only if the compiler emitted it. Grepping source for
# `@implementation __NSCFString` answers "did someone write that text", which is
# level 2 of the four levels this project has now been bitten by:
#
#   1. what does the code call          -- missed 1 of 6 runloop sites
#   2. which FILE mentions it           -- wrong about 1 of 9 Mach declarations
#   3. what survives preprocessing      -- reported a symbol reachable in all 86
#                                          CF files, because it was matching a
#                                          declaration we ourselves inserted
#   4. what the object file contains    -- the only one that cannot be fooled
#
# `_OBJC_CLASS_$_<name>` as a DEFINED symbol is level 4. A class inside an
# #if that is false, or in a file nobody compiles, produces no such symbol and
# correctly does not count.
#
# The guard treating a missing file as "zero classes implemented" is deliberate
# and is the safe direction: it refuses, rather than passing because a list was
# absent.
set -euo pipefail

OBJDIR=${1:?usage: harvest_ns_classes.sh <objdir> [outfile]}
OUT=${2:-$(dirname "$0")/../docs/cf-census/ns-classes.txt}
NM=${NM:-llvm-nm-18}

[ -d "$OBJDIR" ] || { echo "harvest_ns_classes: no such directory: $OBJDIR" >&2; exit 2; }

shopt -s nullglob
objs=("$OBJDIR"/*.o)
if [ ${#objs[@]} -eq 0 ]; then
    echo "harvest_ns_classes: no .o files in $OBJDIR -- refusing to write an" >&2
    echo "  empty class list, which would read as 'nothing implemented' when it" >&2
    echo "  actually means 'nothing was built'." >&2
    exit 2
fi

tmp=$(mktemp)
for o in "${objs[@]}"; do
    # --defined-only: a class we merely REFERENCE (a superclass from another
    # library, say) is undefined here and must not be counted as ours.
    "$NM" --defined-only "$o" 2>/dev/null \
        | sed -n 's/.* _OBJC_CLASS_\$_\(.*\)$/\1/p'
done | sort -u > "$tmp"

n=$(wc -l < "$tmp" | tr -d ' ')
if [ "$n" -eq 0 ]; then
    echo "harvest_ns_classes: ${#objs[@]} objects contained ZERO defined ObjC" >&2
    echo "  classes. That is almost certainly a build or nm problem rather than" >&2
    echo "  a true answer -- refusing to write it." >&2
    rm -f "$tmp"
    exit 2
fi

mkdir -p "$(dirname "$OUT")"
{
    echo "# ObjC classes our Foundation emits, harvested from OBJECT FILES."
    echo "# Generated by scripts/harvest_ns_classes.sh -- do not edit by hand."
    echo "# Source: $OBJDIR (${#objs[@]} objects)"
    echo "# A name here means the compiler emitted _OBJC_CLASS_\$_<name> as a"
    echo "# DEFINED symbol, not that someone wrote @implementation somewhere."
    cat "$tmp"
} > "$OUT"
rm -f "$tmp"

echo "harvest_ns_classes: $n classes from ${#objs[@]} objects -> $OUT"
sed 's/^/  /' <(grep -v '^#' "$OUT")
