#!/bin/bash
# stage_swift_runtime.sh -- macOS. Assemble scratch/mrroot: a machorun guest
# root that carries the Swift runtime, so a Mach-O Swift guest can RUN.
#
# The Swift runtime dylib the SPIKE said "does not exist as a file" DOES exist,
# as plain arm64 (not arm64e) Mach-O, inside the iOS Simulator runtime -- the
# simulator runs non-PAC arm64. We stage those, plus machorun's own darwin/
# dylibs and the two runtime shims that build_runtime_shims.sh produces:
#   libSystem.B.dylib  = syspatch (47 missing symbols) reexporting the real one
#   libc++.1.dylib     = cxxpatch (5 missing symbols)  reexporting the real one
#   Foundation/CoreFoundation stubs (8 error-bridging symbols libswiftCore imports)
#
# Run build_runtime_shims.sh (in Docker) FIRST -- it writes the shims into
# build/linux and this script copies them in.
set -euo pipefail
[ "$(uname -s)" = "Darwin" ] || { echo "macOS only (reads the CoreSimulator runtime)"; exit 1; }
ROOT=$(cd "$(dirname "$0")/.." && pwd)
MACHORUN=${MACHORUN:-$HOME/machorun}
MR="$ROOT/scratch/mrroot"
OUT="$ROOT/build/linux"

SIM=${SIM:-"/Library/Developer/CoreSimulator/Volumes/iOS_23B80/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 26.1.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift"}
[ -f "$SIM/libswiftCore.dylib" ] || { echo "no sim libswiftCore at: $SIM" >&2; exit 1; }
file "$SIM/libswiftCore.dylib" | grep -q arm64 || { echo "sim libswiftCore is not arm64" >&2; exit 1; }
[ -x "$MACHORUN/build/machorun" ] || { echo "build machorun first: $MACHORUN/build/machorun" >&2; exit 1; }

# ---- REFUSE, OR DISPLACE. NEVER rm -rf A ROOT SOMEONE ELSE BUILT (#75).
#
# What was here was `rm -rf "$MR"`, unconditionally. scratch/mrroot is a BUILD
# INPUT -- run_quartz.sh, run_slice.sh, build_pngprobe.sh, build_pngprobe_sysfirst.sh,
# build_slice2.sh, build_swiftcore_umbrella.sh and build_runtime_shims.sh all
# read it -- so that line destroyed a shared tree with no record of what it had
# been, and the next failure would look like a code bug rather than a missing
# root.
#
# The rule this follows is foundation-macho's build_foundation_placeholder.sh:
# refuse on an occupant you did not create, and when told to proceed, MOVE IT
# ASIDE rather than delete it. An owner is identified by the manifest this
# script writes at the end -- so "is this mine?" is answerable from the tree
# rather than assumed from the path.
if [ -e "$MR" ]; then
    if [ -f "$MR/.manifest" ] && grep -q '^# generated by scripts/stage_swift_runtime.sh' "$MR/.manifest"; then
        echo "== replacing a root this script produced ($MR)"
        rm -rf "$MR"
    elif [ "${REPLACE:-0}" = 1 ]; then
        aside="$ROOT/scratch/displaced/$(basename "$MR").$(date +%Y%m%dT%H%M%S)"
        mkdir -p "$(dirname "$aside")"
        mv "$MR" "$aside"
        echo "== DISPLACED an unrecognised root to $aside ($(find "$aside" -type f | wc -l | tr -d ' ') files kept)"
    else
        echo "REFUSING: $MR exists and carries no manifest from this script." >&2
        echo "  It has $(find "$MR" -type f 2>/dev/null | wc -l | tr -d ' ') files and is a BUILD INPUT for" >&2
        echo "  run_quartz.sh, run_slice.sh, build_pngprobe*.sh, build_slice2.sh," >&2
        echo "  build_swiftcore_umbrella.sh and build_runtime_shims.sh." >&2
        echo "  Deleting it silently is how a missing root becomes a code bug." >&2
        echo "  Re-run with REPLACE=1 to move it aside (it is kept, not deleted)." >&2
        exit 2
    fi
fi

mkdir -p "$MR/darwin/usr/lib/swift" \
         "$MR/darwin/System/Library/Frameworks/Foundation.framework" \
         "$MR/darwin/System/Library/Frameworks/CoreFoundation.framework"

# machorun's own userland + loader
cp "$MACHORUN"/darwin/usr/lib/*.dylib "$MR/darwin/usr/lib/"
cp "$MACHORUN/build/machorun" "$MR/machorun"

# the Swift runtime, from the iOS simulator (arm64, non-arm64e)
cp "$SIM/libswiftCore.dylib" "$SIM/libswiftObjectiveC.dylib" "$SIM/libswift_Concurrency.dylib" \
   "$MR/darwin/usr/lib/swift/"
chmod u+w "$MR/darwin/usr/lib/swift/"*.dylib

# the shims (built by build_runtime_shims.sh in Docker)
for f in libSystem.real.dylib libSystem.B.umbrella.dylib \
         libc++.real.dylib libc++.1.umbrella.dylib \
         Foundation.stub.dylib CoreFoundation.stub.dylib; do
    [ -f "$OUT/$f" ] || { echo "missing $OUT/$f -- run build_runtime_shims.sh first" >&2; exit 1; }
done
cp "$OUT/libSystem.real.dylib"        "$MR/darwin/usr/lib/libSystem.real.dylib"
cp "$OUT/libSystem.B.umbrella.dylib"  "$MR/darwin/usr/lib/libSystem.B.dylib"
cp "$OUT/libc++.real.dylib"           "$MR/darwin/usr/lib/libc++.real.dylib"
cp "$OUT/libc++.1.umbrella.dylib"     "$MR/darwin/usr/lib/libc++.1.dylib"
cp "$OUT/Foundation.stub.dylib"       "$MR/darwin/System/Library/Frameworks/Foundation.framework/Foundation"
cp "$OUT/CoreFoundation.stub.dylib"   "$MR/darwin/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation"

# ---- THE MANIFEST. Builder-owns-the-manifest, the same rule build_full.sh and
# stage_swift_overlays.sh follow -- and here it does double duty as the marker
# that identifies this root as ours, so the guard above can tell a root it
# produced from one it must not touch.
#
# Digests are of the SOURCE each file was copied from, never of the file now in
# the root: hashing an artefact and comparing it to itself is the vacuous green
# require_fresh_root.sh refuses outright.
{
    echo "# generated by scripts/stage_swift_runtime.sh -- do not hand-edit"
    echo "copy	machorun	build/machorun"
    for f in "$MACHORUN"/darwin/usr/lib/*.dylib; do
        b=$(basename "$f")
        case "$b" in libSystem.B.dylib|libc++.1.dylib) continue ;; esac
        printf 'copy	darwin/usr/lib/%s	darwin/usr/lib/%s
' "$b" "$b"
    done
    for b in libswiftCore libswiftObjectiveC libswift_Concurrency; do
        printf 'staged	darwin/usr/lib/swift/%s.dylib	%s	%s
' "$b" \
            "$(shasum -a 256 "$SIM/$b.dylib" | cut -d' ' -f1)" "$SIM/$b.dylib"
    done
    printf 'staged	darwin/usr/lib/libSystem.real.dylib	%s	%s
' \
        "$(shasum -a 256 "$OUT/libSystem.real.dylib" | cut -d' ' -f1)" "$OUT/libSystem.real.dylib"
    printf 'staged	darwin/usr/lib/libSystem.B.dylib	%s	%s
' \
        "$(shasum -a 256 "$OUT/libSystem.B.umbrella.dylib" | cut -d' ' -f1)" "$OUT/libSystem.B.umbrella.dylib"
    printf 'staged	darwin/usr/lib/libc++.real.dylib	%s	%s
' \
        "$(shasum -a 256 "$OUT/libc++.real.dylib" | cut -d' ' -f1)" "$OUT/libc++.real.dylib"
    printf 'staged	darwin/usr/lib/libc++.1.dylib	%s	%s
' \
        "$(shasum -a 256 "$OUT/libc++.1.umbrella.dylib" | cut -d' ' -f1)" "$OUT/libc++.1.umbrella.dylib"
    printf 'staged	darwin/System/Library/Frameworks/Foundation.framework/Foundation	%s	%s
' \
        "$(shasum -a 256 "$OUT/Foundation.stub.dylib" | cut -d' ' -f1)" "$OUT/Foundation.stub.dylib"
    printf 'staged	darwin/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation	%s	%s
' \
        "$(shasum -a 256 "$OUT/CoreFoundation.stub.dylib" | cut -d' ' -f1)" "$OUT/CoreFoundation.stub.dylib"
} > "$MR/.manifest"
echo "== manifest ($MR/.manifest): $(grep -c '	' "$MR/.manifest") rows"

echo "staged guest root: $MR/darwin"
find "$MR/darwin" -type f | sed "s#$MR/##" | sort
