import Foundation

// MARK: - AAT / SFNT integer ABI (SFNTTypes.h + SFNTLayoutTypes.h)
// Macintosh language/script IDs match OpenType name-table platform 1.
// Packed sizeof_* values are the C header enumerators, not Swift MemoryLayout.

public var kANKRCurrentVersion: Int { 0 }
public var kBSLNControlPointFormatNoMap: Int { 2 }
public var kBSLNControlPointFormatWithMap: Int { 3 }
public var kBSLNCurrentVersion: Int { 65536 }
public var kBSLNDistanceFormatNoMap: Int { 0 }
public var kBSLNDistanceFormatWithMap: Int { 1 }
public var kBSLNHangingBaseline: Int { 3 }
public var kBSLNIdeographicCenterBaseline: Int { 1 }
public var kBSLNIdeographicHighBaseline: Int { 5 }
public var kBSLNIdeographicLowBaseline: Int { 2 }
public var kBSLNLastBaseline: Int { 31 }
public var kBSLNMathBaseline: Int { 4 }
public var kBSLNNoBaseline: Int { 255 }
public var kBSLNNoBaselineOverride: Int { 255 }
public var kBSLNNumBaselineClasses: Int { 32 }
public var kBSLNRomanBaseline: Int { 0 }
public var kFontAlbanianLanguage: Int { 36 }
public var kFontAmharicLanguage: Int { 85 }
public var kFontAmharicScript: Int { 28 }
public var kFontArabicLanguage: Int { 12 }
public var kFontArabicScript: Int { 4 }
public var kFontArmenianLanguage: Int { 51 }
public var kFontArmenianScript: Int { 24 }
public var kFontAssameseLanguage: Int { 68 }
public var kFontAymaraLanguage: Int { 134 }
public var kFontAzerbaijanArLanguage: Int { 50 }
public var kFontAzerbaijaniLanguage: Int { 49 }
public var kFontBasqueLanguage: Int { 129 }
public var kFontBengaliLanguage: Int { 67 }
public var kFontBengaliScript: Int { 13 }
public var kFontBulgarianLanguage: Int { 44 }
public var kFontBurmeseLanguage: Int { 77 }
public var kFontBurmeseScript: Int { 19 }
public var kFontByelorussianLanguage: Int { 46 }
public var kFontCatalanLanguage: Int { 130 }
public var kFontChewaLanguage: Int { 92 }
public var kFontChineseScript: Int { 2 }
public var kFontCroatianLanguage: Int { 18 }
public var kFontCustom16BitScript: Int { 2 }
public var kFontCustom816BitScript: Int { 1 }
public var kFontCustom8BitScript: Int { 0 }
public var kFontCyrillicScript: Int { 7 }
public var kFontCzechLanguage: Int { 38 }
public var kFontDanishLanguage: Int { 7 }
public var kFontDevanagariScript: Int { 9 }
public var kFontDutchLanguage: Int { 4 }
public var kFontDzongkhaLanguage: Int { 137 }
public var kFontEastEuropeanRomanScript: Int { 29 }
public var kFontEnglishLanguage: Int { 0 }
public var kFontEsperantoLanguage: Int { 94 }
public var kFontEstonianLanguage: Int { 27 }
public var kFontEthiopicScript: Int { 28 }
public var kFontExtendedArabicScript: Int { 31 }
public var kFontFaeroeseLanguage: Int { 30 }
public var kFontFarsiLanguage: Int { 31 }
public var kFontFinnishLanguage: Int { 13 }
public var kFontFlemishLanguage: Int { 34 }
public var kFontFrenchLanguage: Int { 1 }
public var kFontGallaLanguage: Int { 87 }
public var kFontGeezScript: Int { 28 }
public var kFontGeorgianLanguage: Int { 52 }
public var kFontGeorgianScript: Int { 23 }
public var kFontGermanLanguage: Int { 2 }
public var kFontGreekLanguage: Int { 14 }
public var kFontGreekScript: Int { 6 }
public var kFontGuaraniLanguage: Int { 133 }
public var kFontGujaratiLanguage: Int { 69 }
public var kFontGujaratiScript: Int { 11 }
public var kFontGurmukhiScript: Int { 10 }
public var kFontHebrewLanguage: Int { 10 }
public var kFontHebrewScript: Int { 5 }
public var kFontHindiLanguage: Int { 21 }
public var kFontHungarianLanguage: Int { 26 }
public var kFontIcelandicLanguage: Int { 15 }
public var kFontIndonesianLanguage: Int { 81 }
public var kFontIrishLanguage: Int { 35 }
public var kFontItalianLanguage: Int { 3 }
public var kFontJapaneseLanguage: Int { 11 }
public var kFontJapaneseScript: Int { 1 }
public var kFontJavaneseRomLanguage: Int { 138 }
public var kFontKannadaLanguage: Int { 73 }
public var kFontKannadaScript: Int { 16 }
public var kFontKashmiriLanguage: Int { 61 }
public var kFontKazakhLanguage: Int { 48 }
public var kFontKhmerLanguage: Int { 78 }
public var kFontKhmerScript: Int { 20 }
public var kFontKirghizLanguage: Int { 54 }
public var kFontKoreanLanguage: Int { 23 }
public var kFontKoreanScript: Int { 3 }
public var kFontKurdishLanguage: Int { 60 }
public var kFontLaoLanguage: Int { 79 }
public var kFontLaotianScript: Int { 22 }
public var kFontLappishLanguage: Int { 29 }
public var kFontLatinLanguage: Int { 131 }
public var kFontLatvianLanguage: Int { 28 }
public var kFontLettishLanguage: Int { 28 }
public var kFontLithuanianLanguage: Int { 24 }
public var kFontMacedonianLanguage: Int { 43 }
public var kFontMalagasyLanguage: Int { 93 }
public var kFontMalayArabicLanguage: Int { 84 }
public var kFontMalayRomanLanguage: Int { 83 }
public var kFontMalayalamLanguage: Int { 72 }
public var kFontMalayalamScript: Int { 17 }
public var kFontMalteseLanguage: Int { 16 }
public var kFontMarathiLanguage: Int { 66 }
public var kFontMoldavianLanguage: Int { 53 }
public var kFontMongolianCyrLanguage: Int { 58 }
public var kFontMongolianLanguage: Int { 57 }
public var kFontMongolianScript: Int { 27 }
public var kFontNepaliLanguage: Int { 64 }
public var kFontNorwegianLanguage: Int { 9 }
public var kFontOriyaLanguage: Int { 71 }
public var kFontOriyaScript: Int { 12 }
public var kFontOromoLanguage: Int { 87 }
public var kFontPashtoLanguage: Int { 59 }
public var kFontPersianLanguage: Int { 31 }
public var kFontPolishLanguage: Int { 25 }
public var kFontPortugueseLanguage: Int { 8 }
public var kFontPunjabiLanguage: Int { 70 }
public var kFontQuechuaLanguage: Int { 132 }
public var kFontRSymbolScript: Int { 8 }
public var kFontRomanScript: Int { 0 }
public var kFontRomanianLanguage: Int { 37 }
public var kFontRuandaLanguage: Int { 90 }
public var kFontRundiLanguage: Int { 91 }
public var kFontRussian: Int { 7 }
public var kFontRussianLanguage: Int { 32 }
public var kFontSaamiskLanguage: Int { 29 }
public var kFontSanskritLanguage: Int { 65 }
public var kFontSerbianLanguage: Int { 42 }
public var kFontSimpChineseLanguage: Int { 33 }
public var kFontSimpleChineseScript: Int { 25 }
public var kFontSindhiLanguage: Int { 62 }
public var kFontSindhiScript: Int { 31 }
public var kFontSinhaleseLanguage: Int { 76 }
public var kFontSinhaleseScript: Int { 18 }
public var kFontSlavicScript: Int { 29 }
public var kFontSlovakLanguage: Int { 39 }
public var kFontSlovenianLanguage: Int { 40 }
public var kFontSomaliLanguage: Int { 88 }
public var kFontSpanishLanguage: Int { 6 }
public var kFontSundaneseRomLanguage: Int { 139 }
public var kFontSwahiliLanguage: Int { 89 }
public var kFontSwedishLanguage: Int { 5 }
public var kFontTagalogLanguage: Int { 82 }
public var kFontTajikiLanguage: Int { 55 }
public var kFontTamilLanguage: Int { 74 }
public var kFontTamilScript: Int { 14 }
public var kFontTatarLanguage: Int { 135 }
public var kFontTeluguLanguage: Int { 75 }
public var kFontTeluguScript: Int { 15 }
public var kFontThaiLanguage: Int { 22 }
public var kFontThaiScript: Int { 21 }
public var kFontTibetanLanguage: Int { 63 }
public var kFontTibetanScript: Int { 26 }
public var kFontTigrinyaLanguage: Int { 86 }
public var kFontTradChineseLanguage: Int { 19 }
public var kFontTraditionalChineseScript: Int { 2 }
public var kFontTurkishLanguage: Int { 17 }
public var kFontTurkmenLanguage: Int { 56 }
public var kFontUighurLanguage: Int { 136 }
public var kFontUkrainianLanguage: Int { 45 }
public var kFontUninterpretedScript: Int { 32 }
public var kFontUrduLanguage: Int { 20 }
public var kFontUzbekLanguage: Int { 47 }
public var kFontVietnameseLanguage: Int { 80 }
public var kFontVietnameseScript: Int { 30 }
public var kFontWelshLanguage: Int { 128 }
public var kFontYiddishLanguage: Int { 41 }
public var kJUSTCurrentVersion: Int { 65536 }
public var kJUSTKashidaPriority: Int { 0 }
public var kJUSTLetterPriority: Int { 2 }
public var kJUSTNullPriority: Int { 3 }
public var kJUSTOverrideLimits: Int { 16384 }
public var kJUSTOverridePriority: Int { 32768 }
public var kJUSTOverrideUnlimited: Int { 8192 }
public var kJUSTPriorityCount: Int { 4 }
public var kJUSTPriorityMask: Int { 3 }
public var kJUSTSpacePriority: Int { 1 }
public var kJUSTStandardFormat: Int { 0 }
public var kJUSTUnlimited: Int { 4096 }
public var kJUSTnoGlyphcode: Int { 65535 }
public var kJUSTpcConditionalAddAction: Int { 2 }
public var kJUSTpcDecompositionAction: Int { 0 }
public var kJUSTpcDuctilityAction: Int { 4 }
public var kJUSTpcGlyphRepeatAddAction: Int { 5 }
public var kJUSTpcGlyphStretchAction: Int { 3 }
public var kJUSTpcUnconditionalAddAction: Int { 1 }
public var kKERNCrossStream: Int { 16384 }
public var kKERNCrossStreamResetNote: Int { 2 }
public var kKERNCurrentVersion: Int { 65536 }
public var kKERNFormatMask: Int { 255 }
public var kKERNIndexArray: Int { 3 }
public var kKERNLineEndKerning: Int { 2 }
public var kKERNLineStart: Int { 1 }
public var kKERNNoCrossKerning: Int { 4 }
public var kKERNNoStakeNote: Int { 1 }
public var kKERNNotApplied: Int { 1 }
public var kKERNNotesRequested: Int { 8 }
public var kKERNOrderedList: Int { 0 }
public var kKERNResetCrossStream: Int { 32768 }
public var kKERNSimpleArray: Int { 2 }
public var kKERNStateTable: Int { 1 }
public var kKERNUnusedBits: Int { 7936 }
public var kKERNVariation: Int { 8192 }
public var kKERNVertical: Int { 32768 }
public var kKERXActionOffsetMask: Int { 16777215 }
public var kKERXActionTypeAnchorPoints: Int { 1073741824 }
public var kKERXActionTypeControlPoints: Int { 0 }
public var kKERXActionTypeCoordinates: Int { 2147483648 }
public var kKERXActionTypeMask: Int { 3221225472 }
public var kKERXControlPoint: Int { 4 }
public var kKERXCrossStream: Int { 1073741824 }
public var kKERXCrossStreamResetNote: Int { 2 }
public var kKERXCurrentVersion: Int { 131072 }
public var kKERXDescending: Int { 268435456 }
public var kKERXFormatMask: Int { 255 }
public var kKERXIndexArray: Int { 3 }
public var kKERXLineEndKerning: Int { 2 }
public var kKERXLineStart: Int { 1 }
public var kKERXNoCrossKerning: Int { 4 }
public var kKERXNoStakeNote: Int { 1 }
public var kKERXNotApplied: Int { 1 }
public var kKERXNotesRequested: Int { 8 }
public var kKERXOrderedList: Int { 0 }
public var kKERXResetCrossStream: Int { 32768 }
public var kKERXSimpleArray: Int { 2 }
public var kKERXStateTable: Int { 1 }
public var kKERXUnusedBits: Int { 268435200 }
public var kKERXUnusedFlags: Int { 1056964608 }
public var kKERXValuesAreLong: Int { 1 }
public var kKERXVariation: Int { 536870912 }
public var kKERXVertical: Int { -2147483648 }
public var kLCARCtlPointFormat: Int { 1 }
public var kLCARCurrentVersion: Int { 65536 }
public var kLCARLinearFormat: Int { 0 }
public var kLTAGCurrentVersion: Int { 1 }
public var kLastFeatureType: Int { -1 }
public var kMORTContextualType: Int { 1 }
public var kMORTCoverDescending: Int { 16384 }
public var kMORTCoverIgnoreVertical: Int { 8192 }
public var kMORTCoverTypeMask: Int { 15 }
public var kMORTCoverVertical: Int { 32768 }
public var kMORTCurrInsertBefore: Int { 2048 }
public var kMORTCurrInsertCountMask: Int { 992 }
public var kMORTCurrInsertCountShift: Int { 5 }
public var kMORTCurrInsertKashidaLike: Int { 8192 }
public var kMORTCurrJustTableCountMask: Int { 127 }
public var kMORTCurrJustTableCountShift: Int { 0 }
public var kMORTCurrentVersion: Int { 65536 }
public var kMORTDoInsertionsBefore: Int { 128 }
public var kMORTInsertionType: Int { 5 }
public var kMORTInsertionsCountMask: Int { 63 }
public var kMORTIsSplitVowelPiece: Int { 64 }
public var kMORTLigFormOffsetMask: Int { 1073741823 }
public var kMORTLigFormOffsetShift: Int { 2 }
public var kMORTLigLastAction: Int { -2147483648 }
public var kMORTLigStoreLigature: Int { 1073741824 }
public var kMORTLigatureType: Int { 2 }
public var kMORTMarkInsertBefore: Int { 1024 }
public var kMORTMarkInsertCountMask: Int { 31 }
public var kMORTMarkInsertCountShift: Int { 0 }
public var kMORTMarkInsertKashidaLike: Int { 4096 }
public var kMORTMarkJustTableCountMask: Int { 16256 }
public var kMORTMarkJustTableCountShift: Int { 7 }
public var kMORTRearrangementType: Int { 0 }
public var kMORTSwashType: Int { 4 }
public var kMORTraCDx: Int { 6 }
public var kMORTraCDxA: Int { 8 }
public var kMORTraCDxAB: Int { 12 }
public var kMORTraCDxBA: Int { 13 }
public var kMORTraDCx: Int { 7 }
public var kMORTraDCxA: Int { 9 }
public var kMORTraDCxAB: Int { 14 }
public var kMORTraDCxBA: Int { 15 }
public var kMORTraDx: Int { 2 }
public var kMORTraDxA: Int { 3 }
public var kMORTraDxAB: Int { 10 }
public var kMORTraDxBA: Int { 11 }
public var kMORTraNoAction: Int { 0 }
public var kMORTraxA: Int { 1 }
public var kMORTraxAB: Int { 4 }
public var kMORTraxBA: Int { 5 }
public var kMORXCoverDescending: Int { 1073741824 }
public var kMORXCoverIgnoreVertical: Int { 536870912 }
public var kMORXCoverLogicalOrder: Int { 268435456 }
public var kMORXCoverTypeMask: Int { 255 }
public var kMORXCoverVertical: Int { -2147483648 }
public var kMORXCurrentVersion: Int { 131072 }
public var kOPBDControlPointFormat: Int { 1 }
public var kOPBDCurrentVersion: Int { 65536 }
public var kOPBDDistanceFormat: Int { 0 }
public var kPROPALDirectionClass: Int { 2 }
public var kPROPANDirectionClass: Int { 6 }
public var kPROPBNDirectionClass: Int { 19 }
public var kPROPCSDirectionClass: Int { 7 }
public var kPROPCanHangLTMask: Int { 16384 }
public var kPROPCanHangRBMask: Int { 8192 }
public var kPROPCurrentVersion: Int { 196608 }
public var kPROPDirectionMask: Int { 31 }
public var kPROPENDirectionClass: Int { 3 }
public var kPROPESDirectionClass: Int { 4 }
public var kPROPETDirectionClass: Int { 5 }
public var kPROPIsFloaterMask: Int { 32768 }
public var kPROPLDirectionClass: Int { 0 }
public var kPROPLREDirectionClass: Int { 13 }
public var kPROPLRODirectionClass: Int { 14 }
public var kPROPNSMDirectionClass: Int { 18 }
public var kPROPNumDirectionClasses: Int { 20 }
public var kPROPONDirectionClass: Int { 11 }
public var kPROPPDFDirectionClass: Int { 17 }
public var kPROPPSDirectionClass: Int { 8 }
public var kPROPPairOffsetMask: Int { 3840 }
public var kPROPPairOffsetShift: Int { 8 }
public var kPROPPairOffsetSign: Int { 7 }
public var kPROPRDirectionClass: Int { 1 }
public var kPROPRLEDirectionClass: Int { 15 }
public var kPROPRLODirectionClass: Int { 16 }
public var kPROPRightConnectMask: Int { 128 }
public var kPROPSDirectionClass: Int { 9 }
public var kPROPSENDirectionClass: Int { 12 }
public var kPROPUseRLPairMask: Int { 4096 }
public var kPROPWSDirectionClass: Int { 10 }
public var kPROPZeroReserved: Int { 96 }
public var kSFNTLookupSegmentArray: Int { 4 }
public var kSFNTLookupSegmentSingle: Int { 2 }
public var kSFNTLookupSimpleArray: Int { 0 }
public var kSFNTLookupSingleTable: Int { 6 }
public var kSFNTLookupTrimmedArray: Int { 8 }
public var kSFNTLookupVector: Int { 10 }
public var kSTClassDeletedGlyph: Int { 2 }
public var kSTClassEndOfLine: Int { 3 }
public var kSTClassEndOfText: Int { 0 }
public var kSTClassOutOfBounds: Int { 1 }
public var kSTKCrossStreamReset: Int { 8192 }
public var kSTLigActionMask: Int { 16383 }
public var kSTMarkEnd: Int { 8192 }
public var kSTNoAdvance: Int { 16384 }
public var kSTRearrVerbMask: Int { 15 }
public var kSTSetMark: Int { 32768 }
public var kSTXHasLigAction: Int { 8192 }
public var kTRAKCurrentVersion: Int { 65536 }
public var kTRAKUniformFormat: Int { 0 }
public var nonGlyphID: Int { 65535 }
public var sizeof_sfntCMapEncoding: Int { 8 }
public var sizeof_sfntCMapExtendedSubHeader: Int { 12 }
public var sizeof_sfntCMapHeader: Int { 4 }
public var sizeof_sfntCMapSubHeader: Int { 6 }
public var sizeof_sfntDescriptorHeader: Int { 8 }
public var sizeof_sfntDirectory: Int { 12 }
public var sizeof_sfntInstance: Int { 4 }
public var sizeof_sfntNameHeader: Int { 6 }
public var sizeof_sfntNameRecord: Int { 12 }
public var sizeof_sfntVariationAxis: Int { 20 }
public var sizeof_sfntVariationHeader: Int { 16 }
