import CoreFoundation
import Foundation

// MARK: - Integer constants with established public ABI values

public var kCTFontTableAcnt: Int { 1633906292 }
public var kCTFontTableAnkr: Int { 1634626418 }
public var kCTFontTableAvar: Int { 1635148146 }
public var kCTFontTableBASE: Int { 1111577413 }
public var kCTFontTableBdat: Int { 1650745716 }
public var kCTFontTableBhed: Int { 1651008868 }
public var kCTFontTableBloc: Int { 1651273571 }
public var kCTFontTableBsln: Int { 1651731566 }
public var kCTFontTableCBDT: Int { 1128416340 }
public var kCTFontTableCBLC: Int { 1128418371 }
public var kCTFontTableCFF: Int { 1128678944 }
public var kCTFontTableCFF2: Int { 1128678962 }
public var kCTFontTableCOLR: Int { 1129270354 }
public var kCTFontTableCPAL: Int { 1129333068 }
public var kCTFontTableCidg: Int { 1667851367 }
public var kCTFontTableCmap: Int { 1668112752 }
public var kCTFontTableCvar: Int { 1668702578 }
public var kCTFontTableCvt: Int { 1668707360 }
public var kCTFontTableDSIG: Int { 1146308935 }
public var kCTFontTableEBDT: Int { 1161970772 }
public var kCTFontTableEBLC: Int { 1161972803 }
public var kCTFontTableEBSC: Int { 1161974595 }
public var kCTFontTableFdsc: Int { 1717859171 }
public var kCTFontTableFeat: Int { 1717920116 }
public var kCTFontTableFmtx: Int { 1718449272 }
public var kCTFontTableFond: Int { 1718578788 }
public var kCTFontTableFpgm: Int { 1718642541 }
public var kCTFontTableFvar: Int { 1719034226 }
public var kCTFontTableGDEF: Int { 1195656518 }
public var kCTFontTableGPOS: Int { 1196445523 }
public var kCTFontTableGSUB: Int { 1196643650 }
public var kCTFontTableGasp: Int { 1734439792 }
public var kCTFontTableGlyf: Int { 1735162214 }
public var kCTFontTableGvar: Int { 1735811442 }
public var kCTFontTableHVAR: Int { 1213612370 }
public var kCTFontTableHdmx: Int { 1751412088 }
public var kCTFontTableHead: Int { 1751474532 }
public var kCTFontTableHhea: Int { 1751672161 }
public var kCTFontTableHmtx: Int { 1752003704 }
public var kCTFontTableHsty: Int { 1752396921 }
public var kCTFontTableJSTF: Int { 1246975046 }
public var kCTFontTableJust: Int { 1786082164 }
public var kCTFontTableKern: Int { 1801810542 }
public var kCTFontTableKerx: Int { 1801810552 }
public var kCTFontTableLTSH: Int { 1280594760 }
public var kCTFontTableLcar: Int { 1818452338 }
public var kCTFontTableLoca: Int { 1819239265 }
public var kCTFontTableLtag: Int { 1819566439 }
public var kCTFontTableMATH: Int { 1296127048 }
public var kCTFontTableMERG: Int { 1296388679 }
public var kCTFontTableMVAR: Int { 1297498450 }
public var kCTFontTableMaxp: Int { 1835104368 }
public var kCTFontTableMeta: Int { 1835365473 }
public var kCTFontTableMort: Int { 1836020340 }
public var kCTFontTableMorx: Int { 1836020344 }
public var kCTFontTableName: Int { 1851878757 }
public var kCTFontTableOS2: Int { 1330851634 }
public var kCTFontTableOpbd: Int { 1869636196 }
public var kCTFontTablePCLT: Int { 1346587732 }
public var kCTFontTablePost: Int { 1886352244 }
public var kCTFontTablePrep: Int { 1886545264 }
public var kCTFontTableProp: Int { 1886547824 }
public var kCTFontTableSTAT: Int { 1398030676 }
public var kCTFontTableSVG: Int { 1398163232 }
public var kCTFontTableSbit: Int { 1935829364 }
public var kCTFontTableSbix: Int { 1935829368 }
public var kCTFontTableTrak: Int { 1953653099 }
public var kCTFontTableVDMX: Int { 1447316824 }
public var kCTFontTableVORG: Int { 1448038983 }
public var kCTFontTableVVAR: Int { 1448493394 }
public var kCTFontTableVhea: Int { 1986553185 }
public var kCTFontTableVmtx: Int { 1986884728 }
public var kCTFontTableXref: Int { 2020762982 }
public var kCTFontTableZapf: Int { 1516335206 }
public var kAllTypographicFeaturesType: Int { 0 }
public var kAlternateKanaType: Int { 34 }
public var kAnnotationType: Int { 24 }
public var kCJKRomanSpacingType: Int { 103 }
public var kCJKSymbolAlternativesType: Int { 29 }
public var kCJKVerticalRomanPlacementType: Int { 31 }
public var kCaseSensitiveLayoutType: Int { 33 }
public var kCharacterAlternativesType: Int { 17 }
public var kCharacterShapeType: Int { 20 }
public var kContextualAlternatesType: Int { 36 }
public var kCursiveConnectionType: Int { 2 }
public var kDesignComplexityType: Int { 18 }
public var kDiacriticsType: Int { 9 }
public var kFractionsType: Int { 11 }
public var kIdeographicAlternativesType: Int { 30 }
public var kIdeographicSpacingType: Int { 26 }
public var kItalicCJKRomanType: Int { 32 }
public var kKanaSpacingType: Int { 25 }
public var kLanguageTagType: Int { 39 }
public var kLetterCaseType: Int { 3 }
public var kLigaturesType: Int { 1 }
public var kLinguisticRearrangementType: Int { 5 }
public var kLowerCaseType: Int { 37 }
public var kMathematicalExtrasType: Int { 15 }
public var kNumberCaseType: Int { 21 }
public var kNumberSpacingType: Int { 6 }
public var kOrnamentSetsType: Int { 16 }
public var kOverlappingCharactersType: Int { 13 }
public var kRubyKanaType: Int { 28 }
public var kSmartSwashType: Int { 8 }
public var kStyleOptionsType: Int { 19 }
public var kStylisticAlternativesType: Int { 35 }
public var kTextSpacingType: Int { 22 }
public var kTransliterationType: Int { 23 }
public var kTypographicExtrasType: Int { 14 }
public var kUnicodeDecompositionType: Int { 27 }
public var kUpperCaseType: Int { 38 }
public var kVerticalPositionType: Int { 10 }
public var kVerticalSubstitutionType: Int { 4 }
public var kCTVersionNumber10_10: Int32 { 458752 }
public var kCTVersionNumber10_11: Int32 { 524288 }
public var kCTVersionNumber10_12: Int32 { 589824 }
public var kCTVersionNumber10_13: Int32 { 655360 }
public var kCTVersionNumber10_14: Int32 { 720896 }
public var kCTVersionNumber10_15: Int32 { 786432 }
public var kCTVersionNumber10_5: Int32 { 131072 }
public var kCTVersionNumber10_5_2: Int32 { 131073 }
public var kCTVersionNumber10_5_3: Int32 { 131074 }
public var kCTVersionNumber10_5_5: Int32 { 131075 }
public var kCTVersionNumber10_6: Int32 { 196608 }
public var kCTVersionNumber10_7: Int32 { 262144 }
public var kCTVersionNumber10_8: Int32 { 327680 }
public var kCTVersionNumber10_9: Int32 { 393216 }
public var kCTVersionNumber11_0: Int32 { 851968 }
public var kCTFontPriorityComputer: Int { 30000 }
public var kCTFontPriorityDynamic: Int { 50000 }
public var kCTFontPriorityNetwork: Int { 20000 }
public var kCTFontPriorityProcess: Int { 60000 }
public var kCTFontPrioritySystem: Int { 10000 }
public var kCTFontPriorityUser: Int { 40000 }
public var cmapFontTableTag: Int { 1668112752 }
public var descriptorFontTableTag: Int { 1717859171 }
public var featureFontTableTag: Int { 1717920116 }
public var kCTFontClassMaskShift: Int { 28 }
public var kCTRunDelegateCurrentVersion: Int { 1 }
public var kCTRunDelegateVersion1: Int { 1 }
public var kAbbrevSquaredLigaturesOffSelector: Int { 15 }
public var kAbbrevSquaredLigaturesOnSelector: Int { 14 }
public var kAllCapsSelector: Int { 1 }
public var kAllLowerCaseSelector: Int { 2 }
public var kAllTypeFeaturesOffSelector: Int { 1 }
public var kAllTypeFeaturesOnSelector: Int { 0 }
public var kAltHalfWidthTextSelector: Int { 6 }
public var kAltProportionalTextSelector: Int { 5 }
public var kAlternateHorizKanaOffSelector: Int { 1 }
public var kAlternateHorizKanaOnSelector: Int { 0 }
public var kAlternateVertKanaOffSelector: Int { 3 }
public var kAlternateVertKanaOnSelector: Int { 2 }
public var kAsteriskToMultiplyOffSelector: Int { 3 }
public var kAsteriskToMultiplyOnSelector: Int { 2 }
public var kBoxAnnotationSelector: Int { 1 }
public var kCJKItalicRomanOffSelector: Int { 3 }
public var kCJKItalicRomanOnSelector: Int { 2 }
public var kCJKItalicRomanSelector: Int { 1 }
public var kCJKSymbolAltFiveSelector: Int { 5 }
public var kCJKSymbolAltFourSelector: Int { 4 }
public var kCJKSymbolAltOneSelector: Int { 1 }
public var kCJKSymbolAltThreeSelector: Int { 3 }
public var kCJKSymbolAltTwoSelector: Int { 2 }
public var kCJKVerticalRomanCenteredSelector: Int { 0 }
public var kCJKVerticalRomanHBaselineSelector: Int { 1 }
public var kCanonicalCompositionOffSelector: Int { 1 }
public var kCanonicalCompositionOnSelector: Int { 0 }
public var kCaseSensitiveLayoutOffSelector: Int { 1 }
public var kCaseSensitiveLayoutOnSelector: Int { 0 }
public var kCaseSensitiveSpacingOffSelector: Int { 3 }
public var kCaseSensitiveSpacingOnSelector: Int { 2 }
public var kCircleAnnotationSelector: Int { 3 }
public var kCommonLigaturesOffSelector: Int { 3 }
public var kCommonLigaturesOnSelector: Int { 2 }
public var kCompatibilityCompositionOffSelector: Int { 3 }
public var kCompatibilityCompositionOnSelector: Int { 2 }
public var kContextualAlternatesOffSelector: Int { 1 }
public var kContextualAlternatesOnSelector: Int { 0 }
public var kContextualLigaturesOffSelector: Int { 19 }
public var kContextualLigaturesOnSelector: Int { 18 }
public var kContextualSwashAlternatesOffSelector: Int { 5 }
public var kContextualSwashAlternatesOnSelector: Int { 4 }
public var kCursiveSelector: Int { 2 }
public var kDecomposeDiacriticsSelector: Int { 2 }
public var kDecorativeBordersSelector: Int { 4 }
public var kDefaultCJKRomanSelector: Int { 2 }
public var kDefaultLowerCaseSelector: Int { 0 }
public var kDefaultUpperCaseSelector: Int { 0 }
public var kDesignLevel1Selector: Int { 0 }
public var kDesignLevel2Selector: Int { 1 }
public var kDesignLevel3Selector: Int { 2 }
public var kDesignLevel4Selector: Int { 3 }
public var kDesignLevel5Selector: Int { 4 }
public var kDiagonalFractionsSelector: Int { 2 }
public var kDiamondAnnotationSelector: Int { 8 }
public var kDingbatsSelector: Int { 1 }
public var kDiphthongLigaturesOffSelector: Int { 11 }
public var kDiphthongLigaturesOnSelector: Int { 10 }
public var kDisplayTextSelector: Int { 1 }
public var kEngravedTextSelector: Int { 2 }
public var kExpertCharactersSelector: Int { 10 }
public var kExponentsOffSelector: Int { 9 }
public var kExponentsOnSelector: Int { 8 }
public var kFleuronsSelector: Int { 3 }
public var kFormInterrobangOffSelector: Int { 7 }
public var kFormInterrobangOnSelector: Int { 6 }
public var kFullWidthCJKRomanSelector: Int { 3 }
public var kFullWidthIdeographsSelector: Int { 0 }
public var kFullWidthKanaSelector: Int { 0 }
public var kHalfWidthCJKRomanSelector: Int { 0 }
public var kHalfWidthIdeographsSelector: Int { 2 }
public var kHalfWidthTextSelector: Int { 2 }
public var kHanjaToHangulAltOneSelector: Int { 7 }
public var kHanjaToHangulAltThreeSelector: Int { 9 }
public var kHanjaToHangulAltTwoSelector: Int { 8 }
public var kHanjaToHangulSelector: Int { 1 }
public var kHideDiacriticsSelector: Int { 1 }
public var kHiraganaToKatakanaSelector: Int { 2 }
public var kHistoricalLigaturesOffSelector: Int { 21 }
public var kHistoricalLigaturesOnSelector: Int { 20 }
public var kHojoCharactersSelector: Int { 12 }
public var kHyphenToEnDashOffSelector: Int { 3 }
public var kHyphenToEnDashOnSelector: Int { 2 }
public var kHyphenToMinusOffSelector: Int { 1 }
public var kHyphenToMinusOnSelector: Int { 0 }
public var kHyphensToEmDashOffSelector: Int { 1 }
public var kHyphensToEmDashOnSelector: Int { 0 }
public var kIdeographicAltFiveSelector: Int { 5 }
public var kIdeographicAltFourSelector: Int { 4 }
public var kIdeographicAltOneSelector: Int { 1 }
public var kIdeographicAltThreeSelector: Int { 3 }
public var kIdeographicAltTwoSelector: Int { 2 }
public var kIlluminatedCapsSelector: Int { 3 }
public var kInequalityLigaturesOffSelector: Int { 7 }
public var kInequalityLigaturesOnSelector: Int { 6 }
public var kInferiorsSelector: Int { 2 }
public var kInitialCapsAndSmallCapsSelector: Int { 5 }
public var kInitialCapsSelector: Int { 4 }
public var kInternationalSymbolsSelector: Int { 5 }
public var kInvertedBoxAnnotationSelector: Int { 9 }
public var kInvertedCircleAnnotationSelector: Int { 4 }
public var kInvertedRoundedBoxAnnotationSelector: Int { 10 }
public var kJIS1978CharactersSelector: Int { 2 }
public var kJIS1983CharactersSelector: Int { 3 }
public var kJIS1990CharactersSelector: Int { 4 }
public var kJIS2004CharactersSelector: Int { 11 }
public var kKanaToRomanizationSelector: Int { 4 }
public var kKatakanaToHiraganaSelector: Int { 3 }
public var kLineFinalSwashesOffSelector: Int { 7 }
public var kLineFinalSwashesOnSelector: Int { 6 }
public var kLineInitialSwashesOffSelector: Int { 5 }
public var kLineInitialSwashesOnSelector: Int { 4 }
public var kLinguisticRearrangementOffSelector: Int { 1 }
public var kLinguisticRearrangementOnSelector: Int { 0 }
public var kLogosOffSelector: Int { 7 }
public var kLogosOnSelector: Int { 6 }
public var kLowerCaseNumbersSelector: Int { 0 }
public var kLowerCasePetiteCapsSelector: Int { 2 }
public var kLowerCaseSmallCapsSelector: Int { 1 }
public var kMathSymbolsSelector: Int { 6 }
public var kMathematicalGreekOffSelector: Int { 11 }
public var kMathematicalGreekOnSelector: Int { 10 }
public var kMonospacedNumbersSelector: Int { 0 }
public var kMonospacedTextSelector: Int { 1 }
public var kNLCCharactersSelector: Int { 13 }
public var kNoAlternatesSelector: Int { 0 }
public var kNoAnnotationSelector: Int { 0 }
public var kNoCJKItalicRomanSelector: Int { 0 }
public var kNoCJKSymbolAlternativesSelector: Int { 0 }
public var kNoFractionsSelector: Int { 0 }
public var kNoIdeographicAlternativesSelector: Int { 0 }
public var kNoOrnamentsSelector: Int { 0 }
public var kNoRubyKanaSelector: Int { 0 }
public var kNoStyleOptionsSelector: Int { 0 }
public var kNoStylisticAlternatesSelector: Int { 0 }
public var kNoTransliterationSelector: Int { 0 }
public var kNonFinalSwashesOffSelector: Int { 9 }
public var kNonFinalSwashesOnSelector: Int { 8 }
public var kNormalPositionSelector: Int { 0 }
public var kOrdinalsSelector: Int { 3 }
public var kParenthesisAnnotationSelector: Int { 5 }
public var kPartiallyConnectedSelector: Int { 1 }
public var kPeriodAnnotationSelector: Int { 6 }
public var kPeriodsToEllipsisOffSelector: Int { 11 }
public var kPeriodsToEllipsisOnSelector: Int { 10 }
public var kPiCharactersSelector: Int { 2 }
public var kPreventOverlapOffSelector: Int { 1 }
public var kPreventOverlapOnSelector: Int { 0 }
public var kProportionalCJKRomanSelector: Int { 1 }
public var kProportionalIdeographsSelector: Int { 1 }
public var kProportionalKanaSelector: Int { 1 }
public var kProportionalNumbersSelector: Int { 1 }
public var kProportionalTextSelector: Int { 0 }
public var kQuarterWidthNumbersSelector: Int { 3 }
public var kQuarterWidthTextSelector: Int { 4 }
public var kRareLigaturesOffSelector: Int { 5 }
public var kRareLigaturesOnSelector: Int { 4 }
public var kRebusPicturesOffSelector: Int { 9 }
public var kRebusPicturesOnSelector: Int { 8 }
public var kRequiredLigaturesOffSelector: Int { 1 }
public var kRequiredLigaturesOnSelector: Int { 0 }
public var kRomanNumeralAnnotationSelector: Int { 7 }
public var kRomanizationToHiraganaSelector: Int { 5 }
public var kRomanizationToKatakanaSelector: Int { 6 }
public var kRoundedBoxAnnotationSelector: Int { 2 }
public var kRubyKanaOffSelector: Int { 3 }
public var kRubyKanaOnSelector: Int { 2 }
public var kRubyKanaSelector: Int { 1 }
public var kScientificInferiorsSelector: Int { 4 }
public var kShowDiacriticsSelector: Int { 0 }
public var kSimplifiedCharactersSelector: Int { 1 }
public var kSlashToDivideOffSelector: Int { 5 }
public var kSlashToDivideOnSelector: Int { 4 }
public var kSlashedZeroOffSelector: Int { 5 }
public var kSlashedZeroOnSelector: Int { 4 }
public var kSmallCapsSelector: Int { 3 }
public var kSmartQuotesOffSelector: Int { 9 }
public var kSmartQuotesOnSelector: Int { 8 }
public var kSquaredLigaturesOffSelector: Int { 13 }
public var kSquaredLigaturesOnSelector: Int { 12 }
public var kStylisticAltEightOffSelector: Int { 17 }
public var kStylisticAltEightOnSelector: Int { 16 }
public var kStylisticAltEighteenOffSelector: Int { 37 }
public var kStylisticAltEighteenOnSelector: Int { 36 }
public var kStylisticAltElevenOffSelector: Int { 23 }
public var kStylisticAltElevenOnSelector: Int { 22 }
public var kStylisticAltFifteenOffSelector: Int { 31 }
public var kStylisticAltFifteenOnSelector: Int { 30 }
public var kStylisticAltFiveOffSelector: Int { 11 }
public var kStylisticAltFiveOnSelector: Int { 10 }
public var kStylisticAltFourOffSelector: Int { 9 }
public var kStylisticAltFourOnSelector: Int { 8 }
public var kStylisticAltFourteenOffSelector: Int { 29 }
public var kStylisticAltFourteenOnSelector: Int { 28 }
public var kStylisticAltNineOffSelector: Int { 19 }
public var kStylisticAltNineOnSelector: Int { 18 }
public var kStylisticAltNineteenOffSelector: Int { 39 }
public var kStylisticAltNineteenOnSelector: Int { 38 }
public var kStylisticAltOneOffSelector: Int { 3 }
public var kStylisticAltOneOnSelector: Int { 2 }
public var kStylisticAltSevenOffSelector: Int { 15 }
public var kStylisticAltSevenOnSelector: Int { 14 }
public var kStylisticAltSeventeenOffSelector: Int { 35 }
public var kStylisticAltSeventeenOnSelector: Int { 34 }
public var kStylisticAltSixOffSelector: Int { 13 }
public var kStylisticAltSixOnSelector: Int { 12 }
public var kStylisticAltSixteenOffSelector: Int { 33 }
public var kStylisticAltSixteenOnSelector: Int { 32 }
public var kStylisticAltTenOffSelector: Int { 21 }
public var kStylisticAltTenOnSelector: Int { 20 }
public var kStylisticAltThirteenOffSelector: Int { 27 }
public var kStylisticAltThirteenOnSelector: Int { 26 }
public var kStylisticAltThreeOffSelector: Int { 7 }
public var kStylisticAltThreeOnSelector: Int { 6 }
public var kStylisticAltTwelveOffSelector: Int { 25 }
public var kStylisticAltTwelveOnSelector: Int { 24 }
public var kStylisticAltTwentyOffSelector: Int { 41 }
public var kStylisticAltTwentyOnSelector: Int { 40 }
public var kStylisticAltTwoOffSelector: Int { 5 }
public var kStylisticAltTwoOnSelector: Int { 4 }
public var kSubstituteVerticalFormsOffSelector: Int { 1 }
public var kSubstituteVerticalFormsOnSelector: Int { 0 }
public var kSuperiorsSelector: Int { 1 }
public var kSwashAlternatesOffSelector: Int { 3 }
public var kSwashAlternatesOnSelector: Int { 2 }
public var kSymbolLigaturesOffSelector: Int { 17 }
public var kSymbolLigaturesOnSelector: Int { 16 }
public var kTallCapsSelector: Int { 5 }
public var kThirdWidthNumbersSelector: Int { 2 }
public var kThirdWidthTextSelector: Int { 3 }
public var kTitlingCapsSelector: Int { 4 }
public var kTraditionalAltFiveSelector: Int { 9 }
public var kTraditionalAltFourSelector: Int { 8 }
public var kTraditionalAltOneSelector: Int { 5 }
public var kTraditionalAltThreeSelector: Int { 7 }
public var kTraditionalAltTwoSelector: Int { 6 }
public var kTraditionalCharactersSelector: Int { 0 }
public var kTraditionalNamesCharactersSelector: Int { 14 }
public var kTranscodingCompositionOffSelector: Int { 5 }
public var kTranscodingCompositionOnSelector: Int { 4 }
public var kUnconnectedSelector: Int { 0 }
public var kUpperAndLowerCaseSelector: Int { 0 }
public var kUpperCaseNumbersSelector: Int { 1 }
public var kUpperCasePetiteCapsSelector: Int { 2 }
public var kUpperCaseSmallCapsSelector: Int { 1 }
public var kVerticalFractionsSelector: Int { 1 }
public var kWordFinalSwashesOffSelector: Int { 3 }
public var kWordFinalSwashesOnSelector: Int { 2 }
public var kWordInitialSwashesOffSelector: Int { 1 }
public var kWordInitialSwashesOnSelector: Int { 0 }

// MARK: - OpenType name IDs (ISO/IEC 14496-22) imported as Apple kFont* aliases

public var kFontCopyrightName: Int { 0 }
public var kFontFamilyName: Int { 1 }
public var kFontStyleName: Int { 2 }
public var kFontUniqueName: Int { 3 }
public var kFontFullName: Int { 4 }
public var kFontVersionName: Int { 5 }
public var kFontManufacturerName: Int { 8 }
public var kFontDesignerName: Int { 9 }
public var kFontDescriptionName: Int { 10 }
public var kFontVendorURLName: Int { 11 }
public var kFontDesignerURLName: Int { 12 }
public var kFontLicenseDescriptionName: Int { 13 }
public var kFontLicenseInfoURLName: Int { 14 }
public var kFontPreferredFamilyName: Int { 16 }
public var kFontPreferredSubfamilyName: Int { 17 }
public var kFontMacCompatibleFullName: Int { 18 }
public var kFontSampleTextName: Int { 19 }
public var kFontPostscriptName: Int { 6 }
public var kFontPostScriptCIDName: Int { 20 }
public var kFontTrademarkName: Int { 7 }
public var kFontLastReservedName: Int { 255 }

// MARK: - OpenType platform / encoding IDs

public var kFontUnicodePlatform: Int { 0 }
public var kFontMacintoshPlatform: Int { 1 }
public var kFontReservedPlatform: Int { 2 }
public var kFontMicrosoftPlatform: Int { 3 }
public var kFontCustomPlatform: Int { 4 }
public var kFontUnicodeDefaultSemantics: Int { 0 }
public var kFontUnicodeV1_1Semantics: Int { 1 }
public var kFontISO10646_1993Semantics: Int { 2 }
public var kFontUnicodeV2_0BMPOnlySemantics: Int { 3 }
public var kFontUnicodeV2_0FullCoverageSemantics: Int { 4 }
public var kFontUnicodeV4_0VariationSequenceSemantics: Int { 5 }
public var kFontUnicode_FullRepertoire: Int { 6 }
public var kFontMicrosoftSymbolScript: Int { 0 }
public var kFontMicrosoftStandardScript: Int { 1 }
public var kFontMicrosoftUCS4Script: Int { 10 }
public var kFontNoPlatformCode: UInt32 { 0xFFFF_FFFF }
public var kFontNoScriptCode: UInt32 { 0xFFFF_FFFF }
public var kFontNoLanguageCode: UInt32 { 0xFFFF_FFFF }
public var kFontNoNameCode: UInt32 { 0xFFFF_FFFF }

// MARK: - SFNT FourCC table tags (same packing as kCTFontTable*)

public var kMORTTag: Int { 1836020340 }
public var kMORXTag: Int { 1836020344 }
public var kPROPTag: Int { 1886547824 }
public var kKERNTag: Int { 1801810542 }
public var kKERXTag: Int { 1801810552 }
public var kBSLNTag: Int { 1651731566 }
public var kJUSTTag: Int { 1786082164 }
public var kLCARTag: Int { 1818452338 }
public var kOPBDTag: Int { 1869636196 }
public var kTRAKTag: Int { 1953653099 }
public var nameFontTableTag: Int { 1851878757 }
public var os2FontTableTag: Int { 1330851634 }
public var variationFontTableTag: Int { 1719034226 }
public var ATSFONTREF_DEFINED: Int32 { 1 }

// CTParagraphStyle writing-direction flags: (0 << 1) and (1 << 1)
public var kCTWritingDirectionEmbedding: Int { 0 }
public var kCTWritingDirectionOverride: Int { 2 }
