import Foundation
import CoreText

func testCatalogEnumAndOptionSetRawValues() {
    _ = CTCharacterCollection.identityMapping.rawValue
    _ = CTCharacterCollection.identityMapping
    _ = CTCharacterCollection.adobeCNS1
    _ = CTCharacterCollection.adobeGB1
    _ = CTCharacterCollection.adobeJapan1
    _ = CTCharacterCollection.adobeJapan2
    _ = CTCharacterCollection.adobeKorea1
    _ = CTCharacterCollection.kCTIdentityMappingCharacterCollection
    _ = CTCharacterCollection.kCTAdobeCNS1CharacterCollection
    _ = CTCharacterCollection.kCTAdobeGB1CharacterCollection
    _ = CTCharacterCollection.kCTAdobeJapan1CharacterCollection
    _ = CTCharacterCollection.kCTAdobeJapan2CharacterCollection
    _ = CTCharacterCollection.kCTAdobeKorea1CharacterCollection
    precondition(CTCharacterCollection.identityMapping != CTCharacterCollection.adobeCNS1)
    _ = CTFontDescriptorMatchingState.didBegin.rawValue
    _ = CTFontDescriptorMatchingState.didBegin
    _ = CTFontDescriptorMatchingState.didFinish
    _ = CTFontDescriptorMatchingState.willBeginQuerying
    _ = CTFontDescriptorMatchingState.stalled
    _ = CTFontDescriptorMatchingState.willBeginDownloading
    _ = CTFontDescriptorMatchingState.downloading
    _ = CTFontDescriptorMatchingState.didFinishDownloading
    _ = CTFontDescriptorMatchingState.didMatch
    _ = CTFontDescriptorMatchingState.didFailWithError
    precondition(CTFontDescriptorMatchingState.didBegin != CTFontDescriptorMatchingState.didFinish)
    _ = CTFontFormat.unrecognized.rawValue
    _ = CTFontFormat.unrecognized
    _ = CTFontFormat.openTypePostScript
    _ = CTFontFormat.openTypeTrueType
    _ = CTFontFormat.trueType
    _ = CTFontFormat.postScript
    _ = CTFontFormat.bitmap
    precondition(CTFontFormat.unrecognized != CTFontFormat.openTypePostScript)
    _ = CTFontManagerAutoActivationSetting.default.rawValue
    _ = CTFontManagerAutoActivationSetting.default
    _ = CTFontManagerAutoActivationSetting.disabled
    _ = CTFontManagerAutoActivationSetting.enabled
    precondition(CTFontManagerAutoActivationSetting.default != CTFontManagerAutoActivationSetting.disabled)
    _ = CTFontOrientation.default.rawValue
    _ = CTFontOrientation.default
    _ = CTFontOrientation.horizontal
    _ = CTFontOrientation.vertical
    _ = CTFontOrientation.kCTFontDefaultOrientation
    _ = CTFontOrientation.kCTFontHorizontalOrientation
    _ = CTFontOrientation.kCTFontVerticalOrientation
    precondition(CTFontOrientation.default != CTFontOrientation.horizontal)
    _ = CTFontUIFontType.none.rawValue
    _ = CTFontUIFontType.none
    _ = CTFontUIFontType.user
    _ = CTFontUIFontType.userFixedPitch
    _ = CTFontUIFontType.system
    _ = CTFontUIFontType.emphasizedSystem
    _ = CTFontUIFontType.smallSystem
    _ = CTFontUIFontType.smallEmphasizedSystem
    _ = CTFontUIFontType.miniSystem
    _ = CTFontUIFontType.miniEmphasizedSystem
    _ = CTFontUIFontType.views
    _ = CTFontUIFontType.application
    _ = CTFontUIFontType.label
    _ = CTFontUIFontType.menuTitle
    _ = CTFontUIFontType.menuItem
    _ = CTFontUIFontType.menuItemMark
    _ = CTFontUIFontType.menuItemCmdKey
    _ = CTFontUIFontType.windowTitle
    _ = CTFontUIFontType.pushButton
    _ = CTFontUIFontType.utilityWindowTitle
    _ = CTFontUIFontType.alertHeader
    _ = CTFontUIFontType.systemDetail
    _ = CTFontUIFontType.emphasizedSystemDetail
    _ = CTFontUIFontType.toolbar
    _ = CTFontUIFontType.smallToolbar
    _ = CTFontUIFontType.message
    _ = CTFontUIFontType.palette
    _ = CTFontUIFontType.toolTip
    _ = CTFontUIFontType.controlContent
    _ = CTFontUIFontType.kCTFontNoFontType
    _ = CTFontUIFontType.kCTFontUserFontType
    _ = CTFontUIFontType.kCTFontUserFixedPitchFontType
    _ = CTFontUIFontType.kCTFontSystemFontType
    _ = CTFontUIFontType.kCTFontEmphasizedSystemFontType
    _ = CTFontUIFontType.kCTFontSmallSystemFontType
    _ = CTFontUIFontType.kCTFontSmallEmphasizedSystemFontType
    _ = CTFontUIFontType.kCTFontMiniSystemFontType
    _ = CTFontUIFontType.kCTFontMiniEmphasizedSystemFontType
    _ = CTFontUIFontType.kCTFontViewsFontType
    _ = CTFontUIFontType.kCTFontApplicationFontType
    _ = CTFontUIFontType.kCTFontLabelFontType
    _ = CTFontUIFontType.kCTFontMenuTitleFontType
    _ = CTFontUIFontType.kCTFontMenuItemFontType
    _ = CTFontUIFontType.kCTFontMenuItemMarkFontType
    _ = CTFontUIFontType.kCTFontMenuItemCmdKeyFontType
    _ = CTFontUIFontType.kCTFontWindowTitleFontType
    _ = CTFontUIFontType.kCTFontPushButtonFontType
    _ = CTFontUIFontType.kCTFontUtilityWindowTitleFontType
    _ = CTFontUIFontType.kCTFontAlertHeaderFontType
    _ = CTFontUIFontType.kCTFontSystemDetailFontType
    _ = CTFontUIFontType.kCTFontEmphasizedSystemDetailFontType
    _ = CTFontUIFontType.kCTFontToolbarFontType
    _ = CTFontUIFontType.kCTFontSmallToolbarFontType
    _ = CTFontUIFontType.kCTFontMessageFontType
    _ = CTFontUIFontType.kCTFontPaletteFontType
    _ = CTFontUIFontType.kCTFontToolTipFontType
    _ = CTFontUIFontType.kCTFontControlContentFontType
    precondition(CTFontUIFontType.none != CTFontUIFontType.user)
    _ = CTFramePathFillRule.evenOdd.rawValue
    _ = CTFramePathFillRule.evenOdd
    _ = CTFramePathFillRule.windingNumber
    precondition(CTFramePathFillRule.evenOdd != CTFramePathFillRule.windingNumber)
    _ = CTFrameProgression.topToBottom.rawValue
    _ = CTFrameProgression.topToBottom
    _ = CTFrameProgression.rightToLeft
    _ = CTFrameProgression.leftToRight
    precondition(CTFrameProgression.topToBottom != CTFrameProgression.rightToLeft)
    _ = CTLineBreakMode.byWordWrapping.rawValue
    _ = CTLineBreakMode.byWordWrapping
    _ = CTLineBreakMode.byCharWrapping
    _ = CTLineBreakMode.byClipping
    _ = CTLineBreakMode.byTruncatingHead
    _ = CTLineBreakMode.byTruncatingTail
    _ = CTLineBreakMode.byTruncatingMiddle
    precondition(CTLineBreakMode.byWordWrapping != CTLineBreakMode.byCharWrapping)
    _ = CTLineTruncationType.start.rawValue
    _ = CTLineTruncationType.start
    _ = CTLineTruncationType.end
    _ = CTLineTruncationType.middle
    precondition(CTLineTruncationType.start != CTLineTruncationType.end)
    _ = CTParagraphStyleSpecifier.alignment.rawValue
    _ = CTParagraphStyleSpecifier.alignment
    _ = CTParagraphStyleSpecifier.firstLineHeadIndent
    _ = CTParagraphStyleSpecifier.headIndent
    _ = CTParagraphStyleSpecifier.tailIndent
    _ = CTParagraphStyleSpecifier.tabStops
    _ = CTParagraphStyleSpecifier.defaultTabInterval
    _ = CTParagraphStyleSpecifier.lineBreakMode
    _ = CTParagraphStyleSpecifier.lineHeightMultiple
    _ = CTParagraphStyleSpecifier.maximumLineHeight
    _ = CTParagraphStyleSpecifier.minimumLineHeight
    _ = CTParagraphStyleSpecifier.paragraphSpacing
    _ = CTParagraphStyleSpecifier.paragraphSpacingBefore
    _ = CTParagraphStyleSpecifier.baseWritingDirection
    _ = CTParagraphStyleSpecifier.maximumLineSpacing
    _ = CTParagraphStyleSpecifier.minimumLineSpacing
    _ = CTParagraphStyleSpecifier.lineSpacingAdjustment
    _ = CTParagraphStyleSpecifier.lineBoundsOptions
    _ = CTParagraphStyleSpecifier.count
    precondition(CTParagraphStyleSpecifier.alignment != CTParagraphStyleSpecifier.firstLineHeadIndent)
    _ = CTRubyAlignment.invalid.rawValue
    _ = CTRubyAlignment.invalid
    _ = CTRubyAlignment.auto
    _ = CTRubyAlignment.start
    _ = CTRubyAlignment.center
    _ = CTRubyAlignment.end
    _ = CTRubyAlignment.distributeLetter
    _ = CTRubyAlignment.distributeSpace
    _ = CTRubyAlignment.lineEdge
    precondition(CTRubyAlignment.invalid != CTRubyAlignment.auto)
    _ = CTRubyOverhang.invalid.rawValue
    _ = CTRubyOverhang.invalid
    _ = CTRubyOverhang.auto
    _ = CTRubyOverhang.start
    _ = CTRubyOverhang.end
    _ = CTRubyOverhang.none
    precondition(CTRubyOverhang.invalid != CTRubyOverhang.auto)
    _ = CTRubyPosition.before.rawValue
    _ = CTRubyPosition.before
    _ = CTRubyPosition.after
    _ = CTRubyPosition.interCharacter
    _ = CTRubyPosition.inline
    _ = CTRubyPosition.count
    precondition(CTRubyPosition.before != CTRubyPosition.after)
    _ = CTTextAlignment.left.rawValue
    _ = CTTextAlignment.left
    _ = CTTextAlignment.right
    _ = CTTextAlignment.center
    _ = CTTextAlignment.justified
    _ = CTTextAlignment.natural
    _ = CTTextAlignment.kCTLeftTextAlignment
    _ = CTTextAlignment.kCTRightTextAlignment
    _ = CTTextAlignment.kCTCenterTextAlignment
    _ = CTTextAlignment.kCTJustifiedTextAlignment
    _ = CTTextAlignment.kCTNaturalTextAlignment
    precondition(CTTextAlignment.left != CTTextAlignment.right)
    _ = CTWritingDirection.natural.rawValue
    _ = CTWritingDirection.natural
    _ = CTWritingDirection.leftToRight
    _ = CTWritingDirection.rightToLeft
    precondition(CTWritingDirection.natural != CTWritingDirection.leftToRight)
    _ = CTFontManagerScope.none.rawValue
    _ = CTFontManagerScope.none
    _ = CTFontManagerScope.process
    _ = CTFontManagerScope.persistent
    _ = CTFontManagerScope.session
    _ = CTFontManagerScope.user
    precondition(CTFontManagerScope.none != CTFontManagerScope.process)
    _ = CTFontManagerError.fileNotFound.rawValue
    _ = CTFontManagerError.fileNotFound
    _ = CTFontManagerError.insufficientPermissions
    _ = CTFontManagerError.unrecognizedFormat
    _ = CTFontManagerError.invalidFontData
    _ = CTFontManagerError.alreadyRegistered
    _ = CTFontManagerError.exceededResourceLimit
    _ = CTFontManagerError.assetNotFound
    _ = CTFontManagerError.notRegistered
    _ = CTFontManagerError.inUse
    _ = CTFontManagerError.systemRequired
    _ = CTFontManagerError.registrationFailed
    _ = CTFontManagerError.missingEntitlement
    _ = CTFontManagerError.insufficientInfo
    _ = CTFontManagerError.cancelledByUser
    _ = CTFontManagerError.duplicatedName
    _ = CTFontManagerError.invalidFilePath
    _ = CTFontManagerError.unsupportedScope
    precondition(CTFontManagerError.fileNotFound != CTFontManagerError.insufficientPermissions)

    _ = CTFontCollectionCopyOptions().rawValue
    _ = CTFontCollectionCopyOptions.unique.rawValue
    _ = CTFontCollectionCopyOptions.standardSort.rawValue
    precondition(CTFontCollectionCopyOptions.unique != CTFontCollectionCopyOptions.standardSort)
    _ = CTFontOptions().rawValue
    _ = CTFontOptions.preventAutoActivation.rawValue
    _ = CTFontOptions.preventAutoDownload.rawValue
    _ = CTFontOptions.preferSystemFont.rawValue
    precondition(CTFontOptions.preventAutoActivation != CTFontOptions.preventAutoDownload)
    _ = CTFontSymbolicTraits().rawValue
    _ = CTFontSymbolicTraits.italicTrait.rawValue
    _ = CTFontSymbolicTraits.boldTrait.rawValue
    _ = CTFontSymbolicTraits.expandedTrait.rawValue
    _ = CTFontSymbolicTraits.condensedTrait.rawValue
    _ = CTFontSymbolicTraits.monoSpaceTrait.rawValue
    _ = CTFontSymbolicTraits.verticalTrait.rawValue
    _ = CTFontSymbolicTraits.uiOptimizedTrait.rawValue
    _ = CTFontSymbolicTraits.colorGlyphsTrait.rawValue
    _ = CTFontSymbolicTraits.compositeTrait.rawValue
    _ = CTFontSymbolicTraits.classMaskTrait.rawValue
    _ = CTFontSymbolicTraits.traitItalic.rawValue
    _ = CTFontSymbolicTraits.traitBold.rawValue
    _ = CTFontSymbolicTraits.traitExpanded.rawValue
    _ = CTFontSymbolicTraits.traitCondensed.rawValue
    _ = CTFontSymbolicTraits.traitMonoSpace.rawValue
    _ = CTFontSymbolicTraits.traitVertical.rawValue
    _ = CTFontSymbolicTraits.traitUIOptimized.rawValue
    _ = CTFontSymbolicTraits.traitColorGlyphs.rawValue
    _ = CTFontSymbolicTraits.traitComposite.rawValue
    _ = CTFontSymbolicTraits.traitClassMask.rawValue
    precondition(CTFontSymbolicTraits.italicTrait != CTFontSymbolicTraits.boldTrait)
    _ = CTFontStylisticClass().rawValue
    _ = CTFontStylisticClass.oldStyleSerifsClass.rawValue
    _ = CTFontStylisticClass.transitionalSerifsClass.rawValue
    _ = CTFontStylisticClass.modernSerifsClass.rawValue
    _ = CTFontStylisticClass.clarendonSerifsClass.rawValue
    _ = CTFontStylisticClass.slabSerifsClass.rawValue
    _ = CTFontStylisticClass.freeformSerifsClass.rawValue
    _ = CTFontStylisticClass.sansSerifClass.rawValue
    _ = CTFontStylisticClass.ornamentalsClass.rawValue
    _ = CTFontStylisticClass.scriptsClass.rawValue
    _ = CTFontStylisticClass.symbolicClass.rawValue
    _ = CTFontStylisticClass.classOldStyleSerifs.rawValue
    _ = CTFontStylisticClass.classTransitionalSerifs.rawValue
    _ = CTFontStylisticClass.classModernSerifs.rawValue
    _ = CTFontStylisticClass.classClarendonSerifs.rawValue
    _ = CTFontStylisticClass.classSlabSerifs.rawValue
    _ = CTFontStylisticClass.classFreeformSerifs.rawValue
    _ = CTFontStylisticClass.classSansSerif.rawValue
    _ = CTFontStylisticClass.classOrnamentals.rawValue
    _ = CTFontStylisticClass.classScripts.rawValue
    _ = CTFontStylisticClass.classSymbolic.rawValue
    precondition(CTFontStylisticClass.oldStyleSerifsClass != CTFontStylisticClass.transitionalSerifsClass)
    _ = CTFontTableOptions().rawValue
    _ = CTLineBoundsOptions().rawValue
    _ = CTLineBoundsOptions.excludeTypographicLeading.rawValue
    _ = CTLineBoundsOptions.excludeTypographicShifts.rawValue
    _ = CTLineBoundsOptions.useHangingPunctuation.rawValue
    _ = CTLineBoundsOptions.useGlyphPathBounds.rawValue
    _ = CTLineBoundsOptions.useOpticalBounds.rawValue
    _ = CTLineBoundsOptions.includeLanguageExtents.rawValue
    precondition(CTLineBoundsOptions.excludeTypographicLeading != CTLineBoundsOptions.excludeTypographicShifts)
    _ = CTRunStatus().rawValue
    _ = CTRunStatus.rightToLeft.rawValue
    _ = CTRunStatus.nonMonotonic.rawValue
    _ = CTRunStatus.hasNonIdentityMatrix.rawValue
    precondition(CTRunStatus.rightToLeft != CTRunStatus.nonMonotonic)
    _ = CTUnderlineStyle().rawValue
    _ = CTUnderlineStyle.single.rawValue
    _ = CTUnderlineStyle.thick.rawValue
    _ = CTUnderlineStyle.double.rawValue
    precondition(CTUnderlineStyle.single != CTUnderlineStyle.thick)
    _ = CTUnderlineStyleModifiers().rawValue
    _ = CTUnderlineStyleModifiers.patternDot.rawValue
    _ = CTUnderlineStyleModifiers.patternDash.rawValue
    _ = CTUnderlineStyleModifiers.patternDashDot.rawValue
    _ = CTUnderlineStyleModifiers.patternDashDotDot.rawValue
    _ = CTUnderlineStyleModifiers.patternSolid.rawValue
    precondition(CTUnderlineStyleModifiers.patternDot != CTUnderlineStyleModifiers.patternDash)
    var traits: CTFontSymbolicTraits = []
    let inserted = traits.insert(.boldTrait)
    precondition(inserted.inserted)
    precondition(traits.contains(.boldTrait))
    _ = traits.update(with: .italicTrait)
    _ = traits.remove(.boldTrait)
    precondition(traits.union(.monoSpaceTrait).contains(.monoSpaceTrait))
    precondition(traits.intersection(.italicTrait).contains(.italicTrait))
    _ = traits.symmetricDifference(.colorGlyphsTrait)
    var options: CTFontOptions = [.preventAutoActivation]
    options.formUnion(.preferSystemFont)
    precondition(!options.isDisjoint(with: .preferSystemFont))
    precondition(CTFontOptions.preventAutoActivation.isSubset(of: [.preventAutoActivation, .preferSystemFont]))
    precondition(CTFontCollectionCopyOptions.unique.union(.standardSort).contains(.standardSort))
    precondition(CTLineBoundsOptions.excludeTypographicLeading.isSuperset(of: []))
    precondition(CTRunStatus.rightToLeft.contains(.rightToLeft))
}

func testCatalogIntegerConstants() {
    _ = kCTFontTableAcnt
    _ = kCTFontTableAnkr
    _ = kCTFontTableAvar
    _ = kCTFontTableBASE
    _ = kCTFontTableBdat
    _ = kCTFontTableBhed
    _ = kCTFontTableBloc
    _ = kCTFontTableBsln
    _ = kCTFontTableCBDT
    _ = kCTFontTableCBLC
    _ = kCTFontTableCFF
    _ = kCTFontTableCFF2
    _ = kCTFontTableCOLR
    _ = kCTFontTableCPAL
    _ = kCTFontTableCidg
    _ = kCTFontTableCmap
    _ = kCTFontTableCvar
    _ = kCTFontTableCvt
    _ = kCTFontTableDSIG
    _ = kCTFontTableEBDT
    _ = kCTFontTableEBLC
    _ = kCTFontTableEBSC
    _ = kCTFontTableFdsc
    _ = kCTFontTableFeat
    _ = kCTFontTableFmtx
    _ = kCTFontTableFond
    _ = kCTFontTableFpgm
    _ = kCTFontTableFvar
    _ = kCTFontTableGDEF
    _ = kCTFontTableGPOS
    _ = kCTFontTableGSUB
    _ = kCTFontTableGasp
    _ = kCTFontTableGlyf
    _ = kCTFontTableGvar
    _ = kCTFontTableHVAR
    _ = kCTFontTableHdmx
    _ = kCTFontTableHead
    _ = kCTFontTableHhea
    _ = kCTFontTableHmtx
    _ = kCTFontTableHsty
    _ = kCTFontTableJSTF
    _ = kCTFontTableJust
    _ = kCTFontTableKern
    _ = kCTFontTableKerx
    _ = kCTFontTableLTSH
    _ = kCTFontTableLcar
    _ = kCTFontTableLoca
    _ = kCTFontTableLtag
    _ = kCTFontTableMATH
    _ = kCTFontTableMERG
    _ = kCTFontTableMVAR
    _ = kCTFontTableMaxp
    _ = kCTFontTableMeta
    _ = kCTFontTableMort
    _ = kCTFontTableMorx
    _ = kCTFontTableName
    _ = kCTFontTableOS2
    _ = kCTFontTableOpbd
    _ = kCTFontTablePCLT
    _ = kCTFontTablePost
    _ = kCTFontTablePrep
    _ = kCTFontTableProp
    _ = kCTFontTableSTAT
    _ = kCTFontTableSVG
    _ = kCTFontTableSbit
    _ = kCTFontTableSbix
    _ = kCTFontTableTrak
    _ = kCTFontTableVDMX
    _ = kCTFontTableVORG
    _ = kCTFontTableVVAR
    _ = kCTFontTableVhea
    _ = kCTFontTableVmtx
    _ = kCTFontTableXref
    _ = kCTFontTableZapf
    _ = kAllTypographicFeaturesType
    _ = kAlternateKanaType
    _ = kAnnotationType
    _ = kCJKRomanSpacingType
    _ = kCJKSymbolAlternativesType
    _ = kCJKVerticalRomanPlacementType
    _ = kCaseSensitiveLayoutType
    _ = kCharacterAlternativesType
    _ = kCharacterShapeType
    _ = kContextualAlternatesType
    _ = kCursiveConnectionType
    _ = kDesignComplexityType
    _ = kDiacriticsType
    _ = kFractionsType
    _ = kIdeographicAlternativesType
    _ = kIdeographicSpacingType
    _ = kItalicCJKRomanType
    _ = kKanaSpacingType
    _ = kLanguageTagType
    _ = kLetterCaseType
    _ = kLigaturesType
    _ = kLinguisticRearrangementType
    _ = kLowerCaseType
    _ = kMathematicalExtrasType
    _ = kNumberCaseType
    _ = kNumberSpacingType
    _ = kOrnamentSetsType
    _ = kOverlappingCharactersType
    _ = kRubyKanaType
    _ = kSmartSwashType
    _ = kStyleOptionsType
    _ = kStylisticAlternativesType
    _ = kTextSpacingType
    _ = kTransliterationType
    _ = kTypographicExtrasType
    _ = kUnicodeDecompositionType
    _ = kUpperCaseType
    _ = kVerticalPositionType
    _ = kVerticalSubstitutionType
    _ = kCTVersionNumber10_10
    _ = kCTVersionNumber10_11
    _ = kCTVersionNumber10_12
    _ = kCTVersionNumber10_13
    _ = kCTVersionNumber10_14
    _ = kCTVersionNumber10_15
    _ = kCTVersionNumber10_5
    _ = kCTVersionNumber10_5_2
    _ = kCTVersionNumber10_5_3
    _ = kCTVersionNumber10_5_5
    _ = kCTVersionNumber10_6
    _ = kCTVersionNumber10_7
    _ = kCTVersionNumber10_8
    _ = kCTVersionNumber10_9
    _ = kCTVersionNumber11_0
    _ = kCTFontPriorityComputer
    _ = kCTFontPriorityDynamic
    _ = kCTFontPriorityNetwork
    _ = kCTFontPriorityProcess
    _ = kCTFontPrioritySystem
    _ = kCTFontPriorityUser
    _ = kCTFontClassMaskShift
    _ = kCTRunDelegateCurrentVersion
    _ = kCTRunDelegateVersion1
    _ = kAbbrevSquaredLigaturesOffSelector
    _ = kAbbrevSquaredLigaturesOnSelector
    _ = kAllCapsSelector
    _ = kAllLowerCaseSelector
    _ = kAllTypeFeaturesOffSelector
    _ = kAllTypeFeaturesOnSelector
    _ = kAltHalfWidthTextSelector
    _ = kAltProportionalTextSelector
    _ = kAlternateHorizKanaOffSelector
    _ = kAlternateHorizKanaOnSelector
    _ = kAlternateVertKanaOffSelector
    _ = kAlternateVertKanaOnSelector
    _ = kAsteriskToMultiplyOffSelector
    _ = kAsteriskToMultiplyOnSelector
    _ = kBoxAnnotationSelector
    _ = kCJKItalicRomanOffSelector
    _ = kCJKItalicRomanOnSelector
    _ = kCJKItalicRomanSelector
    _ = kCJKSymbolAltFiveSelector
    _ = kCJKSymbolAltFourSelector
    _ = kCJKSymbolAltOneSelector
    _ = kCJKSymbolAltThreeSelector
    _ = kCJKSymbolAltTwoSelector
    _ = kCJKVerticalRomanCenteredSelector
    _ = kCJKVerticalRomanHBaselineSelector
    _ = kCanonicalCompositionOffSelector
    _ = kCanonicalCompositionOnSelector
    _ = kCaseSensitiveLayoutOffSelector
    _ = kCaseSensitiveLayoutOnSelector
    _ = kCaseSensitiveSpacingOffSelector
    _ = kCaseSensitiveSpacingOnSelector
    _ = kCircleAnnotationSelector
    _ = kCommonLigaturesOffSelector
    _ = kCommonLigaturesOnSelector
    _ = kCompatibilityCompositionOffSelector
    _ = kCompatibilityCompositionOnSelector
    _ = kContextualAlternatesOffSelector
    _ = kContextualAlternatesOnSelector
    _ = kContextualLigaturesOffSelector
    _ = kContextualLigaturesOnSelector
    _ = kContextualSwashAlternatesOffSelector
    _ = kContextualSwashAlternatesOnSelector
    _ = kCursiveSelector
    _ = kDecomposeDiacriticsSelector
    _ = kDecorativeBordersSelector
    _ = kDefaultCJKRomanSelector
    _ = kDefaultLowerCaseSelector
    _ = kDefaultUpperCaseSelector
    _ = kDesignLevel1Selector
    _ = kDesignLevel2Selector
    _ = kDesignLevel3Selector
    _ = kDesignLevel4Selector
    _ = kDesignLevel5Selector
    _ = kDiagonalFractionsSelector
    _ = kDiamondAnnotationSelector
    _ = kDingbatsSelector
    _ = kDiphthongLigaturesOffSelector
    _ = kDiphthongLigaturesOnSelector
    _ = kDisplayTextSelector
    _ = kEngravedTextSelector
    _ = kExpertCharactersSelector
    _ = kExponentsOffSelector
    _ = kExponentsOnSelector
    _ = kFleuronsSelector
    _ = kFormInterrobangOffSelector
    _ = kFormInterrobangOnSelector
    _ = kFullWidthCJKRomanSelector
    _ = kFullWidthIdeographsSelector
    _ = kFullWidthKanaSelector
    _ = kHalfWidthCJKRomanSelector
    _ = kHalfWidthIdeographsSelector
    _ = kHalfWidthTextSelector
    _ = kHanjaToHangulAltOneSelector
    _ = kHanjaToHangulAltThreeSelector
    _ = kHanjaToHangulAltTwoSelector
    _ = kHanjaToHangulSelector
    _ = kHideDiacriticsSelector
    _ = kHiraganaToKatakanaSelector
    _ = kHistoricalLigaturesOffSelector
    _ = kHistoricalLigaturesOnSelector
    _ = kHojoCharactersSelector
    _ = kHyphenToEnDashOffSelector
    _ = kHyphenToEnDashOnSelector
    _ = kHyphenToMinusOffSelector
    _ = kHyphenToMinusOnSelector
    _ = kHyphensToEmDashOffSelector
    _ = kHyphensToEmDashOnSelector
    _ = kIdeographicAltFiveSelector
    _ = kIdeographicAltFourSelector
    _ = kIdeographicAltOneSelector
    _ = kIdeographicAltThreeSelector
    _ = kIdeographicAltTwoSelector
    _ = kIlluminatedCapsSelector
    _ = kInequalityLigaturesOffSelector
    _ = kInequalityLigaturesOnSelector
    _ = kInferiorsSelector
    _ = kInitialCapsAndSmallCapsSelector
    _ = kInitialCapsSelector
    _ = kInternationalSymbolsSelector
    _ = kInvertedBoxAnnotationSelector
    _ = kInvertedCircleAnnotationSelector
    _ = kInvertedRoundedBoxAnnotationSelector
    _ = kJIS1978CharactersSelector
    _ = kJIS1983CharactersSelector
    _ = kJIS1990CharactersSelector
    _ = kJIS2004CharactersSelector
    _ = kKanaToRomanizationSelector
    _ = kKatakanaToHiraganaSelector
    _ = kLineFinalSwashesOffSelector
    _ = kLineFinalSwashesOnSelector
    _ = kLineInitialSwashesOffSelector
    _ = kLineInitialSwashesOnSelector
    _ = kLinguisticRearrangementOffSelector
    _ = kLinguisticRearrangementOnSelector
    _ = kLogosOffSelector
    _ = kLogosOnSelector
    _ = kLowerCaseNumbersSelector
    _ = kLowerCasePetiteCapsSelector
    _ = kLowerCaseSmallCapsSelector
    _ = kMathSymbolsSelector
    _ = kMathematicalGreekOffSelector
    _ = kMathematicalGreekOnSelector
    _ = kMonospacedNumbersSelector
    _ = kMonospacedTextSelector
    _ = kNLCCharactersSelector
    _ = kNoAlternatesSelector
    _ = kNoAnnotationSelector
    _ = kNoCJKItalicRomanSelector
    _ = kNoCJKSymbolAlternativesSelector
    _ = kNoFractionsSelector
    _ = kNoIdeographicAlternativesSelector
    _ = kNoOrnamentsSelector
    _ = kNoRubyKanaSelector
    _ = kNoStyleOptionsSelector
    _ = kNoStylisticAlternatesSelector
    _ = kNoTransliterationSelector
    _ = kNonFinalSwashesOffSelector
    _ = kNonFinalSwashesOnSelector
    _ = kNormalPositionSelector
    _ = kOrdinalsSelector
    _ = kParenthesisAnnotationSelector
    _ = kPartiallyConnectedSelector
    _ = kPeriodAnnotationSelector
    _ = kPeriodsToEllipsisOffSelector
    _ = kPeriodsToEllipsisOnSelector
    _ = kPiCharactersSelector
    _ = kPreventOverlapOffSelector
    _ = kPreventOverlapOnSelector
    _ = kProportionalCJKRomanSelector
    _ = kProportionalIdeographsSelector
    _ = kProportionalKanaSelector
    _ = kProportionalNumbersSelector
    _ = kProportionalTextSelector
    _ = kQuarterWidthNumbersSelector
    _ = kQuarterWidthTextSelector
    _ = kRareLigaturesOffSelector
    _ = kRareLigaturesOnSelector
    _ = kRebusPicturesOffSelector
    _ = kRebusPicturesOnSelector
    _ = kRequiredLigaturesOffSelector
    _ = kRequiredLigaturesOnSelector
    _ = kRomanNumeralAnnotationSelector
    _ = kRomanizationToHiraganaSelector
    _ = kRomanizationToKatakanaSelector
    _ = kRoundedBoxAnnotationSelector
    _ = kRubyKanaOffSelector
    _ = kRubyKanaOnSelector
    _ = kRubyKanaSelector
    _ = kScientificInferiorsSelector
    _ = kShowDiacriticsSelector
    _ = kSimplifiedCharactersSelector
    _ = kSlashToDivideOffSelector
    _ = kSlashToDivideOnSelector
    _ = kSlashedZeroOffSelector
    _ = kSlashedZeroOnSelector
    _ = kSmallCapsSelector
    _ = kSmartQuotesOffSelector
    _ = kSmartQuotesOnSelector
    _ = kSquaredLigaturesOffSelector
    _ = kSquaredLigaturesOnSelector
    _ = kStylisticAltEightOffSelector
    _ = kStylisticAltEightOnSelector
    _ = kStylisticAltEighteenOffSelector
    _ = kStylisticAltEighteenOnSelector
    _ = kStylisticAltElevenOffSelector
    _ = kStylisticAltElevenOnSelector
    _ = kStylisticAltFifteenOffSelector
    _ = kStylisticAltFifteenOnSelector
    _ = kStylisticAltFiveOffSelector
    _ = kStylisticAltFiveOnSelector
    _ = kStylisticAltFourOffSelector
    _ = kStylisticAltFourOnSelector
    _ = kStylisticAltFourteenOffSelector
    _ = kStylisticAltFourteenOnSelector
    _ = kStylisticAltNineOffSelector
    _ = kStylisticAltNineOnSelector
    _ = kStylisticAltNineteenOffSelector
    _ = kStylisticAltNineteenOnSelector
    _ = kStylisticAltOneOffSelector
    _ = kStylisticAltOneOnSelector
    _ = kStylisticAltSevenOffSelector
    _ = kStylisticAltSevenOnSelector
    _ = kStylisticAltSeventeenOffSelector
    _ = kStylisticAltSeventeenOnSelector
    _ = kStylisticAltSixOffSelector
    _ = kStylisticAltSixOnSelector
    _ = kStylisticAltSixteenOffSelector
    _ = kStylisticAltSixteenOnSelector
    _ = kStylisticAltTenOffSelector
    _ = kStylisticAltTenOnSelector
    _ = kStylisticAltThirteenOffSelector
    _ = kStylisticAltThirteenOnSelector
    _ = kStylisticAltThreeOffSelector
    _ = kStylisticAltThreeOnSelector
    _ = kStylisticAltTwelveOffSelector
    _ = kStylisticAltTwelveOnSelector
    _ = kStylisticAltTwentyOffSelector
    _ = kStylisticAltTwentyOnSelector
    _ = kStylisticAltTwoOffSelector
    _ = kStylisticAltTwoOnSelector
    _ = kSubstituteVerticalFormsOffSelector
    _ = kSubstituteVerticalFormsOnSelector
    _ = kSuperiorsSelector
    _ = kSwashAlternatesOffSelector
    _ = kSwashAlternatesOnSelector
    _ = kSymbolLigaturesOffSelector
    _ = kSymbolLigaturesOnSelector
    _ = kTallCapsSelector
    _ = kThirdWidthNumbersSelector
    _ = kThirdWidthTextSelector
    _ = kTitlingCapsSelector
    _ = kTraditionalAltFiveSelector
    _ = kTraditionalAltFourSelector
    _ = kTraditionalAltOneSelector
    _ = kTraditionalAltThreeSelector
    _ = kTraditionalAltTwoSelector
    _ = kTraditionalCharactersSelector
    _ = kTraditionalNamesCharactersSelector
    _ = kTranscodingCompositionOffSelector
    _ = kTranscodingCompositionOnSelector
    _ = kUnconnectedSelector
    _ = kUpperAndLowerCaseSelector
    _ = kUpperCaseNumbersSelector
    _ = kUpperCasePetiteCapsSelector
    _ = kUpperCaseSmallCapsSelector
    _ = kVerticalFractionsSelector
    _ = kWordFinalSwashesOffSelector
    _ = kWordFinalSwashesOnSelector
    _ = kWordInitialSwashesOffSelector
    _ = kWordInitialSwashesOnSelector
    precondition(kCTVersionNumber10_5 == 131072)
    precondition(kCTVersionNumber11_0 == 851968)
    precondition(kCTFontTableHead == 1751474532)
}

func testCatalogTypealiasesAndSFNT() {
    let _: ATSFontRef = 0
    let _: BslnBaselineClass = 0
    let _: BslnTableFormat = 0
    let _: CTFontPriority = 0
    let _: CTFontTableTag = 0
    let _: FontLanguageCode = 0
    let _: FontNameCode = 0
    let _: FontPlatformCode = 0
    let _: FontScriptCode = 0
    let _: JustPCActionType = 0
    let _: JustPCUnconditionalAddAction = 0
    let _: JustificationFlags = 0
    let _: KernArrayOffset = 0
    let _: KernKerningValue = 0
    let _: KernSubtableInfo = 0
    let _: KernTableFormat = 0
    let _: KerxArrayOffset = 0
    let _: KerxSubtableCoverage = 0
    let _: MortLigatureActionEntry = 0
    let _: MortSubtableMaskFlags = 0
    let _: OpbdTableFormat = 0
    let _: PropCharProperties = 0
    let _: SFNTLookupKind = 0
    let _: SFNTLookupOffset = 0
    let _: SFNTLookupTableFormat = 0
    let _: SFNTLookupValue = 0
    let _: STClass = 0
    let _: STEntryIndex = 0
    let _: STXClass = 0
    let _: STXEntryIndex = 0
    let _: STXStateIndex = 0
    let _: TrakValue = 0
    let _: STXClassTable = STXClassTable()
    let _: BslnTablePtr? = nil
    let _: KernOffsetTablePtr? = nil
    let _: KernOrderedListEntryPtr? = nil
    let _: KernSubtableHeaderPtr? = nil
    let _: KernTableHeaderPtr? = nil
    let _: KernTableHeaderHandle? = nil
    let _: KerxOrderedListEntryPtr? = nil
    let _: KerxSubtableHeaderPtr? = nil
    let _: KerxTableHeaderPtr? = nil
    let _: KerxTableHeaderHandle? = nil
    let _: LcarCaretTablePtr? = nil
    let _: SFNTLookupTablePtr? = nil
    let _: SFNTLookupTableHandle? = nil
    let _: CTFontCollectionSortDescriptorsCallback = { _, _, _ in .compareEqualTo }
    let _: CTFontDescriptorProgressHandler = { _, _ in true }
    let _: CTRunDelegateDeallocateCallback = { _ in }
    let _: CTRunDelegateGetAscentCallback = { _ in 0 }
    let _: CTRunDelegateGetDescentCallback = { _ in 0 }
    let _: CTRunDelegateGetWidthCallback = { _ in 0 }
    var entry = ALMXGlyphEntry()
    entry.GlyphIndexOffset = 1
    precondition(entry.GlyphIndexOffset == 1)
    let _: CTFontCollection.Type = CTFontCollection.self
    let _: CTFrame.Type = CTFrame.self
    let _: CTFramesetter.Type = CTFramesetter.self
    let _: CTGlyphInfo.Type = CTGlyphInfo.self
    let _: CTLine.Type = CTLine.self
    let _: CTMutableFontCollection.Type = CTMutableFontCollection.self
    let _: CTParagraphStyle.Type = CTParagraphStyle.self
    let _: CTRubyAnnotation.Type = CTRubyAnnotation.self
    let _: CTRunDelegate.Type = CTRunDelegate.self
    let _: CTTextTab.Type = CTTextTab.self
    let _: CTTypesetter.Type = CTTypesetter.self
    let _: CTRun.Type = CTRun.self
    let _: CTFont.Type = CTFont.self
    let _: CTFontDescriptor.Type = CTFontDescriptor.self
    _ = ALMXHeader()
    _ = BslnBaselineRecord.self
}

