// swift-tools-version: 5.9
import PackageDescription

// Standalone verification package for ios-oss's fail-closed service shims.
// These are NOT in the monorepo manifest (the chain package generated by
// Tools/ingest/spm_app_chain.py links them by path — see
// docs/agent_reports/ios-oss-launch2-chain.json). None of them contains a
// working remote service: every network/SDK boundary reports failure,
// cancellation, nil or a dropped call, never a fabricated success.
//
// Module layout follows the pinned SDKs where the app spells a module name
// as a qualifier (`StripeApplePay.STPApplePayContext`,
// `StripePayments.STPPaymentMethod`) or relies on an umbrella re-export
// (`import Firebase` reaching `Crashlytics` and `RemoteConfig`).
//
// Kingfisher/ and Lottie/ are not services: they are fail-closed stand-ins
// for Kingfisher 8.5.0 (its pinned source selects its AppKit branch on the
// macOS target) and lottie-ios 4.5.1 (169 errors against OpenUIKit); see
// their file headers. KingfisherWebP builds on the Kingfisher stand-in.
//
// The `Stripe` umbrella (two `@_exported import`s) is verified here as the
// target `KickstarterStripe`: SwiftPM requires target names to be unique
// across the whole package graph, and the OpenUIKit package (../..) declares
// Eidolon's fail-closed `Stripe` target (Sources/EidolonServiceShims/Stripe).
// The ios-oss chain package builds the same directory as `Stripe` against a
// filtered view of the OpenUIKit manifest without Eidolon's targets
// (spm_app_chain.py "openuikit_manifest_filter").
let ui: [Target.Dependency] = [.product(name: "UIKit", package: "OpenUIKit")]

let package = Package(
    name: "KickstarterServiceShims",
    platforms: [.macOS(.v13)],
    products: [
        "Statsig", "FirebaseCore", "FirebaseAnalytics", "FirebaseCrashlytics", "FirebaseRemoteConfig",
        "Firebase", "FacebookCore", "FacebookLogin", "StripePayments", "StripeApplePay",
        "StripePaymentSheet", "BrazeKit", "BrazeUI", "Segment", "SegmentBrazeUI", "AlamofireImage",
        "KickstarterStripe", "Kingfisher", "KingfisherWebP", "Lottie",
    ].map { .library(name: $0, targets: [$0]) },
    dependencies: [
        .package(name: "OpenUIKit", path: "../.."),
    ],
    targets: [
        .target(name: "Statsig", path: "Statsig"),
        .target(name: "FirebaseCore", path: "FirebaseCore"),
        .target(name: "FirebaseAnalytics", dependencies: ["FirebaseCore"], path: "FirebaseAnalytics"),
        .target(name: "FirebaseCrashlytics", dependencies: ["FirebaseCore"], path: "FirebaseCrashlytics"),
        .target(name: "FirebaseRemoteConfig", dependencies: ["FirebaseCore"], path: "FirebaseRemoteConfig"),
        .target(name: "Firebase",
                dependencies: ["FirebaseCore", "FirebaseAnalytics", "FirebaseCrashlytics", "FirebaseRemoteConfig"],
                path: "Firebase"),
        .target(name: "FacebookCore", dependencies: ui, path: "FacebookCore"),
        .target(name: "FacebookLogin", dependencies: ["FacebookCore"] + ui, path: "FacebookLogin"),
        .target(name: "StripePayments", dependencies: ui, path: "StripePayments"),
        .target(name: "StripeApplePay", dependencies: ["StripePayments"], path: "StripeApplePay"),
        .target(name: "StripePaymentSheet", dependencies: ["StripePayments", "StripeApplePay"] + ui,
                path: "StripePaymentSheet"),
        .target(name: "BrazeKit", path: "BrazeKit"),
        .target(name: "BrazeUI", dependencies: ["BrazeKit"], path: "BrazeUI"),
        .target(name: "Segment", path: "Segment"),
        .target(name: "SegmentBrazeUI", dependencies: ["Segment", "BrazeKit", "BrazeUI"], path: "SegmentBrazeUI"),
        .target(name: "AlamofireImage", dependencies: ui, path: "AlamofireImage"),
        // The `Stripe` umbrella under a graph-unique target name (see above).
        .target(name: "KickstarterStripe", dependencies: ["StripePayments", "StripeApplePay"], path: "Stripe"),
        .target(name: "Kingfisher",
                dependencies: ui + [.product(name: "SwiftUI", package: "OpenUIKit")], path: "Kingfisher"),
        .target(name: "KingfisherWebP", dependencies: ["Kingfisher"], path: "KingfisherWebP"),
        // Fail-closed stand-in for lottie-ios 4.5.1 (see Lottie/Lottie.swift).
        .target(name: "Lottie", dependencies: ui, path: "Lottie"),
        .testTarget(
            name: "KickstarterServiceShimTests",
            dependencies: [
                "Statsig", "Firebase", "FacebookCore", "FacebookLogin", "StripeApplePay", "StripePaymentSheet",
                "BrazeKit", "BrazeUI", "Segment", "SegmentBrazeUI", "AlamofireImage",
                "KickstarterStripe", "Kingfisher", "KingfisherWebP", "Lottie",
            ] + ui,
            path: "Tests/KickstarterServiceShimTests"
        ),
    ]
)
