/// OpenAL scalar types and function-pointer aliases from the iPhoneOS Clang overlay.

public typealias ALCboolean = CChar
public typealias ALCbyte = CChar
public typealias ALCchar = CChar
public typealias ALCdouble = Double
public typealias ALCenum = Int32
public typealias ALCfloat = Float
public typealias ALCint = Int32
public typealias ALCshort = Int16
public typealias ALCsizei = Int32
public typealias ALCubyte = UInt8
public typealias ALCuint = UInt32
public typealias ALCushort = UInt16
public typealias ALboolean = CChar
public typealias ALbyte = CChar
public typealias ALchar = CChar
public typealias ALdouble = Double
public typealias ALenum = Int32
public typealias ALfloat = Float
public typealias ALint = Int32
public typealias ALshort = Int16
public typealias ALsizei = Int32
public typealias ALubyte = UInt8
public typealias ALuint = UInt32
public typealias ALushort = UInt16
public typealias LPALBUFFER3F = (ALuint, ALenum, ALfloat, ALfloat, ALfloat) -> Void
public typealias LPALBUFFER3I = (ALuint, ALenum, ALint, ALint, ALint) -> Void
public typealias LPALBUFFERDATA = (ALuint, ALenum, UnsafeRawPointer?, ALsizei, ALsizei) -> Void
public typealias LPALBUFFERF = (ALuint, ALenum, ALfloat) -> Void
public typealias LPALBUFFERFV = (ALuint, ALenum, UnsafePointer<ALfloat>?) -> Void
public typealias LPALBUFFERI = (ALuint, ALenum, ALint) -> Void
public typealias LPALBUFFERIV = (ALuint, ALenum, UnsafePointer<ALint>?) -> Void
public typealias LPALCCAPTURECLOSEDEVICE = (OpaquePointer?) -> ALCboolean
public typealias LPALCCAPTUREOPENDEVICE = (UnsafePointer<ALCchar>?, ALCuint, ALCenum, ALCsizei) -> OpaquePointer?
public typealias LPALCCAPTURESAMPLES = (OpaquePointer?, UnsafeMutableRawPointer?, ALCsizei) -> Void
public typealias LPALCCAPTURESTART = (OpaquePointer?) -> Void
public typealias LPALCCAPTURESTOP = (OpaquePointer?) -> Void
public typealias LPALCCLOSEDEVICE = (OpaquePointer?) -> ALCboolean
public typealias LPALCCREATECONTEXT = (OpaquePointer?, UnsafePointer<ALCint>?) -> OpaquePointer?
public typealias LPALCDESTROYCONTEXT = (OpaquePointer?) -> Void
public typealias LPALCGETCONTEXTSDEVICE = (OpaquePointer?) -> OpaquePointer?
public typealias LPALCGETCURRENTCONTEXT = () -> OpaquePointer?
public typealias LPALCGETENUMVALUE = (OpaquePointer?, UnsafePointer<ALCchar>?) -> ALCenum
public typealias LPALCGETERROR = (OpaquePointer?) -> ALCenum
public typealias LPALCGETINTEGERV = (OpaquePointer?, ALCenum, ALCsizei, UnsafeMutablePointer<ALCint>?) -> Void
public typealias LPALCGETPROCADDRESS = (OpaquePointer?, UnsafePointer<ALCchar>?) -> UnsafeMutableRawPointer?
public typealias LPALCGETSTRING = (OpaquePointer?, ALCenum) -> UnsafePointer<ALCchar>?
public typealias LPALCISEXTENSIONPRESENT = (OpaquePointer?, UnsafePointer<ALCchar>?) -> ALCboolean
public typealias LPALCMAKECONTEXTCURRENT = (OpaquePointer?) -> ALCboolean
public typealias LPALCOPENDEVICE = (UnsafePointer<ALCchar>?) -> OpaquePointer?
public typealias LPALCPROCESSCONTEXT = (OpaquePointer?) -> Void
public typealias LPALCSUSPENDCONTEXT = (OpaquePointer?) -> Void
public typealias LPALDELETEBUFFERS = (ALsizei, UnsafePointer<ALuint>?) -> Void
public typealias LPALDELETESOURCES = (ALsizei, UnsafePointer<ALuint>?) -> Void
public typealias LPALDISABLE = (ALenum) -> Void
public typealias LPALDISTANCEMODEL = (ALenum) -> Void
public typealias LPALDOPPLERFACTOR = (ALfloat) -> Void
public typealias LPALDOPPLERVELOCITY = (ALfloat) -> Void
public typealias LPALENABLE = (ALenum) -> Void
public typealias LPALGENBUFFERS = (ALsizei, UnsafeMutablePointer<ALuint>?) -> Void
public typealias LPALGENSOURCES = (ALsizei, UnsafeMutablePointer<ALuint>?) -> Void
public typealias LPALGETBOOLEAN = (ALenum) -> ALboolean
public typealias LPALGETBOOLEANV = (ALenum, UnsafeMutablePointer<ALboolean>?) -> Void
public typealias LPALGETBUFFER3F = (ALuint, ALenum, UnsafeMutablePointer<ALfloat>?, UnsafeMutablePointer<ALfloat>?, UnsafeMutablePointer<ALfloat>?) -> Void
public typealias LPALGETBUFFER3I = (ALuint, ALenum, UnsafeMutablePointer<ALint>?, UnsafeMutablePointer<ALint>?, UnsafeMutablePointer<ALint>?) -> Void
public typealias LPALGETBUFFERF = (ALuint, ALenum, UnsafeMutablePointer<ALfloat>?) -> Void
public typealias LPALGETBUFFERFV = (ALuint, ALenum, UnsafeMutablePointer<ALfloat>?) -> Void
public typealias LPALGETBUFFERI = (ALuint, ALenum, UnsafeMutablePointer<ALint>?) -> Void
public typealias LPALGETBUFFERIV = (ALuint, ALenum, UnsafeMutablePointer<ALint>?) -> Void
public typealias LPALGETDOUBLE = (ALenum) -> ALdouble
public typealias LPALGETDOUBLEV = (ALenum, UnsafeMutablePointer<ALdouble>?) -> Void
public typealias LPALGETENUMVALUE = (UnsafePointer<ALchar>?) -> ALenum
public typealias LPALGETERROR = () -> ALenum
public typealias LPALGETFLOAT = (ALenum) -> ALfloat
public typealias LPALGETFLOATV = (ALenum, UnsafeMutablePointer<ALfloat>?) -> Void
public typealias LPALGETINTEGER = (ALenum) -> ALint
public typealias LPALGETINTEGERV = (ALenum, UnsafeMutablePointer<ALint>?) -> Void
public typealias LPALGETLISTENER3F = (ALenum, UnsafeMutablePointer<ALfloat>?, UnsafeMutablePointer<ALfloat>?, UnsafeMutablePointer<ALfloat>?) -> Void
public typealias LPALGETLISTENER3I = (ALenum, UnsafeMutablePointer<ALint>?, UnsafeMutablePointer<ALint>?, UnsafeMutablePointer<ALint>?) -> Void
public typealias LPALGETLISTENERF = (ALenum, UnsafeMutablePointer<ALfloat>?) -> Void
public typealias LPALGETLISTENERFV = (ALenum, UnsafeMutablePointer<ALfloat>?) -> Void
public typealias LPALGETLISTENERI = (ALenum, UnsafeMutablePointer<ALint>?) -> Void
public typealias LPALGETLISTENERIV = (ALenum, UnsafeMutablePointer<ALint>?) -> Void
public typealias LPALGETPROCADDRESS = (UnsafePointer<ALchar>?) -> UnsafeMutableRawPointer?
public typealias LPALGETSOURCE3F = (ALuint, ALenum, UnsafeMutablePointer<ALfloat>?, UnsafeMutablePointer<ALfloat>?, UnsafeMutablePointer<ALfloat>?) -> Void
public typealias LPALGETSOURCE3I = (ALuint, ALenum, UnsafeMutablePointer<ALint>?, UnsafeMutablePointer<ALint>?, UnsafeMutablePointer<ALint>?) -> Void
public typealias LPALGETSOURCEF = (ALuint, ALenum, UnsafeMutablePointer<ALfloat>?) -> Void
public typealias LPALGETSOURCEFV = (ALuint, ALenum, UnsafeMutablePointer<ALfloat>?) -> Void
public typealias LPALGETSOURCEI = (ALuint, ALenum, UnsafeMutablePointer<ALint>?) -> Void
public typealias LPALGETSOURCEIV = (ALuint, ALenum, UnsafeMutablePointer<ALint>?) -> Void
public typealias LPALGETSTRING = (ALenum) -> UnsafePointer<ALchar>?
public typealias LPALISBUFFER = (ALuint) -> ALboolean
public typealias LPALISENABLED = (ALenum) -> ALboolean
public typealias LPALISEXTENSIONPRESENT = (UnsafePointer<ALchar>?) -> ALboolean
public typealias LPALISSOURCE = (ALuint) -> ALboolean
public typealias LPALLISTENER3F = (ALenum, ALfloat, ALfloat, ALfloat) -> Void
public typealias LPALLISTENER3I = (ALenum, ALint, ALint, ALint) -> Void
public typealias LPALLISTENERF = (ALenum, ALfloat) -> Void
public typealias LPALLISTENERFV = (ALenum, UnsafePointer<ALfloat>?) -> Void
public typealias LPALLISTENERI = (ALenum, ALint) -> Void
public typealias LPALLISTENERIV = (ALenum, UnsafePointer<ALint>?) -> Void
public typealias LPALSOURCE3F = (ALuint, ALenum, ALfloat, ALfloat, ALfloat) -> Void
public typealias LPALSOURCE3I = (ALuint, ALenum, ALint, ALint, ALint) -> Void
public typealias LPALSOURCEF = (ALuint, ALenum, ALfloat) -> Void
public typealias LPALSOURCEFV = (ALuint, ALenum, UnsafePointer<ALfloat>?) -> Void
public typealias LPALSOURCEI = (ALuint, ALenum, ALint) -> Void
public typealias LPALSOURCEIV = (ALuint, ALenum, UnsafePointer<ALint>?) -> Void
public typealias LPALSOURCEPAUSE = (ALuint) -> Void
public typealias LPALSOURCEPAUSEV = (ALsizei, UnsafePointer<ALuint>?) -> Void
public typealias LPALSOURCEPLAY = (ALuint) -> Void
public typealias LPALSOURCEPLAYV = (ALsizei, UnsafePointer<ALuint>?) -> Void
public typealias LPALSOURCEQUEUEBUFFERS = (ALuint, ALsizei, UnsafePointer<ALuint>?) -> Void
public typealias LPALSOURCEREWIND = (ALuint) -> Void
public typealias LPALSOURCEREWINDV = (ALsizei, UnsafePointer<ALuint>?) -> Void
public typealias LPALSOURCESTOP = (ALuint) -> Void
public typealias LPALSOURCESTOPV = (ALsizei, UnsafePointer<ALuint>?) -> Void
public typealias LPALSOURCEUNQUEUEBUFFERS = (ALuint, ALsizei, UnsafeMutablePointer<ALuint>?) -> Void
public typealias LPALSPEEDOFSOUND = (ALfloat) -> Void
public typealias alBufferDataStaticProcPtr = (ALint, ALenum, UnsafeRawPointer, ALsizei, ALsizei) -> Void
public typealias alMacOSXGetRenderChannelCountProcPtr = () -> ALint
public typealias alMacOSXRenderChannelCountProcPtr = (ALint) -> Void
public typealias alSourceAddNotificationProcPtr = (ALuint, ALuint, alSourceNotificationProc, UnsafeMutableRawPointer?) -> ALenum
public typealias alSourceGetRenderingQualityProcPtr = (ALuint) -> ALint
public typealias alSourceNotificationProc = (ALuint, ALuint, UnsafeMutableRawPointer?) -> Void
public typealias alSourceRemoveNotificationProcPtr = (ALuint, ALuint, alSourceNotificationProc, UnsafeMutableRawPointer?) -> Void
public typealias alSourceRenderingQualityProcPtr = (ALuint, ALint) -> Void
public typealias alcASAGetListenerProcPtr = (ALuint, UnsafeMutableRawPointer, UnsafeMutablePointer<ALuint>) -> ALenum
public typealias alcASAGetSourceProcPtr = (ALuint, ALuint, UnsafeMutableRawPointer, UnsafeMutablePointer<ALuint>) -> ALenum
public typealias alcASASetListenerProcPtr = (ALuint, UnsafeMutableRawPointer, ALuint) -> ALenum
public typealias alcASASetSourceProcPtr = (ALuint, ALuint, UnsafeMutableRawPointer, ALuint) -> ALenum
public typealias alcMacOSXGetMixerMaxiumumBussesProcPtr = () -> ALint
public typealias alcMacOSXGetMixerOutputRateProcPtr = () -> ALdouble
public typealias alcMacOSXGetRenderingQualityProcPtr = () -> ALint
public typealias alcMacOSXMixerMaxiumumBussesProcPtr = (ALint) -> Void
public typealias alcMacOSXMixerOutputRateProcPtr = (ALdouble) -> Void
public typealias alcMacOSXRenderingQualityProcPtr = (ALint) -> Void
public typealias alcOutputCapturerAvailableSamplesProcPtr = () -> ALint
public typealias alcOutputCapturerPrepareProcPtr = (ALCuint, ALCenum, ALCsizei) -> Void
public typealias alcOutputCapturerSamplesProcPtr = (UnsafeMutableRawPointer, ALCsizei) -> Void
public typealias alcOutputCapturerStartProcPtr = () -> Void
public typealias alcOutputCapturerStopProcPtr = () -> Void
