// GENERATED by scripts/gen_conformance_registry.sh — do not edit.
// Regenerating this file must change nothing (ConformanceRegistryTests).
// Source of truth: one-line ConformanceApps.register in each
// Sources/ConformanceApps/<App>/<App>App.swift, discovered by scanning
// that directory. MEASURED: the six existing apps (NavFlow, Forms,
// TableEditor, Feed, Modal, Tabs) keep byte-identical SKIP_CAPTURE=1 scores
// against /tmp/conformance-<App> goldens after switching openhost and
// confprobe onto this table.
import UIKit

extension ConformanceApps {
    /// App names in directory-scan order (sorted). Safe to read off the
    /// main actor — used by openhost's usage text and confprobe.
    public static let names: [String] = [
        "Feed",
        "Forms",
        "Ledger",
        "Modal",
        "NavFlow",
        "Notes",
        "Pager",
        "Present",
        "TableEditor",
        "Tabs",
        "TextKit",
    ]

    /// Force every app's one-line `static let _register<Name>` to run.
    /// Swift initialises those lets lazily; without this scan-driven
    /// list, `registry` would stay empty.
    @MainActor
    static func loadRegistry() {
        _ = _registerFeed
        _ = _registerForms
        _ = _registerLedger
        _ = _registerModal
        _ = _registerNavFlow
        _ = _registerNotes
        _ = _registerPager
        _ = _registerPresent
        _ = _registerTableEditor
        _ = _registerTabs
        _ = _registerTextKit
    }
}
