/* GENERATED by scripts/gen_ns_forwards.py -- do not edit.
 *
 * The Foundation classes CoreFoundation casts through in its ObjC
 * dispatch macros. Forward declarations only: the cast is a no-op at
 * runtime, since the object's real class is whatever __CFInitialize
 * registered for its typeID and CF never messages through the static
 * type. Declaring @interface bodies here would be a lie about classes
 * that live in src/nscf/.
 *
 * Derived from CF's own sources, never typed by hand -- a fixed list
 * drifts the moment corelibs adds a dispatch site, and drifts
 * silently.
 *
 * 25 classes.
 *
 * Excluded, because our own headers already define them as TYPES
 * and @class would be a redefinition rather than a duplicate:
 *   NSRange, NSUInteger
 */
#ifndef CF_NS_FORWARDS_H
#define CF_NS_FORWARDS_H
#if defined(__OBJC__)
@class NSArray;
@class NSAttributedString;
@class NSCalendar;
@class NSCharacterSet;
@class NSData;
@class NSDate;
@class NSDictionary;
@class NSError;
@class NSException;
@class NSInputStream;
@class NSLocale;
@class NSMutableArray;
@class NSMutableAttributedString;
@class NSMutableCharacterSet;
@class NSMutableData;
@class NSMutableDictionary;
@class NSMutableSet;
@class NSMutableString;
@class NSNumber;
@class NSOutputStream;
@class NSSet;
@class NSString;
@class NSTimeZone;
@class NSTimer;
@class NSURL;
#endif
#endif
