import Foundation

open class MTRBarrierControlClusterBarrierControlGoToPercentParams: NSObject {}
open class MTRBarrierControlClusterBarrierControlStopParams: NSObject {}
open class MTRBaseClusterBarrierControl: MTRGenericBaseCluster {}
open class MTRBaseClusterBinaryInputBasic: MTRGenericBaseCluster {}
open class MTRBaseClusterElectricalMeasurement: MTRGenericBaseCluster {}
open class MTRBaseClusterOnOffSwitchConfiguration: MTRGenericBaseCluster {}
open class MTRClusterBarrierControl: MTRGenericCluster {}
open class MTRClusterBinaryInputBasic: MTRGenericCluster {}
open class MTRClusterElectricalMeasurement: MTRGenericCluster {}
open class MTRClusterOnOffSwitchConfiguration: MTRGenericCluster {}
open class MTRElectricalMeasurementClusterGetMeasurementProfileCommandParams: NSObject {}
open class MTRElectricalMeasurementClusterGetMeasurementProfileResponseCommandParams: NSObject {}
open class MTRElectricalMeasurementClusterGetProfileInfoCommandParams: NSObject {}
open class MTRElectricalMeasurementClusterGetProfileInfoResponseCommandParams: NSObject {}
open class MTRAccessControlClusterAccessControlEntryChangedEvent: NSObject {}
open class MTRAccessControlClusterAccessControlEntryStruct: NSObject {}
open class MTRAccessControlClusterAccessControlExtensionChangedEvent: NSObject {}
open class MTRAccessControlClusterAccessControlExtensionStruct: NSObject {}
open class MTRAccessControlClusterAccessControlTargetStruct: NSObject {}
open class MTRAccessControlClusterAccessRestrictionEntryStruct: NSObject {}
open class MTRAccessControlClusterAccessRestrictionStruct: NSObject {}
open class MTRAccessControlClusterCommissioningAccessRestrictionEntryStruct: NSObject {}
open class MTRAccessControlClusterExtensionEntry: MTRAccessControlClusterAccessControlExtensionStruct {}
open class MTRAccessControlClusterFabricRestrictionReviewUpdateEvent: NSObject {}
open class MTRAccessControlClusterTarget: MTRAccessControlClusterAccessControlTargetStruct {}
open class MTRAccountLoginClusterLoggedOutEvent: NSObject {}
open class MTRActionsClusterActionFailedEvent: NSObject {}
open class MTRActionsClusterActionStruct: NSObject {}
open class MTRActionsClusterEndpointListStruct: NSObject {}
open class MTRActionsClusterStateChangedEvent: NSObject {}
open class MTRActivatedCarbonFilterMonitoringClusterReplacementProductStruct: NSObject {}
open class MTRApplicationBasicClusterApplicationStruct: NSObject {}
open class MTRApplicationLauncherClusterApplicationEPStruct: NSObject {}
open class MTRApplicationLauncherClusterApplicationStruct: NSObject {}
open class MTRAudioOutputClusterOutputInfoStruct: NSObject {}
open class MTRBasicInformationClusterCapabilityMinimaStruct: NSObject {}
open class MTRBasicInformationClusterLeaveEvent: NSObject {}
open class MTRBasicInformationClusterProductAppearanceStruct: NSObject {}
open class MTRBasicInformationClusterReachableChangedEvent: NSObject {}
open class MTRBasicInformationClusterShutDownEvent: NSObject {}
open class MTRBasicInformationClusterStartUpEvent: NSObject {}
open class MTRBindingClusterTargetStruct: NSObject {}
open class MTRBooleanStateClusterStateChangeEvent: NSObject {}
open class MTRBooleanStateConfigurationClusterAlarmsStateChangedEvent: NSObject {}
open class MTRBooleanStateConfigurationClusterSensorFaultEvent: NSObject {}
open class MTRBridgedDeviceBasicInformationClusterActiveChangedEvent: NSObject {}
open class MTRBridgedDeviceBasicInformationClusterLeaveEvent: NSObject {}
open class MTRBridgedDeviceBasicInformationClusterProductAppearanceStruct: NSObject {}
open class MTRBridgedDeviceBasicInformationClusterReachableChangedEvent: NSObject {}
open class MTRBridgedDeviceBasicInformationClusterShutDownEvent: NSObject {}
open class MTRBridgedDeviceBasicInformationClusterStartUpEvent: NSObject {}
open class MTRChannelClusterChannelInfoStruct: NSObject {}
open class MTRChannelClusterChannelPagingStruct: NSObject {}
open class MTRChannelClusterLineupInfoStruct: NSObject {}
open class MTRChannelClusterPageTokenStruct: NSObject {}
open class MTRChannelClusterProgramCastStruct: NSObject {}
open class MTRChannelClusterProgramCategoryStruct: NSObject {}
open class MTRChannelClusterProgramStruct: NSObject {}
open class MTRChannelClusterSeriesInfoStruct: NSObject {}
open class MTRCommissionerControlClusterCommissioningRequestResultEvent: NSObject {}
open class MTRContentLauncherClusterAdditionalInfoStruct: NSObject {}
open class MTRContentLauncherClusterBrandingInformationStruct: NSObject {}
open class MTRContentLauncherClusterContentSearchStruct: NSObject {}
open class MTRContentLauncherClusterDimensionStruct: NSObject {}
open class MTRContentLauncherClusterParameterStruct: NSObject {}
open class MTRContentLauncherClusterStyleInformationStruct: NSObject {}
open class MTRDataTypeAtomicAttributeStatusStruct: NSObject {}
open class MTRDataTypeLocationDescriptorStruct: NSObject {}
open class MTRDescriptorClusterDeviceTypeStruct: NSObject {}
open class MTRDeviceEnergyManagementClusterConstraintsStruct: NSObject {}
open class MTRDeviceEnergyManagementClusterCostStruct: NSObject {}
open class MTRDeviceEnergyManagementClusterForecastStruct: NSObject {}
open class MTRDeviceEnergyManagementClusterPausedEvent: NSObject {}
open class MTRDeviceEnergyManagementClusterPowerAdjustCapabilityStruct: NSObject {}
open class MTRDeviceEnergyManagementClusterPowerAdjustEndEvent: NSObject {}
open class MTRDeviceEnergyManagementClusterPowerAdjustStartEvent: NSObject {}
open class MTRDeviceEnergyManagementClusterPowerAdjustStruct: NSObject {}
open class MTRDeviceEnergyManagementClusterResumedEvent: NSObject {}
open class MTRDeviceEnergyManagementClusterSlotAdjustmentStruct: NSObject {}
open class MTRDeviceEnergyManagementClusterSlotStruct: NSObject {}
open class MTRDeviceEnergyManagementModeClusterModeOptionStruct: NSObject {}
open class MTRDeviceEnergyManagementModeClusterModeTagStruct: NSObject {}
open class MTRDishwasherAlarmClusterNotifyEvent: NSObject {}
open class MTRDishwasherModeClusterModeOptionStruct: NSObject {}
open class MTRDishwasherModeClusterModeTagStruct: NSObject {}
open class MTRDoorLockClusterCredentialStruct: NSObject {}
open class MTRDoorLockClusterDlCredential: MTRDoorLockClusterCredentialStruct {}
open class MTRDoorLockClusterDoorLockAlarmEvent: NSObject {}
open class MTRDoorLockClusterDoorStateChangeEvent: NSObject {}
open class MTRDoorLockClusterLockOperationErrorEvent: NSObject {}
open class MTRDoorLockClusterLockOperationEvent: NSObject {}
open class MTRDoorLockClusterLockUserChangeEvent: NSObject {}
open class MTRElectricalEnergyMeasurementClusterCumulativeEnergyMeasuredEvent: NSObject {}
open class MTRElectricalEnergyMeasurementClusterCumulativeEnergyResetStruct: NSObject {}
open class MTRElectricalEnergyMeasurementClusterEnergyMeasurementStruct: NSObject {}
open class MTRElectricalEnergyMeasurementClusterMeasurementAccuracyRangeStruct: NSObject {}
open class MTRElectricalEnergyMeasurementClusterMeasurementAccuracyStruct: NSObject {}
open class MTRElectricalEnergyMeasurementClusterPeriodicEnergyMeasuredEvent: NSObject {}
open class MTRElectricalPowerMeasurementClusterHarmonicMeasurementStruct: NSObject {}
open class MTRElectricalPowerMeasurementClusterMeasurementAccuracyRangeStruct: NSObject {}
open class MTRElectricalPowerMeasurementClusterMeasurementAccuracyStruct: NSObject {}
open class MTRElectricalPowerMeasurementClusterMeasurementPeriodRangesEvent: NSObject {}
open class MTRElectricalPowerMeasurementClusterMeasurementRangeStruct: NSObject {}
open class MTREnergyEVSEClusterChargingTargetScheduleStruct: NSObject {}
open class MTREnergyEVSEClusterChargingTargetStruct: NSObject {}
open class MTREnergyEVSEClusterEVConnectedEvent: NSObject {}
open class MTREnergyEVSEClusterEVNotDetectedEvent: NSObject {}
open class MTREnergyEVSEClusterEnergyTransferStartedEvent: NSObject {}
open class MTREnergyEVSEClusterEnergyTransferStoppedEvent: NSObject {}
open class MTREnergyEVSEClusterFaultEvent: NSObject {}
open class MTREnergyEVSEClusterRFIDEvent: NSObject {}
open class MTREnergyEVSEModeClusterModeOptionStruct: NSObject {}
open class MTREnergyEVSEModeClusterModeTagStruct: NSObject {}
open class MTRFixedLabelClusterLabelStruct: NSObject {}
open class MTRGeneralCommissioningClusterBasicCommissioningInfo: NSObject {}
open class MTRGeneralDiagnosticsClusterBootReasonEvent: NSObject {}
open class MTRGeneralDiagnosticsClusterHardwareFaultChangeEvent: NSObject {}
open class MTRGeneralDiagnosticsClusterNetworkFaultChangeEvent: NSObject {}
open class MTRGeneralDiagnosticsClusterNetworkInterface: NSObject {}
open class MTRGeneralDiagnosticsClusterNetworkInterfaceType: MTRGeneralDiagnosticsClusterNetworkInterface {}
open class MTRGeneralDiagnosticsClusterRadioFaultChangeEvent: NSObject {}
open class MTRGroupKeyManagementClusterGroupInfoMapStruct: NSObject {}
open class MTRGroupKeyManagementClusterGroupKeyMapStruct: NSObject {}
open class MTRGroupKeyManagementClusterGroupKeySetStruct: NSObject {}
open class MTRHEPAFilterMonitoringClusterReplacementProductStruct: NSObject {}
open class MTRICDManagementClusterMonitoringRegistrationStruct: NSObject {}
open class MTRLaundryWasherModeClusterModeOptionStruct: NSObject {}
open class MTRLaundryWasherModeClusterModeTagStruct: NSObject {}
open class MTRMediaInputClusterInputInfoStruct: NSObject {}
open class MTRMediaPlaybackClusterPlaybackPositionStruct: NSObject {}
open class MTRMediaPlaybackClusterStateChangedEvent: NSObject {}
open class MTRMessagesClusterMessageCompleteEvent: NSObject {}
open class MTRMessagesClusterMessagePresentedEvent: NSObject {}
open class MTRMessagesClusterMessageQueuedEvent: NSObject {}
open class MTRMessagesClusterMessageResponseOptionStruct: NSObject {}
open class MTRMessagesClusterMessageStruct: NSObject {}
open class MTRMicrowaveOvenModeClusterModeOptionStruct: NSObject {}
open class MTRMicrowaveOvenModeClusterModeTagStruct: NSObject {}
open class MTRModeSelectClusterModeOptionStruct: NSObject {}
open class MTRModeSelectClusterSemanticTagStruct: NSObject {}
open class MTRNetworkCommissioningClusterNetworkInfoStruct: NSObject {}
open class MTRNetworkCommissioningClusterThreadInterfaceScanResultStruct: NSObject {}
open class MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct: NSObject {}
open class MTROTASoftwareUpdateRequestorClusterDownloadErrorEvent: NSObject {}
open class MTROTASoftwareUpdateRequestorClusterProviderLocation: NSObject {}
open class MTROTASoftwareUpdateRequestorClusterStateTransitionEvent: NSObject {}
open class MTROTASoftwareUpdateRequestorClusterVersionAppliedEvent: NSObject {}
open class MTROccupancySensingClusterHoldTimeLimitsStruct: NSObject {}
open class MTROccupancySensingClusterOccupancyChangedEvent: NSObject {}
open class MTROperationalCredentialsClusterFabricDescriptorStruct: NSObject {}
open class MTROperationalCredentialsClusterNOCStruct: NSObject {}
open class MTROperationalStateClusterErrorStateStruct: NSObject {}
open class MTROperationalStateClusterOperationCompletionEvent: NSObject {}
open class MTROperationalStateClusterOperationalErrorEvent: NSObject {}
open class MTROperationalStateClusterOperationalStateStruct: NSObject {}
open class MTROtaSoftwareUpdateRequestorClusterDownloadErrorEvent: MTROTASoftwareUpdateRequestorClusterDownloadErrorEvent {}
open class MTROtaSoftwareUpdateRequestorClusterProviderLocation: MTROTASoftwareUpdateRequestorClusterProviderLocation {}
open class MTROtaSoftwareUpdateRequestorClusterStateTransitionEvent: MTROTASoftwareUpdateRequestorClusterStateTransitionEvent {}
open class MTROtaSoftwareUpdateRequestorClusterVersionAppliedEvent: MTROTASoftwareUpdateRequestorClusterVersionAppliedEvent {}
open class MTROvenCavityOperationalStateClusterErrorStateStruct: NSObject {}
open class MTROvenCavityOperationalStateClusterOperationCompletionEvent: NSObject {}
open class MTROvenCavityOperationalStateClusterOperationalErrorEvent: NSObject {}
open class MTROvenCavityOperationalStateClusterOperationalStateStruct: NSObject {}
open class MTROvenModeClusterModeOptionStruct: NSObject {}
open class MTROvenModeClusterModeTagStruct: NSObject {}
open class MTRPowerSourceClusterBatChargeFaultChangeEvent: NSObject {}
open class MTRPowerSourceClusterBatChargeFaultChangeType: NSObject {}
open class MTRPowerSourceClusterBatFaultChangeEvent: NSObject {}
open class MTRPowerSourceClusterBatFaultChangeType: NSObject {}
open class MTRPowerSourceClusterWiredFaultChangeEvent: NSObject {}
open class MTRPowerSourceClusterWiredFaultChangeType: NSObject {}
open class MTRPumpConfigurationAndControlClusterAirDetectionEvent: NSObject {}
open class MTRPumpConfigurationAndControlClusterDryRunningEvent: NSObject {}
open class MTRPumpConfigurationAndControlClusterElectronicFatalFailureEvent: NSObject {}
open class MTRPumpConfigurationAndControlClusterElectronicNonFatalFailureEvent: NSObject {}
open class MTRPumpConfigurationAndControlClusterElectronicTemperatureHighEvent: NSObject {}
open class MTRPumpConfigurationAndControlClusterGeneralFaultEvent: NSObject {}
open class MTRPumpConfigurationAndControlClusterLeakageEvent: NSObject {}
open class MTRPumpConfigurationAndControlClusterMotorTemperatureHighEvent: NSObject {}
open class MTRPumpConfigurationAndControlClusterPowerMissingPhaseEvent: NSObject {}
open class MTRPumpConfigurationAndControlClusterPumpBlockedEvent: NSObject {}
open class MTRPumpConfigurationAndControlClusterPumpMotorFatalFailureEvent: NSObject {}
open class MTRPumpConfigurationAndControlClusterSensorFailureEvent: NSObject {}
open class MTRPumpConfigurationAndControlClusterSupplyVoltageHighEvent: NSObject {}
open class MTRPumpConfigurationAndControlClusterSupplyVoltageLowEvent: NSObject {}
open class MTRPumpConfigurationAndControlClusterSystemPressureHighEvent: NSObject {}
open class MTRPumpConfigurationAndControlClusterSystemPressureLowEvent: NSObject {}
open class MTRPumpConfigurationAndControlClusterTurbineOperationEvent: NSObject {}
open class MTRRVCCleanModeClusterModeOptionStruct: NSObject {}
open class MTRRVCCleanModeClusterModeTagStruct: NSObject {}
open class MTRRVCOperationalStateClusterErrorStateStruct: NSObject {}
open class MTRRVCOperationalStateClusterOperationCompletionEvent: NSObject {}
open class MTRRVCOperationalStateClusterOperationalErrorEvent: NSObject {}
open class MTRRVCOperationalStateClusterOperationalStateStruct: NSObject {}
open class MTRRVCRunModeClusterModeOptionStruct: NSObject {}
open class MTRRVCRunModeClusterModeTagStruct: NSObject {}
open class MTRRefrigeratorAlarmClusterNotifyEvent: NSObject {}
open class MTRRefrigeratorAndTemperatureControlledCabinetModeClusterModeOptionStruct: NSObject {}
open class MTRRefrigeratorAndTemperatureControlledCabinetModeClusterModeTagStruct: NSObject {}
open class MTRServiceAreaClusterAreaInfoStruct: NSObject {}
open class MTRServiceAreaClusterAreaStruct: NSObject {}
open class MTRServiceAreaClusterLandmarkInfoStruct: NSObject {}
open class MTRServiceAreaClusterMapStruct: NSObject {}
open class MTRServiceAreaClusterProgressStruct: NSObject {}
open class MTRSmokeCOAlarmClusterAlarmMutedEvent: NSObject {}
open class MTRSmokeCOAlarmClusterAllClearEvent: NSObject {}
open class MTRSmokeCOAlarmClusterCOAlarmEvent: NSObject {}
open class MTRSmokeCOAlarmClusterEndOfServiceEvent: NSObject {}
open class MTRSmokeCOAlarmClusterHardwareFaultEvent: NSObject {}
open class MTRSmokeCOAlarmClusterInterconnectCOAlarmEvent: NSObject {}
open class MTRSmokeCOAlarmClusterInterconnectSmokeAlarmEvent: NSObject {}
open class MTRSmokeCOAlarmClusterLowBatteryEvent: NSObject {}
open class MTRSmokeCOAlarmClusterMuteEndedEvent: NSObject {}
open class MTRSmokeCOAlarmClusterSelfTestCompleteEvent: NSObject {}
open class MTRSmokeCOAlarmClusterSmokeAlarmEvent: NSObject {}
open class MTRSoftwareDiagnosticsClusterSoftwareFaultEvent: NSObject {}
open class MTRSoftwareDiagnosticsClusterThreadMetricsStruct: NSObject {}
open class MTRSwitchClusterInitialPressEvent: NSObject {}
open class MTRSwitchClusterLongPressEvent: NSObject {}
open class MTRSwitchClusterLongReleaseEvent: NSObject {}
open class MTRSwitchClusterMultiPressCompleteEvent: NSObject {}
open class MTRSwitchClusterMultiPressOngoingEvent: NSObject {}
open class MTRSwitchClusterShortReleaseEvent: NSObject {}
open class MTRSwitchClusterSwitchLatchedEvent: NSObject {}
open class MTRTargetNavigatorClusterTargetInfoStruct: NSObject {}
open class MTRTargetNavigatorClusterTargetUpdatedEvent: NSObject {}
open class MTRThermostatClusterPresetStruct: NSObject {}
open class MTRThermostatClusterPresetTypeStruct: NSObject {}
open class MTRThermostatClusterScheduleStruct: NSObject {}
open class MTRThermostatClusterScheduleTransitionStruct: NSObject {}
open class MTRThermostatClusterScheduleTypeStruct: NSObject {}
open class MTRThermostatClusterWeeklyScheduleTransitionStruct: NSObject {}
open class MTRThreadNetworkDiagnosticsClusterConnectionStatusEvent: NSObject {}
open class MTRThreadNetworkDiagnosticsClusterNeighborTableStruct: NSObject {}
open class MTRThreadNetworkDiagnosticsClusterNetworkFaultChangeEvent: NSObject {}
open class MTRThreadNetworkDiagnosticsClusterOperationalDatasetComponents: NSObject {}
open class MTRThreadNetworkDiagnosticsClusterRouteTableStruct: NSObject {}
open class MTRThreadNetworkDiagnosticsClusterSecurityPolicy: NSObject {}
open class MTRThreadNetworkDirectoryClusterThreadNetworkStruct: NSObject {}
open class MTRTimeSynchronizationClusterDSTOffsetStruct: NSObject {}
open class MTRTimeSynchronizationClusterDSTStatusEvent: NSObject {}
open class MTRTimeSynchronizationClusterDSTTableEmptyEvent: NSObject {}
open class MTRTimeSynchronizationClusterDstOffsetType: MTRTimeSynchronizationClusterDSTOffsetStruct {}
open class MTRTimeSynchronizationClusterFabricScopedTrustedTimeSourceStruct: NSObject {}
open class MTRTimeSynchronizationClusterMissingTrustedTimeSourceEvent: NSObject {}
open class MTRTimeSynchronizationClusterTimeFailureEvent: NSObject {}
open class MTRTimeSynchronizationClusterTimeZoneStatusEvent: NSObject {}
open class MTRTimeSynchronizationClusterTimeZoneStruct: NSObject {}
open class MTRTimeSynchronizationClusterTimeZoneType: MTRTimeSynchronizationClusterTimeZoneStruct {}
open class MTRTimeSynchronizationClusterTrustedTimeSourceStruct: NSObject {}
open class MTRUnitTestingClusterDoubleNestedStructList: NSObject {}
open class MTRUnitTestingClusterNestedStruct: NSObject {}
open class MTRUnitTestingClusterNestedStructList: NSObject {}
open class MTRUnitTestingClusterNullablesAndOptionalsStruct: NSObject {}
open class MTRUnitTestingClusterSimpleStruct: NSObject {}
open class MTRUnitTestingClusterTestEventEvent: NSObject {}
open class MTRUnitTestingClusterTestFabricScoped: NSObject {}
open class MTRUnitTestingClusterTestFabricScopedEventEvent: NSObject {}
open class MTRUnitTestingClusterTestListStructOctet: NSObject {}
open class MTRUserLabelClusterLabelStruct: NSObject {}
open class MTRValveConfigurationAndControlClusterValveFaultEvent: NSObject {}
open class MTRValveConfigurationAndControlClusterValveStateChangedEvent: NSObject {}
open class MTRWaterHeaterManagementClusterBoostEndedEvent: NSObject {}
open class MTRWaterHeaterManagementClusterBoostStartedEvent: NSObject {}
open class MTRWaterHeaterManagementClusterWaterHeaterBoostInfoStruct: NSObject {}
open class MTRWaterHeaterModeClusterModeOptionStruct: NSObject {}
open class MTRWaterHeaterModeClusterModeTagStruct: NSObject {}
open class MTRWiFiNetworkDiagnosticsClusterAssociationFailureEvent: NSObject {}
open class MTRWiFiNetworkDiagnosticsClusterConnectionStatusEvent: NSObject {}
open class MTRWiFiNetworkDiagnosticsClusterDisconnectionEvent: NSObject {}
open class MTRAccessControlClusterReviewFabricRestrictionsParams: NSObject {}
open class MTRAccessControlClusterReviewFabricRestrictionsResponseParams: NSObject {}
open class MTRAccountLoginClusterGetSetupPINParams: NSObject {}
open class MTRAccountLoginClusterGetSetupPINResponseParams: NSObject {}
open class MTRAccountLoginClusterLoginParams: NSObject {}
open class MTRAccountLoginClusterLogoutParams: NSObject {}
open class MTRActionsClusterDisableActionParams: NSObject {}
open class MTRActionsClusterDisableActionWithDurationParams: NSObject {}
open class MTRActionsClusterEnableActionParams: NSObject {}
open class MTRActionsClusterEnableActionWithDurationParams: NSObject {}
open class MTRActionsClusterInstantActionParams: NSObject {}
open class MTRActionsClusterInstantActionWithTransitionParams: NSObject {}
open class MTRActionsClusterPauseActionParams: NSObject {}
open class MTRActionsClusterPauseActionWithDurationParams: NSObject {}
open class MTRActionsClusterResumeActionParams: NSObject {}
open class MTRActionsClusterStartActionParams: NSObject {}
open class MTRActionsClusterStartActionWithDurationParams: NSObject {}
open class MTRActionsClusterStopActionParams: NSObject {}
open class MTRActivatedCarbonFilterMonitoringClusterResetConditionParams: NSObject {}
open class MTRAdministratorCommissioningClusterOpenBasicCommissioningWindowParams: NSObject {}
open class MTRAdministratorCommissioningClusterOpenCommissioningWindowParams: NSObject {}
open class MTRAdministratorCommissioningClusterRevokeCommissioningParams: NSObject {}
open class MTRApplicationLauncherClusterHideAppParams: NSObject {}
open class MTRApplicationLauncherClusterLaunchAppParams: NSObject {}
open class MTRApplicationLauncherClusterLauncherResponseParams: NSObject {}
open class MTRApplicationLauncherClusterStopAppParams: NSObject {}
open class MTRAudioOutputClusterRenameOutputParams: NSObject {}
open class MTRAudioOutputClusterSelectOutputParams: NSObject {}
open class MTRBasicClusterMfgSpecificPingParams: NSObject {}
open class MTRBooleanStateConfigurationClusterEnableDisableAlarmParams: NSObject {}
open class MTRBooleanStateConfigurationClusterSuppressAlarmParams: NSObject {}
open class MTRBridgedDeviceBasicInformationClusterKeepActiveParams: NSObject {}
open class MTRChannelClusterCancelRecordProgramParams: NSObject {}
open class MTRChannelClusterChangeChannelByNumberParams: NSObject {}
open class MTRChannelClusterChangeChannelParams: NSObject {}
open class MTRChannelClusterChangeChannelResponseParams: NSObject {}
open class MTRChannelClusterGetProgramGuideParams: NSObject {}
open class MTRChannelClusterProgramGuideResponseParams: NSObject {}
open class MTRChannelClusterRecordProgramParams: NSObject {}
open class MTRChannelClusterSkipChannelParams: NSObject {}
open class MTRColorControlClusterColorLoopSetParams: NSObject {}
open class MTRColorControlClusterEnhancedMoveHueParams: NSObject {}
open class MTRColorControlClusterEnhancedMoveToHueAndSaturationParams: NSObject {}
open class MTRColorControlClusterEnhancedMoveToHueParams: NSObject {}
open class MTRColorControlClusterEnhancedStepHueParams: NSObject {}
open class MTRColorControlClusterMoveColorParams: NSObject {}
open class MTRColorControlClusterMoveColorTemperatureParams: NSObject {}
open class MTRColorControlClusterMoveHueParams: NSObject {}
open class MTRColorControlClusterMoveSaturationParams: NSObject {}
open class MTRColorControlClusterMoveToColorParams: NSObject {}
open class MTRColorControlClusterMoveToColorTemperatureParams: NSObject {}
open class MTRColorControlClusterMoveToHueAndSaturationParams: NSObject {}
open class MTRColorControlClusterMoveToHueParams: NSObject {}
open class MTRColorControlClusterMoveToSaturationParams: NSObject {}
open class MTRColorControlClusterStepColorParams: NSObject {}
open class MTRColorControlClusterStepColorTemperatureParams: NSObject {}
open class MTRColorControlClusterStepHueParams: NSObject {}
open class MTRColorControlClusterStepSaturationParams: NSObject {}
open class MTRColorControlClusterStopMoveStepParams: NSObject {}
open class MTRCommissionerControlClusterCommissionNodeParams: NSObject {}
open class MTRCommissionerControlClusterRequestCommissioningApprovalParams: NSObject {}
open class MTRCommissionerControlClusterReverseOpenCommissioningWindowParams: NSObject {}
open class MTRContentAppObserverClusterContentAppMessageParams: NSObject {}
open class MTRContentAppObserverClusterContentAppMessageResponseParams: NSObject {}
open class MTRContentLauncherClusterLaunchContentParams: NSObject {}
open class MTRContentLauncherClusterLaunchURLParams: NSObject {}
open class MTRContentLauncherClusterLauncherResponseParams: NSObject {}
open class MTRDeviceEnergyManagementClusterCancelPowerAdjustRequestParams: NSObject {}
open class MTRDeviceEnergyManagementClusterCancelRequestParams: NSObject {}
open class MTRDeviceEnergyManagementClusterModifyForecastRequestParams: NSObject {}
open class MTRDeviceEnergyManagementClusterPauseRequestParams: NSObject {}
open class MTRDeviceEnergyManagementClusterPowerAdjustRequestParams: NSObject {}
open class MTRDeviceEnergyManagementClusterRequestConstraintBasedForecastParams: NSObject {}
open class MTRDeviceEnergyManagementClusterResumeRequestParams: NSObject {}
open class MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams: NSObject {}
open class MTRDeviceEnergyManagementModeClusterChangeToModeParams: NSObject {}
open class MTRDeviceEnergyManagementModeClusterChangeToModeResponseParams: NSObject {}
open class MTRDiagnosticLogsClusterRetrieveLogsRequestParams: NSObject {}
open class MTRDiagnosticLogsClusterRetrieveLogsResponseParams: NSObject {}
open class MTRDishwasherAlarmClusterModifyEnabledAlarmsParams: NSObject {}
open class MTRDishwasherAlarmClusterResetParams: NSObject {}
open class MTRDishwasherModeClusterChangeToModeParams: NSObject {}
open class MTRDishwasherModeClusterChangeToModeResponseParams: NSObject {}
open class MTRDoorLockClusterClearAliroReaderConfigParams: NSObject {}
open class MTRDoorLockClusterClearCredentialParams: NSObject {}
open class MTRDoorLockClusterClearHolidayScheduleParams: NSObject {}
open class MTRDoorLockClusterClearUserParams: NSObject {}
open class MTRDoorLockClusterClearWeekDayScheduleParams: NSObject {}
open class MTRDoorLockClusterClearYearDayScheduleParams: NSObject {}
open class MTRDoorLockClusterGetCredentialStatusParams: NSObject {}
open class MTRDoorLockClusterGetCredentialStatusResponseParams: NSObject {}
open class MTRDoorLockClusterGetHolidayScheduleParams: NSObject {}
open class MTRDoorLockClusterGetHolidayScheduleResponseParams: NSObject {}
open class MTRDoorLockClusterGetUserParams: NSObject {}
open class MTRDoorLockClusterGetUserResponseParams: NSObject {}
open class MTRDoorLockClusterGetWeekDayScheduleParams: NSObject {}
open class MTRDoorLockClusterGetWeekDayScheduleResponseParams: NSObject {}
open class MTRDoorLockClusterGetYearDayScheduleParams: NSObject {}
open class MTRDoorLockClusterGetYearDayScheduleResponseParams: NSObject {}
open class MTRDoorLockClusterLockDoorParams: NSObject {}
open class MTRDoorLockClusterSetAliroReaderConfigParams: NSObject {}
open class MTRDoorLockClusterSetCredentialParams: NSObject {}
open class MTRDoorLockClusterSetCredentialResponseParams: NSObject {}
open class MTRDoorLockClusterSetHolidayScheduleParams: NSObject {}
open class MTRDoorLockClusterSetUserParams: NSObject {}
open class MTRDoorLockClusterSetWeekDayScheduleParams: NSObject {}
open class MTRDoorLockClusterSetYearDayScheduleParams: NSObject {}
open class MTRDoorLockClusterUnboltDoorParams: NSObject {}
open class MTRDoorLockClusterUnlockDoorParams: NSObject {}
open class MTRDoorLockClusterUnlockWithTimeoutParams: NSObject {}
open class MTREnergyEVSEClusterClearTargetsParams: NSObject {}
open class MTREnergyEVSEClusterDisableParams: NSObject {}
open class MTREnergyEVSEClusterEnableChargingParams: NSObject {}
open class MTREnergyEVSEClusterGetTargetsParams: NSObject {}
open class MTREnergyEVSEClusterGetTargetsResponseParams: NSObject {}
open class MTREnergyEVSEClusterSetTargetsParams: NSObject {}
open class MTREnergyEVSEClusterStartDiagnosticsParams: NSObject {}
open class MTREnergyEVSEModeClusterChangeToModeParams: NSObject {}
open class MTREnergyEVSEModeClusterChangeToModeResponseParams: NSObject {}
open class MTREthernetNetworkDiagnosticsClusterResetCountsParams: NSObject {}
open class MTRFanControlClusterStepParams: NSObject {}
open class MTRGeneralCommissioningClusterArmFailSafeParams: NSObject {}
open class MTRGeneralCommissioningClusterArmFailSafeResponseParams: NSObject {}
open class MTRGeneralCommissioningClusterCommissioningCompleteParams: NSObject {}
open class MTRGeneralCommissioningClusterCommissioningCompleteResponseParams: NSObject {}
open class MTRGeneralCommissioningClusterSetRegulatoryConfigParams: NSObject {}
open class MTRGeneralCommissioningClusterSetRegulatoryConfigResponseParams: NSObject {}
open class MTRGeneralDiagnosticsClusterPayloadTestRequestParams: NSObject {}
open class MTRGeneralDiagnosticsClusterPayloadTestResponseParams: NSObject {}
open class MTRGeneralDiagnosticsClusterTestEventTriggerParams: NSObject {}
open class MTRGeneralDiagnosticsClusterTimeSnapshotParams: NSObject {}
open class MTRGeneralDiagnosticsClusterTimeSnapshotResponseParams: NSObject {}
open class MTRGroupKeyManagementClusterKeySetReadAllIndicesParams: NSObject {}
open class MTRGroupKeyManagementClusterKeySetReadAllIndicesResponseParams: NSObject {}
open class MTRGroupKeyManagementClusterKeySetReadParams: NSObject {}
open class MTRGroupKeyManagementClusterKeySetReadResponseParams: NSObject {}
open class MTRGroupKeyManagementClusterKeySetRemoveParams: NSObject {}
open class MTRGroupKeyManagementClusterKeySetWriteParams: NSObject {}
open class MTRGroupsClusterAddGroupIfIdentifyingParams: NSObject {}
open class MTRGroupsClusterAddGroupParams: NSObject {}
open class MTRGroupsClusterAddGroupResponseParams: NSObject {}
open class MTRGroupsClusterGetGroupMembershipParams: NSObject {}
open class MTRGroupsClusterGetGroupMembershipResponseParams: NSObject {}
open class MTRGroupsClusterRemoveAllGroupsParams: NSObject {}
open class MTRGroupsClusterRemoveGroupParams: NSObject {}
open class MTRGroupsClusterRemoveGroupResponseParams: NSObject {}
open class MTRGroupsClusterViewGroupParams: NSObject {}
open class MTRGroupsClusterViewGroupResponseParams: NSObject {}
open class MTRHEPAFilterMonitoringClusterResetConditionParams: NSObject {}
open class MTRICDManagementClusterRegisterClientParams: NSObject {}
open class MTRICDManagementClusterRegisterClientResponseParams: NSObject {}
open class MTRICDManagementClusterStayActiveRequestParams: NSObject {}
open class MTRICDManagementClusterStayActiveResponseParams: NSObject {}
open class MTRICDManagementClusterUnregisterClientParams: NSObject {}
open class MTRIdentifyClusterIdentifyParams: NSObject {}
open class MTRIdentifyClusterTriggerEffectParams: NSObject {}
open class MTRKeypadInputClusterSendKeyParams: NSObject {}
open class MTRKeypadInputClusterSendKeyResponseParams: NSObject {}
open class MTRLaundryWasherModeClusterChangeToModeParams: NSObject {}
open class MTRLaundryWasherModeClusterChangeToModeResponseParams: NSObject {}
open class MTRLevelControlClusterMoveParams: NSObject {}
open class MTRLevelControlClusterMoveToClosestFrequencyParams: NSObject {}
open class MTRLevelControlClusterMoveToLevelParams: NSObject {}
open class MTRLevelControlClusterMoveToLevelWithOnOffParams: NSObject {}
open class MTRLevelControlClusterMoveWithOnOffParams: NSObject {}
open class MTRLevelControlClusterStepParams: NSObject {}
open class MTRLevelControlClusterStepWithOnOffParams: NSObject {}
open class MTRLevelControlClusterStopParams: NSObject {}
open class MTRLevelControlClusterStopWithOnOffParams: NSObject {}
open class MTRLowPowerClusterSleepParams: NSObject {}
open class MTRMediaInputClusterHideInputStatusParams: NSObject {}
open class MTRMediaInputClusterRenameInputParams: NSObject {}
open class MTRMediaInputClusterSelectInputParams: NSObject {}
open class MTRMediaInputClusterShowInputStatusParams: NSObject {}
open class MTRMediaPlaybackClusterActivateAudioTrackParams: NSObject {}
open class MTRMediaPlaybackClusterActivateTextTrackParams: NSObject {}
open class MTRMediaPlaybackClusterDeactivateTextTrackParams: NSObject {}
open class MTRMediaPlaybackClusterFastForwardParams: NSObject {}
open class MTRMediaPlaybackClusterNextParams: NSObject {}
open class MTRMediaPlaybackClusterPauseParams: NSObject {}
open class MTRMediaPlaybackClusterPlayParams: NSObject {}
open class MTRMediaPlaybackClusterPlaybackResponseParams: NSObject {}
open class MTRMediaPlaybackClusterPreviousParams: NSObject {}
open class MTRMediaPlaybackClusterRewindParams: NSObject {}
open class MTRMediaPlaybackClusterSeekParams: NSObject {}
open class MTRMediaPlaybackClusterSkipBackwardParams: NSObject {}
open class MTRMediaPlaybackClusterSkipForwardParams: NSObject {}
open class MTRMediaPlaybackClusterStartOverParams: NSObject {}
open class MTRMediaPlaybackClusterStopParams: NSObject {}
open class MTRMediaPlaybackClusterStopPlaybackParams: MTRMediaPlaybackClusterStopParams {}
open class MTRMessagesClusterCancelMessagesRequestParams: NSObject {}
open class MTRMessagesClusterPresentMessagesRequestParams: NSObject {}
open class MTRMicrowaveOvenControlClusterAddMoreTimeParams: NSObject {}
open class MTRMicrowaveOvenControlClusterSetCookingParametersParams: NSObject {}
open class MTRModeSelectClusterChangeToModeParams: NSObject {}
open class MTRNetworkCommissioningClusterAddOrUpdateThreadNetworkParams: NSObject {}
open class MTRNetworkCommissioningClusterAddOrUpdateWiFiNetworkParams: NSObject {}
open class MTRNetworkCommissioningClusterConnectNetworkParams: NSObject {}
open class MTRNetworkCommissioningClusterConnectNetworkResponseParams: NSObject {}
open class MTRNetworkCommissioningClusterNetworkConfigResponseParams: NSObject {}
open class MTRNetworkCommissioningClusterRemoveNetworkParams: NSObject {}
open class MTRNetworkCommissioningClusterReorderNetworkParams: NSObject {}
open class MTRNetworkCommissioningClusterScanNetworksParams: NSObject {}
open class MTRNetworkCommissioningClusterScanNetworksResponseParams: NSObject {}
open class MTROTASoftwareUpdateProviderClusterApplyUpdateRequestParams: NSObject {}
open class MTROTASoftwareUpdateProviderClusterApplyUpdateResponseParams: NSObject {}
open class MTROTASoftwareUpdateProviderClusterNotifyUpdateAppliedParams: NSObject {}
open class MTROTASoftwareUpdateProviderClusterQueryImageParams: NSObject {}
open class MTROTASoftwareUpdateProviderClusterQueryImageResponseParams: NSObject {}
open class MTROTASoftwareUpdateRequestorClusterAnnounceOTAProviderParams: NSObject {}
open class MTROnOffClusterOffParams: NSObject {}
open class MTROnOffClusterOffWithEffectParams: NSObject {}
open class MTROnOffClusterOnParams: NSObject {}
open class MTROnOffClusterOnWithRecallGlobalSceneParams: NSObject {}
open class MTROnOffClusterOnWithTimedOffParams: NSObject {}
open class MTROnOffClusterToggleParams: NSObject {}
open class MTROperationalCredentialsClusterAddNOCParams: NSObject {}
open class MTROperationalCredentialsClusterAddTrustedRootCertificateParams: NSObject {}
open class MTROperationalCredentialsClusterAttestationRequestParams: NSObject {}
open class MTROperationalCredentialsClusterAttestationResponseParams: NSObject {}
open class MTROperationalCredentialsClusterCSRRequestParams: NSObject {}
open class MTROperationalCredentialsClusterCSRResponseParams: NSObject {}
open class MTROperationalCredentialsClusterCertificateChainRequestParams: NSObject {}
open class MTROperationalCredentialsClusterCertificateChainResponseParams: NSObject {}
open class MTROperationalCredentialsClusterNOCResponseParams: NSObject {}
open class MTROperationalCredentialsClusterRemoveFabricParams: NSObject {}
open class MTROperationalCredentialsClusterUpdateFabricLabelParams: NSObject {}
open class MTROperationalCredentialsClusterUpdateNOCParams: NSObject {}
open class MTROperationalStateClusterOperationalCommandResponseParams: NSObject {}
open class MTROperationalStateClusterPauseParams: NSObject {}
open class MTROperationalStateClusterResumeParams: NSObject {}
open class MTROperationalStateClusterStartParams: NSObject {}
open class MTROperationalStateClusterStopParams: NSObject {}
open class MTROtaSoftwareUpdateProviderClusterApplyUpdateRequestParams: MTROTASoftwareUpdateProviderClusterApplyUpdateRequestParams {}
open class MTROtaSoftwareUpdateProviderClusterApplyUpdateResponseParams: MTROTASoftwareUpdateProviderClusterApplyUpdateResponseParams {}
open class MTROtaSoftwareUpdateProviderClusterNotifyUpdateAppliedParams: MTROTASoftwareUpdateProviderClusterNotifyUpdateAppliedParams {}
open class MTROtaSoftwareUpdateProviderClusterQueryImageParams: MTROTASoftwareUpdateProviderClusterQueryImageParams {}
open class MTROtaSoftwareUpdateProviderClusterQueryImageResponseParams: MTROTASoftwareUpdateProviderClusterQueryImageResponseParams {}
open class MTROtaSoftwareUpdateRequestorClusterAnnounceOtaProviderParams: MTROTASoftwareUpdateRequestorClusterAnnounceOTAProviderParams {}
open class MTROvenCavityOperationalStateClusterOperationalCommandResponseParams: NSObject {}
open class MTROvenCavityOperationalStateClusterStartParams: NSObject {}
open class MTROvenCavityOperationalStateClusterStopParams: NSObject {}
open class MTROvenModeClusterChangeToModeParams: NSObject {}
open class MTROvenModeClusterChangeToModeResponseParams: NSObject {}
open class MTRRVCCleanModeClusterChangeToModeParams: NSObject {}
open class MTRRVCCleanModeClusterChangeToModeResponseParams: NSObject {}
open class MTRRVCOperationalStateClusterGoHomeParams: NSObject {}
open class MTRRVCOperationalStateClusterOperationalCommandResponseParams: NSObject {}
open class MTRRVCOperationalStateClusterPauseParams: NSObject {}
open class MTRRVCOperationalStateClusterResumeParams: NSObject {}
open class MTRRVCRunModeClusterChangeToModeParams: NSObject {}
open class MTRRVCRunModeClusterChangeToModeResponseParams: NSObject {}
open class MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeParams: NSObject {}
open class MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams: NSObject {}
open class MTRServiceAreaClusterSelectAreasParams: NSObject {}
open class MTRServiceAreaClusterSelectAreasResponseParams: NSObject {}
open class MTRServiceAreaClusterSkipAreaParams: NSObject {}
open class MTRServiceAreaClusterSkipAreaResponseParams: NSObject {}
open class MTRSmokeCOAlarmClusterSelfTestRequestParams: NSObject {}
open class MTRSoftwareDiagnosticsClusterResetWatermarksParams: NSObject {}
open class MTRTargetNavigatorClusterNavigateTargetParams: NSObject {}
open class MTRTargetNavigatorClusterNavigateTargetResponseParams: NSObject {}
open class MTRTemperatureControlClusterSetTemperatureParams: NSObject {}
open class MTRThermostatClusterAtomicRequestParams: NSObject {}
open class MTRThermostatClusterAtomicResponseParams: NSObject {}
open class MTRThermostatClusterClearWeeklyScheduleParams: NSObject {}
open class MTRThermostatClusterGetWeeklyScheduleParams: NSObject {}
open class MTRThermostatClusterGetWeeklyScheduleResponseParams: NSObject {}
open class MTRThermostatClusterSetActivePresetRequestParams: NSObject {}
open class MTRThermostatClusterSetActiveScheduleRequestParams: NSObject {}
open class MTRThermostatClusterSetWeeklyScheduleParams: NSObject {}
open class MTRThermostatClusterSetpointRaiseLowerParams: NSObject {}
open class MTRThreadBorderRouterManagementClusterDatasetResponseParams: NSObject {}
open class MTRThreadBorderRouterManagementClusterGetActiveDatasetRequestParams: NSObject {}
open class MTRThreadBorderRouterManagementClusterGetPendingDatasetRequestParams: NSObject {}
open class MTRThreadBorderRouterManagementClusterSetActiveDatasetRequestParams: NSObject {}
open class MTRThreadBorderRouterManagementClusterSetPendingDatasetRequestParams: NSObject {}
open class MTRThreadNetworkDiagnosticsClusterResetCountsParams: NSObject {}
open class MTRThreadNetworkDirectoryClusterAddNetworkParams: NSObject {}
open class MTRThreadNetworkDirectoryClusterGetOperationalDatasetParams: NSObject {}
open class MTRThreadNetworkDirectoryClusterOperationalDatasetResponseParams: NSObject {}
open class MTRThreadNetworkDirectoryClusterRemoveNetworkParams: NSObject {}
open class MTRTimeSynchronizationClusterSetDSTOffsetParams: NSObject {}
open class MTRTimeSynchronizationClusterSetDefaultNTPParams: NSObject {}
open class MTRTimeSynchronizationClusterSetTimeZoneParams: NSObject {}
open class MTRTimeSynchronizationClusterSetTimeZoneResponseParams: NSObject {}
open class MTRTimeSynchronizationClusterSetTrustedTimeSourceParams: NSObject {}
open class MTRTimeSynchronizationClusterSetUTCTimeParams: NSObject {}
open class MTRTimeSynchronizationClusterSetUtcTimeParams: MTRTimeSynchronizationClusterSetUTCTimeParams {}
open class MTRUnitTestingClusterBooleanResponseParams: NSObject {}
open class MTRUnitTestingClusterSimpleStructEchoRequestParams: NSObject {}
open class MTRUnitTestingClusterSimpleStructResponseParams: NSObject {}
open class MTRUnitTestingClusterTestAddArgumentsParams: NSObject {}
open class MTRUnitTestingClusterTestAddArgumentsResponseParams: NSObject {}
open class MTRUnitTestingClusterTestComplexNullableOptionalRequestParams: NSObject {}
open class MTRUnitTestingClusterTestComplexNullableOptionalResponseParams: NSObject {}
open class MTRUnitTestingClusterTestEmitTestEventRequestParams: NSObject {}
open class MTRUnitTestingClusterTestEmitTestEventResponseParams: NSObject {}
open class MTRUnitTestingClusterTestEmitTestFabricScopedEventRequestParams: NSObject {}
open class MTRUnitTestingClusterTestEmitTestFabricScopedEventResponseParams: NSObject {}
open class MTRUnitTestingClusterTestEnumsRequestParams: NSObject {}
open class MTRUnitTestingClusterTestEnumsResponseParams: NSObject {}
open class MTRUnitTestingClusterTestListInt8UArgumentRequestParams: NSObject {}
open class MTRUnitTestingClusterTestListInt8UReverseRequestParams: NSObject {}
open class MTRUnitTestingClusterTestListInt8UReverseResponseParams: NSObject {}
open class MTRUnitTestingClusterTestListNestedStructListArgumentRequestParams: NSObject {}
open class MTRUnitTestingClusterTestListStructArgumentRequestParams: NSObject {}
open class MTRUnitTestingClusterTestNestedStructArgumentRequestParams: NSObject {}
open class MTRUnitTestingClusterTestNestedStructListArgumentRequestParams: NSObject {}
open class MTRUnitTestingClusterTestNotHandledParams: NSObject {}
open class MTRUnitTestingClusterTestNullableOptionalRequestParams: NSObject {}
open class MTRUnitTestingClusterTestNullableOptionalResponseParams: NSObject {}
open class MTRUnitTestingClusterTestParams: NSObject {}
open class MTRUnitTestingClusterTestSimpleArgumentRequestParams: NSObject {}
open class MTRUnitTestingClusterTestSimpleArgumentResponseParams: NSObject {}
open class MTRUnitTestingClusterTestSimpleOptionalArgumentRequestParams: NSObject {}
open class MTRUnitTestingClusterTestSpecificParams: NSObject {}
open class MTRUnitTestingClusterTestSpecificResponseParams: NSObject {}
open class MTRUnitTestingClusterTestStructArgumentRequestParams: NSObject {}
open class MTRUnitTestingClusterTestStructArrayArgumentRequestParams: NSObject {}
open class MTRUnitTestingClusterTestStructArrayArgumentResponseParams: NSObject {}
open class MTRUnitTestingClusterTestUnknownCommandParams: NSObject {}
open class MTRUnitTestingClusterTimedInvokeRequestParams: NSObject {}
open class MTRValveConfigurationAndControlClusterCloseParams: NSObject {}
open class MTRValveConfigurationAndControlClusterOpenParams: NSObject {}
open class MTRWaterHeaterManagementClusterBoostParams: NSObject {}
open class MTRWaterHeaterManagementClusterCancelBoostParams: NSObject {}
open class MTRWaterHeaterModeClusterChangeToModeParams: NSObject {}
open class MTRWaterHeaterModeClusterChangeToModeResponseParams: NSObject {}
open class MTRWiFiNetworkDiagnosticsClusterResetCountsParams: NSObject {}
open class MTRWiFiNetworkManagementClusterNetworkPassphraseRequestParams: NSObject {}
open class MTRWiFiNetworkManagementClusterNetworkPassphraseResponseParams: NSObject {}
open class MTRWindowCoveringClusterDownOrCloseParams: NSObject {}
open class MTRWindowCoveringClusterGoToLiftPercentageParams: NSObject {}
open class MTRWindowCoveringClusterGoToLiftValueParams: NSObject {}
open class MTRWindowCoveringClusterGoToTiltPercentageParams: NSObject {}
open class MTRWindowCoveringClusterGoToTiltValueParams: NSObject {}
open class MTRWindowCoveringClusterStopMotionParams: NSObject {}
open class MTRWindowCoveringClusterUpOrOpenParams: NSObject {}
open class MTRDeviceControllerStartupParams: NSObject {}
open class MTRClusterAccessControl: MTRGenericCluster {}
open class MTRClusterAccountLogin: MTRGenericCluster {}
open class MTRClusterActions: MTRGenericCluster {}
open class MTRClusterActivatedCarbonFilterMonitoring: MTRGenericCluster {}
open class MTRClusterAdministratorCommissioning: MTRGenericCluster {}
open class MTRClusterAirQuality: MTRGenericCluster {}
open class MTRClusterApplicationBasic: MTRGenericCluster {}
open class MTRClusterApplicationLauncher: MTRGenericCluster {}
open class MTRClusterAudioOutput: MTRGenericCluster {}
open class MTRClusterBallastConfiguration: MTRGenericCluster {}
open class MTRClusterBasicInformation: MTRGenericCluster {}
open class MTRClusterBinding: MTRGenericCluster {}
open class MTRClusterBooleanState: MTRGenericCluster {}
open class MTRClusterBooleanStateConfiguration: MTRGenericCluster {}
open class MTRClusterBridgedDeviceBasicInformation: MTRGenericCluster {}
open class MTRClusterCarbonDioxideConcentrationMeasurement: MTRGenericCluster {}
open class MTRClusterCarbonMonoxideConcentrationMeasurement: MTRGenericCluster {}
open class MTRClusterChannel: MTRGenericCluster {}
open class MTRClusterColorControl: MTRGenericCluster {}
open class MTRClusterCommissionerControl: MTRGenericCluster {}
open class MTRClusterContentAppObserver: MTRGenericCluster {}
open class MTRClusterContentLauncher: MTRGenericCluster {}
open class MTRClusterDescriptor: MTRGenericCluster {}
open class MTRClusterDeviceEnergyManagement: MTRGenericCluster {}
open class MTRClusterDeviceEnergyManagementMode: MTRGenericCluster {}
open class MTRClusterDiagnosticLogs: MTRGenericCluster {}
open class MTRClusterDishwasherAlarm: MTRGenericCluster {}
open class MTRClusterDishwasherMode: MTRGenericCluster {}
open class MTRClusterDoorLock: MTRGenericCluster {}
open class MTRClusterElectricalEnergyMeasurement: MTRGenericCluster {}
open class MTRClusterElectricalPowerMeasurement: MTRGenericCluster {}
open class MTRClusterEnergyEVSE: MTRGenericCluster {}
open class MTRClusterEnergyEVSEMode: MTRGenericCluster {}
open class MTRClusterEthernetNetworkDiagnostics: MTRGenericCluster {}
open class MTRClusterFanControl: MTRGenericCluster {}
open class MTRClusterFixedLabel: MTRGenericCluster {}
open class MTRClusterFlowMeasurement: MTRGenericCluster {}
open class MTRClusterFormaldehydeConcentrationMeasurement: MTRGenericCluster {}
open class MTRClusterGeneralCommissioning: MTRGenericCluster {}
open class MTRClusterGeneralDiagnostics: MTRGenericCluster {}
open class MTRClusterGroupKeyManagement: MTRGenericCluster {}
open class MTRClusterGroups: MTRGenericCluster {}
open class MTRClusterHEPAFilterMonitoring: MTRGenericCluster {}
open class MTRClusterICDManagement: MTRGenericCluster {}
open class MTRClusterIdentify: MTRGenericCluster {}
open class MTRClusterIlluminanceMeasurement: MTRGenericCluster {}
open class MTRClusterKeypadInput: MTRGenericCluster {}
open class MTRClusterLaundryDryerControls: MTRGenericCluster {}
open class MTRClusterLaundryWasherControls: MTRGenericCluster {}
open class MTRClusterLaundryWasherMode: MTRGenericCluster {}
open class MTRClusterLevelControl: MTRGenericCluster {}
open class MTRClusterLocalizationConfiguration: MTRGenericCluster {}
open class MTRClusterLowPower: MTRGenericCluster {}
open class MTRClusterMediaInput: MTRGenericCluster {}
open class MTRClusterMediaPlayback: MTRGenericCluster {}
open class MTRClusterMessages: MTRGenericCluster {}
open class MTRClusterMicrowaveOvenControl: MTRGenericCluster {}
open class MTRClusterMicrowaveOvenMode: MTRGenericCluster {}
open class MTRClusterModeSelect: MTRGenericCluster {}
open class MTRClusterNetworkCommissioning: MTRGenericCluster {}
open class MTRClusterNitrogenDioxideConcentrationMeasurement: MTRGenericCluster {}
open class MTRClusterOTASoftwareUpdateProvider: MTRGenericCluster {}
open class MTRClusterOTASoftwareUpdateRequestor: MTRGenericCluster {}
open class MTRClusterOccupancySensing: MTRGenericCluster {}
open class MTRClusterOnOff: MTRGenericCluster {}
open class MTRClusterOperationalCredentials: MTRGenericCluster {}
open class MTRClusterOperationalState: MTRGenericCluster {}
open class MTRClusterOtaSoftwareUpdateProvider: MTRClusterOTASoftwareUpdateProvider {}
open class MTRClusterOtaSoftwareUpdateRequestor: MTRClusterOTASoftwareUpdateRequestor {}
open class MTRClusterOvenCavityOperationalState: MTRGenericCluster {}
open class MTRClusterOvenMode: MTRGenericCluster {}
open class MTRClusterOzoneConcentrationMeasurement: MTRGenericCluster {}
open class MTRClusterPM10ConcentrationMeasurement: MTRGenericCluster {}
open class MTRClusterPM1ConcentrationMeasurement: MTRGenericCluster {}
open class MTRClusterPM25ConcentrationMeasurement: MTRGenericCluster {}
open class MTRClusterPowerSource: MTRGenericCluster {}
open class MTRClusterPowerSourceConfiguration: MTRGenericCluster {}
open class MTRClusterPowerTopology: MTRGenericCluster {}
open class MTRClusterPressureMeasurement: MTRGenericCluster {}
open class MTRClusterPumpConfigurationAndControl: MTRGenericCluster {}
open class MTRClusterRVCCleanMode: MTRGenericCluster {}
open class MTRClusterRVCOperationalState: MTRGenericCluster {}
open class MTRClusterRVCRunMode: MTRGenericCluster {}
open class MTRClusterRadonConcentrationMeasurement: MTRGenericCluster {}
open class MTRClusterRefrigeratorAlarm: MTRGenericCluster {}
open class MTRClusterRefrigeratorAndTemperatureControlledCabinetMode: MTRGenericCluster {}
open class MTRClusterRelativeHumidityMeasurement: MTRGenericCluster {}
open class MTRClusterServiceArea: MTRGenericCluster {}
open class MTRClusterSmokeCOAlarm: MTRGenericCluster {}
open class MTRClusterSoftwareDiagnostics: MTRGenericCluster {}
open class MTRClusterSwitch: MTRGenericCluster {}
open class MTRClusterTargetNavigator: MTRGenericCluster {}
open class MTRClusterTemperatureControl: MTRGenericCluster {}
open class MTRClusterTemperatureMeasurement: MTRGenericCluster {}
open class MTRClusterThermostat: MTRGenericCluster {}
open class MTRClusterThermostatUserInterfaceConfiguration: MTRGenericCluster {}
open class MTRClusterThreadBorderRouterManagement: MTRGenericCluster {}
open class MTRClusterThreadNetworkDiagnostics: MTRGenericCluster {}
open class MTRClusterThreadNetworkDirectory: MTRGenericCluster {}
open class MTRClusterTimeFormatLocalization: MTRGenericCluster {}
open class MTRClusterTimeSynchronization: MTRGenericCluster {}
open class MTRClusterTotalVolatileOrganicCompoundsConcentrationMeasurement: MTRGenericCluster {}
open class MTRClusterUnitLocalization: MTRGenericCluster {}
open class MTRClusterUnitTesting: MTRGenericCluster {}
open class MTRClusterUserLabel: MTRGenericCluster {}
open class MTRClusterValveConfigurationAndControl: MTRGenericCluster {}
open class MTRClusterWakeOnLAN: MTRGenericCluster {}
open class MTRClusterWakeOnLan: MTRClusterWakeOnLAN {}
open class MTRClusterWaterHeaterManagement: MTRGenericCluster {}
open class MTRClusterWaterHeaterMode: MTRGenericCluster {}
open class MTRClusterWiFiNetworkDiagnostics: MTRGenericCluster {}
open class MTRClusterWiFiNetworkManagement: MTRGenericCluster {}
open class MTRClusterWindowCovering: MTRGenericCluster {}
open class MTRBaseClusterAccessControl: MTRGenericBaseCluster {}
open class MTRBaseClusterAccountLogin: MTRGenericBaseCluster {}
open class MTRBaseClusterActions: MTRGenericBaseCluster {}
open class MTRBaseClusterActivatedCarbonFilterMonitoring: MTRGenericBaseCluster {}
open class MTRBaseClusterAdministratorCommissioning: MTRGenericBaseCluster {}
open class MTRBaseClusterAirQuality: MTRGenericBaseCluster {}
open class MTRBaseClusterApplicationBasic: MTRGenericBaseCluster {}
open class MTRBaseClusterApplicationLauncher: MTRGenericBaseCluster {}
open class MTRBaseClusterAudioOutput: MTRGenericBaseCluster {}
open class MTRBaseClusterBallastConfiguration: MTRGenericBaseCluster {}
open class MTRBaseClusterBasicInformation: MTRGenericBaseCluster {}
open class MTRBaseClusterBinding: MTRGenericBaseCluster {}
open class MTRBaseClusterBooleanState: MTRGenericBaseCluster {}
open class MTRBaseClusterBooleanStateConfiguration: MTRGenericBaseCluster {}
open class MTRBaseClusterBridgedDeviceBasicInformation: MTRGenericBaseCluster {}
open class MTRBaseClusterCarbonDioxideConcentrationMeasurement: MTRGenericBaseCluster {}
open class MTRBaseClusterCarbonMonoxideConcentrationMeasurement: MTRGenericBaseCluster {}
open class MTRBaseClusterChannel: MTRGenericBaseCluster {}
open class MTRBaseClusterColorControl: MTRGenericBaseCluster {}
open class MTRBaseClusterCommissionerControl: MTRGenericBaseCluster {}
open class MTRBaseClusterContentAppObserver: MTRGenericBaseCluster {}
open class MTRBaseClusterContentLauncher: MTRGenericBaseCluster {}
open class MTRBaseClusterDescriptor: MTRGenericBaseCluster {}
open class MTRBaseClusterDeviceEnergyManagement: MTRGenericBaseCluster {}
open class MTRBaseClusterDeviceEnergyManagementMode: MTRGenericBaseCluster {}
open class MTRBaseClusterDiagnosticLogs: MTRGenericBaseCluster {}
open class MTRBaseClusterDishwasherAlarm: MTRGenericBaseCluster {}
open class MTRBaseClusterDishwasherMode: MTRGenericBaseCluster {}
open class MTRBaseClusterDoorLock: MTRGenericBaseCluster {}
open class MTRBaseClusterElectricalEnergyMeasurement: MTRGenericBaseCluster {}
open class MTRBaseClusterElectricalPowerMeasurement: MTRGenericBaseCluster {}
open class MTRBaseClusterEnergyEVSE: MTRGenericBaseCluster {}
open class MTRBaseClusterEnergyEVSEMode: MTRGenericBaseCluster {}
open class MTRBaseClusterEthernetNetworkDiagnostics: MTRGenericBaseCluster {}
open class MTRBaseClusterFanControl: MTRGenericBaseCluster {}
open class MTRBaseClusterFixedLabel: MTRGenericBaseCluster {}
open class MTRBaseClusterFlowMeasurement: MTRGenericBaseCluster {}
open class MTRBaseClusterFormaldehydeConcentrationMeasurement: MTRGenericBaseCluster {}
open class MTRBaseClusterGeneralCommissioning: MTRGenericBaseCluster {}
open class MTRBaseClusterGeneralDiagnostics: MTRGenericBaseCluster {}
open class MTRBaseClusterGroupKeyManagement: MTRGenericBaseCluster {}
open class MTRBaseClusterGroups: MTRGenericBaseCluster {}
open class MTRBaseClusterHEPAFilterMonitoring: MTRGenericBaseCluster {}
open class MTRBaseClusterICDManagement: MTRGenericBaseCluster {}
open class MTRBaseClusterIdentify: MTRGenericBaseCluster {}
open class MTRBaseClusterIlluminanceMeasurement: MTRGenericBaseCluster {}
open class MTRBaseClusterKeypadInput: MTRGenericBaseCluster {}
open class MTRBaseClusterLaundryDryerControls: MTRGenericBaseCluster {}
open class MTRBaseClusterLaundryWasherControls: MTRGenericBaseCluster {}
open class MTRBaseClusterLaundryWasherMode: MTRGenericBaseCluster {}
open class MTRBaseClusterLevelControl: MTRGenericBaseCluster {}
open class MTRBaseClusterLocalizationConfiguration: MTRGenericBaseCluster {}
open class MTRBaseClusterLowPower: MTRGenericBaseCluster {}
open class MTRBaseClusterMediaInput: MTRGenericBaseCluster {}
open class MTRBaseClusterMediaPlayback: MTRGenericBaseCluster {}
open class MTRBaseClusterMessages: MTRGenericBaseCluster {}
open class MTRBaseClusterMicrowaveOvenControl: MTRGenericBaseCluster {}
open class MTRBaseClusterMicrowaveOvenMode: MTRGenericBaseCluster {}
open class MTRBaseClusterModeSelect: MTRGenericBaseCluster {}
open class MTRBaseClusterNetworkCommissioning: MTRGenericBaseCluster {}
open class MTRBaseClusterNitrogenDioxideConcentrationMeasurement: MTRGenericBaseCluster {}
open class MTRBaseClusterOTASoftwareUpdateProvider: MTRGenericBaseCluster {}
open class MTRBaseClusterOTASoftwareUpdateRequestor: MTRGenericBaseCluster {}
open class MTRBaseClusterOccupancySensing: MTRGenericBaseCluster {}
open class MTRBaseClusterOnOff: MTRGenericBaseCluster {}
open class MTRBaseClusterOperationalCredentials: MTRGenericBaseCluster {}
open class MTRBaseClusterOperationalState: MTRGenericBaseCluster {}
open class MTRBaseClusterOtaSoftwareUpdateProvider: MTRBaseClusterOTASoftwareUpdateProvider {}
open class MTRBaseClusterOtaSoftwareUpdateRequestor: MTRBaseClusterOTASoftwareUpdateRequestor {}
open class MTRBaseClusterOvenCavityOperationalState: MTRGenericBaseCluster {}
open class MTRBaseClusterOvenMode: MTRGenericBaseCluster {}
open class MTRBaseClusterOzoneConcentrationMeasurement: MTRGenericBaseCluster {}
open class MTRBaseClusterPM10ConcentrationMeasurement: MTRGenericBaseCluster {}
open class MTRBaseClusterPM1ConcentrationMeasurement: MTRGenericBaseCluster {}
open class MTRBaseClusterPM25ConcentrationMeasurement: MTRGenericBaseCluster {}
open class MTRBaseClusterPowerSource: MTRGenericBaseCluster {}
open class MTRBaseClusterPowerSourceConfiguration: MTRGenericBaseCluster {}
open class MTRBaseClusterPowerTopology: MTRGenericBaseCluster {}
open class MTRBaseClusterPressureMeasurement: MTRGenericBaseCluster {}
open class MTRBaseClusterPumpConfigurationAndControl: MTRGenericBaseCluster {}
open class MTRBaseClusterRVCCleanMode: MTRGenericBaseCluster {}
open class MTRBaseClusterRVCOperationalState: MTRGenericBaseCluster {}
open class MTRBaseClusterRVCRunMode: MTRGenericBaseCluster {}
open class MTRBaseClusterRadonConcentrationMeasurement: MTRGenericBaseCluster {}
open class MTRBaseClusterRefrigeratorAlarm: MTRGenericBaseCluster {}
open class MTRBaseClusterRefrigeratorAndTemperatureControlledCabinetMode: MTRGenericBaseCluster {}
open class MTRBaseClusterRelativeHumidityMeasurement: MTRGenericBaseCluster {}
open class MTRBaseClusterServiceArea: MTRGenericBaseCluster {}
open class MTRBaseClusterSmokeCOAlarm: MTRGenericBaseCluster {}
open class MTRBaseClusterSoftwareDiagnostics: MTRGenericBaseCluster {}
open class MTRBaseClusterSwitch: MTRGenericBaseCluster {}
open class MTRBaseClusterTargetNavigator: MTRGenericBaseCluster {}
open class MTRBaseClusterTemperatureControl: MTRGenericBaseCluster {}
open class MTRBaseClusterTemperatureMeasurement: MTRGenericBaseCluster {}
open class MTRBaseClusterThermostat: MTRGenericBaseCluster {}
open class MTRBaseClusterThermostatUserInterfaceConfiguration: MTRGenericBaseCluster {}
open class MTRBaseClusterThreadBorderRouterManagement: MTRGenericBaseCluster {}
open class MTRBaseClusterThreadNetworkDiagnostics: MTRGenericBaseCluster {}
open class MTRBaseClusterThreadNetworkDirectory: MTRGenericBaseCluster {}
open class MTRBaseClusterTimeFormatLocalization: MTRGenericBaseCluster {}
open class MTRBaseClusterTimeSynchronization: MTRGenericBaseCluster {}
open class MTRBaseClusterTotalVolatileOrganicCompoundsConcentrationMeasurement: MTRGenericBaseCluster {}
open class MTRBaseClusterUnitLocalization: MTRGenericBaseCluster {}
open class MTRBaseClusterUnitTesting: MTRGenericBaseCluster {}
open class MTRBaseClusterUserLabel: MTRGenericBaseCluster {}
open class MTRBaseClusterValveConfigurationAndControl: MTRGenericBaseCluster {}
open class MTRBaseClusterWakeOnLAN: MTRGenericBaseCluster {}
open class MTRBaseClusterWakeOnLan: MTRBaseClusterWakeOnLAN {}
open class MTRBaseClusterWaterHeaterManagement: MTRGenericBaseCluster {}
open class MTRBaseClusterWaterHeaterMode: MTRGenericBaseCluster {}
open class MTRBaseClusterWiFiNetworkDiagnostics: MTRGenericBaseCluster {}
open class MTRBaseClusterWiFiNetworkManagement: MTRGenericBaseCluster {}
open class MTRBaseClusterWindowCovering: MTRGenericBaseCluster {}
open class MTRAccessControlClusterAccessControlEntry: MTRAccessControlClusterAccessControlEntryStruct {}
open class MTRApplicationBasicClusterApplicationBasicApplication: MTRApplicationBasicClusterApplicationStruct {}
open class MTRApplicationLauncherClusterApplication: MTRApplicationLauncherClusterApplicationStruct {}
open class MTRApplicationLauncherClusterApplicationEP: MTRApplicationLauncherClusterApplicationEPStruct {}
open class MTRAudioOutputClusterOutputInfo: MTRAudioOutputClusterOutputInfoStruct {}
open class MTRBasicClusterCapabilityMinimaStruct: MTRBasicInformationClusterCapabilityMinimaStruct {}
open class MTRBasicClusterLeaveEvent: MTRBasicInformationClusterLeaveEvent {}
open class MTRBasicClusterReachableChangedEvent: MTRBasicInformationClusterReachableChangedEvent {}
open class MTRBasicClusterShutDownEvent: MTRBasicInformationClusterShutDownEvent {}
open class MTRBasicClusterStartUpEvent: MTRBasicInformationClusterStartUpEvent {}
open class MTRBridgedDeviceBasicClusterLeaveEvent: MTRBridgedDeviceBasicInformationClusterLeaveEvent {}
open class MTRBridgedDeviceBasicClusterReachableChangedEvent: MTRBridgedDeviceBasicInformationClusterReachableChangedEvent {}
open class MTRBridgedDeviceBasicClusterShutDownEvent: MTRBridgedDeviceBasicInformationClusterShutDownEvent {}
open class MTRBridgedDeviceBasicClusterStartUpEvent: MTRBridgedDeviceBasicInformationClusterStartUpEvent {}
open class MTRChannelClusterChannelInfo: MTRChannelClusterChannelInfoStruct {}
open class MTRChannelClusterLineupInfo: MTRChannelClusterLineupInfoStruct {}
open class MTRContentLauncherClusterAdditionalInfo: MTRContentLauncherClusterAdditionalInfoStruct {}
open class MTRContentLauncherClusterBrandingInformation: MTRContentLauncherClusterBrandingInformationStruct {}
open class MTRContentLauncherClusterContentSearch: MTRContentLauncherClusterContentSearchStruct {}
open class MTRContentLauncherClusterDimension: MTRContentLauncherClusterDimensionStruct {}
open class MTRContentLauncherClusterParameter: MTRContentLauncherClusterParameterStruct {}
open class MTRContentLauncherClusterStyleInformation: MTRContentLauncherClusterStyleInformationStruct {}
open class MTRDescriptorClusterDeviceType: MTRDescriptorClusterDeviceTypeStruct {}
open class MTRMediaInputClusterInputInfo: MTRMediaInputClusterInputInfoStruct {}
open class MTRMediaPlaybackClusterPlaybackPosition: MTRMediaPlaybackClusterPlaybackPositionStruct {}
open class MTRModeSelectClusterSemanticTag: MTRModeSelectClusterSemanticTagStruct {}
open class MTRNetworkCommissioningClusterNetworkInfo: MTRNetworkCommissioningClusterNetworkInfoStruct {}
open class MTRNetworkCommissioningClusterThreadInterfaceScanResult: MTRNetworkCommissioningClusterThreadInterfaceScanResultStruct {}
open class MTRNetworkCommissioningClusterWiFiInterfaceScanResult: MTRNetworkCommissioningClusterWiFiInterfaceScanResultStruct {}
open class MTROperationalCredentialsClusterFabricDescriptor: MTROperationalCredentialsClusterFabricDescriptorStruct {}
open class MTRSoftwareDiagnosticsClusterThreadMetrics: MTRSoftwareDiagnosticsClusterThreadMetricsStruct {}
open class MTRTargetNavigatorClusterTargetInfo: MTRTargetNavigatorClusterTargetInfoStruct {}
open class MTRTestClusterClusterDoubleNestedStructList: MTRUnitTestingClusterDoubleNestedStructList {}
open class MTRTestClusterClusterNestedStruct: MTRUnitTestingClusterNestedStruct {}
open class MTRTestClusterClusterNestedStructList: MTRUnitTestingClusterNestedStructList {}
open class MTRTestClusterClusterNullablesAndOptionalsStruct: MTRUnitTestingClusterNullablesAndOptionalsStruct {}
open class MTRTestClusterClusterSimpleStruct: MTRUnitTestingClusterSimpleStruct {}
open class MTRTestClusterClusterTestEventEvent: MTRUnitTestingClusterTestEventEvent {}
open class MTRTestClusterClusterTestFabricScoped: MTRUnitTestingClusterTestFabricScoped {}
open class MTRTestClusterClusterTestFabricScopedEventEvent: MTRUnitTestingClusterTestFabricScopedEventEvent {}
open class MTRTestClusterClusterTestListStructOctet: MTRUnitTestingClusterTestListStructOctet {}
open class MTRThermostatClusterThermostatScheduleTransition: MTRThermostatClusterWeeklyScheduleTransitionStruct {}
open class MTRThreadNetworkDiagnosticsClusterNeighborTable: MTRThreadNetworkDiagnosticsClusterNeighborTableStruct {}
open class MTRThreadNetworkDiagnosticsClusterRouteTable: MTRThreadNetworkDiagnosticsClusterRouteTableStruct {}
open class MTRContentLauncherClusterLaunchResponseParams: MTRContentLauncherClusterLauncherResponseParams {}
open class MTRTestClusterClusterBooleanResponseParams: MTRUnitTestingClusterBooleanResponseParams {}
open class MTRTestClusterClusterSimpleStructEchoRequestParams: MTRUnitTestingClusterSimpleStructEchoRequestParams {}
open class MTRTestClusterClusterSimpleStructResponseParams: MTRUnitTestingClusterSimpleStructResponseParams {}
open class MTRTestClusterClusterTestAddArgumentsParams: MTRUnitTestingClusterTestAddArgumentsParams {}
open class MTRTestClusterClusterTestAddArgumentsResponseParams: MTRUnitTestingClusterTestAddArgumentsResponseParams {}
open class MTRTestClusterClusterTestComplexNullableOptionalRequestParams: MTRUnitTestingClusterTestComplexNullableOptionalRequestParams {}
open class MTRTestClusterClusterTestComplexNullableOptionalResponseParams: MTRUnitTestingClusterTestComplexNullableOptionalResponseParams {}
open class MTRTestClusterClusterTestEmitTestEventRequestParams: MTRUnitTestingClusterTestEmitTestEventRequestParams {}
open class MTRTestClusterClusterTestEmitTestEventResponseParams: MTRUnitTestingClusterTestEmitTestEventResponseParams {}
open class MTRTestClusterClusterTestEmitTestFabricScopedEventRequestParams: MTRUnitTestingClusterTestEmitTestFabricScopedEventRequestParams {}
open class MTRTestClusterClusterTestEmitTestFabricScopedEventResponseParams: MTRUnitTestingClusterTestEmitTestFabricScopedEventResponseParams {}
open class MTRTestClusterClusterTestEnumsRequestParams: MTRUnitTestingClusterTestEnumsRequestParams {}
open class MTRTestClusterClusterTestEnumsResponseParams: MTRUnitTestingClusterTestEnumsResponseParams {}
open class MTRTestClusterClusterTestListInt8UArgumentRequestParams: MTRUnitTestingClusterTestListInt8UArgumentRequestParams {}
open class MTRTestClusterClusterTestListInt8UReverseRequestParams: MTRUnitTestingClusterTestListInt8UReverseRequestParams {}
open class MTRTestClusterClusterTestListInt8UReverseResponseParams: MTRUnitTestingClusterTestListInt8UReverseResponseParams {}
open class MTRTestClusterClusterTestListNestedStructListArgumentRequestParams: MTRUnitTestingClusterTestListNestedStructListArgumentRequestParams {}
open class MTRTestClusterClusterTestListStructArgumentRequestParams: MTRUnitTestingClusterTestListStructArgumentRequestParams {}
open class MTRTestClusterClusterTestNestedStructArgumentRequestParams: MTRUnitTestingClusterTestNestedStructArgumentRequestParams {}
open class MTRTestClusterClusterTestNestedStructListArgumentRequestParams: MTRUnitTestingClusterTestNestedStructListArgumentRequestParams {}
open class MTRTestClusterClusterTestNotHandledParams: MTRUnitTestingClusterTestNotHandledParams {}
open class MTRTestClusterClusterTestNullableOptionalRequestParams: MTRUnitTestingClusterTestNullableOptionalRequestParams {}
open class MTRTestClusterClusterTestNullableOptionalResponseParams: MTRUnitTestingClusterTestNullableOptionalResponseParams {}
open class MTRTestClusterClusterTestParams: MTRUnitTestingClusterTestParams {}
open class MTRTestClusterClusterTestSimpleArgumentRequestParams: MTRUnitTestingClusterTestSimpleArgumentRequestParams {}
open class MTRTestClusterClusterTestSimpleArgumentResponseParams: MTRUnitTestingClusterTestSimpleArgumentResponseParams {}
open class MTRTestClusterClusterTestSimpleOptionalArgumentRequestParams: MTRUnitTestingClusterTestSimpleOptionalArgumentRequestParams {}
open class MTRTestClusterClusterTestSpecificParams: MTRUnitTestingClusterTestSpecificParams {}
open class MTRTestClusterClusterTestSpecificResponseParams: MTRUnitTestingClusterTestSpecificResponseParams {}
open class MTRTestClusterClusterTestStructArgumentRequestParams: MTRUnitTestingClusterTestStructArgumentRequestParams {}
open class MTRTestClusterClusterTestStructArrayArgumentRequestParams: MTRUnitTestingClusterTestStructArrayArgumentRequestParams {}
open class MTRTestClusterClusterTestStructArrayArgumentResponseParams: MTRUnitTestingClusterTestStructArrayArgumentResponseParams {}
open class MTRTestClusterClusterTestUnknownCommandParams: MTRUnitTestingClusterTestUnknownCommandParams {}
open class MTRTestClusterClusterTimedInvokeRequestParams: MTRUnitTestingClusterTimedInvokeRequestParams {}
open class MTRClusterBasic: MTRClusterBasicInformation {}
open class MTRClusterBridgedDeviceBasic: MTRClusterBridgedDeviceBasicInformation {}
open class MTRClusterTestCluster: MTRClusterUnitTesting {}
open class MTRBaseClusterBasic: MTRBaseClusterBasicInformation {}
open class MTRBaseClusterBridgedDeviceBasic: MTRBaseClusterBridgedDeviceBasicInformation {}
open class MTRBaseClusterTestCluster: MTRBaseClusterUnitTesting {}
