import Foundation
import Accessibility

func testFeatureOverrideOptionsMembers() {
    precondition(AXFeatureOverrideSession.Options.grayscale.rawValue == 1 << 0)
    precondition(AXFeatureOverrideSession.Options.invertColors.rawValue == 1 << 1)
    precondition(AXFeatureOverrideSession.Options.voiceControl.rawValue == 1 << 2)
    precondition(AXFeatureOverrideSession.Options.voiceOver.rawValue == 1 << 3)
    precondition(AXFeatureOverrideSession.Options.zoom.rawValue == 1 << 4)
    let empty = AXFeatureOverrideSession.Options()
    precondition(empty.rawValue == 0)
    precondition(empty.isEmpty)
    let fromRaw = AXFeatureOverrideSession.Options(rawValue: 1 << 0)
    precondition(fromRaw == .grayscale)
    let literal: AXFeatureOverrideSession.Options = [.grayscale, .zoom]
    precondition(literal.contains(.grayscale))
    precondition(literal.contains(.zoom))
    let fromSequence = AXFeatureOverrideSession.Options([.invertColors, .voiceOver])
    precondition(fromSequence.contains(.invertColors))
    precondition(fromSequence.contains(.voiceOver))
    precondition(AXFeatureOverrideSession.Options.grayscale != .zoom)
}

func testFeatureOverrideOptionsAlgebra() {
    var options: AXFeatureOverrideSession.Options = [.grayscale, .voiceOver]
    precondition(options.contains(.grayscale))
    precondition(!options.contains(.zoom))
    precondition(options.union(.zoom).contains(.zoom))
    precondition(options.intersection(.voiceOver) == .voiceOver)
    precondition(options.symmetricDifference(.voiceOver) == .grayscale)
    precondition(options.subtracting(.grayscale) == .voiceOver)
    precondition(options.isSuperset(of: .voiceOver))
    precondition(options.isSubset(of: [.grayscale, .voiceOver, .zoom]))
    precondition(!options.isDisjoint(with: .grayscale))
    precondition(options.isDisjoint(with: .zoom))
    precondition(options.isStrictSubset(of: [.grayscale, .voiceOver, .invertColors]))
    precondition(options.isStrictSuperset(of: .grayscale))
    options.formUnion(.zoom)
    precondition(options.contains(.zoom))
    options.formIntersection([.zoom, .voiceOver])
    precondition(options == [.zoom, .voiceOver])
    options.formSymmetricDifference(.voiceOver)
    precondition(options == .zoom)
    options.subtract(.zoom)
    precondition(options.isEmpty)
    var insertable = AXFeatureOverrideSession.Options()
    let inserted = insertable.insert(.invertColors)
    precondition(inserted.inserted)
    precondition(insertable.contains(.invertColors))
    let removed = insertable.remove(.invertColors)
    precondition(removed == .invertColors)
    let updated = insertable.update(with: .voiceControl)
    precondition(updated == nil)
    precondition(insertable.contains(.voiceControl))
}

func testHearingEarMembers() {
    precondition(AXMFiHearingDevice.Ear.left.rawValue == 1 << 1)
    precondition(AXMFiHearingDevice.Ear.right.rawValue == 1 << 2)
    precondition(AXMFiHearingDevice.Ear.both.rawValue == (1 << 1) | (1 << 2))
    let empty = AXMFiHearingDevice.Ear()
    precondition(empty.rawValue == 0)
    precondition(empty.isEmpty)
    let fromRaw = AXMFiHearingDevice.Ear(rawValue: 1 << 1)
    precondition(fromRaw == .left)
    let literal: AXMFiHearingDevice.Ear = [.left, .right]
    precondition(literal == .both)
    let fromSequence = AXMFiHearingDevice.Ear([.left])
    precondition(fromSequence == .left)
    precondition(AXMFiHearingDevice.Ear.left != .right)
}

func testHearingEarAlgebra() {
    var ear: AXMFiHearingDevice.Ear = [.left]
    precondition(ear.contains(.left))
    precondition(!ear.contains(.right))
    precondition(ear.union(.right) == .both)
    precondition(AXMFiHearingDevice.Ear.both.intersection(.left) == .left)
    precondition(AXMFiHearingDevice.Ear.both.symmetricDifference(.left) == .right)
    precondition(AXMFiHearingDevice.Ear.both.subtracting(.right) == .left)
    precondition(AXMFiHearingDevice.Ear.both.isSuperset(of: .left))
    precondition(ear.isSubset(of: .both))
    precondition(ear.isDisjoint(with: .right))
    precondition(ear.isStrictSubset(of: .both))
    precondition(AXMFiHearingDevice.Ear.both.isStrictSuperset(of: .left))
    ear.formUnion(.right)
    precondition(ear == .both)
    ear.formIntersection(.left)
    precondition(ear == .left)
    ear.formSymmetricDifference(.both)
    precondition(ear == .right)
    ear.subtract(.right)
    precondition(ear.isEmpty)
    var insertable = AXMFiHearingDevice.Ear()
    let inserted = insertable.insert(.left)
    precondition(inserted.inserted)
    let removed = insertable.remove(.left)
    precondition(removed == .left)
    let updated = insertable.update(with: .right)
    precondition(updated == nil)
    precondition(insertable.contains(.right))
}
