import Foundation
import Dispatch
import Matter

func testBallastFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRBaseClusterBallastConfiguration(device: baseDevice, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRBaseClusterBallastConfiguration init")
        return
    }
    cluster.readAttributeAcceptedCommandList(completion: { _, _ in })
    cluster.readAttributeAcceptedCommandList(completionHandler: { _, _ in })
    cluster.readAttributeAttributeList(completion: { _, _ in })
    cluster.readAttributeAttributeList(completionHandler: { _, _ in })
    cluster.readAttributeBallastFactorAdjustment(completion: { _, _ in })
    cluster.readAttributeBallastFactorAdjustment(completionHandler: { _, _ in })
    cluster.readAttributeBallastStatus(completion: { _, _ in })
    cluster.readAttributeBallastStatus(completionHandler: { _, _ in })
    cluster.readAttributeClusterRevision(completion: { _, _ in })
    cluster.readAttributeClusterRevision(completionHandler: { _, _ in })
    cluster.readAttributeFeatureMap(completion: { _, _ in })
    cluster.readAttributeFeatureMap(completionHandler: { _, _ in })
    cluster.readAttributeGeneratedCommandList(completion: { _, _ in })
    cluster.readAttributeGeneratedCommandList(completionHandler: { _, _ in })
    cluster.readAttributeIntrinsicBalanceFactor(completionHandler: { _, _ in })
    cluster.readAttributeIntrinsicBallastFactor(completion: { _, _ in })
    cluster.readAttributeLampAlarmMode(completion: { _, _ in })
    cluster.readAttributeLampAlarmMode(completionHandler: { _, _ in })
    cluster.readAttributeLampBurnHoursTripPoint(completion: { _, _ in })
    cluster.readAttributeLampBurnHoursTripPoint(completionHandler: { _, _ in })
    cluster.readAttributeLampBurnHours(completion: { _, _ in })
    cluster.readAttributeLampBurnHours(completionHandler: { _, _ in })
    cluster.readAttributeLampManufacturer(completion: { _, _ in })
    cluster.readAttributeLampManufacturer(completionHandler: { _, _ in })
    cluster.readAttributeLampQuantity(completion: { _, _ in })
    cluster.readAttributeLampQuantity(completionHandler: { _, _ in })
    cluster.readAttributeLampRatedHours(completion: { _, _ in })
    cluster.readAttributeLampRatedHours(completionHandler: { _, _ in })
    cluster.readAttributeLampType(completion: { _, _ in })
    cluster.readAttributeLampType(completionHandler: { _, _ in })
    cluster.readAttributeMaxLevel(completion: { _, _ in })
    cluster.readAttributeMaxLevel(completionHandler: { _, _ in })
    cluster.readAttributeMinLevel(completion: { _, _ in })
    cluster.readAttributeMinLevel(completionHandler: { _, _ in })
    cluster.readAttributePhysicalMaxLevel(completion: { _, _ in })
    cluster.readAttributePhysicalMaxLevel(completionHandler: { _, _ in })
    cluster.readAttributePhysicalMinLevel(completion: { _, _ in })
    cluster.readAttributePhysicalMinLevel(completionHandler: { _, _ in })
    cluster.subscribeAttributeAcceptedCommandList(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcceptedCommandList(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAttributeList(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAttributeList(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeBallastFactorAdjustment(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeBallastFactorAdjustment(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeBallastStatus(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeBallastStatus(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeClusterRevision(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeClusterRevision(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeFeatureMap(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeFeatureMap(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeGeneratedCommandList(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeGeneratedCommandList(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeIntrinsicBalanceFactor(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeIntrinsicBallastFactor(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLampAlarmMode(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLampAlarmMode(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLampBurnHoursTripPoint(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLampBurnHoursTripPoint(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLampBurnHours(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLampBurnHours(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLampManufacturer(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLampManufacturer(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLampQuantity(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLampQuantity(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLampRatedHours(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLampRatedHours(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLampType(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLampType(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMaxLevel(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMaxLevel(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMinLevel(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMinLevel(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePhysicalMaxLevel(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePhysicalMaxLevel(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePhysicalMinLevel(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePhysicalMinLevel(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
}
