import Foundation
import Dispatch
import Matter

func testBaseLevelControlClassCacheFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    MTRBaseClusterLevelControl.readAttributeAcceptedCommandList(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeAcceptedCommandList(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeAttributeList(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeAttributeList(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeClusterRevision(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeClusterRevision(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeCurrentFrequency(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeCurrentFrequency(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeCurrentLevel(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeCurrentLevel(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeDefaultMoveRate(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeDefaultMoveRate(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeFeatureMap(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeFeatureMap(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeGeneratedCommandList(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeGeneratedCommandList(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeMaxFrequency(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeMaxFrequency(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeMaxLevel(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeMaxLevel(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeMinFrequency(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeMinFrequency(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeMinLevel(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeMinLevel(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeOffTransitionTime(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeOffTransitionTime(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeOnLevel(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeOnLevel(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeOnOffTransitionTime(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeOnOffTransitionTime(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeOnTransitionTime(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeOnTransitionTime(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeOptions(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeOptions(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeRemainingTime(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeRemainingTime(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeStartUpCurrentLevel(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterLevelControl.readAttributeStartUpCurrentLevel(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
}

func testBaseLevelControlCommandFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRBaseClusterLevelControl(device: baseDevice, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRBaseClusterLevelControl init")
        return
    }
    cluster.moveToClosestFrequency(with: MTRLevelControlClusterMoveToClosestFrequencyParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.moveToClosestFrequency(with: MTRLevelControlClusterMoveToClosestFrequencyParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.moveToLevelWithOnOff(with: MTRLevelControlClusterMoveToLevelWithOnOffParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.moveToLevelWithOnOff(with: MTRLevelControlClusterMoveToLevelWithOnOffParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.moveToLevel(with: MTRLevelControlClusterMoveToLevelParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.moveToLevel(with: MTRLevelControlClusterMoveToLevelParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.moveWithOnOff(with: MTRLevelControlClusterMoveWithOnOffParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.moveWithOnOff(with: MTRLevelControlClusterMoveWithOnOffParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.move(with: MTRLevelControlClusterMoveParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.move(with: MTRLevelControlClusterMoveParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.stepWithOnOff(with: MTRLevelControlClusterStepWithOnOffParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.stepWithOnOff(with: MTRLevelControlClusterStepWithOnOffParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.step(with: MTRLevelControlClusterStepParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.step(with: MTRLevelControlClusterStepParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.stopWithOnOff(with: MTRLevelControlClusterStopWithOnOffParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.stopWithOnOff(with: MTRLevelControlClusterStopWithOnOffParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.stop(with: MTRLevelControlClusterStopParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.stop(with: MTRLevelControlClusterStopParams(), completionHandler: { err in mtrExpectInvalidState(err) })
}

func testBaseLevelControlWriteFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRBaseClusterLevelControl(device: baseDevice, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRBaseClusterLevelControl init")
        return
    }
    cluster.writeAttributeDefaultMoveRate(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeDefaultMoveRate(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeDefaultMoveRate(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeDefaultMoveRate(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOffTransitionTime(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOffTransitionTime(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOffTransitionTime(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOffTransitionTime(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOnLevel(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOnLevel(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOnLevel(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOnLevel(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOnOffTransitionTime(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOnOffTransitionTime(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOnOffTransitionTime(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOnOffTransitionTime(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOnTransitionTime(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOnTransitionTime(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOnTransitionTime(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOnTransitionTime(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOptions(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOptions(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOptions(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOptions(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeStartUpCurrentLevel(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeStartUpCurrentLevel(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeStartUpCurrentLevel(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeStartUpCurrentLevel(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
}
