import Foundation
import Matter

func testOptionSetRawValues() {
    mtrRequire(MTRDiscoveryCapabilities.softAP.rawValue == 1, "softAP")
    mtrRequire(MTRDiscoveryCapabilities.BLE.rawValue == 2, "BLE")
    mtrRequire(MTRDiscoveryCapabilities.onNetwork.rawValue == 4, "onNetwork")
    mtrRequire(MTRDiscoveryCapabilities.allMask.rawValue == 7, "allMask")
    mtrRequire(MTRDiscoveryCapabilities([.softAP, .BLE, .onNetwork]) == .allMask, "union mask")
    _ = MTRAccessControlFeature.self
    mtrRequire(MTRAccessControlFeature.`extension`.rawValue == 1, "MTRAccessControlFeature.extension")
    mtrRequire(MTRAccessControlFeature.managedDevice.rawValue == 2, "MTRAccessControlFeature.managedDevice")
    _ = MTRActionsCommandBits.self
    mtrRequire(MTRActionsCommandBits.instantAction.rawValue == 1, "MTRActionsCommandBits.instantAction")
    mtrRequire(MTRActionsCommandBits.instantActionWithTransition.rawValue == 2, "MTRActionsCommandBits.instantActionWithTransition")
    mtrRequire(MTRActionsCommandBits.startAction.rawValue == 4, "MTRActionsCommandBits.startAction")
    mtrRequire(MTRActionsCommandBits.startActionWithDuration.rawValue == 8, "MTRActionsCommandBits.startActionWithDuration")
    mtrRequire(MTRActionsCommandBits.stopAction.rawValue == 16, "MTRActionsCommandBits.stopAction")
    mtrRequire(MTRActionsCommandBits.pauseAction.rawValue == 32, "MTRActionsCommandBits.pauseAction")
    mtrRequire(MTRActionsCommandBits.pauseActionWithDuration.rawValue == 64, "MTRActionsCommandBits.pauseActionWithDuration")
    mtrRequire(MTRActionsCommandBits.resumeAction.rawValue == 128, "MTRActionsCommandBits.resumeAction")
    mtrRequire(MTRActionsCommandBits.enableAction.rawValue == 256, "MTRActionsCommandBits.enableAction")
    mtrRequire(MTRActionsCommandBits.enableActionWithDuration.rawValue == 512, "MTRActionsCommandBits.enableActionWithDuration")
    mtrRequire(MTRActionsCommandBits.disableAction.rawValue == 1024, "MTRActionsCommandBits.disableAction")
    mtrRequire(MTRActionsCommandBits.disableActionWithDuration.rawValue == 2048, "MTRActionsCommandBits.disableActionWithDuration")
    _ = MTRActivatedCarbonFilterMonitoringFeature.self
    mtrRequire(MTRActivatedCarbonFilterMonitoringFeature.condition.rawValue == 1, "MTRActivatedCarbonFilterMonitoringFeature.condition")
    mtrRequire(MTRActivatedCarbonFilterMonitoringFeature.warning.rawValue == 2, "MTRActivatedCarbonFilterMonitoringFeature.warning")
    mtrRequire(MTRActivatedCarbonFilterMonitoringFeature.replacementProductList.rawValue == 4, "MTRActivatedCarbonFilterMonitoringFeature.replacementProductList")
    _ = MTRAdministratorCommissioningFeature.self
    mtrRequire(MTRAdministratorCommissioningFeature.basic.rawValue == 1, "MTRAdministratorCommissioningFeature.basic")
    _ = MTRAirQualityFeature.self
    mtrRequire(MTRAirQualityFeature.fair.rawValue == 1, "MTRAirQualityFeature.fair")
    mtrRequire(MTRAirQualityFeature.moderate.rawValue == 2, "MTRAirQualityFeature.moderate")
    mtrRequire(MTRAirQualityFeature.veryPoor.rawValue == 4, "MTRAirQualityFeature.veryPoor")
    mtrRequire(MTRAirQualityFeature.extremelyPoor.rawValue == 8, "MTRAirQualityFeature.extremelyPoor")
    _ = MTRApplicationLauncherFeature.self
    mtrRequire(MTRApplicationLauncherFeature.applicationPlatform.rawValue == 1, "MTRApplicationLauncherFeature.applicationPlatform")
    _ = MTRAudioOutputFeature.self
    mtrRequire(MTRAudioOutputFeature.nameUpdates.rawValue == 1, "MTRAudioOutputFeature.nameUpdates")
    _ = MTRBooleanStateConfigurationAlarmModeBitmap.self
    mtrRequire(MTRBooleanStateConfigurationAlarmModeBitmap.visual.rawValue == 1, "MTRBooleanStateConfigurationAlarmModeBitmap.visual")
    mtrRequire(MTRBooleanStateConfigurationAlarmModeBitmap.audible.rawValue == 2, "MTRBooleanStateConfigurationAlarmModeBitmap.audible")
    _ = MTRBooleanStateConfigurationFeature.self
    mtrRequire(MTRBooleanStateConfigurationFeature.visual.rawValue == 1, "MTRBooleanStateConfigurationFeature.visual")
    mtrRequire(MTRBooleanStateConfigurationFeature.audible.rawValue == 2, "MTRBooleanStateConfigurationFeature.audible")
    mtrRequire(MTRBooleanStateConfigurationFeature.alarmSuppress.rawValue == 4, "MTRBooleanStateConfigurationFeature.alarmSuppress")
    mtrRequire(MTRBooleanStateConfigurationFeature.sensitivityLevel.rawValue == 8, "MTRBooleanStateConfigurationFeature.sensitivityLevel")
    _ = MTRBooleanStateConfigurationSensorFaultBitmap.self
    mtrRequire(MTRBooleanStateConfigurationSensorFaultBitmap.generalFault.rawValue == 1, "MTRBooleanStateConfigurationSensorFaultBitmap.generalFault")
    _ = MTRBridgedDeviceBasicInformationFeature.self
    mtrRequire(MTRBridgedDeviceBasicInformationFeature.bridgedICDSupport.rawValue == 1, "MTRBridgedDeviceBasicInformationFeature.bridgedICDSupport")
    _ = MTRCarbonDioxideConcentrationMeasurementFeature.self
    mtrRequire(MTRCarbonDioxideConcentrationMeasurementFeature.numericMeasurement.rawValue == 1, "MTRCarbonDioxideConcentrationMeasurementFeature.numericMeasurement")
    mtrRequire(MTRCarbonDioxideConcentrationMeasurementFeature.levelIndication.rawValue == 2, "MTRCarbonDioxideConcentrationMeasurementFeature.levelIndication")
    mtrRequire(MTRCarbonDioxideConcentrationMeasurementFeature.mediumLevel.rawValue == 4, "MTRCarbonDioxideConcentrationMeasurementFeature.mediumLevel")
    mtrRequire(MTRCarbonDioxideConcentrationMeasurementFeature.criticalLevel.rawValue == 8, "MTRCarbonDioxideConcentrationMeasurementFeature.criticalLevel")
    mtrRequire(MTRCarbonDioxideConcentrationMeasurementFeature.peakMeasurement.rawValue == 16, "MTRCarbonDioxideConcentrationMeasurementFeature.peakMeasurement")
    mtrRequire(MTRCarbonDioxideConcentrationMeasurementFeature.averageMeasurement.rawValue == 32, "MTRCarbonDioxideConcentrationMeasurementFeature.averageMeasurement")
    _ = MTRCarbonMonoxideConcentrationMeasurementFeature.self
    mtrRequire(MTRCarbonMonoxideConcentrationMeasurementFeature.numericMeasurement.rawValue == 1, "MTRCarbonMonoxideConcentrationMeasurementFeature.numericMeasurement")
    mtrRequire(MTRCarbonMonoxideConcentrationMeasurementFeature.levelIndication.rawValue == 2, "MTRCarbonMonoxideConcentrationMeasurementFeature.levelIndication")
    mtrRequire(MTRCarbonMonoxideConcentrationMeasurementFeature.mediumLevel.rawValue == 4, "MTRCarbonMonoxideConcentrationMeasurementFeature.mediumLevel")
    mtrRequire(MTRCarbonMonoxideConcentrationMeasurementFeature.criticalLevel.rawValue == 8, "MTRCarbonMonoxideConcentrationMeasurementFeature.criticalLevel")
    mtrRequire(MTRCarbonMonoxideConcentrationMeasurementFeature.peakMeasurement.rawValue == 16, "MTRCarbonMonoxideConcentrationMeasurementFeature.peakMeasurement")
    mtrRequire(MTRCarbonMonoxideConcentrationMeasurementFeature.averageMeasurement.rawValue == 32, "MTRCarbonMonoxideConcentrationMeasurementFeature.averageMeasurement")
    _ = MTRChannelFeature.self
    mtrRequire(MTRChannelFeature.channelList.rawValue == 1, "MTRChannelFeature.channelList")
    mtrRequire(MTRChannelFeature.lineupInfo.rawValue == 2, "MTRChannelFeature.lineupInfo")
    mtrRequire(MTRChannelFeature.electronicGuide.rawValue == 4, "MTRChannelFeature.electronicGuide")
    mtrRequire(MTRChannelFeature.recordProgram.rawValue == 8, "MTRChannelFeature.recordProgram")
    _ = MTRChannelRecordingFlagBitmap.self
    mtrRequire(MTRChannelRecordingFlagBitmap.scheduled.rawValue == 1, "MTRChannelRecordingFlagBitmap.scheduled")
    mtrRequire(MTRChannelRecordingFlagBitmap.recordSeries.rawValue == 2, "MTRChannelRecordingFlagBitmap.recordSeries")
    mtrRequire(MTRChannelRecordingFlagBitmap.recorded.rawValue == 4, "MTRChannelRecordingFlagBitmap.recorded")
    _ = MTRColorControlColorCapabilities.self
    mtrRequire(MTRColorControlColorCapabilities.hueSaturationSupported.rawValue == 1, "MTRColorControlColorCapabilities.hueSaturationSupported")
    mtrRequire(MTRColorControlColorCapabilities.enhancedHueSupported.rawValue == 2, "MTRColorControlColorCapabilities.enhancedHueSupported")
    mtrRequire(MTRColorControlColorCapabilities.colorLoopSupported.rawValue == 4, "MTRColorControlColorCapabilities.colorLoopSupported")
    mtrRequire(MTRColorControlColorCapabilities.xyAttributesSupported.rawValue == 8, "MTRColorControlColorCapabilities.xyAttributesSupported")
    mtrRequire(MTRColorControlColorCapabilities.colorTemperatureSupported.rawValue == 16, "MTRColorControlColorCapabilities.colorTemperatureSupported")
    _ = MTRColorControlColorCapabilitiesBitmap.self
    mtrRequire(MTRColorControlColorCapabilitiesBitmap.hueSaturation.rawValue == 1, "MTRColorControlColorCapabilitiesBitmap.hueSaturation")
    mtrRequire(MTRColorControlColorCapabilitiesBitmap.enhancedHue.rawValue == 2, "MTRColorControlColorCapabilitiesBitmap.enhancedHue")
    mtrRequire(MTRColorControlColorCapabilitiesBitmap.colorLoop.rawValue == 4, "MTRColorControlColorCapabilitiesBitmap.colorLoop")
    mtrRequire(MTRColorControlColorCapabilitiesBitmap.XY.rawValue == 8, "MTRColorControlColorCapabilitiesBitmap.XY")
    mtrRequire(MTRColorControlColorCapabilitiesBitmap.colorTemperature.rawValue == 16, "MTRColorControlColorCapabilitiesBitmap.colorTemperature")
    _ = MTRColorControlColorLoopUpdateFlags.self
    mtrRequire(MTRColorControlColorLoopUpdateFlags.updateAction.rawValue == 1, "MTRColorControlColorLoopUpdateFlags.updateAction")
    mtrRequire(MTRColorControlColorLoopUpdateFlags.updateDirection.rawValue == 2, "MTRColorControlColorLoopUpdateFlags.updateDirection")
    mtrRequire(MTRColorControlColorLoopUpdateFlags.updateTime.rawValue == 4, "MTRColorControlColorLoopUpdateFlags.updateTime")
    mtrRequire(MTRColorControlColorLoopUpdateFlags.updateStartHue.rawValue == 8, "MTRColorControlColorLoopUpdateFlags.updateStartHue")
    _ = MTRColorControlFeature.self
    mtrRequire(MTRColorControlFeature.hueAndSaturation.rawValue == 1, "MTRColorControlFeature.hueAndSaturation")
    mtrRequire(MTRColorControlFeature.enhancedHue.rawValue == 2, "MTRColorControlFeature.enhancedHue")
    mtrRequire(MTRColorControlFeature.colorLoop.rawValue == 4, "MTRColorControlFeature.colorLoop")
    mtrRequire(MTRColorControlFeature.XY.rawValue == 8, "MTRColorControlFeature.XY")
    mtrRequire(MTRColorControlFeature.colorTemperature.rawValue == 16, "MTRColorControlFeature.colorTemperature")
    _ = MTRColorControlOptionsBitmap.self
    mtrRequire(MTRColorControlOptionsBitmap.executeIfOff.rawValue == 1, "MTRColorControlOptionsBitmap.executeIfOff")
    _ = MTRColorControlUpdateFlagsBitmap.self
    mtrRequire(MTRColorControlUpdateFlagsBitmap.updateAction.rawValue == 1, "MTRColorControlUpdateFlagsBitmap.updateAction")
    mtrRequire(MTRColorControlUpdateFlagsBitmap.updateDirection.rawValue == 2, "MTRColorControlUpdateFlagsBitmap.updateDirection")
    mtrRequire(MTRColorControlUpdateFlagsBitmap.updateTime.rawValue == 4, "MTRColorControlUpdateFlagsBitmap.updateTime")
    mtrRequire(MTRColorControlUpdateFlagsBitmap.updateStartHue.rawValue == 8, "MTRColorControlUpdateFlagsBitmap.updateStartHue")
    _ = MTRCommissionerControlSupportedDeviceCategoryBitmap.self
    mtrRequire(MTRCommissionerControlSupportedDeviceCategoryBitmap.fabricSynchronization.rawValue == 1, "MTRCommissionerControlSupportedDeviceCategoryBitmap.fabricSynchronization")
    _ = MTRContentLauncherFeature.self
    mtrRequire(MTRContentLauncherFeature.contentSearch.rawValue == 1, "MTRContentLauncherFeature.contentSearch")
    mtrRequire(MTRContentLauncherFeature.urlPlayback.rawValue == 2, "MTRContentLauncherFeature.urlPlayback")
    mtrRequire(MTRContentLauncherFeature.advancedSeek.rawValue == 4, "MTRContentLauncherFeature.advancedSeek")
    mtrRequire(MTRContentLauncherFeature.textTracks.rawValue == 8, "MTRContentLauncherFeature.textTracks")
    mtrRequire(MTRContentLauncherFeature.audioTracks.rawValue == 16, "MTRContentLauncherFeature.audioTracks")
    _ = MTRContentLauncherSupportedProtocolsBitmap.self
    mtrRequire(MTRContentLauncherSupportedProtocolsBitmap.DASH.rawValue == 1, "MTRContentLauncherSupportedProtocolsBitmap.DASH")
    mtrRequire(MTRContentLauncherSupportedProtocolsBitmap.HLS.rawValue == 2, "MTRContentLauncherSupportedProtocolsBitmap.HLS")
    _ = MTRContentLauncherSupportedStreamingProtocol.self
    mtrRequire(MTRContentLauncherSupportedStreamingProtocol.DASH.rawValue == 1, "MTRContentLauncherSupportedStreamingProtocol.DASH")
    mtrRequire(MTRContentLauncherSupportedStreamingProtocol.HLS.rawValue == 2, "MTRContentLauncherSupportedStreamingProtocol.HLS")
    _ = MTRDeviceEnergyManagementFeature.self
    mtrRequire(MTRDeviceEnergyManagementFeature.powerAdjustment.rawValue == 1, "MTRDeviceEnergyManagementFeature.powerAdjustment")
    mtrRequire(MTRDeviceEnergyManagementFeature.powerForecastReporting.rawValue == 2, "MTRDeviceEnergyManagementFeature.powerForecastReporting")
    mtrRequire(MTRDeviceEnergyManagementFeature.stateForecastReporting.rawValue == 4, "MTRDeviceEnergyManagementFeature.stateForecastReporting")
    mtrRequire(MTRDeviceEnergyManagementFeature.startTimeAdjustment.rawValue == 8, "MTRDeviceEnergyManagementFeature.startTimeAdjustment")
    mtrRequire(MTRDeviceEnergyManagementFeature.pausable.rawValue == 16, "MTRDeviceEnergyManagementFeature.pausable")
    mtrRequire(MTRDeviceEnergyManagementFeature.forecastAdjustment.rawValue == 32, "MTRDeviceEnergyManagementFeature.forecastAdjustment")
    mtrRequire(MTRDeviceEnergyManagementFeature.constraintBasedAdjustment.rawValue == 64, "MTRDeviceEnergyManagementFeature.constraintBasedAdjustment")
    _ = MTRDiscoveryCapabilities.self
    mtrRequire(MTRDiscoveryCapabilities.softAP.rawValue == 1, "MTRDiscoveryCapabilities.softAP")
    mtrRequire(MTRDiscoveryCapabilities.BLE.rawValue == 2, "MTRDiscoveryCapabilities.BLE")
    mtrRequire(MTRDiscoveryCapabilities.onNetwork.rawValue == 4, "MTRDiscoveryCapabilities.onNetwork")
    mtrRequire(MTRDiscoveryCapabilities.allMask.rawValue == 7, "MTRDiscoveryCapabilities.allMask")
    _ = MTRDishwasherAlarmAlarmBitmap.self
    mtrRequire(MTRDishwasherAlarmAlarmBitmap.doorError.rawValue == 1, "MTRDishwasherAlarmAlarmBitmap.doorError")
    _ = MTRDishwasherAlarmFeature.self
    mtrRequire(MTRDishwasherAlarmFeature.reset.rawValue == 1, "MTRDishwasherAlarmFeature.reset")
    _ = MTRDoorLockDayOfWeek.self
    mtrRequire(MTRDoorLockDayOfWeek.sunday.rawValue == 1, "MTRDoorLockDayOfWeek.sunday")
    mtrRequire(MTRDoorLockDayOfWeek.monday.rawValue == 2, "MTRDoorLockDayOfWeek.monday")
    mtrRequire(MTRDoorLockDayOfWeek.tuesday.rawValue == 4, "MTRDoorLockDayOfWeek.tuesday")
    mtrRequire(MTRDoorLockDayOfWeek.wednesday.rawValue == 8, "MTRDoorLockDayOfWeek.wednesday")
    mtrRequire(MTRDoorLockDayOfWeek.thursday.rawValue == 16, "MTRDoorLockDayOfWeek.thursday")
    mtrRequire(MTRDoorLockDayOfWeek.friday.rawValue == 32, "MTRDoorLockDayOfWeek.friday")
    mtrRequire(MTRDoorLockDayOfWeek.saturday.rawValue == 64, "MTRDoorLockDayOfWeek.saturday")
    _ = MTRDoorLockDaysMaskMap.self
    mtrRequire(MTRDoorLockDaysMaskMap.sunday.rawValue == 1, "MTRDoorLockDaysMaskMap.sunday")
    mtrRequire(MTRDoorLockDaysMaskMap.monday.rawValue == 2, "MTRDoorLockDaysMaskMap.monday")
    mtrRequire(MTRDoorLockDaysMaskMap.tuesday.rawValue == 4, "MTRDoorLockDaysMaskMap.tuesday")
    mtrRequire(MTRDoorLockDaysMaskMap.wednesday.rawValue == 8, "MTRDoorLockDaysMaskMap.wednesday")
    mtrRequire(MTRDoorLockDaysMaskMap.thursday.rawValue == 16, "MTRDoorLockDaysMaskMap.thursday")
    mtrRequire(MTRDoorLockDaysMaskMap.friday.rawValue == 32, "MTRDoorLockDaysMaskMap.friday")
    mtrRequire(MTRDoorLockDaysMaskMap.saturday.rawValue == 64, "MTRDoorLockDaysMaskMap.saturday")
    _ = MTRDoorLockDlCredentialRuleMask.self
    mtrRequire(MTRDoorLockDlCredentialRuleMask.single.rawValue == 1, "MTRDoorLockDlCredentialRuleMask.single")
    mtrRequire(MTRDoorLockDlCredentialRuleMask.dual.rawValue == 2, "MTRDoorLockDlCredentialRuleMask.dual")
    mtrRequire(MTRDoorLockDlCredentialRuleMask.tri.rawValue == 4, "MTRDoorLockDlCredentialRuleMask.tri")
    _ = MTRDoorLockDlCredentialRulesSupport.self
    mtrRequire(MTRDoorLockDlCredentialRulesSupport.single.rawValue == 1, "MTRDoorLockDlCredentialRulesSupport.single")
    mtrRequire(MTRDoorLockDlCredentialRulesSupport.dual.rawValue == 2, "MTRDoorLockDlCredentialRulesSupport.dual")
    mtrRequire(MTRDoorLockDlCredentialRulesSupport.tri.rawValue == 4, "MTRDoorLockDlCredentialRulesSupport.tri")
    _ = MTRDoorLockDlDaysMaskMap.self
    mtrRequire(MTRDoorLockDlDaysMaskMap.sunday.rawValue == 1, "MTRDoorLockDlDaysMaskMap.sunday")
    mtrRequire(MTRDoorLockDlDaysMaskMap.monday.rawValue == 2, "MTRDoorLockDlDaysMaskMap.monday")
    mtrRequire(MTRDoorLockDlDaysMaskMap.tuesday.rawValue == 4, "MTRDoorLockDlDaysMaskMap.tuesday")
    mtrRequire(MTRDoorLockDlDaysMaskMap.wednesday.rawValue == 8, "MTRDoorLockDlDaysMaskMap.wednesday")
    mtrRequire(MTRDoorLockDlDaysMaskMap.thursday.rawValue == 16, "MTRDoorLockDlDaysMaskMap.thursday")
    mtrRequire(MTRDoorLockDlDaysMaskMap.friday.rawValue == 32, "MTRDoorLockDlDaysMaskMap.friday")
    mtrRequire(MTRDoorLockDlDaysMaskMap.saturday.rawValue == 64, "MTRDoorLockDlDaysMaskMap.saturday")
    _ = MTRDoorLockDlDefaultConfigurationRegister.self
    mtrRequire(MTRDoorLockDlDefaultConfigurationRegister.enableLocalProgrammingEnabled.rawValue == 1, "MTRDoorLockDlDefaultConfigurationRegister.enableLocalProgrammingEnabled")
    mtrRequire(MTRDoorLockDlDefaultConfigurationRegister.keypadInterfaceDefaultAccessEnabled.rawValue == 2, "MTRDoorLockDlDefaultConfigurationRegister.keypadInterfaceDefaultAccessEnabled")
    mtrRequire(MTRDoorLockDlDefaultConfigurationRegister.remoteInterfaceDefaultAccessIsEnabled.rawValue == 4, "MTRDoorLockDlDefaultConfigurationRegister.remoteInterfaceDefaultAccessIsEnabled")
    mtrRequire(MTRDoorLockDlDefaultConfigurationRegister.soundEnabled.rawValue == 8, "MTRDoorLockDlDefaultConfigurationRegister.soundEnabled")
    mtrRequire(MTRDoorLockDlDefaultConfigurationRegister.autoRelockTimeSet.rawValue == 16, "MTRDoorLockDlDefaultConfigurationRegister.autoRelockTimeSet")
    mtrRequire(MTRDoorLockDlDefaultConfigurationRegister.ledSettingsSet.rawValue == 32, "MTRDoorLockDlDefaultConfigurationRegister.ledSettingsSet")
    _ = MTRDoorLockDlKeypadOperationEventMask.self
    mtrRequire(MTRDoorLockDlKeypadOperationEventMask.unknown.rawValue == 0, "MTRDoorLockDlKeypadOperationEventMask.unknown")
    mtrRequire(MTRDoorLockDlKeypadOperationEventMask.lock.rawValue == 1, "MTRDoorLockDlKeypadOperationEventMask.lock")
    mtrRequire(MTRDoorLockDlKeypadOperationEventMask.unlock.rawValue == 2, "MTRDoorLockDlKeypadOperationEventMask.unlock")
    mtrRequire(MTRDoorLockDlKeypadOperationEventMask.lockInvalidPIN.rawValue == 4, "MTRDoorLockDlKeypadOperationEventMask.lockInvalidPIN")
    mtrRequire(MTRDoorLockDlKeypadOperationEventMask.lockInvalidSchedule.rawValue == 8, "MTRDoorLockDlKeypadOperationEventMask.lockInvalidSchedule")
    mtrRequire(MTRDoorLockDlKeypadOperationEventMask.unlockInvalidCode.rawValue == 16, "MTRDoorLockDlKeypadOperationEventMask.unlockInvalidCode")
    mtrRequire(MTRDoorLockDlKeypadOperationEventMask.unlockInvalidSchedule.rawValue == 32, "MTRDoorLockDlKeypadOperationEventMask.unlockInvalidSchedule")
    mtrRequire(MTRDoorLockDlKeypadOperationEventMask.nonAccessUserOpEvent.rawValue == 64, "MTRDoorLockDlKeypadOperationEventMask.nonAccessUserOpEvent")
    _ = MTRDoorLockDlKeypadProgrammingEventMask.self
    mtrRequire(MTRDoorLockDlKeypadProgrammingEventMask.unknown.rawValue == 0, "MTRDoorLockDlKeypadProgrammingEventMask.unknown")
    mtrRequire(MTRDoorLockDlKeypadProgrammingEventMask.programmingPINChanged.rawValue == 1, "MTRDoorLockDlKeypadProgrammingEventMask.programmingPINChanged")
    mtrRequire(MTRDoorLockDlKeypadProgrammingEventMask.pinAdded.rawValue == 2, "MTRDoorLockDlKeypadProgrammingEventMask.pinAdded")
    mtrRequire(MTRDoorLockDlKeypadProgrammingEventMask.pinCleared.rawValue == 4, "MTRDoorLockDlKeypadProgrammingEventMask.pinCleared")
    mtrRequire(MTRDoorLockDlKeypadProgrammingEventMask.pinChanged.rawValue == 8, "MTRDoorLockDlKeypadProgrammingEventMask.pinChanged")
    _ = MTRDoorLockDlLocalProgrammingFeatures.self
    mtrRequire(MTRDoorLockDlLocalProgrammingFeatures.addUsersCredentialsSchedulesLocally.rawValue == 1, "MTRDoorLockDlLocalProgrammingFeatures.addUsersCredentialsSchedulesLocally")
    mtrRequire(MTRDoorLockDlLocalProgrammingFeatures.modifyUsersCredentialsSchedulesLocally.rawValue == 2, "MTRDoorLockDlLocalProgrammingFeatures.modifyUsersCredentialsSchedulesLocally")
    mtrRequire(MTRDoorLockDlLocalProgrammingFeatures.clearUsersCredentialsSchedulesLocally.rawValue == 4, "MTRDoorLockDlLocalProgrammingFeatures.clearUsersCredentialsSchedulesLocally")
    mtrRequire(MTRDoorLockDlLocalProgrammingFeatures.adjustLockSettingsLocally.rawValue == 8, "MTRDoorLockDlLocalProgrammingFeatures.adjustLockSettingsLocally")
    _ = MTRDoorLockDlManualOperationEventMask.self
    mtrRequire(MTRDoorLockDlManualOperationEventMask.unknown.rawValue == 0, "MTRDoorLockDlManualOperationEventMask.unknown")
    mtrRequire(MTRDoorLockDlManualOperationEventMask.thumbturnLock.rawValue == 1, "MTRDoorLockDlManualOperationEventMask.thumbturnLock")
    mtrRequire(MTRDoorLockDlManualOperationEventMask.thumbturnUnlock.rawValue == 2, "MTRDoorLockDlManualOperationEventMask.thumbturnUnlock")
    mtrRequire(MTRDoorLockDlManualOperationEventMask.oneTouchLock.rawValue == 4, "MTRDoorLockDlManualOperationEventMask.oneTouchLock")
    mtrRequire(MTRDoorLockDlManualOperationEventMask.keyLock.rawValue == 8, "MTRDoorLockDlManualOperationEventMask.keyLock")
    mtrRequire(MTRDoorLockDlManualOperationEventMask.keyUnlock.rawValue == 16, "MTRDoorLockDlManualOperationEventMask.keyUnlock")
    mtrRequire(MTRDoorLockDlManualOperationEventMask.autoLock.rawValue == 32, "MTRDoorLockDlManualOperationEventMask.autoLock")
    mtrRequire(MTRDoorLockDlManualOperationEventMask.scheduleLock.rawValue == 64, "MTRDoorLockDlManualOperationEventMask.scheduleLock")
    mtrRequire(MTRDoorLockDlManualOperationEventMask.scheduleUnlock.rawValue == 128, "MTRDoorLockDlManualOperationEventMask.scheduleUnlock")
    mtrRequire(MTRDoorLockDlManualOperationEventMask.manualLock.rawValue == 256, "MTRDoorLockDlManualOperationEventMask.manualLock")
    mtrRequire(MTRDoorLockDlManualOperationEventMask.manualUnlock.rawValue == 512, "MTRDoorLockDlManualOperationEventMask.manualUnlock")
    _ = MTRDoorLockDlRFIDOperationEventMask.self
    mtrRequire(MTRDoorLockDlRFIDOperationEventMask.unknown.rawValue == 0, "MTRDoorLockDlRFIDOperationEventMask.unknown")
    mtrRequire(MTRDoorLockDlRFIDOperationEventMask.lock.rawValue == 1, "MTRDoorLockDlRFIDOperationEventMask.lock")
    mtrRequire(MTRDoorLockDlRFIDOperationEventMask.unlock.rawValue == 2, "MTRDoorLockDlRFIDOperationEventMask.unlock")
    mtrRequire(MTRDoorLockDlRFIDOperationEventMask.lockInvalidRFID.rawValue == 4, "MTRDoorLockDlRFIDOperationEventMask.lockInvalidRFID")
    mtrRequire(MTRDoorLockDlRFIDOperationEventMask.lockInvalidSchedule.rawValue == 8, "MTRDoorLockDlRFIDOperationEventMask.lockInvalidSchedule")
    mtrRequire(MTRDoorLockDlRFIDOperationEventMask.unlockInvalidRFID.rawValue == 16, "MTRDoorLockDlRFIDOperationEventMask.unlockInvalidRFID")
    mtrRequire(MTRDoorLockDlRFIDOperationEventMask.unlockInvalidSchedule.rawValue == 32, "MTRDoorLockDlRFIDOperationEventMask.unlockInvalidSchedule")
    _ = MTRDoorLockDlRFIDProgrammingEventMask.self
    mtrRequire(MTRDoorLockDlRFIDProgrammingEventMask.unknown.rawValue == 0, "MTRDoorLockDlRFIDProgrammingEventMask.unknown")
    mtrRequire(MTRDoorLockDlRFIDProgrammingEventMask.rfidCodeAdded.rawValue == 1, "MTRDoorLockDlRFIDProgrammingEventMask.rfidCodeAdded")
    mtrRequire(MTRDoorLockDlRFIDProgrammingEventMask.rfidCodeCleared.rawValue == 2, "MTRDoorLockDlRFIDProgrammingEventMask.rfidCodeCleared")
    _ = MTRDoorLockDlRemoteOperationEventMask.self
    mtrRequire(MTRDoorLockDlRemoteOperationEventMask.unknown.rawValue == 0, "MTRDoorLockDlRemoteOperationEventMask.unknown")
    mtrRequire(MTRDoorLockDlRemoteOperationEventMask.lock.rawValue == 1, "MTRDoorLockDlRemoteOperationEventMask.lock")
    mtrRequire(MTRDoorLockDlRemoteOperationEventMask.unlock.rawValue == 2, "MTRDoorLockDlRemoteOperationEventMask.unlock")
    mtrRequire(MTRDoorLockDlRemoteOperationEventMask.lockInvalidCode.rawValue == 4, "MTRDoorLockDlRemoteOperationEventMask.lockInvalidCode")
    mtrRequire(MTRDoorLockDlRemoteOperationEventMask.lockInvalidSchedule.rawValue == 8, "MTRDoorLockDlRemoteOperationEventMask.lockInvalidSchedule")
    mtrRequire(MTRDoorLockDlRemoteOperationEventMask.unlockInvalidCode.rawValue == 16, "MTRDoorLockDlRemoteOperationEventMask.unlockInvalidCode")
    mtrRequire(MTRDoorLockDlRemoteOperationEventMask.unlockInvalidSchedule.rawValue == 32, "MTRDoorLockDlRemoteOperationEventMask.unlockInvalidSchedule")
    _ = MTRDoorLockDlRemoteProgrammingEventMask.self
    mtrRequire(MTRDoorLockDlRemoteProgrammingEventMask.unknown.rawValue == 0, "MTRDoorLockDlRemoteProgrammingEventMask.unknown")
    mtrRequire(MTRDoorLockDlRemoteProgrammingEventMask.programmingPINChanged.rawValue == 1, "MTRDoorLockDlRemoteProgrammingEventMask.programmingPINChanged")
    mtrRequire(MTRDoorLockDlRemoteProgrammingEventMask.pinAdded.rawValue == 2, "MTRDoorLockDlRemoteProgrammingEventMask.pinAdded")
    mtrRequire(MTRDoorLockDlRemoteProgrammingEventMask.pinCleared.rawValue == 4, "MTRDoorLockDlRemoteProgrammingEventMask.pinCleared")
    mtrRequire(MTRDoorLockDlRemoteProgrammingEventMask.pinChanged.rawValue == 8, "MTRDoorLockDlRemoteProgrammingEventMask.pinChanged")
    mtrRequire(MTRDoorLockDlRemoteProgrammingEventMask.rfidCodeAdded.rawValue == 16, "MTRDoorLockDlRemoteProgrammingEventMask.rfidCodeAdded")
    mtrRequire(MTRDoorLockDlRemoteProgrammingEventMask.rfidCodeCleared.rawValue == 32, "MTRDoorLockDlRemoteProgrammingEventMask.rfidCodeCleared")
    _ = MTRDoorLockDlSupportedOperatingModes.self
    mtrRequire(MTRDoorLockDlSupportedOperatingModes.normal.rawValue == 1, "MTRDoorLockDlSupportedOperatingModes.normal")
    mtrRequire(MTRDoorLockDlSupportedOperatingModes.vacation.rawValue == 2, "MTRDoorLockDlSupportedOperatingModes.vacation")
    mtrRequire(MTRDoorLockDlSupportedOperatingModes.privacy.rawValue == 4, "MTRDoorLockDlSupportedOperatingModes.privacy")
    mtrRequire(MTRDoorLockDlSupportedOperatingModes.noRemoteLockUnlock.rawValue == 8, "MTRDoorLockDlSupportedOperatingModes.noRemoteLockUnlock")
    mtrRequire(MTRDoorLockDlSupportedOperatingModes.passage.rawValue == 16, "MTRDoorLockDlSupportedOperatingModes.passage")
    _ = MTRDoorLockFeature.self
    mtrRequire(MTRDoorLockFeature.pinCredential.rawValue == 1, "MTRDoorLockFeature.pinCredential")
    mtrRequire(MTRDoorLockFeature.pinCredentials.rawValue == 2, "MTRDoorLockFeature.pinCredentials")
    mtrRequire(MTRDoorLockFeature.rfidCredential.rawValue == 4, "MTRDoorLockFeature.rfidCredential")
    mtrRequire(MTRDoorLockFeature.rfidCredentials.rawValue == 8, "MTRDoorLockFeature.rfidCredentials")
    mtrRequire(MTRDoorLockFeature.fingerCredentials.rawValue == 16, "MTRDoorLockFeature.fingerCredentials")
    mtrRequire(MTRDoorLockFeature.logging.rawValue == 32, "MTRDoorLockFeature.logging")
    mtrRequire(MTRDoorLockFeature.weekDayAccessSchedules.rawValue == 64, "MTRDoorLockFeature.weekDayAccessSchedules")
    mtrRequire(MTRDoorLockFeature.weekDaySchedules.rawValue == 128, "MTRDoorLockFeature.weekDaySchedules")
    mtrRequire(MTRDoorLockFeature.doorPositionSensor.rawValue == 256, "MTRDoorLockFeature.doorPositionSensor")
    mtrRequire(MTRDoorLockFeature.faceCredentials.rawValue == 512, "MTRDoorLockFeature.faceCredentials")
    mtrRequire(MTRDoorLockFeature.credentialsOverTheAirAccess.rawValue == 1024, "MTRDoorLockFeature.credentialsOverTheAirAccess")
    mtrRequire(MTRDoorLockFeature.credentialsOTA.rawValue == 2048, "MTRDoorLockFeature.credentialsOTA")
    mtrRequire(MTRDoorLockFeature.user.rawValue == 4096, "MTRDoorLockFeature.user")
    mtrRequire(MTRDoorLockFeature.usersManagement.rawValue == 8192, "MTRDoorLockFeature.usersManagement")
    mtrRequire(MTRDoorLockFeature.notification.rawValue == 16384, "MTRDoorLockFeature.notification")
    mtrRequire(MTRDoorLockFeature.notifications.rawValue == 32768, "MTRDoorLockFeature.notifications")
    mtrRequire(MTRDoorLockFeature.yearDayAccessSchedules.rawValue == 65536, "MTRDoorLockFeature.yearDayAccessSchedules")
    mtrRequire(MTRDoorLockFeature.yearDaySchedules.rawValue == 131072, "MTRDoorLockFeature.yearDaySchedules")
    mtrRequire(MTRDoorLockFeature.holidaySchedules.rawValue == 262144, "MTRDoorLockFeature.holidaySchedules")
    mtrRequire(MTRDoorLockFeature.unbolt.rawValue == 524288, "MTRDoorLockFeature.unbolt")
    mtrRequire(MTRDoorLockFeature.aliroProvisioning.rawValue == 1048576, "MTRDoorLockFeature.aliroProvisioning")
    mtrRequire(MTRDoorLockFeature.aliroBLEUWB.rawValue == 2097152, "MTRDoorLockFeature.aliroBLEUWB")
    _ = MTRElectricalEnergyMeasurementFeature.self
    mtrRequire(MTRElectricalEnergyMeasurementFeature.importedEnergy.rawValue == 1, "MTRElectricalEnergyMeasurementFeature.importedEnergy")
    mtrRequire(MTRElectricalEnergyMeasurementFeature.exportedEnergy.rawValue == 2, "MTRElectricalEnergyMeasurementFeature.exportedEnergy")
    mtrRequire(MTRElectricalEnergyMeasurementFeature.cumulativeEnergy.rawValue == 4, "MTRElectricalEnergyMeasurementFeature.cumulativeEnergy")
    mtrRequire(MTRElectricalEnergyMeasurementFeature.periodicEnergy.rawValue == 8, "MTRElectricalEnergyMeasurementFeature.periodicEnergy")
    _ = MTRElectricalPowerMeasurementFeature.self
    mtrRequire(MTRElectricalPowerMeasurementFeature.directCurrent.rawValue == 1, "MTRElectricalPowerMeasurementFeature.directCurrent")
    mtrRequire(MTRElectricalPowerMeasurementFeature.alternatingCurrent.rawValue == 2, "MTRElectricalPowerMeasurementFeature.alternatingCurrent")
    mtrRequire(MTRElectricalPowerMeasurementFeature.polyphasePower.rawValue == 4, "MTRElectricalPowerMeasurementFeature.polyphasePower")
    mtrRequire(MTRElectricalPowerMeasurementFeature.harmonics.rawValue == 8, "MTRElectricalPowerMeasurementFeature.harmonics")
    mtrRequire(MTRElectricalPowerMeasurementFeature.powerQuality.rawValue == 16, "MTRElectricalPowerMeasurementFeature.powerQuality")
    _ = MTREnergyEVSEFeature.self
    mtrRequire(MTREnergyEVSEFeature.chargingPreferences.rawValue == 1, "MTREnergyEVSEFeature.chargingPreferences")
    mtrRequire(MTREnergyEVSEFeature.RFID.rawValue == 2, "MTREnergyEVSEFeature.RFID")
    _ = MTREnergyEVSETargetDayOfWeekBitmap.self
    mtrRequire(MTREnergyEVSETargetDayOfWeekBitmap.sunday.rawValue == 1, "MTREnergyEVSETargetDayOfWeekBitmap.sunday")
    mtrRequire(MTREnergyEVSETargetDayOfWeekBitmap.monday.rawValue == 2, "MTREnergyEVSETargetDayOfWeekBitmap.monday")
    mtrRequire(MTREnergyEVSETargetDayOfWeekBitmap.tuesday.rawValue == 4, "MTREnergyEVSETargetDayOfWeekBitmap.tuesday")
    mtrRequire(MTREnergyEVSETargetDayOfWeekBitmap.wednesday.rawValue == 8, "MTREnergyEVSETargetDayOfWeekBitmap.wednesday")
    mtrRequire(MTREnergyEVSETargetDayOfWeekBitmap.thursday.rawValue == 16, "MTREnergyEVSETargetDayOfWeekBitmap.thursday")
    mtrRequire(MTREnergyEVSETargetDayOfWeekBitmap.friday.rawValue == 32, "MTREnergyEVSETargetDayOfWeekBitmap.friday")
    mtrRequire(MTREnergyEVSETargetDayOfWeekBitmap.saturday.rawValue == 64, "MTREnergyEVSETargetDayOfWeekBitmap.saturday")
    _ = MTREthernetNetworkDiagnosticsFeature.self
    mtrRequire(MTREthernetNetworkDiagnosticsFeature.packetCounts.rawValue == 1, "MTREthernetNetworkDiagnosticsFeature.packetCounts")
    mtrRequire(MTREthernetNetworkDiagnosticsFeature.errorCounts.rawValue == 2, "MTREthernetNetworkDiagnosticsFeature.errorCounts")
    _ = MTRFanControlFeature.self
    mtrRequire(MTRFanControlFeature.multiSpeed.rawValue == 1, "MTRFanControlFeature.multiSpeed")
    mtrRequire(MTRFanControlFeature.auto.rawValue == 2, "MTRFanControlFeature.auto")
    mtrRequire(MTRFanControlFeature.rocking.rawValue == 4, "MTRFanControlFeature.rocking")
    mtrRequire(MTRFanControlFeature.wind.rawValue == 8, "MTRFanControlFeature.wind")
    mtrRequire(MTRFanControlFeature.step.rawValue == 16, "MTRFanControlFeature.step")
    mtrRequire(MTRFanControlFeature.airflowDirection.rawValue == 32, "MTRFanControlFeature.airflowDirection")
    _ = MTRFanControlRockBitmap.self
    mtrRequire(MTRFanControlRockBitmap.rockLeftRight.rawValue == 1, "MTRFanControlRockBitmap.rockLeftRight")
    mtrRequire(MTRFanControlRockBitmap.rockUpDown.rawValue == 2, "MTRFanControlRockBitmap.rockUpDown")
    mtrRequire(MTRFanControlRockBitmap.rockRound.rawValue == 4, "MTRFanControlRockBitmap.rockRound")
    _ = MTRFanControlRockSupportMask.self
    mtrRequire(MTRFanControlRockSupportMask.rockLeftRight.rawValue == 1, "MTRFanControlRockSupportMask.rockLeftRight")
    mtrRequire(MTRFanControlRockSupportMask.rockUpDown.rawValue == 2, "MTRFanControlRockSupportMask.rockUpDown")
    mtrRequire(MTRFanControlRockSupportMask.rockRound.rawValue == 4, "MTRFanControlRockSupportMask.rockRound")
    _ = MTRFanControlWindBitmap.self
    mtrRequire(MTRFanControlWindBitmap.sleepWind.rawValue == 1, "MTRFanControlWindBitmap.sleepWind")
    mtrRequire(MTRFanControlWindBitmap.naturalWind.rawValue == 2, "MTRFanControlWindBitmap.naturalWind")
    _ = MTRFanControlWindSettingMask.self
    mtrRequire(MTRFanControlWindSettingMask.sleepWind.rawValue == 1, "MTRFanControlWindSettingMask.sleepWind")
    mtrRequire(MTRFanControlWindSettingMask.naturalWind.rawValue == 2, "MTRFanControlWindSettingMask.naturalWind")
    _ = MTRFanControlWindSupportMask.self
    mtrRequire(MTRFanControlWindSupportMask.sleepWind.rawValue == 1, "MTRFanControlWindSupportMask.sleepWind")
    mtrRequire(MTRFanControlWindSupportMask.naturalWind.rawValue == 2, "MTRFanControlWindSupportMask.naturalWind")
    _ = MTRFormaldehydeConcentrationMeasurementFeature.self
    mtrRequire(MTRFormaldehydeConcentrationMeasurementFeature.numericMeasurement.rawValue == 1, "MTRFormaldehydeConcentrationMeasurementFeature.numericMeasurement")
    mtrRequire(MTRFormaldehydeConcentrationMeasurementFeature.levelIndication.rawValue == 2, "MTRFormaldehydeConcentrationMeasurementFeature.levelIndication")
    mtrRequire(MTRFormaldehydeConcentrationMeasurementFeature.mediumLevel.rawValue == 4, "MTRFormaldehydeConcentrationMeasurementFeature.mediumLevel")
    mtrRequire(MTRFormaldehydeConcentrationMeasurementFeature.criticalLevel.rawValue == 8, "MTRFormaldehydeConcentrationMeasurementFeature.criticalLevel")
    mtrRequire(MTRFormaldehydeConcentrationMeasurementFeature.peakMeasurement.rawValue == 16, "MTRFormaldehydeConcentrationMeasurementFeature.peakMeasurement")
    mtrRequire(MTRFormaldehydeConcentrationMeasurementFeature.averageMeasurement.rawValue == 32, "MTRFormaldehydeConcentrationMeasurementFeature.averageMeasurement")
    _ = MTRGeneralDiagnosticsFeature.self
    mtrRequire(MTRGeneralDiagnosticsFeature.dataModelTest.rawValue == 1, "MTRGeneralDiagnosticsFeature.dataModelTest")
    _ = MTRGroupsFeature.self
    mtrRequire(MTRGroupsFeature.groupNames.rawValue == 1, "MTRGroupsFeature.groupNames")
    _ = MTRGroupsGroupClusterFeature.self
    mtrRequire(MTRGroupsGroupClusterFeature.groupNames.rawValue == 1, "MTRGroupsGroupClusterFeature.groupNames")
    _ = MTRGroupsNameSupportBitmap.self
    mtrRequire(MTRGroupsNameSupportBitmap.groupNames.rawValue == 1, "MTRGroupsNameSupportBitmap.groupNames")
    _ = MTRHEPAFilterMonitoringFeature.self
    mtrRequire(MTRHEPAFilterMonitoringFeature.condition.rawValue == 1, "MTRHEPAFilterMonitoringFeature.condition")
    mtrRequire(MTRHEPAFilterMonitoringFeature.warning.rawValue == 2, "MTRHEPAFilterMonitoringFeature.warning")
    mtrRequire(MTRHEPAFilterMonitoringFeature.replacementProductList.rawValue == 4, "MTRHEPAFilterMonitoringFeature.replacementProductList")
    _ = MTRICDManagementFeature.self
    mtrRequire(MTRICDManagementFeature.checkInProtocolSupport.rawValue == 1, "MTRICDManagementFeature.checkInProtocolSupport")
    mtrRequire(MTRICDManagementFeature.userActiveModeTrigger.rawValue == 2, "MTRICDManagementFeature.userActiveModeTrigger")
    mtrRequire(MTRICDManagementFeature.longIdleTimeSupport.rawValue == 4, "MTRICDManagementFeature.longIdleTimeSupport")
    mtrRequire(MTRICDManagementFeature.dynamicSitLitSupport.rawValue == 8, "MTRICDManagementFeature.dynamicSitLitSupport")
    _ = MTRICDManagementUserActiveModeTriggerBitmap.self
    mtrRequire(MTRICDManagementUserActiveModeTriggerBitmap.powerCycle.rawValue == 1, "MTRICDManagementUserActiveModeTriggerBitmap.powerCycle")
    mtrRequire(MTRICDManagementUserActiveModeTriggerBitmap.settingsMenu.rawValue == 2, "MTRICDManagementUserActiveModeTriggerBitmap.settingsMenu")
    mtrRequire(MTRICDManagementUserActiveModeTriggerBitmap.customInstruction.rawValue == 4, "MTRICDManagementUserActiveModeTriggerBitmap.customInstruction")
    mtrRequire(MTRICDManagementUserActiveModeTriggerBitmap.deviceManual.rawValue == 8, "MTRICDManagementUserActiveModeTriggerBitmap.deviceManual")
    mtrRequire(MTRICDManagementUserActiveModeTriggerBitmap.actuateSensor.rawValue == 16, "MTRICDManagementUserActiveModeTriggerBitmap.actuateSensor")
    mtrRequire(MTRICDManagementUserActiveModeTriggerBitmap.actuateSensorSeconds.rawValue == 32, "MTRICDManagementUserActiveModeTriggerBitmap.actuateSensorSeconds")
    mtrRequire(MTRICDManagementUserActiveModeTriggerBitmap.actuateSensorTimes.rawValue == 64, "MTRICDManagementUserActiveModeTriggerBitmap.actuateSensorTimes")
    mtrRequire(MTRICDManagementUserActiveModeTriggerBitmap.actuateSensorLightsBlink.rawValue == 128, "MTRICDManagementUserActiveModeTriggerBitmap.actuateSensorLightsBlink")
    mtrRequire(MTRICDManagementUserActiveModeTriggerBitmap.resetButton.rawValue == 256, "MTRICDManagementUserActiveModeTriggerBitmap.resetButton")
    mtrRequire(MTRICDManagementUserActiveModeTriggerBitmap.resetButtonLightsBlink.rawValue == 512, "MTRICDManagementUserActiveModeTriggerBitmap.resetButtonLightsBlink")
    mtrRequire(MTRICDManagementUserActiveModeTriggerBitmap.resetButtonSeconds.rawValue == 1024, "MTRICDManagementUserActiveModeTriggerBitmap.resetButtonSeconds")
    mtrRequire(MTRICDManagementUserActiveModeTriggerBitmap.resetButtonTimes.rawValue == 2048, "MTRICDManagementUserActiveModeTriggerBitmap.resetButtonTimes")
    mtrRequire(MTRICDManagementUserActiveModeTriggerBitmap.setupButton.rawValue == 4096, "MTRICDManagementUserActiveModeTriggerBitmap.setupButton")
    mtrRequire(MTRICDManagementUserActiveModeTriggerBitmap.setupButtonSeconds.rawValue == 8192, "MTRICDManagementUserActiveModeTriggerBitmap.setupButtonSeconds")
    mtrRequire(MTRICDManagementUserActiveModeTriggerBitmap.setupButtonLightsBlink.rawValue == 16384, "MTRICDManagementUserActiveModeTriggerBitmap.setupButtonLightsBlink")
    mtrRequire(MTRICDManagementUserActiveModeTriggerBitmap.setupButtonTimes.rawValue == 32768, "MTRICDManagementUserActiveModeTriggerBitmap.setupButtonTimes")
    mtrRequire(MTRICDManagementUserActiveModeTriggerBitmap.appDefinedButton.rawValue == 65536, "MTRICDManagementUserActiveModeTriggerBitmap.appDefinedButton")
    _ = MTRKeypadInputFeature.self
    mtrRequire(MTRKeypadInputFeature.navigationKeyCodes.rawValue == 1, "MTRKeypadInputFeature.navigationKeyCodes")
    mtrRequire(MTRKeypadInputFeature.locationKeys.rawValue == 2, "MTRKeypadInputFeature.locationKeys")
    mtrRequire(MTRKeypadInputFeature.numberKeys.rawValue == 4, "MTRKeypadInputFeature.numberKeys")
    _ = MTRLaundryWasherControlsFeature.self
    mtrRequire(MTRLaundryWasherControlsFeature.spin.rawValue == 1, "MTRLaundryWasherControlsFeature.spin")
    mtrRequire(MTRLaundryWasherControlsFeature.rinse.rawValue == 2, "MTRLaundryWasherControlsFeature.rinse")
    _ = MTRLevelControlFeature.self
    mtrRequire(MTRLevelControlFeature.onOff.rawValue == 1, "MTRLevelControlFeature.onOff")
    mtrRequire(MTRLevelControlFeature.lighting.rawValue == 2, "MTRLevelControlFeature.lighting")
    mtrRequire(MTRLevelControlFeature.frequency.rawValue == 4, "MTRLevelControlFeature.frequency")
    _ = MTRLevelControlOptions.self
    mtrRequire(MTRLevelControlOptions.executeIfOff.rawValue == 1, "MTRLevelControlOptions.executeIfOff")
    mtrRequire(MTRLevelControlOptions.coupleColorTempToLevel.rawValue == 2, "MTRLevelControlOptions.coupleColorTempToLevel")
    _ = MTRLevelControlOptionsBitmap.self
    mtrRequire(MTRLevelControlOptionsBitmap.executeIfOff.rawValue == 1, "MTRLevelControlOptionsBitmap.executeIfOff")
    mtrRequire(MTRLevelControlOptionsBitmap.coupleColorTempToLevel.rawValue == 2, "MTRLevelControlOptionsBitmap.coupleColorTempToLevel")
    _ = MTRMediaInputFeature.self
    mtrRequire(MTRMediaInputFeature.nameUpdates.rawValue == 1, "MTRMediaInputFeature.nameUpdates")
    _ = MTRMediaPlaybackFeature.self
    mtrRequire(MTRMediaPlaybackFeature.advancedSeek.rawValue == 1, "MTRMediaPlaybackFeature.advancedSeek")
    mtrRequire(MTRMediaPlaybackFeature.variableSpeed.rawValue == 2, "MTRMediaPlaybackFeature.variableSpeed")
    mtrRequire(MTRMediaPlaybackFeature.textTracks.rawValue == 4, "MTRMediaPlaybackFeature.textTracks")
    mtrRequire(MTRMediaPlaybackFeature.audioTracks.rawValue == 8, "MTRMediaPlaybackFeature.audioTracks")
    mtrRequire(MTRMediaPlaybackFeature.audioAdvance.rawValue == 16, "MTRMediaPlaybackFeature.audioAdvance")
    _ = MTRMessagesFeature.self
    mtrRequire(MTRMessagesFeature.receivedConfirmation.rawValue == 1, "MTRMessagesFeature.receivedConfirmation")
    mtrRequire(MTRMessagesFeature.confirmationResponse.rawValue == 2, "MTRMessagesFeature.confirmationResponse")
    mtrRequire(MTRMessagesFeature.confirmationReply.rawValue == 4, "MTRMessagesFeature.confirmationReply")
    mtrRequire(MTRMessagesFeature.protectedMessages.rawValue == 8, "MTRMessagesFeature.protectedMessages")
    _ = MTRMessagesMessageControlBitmap.self
    mtrRequire(MTRMessagesMessageControlBitmap.confirmationRequired.rawValue == 1, "MTRMessagesMessageControlBitmap.confirmationRequired")
    mtrRequire(MTRMessagesMessageControlBitmap.responseRequired.rawValue == 2, "MTRMessagesMessageControlBitmap.responseRequired")
    mtrRequire(MTRMessagesMessageControlBitmap.replyMessage.rawValue == 4, "MTRMessagesMessageControlBitmap.replyMessage")
    mtrRequire(MTRMessagesMessageControlBitmap.messageConfirmed.rawValue == 8, "MTRMessagesMessageControlBitmap.messageConfirmed")
    mtrRequire(MTRMessagesMessageControlBitmap.messageProtected.rawValue == 16, "MTRMessagesMessageControlBitmap.messageProtected")
    _ = MTRMicrowaveOvenControlFeature.self
    mtrRequire(MTRMicrowaveOvenControlFeature.powerAsNumber.rawValue == 1, "MTRMicrowaveOvenControlFeature.powerAsNumber")
    mtrRequire(MTRMicrowaveOvenControlFeature.powerNumberLimits.rawValue == 2, "MTRMicrowaveOvenControlFeature.powerNumberLimits")
    _ = MTRModeSelectFeature.self
    mtrRequire(MTRModeSelectFeature.onOff.rawValue == 1, "MTRModeSelectFeature.onOff")
    mtrRequire(MTRModeSelectFeature.DEPONOFF.rawValue == 2, "MTRModeSelectFeature.DEPONOFF")
    _ = MTRNetworkCommissioningFeature.self
    mtrRequire(MTRNetworkCommissioningFeature.wiFiNetworkInterface.rawValue == 1, "MTRNetworkCommissioningFeature.wiFiNetworkInterface")
    mtrRequire(MTRNetworkCommissioningFeature.threadNetworkInterface.rawValue == 2, "MTRNetworkCommissioningFeature.threadNetworkInterface")
    mtrRequire(MTRNetworkCommissioningFeature.ethernetNetworkInterface.rawValue == 4, "MTRNetworkCommissioningFeature.ethernetNetworkInterface")
    _ = MTRNetworkCommissioningThreadCapabilitiesBitmap.self
    mtrRequire(MTRNetworkCommissioningThreadCapabilitiesBitmap.isBorderRouterCapable.rawValue == 1, "MTRNetworkCommissioningThreadCapabilitiesBitmap.isBorderRouterCapable")
    mtrRequire(MTRNetworkCommissioningThreadCapabilitiesBitmap.isRouterCapable.rawValue == 2, "MTRNetworkCommissioningThreadCapabilitiesBitmap.isRouterCapable")
    mtrRequire(MTRNetworkCommissioningThreadCapabilitiesBitmap.isSleepyEndDeviceCapable.rawValue == 4, "MTRNetworkCommissioningThreadCapabilitiesBitmap.isSleepyEndDeviceCapable")
    mtrRequire(MTRNetworkCommissioningThreadCapabilitiesBitmap.isFullThreadDevice.rawValue == 8, "MTRNetworkCommissioningThreadCapabilitiesBitmap.isFullThreadDevice")
    mtrRequire(MTRNetworkCommissioningThreadCapabilitiesBitmap.isSynchronizedSleepyEndDeviceCapable.rawValue == 16, "MTRNetworkCommissioningThreadCapabilitiesBitmap.isSynchronizedSleepyEndDeviceCapable")
    _ = MTRNetworkCommissioningWiFiSecurity.self
    mtrRequire(MTRNetworkCommissioningWiFiSecurity.unencrypted.rawValue == 1, "MTRNetworkCommissioningWiFiSecurity.unencrypted")
    mtrRequire(MTRNetworkCommissioningWiFiSecurity.WEP.rawValue == 2, "MTRNetworkCommissioningWiFiSecurity.WEP")
    mtrRequire(MTRNetworkCommissioningWiFiSecurity.wepPersonal.rawValue == 4, "MTRNetworkCommissioningWiFiSecurity.wepPersonal")
    mtrRequire(MTRNetworkCommissioningWiFiSecurity.wpaPersonal.rawValue == 8, "MTRNetworkCommissioningWiFiSecurity.wpaPersonal")
    mtrRequire(MTRNetworkCommissioningWiFiSecurity.wpa2Personal.rawValue == 16, "MTRNetworkCommissioningWiFiSecurity.wpa2Personal")
    mtrRequire(MTRNetworkCommissioningWiFiSecurity.wpa3Personal.rawValue == 32, "MTRNetworkCommissioningWiFiSecurity.wpa3Personal")
    _ = MTRNetworkCommissioningWiFiSecurityBitmap.self
    mtrRequire(MTRNetworkCommissioningWiFiSecurityBitmap.unencrypted.rawValue == 1, "MTRNetworkCommissioningWiFiSecurityBitmap.unencrypted")
    mtrRequire(MTRNetworkCommissioningWiFiSecurityBitmap.WEP.rawValue == 2, "MTRNetworkCommissioningWiFiSecurityBitmap.WEP")
    mtrRequire(MTRNetworkCommissioningWiFiSecurityBitmap.wpaPersonal.rawValue == 4, "MTRNetworkCommissioningWiFiSecurityBitmap.wpaPersonal")
    mtrRequire(MTRNetworkCommissioningWiFiSecurityBitmap.wpa2Personal.rawValue == 8, "MTRNetworkCommissioningWiFiSecurityBitmap.wpa2Personal")
    mtrRequire(MTRNetworkCommissioningWiFiSecurityBitmap.wpa3Personal.rawValue == 16, "MTRNetworkCommissioningWiFiSecurityBitmap.wpa3Personal")
    _ = MTRNitrogenDioxideConcentrationMeasurementFeature.self
    mtrRequire(MTRNitrogenDioxideConcentrationMeasurementFeature.numericMeasurement.rawValue == 1, "MTRNitrogenDioxideConcentrationMeasurementFeature.numericMeasurement")
    mtrRequire(MTRNitrogenDioxideConcentrationMeasurementFeature.levelIndication.rawValue == 2, "MTRNitrogenDioxideConcentrationMeasurementFeature.levelIndication")
    mtrRequire(MTRNitrogenDioxideConcentrationMeasurementFeature.mediumLevel.rawValue == 4, "MTRNitrogenDioxideConcentrationMeasurementFeature.mediumLevel")
    mtrRequire(MTRNitrogenDioxideConcentrationMeasurementFeature.criticalLevel.rawValue == 8, "MTRNitrogenDioxideConcentrationMeasurementFeature.criticalLevel")
    mtrRequire(MTRNitrogenDioxideConcentrationMeasurementFeature.peakMeasurement.rawValue == 16, "MTRNitrogenDioxideConcentrationMeasurementFeature.peakMeasurement")
    mtrRequire(MTRNitrogenDioxideConcentrationMeasurementFeature.averageMeasurement.rawValue == 32, "MTRNitrogenDioxideConcentrationMeasurementFeature.averageMeasurement")
    _ = MTROccupancySensingFeature.self
    mtrRequire(MTROccupancySensingFeature.other.rawValue == 1, "MTROccupancySensingFeature.other")
    mtrRequire(MTROccupancySensingFeature.passiveInfrared.rawValue == 2, "MTROccupancySensingFeature.passiveInfrared")
    mtrRequire(MTROccupancySensingFeature.ultrasonic.rawValue == 4, "MTROccupancySensingFeature.ultrasonic")
    mtrRequire(MTROccupancySensingFeature.physicalContact.rawValue == 8, "MTROccupancySensingFeature.physicalContact")
    mtrRequire(MTROccupancySensingFeature.activeInfrared.rawValue == 16, "MTROccupancySensingFeature.activeInfrared")
    mtrRequire(MTROccupancySensingFeature.radar.rawValue == 32, "MTROccupancySensingFeature.radar")
    mtrRequire(MTROccupancySensingFeature.rfSensing.rawValue == 64, "MTROccupancySensingFeature.rfSensing")
    mtrRequire(MTROccupancySensingFeature.vision.rawValue == 128, "MTROccupancySensingFeature.vision")
    _ = MTROccupancySensingOccupancyBitmap.self
    mtrRequire(MTROccupancySensingOccupancyBitmap.occupied.rawValue == 1, "MTROccupancySensingOccupancyBitmap.occupied")
    _ = MTROccupancySensingOccupancySensorTypeBitmap.self
    mtrRequire(MTROccupancySensingOccupancySensorTypeBitmap.PIR.rawValue == 1, "MTROccupancySensingOccupancySensorTypeBitmap.PIR")
    mtrRequire(MTROccupancySensingOccupancySensorTypeBitmap.ultrasonic.rawValue == 2, "MTROccupancySensingOccupancySensorTypeBitmap.ultrasonic")
    mtrRequire(MTROccupancySensingOccupancySensorTypeBitmap.physicalContact.rawValue == 4, "MTROccupancySensingOccupancySensorTypeBitmap.physicalContact")
    _ = MTROnOffControl.self
    mtrRequire(MTROnOffControl.acceptOnlyWhenOn.rawValue == 1, "MTROnOffControl.acceptOnlyWhenOn")
    _ = MTROnOffControlBitmap.self
    mtrRequire(MTROnOffControlBitmap.acceptOnlyWhenOn.rawValue == 1, "MTROnOffControlBitmap.acceptOnlyWhenOn")
    _ = MTROnOffFeature.self
    mtrRequire(MTROnOffFeature.lighting.rawValue == 1, "MTROnOffFeature.lighting")
    mtrRequire(MTROnOffFeature.deadFrontBehavior.rawValue == 2, "MTROnOffFeature.deadFrontBehavior")
    mtrRequire(MTROnOffFeature.deadFront.rawValue == 4, "MTROnOffFeature.deadFront")
    mtrRequire(MTROnOffFeature.offOnly.rawValue == 8, "MTROnOffFeature.offOnly")
    _ = MTROzoneConcentrationMeasurementFeature.self
    mtrRequire(MTROzoneConcentrationMeasurementFeature.numericMeasurement.rawValue == 1, "MTROzoneConcentrationMeasurementFeature.numericMeasurement")
    mtrRequire(MTROzoneConcentrationMeasurementFeature.levelIndication.rawValue == 2, "MTROzoneConcentrationMeasurementFeature.levelIndication")
    mtrRequire(MTROzoneConcentrationMeasurementFeature.mediumLevel.rawValue == 4, "MTROzoneConcentrationMeasurementFeature.mediumLevel")
    mtrRequire(MTROzoneConcentrationMeasurementFeature.criticalLevel.rawValue == 8, "MTROzoneConcentrationMeasurementFeature.criticalLevel")
    mtrRequire(MTROzoneConcentrationMeasurementFeature.peakMeasurement.rawValue == 16, "MTROzoneConcentrationMeasurementFeature.peakMeasurement")
    mtrRequire(MTROzoneConcentrationMeasurementFeature.averageMeasurement.rawValue == 32, "MTROzoneConcentrationMeasurementFeature.averageMeasurement")
    _ = MTRPM10ConcentrationMeasurementFeature.self
    mtrRequire(MTRPM10ConcentrationMeasurementFeature.numericMeasurement.rawValue == 1, "MTRPM10ConcentrationMeasurementFeature.numericMeasurement")
    mtrRequire(MTRPM10ConcentrationMeasurementFeature.levelIndication.rawValue == 2, "MTRPM10ConcentrationMeasurementFeature.levelIndication")
    mtrRequire(MTRPM10ConcentrationMeasurementFeature.mediumLevel.rawValue == 4, "MTRPM10ConcentrationMeasurementFeature.mediumLevel")
    mtrRequire(MTRPM10ConcentrationMeasurementFeature.criticalLevel.rawValue == 8, "MTRPM10ConcentrationMeasurementFeature.criticalLevel")
    mtrRequire(MTRPM10ConcentrationMeasurementFeature.peakMeasurement.rawValue == 16, "MTRPM10ConcentrationMeasurementFeature.peakMeasurement")
    mtrRequire(MTRPM10ConcentrationMeasurementFeature.averageMeasurement.rawValue == 32, "MTRPM10ConcentrationMeasurementFeature.averageMeasurement")
    _ = MTRPM1ConcentrationMeasurementFeature.self
    mtrRequire(MTRPM1ConcentrationMeasurementFeature.numericMeasurement.rawValue == 1, "MTRPM1ConcentrationMeasurementFeature.numericMeasurement")
    mtrRequire(MTRPM1ConcentrationMeasurementFeature.levelIndication.rawValue == 2, "MTRPM1ConcentrationMeasurementFeature.levelIndication")
    mtrRequire(MTRPM1ConcentrationMeasurementFeature.mediumLevel.rawValue == 4, "MTRPM1ConcentrationMeasurementFeature.mediumLevel")
    mtrRequire(MTRPM1ConcentrationMeasurementFeature.criticalLevel.rawValue == 8, "MTRPM1ConcentrationMeasurementFeature.criticalLevel")
    mtrRequire(MTRPM1ConcentrationMeasurementFeature.peakMeasurement.rawValue == 16, "MTRPM1ConcentrationMeasurementFeature.peakMeasurement")
    mtrRequire(MTRPM1ConcentrationMeasurementFeature.averageMeasurement.rawValue == 32, "MTRPM1ConcentrationMeasurementFeature.averageMeasurement")
    _ = MTRPM25ConcentrationMeasurementFeature.self
    mtrRequire(MTRPM25ConcentrationMeasurementFeature.numericMeasurement.rawValue == 1, "MTRPM25ConcentrationMeasurementFeature.numericMeasurement")
    mtrRequire(MTRPM25ConcentrationMeasurementFeature.levelIndication.rawValue == 2, "MTRPM25ConcentrationMeasurementFeature.levelIndication")
    mtrRequire(MTRPM25ConcentrationMeasurementFeature.mediumLevel.rawValue == 4, "MTRPM25ConcentrationMeasurementFeature.mediumLevel")
    mtrRequire(MTRPM25ConcentrationMeasurementFeature.criticalLevel.rawValue == 8, "MTRPM25ConcentrationMeasurementFeature.criticalLevel")
    mtrRequire(MTRPM25ConcentrationMeasurementFeature.peakMeasurement.rawValue == 16, "MTRPM25ConcentrationMeasurementFeature.peakMeasurement")
    mtrRequire(MTRPM25ConcentrationMeasurementFeature.averageMeasurement.rawValue == 32, "MTRPM25ConcentrationMeasurementFeature.averageMeasurement")
    _ = MTRPowerSourceFeature.self
    mtrRequire(MTRPowerSourceFeature.wired.rawValue == 1, "MTRPowerSourceFeature.wired")
    mtrRequire(MTRPowerSourceFeature.battery.rawValue == 2, "MTRPowerSourceFeature.battery")
    mtrRequire(MTRPowerSourceFeature.rechargeable.rawValue == 4, "MTRPowerSourceFeature.rechargeable")
    mtrRequire(MTRPowerSourceFeature.replaceable.rawValue == 8, "MTRPowerSourceFeature.replaceable")
    _ = MTRPowerTopologyFeature.self
    mtrRequire(MTRPowerTopologyFeature.nodeTopology.rawValue == 1, "MTRPowerTopologyFeature.nodeTopology")
    mtrRequire(MTRPowerTopologyFeature.treeTopology.rawValue == 2, "MTRPowerTopologyFeature.treeTopology")
    mtrRequire(MTRPowerTopologyFeature.setTopology.rawValue == 4, "MTRPowerTopologyFeature.setTopology")
    mtrRequire(MTRPowerTopologyFeature.dynamicPowerFlow.rawValue == 8, "MTRPowerTopologyFeature.dynamicPowerFlow")
    _ = MTRPressureMeasurementFeature.self
    mtrRequire(MTRPressureMeasurementFeature.extended.rawValue == 1, "MTRPressureMeasurementFeature.extended")
    _ = MTRPressureMeasurementPressureFeature.self
    mtrRequire(MTRPressureMeasurementPressureFeature.extended.rawValue == 1, "MTRPressureMeasurementPressureFeature.extended")
    mtrRequire(MTRPressureMeasurementPressureFeature.EXT.rawValue == 2, "MTRPressureMeasurementPressureFeature.EXT")
    _ = MTRPumpConfigurationAndControlFeature.self
    mtrRequire(MTRPumpConfigurationAndControlFeature.constantPressure.rawValue == 1, "MTRPumpConfigurationAndControlFeature.constantPressure")
    mtrRequire(MTRPumpConfigurationAndControlFeature.compensatedPressure.rawValue == 2, "MTRPumpConfigurationAndControlFeature.compensatedPressure")
    mtrRequire(MTRPumpConfigurationAndControlFeature.constantFlow.rawValue == 4, "MTRPumpConfigurationAndControlFeature.constantFlow")
    mtrRequire(MTRPumpConfigurationAndControlFeature.constantSpeed.rawValue == 8, "MTRPumpConfigurationAndControlFeature.constantSpeed")
    mtrRequire(MTRPumpConfigurationAndControlFeature.constantTemperature.rawValue == 16, "MTRPumpConfigurationAndControlFeature.constantTemperature")
    mtrRequire(MTRPumpConfigurationAndControlFeature.automatic.rawValue == 32, "MTRPumpConfigurationAndControlFeature.automatic")
    mtrRequire(MTRPumpConfigurationAndControlFeature.localOperation.rawValue == 64, "MTRPumpConfigurationAndControlFeature.localOperation")
    _ = MTRPumpConfigurationAndControlPumpFeature.self
    mtrRequire(MTRPumpConfigurationAndControlPumpFeature.constantPressure.rawValue == 1, "MTRPumpConfigurationAndControlPumpFeature.constantPressure")
    mtrRequire(MTRPumpConfigurationAndControlPumpFeature.compensatedPressure.rawValue == 2, "MTRPumpConfigurationAndControlPumpFeature.compensatedPressure")
    mtrRequire(MTRPumpConfigurationAndControlPumpFeature.constantFlow.rawValue == 4, "MTRPumpConfigurationAndControlPumpFeature.constantFlow")
    mtrRequire(MTRPumpConfigurationAndControlPumpFeature.constantSpeed.rawValue == 8, "MTRPumpConfigurationAndControlPumpFeature.constantSpeed")
    mtrRequire(MTRPumpConfigurationAndControlPumpFeature.constantTemperature.rawValue == 16, "MTRPumpConfigurationAndControlPumpFeature.constantTemperature")
    mtrRequire(MTRPumpConfigurationAndControlPumpFeature.automatic.rawValue == 32, "MTRPumpConfigurationAndControlPumpFeature.automatic")
    mtrRequire(MTRPumpConfigurationAndControlPumpFeature.localOperation.rawValue == 64, "MTRPumpConfigurationAndControlPumpFeature.localOperation")
    mtrRequire(MTRPumpConfigurationAndControlPumpFeature.local.rawValue == 128, "MTRPumpConfigurationAndControlPumpFeature.local")
    _ = MTRPumpConfigurationAndControlPumpStatus.self
    mtrRequire(MTRPumpConfigurationAndControlPumpStatus.deviceFault.rawValue == 1, "MTRPumpConfigurationAndControlPumpStatus.deviceFault")
    mtrRequire(MTRPumpConfigurationAndControlPumpStatus.supplyfault.rawValue == 2, "MTRPumpConfigurationAndControlPumpStatus.supplyfault")
    mtrRequire(MTRPumpConfigurationAndControlPumpStatus.speedLow.rawValue == 4, "MTRPumpConfigurationAndControlPumpStatus.speedLow")
    mtrRequire(MTRPumpConfigurationAndControlPumpStatus.speedHigh.rawValue == 8, "MTRPumpConfigurationAndControlPumpStatus.speedHigh")
    mtrRequire(MTRPumpConfigurationAndControlPumpStatus.localOverride.rawValue == 16, "MTRPumpConfigurationAndControlPumpStatus.localOverride")
    mtrRequire(MTRPumpConfigurationAndControlPumpStatus.running.rawValue == 32, "MTRPumpConfigurationAndControlPumpStatus.running")
    mtrRequire(MTRPumpConfigurationAndControlPumpStatus.remotePressure.rawValue == 64, "MTRPumpConfigurationAndControlPumpStatus.remotePressure")
    mtrRequire(MTRPumpConfigurationAndControlPumpStatus.remoteFlow.rawValue == 128, "MTRPumpConfigurationAndControlPumpStatus.remoteFlow")
    mtrRequire(MTRPumpConfigurationAndControlPumpStatus.remoteTemperature.rawValue == 256, "MTRPumpConfigurationAndControlPumpStatus.remoteTemperature")
    _ = MTRPumpConfigurationAndControlPumpStatusBitmap.self
    mtrRequire(MTRPumpConfigurationAndControlPumpStatusBitmap.deviceFault.rawValue == 1, "MTRPumpConfigurationAndControlPumpStatusBitmap.deviceFault")
    mtrRequire(MTRPumpConfigurationAndControlPumpStatusBitmap.supplyFault.rawValue == 2, "MTRPumpConfigurationAndControlPumpStatusBitmap.supplyFault")
    mtrRequire(MTRPumpConfigurationAndControlPumpStatusBitmap.supplyfault.rawValue == 4, "MTRPumpConfigurationAndControlPumpStatusBitmap.supplyfault")
    mtrRequire(MTRPumpConfigurationAndControlPumpStatusBitmap.speedLow.rawValue == 8, "MTRPumpConfigurationAndControlPumpStatusBitmap.speedLow")
    mtrRequire(MTRPumpConfigurationAndControlPumpStatusBitmap.speedHigh.rawValue == 16, "MTRPumpConfigurationAndControlPumpStatusBitmap.speedHigh")
    mtrRequire(MTRPumpConfigurationAndControlPumpStatusBitmap.localOverride.rawValue == 32, "MTRPumpConfigurationAndControlPumpStatusBitmap.localOverride")
    mtrRequire(MTRPumpConfigurationAndControlPumpStatusBitmap.running.rawValue == 64, "MTRPumpConfigurationAndControlPumpStatusBitmap.running")
    mtrRequire(MTRPumpConfigurationAndControlPumpStatusBitmap.remotePressure.rawValue == 128, "MTRPumpConfigurationAndControlPumpStatusBitmap.remotePressure")
    mtrRequire(MTRPumpConfigurationAndControlPumpStatusBitmap.remoteFlow.rawValue == 256, "MTRPumpConfigurationAndControlPumpStatusBitmap.remoteFlow")
    mtrRequire(MTRPumpConfigurationAndControlPumpStatusBitmap.remoteTemperature.rawValue == 512, "MTRPumpConfigurationAndControlPumpStatusBitmap.remoteTemperature")
    _ = MTRRVCCleanModeFeature.self
    _ = MTRRVCRunModeFeature.self
    _ = MTRRadonConcentrationMeasurementFeature.self
    mtrRequire(MTRRadonConcentrationMeasurementFeature.numericMeasurement.rawValue == 1, "MTRRadonConcentrationMeasurementFeature.numericMeasurement")
    mtrRequire(MTRRadonConcentrationMeasurementFeature.levelIndication.rawValue == 2, "MTRRadonConcentrationMeasurementFeature.levelIndication")
    mtrRequire(MTRRadonConcentrationMeasurementFeature.mediumLevel.rawValue == 4, "MTRRadonConcentrationMeasurementFeature.mediumLevel")
    mtrRequire(MTRRadonConcentrationMeasurementFeature.criticalLevel.rawValue == 8, "MTRRadonConcentrationMeasurementFeature.criticalLevel")
    mtrRequire(MTRRadonConcentrationMeasurementFeature.peakMeasurement.rawValue == 16, "MTRRadonConcentrationMeasurementFeature.peakMeasurement")
    mtrRequire(MTRRadonConcentrationMeasurementFeature.averageMeasurement.rawValue == 32, "MTRRadonConcentrationMeasurementFeature.averageMeasurement")
    _ = MTRRefrigeratorAlarmAlarmBitmap.self
    mtrRequire(MTRRefrigeratorAlarmAlarmBitmap.doorOpen.rawValue == 1, "MTRRefrigeratorAlarmAlarmBitmap.doorOpen")
    _ = MTRServiceAreaFeature.self
    mtrRequire(MTRServiceAreaFeature.selectWhileRunning.rawValue == 1, "MTRServiceAreaFeature.selectWhileRunning")
    mtrRequire(MTRServiceAreaFeature.progressReporting.rawValue == 2, "MTRServiceAreaFeature.progressReporting")
    mtrRequire(MTRServiceAreaFeature.maps.rawValue == 4, "MTRServiceAreaFeature.maps")
    _ = MTRSmokeCOAlarmFeature.self
    mtrRequire(MTRSmokeCOAlarmFeature.smokeAlarm.rawValue == 1, "MTRSmokeCOAlarmFeature.smokeAlarm")
    mtrRequire(MTRSmokeCOAlarmFeature.coAlarm.rawValue == 2, "MTRSmokeCOAlarmFeature.coAlarm")
    _ = MTRSoftwareDiagnosticsFeature.self
    mtrRequire(MTRSoftwareDiagnosticsFeature.watermarks.rawValue == 1, "MTRSoftwareDiagnosticsFeature.watermarks")
    mtrRequire(MTRSoftwareDiagnosticsFeature.waterMarks.rawValue == 2, "MTRSoftwareDiagnosticsFeature.waterMarks")
    _ = MTRSwitchFeature.self
    mtrRequire(MTRSwitchFeature.latchingSwitch.rawValue == 1, "MTRSwitchFeature.latchingSwitch")
    mtrRequire(MTRSwitchFeature.momentarySwitch.rawValue == 2, "MTRSwitchFeature.momentarySwitch")
    mtrRequire(MTRSwitchFeature.momentarySwitchRelease.rawValue == 4, "MTRSwitchFeature.momentarySwitchRelease")
    mtrRequire(MTRSwitchFeature.momentarySwitchLongPress.rawValue == 8, "MTRSwitchFeature.momentarySwitchLongPress")
    mtrRequire(MTRSwitchFeature.momentarySwitchMultiPress.rawValue == 16, "MTRSwitchFeature.momentarySwitchMultiPress")
    mtrRequire(MTRSwitchFeature.actionSwitch.rawValue == 32, "MTRSwitchFeature.actionSwitch")
    _ = MTRTemperatureControlFeature.self
    mtrRequire(MTRTemperatureControlFeature.temperatureNumber.rawValue == 1, "MTRTemperatureControlFeature.temperatureNumber")
    mtrRequire(MTRTemperatureControlFeature.temperatureLevel.rawValue == 2, "MTRTemperatureControlFeature.temperatureLevel")
    mtrRequire(MTRTemperatureControlFeature.temperatureStep.rawValue == 4, "MTRTemperatureControlFeature.temperatureStep")
    _ = MTRTestClusterBitmap16MaskMap.self
    mtrRequire(MTRTestClusterBitmap16MaskMap.maskVal1.rawValue == 1, "MTRTestClusterBitmap16MaskMap.maskVal1")
    mtrRequire(MTRTestClusterBitmap16MaskMap.maskVal2.rawValue == 2, "MTRTestClusterBitmap16MaskMap.maskVal2")
    mtrRequire(MTRTestClusterBitmap16MaskMap.maskVal3.rawValue == 4, "MTRTestClusterBitmap16MaskMap.maskVal3")
    mtrRequire(MTRTestClusterBitmap16MaskMap.maskVal4.rawValue == 8, "MTRTestClusterBitmap16MaskMap.maskVal4")
    _ = MTRTestClusterBitmap32MaskMap.self
    mtrRequire(MTRTestClusterBitmap32MaskMap.maskVal1.rawValue == 1, "MTRTestClusterBitmap32MaskMap.maskVal1")
    mtrRequire(MTRTestClusterBitmap32MaskMap.maskVal2.rawValue == 2, "MTRTestClusterBitmap32MaskMap.maskVal2")
    mtrRequire(MTRTestClusterBitmap32MaskMap.maskVal3.rawValue == 4, "MTRTestClusterBitmap32MaskMap.maskVal3")
    mtrRequire(MTRTestClusterBitmap32MaskMap.maskVal4.rawValue == 8, "MTRTestClusterBitmap32MaskMap.maskVal4")
    _ = MTRTestClusterBitmap64MaskMap.self
    mtrRequire(MTRTestClusterBitmap64MaskMap.maskVal1.rawValue == 1, "MTRTestClusterBitmap64MaskMap.maskVal1")
    mtrRequire(MTRTestClusterBitmap64MaskMap.maskVal2.rawValue == 2, "MTRTestClusterBitmap64MaskMap.maskVal2")
    mtrRequire(MTRTestClusterBitmap64MaskMap.maskVal3.rawValue == 4, "MTRTestClusterBitmap64MaskMap.maskVal3")
    mtrRequire(MTRTestClusterBitmap64MaskMap.maskVal4.rawValue == 8, "MTRTestClusterBitmap64MaskMap.maskVal4")
    _ = MTRTestClusterBitmap8MaskMap.self
    mtrRequire(MTRTestClusterBitmap8MaskMap.maskVal1.rawValue == 1, "MTRTestClusterBitmap8MaskMap.maskVal1")
    mtrRequire(MTRTestClusterBitmap8MaskMap.maskVal2.rawValue == 2, "MTRTestClusterBitmap8MaskMap.maskVal2")
    mtrRequire(MTRTestClusterBitmap8MaskMap.maskVal3.rawValue == 4, "MTRTestClusterBitmap8MaskMap.maskVal3")
    mtrRequire(MTRTestClusterBitmap8MaskMap.maskVal4.rawValue == 8, "MTRTestClusterBitmap8MaskMap.maskVal4")
    _ = MTRTestClusterSimpleBitmap.self
    mtrRequire(MTRTestClusterSimpleBitmap.valueA.rawValue == 1, "MTRTestClusterSimpleBitmap.valueA")
    mtrRequire(MTRTestClusterSimpleBitmap.valueB.rawValue == 2, "MTRTestClusterSimpleBitmap.valueB")
    mtrRequire(MTRTestClusterSimpleBitmap.valueC.rawValue == 4, "MTRTestClusterSimpleBitmap.valueC")
    _ = MTRThermostatACErrorCodeBitmap.self
    mtrRequire(MTRThermostatACErrorCodeBitmap.compressorFail.rawValue == 1, "MTRThermostatACErrorCodeBitmap.compressorFail")
    mtrRequire(MTRThermostatACErrorCodeBitmap.roomSensorFail.rawValue == 2, "MTRThermostatACErrorCodeBitmap.roomSensorFail")
    mtrRequire(MTRThermostatACErrorCodeBitmap.outdoorSensorFail.rawValue == 4, "MTRThermostatACErrorCodeBitmap.outdoorSensorFail")
    mtrRequire(MTRThermostatACErrorCodeBitmap.coilSensorFail.rawValue == 8, "MTRThermostatACErrorCodeBitmap.coilSensorFail")
    mtrRequire(MTRThermostatACErrorCodeBitmap.fanFail.rawValue == 16, "MTRThermostatACErrorCodeBitmap.fanFail")
    _ = MTRThermostatDayOfWeek.self
    mtrRequire(MTRThermostatDayOfWeek.sunday.rawValue == 1, "MTRThermostatDayOfWeek.sunday")
    mtrRequire(MTRThermostatDayOfWeek.monday.rawValue == 2, "MTRThermostatDayOfWeek.monday")
    mtrRequire(MTRThermostatDayOfWeek.tuesday.rawValue == 4, "MTRThermostatDayOfWeek.tuesday")
    mtrRequire(MTRThermostatDayOfWeek.wednesday.rawValue == 8, "MTRThermostatDayOfWeek.wednesday")
    mtrRequire(MTRThermostatDayOfWeek.thursday.rawValue == 16, "MTRThermostatDayOfWeek.thursday")
    mtrRequire(MTRThermostatDayOfWeek.friday.rawValue == 32, "MTRThermostatDayOfWeek.friday")
    mtrRequire(MTRThermostatDayOfWeek.saturday.rawValue == 64, "MTRThermostatDayOfWeek.saturday")
    mtrRequire(MTRThermostatDayOfWeek.away.rawValue == 128, "MTRThermostatDayOfWeek.away")
    mtrRequire(MTRThermostatDayOfWeek.awayOrVacation.rawValue == 128, "MTRThermostatDayOfWeek.awayOrVacation")
    _ = MTRThermostatFeature.self
    mtrRequire(MTRThermostatFeature.heating.rawValue == 1, "MTRThermostatFeature.heating")
    mtrRequire(MTRThermostatFeature.cooling.rawValue == 2, "MTRThermostatFeature.cooling")
    mtrRequire(MTRThermostatFeature.occupancy.rawValue == 4, "MTRThermostatFeature.occupancy")
    mtrRequire(MTRThermostatFeature.scheduleConfiguration.rawValue == 8, "MTRThermostatFeature.scheduleConfiguration")
    mtrRequire(MTRThermostatFeature.schedule.rawValue == 16, "MTRThermostatFeature.schedule")
    mtrRequire(MTRThermostatFeature.setback.rawValue == 32, "MTRThermostatFeature.setback")
    mtrRequire(MTRThermostatFeature.autoMode.rawValue == 64, "MTRThermostatFeature.autoMode")
    mtrRequire(MTRThermostatFeature.automode.rawValue == 128, "MTRThermostatFeature.automode")
    mtrRequire(MTRThermostatFeature.localTemperatureNotExposed.rawValue == 256, "MTRThermostatFeature.localTemperatureNotExposed")
    mtrRequire(MTRThermostatFeature.matterScheduleConfiguration.rawValue == 512, "MTRThermostatFeature.matterScheduleConfiguration")
    mtrRequire(MTRThermostatFeature.presets.rawValue == 1024, "MTRThermostatFeature.presets")
    _ = MTRThermostatHVACSystemTypeBitmap.self
    mtrRequire(MTRThermostatHVACSystemTypeBitmap.coolingStage.rawValue == 1, "MTRThermostatHVACSystemTypeBitmap.coolingStage")
    mtrRequire(MTRThermostatHVACSystemTypeBitmap.heatingStage.rawValue == 2, "MTRThermostatHVACSystemTypeBitmap.heatingStage")
    mtrRequire(MTRThermostatHVACSystemTypeBitmap.heatingIsHeatPump.rawValue == 4, "MTRThermostatHVACSystemTypeBitmap.heatingIsHeatPump")
    mtrRequire(MTRThermostatHVACSystemTypeBitmap.heatingUsesFuel.rawValue == 8, "MTRThermostatHVACSystemTypeBitmap.heatingUsesFuel")
    _ = MTRThermostatModeForSequence.self
    mtrRequire(MTRThermostatModeForSequence.heatSetpointPresent.rawValue == 1, "MTRThermostatModeForSequence.heatSetpointPresent")
    mtrRequire(MTRThermostatModeForSequence.heatSetpointFieldPresent.rawValue == 2, "MTRThermostatModeForSequence.heatSetpointFieldPresent")
    mtrRequire(MTRThermostatModeForSequence.coolSetpointPresent.rawValue == 4, "MTRThermostatModeForSequence.coolSetpointPresent")
    mtrRequire(MTRThermostatModeForSequence.coolSetpointFieldPresent.rawValue == 8, "MTRThermostatModeForSequence.coolSetpointFieldPresent")
    _ = MTRThermostatOccupancyBitmap.self
    mtrRequire(MTRThermostatOccupancyBitmap.occupied.rawValue == 1, "MTRThermostatOccupancyBitmap.occupied")
    _ = MTRThermostatPresetTypeFeaturesBitmap.self
    mtrRequire(MTRThermostatPresetTypeFeaturesBitmap.automatic.rawValue == 1, "MTRThermostatPresetTypeFeaturesBitmap.automatic")
    mtrRequire(MTRThermostatPresetTypeFeaturesBitmap.supportsNames.rawValue == 2, "MTRThermostatPresetTypeFeaturesBitmap.supportsNames")
    _ = MTRThermostatProgrammingOperationModeBitmap.self
    mtrRequire(MTRThermostatProgrammingOperationModeBitmap.scheduleActive.rawValue == 1, "MTRThermostatProgrammingOperationModeBitmap.scheduleActive")
    mtrRequire(MTRThermostatProgrammingOperationModeBitmap.autoRecovery.rawValue == 2, "MTRThermostatProgrammingOperationModeBitmap.autoRecovery")
    mtrRequire(MTRThermostatProgrammingOperationModeBitmap.economy.rawValue == 4, "MTRThermostatProgrammingOperationModeBitmap.economy")
    _ = MTRThermostatRelayStateBitmap.self
    mtrRequire(MTRThermostatRelayStateBitmap.heat.rawValue == 1, "MTRThermostatRelayStateBitmap.heat")
    mtrRequire(MTRThermostatRelayStateBitmap.cool.rawValue == 2, "MTRThermostatRelayStateBitmap.cool")
    mtrRequire(MTRThermostatRelayStateBitmap.fan.rawValue == 4, "MTRThermostatRelayStateBitmap.fan")
    mtrRequire(MTRThermostatRelayStateBitmap.heatStage2.rawValue == 8, "MTRThermostatRelayStateBitmap.heatStage2")
    mtrRequire(MTRThermostatRelayStateBitmap.coolStage2.rawValue == 16, "MTRThermostatRelayStateBitmap.coolStage2")
    mtrRequire(MTRThermostatRelayStateBitmap.fanStage2.rawValue == 32, "MTRThermostatRelayStateBitmap.fanStage2")
    mtrRequire(MTRThermostatRelayStateBitmap.fanStage3.rawValue == 64, "MTRThermostatRelayStateBitmap.fanStage3")
    _ = MTRThermostatRemoteSensingBitmap.self
    mtrRequire(MTRThermostatRemoteSensingBitmap.localTemperature.rawValue == 1, "MTRThermostatRemoteSensingBitmap.localTemperature")
    mtrRequire(MTRThermostatRemoteSensingBitmap.outdoorTemperature.rawValue == 2, "MTRThermostatRemoteSensingBitmap.outdoorTemperature")
    mtrRequire(MTRThermostatRemoteSensingBitmap.occupancy.rawValue == 4, "MTRThermostatRemoteSensingBitmap.occupancy")
    _ = MTRThermostatScheduleDayOfWeekBitmap.self
    mtrRequire(MTRThermostatScheduleDayOfWeekBitmap.sunday.rawValue == 1, "MTRThermostatScheduleDayOfWeekBitmap.sunday")
    mtrRequire(MTRThermostatScheduleDayOfWeekBitmap.monday.rawValue == 2, "MTRThermostatScheduleDayOfWeekBitmap.monday")
    mtrRequire(MTRThermostatScheduleDayOfWeekBitmap.tuesday.rawValue == 4, "MTRThermostatScheduleDayOfWeekBitmap.tuesday")
    mtrRequire(MTRThermostatScheduleDayOfWeekBitmap.wednesday.rawValue == 8, "MTRThermostatScheduleDayOfWeekBitmap.wednesday")
    mtrRequire(MTRThermostatScheduleDayOfWeekBitmap.thursday.rawValue == 16, "MTRThermostatScheduleDayOfWeekBitmap.thursday")
    mtrRequire(MTRThermostatScheduleDayOfWeekBitmap.friday.rawValue == 32, "MTRThermostatScheduleDayOfWeekBitmap.friday")
    mtrRequire(MTRThermostatScheduleDayOfWeekBitmap.saturday.rawValue == 64, "MTRThermostatScheduleDayOfWeekBitmap.saturday")
    mtrRequire(MTRThermostatScheduleDayOfWeekBitmap.away.rawValue == 128, "MTRThermostatScheduleDayOfWeekBitmap.away")
    _ = MTRThermostatScheduleModeBitmap.self
    mtrRequire(MTRThermostatScheduleModeBitmap.heatSetpointPresent.rawValue == 1, "MTRThermostatScheduleModeBitmap.heatSetpointPresent")
    mtrRequire(MTRThermostatScheduleModeBitmap.coolSetpointPresent.rawValue == 2, "MTRThermostatScheduleModeBitmap.coolSetpointPresent")
    _ = MTRThermostatScheduleTypeFeaturesBitmap.self
    mtrRequire(MTRThermostatScheduleTypeFeaturesBitmap.supportsPresets.rawValue == 1, "MTRThermostatScheduleTypeFeaturesBitmap.supportsPresets")
    mtrRequire(MTRThermostatScheduleTypeFeaturesBitmap.supportsSetpoints.rawValue == 2, "MTRThermostatScheduleTypeFeaturesBitmap.supportsSetpoints")
    mtrRequire(MTRThermostatScheduleTypeFeaturesBitmap.supportsNames.rawValue == 4, "MTRThermostatScheduleTypeFeaturesBitmap.supportsNames")
    mtrRequire(MTRThermostatScheduleTypeFeaturesBitmap.supportsOff.rawValue == 8, "MTRThermostatScheduleTypeFeaturesBitmap.supportsOff")
    _ = MTRThreadBorderRouterManagementFeature.self
    mtrRequire(MTRThreadBorderRouterManagementFeature.panChange.rawValue == 1, "MTRThreadBorderRouterManagementFeature.panChange")
    _ = MTRThreadNetworkDiagnosticsFeature.self
    mtrRequire(MTRThreadNetworkDiagnosticsFeature.packetCounts.rawValue == 1, "MTRThreadNetworkDiagnosticsFeature.packetCounts")
    mtrRequire(MTRThreadNetworkDiagnosticsFeature.errorCounts.rawValue == 2, "MTRThreadNetworkDiagnosticsFeature.errorCounts")
    mtrRequire(MTRThreadNetworkDiagnosticsFeature.mleCounts.rawValue == 4, "MTRThreadNetworkDiagnosticsFeature.mleCounts")
    mtrRequire(MTRThreadNetworkDiagnosticsFeature.macCounts.rawValue == 8, "MTRThreadNetworkDiagnosticsFeature.macCounts")
    _ = MTRTimeFormatLocalizationFeature.self
    mtrRequire(MTRTimeFormatLocalizationFeature.calendarFormat.rawValue == 1, "MTRTimeFormatLocalizationFeature.calendarFormat")
    _ = MTRTimeSynchronizationFeature.self
    mtrRequire(MTRTimeSynchronizationFeature.timeZone.rawValue == 1, "MTRTimeSynchronizationFeature.timeZone")
    mtrRequire(MTRTimeSynchronizationFeature.ntpClient.rawValue == 2, "MTRTimeSynchronizationFeature.ntpClient")
    mtrRequire(MTRTimeSynchronizationFeature.ntpServer.rawValue == 4, "MTRTimeSynchronizationFeature.ntpServer")
    mtrRequire(MTRTimeSynchronizationFeature.timeSyncClient.rawValue == 8, "MTRTimeSynchronizationFeature.timeSyncClient")
    _ = MTRTotalVolatileOrganicCompoundsConcentrationMeasurementFeature.self
    mtrRequire(MTRTotalVolatileOrganicCompoundsConcentrationMeasurementFeature.numericMeasurement.rawValue == 1, "MTRTotalVolatileOrganicCompoundsConcentrationMeasurementFeature.numericMeasurement")
    mtrRequire(MTRTotalVolatileOrganicCompoundsConcentrationMeasurementFeature.levelIndication.rawValue == 2, "MTRTotalVolatileOrganicCompoundsConcentrationMeasurementFeature.levelIndication")
    mtrRequire(MTRTotalVolatileOrganicCompoundsConcentrationMeasurementFeature.mediumLevel.rawValue == 4, "MTRTotalVolatileOrganicCompoundsConcentrationMeasurementFeature.mediumLevel")
    mtrRequire(MTRTotalVolatileOrganicCompoundsConcentrationMeasurementFeature.criticalLevel.rawValue == 8, "MTRTotalVolatileOrganicCompoundsConcentrationMeasurementFeature.criticalLevel")
    mtrRequire(MTRTotalVolatileOrganicCompoundsConcentrationMeasurementFeature.peakMeasurement.rawValue == 16, "MTRTotalVolatileOrganicCompoundsConcentrationMeasurementFeature.peakMeasurement")
    mtrRequire(MTRTotalVolatileOrganicCompoundsConcentrationMeasurementFeature.averageMeasurement.rawValue == 32, "MTRTotalVolatileOrganicCompoundsConcentrationMeasurementFeature.averageMeasurement")
    _ = MTRUnitLocalizationFeature.self
    mtrRequire(MTRUnitLocalizationFeature.temperatureUnit.rawValue == 1, "MTRUnitLocalizationFeature.temperatureUnit")
    _ = MTRUnitTestingBitmap16MaskMap.self
    mtrRequire(MTRUnitTestingBitmap16MaskMap.maskVal1.rawValue == 1, "MTRUnitTestingBitmap16MaskMap.maskVal1")
    mtrRequire(MTRUnitTestingBitmap16MaskMap.maskVal2.rawValue == 2, "MTRUnitTestingBitmap16MaskMap.maskVal2")
    mtrRequire(MTRUnitTestingBitmap16MaskMap.maskVal3.rawValue == 4, "MTRUnitTestingBitmap16MaskMap.maskVal3")
    mtrRequire(MTRUnitTestingBitmap16MaskMap.maskVal4.rawValue == 8, "MTRUnitTestingBitmap16MaskMap.maskVal4")
    _ = MTRUnitTestingBitmap32MaskMap.self
    mtrRequire(MTRUnitTestingBitmap32MaskMap.maskVal1.rawValue == 1, "MTRUnitTestingBitmap32MaskMap.maskVal1")
    mtrRequire(MTRUnitTestingBitmap32MaskMap.maskVal2.rawValue == 2, "MTRUnitTestingBitmap32MaskMap.maskVal2")
    mtrRequire(MTRUnitTestingBitmap32MaskMap.maskVal3.rawValue == 4, "MTRUnitTestingBitmap32MaskMap.maskVal3")
    mtrRequire(MTRUnitTestingBitmap32MaskMap.maskVal4.rawValue == 8, "MTRUnitTestingBitmap32MaskMap.maskVal4")
    _ = MTRUnitTestingBitmap64MaskMap.self
    mtrRequire(MTRUnitTestingBitmap64MaskMap.maskVal1.rawValue == 1, "MTRUnitTestingBitmap64MaskMap.maskVal1")
    mtrRequire(MTRUnitTestingBitmap64MaskMap.maskVal2.rawValue == 2, "MTRUnitTestingBitmap64MaskMap.maskVal2")
    mtrRequire(MTRUnitTestingBitmap64MaskMap.maskVal3.rawValue == 4, "MTRUnitTestingBitmap64MaskMap.maskVal3")
    mtrRequire(MTRUnitTestingBitmap64MaskMap.maskVal4.rawValue == 8, "MTRUnitTestingBitmap64MaskMap.maskVal4")
    _ = MTRUnitTestingBitmap8MaskMap.self
    mtrRequire(MTRUnitTestingBitmap8MaskMap.maskVal1.rawValue == 1, "MTRUnitTestingBitmap8MaskMap.maskVal1")
    mtrRequire(MTRUnitTestingBitmap8MaskMap.maskVal2.rawValue == 2, "MTRUnitTestingBitmap8MaskMap.maskVal2")
    mtrRequire(MTRUnitTestingBitmap8MaskMap.maskVal3.rawValue == 4, "MTRUnitTestingBitmap8MaskMap.maskVal3")
    mtrRequire(MTRUnitTestingBitmap8MaskMap.maskVal4.rawValue == 8, "MTRUnitTestingBitmap8MaskMap.maskVal4")
    _ = MTRUnitTestingSimpleBitmap.self
    mtrRequire(MTRUnitTestingSimpleBitmap.valueA.rawValue == 1, "MTRUnitTestingSimpleBitmap.valueA")
    mtrRequire(MTRUnitTestingSimpleBitmap.valueB.rawValue == 2, "MTRUnitTestingSimpleBitmap.valueB")
    mtrRequire(MTRUnitTestingSimpleBitmap.valueC.rawValue == 4, "MTRUnitTestingSimpleBitmap.valueC")
    _ = MTRValveConfigurationAndControlFeature.self
    mtrRequire(MTRValveConfigurationAndControlFeature.timeSync.rawValue == 1, "MTRValveConfigurationAndControlFeature.timeSync")
    mtrRequire(MTRValveConfigurationAndControlFeature.level.rawValue == 2, "MTRValveConfigurationAndControlFeature.level")
    _ = MTRValveConfigurationAndControlValveFaultBitmap.self
    mtrRequire(MTRValveConfigurationAndControlValveFaultBitmap.generalFault.rawValue == 1, "MTRValveConfigurationAndControlValveFaultBitmap.generalFault")
    mtrRequire(MTRValveConfigurationAndControlValveFaultBitmap.blocked.rawValue == 2, "MTRValveConfigurationAndControlValveFaultBitmap.blocked")
    mtrRequire(MTRValveConfigurationAndControlValveFaultBitmap.leaking.rawValue == 4, "MTRValveConfigurationAndControlValveFaultBitmap.leaking")
    mtrRequire(MTRValveConfigurationAndControlValveFaultBitmap.notConnected.rawValue == 8, "MTRValveConfigurationAndControlValveFaultBitmap.notConnected")
    mtrRequire(MTRValveConfigurationAndControlValveFaultBitmap.shortCircuit.rawValue == 16, "MTRValveConfigurationAndControlValveFaultBitmap.shortCircuit")
    mtrRequire(MTRValveConfigurationAndControlValveFaultBitmap.currentExceeded.rawValue == 32, "MTRValveConfigurationAndControlValveFaultBitmap.currentExceeded")
    _ = MTRWaterHeaterManagementFeature.self
    mtrRequire(MTRWaterHeaterManagementFeature.energyManagement.rawValue == 1, "MTRWaterHeaterManagementFeature.energyManagement")
    mtrRequire(MTRWaterHeaterManagementFeature.tankPercent.rawValue == 2, "MTRWaterHeaterManagementFeature.tankPercent")
    _ = MTRWaterHeaterManagementWaterHeaterHeatSourceBitmap.self
    mtrRequire(MTRWaterHeaterManagementWaterHeaterHeatSourceBitmap.immersionElement1.rawValue == 1, "MTRWaterHeaterManagementWaterHeaterHeatSourceBitmap.immersionElement1")
    mtrRequire(MTRWaterHeaterManagementWaterHeaterHeatSourceBitmap.immersionElement2.rawValue == 2, "MTRWaterHeaterManagementWaterHeaterHeatSourceBitmap.immersionElement2")
    mtrRequire(MTRWaterHeaterManagementWaterHeaterHeatSourceBitmap.heatPump.rawValue == 4, "MTRWaterHeaterManagementWaterHeaterHeatSourceBitmap.heatPump")
    mtrRequire(MTRWaterHeaterManagementWaterHeaterHeatSourceBitmap.boiler.rawValue == 8, "MTRWaterHeaterManagementWaterHeaterHeatSourceBitmap.boiler")
    mtrRequire(MTRWaterHeaterManagementWaterHeaterHeatSourceBitmap.other.rawValue == 16, "MTRWaterHeaterManagementWaterHeaterHeatSourceBitmap.other")
    _ = MTRWiFiNetworkDiagnosticsFeature.self
    mtrRequire(MTRWiFiNetworkDiagnosticsFeature.packetCounts.rawValue == 1, "MTRWiFiNetworkDiagnosticsFeature.packetCounts")
    mtrRequire(MTRWiFiNetworkDiagnosticsFeature.errorCounts.rawValue == 2, "MTRWiFiNetworkDiagnosticsFeature.errorCounts")
    _ = MTRWindowCoveringConfigStatus.self
    mtrRequire(MTRWindowCoveringConfigStatus.operational.rawValue == 1, "MTRWindowCoveringConfigStatus.operational")
    mtrRequire(MTRWindowCoveringConfigStatus.onlineReserved.rawValue == 2, "MTRWindowCoveringConfigStatus.onlineReserved")
    mtrRequire(MTRWindowCoveringConfigStatus.liftMovementReversed.rawValue == 4, "MTRWindowCoveringConfigStatus.liftMovementReversed")
    mtrRequire(MTRWindowCoveringConfigStatus.liftPositionAware.rawValue == 8, "MTRWindowCoveringConfigStatus.liftPositionAware")
    mtrRequire(MTRWindowCoveringConfigStatus.tiltPositionAware.rawValue == 16, "MTRWindowCoveringConfigStatus.tiltPositionAware")
    mtrRequire(MTRWindowCoveringConfigStatus.liftEncoderControlled.rawValue == 32, "MTRWindowCoveringConfigStatus.liftEncoderControlled")
    mtrRequire(MTRWindowCoveringConfigStatus.tiltEncoderControlled.rawValue == 64, "MTRWindowCoveringConfigStatus.tiltEncoderControlled")
    _ = MTRWindowCoveringFeature.self
    mtrRequire(MTRWindowCoveringFeature.lift.rawValue == 1, "MTRWindowCoveringFeature.lift")
    mtrRequire(MTRWindowCoveringFeature.tilt.rawValue == 2, "MTRWindowCoveringFeature.tilt")
    mtrRequire(MTRWindowCoveringFeature.positionAwareLift.rawValue == 4, "MTRWindowCoveringFeature.positionAwareLift")
    mtrRequire(MTRWindowCoveringFeature.absolutePosition.rawValue == 8, "MTRWindowCoveringFeature.absolutePosition")
    mtrRequire(MTRWindowCoveringFeature.positionAwareTilt.rawValue == 16, "MTRWindowCoveringFeature.positionAwareTilt")
    _ = MTRWindowCoveringMode.self
    mtrRequire(MTRWindowCoveringMode.motorDirectionReversed.rawValue == 1, "MTRWindowCoveringMode.motorDirectionReversed")
    mtrRequire(MTRWindowCoveringMode.calibrationMode.rawValue == 2, "MTRWindowCoveringMode.calibrationMode")
    mtrRequire(MTRWindowCoveringMode.maintenanceMode.rawValue == 4, "MTRWindowCoveringMode.maintenanceMode")
    mtrRequire(MTRWindowCoveringMode.ledFeedback.rawValue == 8, "MTRWindowCoveringMode.ledFeedback")
    _ = MTRWindowCoveringOperationalStatus.self
    mtrRequire(MTRWindowCoveringOperationalStatus.global.rawValue == 1, "MTRWindowCoveringOperationalStatus.global")
    mtrRequire(MTRWindowCoveringOperationalStatus.lift.rawValue == 2, "MTRWindowCoveringOperationalStatus.lift")
    mtrRequire(MTRWindowCoveringOperationalStatus.tilt.rawValue == 4, "MTRWindowCoveringOperationalStatus.tilt")
    _ = MTRWindowCoveringSafetyStatus.self
    mtrRequire(MTRWindowCoveringSafetyStatus.remoteLockout.rawValue == 1, "MTRWindowCoveringSafetyStatus.remoteLockout")
    mtrRequire(MTRWindowCoveringSafetyStatus.tamperDetection.rawValue == 2, "MTRWindowCoveringSafetyStatus.tamperDetection")
    mtrRequire(MTRWindowCoveringSafetyStatus.failedCommunication.rawValue == 4, "MTRWindowCoveringSafetyStatus.failedCommunication")
    mtrRequire(MTRWindowCoveringSafetyStatus.positionFailure.rawValue == 8, "MTRWindowCoveringSafetyStatus.positionFailure")
    mtrRequire(MTRWindowCoveringSafetyStatus.thermalProtection.rawValue == 16, "MTRWindowCoveringSafetyStatus.thermalProtection")
    mtrRequire(MTRWindowCoveringSafetyStatus.obstacleDetected.rawValue == 32, "MTRWindowCoveringSafetyStatus.obstacleDetected")
    mtrRequire(MTRWindowCoveringSafetyStatus.power.rawValue == 64, "MTRWindowCoveringSafetyStatus.power")
    mtrRequire(MTRWindowCoveringSafetyStatus.stopInput.rawValue == 128, "MTRWindowCoveringSafetyStatus.stopInput")
    mtrRequire(MTRWindowCoveringSafetyStatus.motorJammed.rawValue == 256, "MTRWindowCoveringSafetyStatus.motorJammed")
    mtrRequire(MTRWindowCoveringSafetyStatus.hardwareFailure.rawValue == 512, "MTRWindowCoveringSafetyStatus.hardwareFailure")
    mtrRequire(MTRWindowCoveringSafetyStatus.manualOperation.rawValue == 1024, "MTRWindowCoveringSafetyStatus.manualOperation")
    mtrRequire(MTRWindowCoveringSafetyStatus.protection.rawValue == 2048, "MTRWindowCoveringSafetyStatus.protection")
}

func testOptionSetAlgebra() {
    var caps: MTRDiscoveryCapabilities = [.softAP, .BLE]
    mtrRequire(caps.contains(.softAP), "contains")
    mtrRequire(caps.contains(.BLE), "contains ble")
    mtrRequire(!caps.contains(.onNetwork), "no onnet")
    mtrRequire(caps.union(.onNetwork) == .allMask, "union")
    mtrRequire(caps.intersection(.BLE) == .BLE, "inter")
    mtrRequire(MTRDiscoveryCapabilities.softAP.isDisjoint(with: .BLE), "disjoint")
    mtrRequire(MTRDiscoveryCapabilities.allMask.isSuperset(of: .BLE), "superset")
    mtrRequire(MTRDiscoveryCapabilities.BLE.isSubset(of: .allMask), "subset")
    mtrRequire(!MTRDiscoveryCapabilities.allMask.isEmpty, "empty")
    _ = caps.insert(.onNetwork)
    _ = caps.remove(.softAP)
    caps.formUnion(.softAP)
    caps.formIntersection(.allMask)
    caps.formSymmetricDifference(.BLE)
    caps.subtract(.onNetwork)
    mtrRequire(MTRDiscoveryCapabilities([.softAP, .BLE]).symmetricDifference(.BLE) == .softAP, "sym")
    mtrRequire(MTRDiscoveryCapabilities.softAP.subtracting(.softAP).isEmpty, "subtracting")
    mtrRequire(MTRAccessControlFeature.`extension`.rawValue != 0 || MTRAccessControlFeature.`extension`.rawValue == 0, "ext")
}

