import Foundation
import Dispatch
import Matter

func testBaseOccupancySensingClassCacheFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    MTRBaseClusterOccupancySensing.readAttributeAcceptedCommandList(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributeAcceptedCommandList(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributeAttributeList(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributeAttributeList(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributeClusterRevision(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributeClusterRevision(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributeFeatureMap(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributeFeatureMap(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributeGeneratedCommandList(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributeGeneratedCommandList(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributeHoldTimeLimits(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributeHoldTime(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributeOccupancySensorTypeBitmap(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributeOccupancySensorTypeBitmap(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributeOccupancySensorType(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributeOccupancySensorType(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributeOccupancy(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributeOccupancy(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributePIROccupiedToUnoccupiedDelay(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributePIRUnoccupiedToOccupiedDelay(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributePIRUnoccupiedToOccupiedThreshold(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributePhysicalContactOccupiedToUnoccupiedDelay(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributePhysicalContactOccupiedToUnoccupiedDelay(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributePhysicalContactUnoccupiedToOccupiedDelay(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributePhysicalContactUnoccupiedToOccupiedDelay(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributePhysicalContactUnoccupiedToOccupiedThreshold(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributePhysicalContactUnoccupiedToOccupiedThreshold(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributePirOccupiedToUnoccupiedDelay(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributePirUnoccupiedToOccupiedDelay(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributePirUnoccupiedToOccupiedThreshold(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributeUltrasonicOccupiedToUnoccupiedDelay(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributeUltrasonicOccupiedToUnoccupiedDelay(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributeUltrasonicUnoccupiedToOccupiedDelay(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributeUltrasonicUnoccupiedToOccupiedDelay(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributeUltrasonicUnoccupiedToOccupiedThreshold(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterOccupancySensing.readAttributeUltrasonicUnoccupiedToOccupiedThreshold(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
}

func testBaseOccupancySensingInit() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    _ = MTRBaseClusterOccupancySensing(device: baseDevice, endpoint: 1, queue: DispatchQueue.global())
    _ = MTRBaseClusterOccupancySensing(device: baseDevice, endpointID: n(1), queue: DispatchQueue.global())
}

func testBaseOccupancySensingReadFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRBaseClusterOccupancySensing(device: baseDevice, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRBaseClusterOccupancySensing init")
        return
    }
    cluster.readAttributeAcceptedCommandList(completion: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributeAcceptedCommandList(completionHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributeAttributeList(completion: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributeAttributeList(completionHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributeClusterRevision(completion: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributeClusterRevision(completionHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributeFeatureMap(completion: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributeFeatureMap(completionHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributeGeneratedCommandList(completion: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributeGeneratedCommandList(completionHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributeHoldTimeLimits(completion: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributeHoldTime(completion: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributeOccupancySensorTypeBitmap(completion: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributeOccupancySensorTypeBitmap(completionHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributeOccupancySensorType(completion: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributeOccupancySensorType(completionHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributeOccupancy(completion: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributeOccupancy(completionHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributePIROccupiedToUnoccupiedDelay(completion: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributePIRUnoccupiedToOccupiedDelay(completion: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributePIRUnoccupiedToOccupiedThreshold(completion: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributePhysicalContactOccupiedToUnoccupiedDelay(completion: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributePhysicalContactOccupiedToUnoccupiedDelay(completionHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributePhysicalContactUnoccupiedToOccupiedDelay(completion: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributePhysicalContactUnoccupiedToOccupiedDelay(completionHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributePhysicalContactUnoccupiedToOccupiedThreshold(completion: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributePhysicalContactUnoccupiedToOccupiedThreshold(completionHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributePirOccupiedToUnoccupiedDelay(completionHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributePirUnoccupiedToOccupiedDelay(completionHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributePirUnoccupiedToOccupiedThreshold(completionHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributeUltrasonicOccupiedToUnoccupiedDelay(completion: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributeUltrasonicOccupiedToUnoccupiedDelay(completionHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributeUltrasonicUnoccupiedToOccupiedDelay(completion: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributeUltrasonicUnoccupiedToOccupiedDelay(completionHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributeUltrasonicUnoccupiedToOccupiedThreshold(completion: { _, err in mtrExpectInvalidState(err) })
    cluster.readAttributeUltrasonicUnoccupiedToOccupiedThreshold(completionHandler: { _, err in mtrExpectInvalidState(err) })
}

func testBaseOccupancySensingSubscribeFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRBaseClusterOccupancySensing(device: baseDevice, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRBaseClusterOccupancySensing init")
        return
    }
    cluster.subscribeAttributeAcceptedCommandList(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributeAcceptedCommandList(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributeAttributeList(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributeAttributeList(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributeClusterRevision(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributeClusterRevision(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributeFeatureMap(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributeFeatureMap(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributeGeneratedCommandList(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributeGeneratedCommandList(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributeHoldTimeLimits(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributeHoldTime(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributeOccupancySensorTypeBitmap(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributeOccupancySensorTypeBitmap(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributeOccupancySensorType(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributeOccupancySensorType(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributeOccupancy(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributeOccupancy(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributePIROccupiedToUnoccupiedDelay(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributePIRUnoccupiedToOccupiedDelay(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributePIRUnoccupiedToOccupiedThreshold(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributePhysicalContactOccupiedToUnoccupiedDelay(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributePhysicalContactOccupiedToUnoccupiedDelay(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributePhysicalContactUnoccupiedToOccupiedDelay(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributePhysicalContactUnoccupiedToOccupiedDelay(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributePhysicalContactUnoccupiedToOccupiedThreshold(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributePhysicalContactUnoccupiedToOccupiedThreshold(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributePirOccupiedToUnoccupiedDelay(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributePirUnoccupiedToOccupiedDelay(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributePirUnoccupiedToOccupiedThreshold(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributeUltrasonicOccupiedToUnoccupiedDelay(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributeUltrasonicOccupiedToUnoccupiedDelay(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributeUltrasonicUnoccupiedToOccupiedDelay(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributeUltrasonicUnoccupiedToOccupiedDelay(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributeUltrasonicUnoccupiedToOccupiedThreshold(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.subscribeAttributeUltrasonicUnoccupiedToOccupiedThreshold(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, err in mtrExpectInvalidState(err) })
}

func testBaseOccupancySensingWriteFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRBaseClusterOccupancySensing(device: baseDevice, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRBaseClusterOccupancySensing init")
        return
    }
    cluster.writeAttributeHoldTime(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeHoldTime(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributePIROccupiedToUnoccupiedDelay(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributePIROccupiedToUnoccupiedDelay(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributePIRUnoccupiedToOccupiedDelay(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributePIRUnoccupiedToOccupiedDelay(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributePIRUnoccupiedToOccupiedThreshold(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributePIRUnoccupiedToOccupiedThreshold(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributePhysicalContactOccupiedToUnoccupiedDelay(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributePhysicalContactOccupiedToUnoccupiedDelay(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributePhysicalContactOccupiedToUnoccupiedDelay(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributePhysicalContactOccupiedToUnoccupiedDelay(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributePhysicalContactUnoccupiedToOccupiedDelay(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributePhysicalContactUnoccupiedToOccupiedDelay(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributePhysicalContactUnoccupiedToOccupiedDelay(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributePhysicalContactUnoccupiedToOccupiedDelay(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributePhysicalContactUnoccupiedToOccupiedThreshold(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributePhysicalContactUnoccupiedToOccupiedThreshold(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributePhysicalContactUnoccupiedToOccupiedThreshold(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributePhysicalContactUnoccupiedToOccupiedThreshold(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributePirOccupiedToUnoccupiedDelay(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributePirOccupiedToUnoccupiedDelay(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributePirUnoccupiedToOccupiedDelay(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributePirUnoccupiedToOccupiedDelay(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributePirUnoccupiedToOccupiedThreshold(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributePirUnoccupiedToOccupiedThreshold(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeUltrasonicOccupiedToUnoccupiedDelay(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeUltrasonicOccupiedToUnoccupiedDelay(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeUltrasonicOccupiedToUnoccupiedDelay(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeUltrasonicOccupiedToUnoccupiedDelay(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeUltrasonicUnoccupiedToOccupiedDelay(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeUltrasonicUnoccupiedToOccupiedDelay(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeUltrasonicUnoccupiedToOccupiedDelay(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeUltrasonicUnoccupiedToOccupiedDelay(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeUltrasonicUnoccupiedToOccupiedThreshold(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeUltrasonicUnoccupiedToOccupiedThreshold(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeUltrasonicUnoccupiedToOccupiedThreshold(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeUltrasonicUnoccupiedToOccupiedThreshold(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
}
