import Foundation
import Dispatch
import Matter

func testClusterDoorLockCommandFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRClusterDoorLock(device: device, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRClusterDoorLock init")
        return
    }
    cluster.clearAliroReaderConfig(withExpectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.clearAliroReaderConfig(with: MTRDoorLockClusterClearAliroReaderConfigParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.clearCredential(with: MTRDoorLockClusterClearCredentialParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.clearCredential(with: MTRDoorLockClusterClearCredentialParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.clearHolidaySchedule(with: MTRDoorLockClusterClearHolidayScheduleParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.clearHolidaySchedule(with: MTRDoorLockClusterClearHolidayScheduleParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.clearUser(with: MTRDoorLockClusterClearUserParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.clearUser(with: MTRDoorLockClusterClearUserParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.clearWeekDaySchedule(with: MTRDoorLockClusterClearWeekDayScheduleParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.clearWeekDaySchedule(with: MTRDoorLockClusterClearWeekDayScheduleParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.clearYearDaySchedule(with: MTRDoorLockClusterClearYearDayScheduleParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.clearYearDaySchedule(with: MTRDoorLockClusterClearYearDayScheduleParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.credentialStatus(with: MTRDoorLockClusterGetCredentialStatusParams(), expectedValues: [], expectedValueInterval: n(1), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.credentialStatus(with: MTRDoorLockClusterGetCredentialStatusParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.getHolidaySchedule(with: MTRDoorLockClusterGetHolidayScheduleParams(), expectedValues: [], expectedValueInterval: n(1), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.getHolidaySchedule(with: MTRDoorLockClusterGetHolidayScheduleParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.getUserWith(MTRDoorLockClusterGetUserParams(), expectedValues: [], expectedValueInterval: n(1), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.getUserWith(MTRDoorLockClusterGetUserParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.getWeekDaySchedule(with: MTRDoorLockClusterGetWeekDayScheduleParams(), expectedValues: [], expectedValueInterval: n(1), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.getWeekDaySchedule(with: MTRDoorLockClusterGetWeekDayScheduleParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.getYearDaySchedule(with: MTRDoorLockClusterGetYearDayScheduleParams(), expectedValues: [], expectedValueInterval: n(1), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.getYearDaySchedule(with: MTRDoorLockClusterGetYearDayScheduleParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.lockDoor(withExpectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.lockDoor(with: MTRDoorLockClusterLockDoorParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.lockDoor(with: MTRDoorLockClusterLockDoorParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.setAliroReaderConfigWith(MTRDoorLockClusterSetAliroReaderConfigParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.setCredentialWith(MTRDoorLockClusterSetCredentialParams(), expectedValues: [], expectedValueInterval: n(1), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.setCredentialWith(MTRDoorLockClusterSetCredentialParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.setHolidayScheduleWith(MTRDoorLockClusterSetHolidayScheduleParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.setHolidayScheduleWith(MTRDoorLockClusterSetHolidayScheduleParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.setUserWith(MTRDoorLockClusterSetUserParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.setUserWith(MTRDoorLockClusterSetUserParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.setWeekDayScheduleWith(MTRDoorLockClusterSetWeekDayScheduleParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.setWeekDayScheduleWith(MTRDoorLockClusterSetWeekDayScheduleParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.setYearDayScheduleWith(MTRDoorLockClusterSetYearDayScheduleParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.setYearDayScheduleWith(MTRDoorLockClusterSetYearDayScheduleParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.unboltDoor(withExpectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.unboltDoor(with: MTRDoorLockClusterUnboltDoorParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.unlockDoor(withExpectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.unlockDoor(with: MTRDoorLockClusterUnlockDoorParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.unlockDoor(with: MTRDoorLockClusterUnlockDoorParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.unlockWithTimeout(with: MTRDoorLockClusterUnlockWithTimeoutParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.unlockWithTimeout(with: MTRDoorLockClusterUnlockWithTimeoutParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
}

func testClusterDoorLockInit() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    _ = MTRClusterDoorLock(device: device, endpoint: 1, queue: DispatchQueue.global())
    _ = MTRClusterDoorLock(device: device, endpointID: n(1), queue: DispatchQueue.global())
}

func testClusterDoorLockDeviceCache() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRClusterDoorLock(device: device, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRClusterDoorLock init")
        return
    }
    _ = cluster.readAttributeAcceptedCommandList(with: MTRReadParams())
    _ = cluster.readAttributeActuatorEnabled(with: MTRReadParams())
    _ = cluster.readAttributeAliroBLEAdvertisingVersion(with: MTRReadParams())
    _ = cluster.readAttributeAliroExpeditedTransactionSupportedProtocolVersions(with: MTRReadParams())
    _ = cluster.readAttributeAliroGroupResolvingKey(with: MTRReadParams())
    _ = cluster.readAttributeAliroReaderGroupIdentifier(with: MTRReadParams())
    _ = cluster.readAttributeAliroReaderGroupSubIdentifier(with: MTRReadParams())
    _ = cluster.readAttributeAliroReaderVerificationKey(with: MTRReadParams())
    _ = cluster.readAttributeAliroSupportedBLEUWBProtocolVersions(with: MTRReadParams())
    _ = cluster.readAttributeAttributeList(with: MTRReadParams())
    _ = cluster.readAttributeAutoRelockTime(with: MTRReadParams())
    _ = cluster.readAttributeClusterRevision(with: MTRReadParams())
    _ = cluster.readAttributeCredentialRulesSupport(with: MTRReadParams())
    _ = cluster.readAttributeDefaultConfigurationRegister(with: MTRReadParams())
    _ = cluster.readAttributeDoorClosedEvents(with: MTRReadParams())
    _ = cluster.readAttributeDoorOpenEvents(with: MTRReadParams())
    _ = cluster.readAttributeDoorState(with: MTRReadParams())
    _ = cluster.readAttributeEnableInsideStatusLED(with: MTRReadParams())
    _ = cluster.readAttributeEnableLocalProgramming(with: MTRReadParams())
    _ = cluster.readAttributeEnableOneTouchLocking(with: MTRReadParams())
    _ = cluster.readAttributeEnablePrivacyModeButton(with: MTRReadParams())
    _ = cluster.readAttributeExpiringUserTimeout(with: MTRReadParams())
    _ = cluster.readAttributeFeatureMap(with: MTRReadParams())
    _ = cluster.readAttributeGeneratedCommandList(with: MTRReadParams())
    _ = cluster.readAttributeLEDSettings(with: MTRReadParams())
    _ = cluster.readAttributeLanguage(with: MTRReadParams())
    _ = cluster.readAttributeLocalProgrammingFeatures(with: MTRReadParams())
    _ = cluster.readAttributeLockState(with: MTRReadParams())
    _ = cluster.readAttributeLockType(with: MTRReadParams())
    _ = cluster.readAttributeMaxPINCodeLength(with: MTRReadParams())
    _ = cluster.readAttributeMaxRFIDCodeLength(with: MTRReadParams())
    _ = cluster.readAttributeMinPINCodeLength(with: MTRReadParams())
    _ = cluster.readAttributeMinRFIDCodeLength(with: MTRReadParams())
    _ = cluster.readAttributeNumberOfAliroCredentialIssuerKeysSupported(with: MTRReadParams())
    _ = cluster.readAttributeNumberOfAliroEndpointKeysSupported(with: MTRReadParams())
    _ = cluster.readAttributeNumberOfCredentialsSupportedPerUser(with: MTRReadParams())
    _ = cluster.readAttributeNumberOfHolidaySchedulesSupported(with: MTRReadParams())
    _ = cluster.readAttributeNumberOfPINUsersSupported(with: MTRReadParams())
    _ = cluster.readAttributeNumberOfRFIDUsersSupported(with: MTRReadParams())
    _ = cluster.readAttributeNumberOfTotalUsersSupported(with: MTRReadParams())
    _ = cluster.readAttributeNumberOfWeekDaySchedulesSupportedPerUser(with: MTRReadParams())
    _ = cluster.readAttributeNumberOfYearDaySchedulesSupportedPerUser(with: MTRReadParams())
    _ = cluster.readAttributeOpenPeriod(with: MTRReadParams())
    _ = cluster.readAttributeOperatingMode(with: MTRReadParams())
    _ = cluster.readAttributeRequirePINforRemoteOperation(with: MTRReadParams())
    _ = cluster.readAttributeSendPINOverTheAir(with: MTRReadParams())
    _ = cluster.readAttributeSoundVolume(with: MTRReadParams())
    _ = cluster.readAttributeSupportedOperatingModes(with: MTRReadParams())
    _ = cluster.readAttributeUserCodeTemporaryDisableTime(with: MTRReadParams())
    _ = cluster.readAttributeWrongCodeEntryLimit(with: MTRReadParams())
    cluster.writeAttributeAutoRelockTime(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeAutoRelockTime(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeDoorClosedEvents(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeDoorClosedEvents(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeDoorOpenEvents(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeDoorOpenEvents(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeEnableInsideStatusLED(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeEnableInsideStatusLED(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeEnableLocalProgramming(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeEnableLocalProgramming(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeEnableOneTouchLocking(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeEnableOneTouchLocking(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeEnablePrivacyModeButton(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeEnablePrivacyModeButton(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeExpiringUserTimeout(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeExpiringUserTimeout(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeLEDSettings(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeLEDSettings(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeLanguage(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeLanguage(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeLocalProgrammingFeatures(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeLocalProgrammingFeatures(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeOpenPeriod(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeOpenPeriod(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeOperatingMode(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeOperatingMode(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeRequirePINforRemoteOperation(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeRequirePINforRemoteOperation(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeSendPINOverTheAir(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeSendPINOverTheAir(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeSoundVolume(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeSoundVolume(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeUserCodeTemporaryDisableTime(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeUserCodeTemporaryDisableTime(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeWrongCodeEntryLimit(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeWrongCodeEntryLimit(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    let probe = MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(7))
    cluster.writeAttributeAutoRelockTime(withValue: probe, expectedValueInterval: n(1))
    let cached = cluster.readAttributeAutoRelockTime(with: nil)
    mtrRequire(cached != nil, "expected-value cache round-trip")
}
