import Foundation
import Matter

func testErrorCodeRawValues() {
    mtrRequire(MTRError.Code.generalError.rawValue == 1, "general")
    mtrRequire(MTRError.Code.invalidStringLength.rawValue == 2, "strlen")
    mtrRequire(MTRError.Code.invalidIntegerValue.rawValue == 3, "int")
    mtrRequire(MTRError.Code.invalidArgument.rawValue == 4, "arg")
    mtrRequire(MTRError.Code.invalidMessageLength.rawValue == 5, "msglen")
    mtrRequire(MTRError.Code.invalidState.rawValue == 6, "state")
    mtrRequire(MTRError.Code.wrongAddressType.rawValue == 7, "addr")
    mtrRequire(MTRError.Code.integrityCheckFailed.rawValue == 8, "integrity")
    mtrRequire(MTRError.Code.timeout.rawValue == 9, "timeout")
    mtrRequire(MTRError.Code.bufferTooSmall.rawValue == 10, "buf")
    mtrRequire(MTRError.Code.fabricExists.rawValue == 11, "fabric")
    mtrRequire(MTRError.Code.unknownSchema.rawValue == 12, "schema")
    mtrRequire(MTRError.Code.schemaMismatch.rawValue == 13, "mismatch")
    mtrRequire(MTRError.Code.tlvDecodeFailed.rawValue == 14, "tlv")
    mtrRequire(MTRError.Code.dnssdUnauthorized.rawValue == 15, "dnssd")
    mtrRequire(MTRError.Code.cancelled.rawValue == 16, "cancel")
    mtrRequire(MTRError.Code.accessDenied.rawValue == 17, "acl")
    mtrRequire(MTRError.Code.busy.rawValue == 18, "busy")
    mtrRequire(MTRError.Code.notFound.rawValue == 19, "nf")
    mtrRequire(MTRError.Code(rawValue: 4) == .invalidArgument, "err rt")
    mtrRequire(MTRInteractionError.Code.failure.rawValue == 0x01, "fail")
    mtrRequire(MTRInteractionError.Code.invalidSubscription.rawValue == 0x7D, "isub")
    mtrRequire(MTRInteractionError.Code.unsupportedAccess.rawValue == 0x7E, "uacc")
    mtrRequire(MTRInteractionError.Code.unsupportedEndpoint.rawValue == 0x7F, "uep")
    mtrRequire(MTRInteractionError.Code.invalidAction.rawValue == 0x80, "ia")
    mtrRequire(MTRInteractionError.Code.unsupportedCommand.rawValue == 0x81, "ucmd")
    mtrRequire(MTRInteractionError.Code.invalidCommand.rawValue == 0x85, "icmd")
    mtrRequire(MTRInteractionError.Code.unsupportedAttribute.rawValue == 0x86, "uattr")
    mtrRequire(MTRInteractionError.Code.constraintError.rawValue == 0x87, "cons")
    mtrRequire(MTRInteractionError.Code.unsupportedWrite.rawValue == 0x88, "uwrite")
    mtrRequire(MTRInteractionError.Code.resourceExhausted.rawValue == 0x89, "res")
    mtrRequire(MTRInteractionError.Code.notFound.rawValue == 0x8B, "inf")
    mtrRequire(MTRInteractionError.Code.unreportableAttribute.rawValue == 0x8C, "unrep")
    mtrRequire(MTRInteractionError.Code.invalidDataType.rawValue == 0x8D, "idt")
    mtrRequire(MTRInteractionError.Code.unsupportedRead.rawValue == 0x8F, "uread")
    mtrRequire(MTRInteractionError.Code.dataVersionMismatch.rawValue == 0x92, "dvm")
    mtrRequire(MTRInteractionError.Code.timeout.rawValue == 0x94, "ito")
    mtrRequire(MTRInteractionError.Code.busy.rawValue == 0x9C, "ibusy")
    mtrRequire(MTRInteractionError.Code.accessRestricted.rawValue == 0x9D, "arestr")
    mtrRequire(MTRInteractionError.Code.unsupportedCluster.rawValue == 0xC3, "ucl")
    mtrRequire(MTRInteractionError.Code.noUpstreamSubscription.rawValue == 0xC5, "nup")
    mtrRequire(MTRInteractionError.Code.needsTimedInteraction.rawValue == 0xC6, "timed")
    mtrRequire(MTRInteractionError.Code.unsupportedEvent.rawValue == 0xC7, "uev")
    mtrRequire(MTRInteractionError.Code.pathsExhausted.rawValue == 0xC8, "paths")
    mtrRequire(MTRInteractionError.Code.timedRequestMismatch.rawValue == 0xC9, "trm")
    mtrRequire(MTRInteractionError.Code.failsafeRequired.rawValue == 0xCA, "fs")
    mtrRequire(MTRInteractionError.Code.invalidInState.rawValue == 0xCB, "iis")
    mtrRequire(MTRInteractionError.Code.noCommandResponse.rawValue == 0xCC, "ncr")
}

func testErrorCodeStatics() {
    mtrRequire(MTRError.invalidArgument == .invalidArgument, "static arg")
    mtrRequire(MTRError.notFound == .notFound, "static nf")
    mtrRequire(MTRError.timeout == .timeout, "static to")
    mtrRequire(MTRError.busy == .busy, "static busy")
    mtrRequire(MTRError.cancelled == .cancelled, "static can")
    mtrRequire(MTRError.accessDenied == .accessDenied, "static ad")
    mtrRequire(MTRError.invalidState == .invalidState, "static is")
    mtrRequire(MTRError.generalError == .generalError, "static ge")
    mtrRequire(MTRError.invalidStringLength == .invalidStringLength, "static sl")
    mtrRequire(MTRError.invalidIntegerValue == .invalidIntegerValue, "static iv")
    mtrRequire(MTRError.invalidMessageLength == .invalidMessageLength, "static ml")
    mtrRequire(MTRError.wrongAddressType == .wrongAddressType, "static wa")
    mtrRequire(MTRError.integrityCheckFailed == .integrityCheckFailed, "static ic")
    mtrRequire(MTRError.bufferTooSmall == .bufferTooSmall, "static bs")
    mtrRequire(MTRError.fabricExists == .fabricExists, "static fe")
    mtrRequire(MTRError.unknownSchema == .unknownSchema, "static us")
    mtrRequire(MTRError.schemaMismatch == .schemaMismatch, "static sm")
    mtrRequire(MTRError.tlvDecodeFailed == .tlvDecodeFailed, "static td")
    mtrRequire(MTRError.dnssdUnauthorized == .dnssdUnauthorized, "static du")
    mtrRequire(MTRInteractionError.failure == .failure, "istatic f")
    mtrRequire(MTRInteractionError.unsupportedCluster == .unsupportedCluster, "istatic uc")
    mtrRequire(MTRInteractionError.noCommandResponse == .noCommandResponse, "istatic ncr")
    mtrRequire(MTRInteractionError.constraintError == .constraintError, "istatic ce")
    mtrRequire(MTRInteractionError.needsTimedInteraction == .needsTimedInteraction, "istatic nt")
    mtrRequire(MTRInteractionError.failsafeRequired == .failsafeRequired, "istatic fs")
    mtrRequire(MTRInteractionError.invalidInState == .invalidInState, "istatic iis")
    mtrRequire(MTRInteractionError.unsupportedAccess == .unsupportedAccess, "istatic ua")
    mtrRequire(MTRInteractionError.unsupportedEndpoint == .unsupportedEndpoint, "istatic ue")
    mtrRequire(MTRInteractionError.invalidAction == .invalidAction, "istatic ia")
    mtrRequire(MTRInteractionError.unsupportedCommand == .unsupportedCommand, "istatic ucm")
    mtrRequire(MTRInteractionError.invalidCommand == .invalidCommand, "istatic ic")
    mtrRequire(MTRInteractionError.unsupportedAttribute == .unsupportedAttribute, "istatic uat")
    mtrRequire(MTRInteractionError.unsupportedWrite == .unsupportedWrite, "istatic uw")
    mtrRequire(MTRInteractionError.resourceExhausted == .resourceExhausted, "istatic re")
    mtrRequire(MTRInteractionError.notFound == .notFound, "istatic nf")
    mtrRequire(MTRInteractionError.unreportableAttribute == .unreportableAttribute, "istatic ur")
    mtrRequire(MTRInteractionError.invalidDataType == .invalidDataType, "istatic idt")
    mtrRequire(MTRInteractionError.unsupportedRead == .unsupportedRead, "istatic urd")
    mtrRequire(MTRInteractionError.dataVersionMismatch == .dataVersionMismatch, "istatic dv")
    mtrRequire(MTRInteractionError.timeout == .timeout, "istatic to")
    mtrRequire(MTRInteractionError.busy == .busy, "istatic ib")
    mtrRequire(MTRInteractionError.accessRestricted == .accessRestricted, "istatic ar")
    mtrRequire(MTRInteractionError.noUpstreamSubscription == .noUpstreamSubscription, "istatic nu")
    mtrRequire(MTRInteractionError.unsupportedEvent == .unsupportedEvent, "istatic uev")
    mtrRequire(MTRInteractionError.pathsExhausted == .pathsExhausted, "istatic pe")
    mtrRequire(MTRInteractionError.timedRequestMismatch == .timedRequestMismatch, "istatic tr")
    mtrRequire(MTRInteractionError.invalidSubscription == .invalidSubscription, "istatic isub")
}

func testErrorOverlay() {
    let err = MTRError(.invalidArgument, userInfo: [NSLocalizedDescriptionKey: "bad"])
    mtrRequire(err.code == .invalidArgument, "code")
    mtrRequire(err.errorCode == 4, "errorCode")
    mtrRequire(MTRError.errorDomain == MTRErrorDomain, "domain")
    let ns = err as NSError
    mtrRequire(ns.domain == MTRErrorDomain, "ns domain")
    mtrRequire(ns.code == 4, "ns code")
    mtrRequire(MTRError.Code.invalidArgument ~= err, "pattern typed")
    mtrRequire(MTRError.Code.invalidArgument ~= ns, "pattern ns")
    mtrRequire(!(MTRError.Code.notFound ~= err), "pattern neg")
    let fresh = NSError(domain: MTRErrorDomain, code: 4, userInfo: nil)
    mtrRequire(MTRError.Code.invalidArgument ~= fresh, "fresh ns")
    mtrRequire((fresh as? MTRError) == nil, "ns is not MTRError")
    let other = MTRError(.invalidArgument, userInfo: [NSLocalizedDescriptionKey: "bad"])
    mtrRequire(err == other, "eq")
    let im = MTRInteractionError(.unsupportedCluster)
    mtrRequire(im.errorCode == 0xC3, "im code")
    mtrRequire(MTRInteractionError.errorDomain == MTRInteractionErrorDomain, "im domain")
    mtrRequire(MTRInteractionError.Code.unsupportedCluster ~= im, "im pattern")
    mtrRequire(err != MTRError(.notFound), "neq")
    _ = err.hashValue
    _ = im.hashValue
}
