import Foundation
import Dispatch
import Matter

func testThermostatFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRBaseClusterThermostat(device: baseDevice, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRBaseClusterThermostat init")
        return
    }
    cluster.clearWeeklySchedule(completion: { _ in })
    cluster.clearWeeklySchedule(completionHandler: { _ in })
    cluster.getWeeklySchedule(with: MTRThermostatClusterGetWeeklyScheduleParams(), completion: { _, _ in })
    cluster.getWeeklySchedule(with: MTRThermostatClusterGetWeeklyScheduleParams(), completionHandler: { _, _ in })
    cluster.readAttributeACCapacity(completion: { _, _ in })
    cluster.readAttributeACCapacity(completionHandler: { _, _ in })
    cluster.readAttributeACCapacityformat(completion: { _, _ in })
    cluster.readAttributeACCapacityformat(completionHandler: { _, _ in })
    cluster.readAttributeACCoilTemperature(completion: { _, _ in })
    cluster.readAttributeACCoilTemperature(completionHandler: { _, _ in })
    cluster.readAttributeACCompressorType(completion: { _, _ in })
    cluster.readAttributeACCompressorType(completionHandler: { _, _ in })
    cluster.readAttributeACErrorCode(completion: { _, _ in })
    cluster.readAttributeACErrorCode(completionHandler: { _, _ in })
    cluster.readAttributeACLouverPosition(completion: { _, _ in })
    cluster.readAttributeACLouverPosition(completionHandler: { _, _ in })
    cluster.readAttributeACRefrigerantType(completion: { _, _ in })
    cluster.readAttributeACRefrigerantType(completionHandler: { _, _ in })
    cluster.readAttributeACType(completion: { _, _ in })
    cluster.readAttributeACType(completionHandler: { _, _ in })
    cluster.readAttributeAbsMaxCoolSetpointLimit(completion: { _, _ in })
    cluster.readAttributeAbsMaxCoolSetpointLimit(completionHandler: { _, _ in })
    cluster.readAttributeAbsMaxHeatSetpointLimit(completion: { _, _ in })
    cluster.readAttributeAbsMaxHeatSetpointLimit(completionHandler: { _, _ in })
    cluster.readAttributeAbsMinCoolSetpointLimit(completion: { _, _ in })
    cluster.readAttributeAbsMinCoolSetpointLimit(completionHandler: { _, _ in })
    cluster.readAttributeAbsMinHeatSetpointLimit(completion: { _, _ in })
    cluster.readAttributeAbsMinHeatSetpointLimit(completionHandler: { _, _ in })
    cluster.readAttributeAcceptedCommandList(completion: { _, _ in })
    cluster.readAttributeAcceptedCommandList(completionHandler: { _, _ in })
    cluster.readAttributeActivePresetHandle(completion: { _, _ in })
    cluster.readAttributeActiveScheduleHandle(completion: { _, _ in })
    cluster.readAttributeAttributeList(completion: { _, _ in })
    cluster.readAttributeAttributeList(completionHandler: { _, _ in })
    cluster.readAttributeClusterRevision(completion: { _, _ in })
    cluster.readAttributeClusterRevision(completionHandler: { _, _ in })
    cluster.readAttributeControlSequenceOfOperation(completion: { _, _ in })
    cluster.readAttributeControlSequenceOfOperation(completionHandler: { _, _ in })
    cluster.readAttributeEmergencyHeatDelta(completion: { _, _ in })
    cluster.readAttributeEmergencyHeatDelta(completionHandler: { _, _ in })
    cluster.readAttributeFeatureMap(completion: { _, _ in })
    cluster.readAttributeFeatureMap(completionHandler: { _, _ in })
    cluster.readAttributeGeneratedCommandList(completion: { _, _ in })
    cluster.readAttributeGeneratedCommandList(completionHandler: { _, _ in })
    cluster.readAttributeHVACSystemTypeConfiguration(completion: { _, _ in })
    cluster.readAttributeHVACSystemTypeConfiguration(completionHandler: { _, _ in })
    cluster.readAttributeLocalTemperatureCalibration(completion: { _, _ in })
    cluster.readAttributeLocalTemperatureCalibration(completionHandler: { _, _ in })
    cluster.readAttributeLocalTemperature(completion: { _, _ in })
    cluster.readAttributeLocalTemperature(completionHandler: { _, _ in })
    cluster.readAttributeMaxCoolSetpointLimit(completion: { _, _ in })
    cluster.readAttributeMaxCoolSetpointLimit(completionHandler: { _, _ in })
    cluster.readAttributeMaxHeatSetpointLimit(completion: { _, _ in })
    cluster.readAttributeMaxHeatSetpointLimit(completionHandler: { _, _ in })
    cluster.readAttributeMinCoolSetpointLimit(completion: { _, _ in })
    cluster.readAttributeMinCoolSetpointLimit(completionHandler: { _, _ in })
    cluster.readAttributeMinHeatSetpointLimit(completion: { _, _ in })
    cluster.readAttributeMinHeatSetpointLimit(completionHandler: { _, _ in })
    cluster.readAttributeMinSetpointDeadBand(completion: { _, _ in })
    cluster.readAttributeMinSetpointDeadBand(completionHandler: { _, _ in })
    cluster.readAttributeNumberOfDailyTransitions(completion: { _, _ in })
    cluster.readAttributeNumberOfDailyTransitions(completionHandler: { _, _ in })
    cluster.readAttributeNumberOfPresets(completion: { _, _ in })
    cluster.readAttributeNumberOfScheduleTransitionPerDay(completion: { _, _ in })
    cluster.readAttributeNumberOfScheduleTransitions(completion: { _, _ in })
    cluster.readAttributeNumberOfSchedules(completion: { _, _ in })
    cluster.readAttributeNumberOfWeeklyTransitions(completion: { _, _ in })
    cluster.readAttributeNumberOfWeeklyTransitions(completionHandler: { _, _ in })
    cluster.readAttributeOccupancy(completion: { _, _ in })
    cluster.readAttributeOccupancy(completionHandler: { _, _ in })
    cluster.readAttributeOccupiedCoolingSetpoint(completion: { _, _ in })
    cluster.readAttributeOccupiedCoolingSetpoint(completionHandler: { _, _ in })
    cluster.readAttributeOccupiedHeatingSetpoint(completion: { _, _ in })
    cluster.readAttributeOccupiedHeatingSetpoint(completionHandler: { _, _ in })
    cluster.readAttributeOccupiedSetbackMax(completion: { _, _ in })
    cluster.readAttributeOccupiedSetbackMax(completionHandler: { _, _ in })
    cluster.readAttributeOccupiedSetbackMin(completion: { _, _ in })
    cluster.readAttributeOccupiedSetbackMin(completionHandler: { _, _ in })
    cluster.readAttributeOccupiedSetback(completion: { _, _ in })
    cluster.readAttributeOccupiedSetback(completionHandler: { _, _ in })
    cluster.readAttributeOutdoorTemperature(completion: { _, _ in })
    cluster.readAttributeOutdoorTemperature(completionHandler: { _, _ in })
    cluster.readAttributePICoolingDemand(completion: { _, _ in })
    cluster.readAttributePICoolingDemand(completionHandler: { _, _ in })
    cluster.readAttributePIHeatingDemand(completion: { _, _ in })
    cluster.readAttributePIHeatingDemand(completionHandler: { _, _ in })
    cluster.readAttributePresetTypes(completion: { _, _ in })
    cluster.readAttributePresets(completion: { _, _ in })
    cluster.readAttributeRemoteSensing(completion: { _, _ in })
    cluster.readAttributeRemoteSensing(completionHandler: { _, _ in })
    cluster.readAttributeScheduleTypes(completion: { _, _ in })
    cluster.readAttributeSchedules(completion: { _, _ in })
    cluster.readAttributeSetpointChangeAmount(completion: { _, _ in })
    cluster.readAttributeSetpointChangeAmount(completionHandler: { _, _ in })
    cluster.readAttributeSetpointChangeSourceTimestamp(completion: { _, _ in })
    cluster.readAttributeSetpointChangeSourceTimestamp(completionHandler: { _, _ in })
    cluster.readAttributeSetpointChangeSource(completion: { _, _ in })
    cluster.readAttributeSetpointChangeSource(completionHandler: { _, _ in })
    cluster.readAttributeSetpointHoldExpiryTimestamp(completion: { _, _ in })
    cluster.readAttributeStartOfWeek(completion: { _, _ in })
    cluster.readAttributeStartOfWeek(completionHandler: { _, _ in })
    cluster.readAttributeSystemMode(completion: { _, _ in })
    cluster.readAttributeSystemMode(completionHandler: { _, _ in })
    cluster.readAttributeTemperatureSetpointHoldDuration(completion: { _, _ in })
    cluster.readAttributeTemperatureSetpointHoldDuration(completionHandler: { _, _ in })
    cluster.readAttributeTemperatureSetpointHold(completion: { _, _ in })
    cluster.readAttributeTemperatureSetpointHold(completionHandler: { _, _ in })
    cluster.readAttributeThermostatProgrammingOperationMode(completion: { _, _ in })
    cluster.readAttributeThermostatProgrammingOperationMode(completionHandler: { _, _ in })
    cluster.readAttributeThermostatRunningMode(completion: { _, _ in })
    cluster.readAttributeThermostatRunningMode(completionHandler: { _, _ in })
    cluster.readAttributeThermostatRunningState(completion: { _, _ in })
    cluster.readAttributeThermostatRunningState(completionHandler: { _, _ in })
    cluster.readAttributeUnoccupiedCoolingSetpoint(completion: { _, _ in })
    cluster.readAttributeUnoccupiedCoolingSetpoint(completionHandler: { _, _ in })
    cluster.readAttributeUnoccupiedHeatingSetpoint(completion: { _, _ in })
    cluster.readAttributeUnoccupiedHeatingSetpoint(completionHandler: { _, _ in })
    cluster.readAttributeUnoccupiedSetbackMax(completion: { _, _ in })
    cluster.readAttributeUnoccupiedSetbackMax(completionHandler: { _, _ in })
    cluster.readAttributeUnoccupiedSetbackMin(completion: { _, _ in })
    cluster.readAttributeUnoccupiedSetbackMin(completionHandler: { _, _ in })
    cluster.readAttributeUnoccupiedSetback(completion: { _, _ in })
    cluster.readAttributeUnoccupiedSetback(completionHandler: { _, _ in })
    cluster.subscribeAttributeACCapacity(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeACCapacity(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeACCapacityformat(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeACCapacityformat(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeACCoilTemperature(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeACCoilTemperature(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeACCompressorType(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeACCompressorType(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeACErrorCode(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeACErrorCode(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeACLouverPosition(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeACLouverPosition(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeACRefrigerantType(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeACRefrigerantType(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeACType(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeACType(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAbsMaxCoolSetpointLimit(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAbsMaxCoolSetpointLimit(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAbsMaxHeatSetpointLimit(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAbsMaxHeatSetpointLimit(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAbsMinCoolSetpointLimit(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAbsMinCoolSetpointLimit(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAbsMinHeatSetpointLimit(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAbsMinHeatSetpointLimit(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcceptedCommandList(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcceptedCommandList(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActivePresetHandle(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActiveScheduleHandle(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAttributeList(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAttributeList(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeClusterRevision(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeClusterRevision(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeControlSequenceOfOperation(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeControlSequenceOfOperation(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeEmergencyHeatDelta(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeEmergencyHeatDelta(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeFeatureMap(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeFeatureMap(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeGeneratedCommandList(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeGeneratedCommandList(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeHVACSystemTypeConfiguration(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeHVACSystemTypeConfiguration(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLocalTemperatureCalibration(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLocalTemperatureCalibration(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLocalTemperature(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLocalTemperature(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMaxCoolSetpointLimit(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMaxCoolSetpointLimit(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMaxHeatSetpointLimit(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMaxHeatSetpointLimit(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMinCoolSetpointLimit(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMinCoolSetpointLimit(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMinHeatSetpointLimit(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMinHeatSetpointLimit(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMinSetpointDeadBand(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMinSetpointDeadBand(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfDailyTransitions(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfDailyTransitions(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfPresets(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfScheduleTransitionPerDay(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfScheduleTransitions(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfSchedules(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfWeeklyTransitions(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfWeeklyTransitions(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOccupancy(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOccupancy(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOccupiedCoolingSetpoint(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOccupiedCoolingSetpoint(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOccupiedHeatingSetpoint(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOccupiedHeatingSetpoint(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOccupiedSetbackMax(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOccupiedSetbackMax(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOccupiedSetbackMin(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOccupiedSetbackMin(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOccupiedSetback(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOccupiedSetback(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOutdoorTemperature(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOutdoorTemperature(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePICoolingDemand(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePICoolingDemand(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePIHeatingDemand(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePIHeatingDemand(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePresetTypes(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePresets(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRemoteSensing(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRemoteSensing(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeScheduleTypes(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeSchedules(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeSetpointChangeAmount(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeSetpointChangeAmount(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeSetpointChangeSourceTimestamp(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeSetpointChangeSourceTimestamp(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeSetpointChangeSource(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeSetpointChangeSource(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeSetpointHoldExpiryTimestamp(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeStartOfWeek(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeStartOfWeek(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeSystemMode(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeSystemMode(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeTemperatureSetpointHoldDuration(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeTemperatureSetpointHoldDuration(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeTemperatureSetpointHold(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeTemperatureSetpointHold(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeThermostatProgrammingOperationMode(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeThermostatProgrammingOperationMode(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeThermostatRunningMode(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeThermostatRunningMode(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeThermostatRunningState(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeThermostatRunningState(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeUnoccupiedCoolingSetpoint(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeUnoccupiedCoolingSetpoint(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeUnoccupiedHeatingSetpoint(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeUnoccupiedHeatingSetpoint(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeUnoccupiedSetbackMax(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeUnoccupiedSetbackMax(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeUnoccupiedSetbackMin(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeUnoccupiedSetbackMin(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeUnoccupiedSetback(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeUnoccupiedSetback(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
}
