import Foundation
import Dispatch
import Matter

func testLevelControlFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRBaseClusterLevelControl(device: baseDevice, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRBaseClusterLevelControl init")
        return
    }
    cluster.readAttributeAcceptedCommandList(completion: { _, _ in })
    cluster.readAttributeAcceptedCommandList(completionHandler: { _, _ in })
    cluster.readAttributeAttributeList(completion: { _, _ in })
    cluster.readAttributeAttributeList(completionHandler: { _, _ in })
    cluster.readAttributeClusterRevision(completion: { _, _ in })
    cluster.readAttributeClusterRevision(completionHandler: { _, _ in })
    cluster.readAttributeCurrentFrequency(completion: { _, _ in })
    cluster.readAttributeCurrentFrequency(completionHandler: { _, _ in })
    cluster.readAttributeCurrentLevel(completion: { _, _ in })
    cluster.readAttributeCurrentLevel(completionHandler: { _, _ in })
    cluster.readAttributeDefaultMoveRate(completion: { _, _ in })
    cluster.readAttributeDefaultMoveRate(completionHandler: { _, _ in })
    cluster.readAttributeFeatureMap(completion: { _, _ in })
    cluster.readAttributeFeatureMap(completionHandler: { _, _ in })
    cluster.readAttributeGeneratedCommandList(completion: { _, _ in })
    cluster.readAttributeGeneratedCommandList(completionHandler: { _, _ in })
    cluster.readAttributeMaxFrequency(completion: { _, _ in })
    cluster.readAttributeMaxFrequency(completionHandler: { _, _ in })
    cluster.readAttributeMaxLevel(completion: { _, _ in })
    cluster.readAttributeMaxLevel(completionHandler: { _, _ in })
    cluster.readAttributeMinFrequency(completion: { _, _ in })
    cluster.readAttributeMinFrequency(completionHandler: { _, _ in })
    cluster.readAttributeMinLevel(completion: { _, _ in })
    cluster.readAttributeMinLevel(completionHandler: { _, _ in })
    cluster.readAttributeOffTransitionTime(completion: { _, _ in })
    cluster.readAttributeOffTransitionTime(completionHandler: { _, _ in })
    cluster.readAttributeOnLevel(completion: { _, _ in })
    cluster.readAttributeOnLevel(completionHandler: { _, _ in })
    cluster.readAttributeOnOffTransitionTime(completion: { _, _ in })
    cluster.readAttributeOnOffTransitionTime(completionHandler: { _, _ in })
    cluster.readAttributeOnTransitionTime(completion: { _, _ in })
    cluster.readAttributeOnTransitionTime(completionHandler: { _, _ in })
    cluster.readAttributeOptions(completion: { _, _ in })
    cluster.readAttributeOptions(completionHandler: { _, _ in })
    cluster.readAttributeRemainingTime(completion: { _, _ in })
    cluster.readAttributeRemainingTime(completionHandler: { _, _ in })
    cluster.readAttributeStartUpCurrentLevel(completion: { _, _ in })
    cluster.readAttributeStartUpCurrentLevel(completionHandler: { _, _ in })
    cluster.subscribeAttributeAcceptedCommandList(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcceptedCommandList(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAttributeList(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAttributeList(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeClusterRevision(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeClusterRevision(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentFrequency(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentFrequency(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentLevel(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentLevel(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDefaultMoveRate(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDefaultMoveRate(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeFeatureMap(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeFeatureMap(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeGeneratedCommandList(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeGeneratedCommandList(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMaxFrequency(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMaxFrequency(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMaxLevel(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMaxLevel(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMinFrequency(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMinFrequency(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMinLevel(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMinLevel(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOffTransitionTime(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOffTransitionTime(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOnLevel(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOnLevel(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOnOffTransitionTime(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOnOffTransitionTime(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOnTransitionTime(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOnTransitionTime(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOptions(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOptions(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRemainingTime(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRemainingTime(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeStartUpCurrentLevel(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeStartUpCurrentLevel(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
}
