import Foundation
import Dispatch
import Matter

func testColorControlFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRBaseClusterColorControl(device: baseDevice, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRBaseClusterColorControl init")
        return
    }
    cluster.readAttributeAcceptedCommandList(completion: { _, _ in })
    cluster.readAttributeAcceptedCommandList(completionHandler: { _, _ in })
    cluster.readAttributeAttributeList(completion: { _, _ in })
    cluster.readAttributeAttributeList(completionHandler: { _, _ in })
    cluster.readAttributeClusterRevision(completion: { _, _ in })
    cluster.readAttributeClusterRevision(completionHandler: { _, _ in })
    cluster.readAttributeColorCapabilities(completion: { _, _ in })
    cluster.readAttributeColorCapabilities(completionHandler: { _, _ in })
    cluster.readAttributeColorLoopActive(completion: { _, _ in })
    cluster.readAttributeColorLoopActive(completionHandler: { _, _ in })
    cluster.readAttributeColorLoopDirection(completion: { _, _ in })
    cluster.readAttributeColorLoopDirection(completionHandler: { _, _ in })
    cluster.readAttributeColorLoopStartEnhancedHue(completion: { _, _ in })
    cluster.readAttributeColorLoopStartEnhancedHue(completionHandler: { _, _ in })
    cluster.readAttributeColorLoopStoredEnhancedHue(completion: { _, _ in })
    cluster.readAttributeColorLoopStoredEnhancedHue(completionHandler: { _, _ in })
    cluster.readAttributeColorLoopTime(completion: { _, _ in })
    cluster.readAttributeColorLoopTime(completionHandler: { _, _ in })
    cluster.readAttributeColorMode(completion: { _, _ in })
    cluster.readAttributeColorMode(completionHandler: { _, _ in })
    cluster.readAttributeColorPointBIntensity(completion: { _, _ in })
    cluster.readAttributeColorPointBIntensity(completionHandler: { _, _ in })
    cluster.readAttributeColorPointBX(completion: { _, _ in })
    cluster.readAttributeColorPointBX(completionHandler: { _, _ in })
    cluster.readAttributeColorPointBY(completion: { _, _ in })
    cluster.readAttributeColorPointBY(completionHandler: { _, _ in })
    cluster.readAttributeColorPointGIntensity(completion: { _, _ in })
    cluster.readAttributeColorPointGIntensity(completionHandler: { _, _ in })
    cluster.readAttributeColorPointGX(completion: { _, _ in })
    cluster.readAttributeColorPointGX(completionHandler: { _, _ in })
    cluster.readAttributeColorPointGY(completion: { _, _ in })
    cluster.readAttributeColorPointGY(completionHandler: { _, _ in })
    cluster.readAttributeColorPointRIntensity(completion: { _, _ in })
    cluster.readAttributeColorPointRIntensity(completionHandler: { _, _ in })
    cluster.readAttributeColorPointRX(completion: { _, _ in })
    cluster.readAttributeColorPointRX(completionHandler: { _, _ in })
    cluster.readAttributeColorPointRY(completion: { _, _ in })
    cluster.readAttributeColorPointRY(completionHandler: { _, _ in })
    cluster.readAttributeColorTempPhysicalMaxMireds(completion: { _, _ in })
    cluster.readAttributeColorTempPhysicalMaxMireds(completionHandler: { _, _ in })
    cluster.readAttributeColorTempPhysicalMinMireds(completion: { _, _ in })
    cluster.readAttributeColorTempPhysicalMinMireds(completionHandler: { _, _ in })
    cluster.readAttributeColorTemperatureMireds(completion: { _, _ in })
    cluster.readAttributeColorTemperatureMireds(completionHandler: { _, _ in })
    cluster.readAttributeCompensationText(completion: { _, _ in })
    cluster.readAttributeCompensationText(completionHandler: { _, _ in })
    cluster.readAttributeCoupleColorTempToLevelMinMireds(completion: { _, _ in })
    cluster.readAttributeCoupleColorTempToLevelMinMireds(completionHandler: { _, _ in })
    cluster.readAttributeCurrentHue(completion: { _, _ in })
    cluster.readAttributeCurrentHue(completionHandler: { _, _ in })
    cluster.readAttributeCurrentSaturation(completion: { _, _ in })
    cluster.readAttributeCurrentSaturation(completionHandler: { _, _ in })
    cluster.readAttributeCurrentX(completion: { _, _ in })
    cluster.readAttributeCurrentX(completionHandler: { _, _ in })
    cluster.readAttributeCurrentY(completion: { _, _ in })
    cluster.readAttributeCurrentY(completionHandler: { _, _ in })
    cluster.readAttributeDriftCompensation(completion: { _, _ in })
    cluster.readAttributeDriftCompensation(completionHandler: { _, _ in })
    cluster.readAttributeEnhancedColorMode(completion: { _, _ in })
    cluster.readAttributeEnhancedColorMode(completionHandler: { _, _ in })
    cluster.readAttributeEnhancedCurrentHue(completion: { _, _ in })
    cluster.readAttributeEnhancedCurrentHue(completionHandler: { _, _ in })
    cluster.readAttributeFeatureMap(completion: { _, _ in })
    cluster.readAttributeFeatureMap(completionHandler: { _, _ in })
    cluster.readAttributeGeneratedCommandList(completion: { _, _ in })
    cluster.readAttributeGeneratedCommandList(completionHandler: { _, _ in })
    cluster.readAttributeNumberOfPrimaries(completion: { _, _ in })
    cluster.readAttributeNumberOfPrimaries(completionHandler: { _, _ in })
    cluster.readAttributeOptions(completion: { _, _ in })
    cluster.readAttributeOptions(completionHandler: { _, _ in })
    cluster.readAttributePrimary1Intensity(completion: { _, _ in })
    cluster.readAttributePrimary1Intensity(completionHandler: { _, _ in })
    cluster.readAttributePrimary1X(completion: { _, _ in })
    cluster.readAttributePrimary1X(completionHandler: { _, _ in })
    cluster.readAttributePrimary1Y(completion: { _, _ in })
    cluster.readAttributePrimary1Y(completionHandler: { _, _ in })
    cluster.readAttributePrimary2Intensity(completion: { _, _ in })
    cluster.readAttributePrimary2Intensity(completionHandler: { _, _ in })
    cluster.readAttributePrimary2X(completion: { _, _ in })
    cluster.readAttributePrimary2X(completionHandler: { _, _ in })
    cluster.readAttributePrimary2Y(completion: { _, _ in })
    cluster.readAttributePrimary2Y(completionHandler: { _, _ in })
    cluster.readAttributePrimary3Intensity(completion: { _, _ in })
    cluster.readAttributePrimary3Intensity(completionHandler: { _, _ in })
    cluster.readAttributePrimary3X(completion: { _, _ in })
    cluster.readAttributePrimary3X(completionHandler: { _, _ in })
    cluster.readAttributePrimary3Y(completion: { _, _ in })
    cluster.readAttributePrimary3Y(completionHandler: { _, _ in })
    cluster.readAttributePrimary4Intensity(completion: { _, _ in })
    cluster.readAttributePrimary4Intensity(completionHandler: { _, _ in })
    cluster.readAttributePrimary4X(completion: { _, _ in })
    cluster.readAttributePrimary4X(completionHandler: { _, _ in })
    cluster.readAttributePrimary4Y(completion: { _, _ in })
    cluster.readAttributePrimary4Y(completionHandler: { _, _ in })
    cluster.readAttributePrimary5Intensity(completion: { _, _ in })
    cluster.readAttributePrimary5Intensity(completionHandler: { _, _ in })
    cluster.readAttributePrimary5X(completion: { _, _ in })
    cluster.readAttributePrimary5X(completionHandler: { _, _ in })
    cluster.readAttributePrimary5Y(completion: { _, _ in })
    cluster.readAttributePrimary5Y(completionHandler: { _, _ in })
    cluster.readAttributePrimary6Intensity(completion: { _, _ in })
    cluster.readAttributePrimary6Intensity(completionHandler: { _, _ in })
    cluster.readAttributePrimary6X(completion: { _, _ in })
    cluster.readAttributePrimary6X(completionHandler: { _, _ in })
    cluster.readAttributePrimary6Y(completion: { _, _ in })
    cluster.readAttributePrimary6Y(completionHandler: { _, _ in })
    cluster.readAttributeRemainingTime(completion: { _, _ in })
    cluster.readAttributeRemainingTime(completionHandler: { _, _ in })
    cluster.readAttributeStartUpColorTemperatureMireds(completion: { _, _ in })
    cluster.readAttributeStartUpColorTemperatureMireds(completionHandler: { _, _ in })
    cluster.readAttributeWhitePointX(completion: { _, _ in })
    cluster.readAttributeWhitePointX(completionHandler: { _, _ in })
    cluster.readAttributeWhitePointY(completion: { _, _ in })
    cluster.readAttributeWhitePointY(completionHandler: { _, _ in })
    cluster.subscribeAttributeAcceptedCommandList(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcceptedCommandList(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAttributeList(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAttributeList(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeClusterRevision(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeClusterRevision(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorCapabilities(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorCapabilities(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorLoopActive(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorLoopActive(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorLoopDirection(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorLoopDirection(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorLoopStartEnhancedHue(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorLoopStartEnhancedHue(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorLoopStoredEnhancedHue(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorLoopStoredEnhancedHue(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorLoopTime(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorLoopTime(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorMode(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorMode(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorPointBIntensity(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorPointBIntensity(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorPointBX(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorPointBX(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorPointBY(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorPointBY(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorPointGIntensity(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorPointGIntensity(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorPointGX(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorPointGX(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorPointGY(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorPointGY(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorPointRIntensity(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorPointRIntensity(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorPointRX(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorPointRX(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorPointRY(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorPointRY(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorTempPhysicalMaxMireds(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorTempPhysicalMaxMireds(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorTempPhysicalMinMireds(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorTempPhysicalMinMireds(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorTemperatureMireds(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeColorTemperatureMireds(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCompensationText(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCompensationText(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCoupleColorTempToLevelMinMireds(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCoupleColorTempToLevelMinMireds(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentHue(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentHue(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentSaturation(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentSaturation(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentX(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentX(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentY(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentY(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDriftCompensation(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDriftCompensation(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeEnhancedColorMode(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeEnhancedColorMode(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeEnhancedCurrentHue(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeEnhancedCurrentHue(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeFeatureMap(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeFeatureMap(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeGeneratedCommandList(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeGeneratedCommandList(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfPrimaries(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfPrimaries(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOptions(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOptions(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary1Intensity(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary1Intensity(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary1X(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary1X(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary1Y(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary1Y(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary2Intensity(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary2Intensity(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary2X(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary2X(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary2Y(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary2Y(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary3Intensity(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary3Intensity(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary3X(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary3X(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary3Y(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary3Y(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary4Intensity(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary4Intensity(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary4X(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary4X(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary4Y(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary4Y(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary5Intensity(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary5Intensity(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary5X(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary5X(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary5Y(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary5Y(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary6Intensity(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary6Intensity(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary6X(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary6X(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary6Y(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePrimary6Y(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRemainingTime(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRemainingTime(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeStartUpColorTemperatureMireds(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeStartUpColorTemperatureMireds(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeWhitePointX(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeWhitePointX(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeWhitePointY(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeWhitePointY(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
}
