import Foundation
import Matter

func testCStringConstants() {
    mtrRequire(MTRArrayValueType == "Array", "MTRArrayValueType")
    mtrRequire(MTRAttributePathKey == "attributePath", "MTRAttributePathKey")
    mtrRequire(MTRBooleanValueType == "Boolean", "MTRBooleanValueType")
    mtrRequire(MTRCommandPathKey == "commandPath", "MTRCommandPathKey")
    mtrRequire(MTRContextTagKey == "contextTag", "MTRContextTagKey")
    mtrRequire(MTRDataKey == "data", "MTRDataKey")
    mtrRequire(MTRDataVersionKey == "dataVersion", "MTRDataVersionKey")
    mtrRequire(MTRDoubleValueType == "Double", "MTRDoubleValueType")
    mtrRequire(MTRErrorDomain == "MTRErrorDomain", "MTRErrorDomain")
    mtrRequire(MTRErrorKey == "error", "MTRErrorKey")
    mtrRequire(MTREventIsHistoricalKey == "historical", "MTREventIsHistoricalKey")
    mtrRequire(MTREventNumberKey == "eventNumber", "MTREventNumberKey")
    mtrRequire(MTREventPathKey == "eventPath", "MTREventPathKey")
    mtrRequire(MTREventPriorityKey == "eventPriority", "MTREventPriorityKey")
    mtrRequire(MTREventSystemUpTimeKey == "systemUpTime", "MTREventSystemUpTimeKey")
    mtrRequire(MTREventTimeTypeKey == "eventTimeType", "MTREventTimeTypeKey")
    mtrRequire(MTREventTimestampDateKey == "timestampDate", "MTREventTimestampDateKey")
    mtrRequire(MTRFloatValueType == "Float", "MTRFloatValueType")
    mtrRequire(MTRInteractionErrorDomain == "MTRInteractionErrorDomain", "MTRInteractionErrorDomain")
    mtrRequire(MTRNullValueType == "Null", "MTRNullValueType")
    mtrRequire(MTROctetStringValueType == "OctetString", "MTROctetStringValueType")
    mtrRequire(MTRPreviousDataKey == "previousData", "MTRPreviousDataKey")
    mtrRequire(MTRSignedIntegerValueType == "SignedInteger", "MTRSignedIntegerValueType")
    mtrRequire(MTRStructureValueType == "Structure", "MTRStructureValueType")
    mtrRequire(MTRTypeKey == "type", "MTRTypeKey")
    mtrRequire(MTRUTF8StringValueType == "UTF8String", "MTRUTF8StringValueType")
    mtrRequire(MTRUnsignedIntegerValueType == "UnsignedInteger", "MTRUnsignedIntegerValueType")
    mtrRequire(MTRValueKey == "value", "MTRValueKey")
    mtrRequire(MTRDeviceControllerRegistrationControllerCompressedFabricIDKey == "MTRDeviceControllerRegistrationControllerCompressedFabricIDKey", "MTRDeviceControllerRegistrationControllerCompressedFabricIDKey")
    mtrRequire(MTRDeviceControllerRegistrationControllerContextKey == "MTRDeviceControllerRegistrationControllerContextKey", "MTRDeviceControllerRegistrationControllerContextKey")
    mtrRequire(MTRDeviceControllerRegistrationControllerIsRunningKey == "MTRDeviceControllerRegistrationControllerIsRunningKey", "MTRDeviceControllerRegistrationControllerIsRunningKey")
    mtrRequire(MTRDeviceControllerRegistrationControllerNodeIDKey == "MTRDeviceControllerRegistrationControllerNodeIDKey", "MTRDeviceControllerRegistrationControllerNodeIDKey")
    mtrRequire(MTRDeviceControllerRegistrationDeviceInternalStateKey == "MTRDeviceControllerRegistrationDeviceInternalStateKey", "MTRDeviceControllerRegistrationDeviceInternalStateKey")
    mtrRequire(MTRDeviceControllerRegistrationNodeIDKey == "MTRDeviceControllerRegistrationNodeIDKey", "MTRDeviceControllerRegistrationNodeIDKey")
    mtrRequire(MTRDeviceControllerRegistrationNodeIDsKey == "MTRDeviceControllerRegistrationNodeIDsKey", "MTRDeviceControllerRegistrationNodeIDsKey")
    mtrRequire(MTRSizeThreadExtendedPANID == 8, "MTRSizeThreadExtendedPANID")
    mtrRequire(MTRSizeThreadExtendedPanId == 8, "MTRSizeThreadExtendedPanId")
    mtrRequire(MTRSizeThreadMasterKey == 16, "MTRSizeThreadMasterKey")
    mtrRequire(MTRSizeThreadNetworkName == 16, "MTRSizeThreadNetworkName")
    mtrRequire(MTRSizeThreadPANID == 2, "MTRSizeThreadPANID")
    mtrRequire(MTRSizeThreadPSKc == 16, "MTRSizeThreadPSKc")
    mtrRequire(MTR_ENABLE_PROVISIONAL == 0, "MTR_ENABLE_PROVISIONAL")
    mtrRequire(MTR_ENABLE_UNSTABLE_API == 0, "MTR_ENABLE_UNSTABLE_API")
    mtrRequire(MTR_NO_AVAILABILITY == 0, "MTR_NO_AVAILABILITY")
}
