import Foundation
import Dispatch
import Matter

func testDoorLockFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRBaseClusterDoorLock(device: baseDevice, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRBaseClusterDoorLock init")
        return
    }
    cluster.clearAliroReaderConfig(completion: { _ in })
    cluster.getHolidaySchedule(with: MTRDoorLockClusterGetHolidayScheduleParams(), completion: { _, _ in })
    cluster.getHolidaySchedule(with: MTRDoorLockClusterGetHolidayScheduleParams(), completionHandler: { _, _ in })
    cluster.getUserWith(MTRDoorLockClusterGetUserParams(), completion: { _, _ in })
    cluster.getUserWith(MTRDoorLockClusterGetUserParams(), completionHandler: { _, _ in })
    cluster.getWeekDaySchedule(with: MTRDoorLockClusterGetWeekDayScheduleParams(), completion: { _, _ in })
    cluster.getWeekDaySchedule(with: MTRDoorLockClusterGetWeekDayScheduleParams(), completionHandler: { _, _ in })
    cluster.getYearDaySchedule(with: MTRDoorLockClusterGetYearDayScheduleParams(), completion: { _, _ in })
    cluster.getYearDaySchedule(with: MTRDoorLockClusterGetYearDayScheduleParams(), completionHandler: { _, _ in })
    cluster.lockDoor(completion: { _ in })
    cluster.readAttributeAcceptedCommandList(completion: { _, _ in })
    cluster.readAttributeAcceptedCommandList(completionHandler: { _, _ in })
    cluster.readAttributeActuatorEnabled(completion: { _, _ in })
    cluster.readAttributeActuatorEnabled(completionHandler: { _, _ in })
    cluster.readAttributeAliroBLEAdvertisingVersion(completion: { _, _ in })
    cluster.readAttributeAliroExpeditedTransactionSupportedProtocolVersions(completion: { _, _ in })
    cluster.readAttributeAliroGroupResolvingKey(completion: { _, _ in })
    cluster.readAttributeAliroReaderGroupIdentifier(completion: { _, _ in })
    cluster.readAttributeAliroReaderGroupSubIdentifier(completion: { _, _ in })
    cluster.readAttributeAliroReaderVerificationKey(completion: { _, _ in })
    cluster.readAttributeAliroSupportedBLEUWBProtocolVersions(completion: { _, _ in })
    cluster.readAttributeAttributeList(completion: { _, _ in })
    cluster.readAttributeAttributeList(completionHandler: { _, _ in })
    cluster.readAttributeAutoRelockTime(completion: { _, _ in })
    cluster.readAttributeAutoRelockTime(completionHandler: { _, _ in })
    cluster.readAttributeClusterRevision(completion: { _, _ in })
    cluster.readAttributeClusterRevision(completionHandler: { _, _ in })
    cluster.readAttributeCredentialRulesSupport(completion: { _, _ in })
    cluster.readAttributeCredentialRulesSupport(completionHandler: { _, _ in })
    cluster.readAttributeDefaultConfigurationRegister(completion: { _, _ in })
    cluster.readAttributeDefaultConfigurationRegister(completionHandler: { _, _ in })
    cluster.readAttributeDoorClosedEvents(completion: { _, _ in })
    cluster.readAttributeDoorClosedEvents(completionHandler: { _, _ in })
    cluster.readAttributeDoorOpenEvents(completion: { _, _ in })
    cluster.readAttributeDoorOpenEvents(completionHandler: { _, _ in })
    cluster.readAttributeDoorState(completion: { _, _ in })
    cluster.readAttributeDoorState(completionHandler: { _, _ in })
    cluster.readAttributeEnableInsideStatusLED(completion: { _, _ in })
    cluster.readAttributeEnableInsideStatusLED(completionHandler: { _, _ in })
    cluster.readAttributeEnableLocalProgramming(completion: { _, _ in })
    cluster.readAttributeEnableLocalProgramming(completionHandler: { _, _ in })
    cluster.readAttributeEnableOneTouchLocking(completion: { _, _ in })
    cluster.readAttributeEnableOneTouchLocking(completionHandler: { _, _ in })
    cluster.readAttributeEnablePrivacyModeButton(completion: { _, _ in })
    cluster.readAttributeEnablePrivacyModeButton(completionHandler: { _, _ in })
    cluster.readAttributeExpiringUserTimeout(completion: { _, _ in })
    cluster.readAttributeExpiringUserTimeout(completionHandler: { _, _ in })
    cluster.readAttributeFeatureMap(completion: { _, _ in })
    cluster.readAttributeFeatureMap(completionHandler: { _, _ in })
    cluster.readAttributeGeneratedCommandList(completion: { _, _ in })
    cluster.readAttributeGeneratedCommandList(completionHandler: { _, _ in })
    cluster.readAttributeLEDSettings(completion: { _, _ in })
    cluster.readAttributeLEDSettings(completionHandler: { _, _ in })
    cluster.readAttributeLanguage(completion: { _, _ in })
    cluster.readAttributeLanguage(completionHandler: { _, _ in })
    cluster.readAttributeLocalProgrammingFeatures(completion: { _, _ in })
    cluster.readAttributeLocalProgrammingFeatures(completionHandler: { _, _ in })
    cluster.readAttributeLockState(completion: { _, _ in })
    cluster.readAttributeLockState(completionHandler: { _, _ in })
    cluster.readAttributeLockType(completion: { _, _ in })
    cluster.readAttributeLockType(completionHandler: { _, _ in })
    cluster.readAttributeMaxPINCodeLength(completion: { _, _ in })
    cluster.readAttributeMaxPINCodeLength(completionHandler: { _, _ in })
    cluster.readAttributeMaxRFIDCodeLength(completion: { _, _ in })
    cluster.readAttributeMaxRFIDCodeLength(completionHandler: { _, _ in })
    cluster.readAttributeMinPINCodeLength(completion: { _, _ in })
    cluster.readAttributeMinPINCodeLength(completionHandler: { _, _ in })
    cluster.readAttributeMinRFIDCodeLength(completion: { _, _ in })
    cluster.readAttributeMinRFIDCodeLength(completionHandler: { _, _ in })
    cluster.readAttributeNumberOfAliroCredentialIssuerKeysSupported(completion: { _, _ in })
    cluster.readAttributeNumberOfAliroEndpointKeysSupported(completion: { _, _ in })
    cluster.readAttributeNumberOfCredentialsSupportedPerUser(completion: { _, _ in })
    cluster.readAttributeNumberOfCredentialsSupportedPerUser(completionHandler: { _, _ in })
    cluster.readAttributeNumberOfHolidaySchedulesSupported(completion: { _, _ in })
    cluster.readAttributeNumberOfHolidaySchedulesSupported(completionHandler: { _, _ in })
    cluster.readAttributeNumberOfPINUsersSupported(completion: { _, _ in })
    cluster.readAttributeNumberOfPINUsersSupported(completionHandler: { _, _ in })
    cluster.readAttributeNumberOfRFIDUsersSupported(completion: { _, _ in })
    cluster.readAttributeNumberOfRFIDUsersSupported(completionHandler: { _, _ in })
    cluster.readAttributeNumberOfTotalUsersSupported(completion: { _, _ in })
    cluster.readAttributeNumberOfTotalUsersSupported(completionHandler: { _, _ in })
    cluster.readAttributeNumberOfWeekDaySchedulesSupportedPerUser(completion: { _, _ in })
    cluster.readAttributeNumberOfWeekDaySchedulesSupportedPerUser(completionHandler: { _, _ in })
    cluster.readAttributeNumberOfYearDaySchedulesSupportedPerUser(completion: { _, _ in })
    cluster.readAttributeNumberOfYearDaySchedulesSupportedPerUser(completionHandler: { _, _ in })
    cluster.readAttributeOpenPeriod(completion: { _, _ in })
    cluster.readAttributeOpenPeriod(completionHandler: { _, _ in })
    cluster.readAttributeOperatingMode(completion: { _, _ in })
    cluster.readAttributeOperatingMode(completionHandler: { _, _ in })
    cluster.readAttributeRequirePINforRemoteOperation(completion: { _, _ in })
    cluster.readAttributeRequirePINforRemoteOperation(completionHandler: { _, _ in })
    cluster.readAttributeSendPINOverTheAir(completion: { _, _ in })
    cluster.readAttributeSendPINOverTheAir(completionHandler: { _, _ in })
    cluster.readAttributeSoundVolume(completion: { _, _ in })
    cluster.readAttributeSoundVolume(completionHandler: { _, _ in })
    cluster.readAttributeSupportedOperatingModes(completion: { _, _ in })
    cluster.readAttributeSupportedOperatingModes(completionHandler: { _, _ in })
    cluster.readAttributeUserCodeTemporaryDisableTime(completion: { _, _ in })
    cluster.readAttributeUserCodeTemporaryDisableTime(completionHandler: { _, _ in })
    cluster.readAttributeWrongCodeEntryLimit(completion: { _, _ in })
    cluster.readAttributeWrongCodeEntryLimit(completionHandler: { _, _ in })
    cluster.subscribeAttributeAcceptedCommandList(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcceptedCommandList(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActuatorEnabled(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActuatorEnabled(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAliroBLEAdvertisingVersion(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAliroExpeditedTransactionSupportedProtocolVersions(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAliroGroupResolvingKey(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAliroReaderGroupIdentifier(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAliroReaderGroupSubIdentifier(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAliroReaderVerificationKey(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAliroSupportedBLEUWBProtocolVersions(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAttributeList(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAttributeList(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAutoRelockTime(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAutoRelockTime(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeClusterRevision(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeClusterRevision(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCredentialRulesSupport(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCredentialRulesSupport(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDefaultConfigurationRegister(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDefaultConfigurationRegister(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDoorClosedEvents(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDoorClosedEvents(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDoorOpenEvents(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDoorOpenEvents(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDoorState(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDoorState(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeEnableInsideStatusLED(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeEnableInsideStatusLED(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeEnableLocalProgramming(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeEnableLocalProgramming(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeEnableOneTouchLocking(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeEnableOneTouchLocking(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeEnablePrivacyModeButton(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeEnablePrivacyModeButton(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeExpiringUserTimeout(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeExpiringUserTimeout(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeFeatureMap(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeFeatureMap(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeGeneratedCommandList(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeGeneratedCommandList(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLEDSettings(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLEDSettings(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLanguage(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLanguage(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLocalProgrammingFeatures(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLocalProgrammingFeatures(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLockState(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLockState(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLockType(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLockType(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMaxPINCodeLength(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMaxPINCodeLength(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMaxRFIDCodeLength(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMaxRFIDCodeLength(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMinPINCodeLength(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMinPINCodeLength(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMinRFIDCodeLength(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMinRFIDCodeLength(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfAliroCredentialIssuerKeysSupported(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfAliroEndpointKeysSupported(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfCredentialsSupportedPerUser(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfCredentialsSupportedPerUser(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfHolidaySchedulesSupported(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfHolidaySchedulesSupported(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfPINUsersSupported(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfPINUsersSupported(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfRFIDUsersSupported(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfRFIDUsersSupported(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfTotalUsersSupported(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfTotalUsersSupported(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfWeekDaySchedulesSupportedPerUser(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfWeekDaySchedulesSupportedPerUser(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfYearDaySchedulesSupportedPerUser(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfYearDaySchedulesSupportedPerUser(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOpenPeriod(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOpenPeriod(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOperatingMode(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOperatingMode(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRequirePINforRemoteOperation(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRequirePINforRemoteOperation(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeSendPINOverTheAir(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeSendPINOverTheAir(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeSoundVolume(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeSoundVolume(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeSupportedOperatingModes(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeSupportedOperatingModes(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeUserCodeTemporaryDisableTime(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeUserCodeTemporaryDisableTime(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeWrongCodeEntryLimit(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeWrongCodeEntryLimit(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.unboltDoor(completion: { _ in })
    cluster.unlockDoor(completion: { _ in })
}
