import Foundation
import Dispatch
import Matter

func testClusterThermostatCommandFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRClusterThermostat(device: device, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRClusterThermostat init")
        return
    }
    cluster.atomicRequest(with: MTRThermostatClusterAtomicRequestParams(), expectedValues: [], expectedValueInterval: n(1), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.clearWeeklySchedule(withExpectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.clearWeeklySchedule(withExpectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.clearWeeklySchedule(with: MTRThermostatClusterClearWeeklyScheduleParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.clearWeeklySchedule(with: MTRThermostatClusterClearWeeklyScheduleParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.getWeeklySchedule(with: MTRThermostatClusterGetWeeklyScheduleParams(), expectedValues: [], expectedValueInterval: n(1), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.getWeeklySchedule(with: MTRThermostatClusterGetWeeklyScheduleParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.setActivePresetRequestWith(MTRThermostatClusterSetActivePresetRequestParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.setActiveScheduleRequestWith(MTRThermostatClusterSetActiveScheduleRequestParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.setWeeklyScheduleWith(MTRThermostatClusterSetWeeklyScheduleParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.setWeeklyScheduleWith(MTRThermostatClusterSetWeeklyScheduleParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.setpointRaiseLower(with: MTRThermostatClusterSetpointRaiseLowerParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.setpointRaiseLower(with: MTRThermostatClusterSetpointRaiseLowerParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
}

func testClusterThermostatInit() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    _ = MTRClusterThermostat(device: device, endpoint: 1, queue: DispatchQueue.global())
    _ = MTRClusterThermostat(device: device, endpointID: n(1), queue: DispatchQueue.global())
}

func testClusterThermostatDeviceCache() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRClusterThermostat(device: device, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRClusterThermostat init")
        return
    }
    _ = cluster.readAttributeACCapacity(with: MTRReadParams())
    _ = cluster.readAttributeACCapacityformat(with: MTRReadParams())
    _ = cluster.readAttributeACCoilTemperature(with: MTRReadParams())
    _ = cluster.readAttributeACCompressorType(with: MTRReadParams())
    _ = cluster.readAttributeACErrorCode(with: MTRReadParams())
    _ = cluster.readAttributeACLouverPosition(with: MTRReadParams())
    _ = cluster.readAttributeACRefrigerantType(with: MTRReadParams())
    _ = cluster.readAttributeACType(with: MTRReadParams())
    _ = cluster.readAttributeAbsMaxCoolSetpointLimit(with: MTRReadParams())
    _ = cluster.readAttributeAbsMaxHeatSetpointLimit(with: MTRReadParams())
    _ = cluster.readAttributeAbsMinCoolSetpointLimit(with: MTRReadParams())
    _ = cluster.readAttributeAbsMinHeatSetpointLimit(with: MTRReadParams())
    _ = cluster.readAttributeAcceptedCommandList(with: MTRReadParams())
    _ = cluster.readAttributeActivePresetHandle(with: MTRReadParams())
    _ = cluster.readAttributeActiveScheduleHandle(with: MTRReadParams())
    _ = cluster.readAttributeAttributeList(with: MTRReadParams())
    _ = cluster.readAttributeClusterRevision(with: MTRReadParams())
    _ = cluster.readAttributeControlSequenceOfOperation(with: MTRReadParams())
    _ = cluster.readAttributeEmergencyHeatDelta(with: MTRReadParams())
    _ = cluster.readAttributeFeatureMap(with: MTRReadParams())
    _ = cluster.readAttributeGeneratedCommandList(with: MTRReadParams())
    _ = cluster.readAttributeHVACSystemTypeConfiguration(with: MTRReadParams())
    _ = cluster.readAttributeLocalTemperatureCalibration(with: MTRReadParams())
    _ = cluster.readAttributeLocalTemperature(with: MTRReadParams())
    _ = cluster.readAttributeMaxCoolSetpointLimit(with: MTRReadParams())
    _ = cluster.readAttributeMaxHeatSetpointLimit(with: MTRReadParams())
    _ = cluster.readAttributeMinCoolSetpointLimit(with: MTRReadParams())
    _ = cluster.readAttributeMinHeatSetpointLimit(with: MTRReadParams())
    _ = cluster.readAttributeMinSetpointDeadBand(with: MTRReadParams())
    _ = cluster.readAttributeNumberOfDailyTransitions(with: MTRReadParams())
    _ = cluster.readAttributeNumberOfPresets(with: MTRReadParams())
    _ = cluster.readAttributeNumberOfScheduleTransitionPerDay(with: MTRReadParams())
    _ = cluster.readAttributeNumberOfScheduleTransitions(with: MTRReadParams())
    _ = cluster.readAttributeNumberOfSchedules(with: MTRReadParams())
    _ = cluster.readAttributeNumberOfWeeklyTransitions(with: MTRReadParams())
    _ = cluster.readAttributeOccupancy(with: MTRReadParams())
    _ = cluster.readAttributeOccupiedCoolingSetpoint(with: MTRReadParams())
    _ = cluster.readAttributeOccupiedHeatingSetpoint(with: MTRReadParams())
    _ = cluster.readAttributeOccupiedSetbackMax(with: MTRReadParams())
    _ = cluster.readAttributeOccupiedSetbackMin(with: MTRReadParams())
    _ = cluster.readAttributeOccupiedSetback(with: MTRReadParams())
    _ = cluster.readAttributeOutdoorTemperature(with: MTRReadParams())
    _ = cluster.readAttributePICoolingDemand(with: MTRReadParams())
    _ = cluster.readAttributePIHeatingDemand(with: MTRReadParams())
    _ = cluster.readAttributePresetTypes(with: MTRReadParams())
    _ = cluster.readAttributePresets(with: MTRReadParams())
    _ = cluster.readAttributeRemoteSensing(with: MTRReadParams())
    _ = cluster.readAttributeScheduleTypes(with: MTRReadParams())
    _ = cluster.readAttributeSchedules(with: MTRReadParams())
    _ = cluster.readAttributeSetpointChangeAmount(with: MTRReadParams())
    _ = cluster.readAttributeSetpointChangeSourceTimestamp(with: MTRReadParams())
    _ = cluster.readAttributeSetpointChangeSource(with: MTRReadParams())
    _ = cluster.readAttributeSetpointHoldExpiryTimestamp(with: MTRReadParams())
    _ = cluster.readAttributeStartOfWeek(with: MTRReadParams())
    _ = cluster.readAttributeSystemMode(with: MTRReadParams())
    _ = cluster.readAttributeTemperatureSetpointHoldDuration(with: MTRReadParams())
    _ = cluster.readAttributeTemperatureSetpointHold(with: MTRReadParams())
    _ = cluster.readAttributeThermostatProgrammingOperationMode(with: MTRReadParams())
    _ = cluster.readAttributeThermostatRunningMode(with: MTRReadParams())
    _ = cluster.readAttributeThermostatRunningState(with: MTRReadParams())
    _ = cluster.readAttributeUnoccupiedCoolingSetpoint(with: MTRReadParams())
    _ = cluster.readAttributeUnoccupiedHeatingSetpoint(with: MTRReadParams())
    _ = cluster.readAttributeUnoccupiedSetbackMax(with: MTRReadParams())
    _ = cluster.readAttributeUnoccupiedSetbackMin(with: MTRReadParams())
    _ = cluster.readAttributeUnoccupiedSetback(with: MTRReadParams())
    cluster.writeAttributeACCapacity(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeACCapacity(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeACCapacityformat(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeACCapacityformat(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeACCompressorType(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeACCompressorType(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeACErrorCode(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeACErrorCode(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeACLouverPosition(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeACLouverPosition(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeACRefrigerantType(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeACRefrigerantType(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeACType(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeACType(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeControlSequenceOfOperation(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeControlSequenceOfOperation(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeEmergencyHeatDelta(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeEmergencyHeatDelta(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeHVACSystemTypeConfiguration(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeHVACSystemTypeConfiguration(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeLocalTemperatureCalibration(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeLocalTemperatureCalibration(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeMaxCoolSetpointLimit(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeMaxCoolSetpointLimit(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeMaxHeatSetpointLimit(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    let probe = MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(7))
    cluster.writeAttributeACCapacity(withValue: probe, expectedValueInterval: n(1))
    let cached = cluster.readAttributeACCapacity(with: nil)
    mtrRequire(cached != nil, "expected-value cache round-trip")
}

func testClusterThermostatDeviceCacheGroup2() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRClusterThermostat(device: device, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRClusterThermostat init")
        return
    }
    cluster.writeAttributeMaxHeatSetpointLimit(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeMinCoolSetpointLimit(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeMinCoolSetpointLimit(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeMinHeatSetpointLimit(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeMinHeatSetpointLimit(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeMinSetpointDeadBand(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeMinSetpointDeadBand(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeOccupiedCoolingSetpoint(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeOccupiedCoolingSetpoint(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeOccupiedHeatingSetpoint(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeOccupiedHeatingSetpoint(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeOccupiedSetback(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeOccupiedSetback(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributePresets(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributePresets(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeRemoteSensing(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeRemoteSensing(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeSchedules(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeSchedules(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeSystemMode(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeSystemMode(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeTemperatureSetpointHoldDuration(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeTemperatureSetpointHoldDuration(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeTemperatureSetpointHold(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeTemperatureSetpointHold(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeThermostatProgrammingOperationMode(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeThermostatProgrammingOperationMode(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeUnoccupiedCoolingSetpoint(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeUnoccupiedCoolingSetpoint(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeUnoccupiedHeatingSetpoint(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeUnoccupiedHeatingSetpoint(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeUnoccupiedSetback(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeUnoccupiedSetback(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    let probe = MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(7))
    cluster.writeAttributeMaxHeatSetpointLimit(withValue: probe, expectedValueInterval: n(1))
    let cached = cluster.readAttributeMaxHeatSetpointLimit(with: nil)
    mtrRequire(cached != nil, "expected-value cache round-trip")
}
