import Foundation
import Dispatch
import Matter

func testElectricalMeasurementReadFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRBaseClusterElectricalMeasurement(device: baseDevice, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRBaseClusterElectricalMeasurement init")
        return
    }
    cluster.readAttributeAcActivePowerOverload(completion: { _, _ in })
    cluster.readAttributeAcActivePowerOverload(completionHandler: { _, _ in })
    cluster.readAttributeAcCurrentDivisor(completion: { _, _ in })
    cluster.readAttributeAcCurrentDivisor(completionHandler: { _, _ in })
    cluster.readAttributeAcCurrentMultiplier(completion: { _, _ in })
    cluster.readAttributeAcCurrentMultiplier(completionHandler: { _, _ in })
    cluster.readAttributeAcCurrentOverload(completion: { _, _ in })
    cluster.readAttributeAcCurrentOverload(completionHandler: { _, _ in })
    cluster.readAttributeAcFrequencyDivisor(completion: { _, _ in })
    cluster.readAttributeAcFrequencyDivisor(completionHandler: { _, _ in })
    cluster.readAttributeAcFrequencyMax(completion: { _, _ in })
    cluster.readAttributeAcFrequencyMax(completionHandler: { _, _ in })
    cluster.readAttributeAcFrequencyMin(completion: { _, _ in })
    cluster.readAttributeAcFrequencyMin(completionHandler: { _, _ in })
    cluster.readAttributeAcFrequencyMultiplier(completion: { _, _ in })
    cluster.readAttributeAcFrequencyMultiplier(completionHandler: { _, _ in })
    cluster.readAttributeAcFrequency(completion: { _, _ in })
    cluster.readAttributeAcFrequency(completionHandler: { _, _ in })
    cluster.readAttributeAcOverloadAlarmsMask(completion: { _, _ in })
    cluster.readAttributeAcOverloadAlarmsMask(completionHandler: { _, _ in })
    cluster.readAttributeAcPowerDivisor(completion: { _, _ in })
    cluster.readAttributeAcPowerDivisor(completionHandler: { _, _ in })
    cluster.readAttributeAcPowerMultiplier(completion: { _, _ in })
    cluster.readAttributeAcPowerMultiplier(completionHandler: { _, _ in })
    cluster.readAttributeAcReactivePowerOverload(completion: { _, _ in })
    cluster.readAttributeAcReactivePowerOverload(completionHandler: { _, _ in })
    cluster.readAttributeAcVoltageDivisor(completion: { _, _ in })
    cluster.readAttributeAcVoltageDivisor(completionHandler: { _, _ in })
    cluster.readAttributeAcVoltageMultiplier(completion: { _, _ in })
    cluster.readAttributeAcVoltageMultiplier(completionHandler: { _, _ in })
    cluster.readAttributeAcVoltageOverload(completion: { _, _ in })
    cluster.readAttributeAcVoltageOverload(completionHandler: { _, _ in })
    cluster.readAttributeAcceptedCommandList(completion: { _, _ in })
    cluster.readAttributeAcceptedCommandList(completionHandler: { _, _ in })
    cluster.readAttributeActiveCurrentPhaseB(completion: { _, _ in })
    cluster.readAttributeActiveCurrentPhaseB(completionHandler: { _, _ in })
    cluster.readAttributeActiveCurrentPhaseC(completion: { _, _ in })
    cluster.readAttributeActiveCurrentPhaseC(completionHandler: { _, _ in })
    cluster.readAttributeActivePowerMaxPhaseB(completion: { _, _ in })
    cluster.readAttributeActivePowerMaxPhaseB(completionHandler: { _, _ in })
    cluster.readAttributeActivePowerMaxPhaseC(completion: { _, _ in })
    cluster.readAttributeActivePowerMaxPhaseC(completionHandler: { _, _ in })
    cluster.readAttributeActivePowerMax(completion: { _, _ in })
    cluster.readAttributeActivePowerMax(completionHandler: { _, _ in })
    cluster.readAttributeActivePowerMinPhaseB(completion: { _, _ in })
    cluster.readAttributeActivePowerMinPhaseB(completionHandler: { _, _ in })
    cluster.readAttributeActivePowerMinPhaseC(completion: { _, _ in })
    cluster.readAttributeActivePowerMinPhaseC(completionHandler: { _, _ in })
    cluster.readAttributeActivePowerMin(completion: { _, _ in })
    cluster.readAttributeActivePowerMin(completionHandler: { _, _ in })
    cluster.readAttributeActivePowerPhaseB(completion: { _, _ in })
    cluster.readAttributeActivePowerPhaseB(completionHandler: { _, _ in })
    cluster.readAttributeActivePowerPhaseC(completion: { _, _ in })
    cluster.readAttributeActivePowerPhaseC(completionHandler: { _, _ in })
    cluster.readAttributeActivePower(completion: { _, _ in })
    cluster.readAttributeActivePower(completionHandler: { _, _ in })
    cluster.readAttributeApparentPowerPhaseB(completion: { _, _ in })
    cluster.readAttributeApparentPowerPhaseB(completionHandler: { _, _ in })
    cluster.readAttributeApparentPowerPhaseC(completion: { _, _ in })
    cluster.readAttributeApparentPowerPhaseC(completionHandler: { _, _ in })
    cluster.readAttributeApparentPower(completion: { _, _ in })
    cluster.readAttributeApparentPower(completionHandler: { _, _ in })
    cluster.readAttributeAttributeList(completion: { _, _ in })
    cluster.readAttributeAttributeList(completionHandler: { _, _ in })
    cluster.readAttributeAverageRmsOverVoltageCounterPhaseB(completion: { _, _ in })
    cluster.readAttributeAverageRmsOverVoltageCounterPhaseB(completionHandler: { _, _ in })
    cluster.readAttributeAverageRmsOverVoltageCounterPhaseC(completion: { _, _ in })
    cluster.readAttributeAverageRmsOverVoltageCounterPhaseC(completionHandler: { _, _ in })
    cluster.readAttributeAverageRmsOverVoltage(completion: { _, _ in })
    cluster.readAttributeAverageRmsOverVoltage(completionHandler: { _, _ in })
    cluster.readAttributeAverageRmsUnderVoltageCounterPhaseB(completion: { _, _ in })
    cluster.readAttributeAverageRmsUnderVoltageCounterPhaseB(completionHandler: { _, _ in })
    cluster.readAttributeAverageRmsUnderVoltageCounterPhaseC(completion: { _, _ in })
    cluster.readAttributeAverageRmsUnderVoltageCounterPhaseC(completionHandler: { _, _ in })
    cluster.readAttributeAverageRmsUnderVoltageCounter(completion: { _, _ in })
    cluster.readAttributeAverageRmsUnderVoltageCounter(completionHandler: { _, _ in })
    cluster.readAttributeAverageRmsUnderVoltage(completion: { _, _ in })
    cluster.readAttributeAverageRmsUnderVoltage(completionHandler: { _, _ in })
    cluster.readAttributeAverageRmsVoltageMeasurementPeriodPhaseB(completion: { _, _ in })
    cluster.readAttributeAverageRmsVoltageMeasurementPeriodPhaseB(completionHandler: { _, _ in })
    cluster.readAttributeAverageRmsVoltageMeasurementPeriodPhaseC(completion: { _, _ in })
    cluster.readAttributeAverageRmsVoltageMeasurementPeriodPhaseC(completionHandler: { _, _ in })
    cluster.readAttributeAverageRmsVoltageMeasurementPeriod(completion: { _, _ in })
    cluster.readAttributeAverageRmsVoltageMeasurementPeriod(completionHandler: { _, _ in })
    cluster.readAttributeClusterRevision(completion: { _, _ in })
    cluster.readAttributeClusterRevision(completionHandler: { _, _ in })
    cluster.readAttributeCurrentOverload(completion: { _, _ in })
    cluster.readAttributeCurrentOverload(completionHandler: { _, _ in })
    cluster.readAttributeDcCurrentDivisor(completion: { _, _ in })
    cluster.readAttributeDcCurrentDivisor(completionHandler: { _, _ in })
    cluster.readAttributeDcCurrentMax(completion: { _, _ in })
    cluster.readAttributeDcCurrentMax(completionHandler: { _, _ in })
    cluster.readAttributeDcCurrentMin(completion: { _, _ in })
    cluster.readAttributeDcCurrentMin(completionHandler: { _, _ in })
    cluster.readAttributeDcCurrentMultiplier(completion: { _, _ in })
    cluster.readAttributeDcCurrentMultiplier(completionHandler: { _, _ in })
    cluster.readAttributeDcCurrent(completion: { _, _ in })
    cluster.readAttributeDcCurrent(completionHandler: { _, _ in })
    cluster.readAttributeDcPowerDivisor(completion: { _, _ in })
    cluster.readAttributeDcPowerDivisor(completionHandler: { _, _ in })
    cluster.readAttributeDcPowerMax(completion: { _, _ in })
    cluster.readAttributeDcPowerMax(completionHandler: { _, _ in })
    cluster.readAttributeDcPowerMin(completion: { _, _ in })
    cluster.readAttributeDcPowerMin(completionHandler: { _, _ in })
    cluster.readAttributeDcPowerMultiplier(completion: { _, _ in })
    cluster.readAttributeDcPowerMultiplier(completionHandler: { _, _ in })
    cluster.readAttributeDcPower(completion: { _, _ in })
    cluster.readAttributeDcPower(completionHandler: { _, _ in })
    cluster.readAttributeDcVoltageDivisor(completion: { _, _ in })
    cluster.readAttributeDcVoltageDivisor(completionHandler: { _, _ in })
    cluster.readAttributeDcVoltageMax(completion: { _, _ in })
    cluster.readAttributeDcVoltageMax(completionHandler: { _, _ in })
    cluster.readAttributeDcVoltageMin(completion: { _, _ in })
    cluster.readAttributeDcVoltageMin(completionHandler: { _, _ in })
    cluster.readAttributeDcVoltageMultiplier(completion: { _, _ in })
    cluster.readAttributeDcVoltageMultiplier(completionHandler: { _, _ in })
    cluster.readAttributeDcVoltage(completion: { _, _ in })
    cluster.readAttributeDcVoltage(completionHandler: { _, _ in })
    cluster.readAttributeFeatureMap(completion: { _, _ in })
    cluster.readAttributeFeatureMap(completionHandler: { _, _ in })
    cluster.readAttributeGeneratedCommandList(completion: { _, _ in })
    cluster.readAttributeGeneratedCommandList(completionHandler: { _, _ in })
    cluster.readAttributeHarmonicCurrentMultiplier(completion: { _, _ in })
    cluster.readAttributeHarmonicCurrentMultiplier(completionHandler: { _, _ in })
    cluster.readAttributeInstantaneousActiveCurrent(completion: { _, _ in })
    cluster.readAttributeInstantaneousActiveCurrent(completionHandler: { _, _ in })
    cluster.readAttributeInstantaneousLineCurrent(completion: { _, _ in })
    cluster.readAttributeInstantaneousLineCurrent(completionHandler: { _, _ in })
    cluster.readAttributeInstantaneousPower(completion: { _, _ in })
    cluster.readAttributeInstantaneousPower(completionHandler: { _, _ in })
    cluster.readAttributeInstantaneousReactiveCurrent(completion: { _, _ in })
    cluster.readAttributeInstantaneousReactiveCurrent(completionHandler: { _, _ in })
    cluster.readAttributeInstantaneousVoltage(completion: { _, _ in })
    cluster.readAttributeInstantaneousVoltage(completionHandler: { _, _ in })
    cluster.readAttributeLineCurrentPhaseB(completion: { _, _ in })
    cluster.readAttributeLineCurrentPhaseB(completionHandler: { _, _ in })
    cluster.readAttributeLineCurrentPhaseC(completion: { _, _ in })
    cluster.readAttributeLineCurrentPhaseC(completionHandler: { _, _ in })
    cluster.readAttributeMeasured11thHarmonicCurrent(completion: { _, _ in })
    cluster.readAttributeMeasured11thHarmonicCurrent(completionHandler: { _, _ in })
    cluster.readAttributeMeasured1stHarmonicCurrent(completion: { _, _ in })
    cluster.readAttributeMeasured1stHarmonicCurrent(completionHandler: { _, _ in })
    cluster.readAttributeMeasured3rdHarmonicCurrent(completion: { _, _ in })
    cluster.readAttributeMeasured3rdHarmonicCurrent(completionHandler: { _, _ in })
    cluster.readAttributeMeasured5thHarmonicCurrent(completion: { _, _ in })
    cluster.readAttributeMeasured5thHarmonicCurrent(completionHandler: { _, _ in })
    cluster.readAttributeMeasured7thHarmonicCurrent(completion: { _, _ in })
    cluster.readAttributeMeasured7thHarmonicCurrent(completionHandler: { _, _ in })
    cluster.readAttributeMeasured9thHarmonicCurrent(completion: { _, _ in })
    cluster.readAttributeMeasured9thHarmonicCurrent(completionHandler: { _, _ in })
    cluster.readAttributeMeasuredPhase11thHarmonicCurrent(completion: { _, _ in })
    cluster.readAttributeMeasuredPhase11thHarmonicCurrent(completionHandler: { _, _ in })
    cluster.readAttributeMeasuredPhase1stHarmonicCurrent(completion: { _, _ in })
    cluster.readAttributeMeasuredPhase1stHarmonicCurrent(completionHandler: { _, _ in })
    cluster.readAttributeMeasuredPhase3rdHarmonicCurrent(completion: { _, _ in })
    cluster.readAttributeMeasuredPhase3rdHarmonicCurrent(completionHandler: { _, _ in })
    cluster.readAttributeMeasuredPhase5thHarmonicCurrent(completion: { _, _ in })
    cluster.readAttributeMeasuredPhase5thHarmonicCurrent(completionHandler: { _, _ in })
    cluster.readAttributeMeasuredPhase7thHarmonicCurrent(completion: { _, _ in })
    cluster.readAttributeMeasuredPhase7thHarmonicCurrent(completionHandler: { _, _ in })
    cluster.readAttributeMeasuredPhase9thHarmonicCurrent(completion: { _, _ in })
    cluster.readAttributeMeasuredPhase9thHarmonicCurrent(completionHandler: { _, _ in })
    cluster.readAttributeMeasurementType(completion: { _, _ in })
    cluster.readAttributeMeasurementType(completionHandler: { _, _ in })
    cluster.readAttributeNeutralCurrent(completion: { _, _ in })
    cluster.readAttributeNeutralCurrent(completionHandler: { _, _ in })
    cluster.readAttributeOverloadAlarmsMask(completion: { _, _ in })
    cluster.readAttributeOverloadAlarmsMask(completionHandler: { _, _ in })
    cluster.readAttributePhaseHarmonicCurrentMultiplier(completion: { _, _ in })
    cluster.readAttributePhaseHarmonicCurrentMultiplier(completionHandler: { _, _ in })
    cluster.readAttributePowerDivisor(completion: { _, _ in })
    cluster.readAttributePowerDivisor(completionHandler: { _, _ in })
    cluster.readAttributePowerFactorPhaseB(completion: { _, _ in })
    cluster.readAttributePowerFactorPhaseB(completionHandler: { _, _ in })
    cluster.readAttributePowerFactorPhaseC(completion: { _, _ in })
    cluster.readAttributePowerFactorPhaseC(completionHandler: { _, _ in })
    cluster.readAttributePowerFactor(completion: { _, _ in })
    cluster.readAttributePowerFactor(completionHandler: { _, _ in })
    cluster.readAttributePowerMultiplier(completion: { _, _ in })
    cluster.readAttributePowerMultiplier(completionHandler: { _, _ in })
    cluster.readAttributeReactiveCurrentPhaseB(completion: { _, _ in })
    cluster.readAttributeReactiveCurrentPhaseB(completionHandler: { _, _ in })
    cluster.readAttributeReactiveCurrentPhaseC(completion: { _, _ in })
    cluster.readAttributeReactiveCurrentPhaseC(completionHandler: { _, _ in })
    cluster.readAttributeReactivePowerPhaseB(completion: { _, _ in })
    cluster.readAttributeReactivePowerPhaseB(completionHandler: { _, _ in })
    cluster.readAttributeReactivePowerPhaseC(completion: { _, _ in })
    cluster.readAttributeReactivePowerPhaseC(completionHandler: { _, _ in })
    cluster.readAttributeReactivePower(completion: { _, _ in })
    cluster.readAttributeReactivePower(completionHandler: { _, _ in })
    cluster.readAttributeRmsCurrentMaxPhaseB(completion: { _, _ in })
    cluster.readAttributeRmsCurrentMaxPhaseB(completionHandler: { _, _ in })
    cluster.readAttributeRmsCurrentMaxPhaseC(completion: { _, _ in })
    cluster.readAttributeRmsCurrentMaxPhaseC(completionHandler: { _, _ in })
    cluster.readAttributeRmsCurrentMax(completion: { _, _ in })
    cluster.readAttributeRmsCurrentMax(completionHandler: { _, _ in })
    cluster.readAttributeRmsCurrentMinPhaseB(completion: { _, _ in })
    cluster.readAttributeRmsCurrentMinPhaseB(completionHandler: { _, _ in })
    cluster.readAttributeRmsCurrentMinPhaseC(completion: { _, _ in })
    cluster.readAttributeRmsCurrentMinPhaseC(completionHandler: { _, _ in })
    cluster.readAttributeRmsCurrentMin(completion: { _, _ in })
    cluster.readAttributeRmsCurrentMin(completionHandler: { _, _ in })
    cluster.readAttributeRmsCurrentPhaseB(completion: { _, _ in })
    cluster.readAttributeRmsCurrentPhaseB(completionHandler: { _, _ in })
    cluster.readAttributeRmsCurrentPhaseC(completion: { _, _ in })
    cluster.readAttributeRmsCurrentPhaseC(completionHandler: { _, _ in })
    cluster.readAttributeRmsCurrent(completion: { _, _ in })
    cluster.readAttributeRmsCurrent(completionHandler: { _, _ in })
    cluster.readAttributeRmsExtremeOverVoltagePeriodPhaseB(completion: { _, _ in })
    cluster.readAttributeRmsExtremeOverVoltagePeriodPhaseB(completionHandler: { _, _ in })
    cluster.readAttributeRmsExtremeOverVoltagePeriodPhaseC(completion: { _, _ in })
    cluster.readAttributeRmsExtremeOverVoltagePeriodPhaseC(completionHandler: { _, _ in })
    cluster.readAttributeRmsExtremeOverVoltagePeriod(completion: { _, _ in })
    cluster.readAttributeRmsExtremeOverVoltagePeriod(completionHandler: { _, _ in })
    cluster.readAttributeRmsExtremeOverVoltage(completion: { _, _ in })
    cluster.readAttributeRmsExtremeOverVoltage(completionHandler: { _, _ in })
    cluster.readAttributeRmsExtremeUnderVoltagePeriodPhaseB(completion: { _, _ in })
    cluster.readAttributeRmsExtremeUnderVoltagePeriodPhaseB(completionHandler: { _, _ in })
    cluster.readAttributeRmsExtremeUnderVoltagePeriodPhaseC(completion: { _, _ in })
    cluster.readAttributeRmsExtremeUnderVoltagePeriodPhaseC(completionHandler: { _, _ in })
    cluster.readAttributeRmsExtremeUnderVoltagePeriod(completion: { _, _ in })
    cluster.readAttributeRmsExtremeUnderVoltagePeriod(completionHandler: { _, _ in })
    cluster.readAttributeRmsExtremeUnderVoltage(completion: { _, _ in })
    cluster.readAttributeRmsExtremeUnderVoltage(completionHandler: { _, _ in })
    cluster.readAttributeRmsVoltageMaxPhaseB(completion: { _, _ in })
    cluster.readAttributeRmsVoltageMaxPhaseB(completionHandler: { _, _ in })
    cluster.readAttributeRmsVoltageMaxPhaseC(completion: { _, _ in })
    cluster.readAttributeRmsVoltageMaxPhaseC(completionHandler: { _, _ in })
    cluster.readAttributeRmsVoltageMax(completion: { _, _ in })
    cluster.readAttributeRmsVoltageMax(completionHandler: { _, _ in })
    cluster.readAttributeRmsVoltageMinPhaseB(completion: { _, _ in })
    cluster.readAttributeRmsVoltageMinPhaseB(completionHandler: { _, _ in })
    cluster.readAttributeRmsVoltageMinPhaseC(completion: { _, _ in })
    cluster.readAttributeRmsVoltageMinPhaseC(completionHandler: { _, _ in })
    cluster.readAttributeRmsVoltageMin(completion: { _, _ in })
    cluster.readAttributeRmsVoltageMin(completionHandler: { _, _ in })
    cluster.readAttributeRmsVoltagePhaseB(completion: { _, _ in })
    cluster.readAttributeRmsVoltagePhaseB(completionHandler: { _, _ in })
    cluster.readAttributeRmsVoltagePhaseC(completion: { _, _ in })
    cluster.readAttributeRmsVoltagePhaseC(completionHandler: { _, _ in })
    cluster.readAttributeRmsVoltageSagPeriodPhaseB(completion: { _, _ in })
    cluster.readAttributeRmsVoltageSagPeriodPhaseB(completionHandler: { _, _ in })
    cluster.readAttributeRmsVoltageSagPeriodPhaseC(completion: { _, _ in })
    cluster.readAttributeRmsVoltageSagPeriodPhaseC(completionHandler: { _, _ in })
    cluster.readAttributeRmsVoltageSagPeriod(completion: { _, _ in })
    cluster.readAttributeRmsVoltageSagPeriod(completionHandler: { _, _ in })
    cluster.readAttributeRmsVoltageSag(completion: { _, _ in })
    cluster.readAttributeRmsVoltageSag(completionHandler: { _, _ in })
    cluster.readAttributeRmsVoltageSwellPeriodPhaseB(completion: { _, _ in })
    cluster.readAttributeRmsVoltageSwellPeriodPhaseB(completionHandler: { _, _ in })
    cluster.readAttributeRmsVoltageSwellPeriodPhaseC(completion: { _, _ in })
    cluster.readAttributeRmsVoltageSwellPeriodPhaseC(completionHandler: { _, _ in })
    cluster.readAttributeRmsVoltageSwellPeriod(completion: { _, _ in })
    cluster.readAttributeRmsVoltageSwellPeriod(completionHandler: { _, _ in })
    cluster.readAttributeRmsVoltageSwell(completion: { _, _ in })
    cluster.readAttributeRmsVoltageSwell(completionHandler: { _, _ in })
    cluster.readAttributeRmsVoltage(completion: { _, _ in })
    cluster.readAttributeRmsVoltage(completionHandler: { _, _ in })
    cluster.readAttributeTotalActivePower(completion: { _, _ in })
    cluster.readAttributeTotalActivePower(completionHandler: { _, _ in })
    cluster.readAttributeTotalApparentPower(completion: { _, _ in })
    cluster.readAttributeTotalApparentPower(completionHandler: { _, _ in })
    cluster.readAttributeTotalReactivePower(completion: { _, _ in })
    cluster.readAttributeTotalReactivePower(completionHandler: { _, _ in })
    cluster.readAttributeVoltageOverload(completion: { _, _ in })
    cluster.readAttributeVoltageOverload(completionHandler: { _, _ in })
}

func testElectricalMeasurementSubscribeFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRBaseClusterElectricalMeasurement(device: baseDevice, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRBaseClusterElectricalMeasurement init")
        return
    }
    cluster.subscribeAttributeAcActivePowerOverload(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcActivePowerOverload(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcCurrentDivisor(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcCurrentDivisor(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcCurrentMultiplier(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcCurrentMultiplier(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcCurrentOverload(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcCurrentOverload(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcFrequencyDivisor(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcFrequencyDivisor(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcFrequencyMax(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcFrequencyMax(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcFrequencyMin(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcFrequencyMin(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcFrequencyMultiplier(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcFrequencyMultiplier(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcFrequency(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcFrequency(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcOverloadAlarmsMask(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcOverloadAlarmsMask(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcPowerDivisor(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcPowerDivisor(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcPowerMultiplier(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcPowerMultiplier(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcReactivePowerOverload(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcReactivePowerOverload(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcVoltageDivisor(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcVoltageDivisor(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcVoltageMultiplier(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcVoltageMultiplier(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcVoltageOverload(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcVoltageOverload(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcceptedCommandList(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcceptedCommandList(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActiveCurrentPhaseB(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActiveCurrentPhaseB(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActiveCurrentPhaseC(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActiveCurrentPhaseC(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActivePowerMaxPhaseB(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActivePowerMaxPhaseB(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActivePowerMaxPhaseC(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActivePowerMaxPhaseC(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActivePowerMax(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActivePowerMax(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActivePowerMinPhaseB(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActivePowerMinPhaseB(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActivePowerMinPhaseC(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActivePowerMinPhaseC(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActivePowerMin(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActivePowerMin(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActivePowerPhaseB(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActivePowerPhaseB(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActivePowerPhaseC(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActivePowerPhaseC(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActivePower(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeActivePower(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeApparentPowerPhaseB(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeApparentPowerPhaseB(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeApparentPowerPhaseC(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeApparentPowerPhaseC(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeApparentPower(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeApparentPower(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAttributeList(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAttributeList(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAverageRmsOverVoltageCounterPhaseB(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAverageRmsOverVoltageCounterPhaseB(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAverageRmsOverVoltageCounterPhaseC(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAverageRmsOverVoltageCounterPhaseC(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAverageRmsOverVoltage(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAverageRmsOverVoltage(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAverageRmsUnderVoltageCounterPhaseB(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAverageRmsUnderVoltageCounterPhaseB(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAverageRmsUnderVoltageCounterPhaseC(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAverageRmsUnderVoltageCounterPhaseC(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAverageRmsUnderVoltageCounter(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAverageRmsUnderVoltageCounter(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAverageRmsUnderVoltage(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAverageRmsUnderVoltage(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAverageRmsVoltageMeasurementPeriodPhaseB(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAverageRmsVoltageMeasurementPeriodPhaseB(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAverageRmsVoltageMeasurementPeriodPhaseC(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAverageRmsVoltageMeasurementPeriodPhaseC(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAverageRmsVoltageMeasurementPeriod(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAverageRmsVoltageMeasurementPeriod(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeClusterRevision(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeClusterRevision(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentOverload(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentOverload(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcCurrentDivisor(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcCurrentDivisor(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcCurrentMax(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcCurrentMax(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcCurrentMin(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcCurrentMin(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcCurrentMultiplier(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcCurrentMultiplier(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcCurrent(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcCurrent(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcPowerDivisor(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcPowerDivisor(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcPowerMax(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcPowerMax(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcPowerMin(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcPowerMin(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcPowerMultiplier(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcPowerMultiplier(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcPower(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcPower(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcVoltageDivisor(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcVoltageDivisor(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcVoltageMax(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcVoltageMax(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcVoltageMin(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcVoltageMin(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcVoltageMultiplier(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcVoltageMultiplier(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcVoltage(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeDcVoltage(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeFeatureMap(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeFeatureMap(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeGeneratedCommandList(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeGeneratedCommandList(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeHarmonicCurrentMultiplier(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeHarmonicCurrentMultiplier(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeInstantaneousActiveCurrent(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeInstantaneousActiveCurrent(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeInstantaneousLineCurrent(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeInstantaneousLineCurrent(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeInstantaneousPower(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeInstantaneousPower(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeInstantaneousReactiveCurrent(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeInstantaneousReactiveCurrent(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeInstantaneousVoltage(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeInstantaneousVoltage(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLineCurrentPhaseB(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLineCurrentPhaseB(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLineCurrentPhaseC(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeLineCurrentPhaseC(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasured11thHarmonicCurrent(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasured11thHarmonicCurrent(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasured1stHarmonicCurrent(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasured1stHarmonicCurrent(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasured3rdHarmonicCurrent(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasured3rdHarmonicCurrent(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasured5thHarmonicCurrent(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasured5thHarmonicCurrent(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasured7thHarmonicCurrent(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasured7thHarmonicCurrent(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasured9thHarmonicCurrent(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasured9thHarmonicCurrent(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasuredPhase11thHarmonicCurrent(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasuredPhase11thHarmonicCurrent(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasuredPhase1stHarmonicCurrent(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasuredPhase1stHarmonicCurrent(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasuredPhase3rdHarmonicCurrent(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasuredPhase3rdHarmonicCurrent(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasuredPhase5thHarmonicCurrent(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasuredPhase5thHarmonicCurrent(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasuredPhase7thHarmonicCurrent(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasuredPhase7thHarmonicCurrent(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasuredPhase9thHarmonicCurrent(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasuredPhase9thHarmonicCurrent(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasurementType(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMeasurementType(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNeutralCurrent(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNeutralCurrent(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOverloadAlarmsMask(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOverloadAlarmsMask(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePhaseHarmonicCurrentMultiplier(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePhaseHarmonicCurrentMultiplier(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePowerDivisor(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePowerDivisor(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePowerFactorPhaseB(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePowerFactorPhaseB(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePowerFactorPhaseC(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePowerFactorPhaseC(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePowerFactor(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePowerFactor(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePowerMultiplier(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePowerMultiplier(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeReactiveCurrentPhaseB(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeReactiveCurrentPhaseB(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeReactiveCurrentPhaseC(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeReactiveCurrentPhaseC(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeReactivePowerPhaseB(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeReactivePowerPhaseB(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeReactivePowerPhaseC(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeReactivePowerPhaseC(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeReactivePower(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeReactivePower(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsCurrentMaxPhaseB(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsCurrentMaxPhaseB(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsCurrentMaxPhaseC(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsCurrentMaxPhaseC(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsCurrentMax(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsCurrentMax(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsCurrentMinPhaseB(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsCurrentMinPhaseB(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsCurrentMinPhaseC(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsCurrentMinPhaseC(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsCurrentMin(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsCurrentMin(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsCurrentPhaseB(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsCurrentPhaseB(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsCurrentPhaseC(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsCurrentPhaseC(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsCurrent(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsCurrent(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsExtremeOverVoltagePeriodPhaseB(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsExtremeOverVoltagePeriodPhaseB(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsExtremeOverVoltagePeriodPhaseC(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsExtremeOverVoltagePeriodPhaseC(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsExtremeOverVoltagePeriod(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsExtremeOverVoltagePeriod(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsExtremeOverVoltage(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsExtremeOverVoltage(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsExtremeUnderVoltagePeriodPhaseB(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsExtremeUnderVoltagePeriodPhaseB(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsExtremeUnderVoltagePeriodPhaseC(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsExtremeUnderVoltagePeriodPhaseC(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsExtremeUnderVoltagePeriod(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsExtremeUnderVoltagePeriod(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsExtremeUnderVoltage(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsExtremeUnderVoltage(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageMaxPhaseB(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageMaxPhaseB(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageMaxPhaseC(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageMaxPhaseC(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageMax(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageMax(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageMinPhaseB(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageMinPhaseB(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageMinPhaseC(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageMinPhaseC(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageMin(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageMin(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltagePhaseB(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltagePhaseB(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltagePhaseC(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltagePhaseC(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageSagPeriodPhaseB(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageSagPeriodPhaseB(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageSagPeriodPhaseC(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageSagPeriodPhaseC(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageSagPeriod(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageSagPeriod(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageSag(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageSag(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageSwellPeriodPhaseB(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageSwellPeriodPhaseB(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageSwellPeriodPhaseC(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageSwellPeriodPhaseC(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageSwellPeriod(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageSwellPeriod(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageSwell(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltageSwell(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltage(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeRmsVoltage(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeTotalActivePower(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeTotalActivePower(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeTotalApparentPower(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeTotalApparentPower(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeTotalReactivePower(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeTotalReactivePower(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeVoltageOverload(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeVoltageOverload(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
}

func testElectricalMeasurementCommandFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRBaseClusterElectricalMeasurement(device: baseDevice, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRBaseClusterElectricalMeasurement init")
        return
    }
    cluster.getProfileCommand(with: MTRElectricalMeasurementClusterGetMeasurementProfileCommandParams(), completion: { _ in })
    cluster.getProfileCommand(with: MTRElectricalMeasurementClusterGetMeasurementProfileCommandParams(), completionHandler: { _ in })
    cluster.getProfileInfoCommand(completion: { _ in })
    cluster.getProfileInfoCommand(completionHandler: { _ in })
    cluster.getProfileInfoCommand(with: MTRElectricalMeasurementClusterGetProfileInfoCommandParams(), completion: { _ in })
    cluster.getProfileInfoCommand(with: MTRElectricalMeasurementClusterGetProfileInfoCommandParams(), completionHandler: { _ in })
}

func testClusterElectricalMeasurementCache() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRClusterElectricalMeasurement(device: device, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRClusterElectricalMeasurement init")
        return
    }
    cluster.getProfileCommand(with: MTRElectricalMeasurementClusterGetMeasurementProfileCommandParams(), expectedValues: nil, expectedValueInterval: nil, completion: { _ in })
    cluster.getProfileCommand(with: MTRElectricalMeasurementClusterGetMeasurementProfileCommandParams(), expectedValues: nil, expectedValueInterval: nil, completionHandler: { _ in })
    cluster.getProfileInfoCommand(withExpectedValues: nil, expectedValueInterval: nil, completion: { _ in })
    cluster.getProfileInfoCommand(withExpectedValues: nil, expectedValueInterval: nil, completionHandler: { _ in })
    cluster.getProfileInfoCommand(with: MTRElectricalMeasurementClusterGetProfileInfoCommandParams(), expectedValues: nil, expectedValueInterval: nil, completion: { _ in })
    cluster.getProfileInfoCommand(with: MTRElectricalMeasurementClusterGetProfileInfoCommandParams(), expectedValues: nil, expectedValueInterval: nil, completionHandler: { _ in })
    _ = cluster.readAttributeAcActivePowerOverload(with: MTRReadParams())
    _ = cluster.readAttributeAcCurrentDivisor(with: MTRReadParams())
    _ = cluster.readAttributeAcCurrentMultiplier(with: MTRReadParams())
    _ = cluster.readAttributeAcCurrentOverload(with: MTRReadParams())
    _ = cluster.readAttributeAcFrequencyDivisor(with: MTRReadParams())
    _ = cluster.readAttributeAcFrequencyMax(with: MTRReadParams())
    _ = cluster.readAttributeAcFrequencyMin(with: MTRReadParams())
    _ = cluster.readAttributeAcFrequencyMultiplier(with: MTRReadParams())
    _ = cluster.readAttributeAcFrequency(with: MTRReadParams())
    _ = cluster.readAttributeAcOverloadAlarmsMask(with: MTRReadParams())
    _ = cluster.readAttributeAcPowerDivisor(with: MTRReadParams())
    _ = cluster.readAttributeAcPowerMultiplier(with: MTRReadParams())
    _ = cluster.readAttributeAcReactivePowerOverload(with: MTRReadParams())
    _ = cluster.readAttributeAcVoltageDivisor(with: MTRReadParams())
    _ = cluster.readAttributeAcVoltageMultiplier(with: MTRReadParams())
    _ = cluster.readAttributeAcVoltageOverload(with: MTRReadParams())
    _ = cluster.readAttributeAcceptedCommandList(with: MTRReadParams())
    _ = cluster.readAttributeActiveCurrentPhaseB(with: MTRReadParams())
    _ = cluster.readAttributeActiveCurrentPhaseC(with: MTRReadParams())
    _ = cluster.readAttributeActivePowerMaxPhaseB(with: MTRReadParams())
    _ = cluster.readAttributeActivePowerMaxPhaseC(with: MTRReadParams())
    _ = cluster.readAttributeActivePowerMax(with: MTRReadParams())
    _ = cluster.readAttributeActivePowerMinPhaseB(with: MTRReadParams())
    _ = cluster.readAttributeActivePowerMinPhaseC(with: MTRReadParams())
    _ = cluster.readAttributeActivePowerMin(with: MTRReadParams())
    _ = cluster.readAttributeActivePowerPhaseB(with: MTRReadParams())
    _ = cluster.readAttributeActivePowerPhaseC(with: MTRReadParams())
    _ = cluster.readAttributeActivePower(with: MTRReadParams())
    _ = cluster.readAttributeApparentPowerPhaseB(with: MTRReadParams())
    _ = cluster.readAttributeApparentPowerPhaseC(with: MTRReadParams())
    _ = cluster.readAttributeApparentPower(with: MTRReadParams())
    _ = cluster.readAttributeAttributeList(with: MTRReadParams())
    _ = cluster.readAttributeAverageRmsOverVoltageCounterPhaseB(with: MTRReadParams())
    _ = cluster.readAttributeAverageRmsOverVoltageCounterPhaseC(with: MTRReadParams())
    _ = cluster.readAttributeAverageRmsOverVoltage(with: MTRReadParams())
    _ = cluster.readAttributeAverageRmsUnderVoltageCounterPhaseB(with: MTRReadParams())
    _ = cluster.readAttributeAverageRmsUnderVoltageCounterPhaseC(with: MTRReadParams())
    _ = cluster.readAttributeAverageRmsUnderVoltageCounter(with: MTRReadParams())
    _ = cluster.readAttributeAverageRmsUnderVoltage(with: MTRReadParams())
    _ = cluster.readAttributeAverageRmsVoltageMeasurementPeriodPhaseB(with: MTRReadParams())
    _ = cluster.readAttributeAverageRmsVoltageMeasurementPeriodPhaseC(with: MTRReadParams())
    _ = cluster.readAttributeAverageRmsVoltageMeasurementPeriod(with: MTRReadParams())
    _ = cluster.readAttributeClusterRevision(with: MTRReadParams())
    _ = cluster.readAttributeCurrentOverload(with: MTRReadParams())
    _ = cluster.readAttributeDcCurrentDivisor(with: MTRReadParams())
    _ = cluster.readAttributeDcCurrentMax(with: MTRReadParams())
    _ = cluster.readAttributeDcCurrentMin(with: MTRReadParams())
    _ = cluster.readAttributeDcCurrentMultiplier(with: MTRReadParams())
    _ = cluster.readAttributeDcCurrent(with: MTRReadParams())
    _ = cluster.readAttributeDcPowerDivisor(with: MTRReadParams())
    _ = cluster.readAttributeDcPowerMax(with: MTRReadParams())
    _ = cluster.readAttributeDcPowerMin(with: MTRReadParams())
    _ = cluster.readAttributeDcPowerMultiplier(with: MTRReadParams())
    _ = cluster.readAttributeDcPower(with: MTRReadParams())
    _ = cluster.readAttributeDcVoltageDivisor(with: MTRReadParams())
    _ = cluster.readAttributeDcVoltageMax(with: MTRReadParams())
    _ = cluster.readAttributeDcVoltageMin(with: MTRReadParams())
    _ = cluster.readAttributeDcVoltageMultiplier(with: MTRReadParams())
    _ = cluster.readAttributeDcVoltage(with: MTRReadParams())
    _ = cluster.readAttributeFeatureMap(with: MTRReadParams())
    _ = cluster.readAttributeGeneratedCommandList(with: MTRReadParams())
    _ = cluster.readAttributeHarmonicCurrentMultiplier(with: MTRReadParams())
    _ = cluster.readAttributeInstantaneousActiveCurrent(with: MTRReadParams())
    _ = cluster.readAttributeInstantaneousLineCurrent(with: MTRReadParams())
    _ = cluster.readAttributeInstantaneousPower(with: MTRReadParams())
    _ = cluster.readAttributeInstantaneousReactiveCurrent(with: MTRReadParams())
    _ = cluster.readAttributeInstantaneousVoltage(with: MTRReadParams())
    _ = cluster.readAttributeLineCurrentPhaseB(with: MTRReadParams())
    _ = cluster.readAttributeLineCurrentPhaseC(with: MTRReadParams())
    _ = cluster.readAttributeMeasured11thHarmonicCurrent(with: MTRReadParams())
    _ = cluster.readAttributeMeasured1stHarmonicCurrent(with: MTRReadParams())
    _ = cluster.readAttributeMeasured3rdHarmonicCurrent(with: MTRReadParams())
    _ = cluster.readAttributeMeasured5thHarmonicCurrent(with: MTRReadParams())
    _ = cluster.readAttributeMeasured7thHarmonicCurrent(with: MTRReadParams())
    _ = cluster.readAttributeMeasured9thHarmonicCurrent(with: MTRReadParams())
    _ = cluster.readAttributeMeasuredPhase11thHarmonicCurrent(with: MTRReadParams())
    _ = cluster.readAttributeMeasuredPhase1stHarmonicCurrent(with: MTRReadParams())
    _ = cluster.readAttributeMeasuredPhase3rdHarmonicCurrent(with: MTRReadParams())
    _ = cluster.readAttributeMeasuredPhase5thHarmonicCurrent(with: MTRReadParams())
    _ = cluster.readAttributeMeasuredPhase7thHarmonicCurrent(with: MTRReadParams())
    _ = cluster.readAttributeMeasuredPhase9thHarmonicCurrent(with: MTRReadParams())
    _ = cluster.readAttributeMeasurementType(with: MTRReadParams())
    _ = cluster.readAttributeNeutralCurrent(with: MTRReadParams())
    _ = cluster.readAttributeOverloadAlarmsMask(with: MTRReadParams())
    _ = cluster.readAttributePhaseHarmonicCurrentMultiplier(with: MTRReadParams())
    _ = cluster.readAttributePowerDivisor(with: MTRReadParams())
    _ = cluster.readAttributePowerFactorPhaseB(with: MTRReadParams())
    _ = cluster.readAttributePowerFactorPhaseC(with: MTRReadParams())
    _ = cluster.readAttributePowerFactor(with: MTRReadParams())
    _ = cluster.readAttributePowerMultiplier(with: MTRReadParams())
    _ = cluster.readAttributeReactiveCurrentPhaseB(with: MTRReadParams())
    _ = cluster.readAttributeReactiveCurrentPhaseC(with: MTRReadParams())
    _ = cluster.readAttributeReactivePowerPhaseB(with: MTRReadParams())
    _ = cluster.readAttributeReactivePowerPhaseC(with: MTRReadParams())
    _ = cluster.readAttributeReactivePower(with: MTRReadParams())
    _ = cluster.readAttributeRmsCurrentMaxPhaseB(with: MTRReadParams())
    _ = cluster.readAttributeRmsCurrentMaxPhaseC(with: MTRReadParams())
    _ = cluster.readAttributeRmsCurrentMax(with: MTRReadParams())
    _ = cluster.readAttributeRmsCurrentMinPhaseB(with: MTRReadParams())
    _ = cluster.readAttributeRmsCurrentMinPhaseC(with: MTRReadParams())
    _ = cluster.readAttributeRmsCurrentMin(with: MTRReadParams())
    _ = cluster.readAttributeRmsCurrentPhaseB(with: MTRReadParams())
    _ = cluster.readAttributeRmsCurrentPhaseC(with: MTRReadParams())
    _ = cluster.readAttributeRmsCurrent(with: MTRReadParams())
    _ = cluster.readAttributeRmsExtremeOverVoltagePeriodPhaseB(with: MTRReadParams())
    _ = cluster.readAttributeRmsExtremeOverVoltagePeriodPhaseC(with: MTRReadParams())
    _ = cluster.readAttributeRmsExtremeOverVoltagePeriod(with: MTRReadParams())
    _ = cluster.readAttributeRmsExtremeOverVoltage(with: MTRReadParams())
    _ = cluster.readAttributeRmsExtremeUnderVoltagePeriodPhaseB(with: MTRReadParams())
    _ = cluster.readAttributeRmsExtremeUnderVoltagePeriodPhaseC(with: MTRReadParams())
    _ = cluster.readAttributeRmsExtremeUnderVoltagePeriod(with: MTRReadParams())
    _ = cluster.readAttributeRmsExtremeUnderVoltage(with: MTRReadParams())
    _ = cluster.readAttributeRmsVoltageMaxPhaseB(with: MTRReadParams())
    _ = cluster.readAttributeRmsVoltageMaxPhaseC(with: MTRReadParams())
    _ = cluster.readAttributeRmsVoltageMax(with: MTRReadParams())
    _ = cluster.readAttributeRmsVoltageMinPhaseB(with: MTRReadParams())
    _ = cluster.readAttributeRmsVoltageMinPhaseC(with: MTRReadParams())
    _ = cluster.readAttributeRmsVoltageMin(with: MTRReadParams())
    _ = cluster.readAttributeRmsVoltagePhaseB(with: MTRReadParams())
    _ = cluster.readAttributeRmsVoltagePhaseC(with: MTRReadParams())
    _ = cluster.readAttributeRmsVoltageSagPeriodPhaseB(with: MTRReadParams())
    _ = cluster.readAttributeRmsVoltageSagPeriodPhaseC(with: MTRReadParams())
    _ = cluster.readAttributeRmsVoltageSagPeriod(with: MTRReadParams())
    _ = cluster.readAttributeRmsVoltageSag(with: MTRReadParams())
    _ = cluster.readAttributeRmsVoltageSwellPeriodPhaseB(with: MTRReadParams())
    _ = cluster.readAttributeRmsVoltageSwellPeriodPhaseC(with: MTRReadParams())
    _ = cluster.readAttributeRmsVoltageSwellPeriod(with: MTRReadParams())
    _ = cluster.readAttributeRmsVoltageSwell(with: MTRReadParams())
    _ = cluster.readAttributeRmsVoltage(with: MTRReadParams())
    _ = cluster.readAttributeTotalActivePower(with: MTRReadParams())
    _ = cluster.readAttributeTotalApparentPower(with: MTRReadParams())
    _ = cluster.readAttributeTotalReactivePower(with: MTRReadParams())
    _ = cluster.readAttributeVoltageOverload(with: MTRReadParams())
    cluster.writeAttributeAcOverloadAlarmsMask(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeAcOverloadAlarmsMask(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeAverageRmsUnderVoltageCounter(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeAverageRmsUnderVoltageCounter(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeAverageRmsVoltageMeasurementPeriod(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeAverageRmsVoltageMeasurementPeriod(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeOverloadAlarmsMask(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeOverloadAlarmsMask(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeRmsExtremeOverVoltagePeriod(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeRmsExtremeOverVoltagePeriod(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeRmsExtremeUnderVoltagePeriod(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeRmsExtremeUnderVoltagePeriod(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeRmsVoltageSagPeriod(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeRmsVoltageSagPeriod(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeRmsVoltageSwellPeriod(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeRmsVoltageSwellPeriod(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
}
