import Foundation
import Dispatch
import Matter

func testClusterColorControlCommandFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRClusterColorControl(device: device, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRClusterColorControl init")
        return
    }
    cluster.colorLoopSet(with: MTRColorControlClusterColorLoopSetParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.colorLoopSet(with: MTRColorControlClusterColorLoopSetParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.enhancedMoveHue(with: MTRColorControlClusterEnhancedMoveHueParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.enhancedMoveHue(with: MTRColorControlClusterEnhancedMoveHueParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.enhancedMoveToHueAndSaturation(with: MTRColorControlClusterEnhancedMoveToHueAndSaturationParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.enhancedMoveToHueAndSaturation(with: MTRColorControlClusterEnhancedMoveToHueAndSaturationParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.enhancedMoveToHue(with: MTRColorControlClusterEnhancedMoveToHueParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.enhancedMoveToHue(with: MTRColorControlClusterEnhancedMoveToHueParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.enhancedStepHue(with: MTRColorControlClusterEnhancedStepHueParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.enhancedStepHue(with: MTRColorControlClusterEnhancedStepHueParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.moveColorTemperature(with: MTRColorControlClusterMoveColorTemperatureParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.moveColorTemperature(with: MTRColorControlClusterMoveColorTemperatureParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.moveColor(with: MTRColorControlClusterMoveColorParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.moveColor(with: MTRColorControlClusterMoveColorParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.moveHue(with: MTRColorControlClusterMoveHueParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.moveHue(with: MTRColorControlClusterMoveHueParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.moveSaturation(with: MTRColorControlClusterMoveSaturationParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.moveSaturation(with: MTRColorControlClusterMoveSaturationParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.moveToColorTemperature(with: MTRColorControlClusterMoveToColorTemperatureParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.moveToColorTemperature(with: MTRColorControlClusterMoveToColorTemperatureParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.moveToColor(with: MTRColorControlClusterMoveToColorParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.moveToColor(with: MTRColorControlClusterMoveToColorParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.moveToHueAndSaturation(with: MTRColorControlClusterMoveToHueAndSaturationParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.moveToHueAndSaturation(with: MTRColorControlClusterMoveToHueAndSaturationParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.moveToHue(with: MTRColorControlClusterMoveToHueParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.moveToHue(with: MTRColorControlClusterMoveToHueParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.moveToSaturation(with: MTRColorControlClusterMoveToSaturationParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.moveToSaturation(with: MTRColorControlClusterMoveToSaturationParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.stepColorTemperature(with: MTRColorControlClusterStepColorTemperatureParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.stepColorTemperature(with: MTRColorControlClusterStepColorTemperatureParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.stepColor(with: MTRColorControlClusterStepColorParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.stepColor(with: MTRColorControlClusterStepColorParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.stepHue(with: MTRColorControlClusterStepHueParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.stepHue(with: MTRColorControlClusterStepHueParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.stepSaturation(with: MTRColorControlClusterStepSaturationParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.stepSaturation(with: MTRColorControlClusterStepSaturationParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.stopMoveStep(with: MTRColorControlClusterStopMoveStepParams(), expectedValues: [], expectedValueInterval: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.stopMoveStep(with: MTRColorControlClusterStopMoveStepParams(), expectedValues: [], expectedValueInterval: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
}

func testClusterColorControlInit() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    _ = MTRClusterColorControl(device: device, endpoint: 1, queue: DispatchQueue.global())
    _ = MTRClusterColorControl(device: device, endpointID: n(1), queue: DispatchQueue.global())
}

func testClusterColorControlDeviceCache() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRClusterColorControl(device: device, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRClusterColorControl init")
        return
    }
    _ = cluster.readAttributeAcceptedCommandList(with: MTRReadParams())
    _ = cluster.readAttributeAttributeList(with: MTRReadParams())
    _ = cluster.readAttributeClusterRevision(with: MTRReadParams())
    _ = cluster.readAttributeColorCapabilities(with: MTRReadParams())
    _ = cluster.readAttributeColorLoopActive(with: MTRReadParams())
    _ = cluster.readAttributeColorLoopDirection(with: MTRReadParams())
    _ = cluster.readAttributeColorLoopStartEnhancedHue(with: MTRReadParams())
    _ = cluster.readAttributeColorLoopStoredEnhancedHue(with: MTRReadParams())
    _ = cluster.readAttributeColorLoopTime(with: MTRReadParams())
    _ = cluster.readAttributeColorMode(with: MTRReadParams())
    _ = cluster.readAttributeColorPointBIntensity(with: MTRReadParams())
    _ = cluster.readAttributeColorPointBX(with: MTRReadParams())
    _ = cluster.readAttributeColorPointBY(with: MTRReadParams())
    _ = cluster.readAttributeColorPointGIntensity(with: MTRReadParams())
    _ = cluster.readAttributeColorPointGX(with: MTRReadParams())
    _ = cluster.readAttributeColorPointGY(with: MTRReadParams())
    _ = cluster.readAttributeColorPointRIntensity(with: MTRReadParams())
    _ = cluster.readAttributeColorPointRX(with: MTRReadParams())
    _ = cluster.readAttributeColorPointRY(with: MTRReadParams())
    _ = cluster.readAttributeColorTempPhysicalMaxMireds(with: MTRReadParams())
    _ = cluster.readAttributeColorTempPhysicalMinMireds(with: MTRReadParams())
    _ = cluster.readAttributeColorTemperatureMireds(with: MTRReadParams())
    _ = cluster.readAttributeCompensationText(with: MTRReadParams())
    _ = cluster.readAttributeCoupleColorTempToLevelMinMireds(with: MTRReadParams())
    _ = cluster.readAttributeCurrentHue(with: MTRReadParams())
    _ = cluster.readAttributeCurrentSaturation(with: MTRReadParams())
    _ = cluster.readAttributeCurrentX(with: MTRReadParams())
    _ = cluster.readAttributeCurrentY(with: MTRReadParams())
    _ = cluster.readAttributeDriftCompensation(with: MTRReadParams())
    _ = cluster.readAttributeEnhancedColorMode(with: MTRReadParams())
    _ = cluster.readAttributeEnhancedCurrentHue(with: MTRReadParams())
    _ = cluster.readAttributeFeatureMap(with: MTRReadParams())
    _ = cluster.readAttributeGeneratedCommandList(with: MTRReadParams())
    _ = cluster.readAttributeNumberOfPrimaries(with: MTRReadParams())
    _ = cluster.readAttributeOptions(with: MTRReadParams())
    _ = cluster.readAttributePrimary1Intensity(with: MTRReadParams())
    _ = cluster.readAttributePrimary1X(with: MTRReadParams())
    _ = cluster.readAttributePrimary1Y(with: MTRReadParams())
    _ = cluster.readAttributePrimary2Intensity(with: MTRReadParams())
    _ = cluster.readAttributePrimary2X(with: MTRReadParams())
    _ = cluster.readAttributePrimary2Y(with: MTRReadParams())
    _ = cluster.readAttributePrimary3Intensity(with: MTRReadParams())
    _ = cluster.readAttributePrimary3X(with: MTRReadParams())
    _ = cluster.readAttributePrimary3Y(with: MTRReadParams())
    _ = cluster.readAttributePrimary4Intensity(with: MTRReadParams())
    _ = cluster.readAttributePrimary4X(with: MTRReadParams())
    _ = cluster.readAttributePrimary4Y(with: MTRReadParams())
    _ = cluster.readAttributePrimary5Intensity(with: MTRReadParams())
    _ = cluster.readAttributePrimary5X(with: MTRReadParams())
    _ = cluster.readAttributePrimary5Y(with: MTRReadParams())
    _ = cluster.readAttributePrimary6Intensity(with: MTRReadParams())
    _ = cluster.readAttributePrimary6X(with: MTRReadParams())
    _ = cluster.readAttributePrimary6Y(with: MTRReadParams())
    _ = cluster.readAttributeRemainingTime(with: MTRReadParams())
    _ = cluster.readAttributeStartUpColorTemperatureMireds(with: MTRReadParams())
    _ = cluster.readAttributeWhitePointX(with: MTRReadParams())
    _ = cluster.readAttributeWhitePointY(with: MTRReadParams())
    cluster.writeAttributeColorPointBIntensity(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeColorPointBIntensity(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeColorPointBX(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeColorPointBX(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeColorPointBY(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeColorPointBY(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeColorPointGIntensity(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeColorPointGIntensity(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeColorPointGX(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeColorPointGX(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeColorPointGY(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeColorPointGY(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeColorPointRIntensity(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeColorPointRIntensity(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeColorPointRX(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeColorPointRX(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeColorPointRY(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeColorPointRY(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeOptions(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeOptions(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeStartUpColorTemperatureMireds(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeStartUpColorTemperatureMireds(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeWhitePointX(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeWhitePointX(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    cluster.writeAttributeWhitePointY(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1))
    cluster.writeAttributeWhitePointY(withValue: MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(1)), expectedValueInterval: n(1), params: MTRWriteParams())
    let probe = MTRMakeDataValue(type: MTRUnsignedIntegerValueType, value: n(7))
    cluster.writeAttributeColorPointBIntensity(withValue: probe, expectedValueInterval: n(1))
    let cached = cluster.readAttributeColorPointBIntensity(with: nil)
    mtrRequire(cached != nil, "expected-value cache round-trip")
}
