import Foundation
import Dispatch
import Matter

func testBaseDoorLockClassCacheFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    MTRBaseClusterDoorLock.readAttributeAcceptedCommandList(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeAcceptedCommandList(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeActuatorEnabled(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeActuatorEnabled(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeAliroBLEAdvertisingVersion(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeAliroExpeditedTransactionSupportedProtocolVersions(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeAliroGroupResolvingKey(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeAliroReaderGroupIdentifier(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeAliroReaderGroupSubIdentifier(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeAliroReaderVerificationKey(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeAliroSupportedBLEUWBProtocolVersions(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeAttributeList(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeAttributeList(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeAutoRelockTime(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeAutoRelockTime(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeClusterRevision(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeClusterRevision(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeCredentialRulesSupport(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeCredentialRulesSupport(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeDefaultConfigurationRegister(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeDefaultConfigurationRegister(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeDoorClosedEvents(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeDoorClosedEvents(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeDoorOpenEvents(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeDoorOpenEvents(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeDoorState(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeDoorState(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeEnableInsideStatusLED(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeEnableInsideStatusLED(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeEnableLocalProgramming(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeEnableLocalProgramming(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeEnableOneTouchLocking(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeEnableOneTouchLocking(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeEnablePrivacyModeButton(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeEnablePrivacyModeButton(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeExpiringUserTimeout(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeExpiringUserTimeout(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeFeatureMap(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeFeatureMap(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeGeneratedCommandList(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeGeneratedCommandList(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeLEDSettings(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeLEDSettings(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeLanguage(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeLanguage(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeLocalProgrammingFeatures(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeLocalProgrammingFeatures(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeLockState(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeLockState(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeLockType(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeLockType(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeMaxPINCodeLength(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeMaxPINCodeLength(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeMaxRFIDCodeLength(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeMaxRFIDCodeLength(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeMinPINCodeLength(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeMinPINCodeLength(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeMinRFIDCodeLength(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeMinRFIDCodeLength(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeNumberOfAliroCredentialIssuerKeysSupported(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeNumberOfAliroEndpointKeysSupported(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeNumberOfCredentialsSupportedPerUser(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeNumberOfCredentialsSupportedPerUser(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeNumberOfHolidaySchedulesSupported(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeNumberOfHolidaySchedulesSupported(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeNumberOfPINUsersSupported(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeNumberOfPINUsersSupported(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeNumberOfRFIDUsersSupported(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeNumberOfRFIDUsersSupported(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeNumberOfTotalUsersSupported(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeNumberOfTotalUsersSupported(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeNumberOfWeekDaySchedulesSupportedPerUser(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeNumberOfWeekDaySchedulesSupportedPerUser(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeNumberOfYearDaySchedulesSupportedPerUser(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeNumberOfYearDaySchedulesSupportedPerUser(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeOpenPeriod(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeOpenPeriod(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeOperatingMode(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeOperatingMode(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeRequirePINforRemoteOperation(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeRequirePINforRemoteOperation(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeSendPINOverTheAir(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeSendPINOverTheAir(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeSoundVolume(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeSoundVolume(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeSupportedOperatingModes(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeSupportedOperatingModes(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeUserCodeTemporaryDisableTime(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeUserCodeTemporaryDisableTime(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterDoorLock.readAttributeWrongCodeEntryLimit(withAttributeCache: MTRAttributeCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completionHandler: { _, err in mtrExpectInvalidState(err) })
}

func testBaseDoorLockClassCacheFailClosedGroup2() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    MTRBaseClusterDoorLock.readAttributeWrongCodeEntryLimit(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
}

func testBaseDoorLockCommandFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRBaseClusterDoorLock(device: baseDevice, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRBaseClusterDoorLock init")
        return
    }
    cluster.clearAliroReaderConfig(with: MTRDoorLockClusterClearAliroReaderConfigParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.clearCredential(with: MTRDoorLockClusterClearCredentialParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.clearCredential(with: MTRDoorLockClusterClearCredentialParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.clearHolidaySchedule(with: MTRDoorLockClusterClearHolidayScheduleParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.clearHolidaySchedule(with: MTRDoorLockClusterClearHolidayScheduleParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.clearUser(with: MTRDoorLockClusterClearUserParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.clearUser(with: MTRDoorLockClusterClearUserParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.clearWeekDaySchedule(with: MTRDoorLockClusterClearWeekDayScheduleParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.clearWeekDaySchedule(with: MTRDoorLockClusterClearWeekDayScheduleParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.clearYearDaySchedule(with: MTRDoorLockClusterClearYearDayScheduleParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.clearYearDaySchedule(with: MTRDoorLockClusterClearYearDayScheduleParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.credentialStatus(with: MTRDoorLockClusterGetCredentialStatusParams(), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.credentialStatus(with: MTRDoorLockClusterGetCredentialStatusParams(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.lockDoor(with: MTRDoorLockClusterLockDoorParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.lockDoor(with: MTRDoorLockClusterLockDoorParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.setAliroReaderConfigWith(MTRDoorLockClusterSetAliroReaderConfigParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.setCredentialWith(MTRDoorLockClusterSetCredentialParams(), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.setCredentialWith(MTRDoorLockClusterSetCredentialParams(), completionHandler: { _, err in mtrExpectInvalidState(err) })
    cluster.setHolidayScheduleWith(MTRDoorLockClusterSetHolidayScheduleParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.setHolidayScheduleWith(MTRDoorLockClusterSetHolidayScheduleParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.setUserWith(MTRDoorLockClusterSetUserParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.setUserWith(MTRDoorLockClusterSetUserParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.setWeekDayScheduleWith(MTRDoorLockClusterSetWeekDayScheduleParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.setWeekDayScheduleWith(MTRDoorLockClusterSetWeekDayScheduleParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.setYearDayScheduleWith(MTRDoorLockClusterSetYearDayScheduleParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.setYearDayScheduleWith(MTRDoorLockClusterSetYearDayScheduleParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.unboltDoor(with: MTRDoorLockClusterUnboltDoorParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.unlockDoor(with: MTRDoorLockClusterUnlockDoorParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.unlockDoor(with: MTRDoorLockClusterUnlockDoorParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.unlockWithTimeout(with: MTRDoorLockClusterUnlockWithTimeoutParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.unlockWithTimeout(with: MTRDoorLockClusterUnlockWithTimeoutParams(), completionHandler: { err in mtrExpectInvalidState(err) })
}

func testBaseDoorLockWriteFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRBaseClusterDoorLock(device: baseDevice, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRBaseClusterDoorLock init")
        return
    }
    cluster.writeAttributeAutoRelockTime(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeAutoRelockTime(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeAutoRelockTime(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeAutoRelockTime(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeDoorClosedEvents(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeDoorClosedEvents(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeDoorClosedEvents(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeDoorClosedEvents(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeDoorOpenEvents(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeDoorOpenEvents(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeDoorOpenEvents(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeDoorOpenEvents(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEnableInsideStatusLED(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEnableInsideStatusLED(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEnableInsideStatusLED(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEnableInsideStatusLED(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEnableLocalProgramming(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEnableLocalProgramming(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEnableLocalProgramming(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEnableLocalProgramming(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEnableOneTouchLocking(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEnableOneTouchLocking(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEnableOneTouchLocking(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEnableOneTouchLocking(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEnablePrivacyModeButton(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEnablePrivacyModeButton(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEnablePrivacyModeButton(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEnablePrivacyModeButton(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeExpiringUserTimeout(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeExpiringUserTimeout(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeExpiringUserTimeout(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeExpiringUserTimeout(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeLEDSettings(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeLEDSettings(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeLEDSettings(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeLEDSettings(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeLanguage(withValue: "x", completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeLanguage(withValue: "x", completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeLanguage(withValue: "x", params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeLanguage(withValue: "x", params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeLocalProgrammingFeatures(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeLocalProgrammingFeatures(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeLocalProgrammingFeatures(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeLocalProgrammingFeatures(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOpenPeriod(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOpenPeriod(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOpenPeriod(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOpenPeriod(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOperatingMode(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOperatingMode(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOperatingMode(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOperatingMode(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeRequirePINforRemoteOperation(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeRequirePINforRemoteOperation(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeRequirePINforRemoteOperation(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeRequirePINforRemoteOperation(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeSendPINOverTheAir(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeSendPINOverTheAir(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeSendPINOverTheAir(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeSendPINOverTheAir(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeSoundVolume(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeSoundVolume(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeSoundVolume(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeSoundVolume(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeUserCodeTemporaryDisableTime(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeUserCodeTemporaryDisableTime(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeUserCodeTemporaryDisableTime(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeUserCodeTemporaryDisableTime(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeWrongCodeEntryLimit(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeWrongCodeEntryLimit(withValue: n(1), completionHandler: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeWrongCodeEntryLimit(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeWrongCodeEntryLimit(withValue: n(1), params: MTRWriteParams(), completionHandler: { err in mtrExpectInvalidState(err) })
}
