import Foundation
import Dispatch
import Matter

func testWindowCoveringFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRBaseClusterWindowCovering(device: baseDevice, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRBaseClusterWindowCovering init")
        return
    }
    cluster.downOrClose(completion: { _ in })
    cluster.downOrClose(completionHandler: { _ in })
    cluster.readAttributeAcceptedCommandList(completion: { _, _ in })
    cluster.readAttributeAcceptedCommandList(completionHandler: { _, _ in })
    cluster.readAttributeAttributeList(completion: { _, _ in })
    cluster.readAttributeAttributeList(completionHandler: { _, _ in })
    cluster.readAttributeClusterRevision(completion: { _, _ in })
    cluster.readAttributeClusterRevision(completionHandler: { _, _ in })
    cluster.readAttributeConfigStatus(completion: { _, _ in })
    cluster.readAttributeConfigStatus(completionHandler: { _, _ in })
    cluster.readAttributeCurrentPositionLiftPercent100ths(completion: { _, _ in })
    cluster.readAttributeCurrentPositionLiftPercent100ths(completionHandler: { _, _ in })
    cluster.readAttributeCurrentPositionLiftPercentage(completion: { _, _ in })
    cluster.readAttributeCurrentPositionLiftPercentage(completionHandler: { _, _ in })
    cluster.readAttributeCurrentPositionLift(completion: { _, _ in })
    cluster.readAttributeCurrentPositionLift(completionHandler: { _, _ in })
    cluster.readAttributeCurrentPositionTiltPercent100ths(completion: { _, _ in })
    cluster.readAttributeCurrentPositionTiltPercent100ths(completionHandler: { _, _ in })
    cluster.readAttributeCurrentPositionTiltPercentage(completion: { _, _ in })
    cluster.readAttributeCurrentPositionTiltPercentage(completionHandler: { _, _ in })
    cluster.readAttributeCurrentPositionTilt(completion: { _, _ in })
    cluster.readAttributeCurrentPositionTilt(completionHandler: { _, _ in })
    cluster.readAttributeEndProductType(completion: { _, _ in })
    cluster.readAttributeEndProductType(completionHandler: { _, _ in })
    cluster.readAttributeFeatureMap(completion: { _, _ in })
    cluster.readAttributeFeatureMap(completionHandler: { _, _ in })
    cluster.readAttributeGeneratedCommandList(completion: { _, _ in })
    cluster.readAttributeGeneratedCommandList(completionHandler: { _, _ in })
    cluster.readAttributeInstalledClosedLimitLift(completion: { _, _ in })
    cluster.readAttributeInstalledClosedLimitLift(completionHandler: { _, _ in })
    cluster.readAttributeInstalledClosedLimitTilt(completion: { _, _ in })
    cluster.readAttributeInstalledClosedLimitTilt(completionHandler: { _, _ in })
    cluster.readAttributeInstalledOpenLimitLift(completion: { _, _ in })
    cluster.readAttributeInstalledOpenLimitLift(completionHandler: { _, _ in })
    cluster.readAttributeInstalledOpenLimitTilt(completion: { _, _ in })
    cluster.readAttributeInstalledOpenLimitTilt(completionHandler: { _, _ in })
    cluster.readAttributeMode(completion: { _, _ in })
    cluster.readAttributeMode(completionHandler: { _, _ in })
    cluster.readAttributeNumberOfActuationsLift(completion: { _, _ in })
    cluster.readAttributeNumberOfActuationsLift(completionHandler: { _, _ in })
    cluster.readAttributeNumberOfActuationsTilt(completion: { _, _ in })
    cluster.readAttributeNumberOfActuationsTilt(completionHandler: { _, _ in })
    cluster.readAttributeOperationalStatus(completion: { _, _ in })
    cluster.readAttributeOperationalStatus(completionHandler: { _, _ in })
    cluster.readAttributePhysicalClosedLimitLift(completion: { _, _ in })
    cluster.readAttributePhysicalClosedLimitLift(completionHandler: { _, _ in })
    cluster.readAttributePhysicalClosedLimitTilt(completion: { _, _ in })
    cluster.readAttributePhysicalClosedLimitTilt(completionHandler: { _, _ in })
    cluster.readAttributeSafetyStatus(completion: { _, _ in })
    cluster.readAttributeSafetyStatus(completionHandler: { _, _ in })
    cluster.readAttributeTargetPositionLiftPercent100ths(completion: { _, _ in })
    cluster.readAttributeTargetPositionLiftPercent100ths(completionHandler: { _, _ in })
    cluster.readAttributeTargetPositionTiltPercent100ths(completion: { _, _ in })
    cluster.readAttributeTargetPositionTiltPercent100ths(completionHandler: { _, _ in })
    cluster.readAttributeType(completion: { _, _ in })
    cluster.readAttributeType(completionHandler: { _, _ in })
    cluster.stopMotion(completion: { _ in })
    cluster.stopMotion(completionHandler: { _ in })
    cluster.subscribeAttributeAcceptedCommandList(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAcceptedCommandList(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAttributeList(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeAttributeList(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeClusterRevision(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeClusterRevision(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeConfigStatus(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeConfigStatus(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentPositionLiftPercent100ths(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentPositionLiftPercent100ths(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentPositionLiftPercentage(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentPositionLiftPercentage(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentPositionLift(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentPositionLift(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentPositionTiltPercent100ths(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentPositionTiltPercent100ths(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentPositionTiltPercentage(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentPositionTiltPercentage(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentPositionTilt(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeCurrentPositionTilt(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeEndProductType(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeEndProductType(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeFeatureMap(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeFeatureMap(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeGeneratedCommandList(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeGeneratedCommandList(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeInstalledClosedLimitLift(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeInstalledClosedLimitLift(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeInstalledClosedLimitTilt(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeInstalledClosedLimitTilt(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeInstalledOpenLimitLift(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeInstalledOpenLimitLift(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeInstalledOpenLimitTilt(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeInstalledOpenLimitTilt(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMode(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeMode(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfActuationsLift(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfActuationsLift(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfActuationsTilt(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeNumberOfActuationsTilt(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOperationalStatus(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeOperationalStatus(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePhysicalClosedLimitLift(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePhysicalClosedLimitLift(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePhysicalClosedLimitTilt(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributePhysicalClosedLimitTilt(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeSafetyStatus(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeSafetyStatus(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeTargetPositionLiftPercent100ths(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeTargetPositionLiftPercent100ths(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeTargetPositionTiltPercent100ths(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeTargetPositionTiltPercent100ths(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeType(withMinInterval: n(1), maxInterval: n(1), params: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.subscribeAttributeType(with: MTRSubscribeParams.new(), subscriptionEstablished: nil as MTRSubscriptionEstablishedHandler?, reportHandler: { _, _ in })
    cluster.upOrOpen(completion: { _ in })
    cluster.upOrOpen(completionHandler: { _ in })
}
