import Foundation
import Dispatch
import Matter

func testBaseUnitTestingClassCacheFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    MTRBaseClusterUnitTesting.readAttributeAcceptedCommandList(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeAttributeList(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeBitmap16(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeBitmap32(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeBitmap64(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeBitmap8(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeBoolean(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeCharString(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeClusterErrorBoolean(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeClusterRevision(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeEnum16(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeEnum8(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeEnumAttr(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeEpochS(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeEpochUs(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeFeatureMap(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeFloatDouble(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeFloatSingle(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeGeneralErrorBoolean(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeGeneratedCommandList(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeInt16s(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeInt16u(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeInt24s(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeInt24u(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeInt32s(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeInt32u(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeInt40s(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeInt40u(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeInt48s(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeInt48u(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeInt56s(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeInt56u(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeInt64s(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeInt64u(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeInt8s(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeInt8u(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeListFabricScoped(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeListInt8u(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeListLongOctetString(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeListNullablesAndOptionalsStruct(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeListOctetString(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeListStructOctetString(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeLongCharString(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeLongOctetString(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableBitmap16(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableBitmap32(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableBitmap64(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableBitmap8(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableBoolean(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableCharString(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableEnum16(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableEnum8(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableEnumAttr(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableFloatDouble(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableFloatSingle(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableInt16s(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableInt16u(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableInt24s(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableInt24u(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableInt32s(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableInt32u(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableInt40s(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableInt40u(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableInt48s(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableInt48u(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableInt56s(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableInt56u(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableInt64s(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableInt64u(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableInt8s(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableInt8u(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableOctetString(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableRangeRestrictedInt16s(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableRangeRestrictedInt16u(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableRangeRestrictedInt8s(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableRangeRestrictedInt8u(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeNullableStruct(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeOctetString(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeRangeRestrictedInt16s(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeRangeRestrictedInt16u(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeRangeRestrictedInt8s(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeRangeRestrictedInt8u(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeStructAttr(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeTimedWriteBoolean(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeUnsupported(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeVendorId(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
    MTRBaseClusterUnitTesting.readAttributeWriteOnlyInt8u(withClusterStateCache: MTRClusterStateCacheContainer(), endpoint: n(1), queue: DispatchQueue.global(), completion: { _, err in mtrExpectInvalidState(err) })
}

func testBaseUnitTestingReadFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRBaseClusterUnitTesting(device: baseDevice, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRBaseClusterUnitTesting init")
        return
    }
    cluster.readAttributeListFabricScoped(with: MTRReadParams(), completion: { _, err in mtrExpectInvalidState(err) })
}

func testBaseUnitTestingCommandFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRBaseClusterUnitTesting(device: baseDevice, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRBaseClusterUnitTesting init")
        return
    }
    cluster.simpleStructEchoRequest(with: MTRUnitTestingClusterSimpleStructEchoRequestParams(), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.testAddArguments(with: MTRUnitTestingClusterTestAddArgumentsParams(), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.testComplexNullableOptionalRequest(with: MTRUnitTestingClusterTestComplexNullableOptionalRequestParams(), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.testEmitTestEventRequest(with: MTRUnitTestingClusterTestEmitTestEventRequestParams(), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.testEmitTestFabricScopedEventRequest(with: MTRUnitTestingClusterTestEmitTestFabricScopedEventRequestParams(), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.testEnumsRequest(with: MTRUnitTestingClusterTestEnumsRequestParams(), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.testListInt8UArgumentRequest(with: MTRUnitTestingClusterTestListInt8UArgumentRequestParams(), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.testListInt8UReverseRequest(with: MTRUnitTestingClusterTestListInt8UReverseRequestParams(), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.testListNestedStructListArgumentRequest(with: MTRUnitTestingClusterTestListNestedStructListArgumentRequestParams(), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.testListStructArgumentRequest(with: MTRUnitTestingClusterTestListStructArgumentRequestParams(), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.testNestedStructArgumentRequest(with: MTRUnitTestingClusterTestNestedStructArgumentRequestParams(), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.testNestedStructListArgumentRequest(with: MTRUnitTestingClusterTestNestedStructListArgumentRequestParams(), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.testNotHandled(with: MTRUnitTestingClusterTestNotHandledParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.testNullableOptionalRequest(with: MTRUnitTestingClusterTestNullableOptionalRequestParams(), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.testSimpleArgumentRequest(with: MTRUnitTestingClusterTestSimpleArgumentRequestParams(), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.testSimpleOptionalArgumentRequest(with: MTRUnitTestingClusterTestSimpleOptionalArgumentRequestParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.testSpecific(with: MTRUnitTestingClusterTestSpecificParams(), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.testStructArgumentRequest(with: MTRUnitTestingClusterTestStructArgumentRequestParams(), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.testStructArrayArgumentRequest(with: MTRUnitTestingClusterTestStructArrayArgumentRequestParams(), completion: { _, err in mtrExpectInvalidState(err) })
    cluster.testUnknownCommand(with: MTRUnitTestingClusterTestUnknownCommandParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.test(with: MTRUnitTestingClusterTestParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.timedInvokeRequest(with: MTRUnitTestingClusterTimedInvokeRequestParams(), completion: { err in mtrExpectInvalidState(err) })
}

func testBaseUnitTestingWriteFailClosed() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRBaseClusterUnitTesting(device: baseDevice, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRBaseClusterUnitTesting init")
        return
    }
    cluster.writeAttributeBitmap16(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeBitmap16(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeBitmap32(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeBitmap32(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeBitmap64(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeBitmap64(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeBitmap8(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeBitmap8(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeBoolean(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeBoolean(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeCharString(withValue: "x", completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeCharString(withValue: "x", params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeClusterErrorBoolean(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeClusterErrorBoolean(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEnum16(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEnum16(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEnum8(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEnum8(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEnumAttr(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEnumAttr(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEpochS(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEpochS(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEpochUs(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeEpochUs(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeFloatDouble(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeFloatDouble(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeFloatSingle(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeFloatSingle(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeGeneralErrorBoolean(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeGeneralErrorBoolean(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt16s(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt16s(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt16u(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt16u(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt24s(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt24s(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt24u(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt24u(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt32s(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt32s(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt32u(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt32u(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt40s(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt40s(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt40u(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt40u(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt48s(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt48s(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt48u(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt48u(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt56s(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt56s(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt56u(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt56u(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt64s(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt64s(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt64u(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt64u(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt8s(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt8s(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt8u(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeInt8u(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeListFabricScoped(withValue: [], completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeListFabricScoped(withValue: [], params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeListInt8u(withValue: [], completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeListInt8u(withValue: [], params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeListLongOctetString(withValue: [], completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeListLongOctetString(withValue: [], params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeListNullablesAndOptionalsStruct(withValue: [], completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeListNullablesAndOptionalsStruct(withValue: [], params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeListOctetString(withValue: [], completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeListOctetString(withValue: [], params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeListStructOctetString(withValue: [], completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeListStructOctetString(withValue: [], params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeLongCharString(withValue: "x", completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeLongCharString(withValue: "x", params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeLongOctetString(withValue: Data(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeLongOctetString(withValue: Data(), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableBitmap16(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableBitmap16(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableBitmap32(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableBitmap32(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableBitmap64(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableBitmap64(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableBitmap8(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableBitmap8(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableBoolean(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableBoolean(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableCharString(withValue: "x", completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableCharString(withValue: "x", params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
}

func testBaseUnitTestingWriteFailClosedGroup2() {
    let controller = MTRDeviceController()
    let device = MTRDevice(nodeID: n(1), controller: controller)
    let baseDevice: MTRBaseDevice = device
    _ = (device, baseDevice)
    guard let cluster = MTRBaseClusterUnitTesting(device: baseDevice, endpointID: n(1), queue: DispatchQueue.global()) else {
        mtrRequire(false, "MTRBaseClusterUnitTesting init")
        return
    }
    cluster.writeAttributeNullableEnum16(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableEnum16(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableEnum8(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableEnum8(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableEnumAttr(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableEnumAttr(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableFloatDouble(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableFloatDouble(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableFloatSingle(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableFloatSingle(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt16s(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt16s(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt16u(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt16u(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt24s(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt24s(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt24u(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt24u(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt32s(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt32s(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt32u(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt32u(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt40s(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt40s(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt40u(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt40u(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt48s(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt48s(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt48u(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt48u(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt56s(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt56s(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt56u(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt56u(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt64s(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt64s(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt64u(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt64u(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt8s(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt8s(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt8u(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableInt8u(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableOctetString(withValue: Data(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableOctetString(withValue: Data(), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableRangeRestrictedInt16s(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableRangeRestrictedInt16s(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableRangeRestrictedInt16u(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableRangeRestrictedInt16u(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableRangeRestrictedInt8s(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableRangeRestrictedInt8s(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableRangeRestrictedInt8u(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableRangeRestrictedInt8u(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableStruct(withValue: MTRUnitTestingClusterSimpleStruct(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeNullableStruct(withValue: MTRUnitTestingClusterSimpleStruct(), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOctetString(withValue: Data(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeOctetString(withValue: Data(), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeRangeRestrictedInt16s(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeRangeRestrictedInt16s(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeRangeRestrictedInt16u(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeRangeRestrictedInt16u(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeRangeRestrictedInt8s(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeRangeRestrictedInt8s(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeRangeRestrictedInt8u(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeRangeRestrictedInt8u(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeStructAttr(withValue: MTRUnitTestingClusterSimpleStruct(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeStructAttr(withValue: MTRUnitTestingClusterSimpleStruct(), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeTimedWriteBoolean(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeTimedWriteBoolean(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeUnsupported(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeUnsupported(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeVendorId(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeVendorId(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeWriteOnlyInt8u(withValue: n(1), completion: { err in mtrExpectInvalidState(err) })
    cluster.writeAttributeWriteOnlyInt8u(withValue: n(1), params: MTRWriteParams(), completion: { err in mtrExpectInvalidState(err) })
}
