// swift-tools-version:5.9
// Generated by Tools/ingest/xcodeproj_to_package.py — do not edit by hand.
// Source project: scratch/ladder-corpus/eidolon/Kiosk.xcodeproj
// Target: Kiosk
import PackageDescription

let package = Package(
    name: "Eidolon",
    platforms: [.macOS(.v11)],
    products: [
        .library(name: "Eidolon", targets: ["Eidolon"]),
    ],
    dependencies: [
        .package(name: "OpenUIKit", path: "../.."),
    ],
    targets: [
        .target(
            name: "EidolonObjC",
            dependencies: [.product(name: "OpenUIKit", package: "OpenUIKit")],
            path: "Sources/EidolonObjC",
            publicHeadersPath: "include"
        ),
        .target(
            name: "Eidolon",
            dependencies: [
                .product(name: "OpenUIKit", package: "OpenUIKit"),
                .product(name: "UIKit", package: "OpenUIKit"),
                .product(name: "SwiftUI", package: "OpenUIKit"),
                .product(name: "DeveloperToolsSupport", package: "OpenUIKit"),
                .product(name: "Symbols", package: "OpenUIKit"),
                .product(name: "Combine", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "os", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "Glean", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "Intents", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "IntentsUI", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "Onboarding", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "Licenses", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "DesignSystem", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "SnapKit", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "Sentry", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "Fuzi", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "libkern", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "WebKit", package: "OpenUIKit"),
                .product(name: "FocusAppServices", package: "OpenUIKit"),
                .product(name: "UIHelpers", package: "OpenUIKit"),
                .product(name: "UIComponents", package: "OpenUIKit"),
                .product(name: "AppShortcuts", package: "OpenUIKit"),
                .product(name: "LocalAuthentication", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "PassKit", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "Network", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "SafariServices", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "StoreKit", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                "EidolonObjC",
            ],
            resources: [
                .copy("Resources"),
            ],
            swiftSettings: [
                .unsafeFlags([
                    "-default-isolation", "MainActor",
                    "-disable-availability-checking",
                ]),
            ]
        ),
    ]
)
