// swift-tools-version:5.9
// Generated by Tools/ingest/xcodeproj_to_package.py — do not edit by hand.
// Source project: scratch/ladder-corpus/eidolon/Kiosk.xcodeproj
// Target: Kiosk
import PackageDescription

#if os(Linux)
let linuxCompatibilityProducts: [Target.Dependency] = [
                .product(name: "libkern", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "StoreKit", package: "OpenUIKit", condition: .when(platforms: [.linux])),
]
#else
let linuxCompatibilityProducts: [Target.Dependency] = []
#endif

let package = Package(
    name: "Eidolon",
    platforms: [.macOS(.v11)],
    products: [
        .library(name: "Eidolon", targets: ["Eidolon"]),
    ],
    dependencies: [
        .package(name: "OpenUIKit", path: "../.."),
    ],
    targets: [
        .target(
            name: "EidolonObjC",
            dependencies: [.product(name: "OpenUIKit", package: "OpenUIKit")],
            path: "Sources/EidolonObjC",
            publicHeadersPath: "include",
            cSettings: [.headerSearchPath("include/Kiosk/App"), .headerSearchPath("include/Kiosk/Supporting Files")]
        ),
        .target(
            name: "Eidolon",
            dependencies: [
                .product(name: "OpenUIKit", package: "OpenUIKit"),
                .product(name: "UIKit", package: "OpenUIKit"),
                .product(name: "SwiftUI", package: "OpenUIKit"),
                .product(name: "DeveloperToolsSupport", package: "OpenUIKit"),
                .product(name: "Symbols", package: "OpenUIKit"),
                .product(name: "Combine", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "os", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "Glean", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "Intents", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "IntentsUI", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "Onboarding", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "Licenses", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "DesignSystem", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "SnapKit", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "Sentry", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "Fuzi", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "WebKit", package: "OpenUIKit"),
                .product(name: "FocusAppServices", package: "OpenUIKit"),
                .product(name: "UIHelpers", package: "OpenUIKit"),
                .product(name: "UIComponents", package: "OpenUIKit"),
                .product(name: "AppShortcuts", package: "OpenUIKit"),
                .product(name: "LocalAuthentication", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "PassKit", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "Network", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "SafariServices", package: "OpenUIKit", condition: .when(platforms: [.linux])),
                .product(name: "ARAnalytics", package: "OpenUIKit", condition: .when(platforms: [.macOS])),
                .product(name: "Action", package: "OpenUIKit", condition: .when(platforms: [.macOS])),
                .product(name: "Alamofire", package: "OpenUIKit", condition: .when(platforms: [.macOS])),
                .product(name: "Keys", package: "OpenUIKit", condition: .when(platforms: [.macOS])),
                .product(name: "Moya", package: "OpenUIKit", condition: .when(platforms: [.macOS])),
                .product(name: "NSObject_Rx", package: "OpenUIKit", condition: .when(platforms: [.macOS])),
                .product(name: "Reachability", package: "OpenUIKit", condition: .when(platforms: [.macOS])),
                .product(name: "Result", package: "OpenUIKit", condition: .when(platforms: [.macOS])),
                .product(name: "RxCocoa", package: "OpenUIKit", condition: .when(platforms: [.macOS])),
                .product(name: "RxOptional", package: "OpenUIKit", condition: .when(platforms: [.macOS])),
                .product(name: "RxSwift", package: "OpenUIKit", condition: .when(platforms: [.macOS])),
                .product(name: "Stripe", package: "OpenUIKit", condition: .when(platforms: [.macOS])),
                .product(name: "SwiftyJSON", package: "OpenUIKit", condition: .when(platforms: [.macOS])),
                "EidolonObjC",
            ] + linuxCompatibilityProducts,
            resources: [
                .copy("Resources"),
            ],
            swiftSettings: [
                .unsafeFlags([
                    "-default-isolation", "MainActor",
                    "-disable-availability-checking",
                ]),
            ]
        ),
    ],
    swiftLanguageVersions: [.version("4")]
)
