import Foundation
import MetalPerformanceShadersGraph

func testEnumRawValues() {
    precondition(MPSGraphDeploymentPlatform.macOS.rawValue == 0)
    precondition(MPSGraphDeploymentPlatform.iOS.rawValue == 1)
    precondition(MPSGraphDeploymentPlatform.tvOS.rawValue == 2)
    precondition(MPSGraphDeploymentPlatform.visionOS.rawValue == 3)
    precondition(MPSGraphDeviceType.metal.rawValue == 0)
    precondition(MPSGraphExecutionStage.completed.rawValue == 0)
    precondition(MPSGraphFFTScalingMode.none.rawValue == 0)
    precondition(MPSGraphFFTScalingMode.size.rawValue == 1)
    precondition(MPSGraphFFTScalingMode.unitary.rawValue == 2)
    precondition(MPSGraphLossReductionType.none.rawValue == 0)
    precondition(MPSGraphLossReductionType.sum.rawValue == 1)
    precondition(MPSGraphLossReductionType.mean.rawValue == 2)
    precondition(MPSGraphLossReductionType.axis == .none)
    precondition(MPSGraphNonMaximumSuppressionCoordinateMode.explicit.rawValue == 0)
    precondition(MPSGraphNonMaximumSuppressionCoordinateMode.cornersWidthFirst.rawValue == 1)
    precondition(MPSGraphNonMaximumSuppressionCoordinateMode.centersHeightFirst.rawValue == 2)
    precondition(MPSGraphNonMaximumSuppressionCoordinateMode.centersWidthFirst.rawValue == 3)
    precondition(MPSGraphOptimization.level0.rawValue == 0)
    precondition(MPSGraphOptimization.level1.rawValue == 1)
    precondition(MPSGraphOptimizationProfile.performance.rawValue == 0)
    precondition(MPSGraphOptimizationProfile.powerEfficiency.rawValue == 1)
    precondition(MPSGraphOptions.none.rawValue == 0)
    precondition(MPSGraphOptions.synchronizeResults.rawValue == 1)
    precondition(MPSGraphOptions.verbose.rawValue == 2)
    precondition(MPSGraphOptions.default == .synchronizeResults)
    precondition(MPSGraphPaddingMode.constant.rawValue == 0)
    precondition(MPSGraphPaddingMode.reflect.rawValue == 1)
    precondition(MPSGraphPaddingMode.symmetric.rawValue == 2)
    precondition(MPSGraphPaddingMode.clampToEdge.rawValue == 3)
    precondition(MPSGraphPaddingMode.zero.rawValue == 4)
    precondition(MPSGraphPaddingMode.periodic.rawValue == 5)
    precondition(MPSGraphPaddingMode.antiPeriodic.rawValue == 6)
    precondition(MPSGraphPaddingStyle.explicit.rawValue == 0)
    precondition(MPSGraphPaddingStyle.TF_VALID.rawValue == 1)
    precondition(MPSGraphPaddingStyle.TF_SAME.rawValue == 2)
    precondition(MPSGraphPaddingStyle.explicitOffset.rawValue == 3)
    precondition(MPSGraphPaddingStyle.ONNX_SAME_LOWER.rawValue == 4)
    precondition(MPSGraphPoolingReturnIndicesMode.none.rawValue == 0)
    precondition(MPSGraphPoolingReturnIndicesMode.globalFlatten1D.rawValue == 1)
    precondition(MPSGraphPoolingReturnIndicesMode.globalFlatten2D.rawValue == 2)
    precondition(MPSGraphPoolingReturnIndicesMode.globalFlatten3D.rawValue == 3)
    precondition(MPSGraphPoolingReturnIndicesMode.globalFlatten4D.rawValue == 4)
    precondition(MPSGraphPoolingReturnIndicesMode.localFlatten1D.rawValue == 5)
    precondition(MPSGraphPoolingReturnIndicesMode.localFlatten2D.rawValue == 6)
    precondition(MPSGraphPoolingReturnIndicesMode.localFlatten3D.rawValue == 7)
    precondition(MPSGraphPoolingReturnIndicesMode.localFlatten4D.rawValue == 8)
    precondition(MPSGraphRNNActivation.none.rawValue == 0)
    precondition(MPSGraphRNNActivation.relu.rawValue == 1)
    precondition(MPSGraphRNNActivation.tanh.rawValue == 2)
    precondition(MPSGraphRNNActivation.sigmoid.rawValue == 3)
    precondition(MPSGraphRNNActivation.hardSigmoid.rawValue == 4)
    precondition(MPSGraphRandomDistribution.uniform.rawValue == 0)
    precondition(MPSGraphRandomDistribution.normal.rawValue == 1)
    precondition(MPSGraphRandomDistribution.truncatedNormal.rawValue == 2)
    precondition(MPSGraphRandomNormalSamplingMethod.invCDF.rawValue == 0)
    precondition(MPSGraphRandomNormalSamplingMethod.boxMuller.rawValue == 1)
    precondition(MPSGraphReducedPrecisionFastMath.none.rawValue == 0)
    precondition(MPSGraphReducedPrecisionFastMath.allowFP16Conv2DWinogradTransformIntermediate.rawValue == 1 << 1)
    precondition(MPSGraphReducedPrecisionFastMath.allowFP16Intermediates == .allowFP16Conv2DWinogradTransformIntermediate)
    precondition(MPSGraphReductionMode.min.rawValue == 0)
    precondition(MPSGraphReductionMode.max.rawValue == 1)
    precondition(MPSGraphReductionMode.sum.rawValue == 2)
    precondition(MPSGraphReductionMode.product.rawValue == 3)
    precondition(MPSGraphReductionMode.argumentMin.rawValue == 4)
    precondition(MPSGraphReductionMode.argumentMax.rawValue == 5)
    precondition(MPSGraphResizeMode.nearest.rawValue == 0)
    precondition(MPSGraphResizeMode.bilinear.rawValue == 1)
    precondition(MPSGraphResizeNearestRoundingMode.roundPreferCeil.rawValue == 0)
    precondition(MPSGraphResizeNearestRoundingMode.roundPreferFloor.rawValue == 1)
    precondition(MPSGraphResizeNearestRoundingMode.ceil.rawValue == 2)
    precondition(MPSGraphResizeNearestRoundingMode.floor.rawValue == 3)
    precondition(MPSGraphResizeNearestRoundingMode.roundToEven.rawValue == 4)
    precondition(MPSGraphResizeNearestRoundingMode.roundToOdd.rawValue == 5)
    precondition(MPSGraphScatterMode.set.rawValue == 0)
    precondition(MPSGraphScatterMode.add.rawValue == 1)
    precondition(MPSGraphScatterMode.sub.rawValue == 2)
    precondition(MPSGraphScatterMode.mul.rawValue == 3)
    precondition(MPSGraphScatterMode.div.rawValue == 4)
    precondition(MPSGraphScatterMode.min.rawValue == 5)
    precondition(MPSGraphScatterMode.max.rawValue == 6)
    precondition(MPSGraphSparseStorageType.COO.rawValue == 0)
    precondition(MPSGraphSparseStorageType.CSC.rawValue == 1)
    precondition(MPSGraphSparseStorageType.CSR.rawValue == 2)
    precondition(MPSGraphTensorNamedDataLayout.NCHW.rawValue == 0)
    precondition(MPSGraphTensorNamedDataLayout.NHWC.rawValue == 1)
    precondition(MPSGraphTensorNamedDataLayout.OIHW.rawValue == 2)
    precondition(MPSGraphTensorNamedDataLayout.HWIO.rawValue == 3)
    precondition(MPSGraphTensorNamedDataLayout.CHW.rawValue == 4)
    precondition(MPSGraphTensorNamedDataLayout.HWC.rawValue == 5)
    precondition(MPSGraphTensorNamedDataLayout.HW.rawValue == 6)
    precondition(MPSGraphTensorNamedDataLayout.NCDHW.rawValue == 7)
    precondition(MPSGraphTensorNamedDataLayout.NDHWC.rawValue == 8)
    precondition(MPSGraphTensorNamedDataLayout.OIDHW.rawValue == 9)
    precondition(MPSGraphTensorNamedDataLayout.DHWIO.rawValue == 10)
}

func testEnumInequality() {
    precondition(MPSGraphDeploymentPlatform.macOS != .iOS)
    precondition(MPSGraphDeviceType.metal == .metal)
    precondition(!(MPSGraphDeviceType.metal != .metal))
    precondition(MPSGraphExecutionStage.completed == .completed)
    precondition(MPSGraphFFTScalingMode.none != .size)
    precondition(MPSGraphLossReductionType.none != .sum)
    precondition(MPSGraphNonMaximumSuppressionCoordinateMode.explicit != .cornersWidthFirst)
    precondition(MPSGraphOptimization.level0 != .level1)
    precondition(MPSGraphOptimizationProfile.performance != .powerEfficiency)
    precondition(MPSGraphOptions.none != .verbose)
    precondition(MPSGraphPaddingMode.constant != .zero)
    precondition(MPSGraphPaddingStyle.explicit != .TF_SAME)
    precondition(MPSGraphPoolingReturnIndicesMode.none != .localFlatten1D)
    precondition(MPSGraphRNNActivation.none != .relu)
    precondition(MPSGraphRandomDistribution.uniform != .normal)
    precondition(MPSGraphRandomNormalSamplingMethod.invCDF != .boxMuller)
    precondition(MPSGraphReducedPrecisionFastMath.none != .allowFP16Intermediates)
    precondition(MPSGraphReductionMode.min != .max)
    precondition(MPSGraphResizeMode.nearest != .bilinear)
    precondition(MPSGraphResizeNearestRoundingMode.ceil != .floor)
    precondition(MPSGraphScatterMode.set != .add)
    precondition(MPSGraphSparseStorageType.COO != .CSR)
    precondition(MPSGraphTensorNamedDataLayout.NCHW != .NHWC)
}

func testEnumHashValue() {
    precondition(MPSGraphDeploymentPlatform.iOS.hashValue == MPSGraphDeploymentPlatform.iOS.hashValue)
    precondition(MPSGraphDeviceType.metal.hashValue == MPSGraphDeviceType.metal.hashValue)
    precondition(MPSGraphExecutionStage.completed.hashValue == MPSGraphExecutionStage.completed.hashValue)
    precondition(MPSGraphFFTScalingMode.size.hashValue == MPSGraphFFTScalingMode.size.hashValue)
    precondition(MPSGraphLossReductionType.mean.hashValue == MPSGraphLossReductionType.mean.hashValue)
    precondition(MPSGraphNonMaximumSuppressionCoordinateMode.explicit.hashValue == MPSGraphNonMaximumSuppressionCoordinateMode.explicit.hashValue)
    precondition(MPSGraphOptimization.level1.hashValue == MPSGraphOptimization.level1.hashValue)
    precondition(MPSGraphOptimizationProfile.performance.hashValue == MPSGraphOptimizationProfile.performance.hashValue)
    precondition(MPSGraphOptions.synchronizeResults.hashValue == MPSGraphOptions.synchronizeResults.hashValue)
    precondition(MPSGraphPaddingMode.reflect.hashValue == MPSGraphPaddingMode.reflect.hashValue)
    precondition(MPSGraphPaddingStyle.TF_VALID.hashValue == MPSGraphPaddingStyle.TF_VALID.hashValue)
    precondition(MPSGraphPoolingReturnIndicesMode.globalFlatten2D.hashValue == MPSGraphPoolingReturnIndicesMode.globalFlatten2D.hashValue)
    precondition(MPSGraphRNNActivation.tanh.hashValue == MPSGraphRNNActivation.tanh.hashValue)
    precondition(MPSGraphRandomDistribution.normal.hashValue == MPSGraphRandomDistribution.normal.hashValue)
    precondition(MPSGraphRandomNormalSamplingMethod.boxMuller.hashValue == MPSGraphRandomNormalSamplingMethod.boxMuller.hashValue)
    precondition(MPSGraphReductionMode.sum.hashValue == MPSGraphReductionMode.sum.hashValue)
    precondition(MPSGraphResizeMode.bilinear.hashValue == MPSGraphResizeMode.bilinear.hashValue)
    precondition(MPSGraphResizeNearestRoundingMode.roundToEven.hashValue == MPSGraphResizeNearestRoundingMode.roundToEven.hashValue)
    precondition(MPSGraphScatterMode.mul.hashValue == MPSGraphScatterMode.mul.hashValue)
    precondition(MPSGraphSparseStorageType.CSC.hashValue == MPSGraphSparseStorageType.CSC.hashValue)
    precondition(MPSGraphTensorNamedDataLayout.HWIO.hashValue == MPSGraphTensorNamedDataLayout.HWIO.hashValue)
}

func testEnumHashInto() {
    func hash<T: Hashable>(_ value: T) -> Int {
        var hasher = Hasher()
        value.hash(into: &hasher)
        return hasher.finalize()
    }
    precondition(hash(MPSGraphDeploymentPlatform.tvOS) == hash(MPSGraphDeploymentPlatform.tvOS))
    precondition(hash(MPSGraphDeviceType.metal) == hash(MPSGraphDeviceType.metal))
    precondition(hash(MPSGraphExecutionStage.completed) == hash(MPSGraphExecutionStage.completed))
    precondition(hash(MPSGraphFFTScalingMode.unitary) == hash(MPSGraphFFTScalingMode.unitary))
    precondition(hash(MPSGraphLossReductionType.sum) == hash(MPSGraphLossReductionType.sum))
    precondition(hash(MPSGraphNonMaximumSuppressionCoordinateMode.centersHeightFirst) == hash(MPSGraphNonMaximumSuppressionCoordinateMode.centersHeightFirst))
    precondition(hash(MPSGraphOptimization.level0) == hash(MPSGraphOptimization.level0))
    precondition(hash(MPSGraphOptimizationProfile.powerEfficiency) == hash(MPSGraphOptimizationProfile.powerEfficiency))
    precondition(hash(MPSGraphOptions.verbose) == hash(MPSGraphOptions.verbose))
    precondition(hash(MPSGraphPaddingMode.periodic) == hash(MPSGraphPaddingMode.periodic))
    precondition(hash(MPSGraphPaddingStyle.explicitOffset) == hash(MPSGraphPaddingStyle.explicitOffset))
    precondition(hash(MPSGraphPoolingReturnIndicesMode.localFlatten4D) == hash(MPSGraphPoolingReturnIndicesMode.localFlatten4D))
    precondition(hash(MPSGraphRNNActivation.hardSigmoid) == hash(MPSGraphRNNActivation.hardSigmoid))
    precondition(hash(MPSGraphRandomDistribution.truncatedNormal) == hash(MPSGraphRandomDistribution.truncatedNormal))
    precondition(hash(MPSGraphRandomNormalSamplingMethod.invCDF) == hash(MPSGraphRandomNormalSamplingMethod.invCDF))
    precondition(hash(MPSGraphReductionMode.product) == hash(MPSGraphReductionMode.product))
    precondition(hash(MPSGraphResizeMode.nearest) == hash(MPSGraphResizeMode.nearest))
    precondition(hash(MPSGraphResizeNearestRoundingMode.roundToOdd) == hash(MPSGraphResizeNearestRoundingMode.roundToOdd))
    precondition(hash(MPSGraphScatterMode.max) == hash(MPSGraphScatterMode.max))
    precondition(hash(MPSGraphSparseStorageType.CSR) == hash(MPSGraphSparseStorageType.CSR))
    precondition(hash(MPSGraphTensorNamedDataLayout.DHWIO) == hash(MPSGraphTensorNamedDataLayout.DHWIO))
}

func testEnumRawValueInits() {
    precondition(MPSGraphDeploymentPlatform(rawValue: 1) == .iOS)
    precondition(MPSGraphDeviceType(rawValue: 0) == .metal)
    precondition(MPSGraphDeviceType(rawValue: 7) == nil)
    precondition(MPSGraphExecutionStage(rawValue: 0) == .completed)
    precondition(MPSGraphFFTScalingMode(rawValue: 2) == .unitary)
    precondition(MPSGraphLossReductionType(rawValue: 2) == .mean)
    precondition(MPSGraphNonMaximumSuppressionCoordinateMode(rawValue: 0) == .explicit)
    precondition(MPSGraphOptimization(rawValue: 1) == .level1)
    precondition(MPSGraphOptimizationProfile(rawValue: 1) == .powerEfficiency)
    precondition(MPSGraphOptions(rawValue: 1) == .synchronizeResults)
    precondition(MPSGraphPaddingMode(rawValue: 4) == .zero)
    precondition(MPSGraphPaddingStyle(rawValue: 2) == .TF_SAME)
    precondition(MPSGraphPoolingReturnIndicesMode(rawValue: 8) == .localFlatten4D)
    precondition(MPSGraphRNNActivation(rawValue: 2) == .tanh)
    precondition(MPSGraphRandomDistribution(rawValue: 1) == .normal)
    precondition(MPSGraphRandomNormalSamplingMethod(rawValue: 1) == .boxMuller)
    precondition(MPSGraphReductionMode(rawValue: 2) == .sum)
    precondition(MPSGraphResizeMode(rawValue: 1) == .bilinear)
    precondition(MPSGraphResizeNearestRoundingMode(rawValue: 3) == .floor)
    precondition(MPSGraphScatterMode(rawValue: 1) == .add)
    precondition(MPSGraphSparseStorageType(rawValue: 0) == .COO)
    precondition(MPSGraphTensorNamedDataLayout(rawValue: 10) == .DHWIO)
    let fast = MPSGraphReducedPrecisionFastMath(rawValue: 1 << 1)
    precondition(fast == .allowFP16Conv2DWinogradTransformIntermediate)
}

func testOptionSetAlgebra() {
    var flags: MPSGraphReducedPrecisionFastMath = []
    precondition(flags.isEmpty)
    precondition(MPSGraphReducedPrecisionFastMath().isEmpty)
    let fromSeq = MPSGraphReducedPrecisionFastMath([.allowFP16Intermediates])
    precondition(fromSeq.contains(.allowFP16Conv2DWinogradTransformIntermediate))
    let inserted = flags.insert(.allowFP16Intermediates)
    precondition(inserted.inserted)
    precondition(flags.contains(.allowFP16Intermediates))
    precondition(flags.isSuperset(of: .allowFP16Intermediates))
    precondition(flags.isSubset(of: .allowFP16Intermediates))
    precondition(!flags.isStrictSubset(of: .allowFP16Intermediates))
    precondition(!flags.isStrictSuperset(of: .none))
    precondition(flags.isDisjoint(with: .none) || flags.contains(.allowFP16Intermediates))
    let unioned = MPSGraphReducedPrecisionFastMath.none.union(.allowFP16Intermediates)
    precondition(unioned.contains(.allowFP16Intermediates))
    let intersection = unioned.intersection(.allowFP16Intermediates)
    precondition(intersection == .allowFP16Intermediates)
    let subtracted = unioned.subtracting(.allowFP16Intermediates)
    precondition(subtracted.isEmpty)
    var mutating = unioned
    mutating.formUnion(.none)
    mutating.formIntersection(.allowFP16Intermediates)
    mutating.formSymmetricDifference(.allowFP16Intermediates)
    precondition(mutating.isEmpty)
    var updateTarget: MPSGraphReducedPrecisionFastMath = []
    _ = updateTarget.update(with: .allowFP16Intermediates)
    _ = updateTarget.remove(.allowFP16Intermediates)
    updateTarget.subtract(.allowFP16Intermediates)
    let symmetric = MPSGraphReducedPrecisionFastMath.allowFP16Intermediates.symmetricDifference(.none)
    precondition(symmetric.contains(.allowFP16Intermediates))
}

func testHandlerTypealiases() {
    let compile: MPSGraphCompilationCompletionHandler = { _, _ in }
    let complete: MPSGraphCompletionHandler = { _, _ in }
    let scheduled: MPSGraphScheduledHandler = { _, _ in }
    let execComplete: MPSGraphExecutableCompletionHandler = { _, _ in }
    let execScheduled: MPSGraphExecutableScheduledHandler = { _, _ in }
    let dep: MPSGraphControlFlowDependencyBlock = { [] }
    let body: MPSGraphForLoopBodyBlock = { _, args in args }
    let branch: MPSGraphIfThenElseBlock = { [] }
    let after: MPSGraphWhileAfterBlock = { $0 }
    let before: MPSGraphWhileBeforeBlock = { inputs, cond in
        cond.add(true)
        return inputs[0]
    }
    _ = compile
    _ = complete
    _ = scheduled
    _ = execComplete
    _ = execScheduled
    _ = dep
    _ = body
    _ = branch
    _ = after
    _ = before
}
