import Foundation
import Intents

private func wave12CheckEnumWitness<T: RawRepresentable & Hashable>(_ type: T.Type) where T.RawValue: FixedWidthInteger {
    let raw = (-10_000...10_000).lazy.compactMap(T.RawValue.init(exactly:)).first { T(rawValue: $0) != nil }
    guard let raw, let first = T(rawValue: raw), let second = T(rawValue: raw) else {
        preconditionFailure("enum \(T.self) must expose a documented-range raw value")
    }
    precondition(first == second)
    precondition(!(first != second))
    precondition(Set([first]).contains(second))
    var hasher = Hasher()
    first.hash(into: &hasher)
    _ = hasher.finalize()
    precondition(first.hashValue == second.hashValue)
}

func testGeneratedEnumEqualityAndHashingWitnesses() {
    wave12CheckEnumWitness(INAccountType.self)
    wave12CheckEnumWitness(INActivateCarSignalIntentResponseCode.self)
    wave12CheckEnumWitness(INAddMediaMediaDestinationUnsupportedReason.self)
    wave12CheckEnumWitness(INAddTasksIntentResponseCode.self)
    wave12CheckEnumWitness(INAddTasksTargetTaskListConfirmationReason.self)
    wave12CheckEnumWitness(INAddTasksTemporalEventTriggerUnsupportedReason.self)
    wave12CheckEnumWitness(INAmountType.self)
    wave12CheckEnumWitness(INAnswerCallIntentResponseCode.self)
    wave12CheckEnumWitness(INAppendToNoteIntentResponseCode.self)
    wave12CheckEnumWitness(INBalanceType.self)
    wave12CheckEnumWitness(INBillType.self)
    wave12CheckEnumWitness(INBookRestaurantReservationIntentCode.self)
    wave12CheckEnumWitness(INCallAudioRoute.self)
    wave12CheckEnumWitness(INCallCapability.self)
    wave12CheckEnumWitness(INCallDestinationType.self)
    wave12CheckEnumWitness(INCallRecordType.self)
    wave12CheckEnumWitness(INCancelRideIntentResponseCode.self)
    wave12CheckEnumWitness(INCancelWorkoutIntentResponseCode.self)
    wave12CheckEnumWitness(INCarAirCirculationMode.self)
    wave12CheckEnumWitness(INCarAudioSource.self)
    wave12CheckEnumWitness(INCarDefroster.self)
    wave12CheckEnumWitness(INCarSeat.self)
    wave12CheckEnumWitness(INCarSignalOptions.self)
    wave12CheckEnumWitness(INConditionalOperator.self)
    wave12CheckEnumWitness(INDateSearchType.self)
    wave12CheckEnumWitness(INDayOfWeekOptions.self)
    wave12CheckEnumWitness(INDeleteTasksTaskListUnsupportedReason.self)
    wave12CheckEnumWitness(INDeleteTasksTaskUnsupportedReason.self)
    wave12CheckEnumWitness(INEditMessageIntentResponseCode.self)
    wave12CheckEnumWitness(INEndWorkoutIntentResponseCode.self)
    wave12CheckEnumWitness(INFocusStatusAuthorizationStatus.self)
    wave12CheckEnumWitness(INGetCarLockStatusIntentResponseCode.self)
    wave12CheckEnumWitness(INGetCarPowerLevelStatusIntentResponseCode.self)
    wave12CheckEnumWitness(INGetReservationDetailsIntentResponseCode.self)
    wave12CheckEnumWitness(INGetRestaurantGuestIntentResponseCode.self)
    wave12CheckEnumWitness(INGetRideStatusIntentResponseCode.self)
    wave12CheckEnumWitness(INGetVisualCodeIntentResponseCode.self)
    wave12CheckEnumWitness(INHangUpCallIntentResponseCode.self)
    wave12CheckEnumWitness(INIntentError.Code.self)
    wave12CheckEnumWitness(INIntentHandlingStatus.self)
    wave12CheckEnumWitness(INInteractionDirection.self)
    wave12CheckEnumWitness(INListCarsIntentResponseCode.self)
    wave12CheckEnumWitness(INListRideOptionsIntentResponseCode.self)
    wave12CheckEnumWitness(INLocationSearchType.self)
    wave12CheckEnumWitness(INMediaAffinityType.self)
    wave12CheckEnumWitness(INMediaItemType.self)
    wave12CheckEnumWitness(INMediaReference.self)
    wave12CheckEnumWitness(INMediaSortOrder.self)
    wave12CheckEnumWitness(INMediaUserContext.SubscriptionStatus.self)
    wave12CheckEnumWitness(INMessageAttribute.self)
    wave12CheckEnumWitness(INMessageReactionType.self)
    wave12CheckEnumWitness(INMessageType.self)
    wave12CheckEnumWitness(INNoteContentType.self)
    wave12CheckEnumWitness(INOutgoingMessageType.self)
    wave12CheckEnumWitness(INPauseWorkoutIntentResponseCode.self)
    wave12CheckEnumWitness(INPayBillIntentResponseCode.self)
    wave12CheckEnumWitness(INPaymentMethodType.self)
    wave12CheckEnumWitness(INPaymentStatus.self)
    wave12CheckEnumWitness(INPersonHandleType.self)
    wave12CheckEnumWitness(INPhotoAttributeOptions.self)
    wave12CheckEnumWitness(INPlayMediaMediaItemUnsupportedReason.self)
    wave12CheckEnumWitness(INPlayMediaPlaybackSpeedUnsupportedReason.self)
    wave12CheckEnumWitness(INPlaybackQueueLocation.self)
    wave12CheckEnumWitness(INPlaybackRepeatMode.self)
    wave12CheckEnumWitness(INRadioType.self)
    wave12CheckEnumWitness(INRecurrenceFrequency.self)
    wave12CheckEnumWitness(INRelativeReference.self)
    wave12CheckEnumWitness(INRelativeSetting.self)
    wave12CheckEnumWitness(INRelevantShortcutRole.self)
    wave12CheckEnumWitness(INRequestPaymentCurrencyAmountUnsupportedReason.self)
    wave12CheckEnumWitness(INRequestPaymentPayerUnsupportedReason.self)
    wave12CheckEnumWitness(INRequestRideIntentResponseCode.self)
    wave12CheckEnumWitness(INReservationActionType.self)
    wave12CheckEnumWitness(INReservationStatus.self)
    wave12CheckEnumWitness(INRestaurantReservationUserBookingStatus.self)
    wave12CheckEnumWitness(INResumeWorkoutIntentResponseCode.self)
    wave12CheckEnumWitness(INRideFeedbackTypeOptions.self)
    wave12CheckEnumWitness(INRidePhase.self)
    wave12CheckEnumWitness(INSaveProfileInCarIntentResponseCode.self)
    wave12CheckEnumWitness(INSearchCallHistoryIntentResponseCode.self)
    wave12CheckEnumWitness(INSearchForAccountsIntentResponseCode.self)
    wave12CheckEnumWitness(INSearchForBillsIntentResponseCode.self)
    wave12CheckEnumWitness(INSearchForMediaIntentResponseCode.self)
    wave12CheckEnumWitness(INSearchForMediaMediaItemUnsupportedReason.self)
    wave12CheckEnumWitness(INSearchForNotebookItemsIntentResponseCode.self)
    wave12CheckEnumWitness(INSearchForPhotosIntentResponseCode.self)
    wave12CheckEnumWitness(INSendMessageIntentResponseCode.self)
    wave12CheckEnumWitness(INSendPaymentCurrencyAmountUnsupportedReason.self)
    wave12CheckEnumWitness(INSendPaymentPayeeUnsupportedReason.self)
    wave12CheckEnumWitness(INSendRideFeedbackIntentResponseCode.self)
    wave12CheckEnumWitness(INSetAudioSourceInCarIntentResponseCode.self)
    wave12CheckEnumWitness(INSetCarLockStatusIntentResponseCode.self)
    wave12CheckEnumWitness(INSetClimateSettingsInCarIntentResponseCode.self)
    wave12CheckEnumWitness(INSetMessageAttributeIntentResponseCode.self)
    wave12CheckEnumWitness(INSetTaskAttributeIntentResponseCode.self)
    wave12CheckEnumWitness(INSetTaskAttributeTemporalEventTriggerUnsupportedReason.self)
    wave12CheckEnumWitness(INShareFocusStatusIntentResponseCode.self)
    wave12CheckEnumWitness(INShortcutAvailabilityOptions.self)
    wave12CheckEnumWitness(INSiriAuthorizationStatus.self)
    wave12CheckEnumWitness(INSnoozeTasksIntentResponseCode.self)
    wave12CheckEnumWitness(INSnoozeTasksTaskUnsupportedReason.self)
    wave12CheckEnumWitness(INSortType.self)
    wave12CheckEnumWitness(INSpatialEvent.self)
    wave12CheckEnumWitness(INStartAudioCallIntentResponseCode.self)
    wave12CheckEnumWitness(INStartCallCallCapabilityUnsupportedReason.self)
    wave12CheckEnumWitness(INStartCallCallRecordToCallBackUnsupportedReason.self)
    wave12CheckEnumWitness(INStartCallContactUnsupportedReason.self)
    wave12CheckEnumWitness(INStartCallIntentResponseCode.self)
    wave12CheckEnumWitness(INStartPhotoPlaybackIntentResponseCode.self)
    wave12CheckEnumWitness(INStartVideoCallIntentResponseCode.self)
    wave12CheckEnumWitness(INSticker.StickerType.self)
    wave12CheckEnumWitness(INTaskStatus.self)
    wave12CheckEnumWitness(INTaskType.self)
    wave12CheckEnumWitness(INTicketedEventCategory.self)
    wave12CheckEnumWitness(INTransferMoneyIntentResponseCode.self)
    wave12CheckEnumWitness(INUnsendMessagesIntentResponseCode.self)
    wave12CheckEnumWitness(INUpcomingMediaPredictionMode.self)
    wave12CheckEnumWitness(INUpdateMediaAffinityIntentResponseCode.self)
    wave12CheckEnumWitness(INUpdateMediaAffinityMediaItemUnsupportedReason.self)
    wave12CheckEnumWitness(INVisualCodeType.self)
    wave12CheckEnumWitness(INVocabularyStringType.self)
}

func testAirlineAirportAndGateRetainedProperties() {
    let airline = INAirline(name: "OpenAir", iataCode: "OA", icaoCode: "OAI")
    precondition(airline.iataCode == "OA")
    precondition(airline.icaoCode == "OAI")

    let airport = INAirport(name: "San Francisco", iataCode: "SFO", icaoCode: "KSFO")
    precondition(airport.name == "San Francisco")
    precondition(airport.icaoCode == "KSFO")

    let gate = INAirportGate(airport: airport, terminal: "2", gate: "G1")
    precondition(gate.airport === airport)
    precondition(gate.terminal == "2")
}

func testBillPayeeDesignatedValues() {
    let nickname = INSpeakableString(spokenPhrase: "Home")
    let organization = INSpeakableString(spokenPhrase: "Open Utilities")
    guard let payee = INBillPayee(
        nickname: nickname,
        number: "account-42",
        organizationName: organization
    ) else {
        preconditionFailure("valid bill payee values must initialize")
    }
    precondition(payee.nickname === nickname)
    precondition(payee.accountNumber == "account-42")
    precondition(payee.organizationName === organization)
}
