@_spi(PDFKitTesting) import PDFKit
import Foundation

func testAccessPermissionsRawValues() {
    pdfkitExpect(PDFAccessPermissions.allowsLowQualityPrinting.rawValue == 1 << 0, "low print")
    pdfkitExpect(PDFAccessPermissions.allowsHighQualityPrinting.rawValue == 1 << 1, "high print")
    pdfkitExpect(PDFAccessPermissions.allowsDocumentChanges.rawValue == 1 << 2, "changes")
    pdfkitExpect(PDFAccessPermissions.allowsDocumentAssembly.rawValue == 1 << 3, "assembly")
    pdfkitExpect(PDFAccessPermissions.allowsContentCopying.rawValue == 1 << 4, "copy")
    pdfkitExpect(PDFAccessPermissions.allowsContentAccessibility.rawValue == 1 << 5, "a11y")
    pdfkitExpect(PDFAccessPermissions.allowsCommenting.rawValue == 1 << 6, "comment")
    pdfkitExpect(PDFAccessPermissions.allowsFormFieldEntry.rawValue == 1 << 7, "form")
    let combined = PDFAccessPermissions(rawValue: (1 << 0) | (1 << 6))
    pdfkitExpect(combined.contains(.allowsLowQualityPrinting), "combined low")
    pdfkitExpect(combined.contains(.allowsCommenting), "combined comment")
    pdfkitExpect(combined != .allowsCommenting, "permissions !=")
    pdfkitHashProbe(PDFAccessPermissions.allowsContentCopying)
    _ = PDFAccessPermissions.allowsCommenting
}

func testActionNamedNameRawValues() {
    pdfkitExpect(PDFActionNamedName.none.rawValue == 0, "none")
    pdfkitExpect(PDFActionNamedName.nextPage.rawValue == 1, "next")
    pdfkitExpect(PDFActionNamedName.previousPage.rawValue == 2, "prev")
    pdfkitExpect(PDFActionNamedName.firstPage.rawValue == 3, "first")
    pdfkitExpect(PDFActionNamedName.lastPage.rawValue == 4, "last")
    pdfkitExpect(PDFActionNamedName.goBack.rawValue == 5, "back")
    pdfkitExpect(PDFActionNamedName.goForward.rawValue == 6, "forward")
    pdfkitExpect(PDFActionNamedName.goToPage.rawValue == 7, "goto")
    pdfkitExpect(PDFActionNamedName.find.rawValue == 8, "find")
    pdfkitExpect(PDFActionNamedName.print.rawValue == 9, "print")
    pdfkitExpect(PDFActionNamedName.zoomIn.rawValue == 10, "zoomin")
    pdfkitExpect(PDFActionNamedName.zoomOut.rawValue == 11, "zoomout")
    pdfkitExpect(PDFActionNamedName(rawValue: 8) == .find, "raw init find")
    pdfkitExpect(PDFActionNamedName.nextPage != .previousPage, "named !=")
    pdfkitHashProbe(PDFActionNamedName.find)
}

func testAreaOfInterestOptionSetAlgebra() {
    var area = PDFAreaOfInterest()
    pdfkitExpect(area.isEmpty, "empty")
    area = PDFAreaOfInterest(rawValue: 1 << 0)
    pdfkitExpect(area.contains(.pageArea), "contains page")
    let fromLiteral: PDFAreaOfInterest = [.pageArea, .annotationArea]
    pdfkitExpect(fromLiteral.contains(.annotationArea), "array literal")
    _ = PDFAreaOfInterest([.textArea])
    pdfkitExpect(PDFAreaOfInterest.pageArea.union(.annotationArea).contains(.annotationArea), "union")
    pdfkitExpect(PDFAreaOfInterest.pageArea.intersection(.pageArea).contains(.pageArea), "intersection")
    pdfkitExpect(!PDFAreaOfInterest.pageArea.intersection(.textArea).contains(.textArea), "empty intersection")
    pdfkitExpect(
        PDFAreaOfInterest.pageArea.symmetricDifference(.annotationArea).contains(.annotationArea),
        "symmetricDifference"
    )
    pdfkitExpect(PDFAreaOfInterest.anyArea.contains(.pageArea), "any")
    pdfkitExpect(PDFAreaOfInterest.pageArea.isSubset(of: .anyArea), "subset")
    pdfkitExpect(PDFAreaOfInterest.anyArea.isSuperset(of: .pageArea), "superset")
    pdfkitExpect(PDFAreaOfInterest.pageArea.isStrictSubset(of: .anyArea), "strict subset")
    pdfkitExpect(PDFAreaOfInterest.anyArea.isStrictSuperset(of: .pageArea), "strict superset")
    pdfkitExpect(PDFAreaOfInterest.pageArea.isDisjoint(with: .textArea), "disjoint")
    pdfkitExpect(PDFAreaOfInterest.pageArea.subtracting(.pageArea).isEmpty, "subtracting")
    var mutable = PDFAreaOfInterest.pageArea
    mutable.formUnion(.linkArea)
    pdfkitExpect(mutable.contains(.linkArea), "formUnion")
    mutable.formIntersection(.pageArea)
    pdfkitExpect(!mutable.contains(.linkArea), "formIntersection")
    mutable.formSymmetricDifference(.annotationArea)
    pdfkitExpect(mutable.contains(.annotationArea), "formSymmetricDifference")
    mutable.subtract(.annotationArea)
    _ = mutable.insert(.controlArea)
    _ = mutable.remove(.controlArea)
    _ = mutable.update(with: .iconArea)
    pdfkitExpect(PDFAreaOfInterest.controlArea.rawValue != 0, "control")
    pdfkitExpect(PDFAreaOfInterest.iconArea.rawValue != 0, "icon")
    pdfkitExpect(PDFAreaOfInterest.imageArea.rawValue != 0, "image")
    pdfkitExpect(PDFAreaOfInterest.linkArea.rawValue != 0, "link")
    pdfkitExpect(PDFAreaOfInterest.popupArea.rawValue != 0, "popup")
    pdfkitExpect(PDFAreaOfInterest.textArea.rawValue != 0, "text")
    pdfkitExpect(PDFAreaOfInterest.textFieldArea.rawValue != 0, "text field")
    pdfkitExpect(PDFAreaOfInterest.pageArea != .annotationArea, "area !=")
}

func testDisplayAndLayoutEnumRawValues() {
    pdfkitExpect(PDFDisplayBox.mediaBox.rawValue == 0, "media")
    pdfkitExpect(PDFDisplayBox.cropBox.rawValue == 1, "crop")
    pdfkitExpect(PDFDisplayBox.bleedBox.rawValue == 2, "bleed")
    pdfkitExpect(PDFDisplayBox.trimBox.rawValue == 3, "trim")
    pdfkitExpect(PDFDisplayBox.artBox.rawValue == 4, "art")
    pdfkitExpect(PDFDisplayBox(rawValue: 0) == .mediaBox, "media init")
    pdfkitExpect(PDFDisplayBox.cropBox != .mediaBox, "box !=")
    pdfkitHashProbe(PDFDisplayBox.cropBox)

    pdfkitExpect(PDFDisplayDirection.vertical.rawValue == 0, "vertical")
    pdfkitExpect(PDFDisplayDirection.horizontal.rawValue == 1, "horizontal")
    pdfkitExpect(PDFDisplayDirection(rawValue: 1) == .horizontal, "dir init")
    pdfkitExpect(PDFDisplayDirection.vertical != .horizontal, "dir !=")
    pdfkitHashProbe(PDFDisplayDirection.horizontal)

    pdfkitExpect(PDFDisplayMode.singlePage.rawValue == 0, "single")
    pdfkitExpect(PDFDisplayMode.singlePageContinuous.rawValue == 1, "spc")
    pdfkitExpect(PDFDisplayMode.twoUp.rawValue == 2, "two")
    pdfkitExpect(PDFDisplayMode.twoUpContinuous.rawValue == 3, "tuc")
    pdfkitExpect(PDFDisplayMode(rawValue: 1) == .singlePageContinuous, "mode init")
    pdfkitExpect(PDFDisplayMode.twoUp != .singlePage, "mode !=")
    pdfkitHashProbe(PDFDisplayMode.twoUp)

    pdfkitExpect(PDFThumbnailLayoutMode.vertical.rawValue == 0, "thumb v")
    pdfkitExpect(PDFThumbnailLayoutMode.horizontal.rawValue == 1, "thumb h")
    pdfkitExpect(PDFThumbnailLayoutMode(rawValue: 0) == .vertical, "thumb init")
    pdfkitExpect(PDFThumbnailLayoutMode.vertical != .horizontal, "thumb !=")
    pdfkitHashProbe(PDFThumbnailLayoutMode.horizontal)

    pdfkitExpect(PDFInterpolationQuality.none.rawValue == 0, "iq none")
    pdfkitExpect(PDFInterpolationQuality.low.rawValue == 1, "iq low")
    pdfkitExpect(PDFInterpolationQuality.high.rawValue == 2, "iq high")
    pdfkitExpect(PDFInterpolationQuality(rawValue: 2) == .high, "iq init")
    pdfkitExpect(PDFInterpolationQuality.low != .high, "iq !=")
    pdfkitHashProbe(PDFInterpolationQuality.high)

    pdfkitExpect(PDFDocumentPermissions.none.rawValue == 0, "perms none")
    pdfkitExpect(PDFDocumentPermissions.user.rawValue == 1, "perms user")
    pdfkitExpect(PDFDocumentPermissions.owner.rawValue == 2, "perms owner")
    pdfkitExpect(PDFDocumentPermissions(rawValue: 1) == .user, "perms init")
    pdfkitExpect(PDFDocumentPermissions.user != .owner, "perms !=")
    pdfkitHashProbe(PDFDocumentPermissions.owner)

    pdfkitExpect(PDFSelectionGranularity.character.rawValue == 0, "gran char")
    pdfkitExpect(PDFSelectionGranularity.word.rawValue == 1, "gran word")
    pdfkitExpect(PDFSelectionGranularity.line.rawValue == 2, "gran line")
    pdfkitExpect(PDFSelectionGranularity(rawValue: 1) == .word, "gran init")
    pdfkitExpect(PDFSelectionGranularity.word != .line, "gran !=")
    pdfkitHashProbe(PDFSelectionGranularity.word)
}

func testBorderLineMarkupWidgetEnumRawValues() {
    pdfkitExpect(PDFBorderStyle.solid.rawValue == 0, "solid")
    pdfkitExpect(PDFBorderStyle.dashed.rawValue == 1, "dashed")
    pdfkitExpect(PDFBorderStyle.beveled.rawValue == 2, "beveled")
    pdfkitExpect(PDFBorderStyle.inset.rawValue == 3, "inset")
    pdfkitExpect(PDFBorderStyle.underline.rawValue == 4, "underline")
    pdfkitExpect(PDFBorderStyle(rawValue: 1) == .dashed, "border init")
    pdfkitExpect(PDFBorderStyle.solid != .dashed, "border !=")
    pdfkitHashProbe(PDFBorderStyle.dashed)

    pdfkitExpect(PDFLineStyle.none.rawValue == 0, "ls none")
    pdfkitExpect(PDFLineStyle.square.rawValue == 1, "ls square")
    pdfkitExpect(PDFLineStyle.circle.rawValue == 2, "ls circle")
    pdfkitExpect(PDFLineStyle.diamond.rawValue == 3, "ls diamond")
    pdfkitExpect(PDFLineStyle.openArrow.rawValue == 4, "ls open")
    pdfkitExpect(PDFLineStyle.closedArrow.rawValue == 5, "ls closed")
    pdfkitExpect(PDFLineStyle(rawValue: 2) == .circle, "ls init")
    pdfkitExpect(PDFLineStyle.square != .circle, "ls !=")
    pdfkitHashProbe(PDFLineStyle.diamond)

    pdfkitExpect(PDFMarkupType.highlight.rawValue == 0, "mu hl")
    pdfkitExpect(PDFMarkupType.strikeOut.rawValue == 1, "mu strike")
    pdfkitExpect(PDFMarkupType.underline.rawValue == 2, "mu ul")
    pdfkitExpect(PDFMarkupType.redact.rawValue == 3, "mu redact")
    pdfkitExpect(PDFMarkupType(rawValue: 3) == .redact, "mu init")
    pdfkitExpect(PDFMarkupType.highlight != .redact, "mu !=")
    pdfkitHashProbe(PDFMarkupType.underline)

    pdfkitExpect(PDFTextAnnotationIconType.comment.rawValue == 0, "icon comment")
    pdfkitExpect(PDFTextAnnotationIconType.key.rawValue == 1, "icon key")
    pdfkitExpect(PDFTextAnnotationIconType.note.rawValue == 2, "icon note")
    pdfkitExpect(PDFTextAnnotationIconType.help.rawValue == 3, "icon help")
    pdfkitExpect(PDFTextAnnotationIconType.newParagraph.rawValue == 4, "icon np")
    pdfkitExpect(PDFTextAnnotationIconType.paragraph.rawValue == 5, "icon p")
    pdfkitExpect(PDFTextAnnotationIconType.insert.rawValue == 6, "icon insert")
    pdfkitExpect(PDFTextAnnotationIconType(rawValue: 0) == .comment, "icon init")
    pdfkitExpect(PDFTextAnnotationIconType.comment != .note, "icon !=")
    pdfkitHashProbe(PDFTextAnnotationIconType.help)

    pdfkitExpect(PDFWidgetCellState.mixedState.rawValue == -1, "mixed")
    pdfkitExpect(PDFWidgetCellState.offState.rawValue == 0, "off")
    pdfkitExpect(PDFWidgetCellState.onState.rawValue == 1, "on")
    pdfkitExpect(PDFWidgetCellState(rawValue: 0) == .offState, "cell init")
    pdfkitExpect(PDFWidgetCellState.onState != .offState, "cell !=")
    pdfkitHashProbe(PDFWidgetCellState.onState)

    pdfkitExpect(PDFWidgetControlType.unknownControl.rawValue == -1, "unknown")
    pdfkitExpect(PDFWidgetControlType.pushButtonControl.rawValue == 0, "push")
    pdfkitExpect(PDFWidgetControlType.radioButtonControl.rawValue == 1, "radio")
    pdfkitExpect(PDFWidgetControlType.checkBoxControl.rawValue == 2, "check")
    pdfkitExpect(PDFWidgetControlType(rawValue: 2) == .checkBoxControl, "widget init")
    pdfkitExpect(PDFWidgetControlType.radioButtonControl != .checkBoxControl, "widget !=")
    pdfkitHashProbe(PDFWidgetControlType.checkBoxControl)
}

func testTypedStringKeysAndDestinations() {
    pdfkitExpect(kPDFDestinationUnspecifiedValue < 0, "unspecified sentinel")
    pdfkitExpect(PDFDocumentFoundSelectionKey == "PDFDocumentFoundSelection", "found key")
    pdfkitExpect(PDFDocumentPageIndexKey == "PDFDocumentPageIndex", "page index key")

    pdfkitExpect(PDFDocumentAttribute.titleAttribute.rawValue == "Title", "title")
    pdfkitExpect(PDFDocumentAttribute.authorAttribute.rawValue == "Author", "author")
    pdfkitExpect(PDFDocumentAttribute.subjectAttribute.rawValue == "Subject", "subject")
    pdfkitExpect(PDFDocumentAttribute.creatorAttribute.rawValue == "Creator", "creator")
    pdfkitExpect(PDFDocumentAttribute.producerAttribute.rawValue == "Producer", "producer")
    pdfkitExpect(PDFDocumentAttribute.creationDateAttribute.rawValue == "CreationDate", "creation")
    pdfkitExpect(PDFDocumentAttribute.modificationDateAttribute.rawValue == "ModDate", "mod")
    pdfkitExpect(PDFDocumentAttribute.keywordsAttribute.rawValue == "Keywords", "keywords")
    pdfkitExpect(PDFDocumentAttribute(rawValue: "Title") == .titleAttribute, "attr init")
    pdfkitExpect(PDFDocumentAttribute.titleAttribute != .authorAttribute, "attr !=")
    pdfkitHashProbe(PDFDocumentAttribute.titleAttribute)

    pdfkitExpect(PDFDocumentWriteOption.ownerPasswordOption.rawValue.contains("OwnerPassword"), "owner")
    pdfkitExpect(PDFDocumentWriteOption.userPasswordOption.rawValue.contains("UserPassword"), "user")
    pdfkitExpect(PDFDocumentWriteOption.accessPermissionsOption.rawValue.contains("AccessPermissions"), "perms")
    pdfkitExpect(PDFDocumentWriteOption.burnInAnnotationsOption.rawValue.contains("BurnIn"), "burn")
    pdfkitExpect(PDFDocumentWriteOption.saveTextFromOCROption.rawValue.contains("OCR"), "ocr")
    pdfkitExpect(PDFDocumentWriteOption.saveImagesAsJPEGOption.rawValue.contains("JPEG"), "jpeg")
    pdfkitExpect(PDFDocumentWriteOption.optimizeImagesForScreenOption.rawValue.contains("Screen"), "screen")
    pdfkitExpect(PDFDocumentWriteOption(rawValue: "PDFDocumentOwnerPassword") == .ownerPasswordOption, "write init")
    pdfkitExpect(PDFDocumentWriteOption.ownerPasswordOption != .userPasswordOption, "write !=")
    pdfkitHashProbe(PDFDocumentWriteOption.userPasswordOption)

    pdfkitExpect(PDFPage.ImageInitializationOption.mediaBox.rawValue.contains("MediaBox"), "img media")
    pdfkitExpect(PDFPage.ImageInitializationOption.rotation.rawValue.contains("Rotation"), "img rot")
    pdfkitExpect(PDFPage.ImageInitializationOption.upscaleIfSmaller.rawValue.contains("Upscale"), "img up")
    pdfkitExpect(PDFPage.ImageInitializationOption.compressionQuality.rawValue.contains("Compression"), "img cq")
    pdfkitExpect(
        PDFPage.ImageInitializationOption(rawValue: "PDFPageImageInitializationOptionMediaBox") == .mediaBox,
        "img init"
    )
    pdfkitExpect(
        PDFPage.ImageInitializationOption.mediaBox != .rotation,
        "img !="
    )
    pdfkitHashProbe(PDFPage.ImageInitializationOption.rotation)

    pdfkitExpect(PDFBorderKey.lineWidth.rawValue == "/W", "border W")
    pdfkitExpect(PDFBorderKey.style.rawValue == "/S", "border S")
    pdfkitExpect(PDFBorderKey.dashPattern.rawValue == "/D", "border D")
    pdfkitExpect(PDFBorderKey(rawValue: "/W") == .lineWidth, "border key init")
    pdfkitExpect(PDFBorderKey.lineWidth != .style, "border key !=")
    pdfkitHashProbe(PDFBorderKey.style)

    pdfkitExpect(PDFAppearanceCharacteristicsKey.backgroundColor.rawValue == "/BG", "ack bg")
    pdfkitExpect(PDFAppearanceCharacteristicsKey.borderColor.rawValue == "/BC", "ack bc")
    pdfkitExpect(PDFAppearanceCharacteristicsKey.rotation.rawValue == "/R", "ack r")
    pdfkitExpect(PDFAppearanceCharacteristicsKey.caption.rawValue == "/CA", "ack ca")
    pdfkitExpect(PDFAppearanceCharacteristicsKey.rolloverCaption.rawValue == "/RC", "ack rc")
    pdfkitExpect(PDFAppearanceCharacteristicsKey.downCaption.rawValue == "/AC", "ack ac")
    pdfkitExpect(PDFAppearanceCharacteristicsKey(rawValue: "/CA") == .caption, "ack init")
    pdfkitExpect(PDFAppearanceCharacteristicsKey.caption != .downCaption, "ack !=")
    pdfkitHashProbe(PDFAppearanceCharacteristicsKey.caption)
}

func testNotificationNames() {
    pdfkitExpect(Notification.Name.PDFDocumentDidBeginFind.rawValue.contains("PDFDocumentDidBeginFind"), "begin find")
    pdfkitExpect(Notification.Name.PDFDocumentDidEndFind.rawValue.contains("PDFDocumentDidEndFind"), "end find")
    pdfkitExpect(Notification.Name.PDFDocumentDidBeginPageFind.rawValue.contains("BeginPageFind"), "begin page find")
    pdfkitExpect(Notification.Name.PDFDocumentDidEndPageFind.rawValue.contains("EndPageFind"), "end page find")
    pdfkitExpect(Notification.Name.PDFDocumentDidFindMatch.rawValue.contains("DidFindMatch"), "find match")
    pdfkitExpect(Notification.Name.PDFDocumentDidUnlock.rawValue.contains("DidUnlock"), "unlock")
    pdfkitExpect(Notification.Name.PDFDocumentDidBeginWrite.rawValue.contains("BeginWrite"), "begin write")
    pdfkitExpect(Notification.Name.PDFDocumentDidEndWrite.rawValue.contains("EndWrite"), "end write")
    pdfkitExpect(Notification.Name.PDFDocumentDidBeginPageWrite.rawValue.contains("BeginPageWrite"), "begin page write")
    pdfkitExpect(Notification.Name.PDFDocumentDidEndPageWrite.rawValue.contains("EndPageWrite"), "end page write")
    pdfkitExpect(Notification.Name.PDFViewDocumentChanged.rawValue.contains("PDFViewDocumentChanged"), "doc changed")
    pdfkitExpect(Notification.Name.PDFViewPageChanged.rawValue.contains("PDFViewPageChanged"), "page changed")
    pdfkitExpect(Notification.Name.PDFViewScaleChanged.rawValue.contains("ScaleChanged"), "scale")
    pdfkitExpect(Notification.Name.PDFViewSelectionChanged.rawValue.contains("SelectionChanged"), "sel")
    pdfkitExpect(Notification.Name.PDFViewDisplayBoxChanged.rawValue.contains("DisplayBox"), "box")
    pdfkitExpect(Notification.Name.PDFViewDisplayModeChanged.rawValue.contains("DisplayMode"), "mode")
    pdfkitExpect(Notification.Name.PDFViewChangedHistory.rawValue.contains("ChangedHistory"), "history")
    pdfkitExpect(Notification.Name.PDFViewVisiblePagesChanged.rawValue.contains("VisiblePages"), "visible")
    pdfkitExpect(Notification.Name.PDFViewCopyPermission.rawValue.contains("CopyPermission"), "copy")
    pdfkitExpect(Notification.Name.PDFViewPrintPermission.rawValue.contains("PrintPermission"), "print")
    pdfkitExpect(Notification.Name.PDFViewAnnotationHit.rawValue.contains("AnnotationHit"), "hit")
    pdfkitExpect(Notification.Name.PDFViewAnnotationWillHit.rawValue.contains("AnnotationWillHit"), "will hit")
    pdfkitExpect(Notification.Name.PDFThumbnailViewDocumentEdited.rawValue.contains("ThumbnailViewDocumentEdited"), "thumbs")
}
